Azure/azure-sdk-for-go

clients/storage/blob.go, clients/storage/client.go
Rearranged several methods like DeleteBlobIfExists and decided to not to export getProperties() methods.
Closes #4.
=> Added godoc for exported blob client methods and types

clients/storage/blob.go
- reorder BlobListResponse to be after ContainerListResponse
- standardize on "name string" parameter for the "Container" methods
Somewhat OCD, but I thought these would be good merged. Let me know what you think.
=> Code tweaks:

clients/storage/blob.go, clients/storage/blob_test.go
Here is simple support for page blobs. (contains a few other minor fixes I just noticed)
Does not contain anything related to page blob sequence numbers (implementation omitted as it's not a current need for docker-registry azure storage driver).
cc: @paulmey @snesha @sachin-jayant-joshi
=> Simple support for Page Blobs

.travis.yml
Set up CI for storage client code to run existing test suite we have. See test results here: https://travis-ci.org/ahmetalpbalkan/azure-sdk-for-go/builds/48724492
This system uses storage keys set up on Travis-CI side and they're injected to the test container before test runs. Additional setup will be required by the repo admins to enable CI for the repo on http://travis-ci.org and setting private environment variables about the storage account from settings section of Travis-CI. 
This will help us understand if the PRs sent are breaking the code.
Please reach me out in setting up the CI on travis-ci, I can provide hands on help.
cc: @jeffmendoza @hopetobelievein @paulmey
=> Travis-CI support for storage client

clients/vmClient/entities.go
Credit to @frodenas for inspiration.
CLA has been signed.
=> Add Vip addresses & InstanceEndpoints to VMs

clients/locationClient/entities.go
Previously the locations client did not return information about the available role sizes in each location. This commit adds two additional properties to the LocationList type to expose a list of Web/Worker role sizes and VM sizes available per region. Since the data is already returned by the API endpoint no API call changes are required.
=> Include the available role sizes from locations

clients/locationClient/entities.go
The previous commit for this had a misspelling of VirtualMachinesRolesSizes for VirtualMachineRoleSizes (I assumed the XML naming would be consistent between Web/Worker roles and VMs!).
Is there a policy for how to write unit tests for this kind of stuff? Seems we'd need some kind of test Azure account for them to be able to run in CI?
=> Fix XML path to Virtual Machines Roles Sizes

clients/locationClient/locationClient.go, clients/vmClient/vmClient.go
There was previously nothing to prevent creation of a virtual machine of an instance size which was unavailable in a given location - instead the operation completed and getting the status returned a `ResourceNotFound` error. This pull request makes the following changes:
- Add a `GetLocation` function to the `locationClient` in order to get access to the structure without iterating through the list returned from `GetLocationList` in multiple spots.
- Remove the call to verify the instance size against the global list.
- Add a function `verifyInstanceSizeAvailableInLocation` to the `vmClient` and call this in place of verification against the global list.
=> Add check of availability of VM role size in location

clients/hostedServiceClient/entities.go, clients/hostedServiceClient/hostedServiceClient.go, clients/vmClient/entities.go, clients/vmClient/vmClient.go
This allows for a less confusing creation of empty cloud services (if for example one is trying to provision multiple virtual machines into the same cloud service and wants to create it first).
Also allow specification of the Reverse DNS FQDN for the cloud service upon creation (will be ommitted from the request to Azure if it's empty
as per the documentation).
At the moment the API for creating Virtual Machines does not allow them to be placed into an existing cloud service, that change will follow.
=> Separate the Hosted Service Client from VM Client

clients/storage/blob.go
I'm clustering the definitions for `Container`, `ContainerProperties`, and `ContainerListResponse` together, and likewise for the "`Blob`" equivalents.
=> blob.go: reorder struct definitions more logically / for better readability

clients/locationClient/entities.go, clients/locationClient/locationClient.go
As discussed in #26.
This eliminates some repetition in the location client by implementing Stringer on a LocationList as a comma separated list of the location names.
=> Add method on entities for concatenating locations

clients/hostedServiceClient/hostedServiceClient.go, clients/imageClient/imageClient.go, clients/locationClient/locationClient.go, clients/storageServiceClient/storageServiceClient.go, clients/vmClient/vmClient.go, clients/vmDiskClient/vmDiskClient.go, common.go, publishSettings.go
As discussed during #26.
This necessitates duplication of the error message across the various different packages, however for the cleanliness of the API this seems worthwhile given that the error messages should likely not be localized anyway.
=> Make azure.ParamNotSpecifiedError unexported

clients/vnetClient/entities.go, clients/vnetClient/vnetClient.go, common.go
This pull requests support for managing virtual networks in Azure.
It adds structs to parse and generate the (seemingly unavailable) XML schema for virtual network specification, and a client with Get and Set operations for the currently active subscription.
The pattern for using the client is the same as the powershell version - get the running config, merge in any desired changes and set the configuration to the new state. There is no documentation on what the concurrency constraints are with the underlying Azure REST API, I suspect it is not safe to call concurrently though can't verify this.
It was also necessary to modify the HTTP client to accept different content types, since the underlying REST API requires the PUT operation to be made with a content type of `text/plain`, despite …
=> Add a client for Virtual Network management

azure/storageservice/client.go, azure/virtualmachine/client.go, azure/virtualmachinedisk/client.go
Just noticed various cases where we weren't passing down the error which could have been received from `WaitAsyncOperation` - this PR fixes them.
=> Always pass on errors from WaitAsyncOperation

management/client.go, management/http.go
Refactor client for consolidation and to support custom config options
=> Client refactor

management/http.go
Allows usage of tools like Fiddler for debugging. This is the standard
way of determining the proxy.
=> Take HTTP proxy from environment

management/publishSettings.go, management/util.go
I implemented PKCS12 from the RFC's to read PFX files. With this, we can drop the implicit openssl dependency.
cc: @ahmetalpbalkan
=> Replace openssl dependency with pure go implementation for converting

.travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details. Will make builds start faster. Also, Travis seems to have more capacity for container based builds than for VM based (capped at 500?).
=> Use container build infra on Travis CI

management/virtualmachineimage/client.go, management/virtualmachineimage/entities.go
Not to be confused with vm.Capture, which yields a OSImage, whereas vmimage.Capture yields a VMImage. The latter stores additional configuration for datadisks etc.
=> Add vmimage.Capture

management/testutils/managementclient.go, management/vmutils/integration_test.go
so it can be used in other SDK package tests. (preparing some tests in the virtualmachine package)
=> Move GetTestClient from vmutils to testutils

management/hostedservice/entities.go
These fields were _named_ omitempty instead of being omitted when empty.
=> Fix omit empty in hosted service entities

management/virtualmachine/entities.go, management/vmutils/extensions_test.go
To only update the resource extensions for a role, the update role operation needs to post the Role object with just the resource extensions tag filled out. Presence of an empty role name tag is interpreted as trying to change the role name and hence will lead to an error.
=> Enable update role scenario for resource extensions

management/publishSettings.go
Commit https://github.com/Azure/go-pkcs12/commit/2b3a2b00323d1388384de1c52c61063c366294f6 changed the API which broke this package. By this simple change everything looks good again…
=> Small fix needed to get the package to compile again.

management/publishSettings.go
This didn’t work as expected as the wrong variable was passed to the `makeClient` func…
=> If not supplying a subscription ID, it should use the first one found

management/virtualmachine/client.go, management/virtualmachine/entities.go, management/vmutils/examples_test.go, management/vmutils/integration_test.go, management/vmutils/network.go
A use case example is that without this code it isn’t possible to create a deployment for a custom virtual network/subnet…
See PR #107 for the complete story on this one.
=> This enables creating deployments with additional options

management/virtualmachine/client.go, management/virtualmachine/entities.go, management/vmutils/network.go
Also removed `subnet` from the deployment options as it’s not used there. The subnet config is part of a `ConfigurationSet` of type `Network` and so is configured by the function `ConfigureWithSubnet`
=> Added support to associate a Network Security Group with a VM

.travis.yml, storage/blob.go, storage/blob_test.go, storage/client.go, storage/client_test.go, storage/util.go
Took a stab at #112 by adding `gofmt`, `go vet` and `golint` checks for the `storage` pkg.
I expect the work at `management` pkg to be much more. So deferring that to some other PR.
cc: @paulmey
=> CI: gofmt/go vet/golint for ./storage

management/http.go, management/util.go
Cleaned up repetitive code.
We're now closing the request body after reading, also switched to
`io/ioutil.ReadAll` and now we're handling errors while reading
the response body responsibly.
Changed word `requestType` to `method` , makes better sense.
Signed-off-by: Ahmet Alp Balkan
cc: @paulmey please review I might be missing some stuff.
=> management: Code cleanup around http.go

management/client.go, management/http.go, management/operations.go, management/publishSettings.go
Fixes #55, #88.
Also exposed default values used to build basic client and
a `DefaultConfig` method that allows user to get a copy of
the config object (that will make it easy to construct and
override only a part of it).
Signed-off-by: Ahmet Alp Balkan
cc: @paulmey
=> management: Custom API versions and User Agent Header

management/storageservice/client.go, management/storageservice/entities.go, management/vmutils/integration_test.go
Fixes #68. Removed some 'special logic' containing helper methods (including `Create` in favor of `CreateAsync`).
Did some code cleanup and stopped returning pointers.
cc:@paulmey
=> management/storage: Remove helpers and cleanup

README.md, management/hostedservice/client.go, management/hostedservice/entities.go, management/vmutils/examples_test.go, management/vmutils/integration_test.go
1. `CreateHostedService` func now takes a struct input
to stabilize the function signature. (base64 encoding of `Label` left to the
user, just like in the rest API. implicitly handling that confuses user more.)
2. `CreateHostedService` is actually not a long running operation,
therefore just returning `error` value from that func now.
3. Changed `CheckHostedServiceNameAvailabilityMethod` to return
the correct response struct to the user.
4. Updated example codes and tests to accomodate changes.
(Please run the integration tests after merging this.)
cc: @paulmey please review
=> management/hostedservice: Refactoring various parts

management/operations.go, management/virtualnetwork/client.go, management/vmutils/examples_test.go, management/vmutils/integration_test.go
- Added cancellation through channel
- Renamed the method
- Updated godocs
- Updated caller methods
- Removed waiting from virtualnetwork.Set method
Fixes #87
cc: @paulmey @svanharmelen
=> Cancellation support for WaitForOperation

management/virtualmachine/entities.go, management/virtualmachine/entities_test.go, management/vmutils/extensions.go, management/vmutils/extensions_test.go, management/vmutils/vmutils_test.go
ResourceExtensionReferences needs to be a pointer to be able to
completely omit the element from the XML, which is necessary for
deploying a VM from a VM image (TestDeployFromVmImage).
cc: @svanharmelen @ahmetalpbalkan
=> Fix integration tests

storage/blob.go, storage/queue.go, storage/util.go
This was causing memory leaks due to not closed response bodies
and thus HTTP connections (especially in PutBlock method).
https://github.com/docker/distribution/issues/620
=> storage: Close underlying http conns before return

management/affinitygroup/client.go, management/affinitygroup/entities.go
This PR depends on the SQL client naming fix: https://github.com/Azure/azure-sdk-for-go/pull/177
=> Added affinity group management support.

management/publishSettings.go
This adds support for initializing a `client` from the contents of a settings file that's stored in memory. At present, `client`s are created by supplying a file path to a settings file, but for my use case I have the contents of the file stored elsewhere, either encrypted in a database or something like [HashiCorp's Vault][1]
I originally tried modifying `ClientFromPublishSettingsFileWithConfig` to check the `filePath` parameter supplied, to see if it's valid XML and not a file path, but settled on duplicating and modifying the `ClientFromPublishSettingsFile` and `ClientFromPublishSettingsFileWithConfig` methods into `ClientFromPublishSettingsData` and `ClientFromPublishSettingsDataWithConfig`, instead. There is duplication, but I felt it was simpler to reason about. 
Example usage, …
=> Add support for creating Clients from a previously read settings file

management/publishSettings.go
@catsby this is the change I was proposing in the #181. :) Implementation of `ClientFromPublishSettingsDataWithConfig` is already 100% the same with `clientFromPublishData` method and makes it obsolete.
=> Reconcile publishSettings methods

storage/queue.go, storage/queue_test.go
this one include #201 and add support for SetMetadata and to deal with user defined fields.
It is separate as implementation is less obvious so if this is not the way the team wants to go with user-defined data, it would be easier to only accept the other, straight-forward patch.
=> Queue metadata with userdefined

management/virtualmachine/client.go
This is a pretty serious bug and limits what we can achieve with production grade deployments on Azure: https://github.com/hashicorp/terraform/issues/3568
As a first step to fix this bug, I propose that we add an "AddRole" method to azure-sdk-for-go for the virtualmachine client. This is a missing API now. Azure already has a REST API for this: https://msdn.microsoft.com/en-us/library/azure/jj157186.aspx
However, azure-sdk-for-go does not have a corresponding method that calls this REST API. Hence, we cannot add a new VM to an existing deployment or cloud service today.
Please accept this straightforward change. It is just the addition of a base method that is missing. Once accepted and merged, I plan to use it from terraform and fix the issue. Thanks again!
I have tested this method …
=> Adding AddRole method so that this bug can be fixed: #3568

management/virtualmachine/client.go
DeleteRole REST API (used to destroy a VM) needs a query parameter to also delete the VHD disk from storage while deleting the VM. This parameter is "comp=media". Documentation is here: https://msdn.microsoft.com/en-us/library/azure/jj157184.aspx
Without this parameter, the DeleteRole() method would only delete the VM but not the disk, thereby leaking storage dollars. Added the parameter, but made it effective only if the boolean argument is true. Thanks.
Context: I am trying to fix hashicorp/terraform#3568. In other words, I am adding the capability to manage multiple VM-s under the same Cloud Service to Terraform. Once this capability is there, we will have to also be able to destroy one VM at a time. As of now, terraform takes the shortcut of deleting the entire cloud service when …
=> Add query parameter to DeleteRole to delete disk based on boolean

management/virtualmachinedisk/client.go
Doc says it returns synchronously. Prevent users from doing an extra "get operation" call.
=> Make DeleteDisk return synchronously

storage/blob.go, storage/blob_test.go, storage/client.go
#209 
Accept extra headers as `map[string]string` on blob-related functions `CreateBlockBlobFromReader`, `PutPageBlob` and `PutBlockWithLength`.
This enable the use case of passing extra headers such as `content-type` with `image/jpeg` to allow azure to serve the blob with correct `content-type`.
=> Accept extra headers

storage/blob.go, storage/blob_test.go, storage/client.go, storage/file.go, storage/queue.go
Adds PutAppendBlob and AppendBlock methods
Addresses #275
=> [storage] Adds support for Append Blobs

management/virtualmachine/client.go, management/virtualmachine/entities.go, management/vmutils/integration_test.go
The implementation of Shutdown Role is incomplete: https://msdn.microsoft.com/en-us/library/azure/jj157195.aspx
The parameter PostShudownAction was not implemented
=> Add support of PostShudownAction for shutdown vm

.travis.yml
./arm/resources$ contains no files, it makes error message confusing.
=> Ignore little warning in travis build

.travis.yml
Apparently `tip` gives development version of go and not the `tip` of the stable feed. (https://github.com/travis-ci/gimme/issues/39)
We ought to increment this version number as new go stable versions come up.
=> Pin travis build to go:1.6

storage/blob.go, storage/blob_test.go
A couple lines difference. Implementation taken from other functions in the file...
=> add support for extra headers in AppendBlock

storage/client.go
Enables connection sharing with http keepalive, and allows callers to
use Go's other http client/transport features like request timeouts.
=> Reuse http.Client across requests, and allow caller to provide its own.

storage/blob.go, storage/blob_test.go
Same change as #257 (and other recent changes) ... but for DeleteBlob and DeleteBlobIfExists.
=> Allow caller to provide headers for DeleteBlob methods.

storage/blob.go, storage/blob_test.go
Per the MSDN docs, BlobPrefixes and Delimiter would be required in BlobListResponse in order to traverse the blob storage as if it were a file system.
As with this example:
```
func traveseBlobs(client storage.BlobStorageClient, prefix string, depth int) {
blobParams := storage.ListBlobsParameters{
Delimiter: "/",
Prefix:    prefix,
}
response, err := client.ListBlobs(accountContainer, blobParams)
checkError(err)
pad := strings.Repeat(" ", depth*2)
// Print folders
folders := response.BlobPrefixes
for _, folder := range folders {
folderWithoutParent := strings.TrimPrefix(folder, prefix)
fmt.Printf("%sd %s\n", pad, folderWithoutParent)
traveseBlobs(client, folder, depth+1)
}
// Print blob names
blobs := response.Blobs
for _, blob := range blobs {
blobWithoutParent := …
```
=> storage: Add BlobPrefixes and Delimiter to BlobListResponse

storage/blob.go
GetBlobSASURI: set expiry location to UTC to meet formatting requirements of Shared Access …
https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-shared-access-signature-part-1/
=> GetBlobSASURI: set expiry location to UTC

storage/blob.go, storage/blob_test.go
This PR adds Metadata to Blob objects in BlobListResponse.
=> List blob metadata

storage/blob.go, storage/blob_test.go
Restores ability to `xml.Marshal()` a Blob.
=> Implement xml.Marshaler for BlobMetadata.

management/virtualmachine/entities.go
The public IP name and timeout were provided, but there was no way to
get the actual address.
=> Expose the public IP address of virtual machines

storage/blob.go, storage/blob_test.go
This Pull Request adds support for extra header in SetBlobMetadata requests.
=> Add support for extra headers in SetBlobMetadata

storage/blob.go
Particularly in case of a Page Blob, this property is useful in determining if the VHD is being used by a VM or not.
Tracking this enhancement as issue - #335
=> Adding LeaseStatus to storage.BlobProperties

arm/README.md
azure.AzureResourceManagerScope is not recognized as it looks like it has evolved to azure.PublicCloud.ResourceManagerEndpoint
=> Updating to correct scope in NewServicePrincipalTokenFromCredentials

storage/client.go, storage/client_test.go
This returns a better error message for malformed base64 storage account keys.
Fixes #344.
=> storage: friendlier error for malformed key

arm/README.md
This ensures code samples are up-to-date.
In the limit we should write a test that extracts and attempts to compile the inline code.  But for now, stop the bleeding.
=> Remove code examples and replace with links to code.  

storage/blob.go, storage/blob_test.go, storage/client.go, storage/client_test.go
I've updated every test that operates on a blob to check for the existence of a space, and other special URL characters. I've excluded the + (plus) character from this, as it appears to need additional special handling (as it stands in for 'space' in some parts of the URL component, but not others).  The others work as expected.
=> Add support for blobs with spaces (and other special URL characters) in the name

storage/blob.go, storage/blob_test.go, storage/util.go, storage/util_test.go
Add following properties to GetBlobProperties:
* Cache-Control
* Cache-Language
Add function SetBlobProperties to set ContentSettings like:
* Content-MD5
* Content-Language
* Content-Encoding
* Content-Type
* Cache-Control
Add Test for SetBlobProperties.
=> provide missing SetBlobProperties function and add missing properties to GetBlobProperties

storage/client.go
We need to remove the "-secondary" string from the account name when using it to authorize access.
See also here: https://blogs.technet.microsoft.com/ksasaki/2013/12/23/use-ra-grs/.
=> Make storage client work correctly with read only secondary accounts

management/vmutils/vmutils.go
Hey Azure-go team!
I happen to need to set custom data for vm creation request, but couldn't find a suitable way to do this. Looks to me like there's currently no way, so I've added helpers to vmutils. My aim is to extend azure_instance resource in Azure provider for Terraform with custom_data and in order to do that, I'd need azure-go library support first.
Please take a look.
=> vmutils: add ConfigureWithCustomData* helpers

storage/table_entities.go
extractContinuationTokenFromHeaders(resp.headers) panics if execTable fails, e.g. due to lack of ca-certificates package installed
=> Checking err for nil after execTable

glide.lock
To pick up the fix made in https://github.com/Azure/go-autorest/pull/89.
=> Update dependent packages versions.

management/http.go
errors should not be ignored in this codebase, and https://github.com/kisielk/errcheck should probably be run over the whole repo.
this caused a hard to debug auth problem where i mishandled certificate decoding from `azureProfile.json` from the CLI.
=> management: check x509 decoding errors

storage/blob.go
A resp.body.Close() statement was causing nil pointer dereference
panics when deleteBlob() returned an error and hence resp was nil.
Signed-off-by: Ahmet Alp Balkan <ahmetalpbalkan@gmail.com>
=> storage#DeleteBlobIfExists: fix panic if resp==nil

storage/client.go, storage/client_test.go
This fixes a bug where `buildCanonicalizedResourceTable` would create an
invalid string when using a PartitionKey or RowKey with a special
character in it, such as "=".
As per the documentation for creating CanonicalizedResource strings for
SharedKey and SharedKeyLite, found at:
https://msdn.microsoft.com/en-gb/library/azure/dd179428.aspx
"Any portion of the CanonicalizedResource string that is derived from
the resource's URI should be encoded exactly as it is in the URI."
`buildCanonicalizedResource` used in other places, was already using
this same method to conform to the documentation.
=> Escape path when creating Canonicalized Resource for Table

.travis.yml, Gododir/gen.go, arm/examples/helpers/helpers.go, storage/table_entities.go
Mostly because of some recent updates on gas ([the update, for the curious](https://github.com/GoASTScanner/gas/commit/a3fcd96f57246314004c9c0d0e747bfd29171e57)).
Gas would skip all `models.go` generated files, another possibility is to disable rule [G101](https://github.com/GoASTScanner/gas#available-rules).
PTAL, @garimakhulbe @jhendrixMSFT @vishrutshah
=> Fixing gas scanning

.travis.yml
gas seems to have broken underneath us, and is no longer ignoring files
that we tell it to. Until I either find an alternative means of skipping
files, or can fix the issue in gas, I'm disabling these checks.
=> Temp removing gas checks from cont. integration

.travis.yml
gas changed the way their globs are resolved to no longer use
Go/filepath, but instead a package published by an individual. This
caused a change in behavior, where there must be a prefix '/' when
providing a pattern that starts with a path.
=> Updating gas skip paths to accomodate new globs.

storage/client.go, storage/client_test.go
Currently, if somebody was trying to implement an `is404(error )`
for errors returned from "storage" package, they would miss
out the errors coming from HEAD requests, such as GetBlobProperties
as these responses do not have a response body that contains an error
message.
Therefore, reusing AzureStorageServiceError to return a sensible
error message that still contains the status code (int) to implement
a `err.(AzureStorageServiceError).Code==404` and the status text (str)
that contains a helpful error message instead of just "404 Not Found" with
an indicator saying "no response body was available".
That simplifies the code that would implement an is404(error) in the
downstream clients.
cc: @yuwamsft FYI
=> storage: return AzureStorageServiceError for empty responses

storage/client_test.go
Issue 485 masked the issue because it appeared that gas was the only
cause of failure in the integration tests.
=> Adding missing import that wasn't caught in last pull-request.

storage/blob.go, storage/blob_test.go, storage/queue.go, storage/table.go, storage/table_entities.go
I've updated all http-verbs to refer to consts that are defined in
golang's src/net/http/method.go
This effort was scoped to files in /storage/
=> Cleaning up hard-coded HTTP verbs.

README.md, management/affinitygroup/client.go, management/publishSettings.go, management/sql/entities.go, management/vmutils/integration_test.go, storage/blob.go, storage/file.go
I added support for Go Report Card, which is a popular lint-like service that helps build confidence in folks hoping to adopt our package.
We currently have an A+ rating, but are not at 100%. I made some of the easy changes that will help bring us closer to 100. It is worth noting that I did not fix issues that are results of mistakes in swagger files (mis-spelled words) and I did not yet go add documentation to a handful of public methods that have no comment.
=> Adding Go Report Card

storage/directory.go, storage/directory_test.go, storage/file.go, storage/file_test.go, storage/fileserviceclient.go, storage/share.go, storage/share_test.go
Split code for shares, directories and files into their own source files;
the same refactoring was made for the test code as well.
Make CRUD APIs for shares, directories and files methods for their
respective types.
Added support for content MD5 hashes when sending/receiving file ranges.
=> Refactor file storage APIs.

Gododir/gen.go, storage/blob.go, storage/client.go, storage/client_test.go, storage/file.go, storage/fileserviceclient.go, storage/queue.go, storage/table.go, storage/version.go
Taking some cool ideas from the [Ruby SDK telemetry](https://github.com/Azure/azure-sdk-for-ruby/pull/543), users can append more info to the User Agent using the `AddToUserAgent` func.
The User-Agent header follows this format...
```
Go/[version] ([arch]-[OS]) Azure-SDK-for-Go/[version] storage-dataplane/[APIversion] [storageService]
```
... and would look like this...
```
Go/go1.7 (amd64-windows) Azure-SDK-for-Go/7.0.1-beta storage-dataplane/2015-02-21 queue
```
PTAL
@salameer @kirthik @vishrutshah @marstr @jhendrixMSFT
=> Adding telemetry to storage dataplane

.travis.yml, rungas.sh
As per issue #514, I've written a script to mask running gas unless we are on the release branch "master"
Travis is bugging out, so this PR is a copy of #521 as a mitigation.
=> Updating gas to only run during CI when on master

storage/blob.go, storage/blob_test.go, storage/client_test.go, storage/storagepolicy.go, storage/table.go, storage/table_test.go
Found this on the way.
ACLs were working with a single permission, but they should also work with many permissions.
PTAL
@jhendrixMSFT @marstr
=> ACLs now work correctly with lists

storage/blob.go, storage/blob_test.go
We are using this as a dependency in Yammer's fork of hashicorp/vault which includes support for Azure Blob Storage SAS URI generation (I'll send them a PR once I get the OSS approval)
Slightly modifies GetBlobSASURI behavior to generate a URI for the entire container instead of just a single blob, if blob name isn't specified.
-- Rao Li (raol@microsoft.com)
=> Add support to generate SAS URI for entire containers

storage/blob.go, storage/blobserviceclient.go, storage/client.go, storage/fileserviceclient.go, storage/queue.go, storage/queueserviceclient.go, storage/storageservice.go, storage/storageservice_test.go, storage/table.go, storage/tableserviceclient.go
Related to https://github.com/Azure/azure-sdk-for-go/issues/518
There are still some funcs missing for all services. Started with get and set service properties.
=> Service properties

storage/blob.go
Updating `blob.AcquireLease(...)` to ensure that leaseTimeInSeconds is
submitted within the bounds of what the Azure REST API expects. I
decided clamping the value to the min/max acceptable value was more user
friendly than throwing an error without adding too much complexity.
The real alternative to what I did was to simply remove the check
all-together and just pass through the value to Azure. The reason I
didn't do that, is that I presume Azure would adopt the same behavior I
enumerated. Having this operation done client side will allow folks who
are debugging to see the operation.
=> Addressing issue #548

Gododir/gen.go
This works with the cowboy's latest changes.
PTAL @marstr @jhendrixMSFT
=> Gen.go update

Gododir/gen.go, management/client.go, management/version.go
Fixes https://github.com/Azure/azure-sdk-for-go/issues/555
=> More complete User-Agent for ASM

storage/table_entities.go, storage/table_test.go
There is a nasty bug in the current TableService code that results in some errors being silently dropped.
The following functions are only checking the response code if a call to `c.execTable` returns an error:
* `InsertEntity`
* `UpdateEntity`
* `InsertOrReplaceEntity`
* `InsertOrMergeEntity`
In some cases calls to `c.execTable` can fail without returning errors. In particular, it calls `client.execInternalJSON`,  which does return an error for bad status codes with no response body (https://github.com/Azure/azure-sdk-for-go/blob/master/storage/client.go#L414). However if there is some response body, it then unmarshals it, and only returns an error if this unmarshalling fails (https://github.com/Azure/azure-sdk-for-go/blob/master/storage/client.go#L420).
It is unclear if this behaviour …
=> Fix table entities error checking

storage/client.go, storage/client_test.go
Inspired by #584, #594.
@mcardosos @jhendrixMSFT @marstr
=> storage: avoid transiting url.URL through string

Gododir/gen.go
Added optional flag "testgen" that will invoke the Go.TestGen generator,
dumping the output into a "tests" subdirectory for each swagger.
Added the ability to toggle between using a globally-installed AutoRest
and a locally-built one (defaults to global installation).
Cleaned up some hard-coded path separator.
=> Add support for the Go test generator.

storage/client.go
As far as I can tell, Go will calculate the correct value for
Content-Length independently if we just leave it unset when we create a
new request.
=> Removing storage/client.go Content-Length calc.

glide.lock, glide.yaml, storage/client.go
Using ioutil.ReadAll() to read the request body can introduce a large
number of allocations increasing heap pressure.  For cases where the
content length of the request is known we can read the body into an
allocated buffer of exact size.
Update go-autorest dependency to 8.1.0 to use RetriableRequest feature.
=> Reduce allocations for request retry logic.

storage/blobsasuri.go, storage/blobsasuri_test.go, storage/client.go, storage/client_test.go, storage/container.go, storage/container_test.go
GetSASURI func now receive grouped parameters
GetSASURI also includes signed identifier and overridable headers
Got rid of GetSASURIWithSignedIPAndProtocol
PTAL
@marstr @jhendrixMSFT
=> GetSASURI is more complete and has grouped params

storage/util.go
Attempting to use `Blob.Get()` to retrieve blob snapshots fails.
`addSnapshot()` is using the wrong format for the timestamp parameter.
This PR fixes `addSnapshot()` to use the correct timestamp format.
=> Fix Snapshot parameter format

storage/directory.go, storage/file.go
Added a sync.Mutex to the File object to be held by APIs that support
concurrent operation.
Updated File.WriteRange() to hold the file mutex when updating the ETag
and last modified date properties.
Removed some duplicated code.
=> Fix race condition in File.WriteRange().

storage/blockblob_test.go, storage/client.go, storage/recordings/BlockBlobSuite/TestPutBlockWithLengthUsingLimitReader.yaml
The ctor for http.Request will perform type assertions for a handful of
types in order to set the content length.  Unfortunately it doesn't test
for io.LimitedReader so a check has been added.
Fix for issue https://github.com/Azure/azure-sdk-for-go/issues/683
=> Ensure content length is set when body is a io.LimitedReader.

.travis.yml
👋 
I'm upgrading Terraform to Go 1.9 and noticed the SDK wasn't building against this yet, as such I've updated the Travis file to do this. I'm not sure if this needs to be updated anywhere else, but hopefully this is useful :)
=> Upgrading to Go 1.9

storage/blob.go
SetProperties uses correct format for ContentLength header.
options.SequenceNumberAction is only accessed when options != nil.
See comments in Issue 765 for detailed description.  Hope this helps!
=> blob.SetProperties fixes (Issue 765)

README.md
As noted in #448, we needed to update the README to talk about our SDK
Versioning and support stories. This contribution hopes to document that.
=> Updating README to address versioning strategy

storage/client.go, storage/client_test.go
Based on the [Node.js version](https://github.com/Azure/azure-storage-node/blob/a2a26c7c70acb1eee0a77fb68fc1547145afec28/lib/common/services/servicesettings.js#L710), allows instantiating storage clients from connection strings.
=> feat(storage): allow creating clients from connection strings

tools/profileBuilder/test.sh
Bash is extremely sensitive to whitespace. The profileBuilder tests weren't getting run before this PR.
=> Fixing bash script to run profileBuilder tests

.github/PULL_REQUEST_TEMPLATE.md
There are a lot of submissions to the `master` branch, which will get
immediately released to folks using `go get` for that reason, we want to
always make sure that `master` stays in release quality.
=> Adding a Template to help guide new PRs.

storage/pageblob.go, storage/util.go
The previous snapshot time query param is supposed to be in RFC3339
format.  Moved formatting code to its own function.
=> Format previous snapshot time as RFC3339.

profiles/2017-03-09/compute/mgmt/compute/models.go, profiles/2017-03-09/definition.txt, profiles/2017-03-09/network/mgmt/network/models.go, profiles/2017-03-09/resources/mgmt/features/models.go, profiles/2017-03-09/resources/mgmt/links/models.go, profiles/2017-03-09/resources/mgmt/policy/models.go, profiles/2017-03-09/resources/mgmt/resources/models.go, profiles/2017-03-09/resources/mgmt/subscriptions/models.go, profiles/2017-03-09/storage/mgmt/storage/models.go
Updating the profile that was generated for "2017-03-09" to match the versions as enumerated by the CLI defintion, which can be found here:
https://github.com/Azure/azure-cli/blob/3abcc80788f3e21d00d40c60fda43c3ff6754e5c/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L67
---
=> One change to match the Stack profile

tools/profileBuilder/program.go
This will prevent profiles built with the profile Builder from ever failing CI after #853 is merged.
---
=> Adding call to `gofmt` once a profile is generated

tools/generator/program.go
Added command flag 'a' to optionally specify autoret.go version.
=> Make autorest.go version configurable.

storage/blobsasuri.go
The 'st' param was not added to the url parameters
=> BlobStorage SignedUrl - Specifying start time not added to url parameters

.travis.yml
- Adding `master` to the build matrix for go.
- Removing `GO15VENDOREXPERIMENT` as it is on by defaullt since go 1.6.
=> Run build against latest go version

swagger_to_sdk_config.json
Profiles must be regenerated to match the regenerated services folders.
=> Adding profile generation to Swagger->SDK

storage/util.go
With this, `xml.Marshal(BlobListResponse{...})` (for example) produces XML that can be decoded by the client. This makes it much easier to write a stub server.
=> Marshal TimeRFC1123 as RFC1123 instead of empty string.

storage/file.go
A very small change. Instead of users of this library having to hardcode the maximum range and file size, they should just be able to pick them from the library.
---
=> Export maximum range and file sizes

swagger_to_sdk_config.json
At the moment, we're having trouble running the profileBuilder in the
Swagger->SDK environment, because it assumes that GOPATH is set on the
machine in which it is running. Issue #1101 is tracking this and other
problems introduced by that dependency.
=> Removing `profileBuilder` portion of Swagger->SDK

services/containerinstance/mgmt/2018-02-01-preview/containerinstance/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2651
=> [AutoPR containerinstance/resource-manager] Fixing Error in Naming Convention for Rows and Cols in Terminal Size

tools/profileBuilder/model/transforms.go
Include the bad path in the error message.
Close the file handle to avoid race conditions.
Moved formatting to be per file so that it only touches the contents of
the profile being generated.
=> Tweaks to profile builder.

tools/apidiff/cmd/common.go, tools/apidiff/cmd/root.go, tools/apidiff/delta/delta.go, tools/apidiff/delta/delta_test.go, tools/apidiff/ioext/ioext.go
Fixed a bug in breakingChanges.isEmpty() that was causing it to return
true when it should have returned false.
Convert relative package(s) path to absolute path.
Added switch "copyrep" to copy the source repo instead of cloning it;
useful for CI so things like FETCH_HEAD are preserved.
Include new struct fields and interface methods in GetExports().
Added package ioext containing various IO extension funcs.
=> Fixes to apidiff tool.

.travis.yml
Run the apidiff tool in travis to report breaking changes in a PR.  The
tool is run as an allowed failure and will return a non-zero exit code
if there are breaking changes so the task shows up as red.  The raw JSON
log will also be output to the console.
=> Add breaking changes detection to travis CI.

services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/accounts.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/client.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/operations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2786
=> [AutoPR cognitiveservices/resource-manager] Make filter a method parameter

tools/apidiff/cmd/common.go, tools/apidiff/cmd/package.go, tools/apidiff/cmd/packages.go
To support porting non-breaking changes the generated report now
includes the collection of packages impacted by commit along with a list
of commits that introduce breaking changes.
Moved the changes to a "deltas" field in the report; each entry is an
object described as "base:target" commit range.
Added support for report generation based on a sequence of commits, see
the help documentation for further details on how this works.
=> Updates to apidiff tool

services/compute/mgmt/2018-04-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2836
=> [AutoPR compute/resource-manager] Added Eviction Policy Property for VirtualMachineScaleSetVMProfile for version 2017-12-01

services/monitor/mgmt/2017-05-01-preview/insights/actiongroups.go, services/monitor/mgmt/2018-03-01/insights/actiongroups.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2841
=> [AutoPR monitor/resource-manager] fix documentation bug: max length of Group Short Name should be 12

storage/client.go
The only change here is when returned error is nil (the Response is guaranteed to contain a non-nil Body); in other cases throughout the code, readAndCloseBody is already called.
Without this fix, retries will cause connection leaks
Fixes https://github.com/Azure/azure-sdk-for-go/issues/1500
=> Read and close response body after each retry

storage/blob.go, storage/blockblob.go, storage/client.go, storage/container.go, storage/copyblob.go, storage/directory.go, storage/entity.go, storage/file.go, storage/fileserviceclient.go, storage/leaseblob.go, storage/message.go, storage/pageblob.go, storage/queue.go, storage/share.go, storage/storageservice.go, storage/table.go, storage/table_batch.go
Added func drainRespBody() that copies the HTTP response body into
nothingness then closes it, avoiding allocations.
When reading/closing the HTTP response body, for cases that don't
require the data call drainRespBody() instead of readAndCloseBody().
=> Drain response body without allocating a buffer.

tools/apidiff/cmd/common.go, tools/apidiff/cmd/packages.go, tools/apidiff/cmd/root.go, tools/apidiff/repo/repo.go, tools/picker/cmd/root.go, tools/picker/main.go
The picker tool is used to cherry-pick non-breaking changes from one
branch to another.  Note that this tool will mutate the state of your
working tree.
Added ExecPackagesCmd() for programmatically invoking the packages
command and exported the type of the report it returns.
Added Cherry() and CherryPick() to the repo package.
=> Add picker tool for cherry-picking commits

tools/profileBuilder/model/transforms.go
Don't attempt to sort the file decls, just leave them in their original
order (the generator sorts them).
Removed extra print-line for writing file.
=> Leave file decls in their original order

services/cognitiveservices/v1.0/contentmoderator/textmoderation.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2884
=> [AutoPR cognitiveservices/data-plane/ContentModerator] Set language parameter as a non-required field for Screen Text API

services/web/mgmt/2016-09-01/web/apps.go, services/web/mgmt/2018-02-01/web/apps.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3017
=> [AutoPR web/resource-manager] Fix for https://github.com/Azure/azure-rest-api-specs/issues/2907. Missed the production slot APIs earlier. 

profiles/latest/eventgrid/eventgrid/models.go, profiles/preview/eventgrid/eventgrid/models.go, services/eventgrid/2018-01-01/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3061
=> [AutoPR eventgrid/data-plane] EventGrid Dataplane: Added schemas corresponding to SubscriptionValidationEvent/Response and SubscriptionDeletedEvent

profiles/preview/preview/resources/mgmt/management/models.go, services/preview/resources/mgmt/2018-03-01-preview/management/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3115
=> [AutoPR managementgroups/resource-manager] Fix typo in enum

services/classic/management/networksecuritygroup/client.go
The unmarshalling code didn't account for the payload being wrapped in a
NetworkSecurityGroups element; this has been fixed.
=> Fix SecurityGroupClient.ListNetworkSecurityGroups()

profiles/preview/network/mgmt/network/models.go, services/network/mgmt/2018-02-01/network/models.go, services/network/mgmt/2018-04-01/network/models.go, services/network/mgmt/2018-05-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3230
=> [AutoPR network/resource-manager] network: add https probe which was missing in the spec

services/preview/apimanagement/mgmt/2018-01-01/apimanagement/productapi.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3258
=> [AutoPR apimanagement/resource-manager] Fix the validation Check for apiId parameter in the productapis

tools/apidiff/cmd/packages.go
Using "packageName:apiVersion" as the dictionary key is not enough info
to ensure unique package identity; this is because there are duplicated
packages in the services and services/preview directories.  The result
is incorrect delta information.  Use the full package package which is
guaranteed to be unique.
=> Diff'ing packages can contain incorrect information

services/preview/monitor/mgmt/2017-05-01-preview/insights/alertrules.go, services/preview/monitor/mgmt/2017-05-01-preview/insights/autoscalesettings.go, services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go, services/preview/monitor/mgmt/2018-03-01/insights/alertrules.go, services/preview/monitor/mgmt/2018-03-01/insights/autoscalesettings.go, services/preview/monitor/mgmt/2018-03-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3285
=> [AutoPR monitor/resource-manager] Add two missing "by subscription" operations for completeness and compliance

storage/blobserviceclient.go, storage/client.go
storage.GetContainerReferenceFromSASURI() didn't set the storage account
name and other fields when creating a SAS client from a URI.
=> Fixes for blob storage SAS URI parsing

storage/message.go
The visibilitytimeout query param is required for the update method so
include the default value of zero.
=> Fix QueueMessage Update method

swagger_to_sdk_config.json
=> Update generator version to 2.1.110 for swagge to sdk

.travis.yml
- restrict travis branch push builds only to master and latest branches
=> do CI builds only on release branches

Gopkg.lock, profiles/latest/cognitiveservices/contentmoderator/models.go, profiles/preview/cognitiveservices/contentmoderator/models.go, services/cognitiveservices/v1.0/contentmoderator/client.go, services/cognitiveservices/v1.0/contentmoderator/imagemoderation.go, services/cognitiveservices/v1.0/contentmoderator/listmanagementimage.go, services/cognitiveservices/v1.0/contentmoderator/listmanagementimagelists.go, services/cognitiveservices/v1.0/contentmoderator/listmanagementterm.go, services/cognitiveservices/v1.0/contentmoderator/listmanagementtermlists.go, services/cognitiveservices/v1.0/contentmoderator/models.go, services/cognitiveservices/v1.0/contentmoderator/reviews.go, services/cognitiveservices/v1.0/contentmoderator/textmoderation.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3505
=> [AutoPR cognitiveservices/data-plane/ContentModerator] [Cognitive Services] Update endpoint URL template for Content Moderator.

profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2018-06-01/compute/models.go, services/web/mgmt/2016-09-01/web/apps.go, services/web/mgmt/2018-02-01/web/apps.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3757
=> [AutoPR compute/resource-manager] Added the replica count API change to Shared Image Gallery swagger file.

profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2018-06-01/compute/disks.go, services/compute/mgmt/2018-06-01/compute/models.go, services/compute/mgmt/2018-06-01/compute/snapshots.go
Created to accumulate context: compute/resource-manager
=> [AutoPR] compute/resource-manager

profiles/preview/preview/monitor/mgmt/insights/models.go, services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go, services/preview/monitor/mgmt/2018-03-01/insights/models.go, services/preview/monitor/mgmt/2018-09-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3921
=> [AutoPR monitor/resource-manager] [Azure monitor] Add missing enum for aggregation type

services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3949
=> [AutoPR containerservices/resource-manager] Remove serverAppSecret which is not required for AKS cluster updates

profiles/preview/preview/machinelearning/mgmt/services/models.go, services/preview/machinelearning/mgmt/2018-03-01-preview/services/machinelearningcompute.go, services/preview/machinelearning/mgmt/2018-03-01-preview/services/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3889
=> [AutoPR machinelearningservices/resource-manager] update machine learning compute portion of the machine learning services swagger

tools/apidiff/cmd/changelog.go, tools/apidiff/cmd/packages.go
The changelog command will generate tables for packages that are new,
updated, removed, and with breaking changes.  Table is generated in
markdown format.
=> Add changelog command to apidiff tool

services/compute/mgmt/2018-06-01/compute/galleries.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3981
=> [AutoPR compute/resource-manager] Improve gallery swagger by improving one description and mark one param as required.

profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2018-06-01/compute/models.go, services/compute/mgmt/2018-10-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3944
=> [AutoPR compute/resource-manager] Swagger changes for adding diffdisksettings property for the Ephemeral OS Disks 

services/compute/mgmt/2017-03-30/compute/models.go, services/compute/mgmt/2018-04-01/compute/models.go, services/compute/mgmt/2018-06-01/compute/models.go, services/compute/mgmt/2018-10-01/compute/models.go, services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3966
=> [AutoPR compute/resource-manager] Fix typo in Compute ImageDiskReference::id description

README.md
Documents the changes implemented for #2610
Requires `go-autorest` to be revendored to version 11.1.0+.
Inspired by https://github.com/MicrosoftDocs/azure-docs/blob/e43e8e75f1dbf37054bb3dd6b6136d6954e85c70/articles/key-vault/service-to-service-authentication.md
=> Updated README.MD with NewAuthorizerFromCLI() details

.travis.yml, swagger_to_sdk_config.json, tools/pkgchk/cmd/root.go, tools/pkgchk/exceptions.txt, tools/pkgchk/main.go
pkgchk will verify the following things:
- package and directory names match
- all lower-case characters in package path
- directory for ARM packages are well-formed
Updated swagger->sdk to specify the preview-chk switch to verify that a
preview swagger has its codegen under a preview subdirectory.
=> Add pkgchk tool and integrate into CI

.travis.yml, Gopkg.lock
Ensure there are no unstaged changes; this typically happens if a new
dependency is introduced and you forget to run "dep ensure".
=> Ensure branch is clean in CI

storage/queue.go
Params wasn't used. Instead of using the variable, a nearly identical object was created.
Signed-off-by: Jannick Fahlbusch <git@jf-projects.de>
=> Storage: Pass pre-built parameters instead of generating them twice

profiles/preview/preview/automation/mgmt/automation/models.go, services/preview/automation/mgmt/2017-05-15-preview/automation/models.go, services/preview/automation/mgmt/2018-01-15-preview/automation/models.go, services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4165
=> [AutoPR automation/resource-manager] Swagger change for Update configuration dynamic group

profiles/latest/servicebus/mgmt/servicebus/models.go, profiles/preview/servicebus/mgmt/servicebus/models.go, services/servicebus/mgmt/2015-08-01/servicebus/namespaces.go, services/servicebus/mgmt/2017-04-01/servicebus/migrationconfigs.go, services/servicebus/mgmt/2017-04-01/servicebus/models.go, services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4245
=> [AutoPR servicebus/resource-manager] Service Bus: moved VNet and IpFilter rules from 2018-preview to 2017 API version

.travis.yml
=> remove golint as it fails to build on older versions of Go

profiles/latest/eventhub/mgmt/eventhub/models.go, profiles/preview/eventhub/mgmt/eventhub/models.go, services/eventhub/mgmt/2015-08-01/eventhub/namespaces.go, services/eventhub/mgmt/2017-04-01/eventhub/models.go, services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/clusters.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/namespaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4246
=> [AutoPR eventhub/resource-manager] EventHub: moved VNet, IpFilter rules and Kafka from 2018-preview to 2017 API Version

README.md
Hoping that this PR ensures something like this: https://github.com/Azure/azure-sdk-for-go/issues/3111 doesn't happen again.
=> docs: adding more clarity to backwards compatibility

tools/pkgchk/cmd/root.go
A scanner's last error should always be checked. This ensures a proper scan completes successfully.
Closing the original PR: https://github.com/Azure/azure-sdk-for-go/pull/3118 per @jhendrixMSFT in favor of this PR which is based off of the `latest` branch.
=> fix scanner

profiles/preview/containerinstance/mgmt/containerinstance/models.go, services/containerinstance/mgmt/2018-10-01/containerinstance/containergroups.go, services/containerinstance/mgmt/2018-10-01/containerinstance/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4373
=> [AutoPR containerinstance/resource-manager] Update Microsoft.Containerinstance swagger with DNSConfig and GPU

services/preview/cognitiveservices/v1.0/visualsearch/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4398
=> [AutoPR cognitiveservices/data-plane/VisualSearch] enable swagger-to-sdk in visual search for Go SDK

profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4375
=> [AutoPR datafactory/resource-manager] [DataFactory]Add sensitive fields extracted from connection string in swagger for AKV reference

services/network/mgmt/2018-08-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4459
=> [AutoPR network/resource-manager] Model ContainerNic refs under ContainerNicConfig as sub resources

profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/clusters.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/hdinsightapi/interfaces.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/clusters.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/hdinsightapi/interfaces.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to accumulate context: hdinsight/resource-manager
=> [AutoPR] hdinsight/resource-manager

profiles/preview/network/mgmt/network/models.go, services/network/mgmt/2018-10-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4387
=> [AutoPR network/resource-manager] Application gateway Identity and Keyvault support

README.md
This adds a link to the azure-sdk-for-go channel in the Gophers Slack to the README.
=> add Slack link to README

tools/apidiff/cmd/packages.go
The addition of the *api subdirectories broke some assumptions the tool
made on how to find packages.  Update the logic to not recurse into the
api subdirectories.
=> Fix packages command for apidiff tool

services/web/mgmt/2016-09-01/web/appservicecertificateorders.go, services/web/mgmt/2016-09-01/web/models.go, services/web/mgmt/2018-02-01/web/appservicecertificateorders.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4502
=> [AutoPR web/resource-manager] typo: Fix AppServiceCertificateOrders.json

profiles/latest/containerregistry/mgmt/containerregistry/models.go, profiles/preview/containerregistry/mgmt/containerregistry/models.go, profiles/preview/preview/containerregistry/mgmt/containerregistry/models.go, services/containerregistry/mgmt/2017-03-01/containerregistry/registries.go, services/containerregistry/mgmt/2017-10-01/containerregistry/models.go, services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go, services/containerregistry/mgmt/2017-10-01/containerregistry/replications.go, services/containerregistry/mgmt/2017-10-01/containerregistry/webhooks.go, services/containerregistry/mgmt/2018-09-01/containerregistry/models.go, services/containerregistry/mgmt/2018-09-01/containerregistry/registries.go, services/containerregistry/mgmt/2018-09-01/containerregistry/replications.go, services/containerregistry/mgmt/2018-09-01/containerregistry/runs.go, services/containerregistry/mgmt/2018-09-01/containerregistry/tasks.go, services/containerregistry/mgmt/2018-09-01/containerregistry/webhooks.go, services/preview/containerregistry/mgmt/2017-06-01-preview/containerregistry/models.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/registries.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/replications.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/webhooks.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4506
=> [AutoPR containerregistry/resource-manager] [ACR] Add empty resource group name validation, minor cleanup

services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4711
=> [AutoPR marketplaceordering/resource-manager] typo: marketplaceordering/resource-manager/Microsoft.MarketplaceOrdering

services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4710
=> [AutoPR mariadb/resource-manager] typo: mariadb/resource-manager/Microsoft.DBforMariaDB

profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/models.go, services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4740
=> [AutoPR sqlvirtualmachine/resource-manager] [Portal Generated] Review request for Microsoft.SqlVirtualMachine to add version 2017-03-01-preview

services/cognitiveservices/v1.2/customvision/training/client.go, services/cognitiveservices/v1.2/customvision/training/models.go, services/cognitiveservices/v2.1/customvision/training/client.go, services/cognitiveservices/v2.1/customvision/training/models.go, services/cognitiveservices/v2.2/customvision/training/client.go, services/cognitiveservices/v2.2/customvision/training/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4817
=> [AutoPR cognitiveservices/data-plane/CustomVision/Training] typo: CustomVision/Training

services/servicefabric/6.2/servicefabric/models.go, services/servicefabric/6.3/servicefabric/models.go, services/servicefabric/6.4/servicefabric/models.go
Created to accumulate context: servicefabric/data-plane
=> [AutoPR] servicefabric/data-plane

profiles/preview/preview/containerservice/mgmt/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/containerserviceapi/interfaces.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/openshiftmanagedclusters.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/containerserviceapi/interfaces.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/openshiftmanagedclusters.go
Created to accumulate context: containerservices/resource-manager
=> [AutoPR] containerservices/resource-manager

profiles/latest/eventgrid/mgmt/eventgrid/eventgridapi/models.go, profiles/latest/eventgrid/mgmt/eventgrid/models.go, profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanainstances.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanaonazureapi/interfaces.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4949
=> [AutoPR hanaonazure/resource-manager] Add PATCH API example to hanaonazure

services/classic/management/virtualmachine/client.go, services/classic/management/virtualmachine/entities.go, services/classic/management/virtualmachine/resourceextensions.go
Several large enterprises still extensively use Azure PaaS V1 (Cloud Services a.k.a. Web/Worker Roles) through the classic management API (ASM). These are early adopters of the Azure cloud platform and will take singificant migration effort to move to newer Compute options available via Azure Resource Manager (ARM).
Newer cross platform automation options (azure cli, Az Powershell Module) do not provide support for ASM, which makes it non feasible to run on non windows environment (e.g:- Linux Containers as part of CI/CD).
This pull request wraps the ASM API and adds support for the common workflows such as deploying cloud service packages to production or staging slots of a cloud service and performing blue/green style deployment with VIP Swap. It also adds support for managing …
=> Support asm cloud services (Targeting latest branch)

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5007
=> [AutoPR datafactory/resource-manager] [Datafactory] Add Webhook Activity to Azure Data Factory 

services/classic/management/client.go, services/classic/management/http.go
This PR addresses re-using the underlying httpClient when making API calls to Azure Service Management (ASM). 
It also adds some throttling when ASM returns a ServiceUnavailable response (Code: TooManyRequests, Message: Too many requests received. Retry after some time.)
=> Reuse http client used with ASM API 

services/classic/management/virtualmachine/entities.go
Certain workflows rely on the deployment identifier (a.k.a. PrivateID) from the Deployment response. 
https://docs.microsoft.com/en-us/rest/api/compute/cloudservices/rest-get-deployment
<PrivateID>identifier-of-deployment</PrivateID>  
This was missing in the entity
=> Read deployment ID (a.k.a. PrivateID) from GetDeployment response

profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/alertrules.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/securityinsightapi/interfaces.go
Created to accumulate context: securityinsights/resource-manager
=> [AutoPR] securityinsights/resource-manager

profiles/latest/web/mgmt/web/models.go, profiles/preview/web/mgmt/web/models.go, services/web/mgmt/2018-02-01/web/client.go, services/web/mgmt/2018-02-01/web/models.go, services/web/mgmt/2018-02-01/web/recommendations.go, services/web/mgmt/2018-02-01/web/webapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5111
=> [AutoPR web/resource-manager] [App Service] Update swagger spec for ANT80

.travis.yml, tools/indexer/main.go
Added missing directory argument to indexer.
Fixed indexer to always calculate absolute path.
=> Fix indexer run in CI

profiles/latest/cognitiveservices/face/models.go, profiles/preview/cognitiveservices/face/models.go, services/cognitiveservices/v1.0/face/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5188
=> [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Remove Face API reference of Gender::genderless to avoid confusion.

profiles/latest/marketplaceordering/mgmt/marketplaceordering/models.go, profiles/preview/marketplaceordering/mgmt/marketplaceordering/models.go, services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/marketplaceagreements.go, services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/marketplaceorderingapi/interfaces.go, services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5279
=> [AutoPR marketplaceordering/resource-manager] Add missing MarketplaceOrdering operations to swagger

profiles/latest/search/mgmt/search/models.go, profiles/preview/search/mgmt/search/models.go, services/search/mgmt/2015-08-19/search/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5319
=> [AutoPR search/resource-manager] Azure Search: Resource Manager: Support 'None' Identity type

services/graphrbac/1.6/graphrbac/applications.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5425
=> [AutoPR graphrbac/data-plane] graph: identifierUris should not be required

profiles/latest/cognitiveservices/textanalytics/models.go, profiles/preview/cognitiveservices/textanalytics/models.go, services/cognitiveservices/v2.1/textanalytics/client.go, services/cognitiveservices/v2.1/textanalytics/models.go, services/cognitiveservices/v2.1/textanalytics/textanalyticsapi/interfaces.go, services/cognitiveservices/v2.1/textanalytics/version.go
Created to accumulate context: cognitiveservices/data-plane/TextAnalytics
=> [AutoPR] cognitiveservices/data-plane/TextAnalytics

services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5430
=> [AutoPR containerregistry/resource-manager] [ACR] Add Readonly RunErrorMessage to RunProperties

services/cognitiveservices/v3.0/translatortext/translator.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5484
=> [AutoPR cognitiveservices/data-plane/TranslatorText] typo: cognitiveservices/data-plane/TranslatorText

services/compute/mgmt/2018-10-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5498
=> [AutoPR compute/resource-manager] Adding doNotRunExtensionsOnOverprovisionedVMs property to swagger

services/containerservice/mgmt/2019-02-01/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5491
=> [AutoPR containerservice/resource-manager] Adding customerAdminGroupId to OSA cluster swagger spec

services/network/mgmt/2018-12-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5675
=> [AutoPR network/resource-manager] Resolve issue with unreferenced examples in Network specs for older API versions

profiles/latest/iotcentral/mgmt/iotcentral/models.go, profiles/preview/iotcentral/mgmt/iotcentral/models.go, services/iotcentral/mgmt/2018-09-01/iotcentral/apps.go, services/iotcentral/mgmt/2018-09-01/iotcentral/iotcentralapi/interfaces.go, services/iotcentral/mgmt/2018-09-01/iotcentral/models.go
Created to accumulate context: iotcentral/resource-manager
=> [AutoPR] iotcentral/resource-manager

profiles/latest/compute/mgmt/compute/models.go, profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2019-03-01/compute/models.go, services/compute/mgmt/2019-03-01/compute/resourceskus.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5753
=> [AutoPR compute/resource-manager] Moved AdditionalCapabilities out from VM profile to VMSS and updated SKUs API to support zonal capabilities

services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5780
=> [AutoPR sql/resource-manager] Fix missing proxy override enum for managed instance swagger

profiles/preview/preview/eventhub/mgmt/eventhub/models.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/clusters.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/eventhubapi/interfaces.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5565
=> [AutoPR eventhub/resource-manager] Adding Create, Delete and List Namespaces Endpoints for Event Hubs Cluster Resource

storage/table_batch.go, storage/util.go
The v1.2.0 version of the go.uuid package has a different signature for
function NewV1() compared to HEAD causing build breaks for go getters.
Removed dependences on uuid.NewV1(), replaced with internal newUUID()
function taken from azure-storage-blob-go.
=> Fix build break in storage for 'go get' consumers

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/storage/mgmt/2019-04-01/storage/blobcontainers.go, services/storage/mgmt/2019-04-01/storage/models.go, services/storage/mgmt/2019-04-01/storage/storageapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5733
=> [AutoPR storage/resource-manager] [SRP] Expose lease container in Apr19 API.

services/containerservice/mgmt/2019-04-30/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5841
=> [AutoPR containerservice/resource-manager] Revert node public ip support from 2019-04-01 model.

storage/entity.go, storage/entity_test.go, storage/odata.go, storage/recordings/StorageEntitySuite/TestDelete.yaml, storage/recordings/StorageEntitySuite/TestExecuteQueryNextResults.yaml, storage/recordings/StorageEntitySuite/TestGet.yaml, storage/recordings/StorageEntitySuite/TestInsert.yaml, storage/recordings/StorageEntitySuite/TestInsertOrMerge.yaml, storage/recordings/StorageEntitySuite/TestInsertOrReplace.yaml, storage/recordings/StorageEntitySuite/TestMerge.yaml, storage/recordings/StorageEntitySuite/TestUpdate.yaml, storage/recordings/StorageEntitySuite/Test_InsertAndDeleteEntities.yaml, storage/recordings/StorageEntitySuite/Test_InsertAndExecuteQuery.yaml, storage/recordings/StorageEntitySuite/Test_InsertAndGetEntities.yaml, storage/recordings/TableBatchSuite/Test_BatchInsertDeleteSameEntity.yaml, storage/recordings/TableBatchSuite/Test_BatchInsertMultipleEntities.yaml, storage/recordings/TableBatchSuite/Test_BatchInsertSameEntryMultipleTimes.yaml, storage/recordings/TableBatchSuite/Test_BatchInsertThenDeleteDifferentBatches.yaml, storage/recordings/TableBatchSuite/Test_BatchInsertThenMergeDifferentBatches.yaml
Floating point numbers that happen to be whole numbers are
incorrectly treated as integers.  For float64 types encode them
as Edm.Double types.
=> Add proper support for floats in entities

services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5872
=> [AutoPR blueprint/resource-manager] Blueprints: timeCreated and lastModified should be date-time format

tools/apidiff/cmd/changelog.go, tools/apidiff/cmd/common.go, tools/apidiff/cmd/package.go, tools/apidiff/cmd/packages.go, tools/apidiff/delta/delta.go, tools/apidiff/delta/delta_test.go, tools/apidiff/report/markdown.go, tools/apidiff/report/report.go, tools/versioner/cmd/root.go, tools/versioner/cmd/root_test.go, tools/versioner/internal/modinfo/modinfo.go, tools/versioner/internal/modinfo/modinfo_test.go, tools/versioner/testdata/scenariod/foo/stage/foo.go, tools/versioner/testdata/scenarioe/foo/stage/foo.go, tools/versioner/testdata/scenariof/foo/stage/foo.go
Updates to existing modules will generate a changelog in the module
directory; new modules won't contain a changelog.
Refactor package report generation to its own package.
=> Add changelog generation to the versioner tool

storage/client.go, storage/client_test.go
original [pr](https://github.com/Azure/azure-sdk-for-go/pull/4854) which carries a bunch of AutoPR and generated commit is closed. sorry for my mistake. 
the go sdk checks for [spr parameter](https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1#parameters-common-to-account-sas-and-service-sas-tokens), but when it comes to tokens generated from Storage Explorer, there is no such spr parameter, and the sdk get empty string for spr. so after compares empty string and "https", it [sets useHTTPS to false](https://github.com/Azure/azure-sdk-for-go/blob/master/storage/client.go#L374), while it actually needs to set it to true
this patch just altered that and I add a test case. the test account has been deleted to prevent malformed requests but the …
=> fix a bug when spr parameter is missing

profiles/preview/preview/cognitiveservices/formrecognizer/models.go, services/preview/cognitiveservices/v1.0/formrecognizer/client.go, services/preview/cognitiveservices/v1.0/formrecognizer/formrecognizerapi/interfaces.go, services/preview/cognitiveservices/v1.0/formrecognizer/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6042
=> [AutoPR cognitiveservices/data-plane/FormRecognizer] FormRecognizerReceipt - Initial Commit.

services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6150
=> [AutoPR hdinsight/resource-manager] [HDInsight] Fix specs not support subdomainsuffix parameter

services/cdn/mgmt/2019-04-15/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6192
=> [AutoPR cdn/resource-manager] typo: Double word "use"

profiles/preview/preview/cognitiveservices/formrecognizer/models.go, services/preview/cognitiveservices/v1.0/formrecognizer/client.go, services/preview/cognitiveservices/v1.0/formrecognizer/formrecognizerapi/interfaces.go, services/preview/cognitiveservices/v1.0/formrecognizer/models.go
Created to accumulate context: cognitiveservices/data-plane/FormRecognizer
=> [AutoPR] cognitiveservices/data-plane/FormRecognizer

.gitignore, profiles/2017-03-09/definition.json, profiles/2018-03-01/definition.json, profiles/2019-03-01/definition.json, tools/internal/dirs/dirs.go, tools/internal/dirs/dirs_test.go, tools/internal/modinfo/modinfo.go, tools/internal/modinfo/modinfo_test.go, tools/profileBuilder/cmd/latest.go, tools/profileBuilder/cmd/list.go, tools/profileBuilder/cmd/list_test.go, tools/profileBuilder/cmd/root.go, tools/profileBuilder/model/aliasPackage.go, tools/profileBuilder/model/latest.go, tools/profileBuilder/model/latest_test.go, tools/profileBuilder/model/paths.go, tools/profileBuilder/model/paths_test.go, tools/profileBuilder/model/transforms.go, tools/profileBuilder/model/transforms_test.go, tools/versioner/cmd/root.go, tools/versioner/cmd/root_test.go
Added 'modules' flag to profileBuilder to run in module-aware mode.  For
the latest/preview profiles this means that it will include module major
versions in its comparison algorithm.
For static profiles (i.e. 2017-03-09 etc) a new major version of an
included module will result in a new major version for that profile.
Moved some code into central packages (modinfo) to be shared across
tools.
Added additional tests to various functions.
Cleaned up white-space in profile definitions.
=> Update profile builder to understand modules

profiles/latest/alertsmanagement/mgmt/alertsmanagement/models.go, profiles/preview/alertsmanagement/mgmt/alertsmanagement/models.go, services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/alertsmanagementapi/interfaces.go, services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/models.go, services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/smartgroups.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6198
=> [AutoPR alertsmanagement/resource-manager] Updated swagger spec for stable/2018-05-05 version

services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6259
=> [AutoPR hanaonazure/resource-manager] Microsoft.HanaOnAzure: Remove readOnly attribute from customer-provided properties in CreateHanaInstance

services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6287
=> [AutoPR hdinsight/resource-manager] [HDInsight] Fix syntax error in description of subDomainSuffix parameter

profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6158
=> [AutoPR hdinsight/resource-manager] HDI add autoscale feature support

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6396
=> [AutoPR datafactory/resource-manager] fix public swagger issues

profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/hdinsightapi/interfaces.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/locations.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/hdinsightapi/interfaces.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/locations.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6360
=> [AutoPR hdinsight/resource-manager] [HDInsight] Add ListBillingSpecs API to HDInsight's  stable and preview version

services/preview/monitor/mgmt/2017-05-01-preview/insights/activitylogs.go, services/preview/monitor/mgmt/2018-03-01/insights/activitylogs.go, services/preview/monitor/mgmt/2018-03-01/insights/models.go, services/preview/monitor/mgmt/2018-09-01/insights/activitylogs.go, services/preview/monitor/mgmt/2018-09-01/insights/models.go, services/preview/monitor/mgmt/2018-11-01-preview/insights/activitylogs.go, services/preview/monitor/mgmt/2018-11-01-preview/insights/models.go, services/preview/monitor/mgmt/2019-03-01/insights/activitylogs.go, services/preview/monitor/mgmt/2019-03-01/insights/models.go, services/preview/monitor/mgmt/2019-06-01/insights/activitylogs.go, services/preview/monitor/mgmt/2019-06-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6485
=> [AutoPR monitor/resource-manager] BUG fix: Fixing type of MetricValue.Count to be double instead of the incorrect int64 it had before

README.md
=> add documentation for retry policy

services/resources/mgmt/2018-06-01/subscriptions/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6473
=> [AutoPR resources/resource-manager] Add missing displayName and domains properties to response of Tenants_List call

profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6614
=> [AutoPR securityinsights/resource-manager] Add data connector kinds AzureAdvancedThreatProtection and MicrosoftDefenderAdvancedThreatProtection.

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6686
=> [AutoPR datafactory/resource-manager] fix: datafactory character encoding

README.md, azure-pipelines.yml, storage/file.go, tools/apidiff/cmd/packages.go, tools/apidiff/delta/delta_test.go, tools/apidiff/exports/package_test.go, tools/deprecate/cmd/package.go, tools/profileBuilder/model/latest.go, tools/profileBuilder/model/latest_test.go, tools/profileBuilder/model/paths_test.go, tools/versioner/cmd/root_test.go
=> Cherry-pick Azure devops changes

profiles/preview/preview/security/mgmt/security/models.go, services/preview/security/mgmt/v3.0/security/models.go
Created to accumulate context: security/resource-manager
=> [AutoPR] security/resource-manager

profiles/latest/appinsights/mgmt/insights/models.go, profiles/preview/appinsights/mgmt/insights/models.go, services/appinsights/mgmt/2015-05-01/insights/annotations.go, services/appinsights/mgmt/2015-05-01/insights/insightsapi/interfaces.go, services/appinsights/mgmt/2015-05-01/insights/models.go, services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6636
=> [AutoPR applicationinsights/resource-manager] fix: applicationinsights delete examples

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6816
=> [AutoPR datafactory/resource-manager] Enable Avro Dataset in public swagger

profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6785
=> [AutoPR hdinsight/resource-manager] [HDInsight] Change accessModes and applicationType from enum to string

tools/apidiff/repo/repo.go, tools/internal/modinfo/modinfo.go, tools/internal/modinfo/modinfo_test.go, tools/versioner/cmd/root.go
Return empty slice when no tags are found.
Added module version string validation.
Added optional arg 'initial module version' to versioner tool.
=> Tooling fixes

tools/apidiff/repo/repo.go, tools/major-updater/cmd/afterscripts.go, tools/major-updater/cmd/autorest.go, tools/major-updater/cmd/common.go, tools/major-updater/cmd/dep.go, tools/major-updater/cmd/root.go, tools/major-updater/cmd/updateSDK.go, tools/major-updater/cmd/updateSpecs.go, tools/major-updater/cmd/work.go, tools/major-updater/main.go
This is a tool I wrote which tries to accumulate the major version release operations in one command
=> Major updater tool

doc.go
This PR updates any links in the github repo to the documentation site since old links may now 404. This PR is against the `master` branch since that is where godoc builds from, and it appears that the `docs.go` file is not contained in `latest`.
---
=> Fix links to docs site

profiles/latest/cognitiveservices/qnamaker/models.go, profiles/preview/cognitiveservices/qnamaker/models.go, services/cognitiveservices/v4.0/qnamaker/models.go
Created to accumulate context: cognitiveservices/data-plane/QnAMaker
=> [AutoPR] cognitiveservices/data-plane/QnAMaker

profiles/latest/datamigration/mgmt/datamigration/models.go, profiles/preview/datamigration/mgmt/datamigration/models.go, profiles/preview/preview/datamigration/mgmt/datamigration/models.go, services/datamigration/mgmt/2018-04-19/datamigration/models.go, services/preview/datamigration/mgmt/2017-11-15-preview/datamigration/models.go, services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/models.go, services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6971
=> [AutoPR datamigration/resource-manager] Fix bad discriminator value on ConnectionInfo for node/js SDK

services/preview/storage/datalake/2018-06-17/storagedatalake/filesystem.go, services/preview/storage/datalake/2018-06-17/storagedatalake/path.go, services/storage/datalake/2018-11-09/storagedatalake/filesystem.go, services/storage/datalake/2018-11-09/storagedatalake/path.go
This PR is to solve a issue introduced by http base URL in storagedatalake (aka. storage dfs) api, for now if we use the bearer token to call `http` api without `https` (aka. tls), the storage dfs service will respond some error like:
```
{
"error": {
"code": "AuthenticationFailed",
"message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:65fca257-e01f-011c-3eb9-576491000000\nTime:2019-08-21T00:41:26.9881685Z"
}
}
```
After changing into `https` this will be resolved.
=> datalakegen2 endpoints require https

profiles/2017-03-09/generate.go, profiles/2018-03-01/generate.go, profiles/2019-03-01/generate.go, profiles/latest/generate.go, profiles/preview/generate.go, tools/profileBuilder/cmd/latest.go, tools/profileBuilder/cmd/list.go
=> Change log level of profile builder from verbose to normal

services/network/mgmt/2018-07-01/network/models.go, services/network/mgmt/2018-08-01/network/models.go, services/network/mgmt/2018-10-01/network/models.go, services/network/mgmt/2018-11-01/network/models.go, services/network/mgmt/2018-12-01/network/models.go, services/network/mgmt/2019-02-01/network/models.go, services/network/mgmt/2019-04-01/network/models.go, services/network/mgmt/2019-04-01/network/privateendpoints.go, services/network/mgmt/2019-04-01/network/privatelinkservices.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6908
=> [AutoPR network/resource-manager] Add missing read-only property "outboundRules" in LoadBalancer specs

profiles/latest/servicebus/mgmt/servicebus/models.go, profiles/preview/servicebus/mgmt/servicebus/models.go, services/servicebus/mgmt/2017-04-01/servicebus/models.go, services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go, services/servicebus/mgmt/2017-04-01/servicebus/rules.go, services/servicebus/mgmt/2017-04-01/servicebus/servicebusapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7050
=> [AutoPR servicebus/resource-manager] ServiceBus: added NetworkRuleSets list API

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/activityruns.go
Created to accumulate context: datafactory/resource-manager
=> [AutoPR] datafactory/resource-manager

services/datalake/analytics/2016-11-01-preview/catalog/models.go, services/preview/datalake/analytics/2015-10-01-preview/catalog/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7181
=> [AutoPR datalake-analytics/data-plane] fix: Double word "the" in datalake-analytics

services/automation/mgmt/2015-10-31/automation/dsccompilationjob.go, services/automation/mgmt/2015-10-31/automation/dscconfiguration.go, services/preview/automation/mgmt/2017-05-15-preview/automation/dsccompilationjob.go, services/preview/automation/mgmt/2017-05-15-preview/automation/dscconfiguration.go, services/preview/automation/mgmt/2018-01-15-preview/automation/dsccompilationjob.go, services/preview/automation/mgmt/2018-01-15-preview/automation/dscconfiguration.go, services/preview/automation/mgmt/2018-01-15-preview/automation/dscnode.go, services/preview/automation/mgmt/2018-01-15-preview/automation/dscnodeconfiguration.go, services/preview/automation/mgmt/2018-06-30-preview/automation/dsccompilationjob.go, services/preview/automation/mgmt/2018-06-30-preview/automation/dscconfiguration.go, services/preview/automation/mgmt/2018-06-30-preview/automation/dscnode.go, services/preview/automation/mgmt/2018-06-30-preview/automation/dscnodeconfiguration.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7180
=> [AutoPR automation/resource-manager] fix: Double word "the" in automation

profiles/preview/preview/reservations/mgmt/reservations/models.go, services/preview/reservations/mgmt/2019-04-01/reservations/client.go, services/preview/reservations/mgmt/2019-04-01/reservations/models.go, services/preview/reservations/mgmt/2019-04-01/reservations/order.go, services/preview/reservations/mgmt/2019-04-01/reservations/reservationsapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7206
=> [AutoPR reservations/resource-manager] [Hub Generated] Review request for Microsoft.Capacity to add version preview/2019-04-01

README.md
=> update README with info on customizing SendDecorators

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/storage/mgmt/2019-04-01/storage/accounts.go, services/storage/mgmt/2019-04-01/storage/models.go, services/storage/mgmt/2019-04-01/storage/storageapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7237
=> [AutoPR storage/resource-manager] [SRP] Add nextLink to StorageAccountList

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/storage/mgmt/2019-04-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7326
=> [AutoPR storage/resource-manager] [SRP] Add new storage account property largeFileSharesState

profiles/latest/cdn/mgmt/cdn/models.go, profiles/preview/cdn/mgmt/cdn/models.go, services/cdn/mgmt/2019-04-15/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7367
=> [AutoPR cdn/resource-manager] Add two match condition for CDN RulesEngine.

profiles/preview/preview/eventhub/mgmt/eventhub/models.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7149
=> [AutoPR eventhub/resource-manager] Eventhub: Added Namespace properties for BYOK

profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/models.go, services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go, services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/sqlvirtualmachineapi/interfaces.go, services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/sqlvirtualmachines.go
Created to accumulate context: sqlvirtualmachine/resource-manager
=> [AutoPR] sqlvirtualmachine/resource-manager

services/compute/mgmt/2019-03-01/compute/models.go, services/compute/mgmt/2019-07-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7246
=> [AutoPR compute/resource-manager] VMSS: exposing the `requireGuestProvisionSignal` field for `2019-03-01`

profiles/latest/advisor/mgmt/advisor/models.go, profiles/preview/advisor/mgmt/advisor/models.go, services/advisor/mgmt/2017-03-31/advisor/models.go, services/advisor/mgmt/2017-04-19/advisor/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7495
=> [AutoPR advisor/resource-manager] [Advisor] Add OperationalExcellence category to enum list.

sdk/azcore/core.go, sdk/azcore/doc.go, sdk/azcore/error.go, sdk/azcore/log.go, sdk/azcore/policy_body_download.go, sdk/azcore/policy_default_http_client.go, sdk/azcore/policy_retry.go, sdk/azcore/policy_shared_key_credential.go, sdk/azcore/policy_telemetry.go, sdk/azcore/policy_token_credential.go, sdk/azcore/policy_unique_request_id.go, sdk/azcore/request.go, sdk/azcore/response.go
added/fixed various export comments
fixed up receivers by-val and by-ref
implemented stateless policies as first-class funcs
rewrote the retry policy to be generic and always retry on errors
=> refactoring and clean-up

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7437
=> [AutoPR datafactory/resource-manager] [DataFactory]Add Dynamics Server-toServer authentication type.

profiles/latest/cdn/mgmt/cdn/models.go, profiles/preview/cdn/mgmt/cdn/models.go, services/cdn/mgmt/2019-04-15/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7441
=> [AutoPR cdn/resource-manager] [CDN] Add missing customHttpsParameters field of CustomDomainProperties.

services/network/mgmt/2019-04-01/network/models.go, services/network/mgmt/2019-06-01/network/models.go, services/network/mgmt/2019-07-01/network/models.go, services/network/mgmt/2019-08-01/network/models.go, services/network/mgmt/2019-09-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7672
=> [AutoPR network/resource-manager] Fix the typo for actionsRequired in PrivateLinkServiceConnectionState.

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, profiles/preview/preview/sql/mgmt/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7646
=> [AutoPR datafactory/resource-manager] Add Properties for ssis embedded package

profiles/preview/preview/timeseriesinsights/mgmt/timeseriesinsights/models.go, services/preview/timeseriesinsights/mgmt/2018-08-15-preview/timeseriesinsights/environments.go, services/preview/timeseriesinsights/mgmt/2018-08-15-preview/timeseriesinsights/models.go, services/preview/timeseriesinsights/mgmt/2018-08-15-preview/timeseriesinsights/timeseriesinsightsapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7643
=> [AutoPR timeseriesinsights/resource-manager] updating with warm store features

sdk/azidentity/chained_token_credential.go, sdk/azidentity/client_secret_credential.go
uses double-checked lock when updating bearer token
=> only retrieve bearer token when expired

services/containerservice/mgmt/2019-06-01/containerservice/agentpools.go, services/containerservice/mgmt/2019-08-01/containerservice/agentpools.go, services/containerservice/mgmt/2019-10-01/containerservice/agentpools.go, services/preview/containerservice/mgmt/2019-09-30-preview/containerservice/agentpools.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7746
=> [AutoPR containerservice/resource-manager] AKS: making the `count` field optiona;

sdk/azcore/core.go, sdk/storage/azblob/examples_test.go, sdk/storage/azblob/go.mod, sdk/storage/azblob/internal/azblob/models.go, sdk/storage/azblob/internal/azblob/service.go, sdk/storage/azblob/models.go, sdk/storage/azblob/service.go
move generated code to internal package
simplified codegen to contain only request creation/response handling
internal types are exposed via type aliasing in the public package
updated page iterator per latest discussion
=> refactor azblob

storage/blob.go, storage/directory.go
Not sure this warrants a Change Log entry to be honest. I've just created a series of PRs across the board for products involved with Hashicorp Vault.
Will update Change Log if requested of course.
=> Simple grammar fix

services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/appplatformapi/interfaces.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/apps.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/bindings.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/deployments.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/services.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7874
=> [AutoPR appplatform/resource-manager] Change the order of parameters in `appplatform` to comply the convention in SDK

sdk/azidentity/bearer_token_policy.go, sdk/azidentity/bearer_token_policy_test.go
also avoids using an expired token
fixed up some bearar authorizer tests
redo of https://github.com/Azure/azure-sdk-for-go/pull/6435
=> improved token refresh logic

sdk/ci.yml
prevent track1 CI from running on track2 changes
omit track2 content from track1 CI
added pipeline specific to track2
=> track2 CI fixes

profiles/latest/frontdoor/mgmt/frontdoor/frontdoorapi/models.go, profiles/latest/frontdoor/mgmt/frontdoor/models.go, profiles/preview/frontdoor/mgmt/frontdoor/frontdoorapi/models.go, profiles/preview/frontdoor/mgmt/frontdoor/models.go
=> Generate profiles

sdk/ci.yml, sdk/internal/atomic/atomic.go, sdk/internal/go.mod, sdk/internal/mock/mock.go, sdk/internal/uuid/uuid.go
This brings the `sdk/internal` module to master along with the requisite CI changes.
This module needs to be ported first since `azcore` has a dependency on it.
=> Internal master

sdk/azcore/core.go, sdk/azcore/credential.go, sdk/azcore/doc.go, sdk/azcore/error.go, sdk/azcore/go.mod, sdk/azcore/go.sum, sdk/azcore/headers.go, sdk/azcore/log.go, sdk/azcore/log_test.go, sdk/azcore/policy_anonymous_credential.go, sdk/azcore/policy_anonymous_credential_test.go, sdk/azcore/policy_body_download.go, sdk/azcore/policy_body_download_test.go, sdk/azcore/policy_logging.go, sdk/azcore/policy_logging_test.go, sdk/azcore/policy_retry.go, sdk/azcore/policy_retry_test.go, sdk/azcore/policy_telemetry.go, sdk/azcore/policy_telemetry_test.go, sdk/azcore/policy_unique_request_id.go, sdk/azcore/policy_unique_request_id_test.go, sdk/azcore/progress.go, sdk/azcore/progress_test.go, sdk/azcore/request.go, sdk/azcore/request_test.go, sdk/azcore/response.go, sdk/azcore/response_test.go, sdk/azcore/transport_default_http_client.go, sdk/azcore/version.go, sdk/ci.yml
update internal module dependency
remove golint from CI
=> copy azcore to master

sdk/azcore/credential.go, sdk/azidentity/aad_identity_client.go, sdk/azidentity/aad_identity_client_test.go, sdk/azidentity/azidentity.go, sdk/azidentity/azidentity_test.go, sdk/azidentity/bearer_token_policy_test.go, sdk/azidentity/chained_token_credential.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/default_token_credential.go, sdk/azidentity/default_token_credential_test.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/device_code_credential_test.go, sdk/azidentity/environment_credential.go, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go, sdk/azidentity/username_password_credential.go, sdk/azidentity/username_password_credential_test.go, sdk/storage/blob/2018-11-09/azblob/examples_test.go
This PR includes: 
- Adding DeviceCodeCredential and corresponding unit/mock tests  #6433
- Adding MSI Access Token parsing to include ExpiresOn cases #6350
- Updating error handling for ChainedTokenCredential
- Fixed MSI tests to use MSI specific scopes
- Added IMDS request creation test
- Updated DefaultTokenCredential chain creation
- Updated MSI type const names
- Removed ChainedCredentialError #6549
=> Adding DeviceCodeCredential, MSI Access Token creation, fixed error handling in ChainedTokenCredential

profiles/preview/preview/eventgrid/mgmt/eventgrid/eventgridapi/models.go, profiles/preview/preview/eventgrid/mgmt/eventgrid/models.go
=> 2020-04-preview

sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/default_token_credential.go, sdk/azidentity/default_token_credential_test.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go
Updated ManagedIdentityCredential constructor to check for MSI environment upon creation. Also updated tests and other references to Managed Identity Credential
=> Update ManagedIdentityCredential constructor

sdk/azcore/policy_body_download.go, sdk/azcore/policy_body_download_test.go, sdk/azcore/request.go, sdk/azcore/request_test.go, sdk/azcore/response.go, sdk/azcore/response_test.go
Removed Response.Payload field, replacing it with an internal
implementation nopClosingBytesReader.
=> Add support for marshalling/unmarshalling JSON

sdk/azcore/policy_retry.go, sdk/azcore/policy_retry_test.go, sdk/azcore/response.go, sdk/azcore/response_test.go
Added DefaultRetryOptions() to create initialized default options.
Removed Response.CheckStatusCode() as it can't create custom errors.
=> Some refactoring in azcore

sdk/ci.yml
=> add test results and code coverage to track2 CI

sdk/azidentity/chained_token_credential_test.go, sdk/internal/mock/mock.go
Adding a test to check for CredentialUnavailable errors in the ChainedTokenCredential test suite. 
Also adding a function to append errors as responses for the test server.
=> Track2 chainedcredentialtest

sdk/azcore/headers.go, sdk/azcore/policy_logging_test.go, sdk/azcore/policy_retry.go, sdk/azcore/policy_retry_test.go, sdk/azcore/request.go, sdk/azcore/response.go, sdk/azcore/response_test.go
Added WithRetryOptions() that adds a custom RetryOptions to the provided
context, allowing custom settings per API call.
Remove 429 from the list of default HTTP status codes for retry.
Change StatusCodesForRetry to a slice so consumers can append to it.
=> Enable custom RetryOptions to be specified per API call

sdk/to/go.mod, sdk/to/to.go
=> add `to` module

sdk/azcore/log.go, sdk/azcore/policy_retry.go, sdk/azcore/request.go
Explicitly call cancel the per-try timeout when the response body has
been read/closed by the body download policy.
When the response body is returned to the caller for reading/closing,
wrap it in a responseBodyReader that will cancel the timeout when the
body is closed.
Logger.Should() will return false if no listener is set.
=> Ensure per-try timeout is properly cancelled

swagger_to_sdk_config.json
=> Fix SDK Automation Failure

storage/entity.go
e.Table.tsc.client.exec can return nil resp and non-nil err. This causes
resp.StatusCode to crash with nil dereference. This change adds the
nil check on resp before accessing StatusCode.
=> Fix nil dereference error

storage/client.go, storage/entity.go, storage/recordings/StorageEntitySuite/TestDelete.yaml, storage/recordings/StorageEntitySuite/TestGet.yaml, storage/recordings/StorageEntitySuite/TestInsertOrMerge.yaml, storage/recordings/StorageEntitySuite/TestInsertOrReplace.yaml, storage/recordings/StorageEntitySuite/TestMerge.yaml, storage/recordings/StorageEntitySuite/TestUpdate.yaml, storage/recordings/StorageEntitySuite/Test_InsertAndDeleteEntities.yaml, storage/recordings/TableBatchSuite/Test_BatchInsertMultipleEntities.yaml, storage/recordings/TableBatchSuite/Test_BatchInsertThenDeleteDifferentBatches.yaml, storage/recordings/TableBatchSuite/Test_BatchInsertThenMergeDifferentBatches.yaml
This change allows azure-sdk-for-go to send the requests to
cosmosdb table API. It exposes a new method as AddAdditionalHeaders
which allows users to specify cosmosdb specific headers.
This change allows users to use azure-sdk-for-go to connect to and use
cosmosdb table storage. 
=> Handle cosmosdb table API requests

sdk/azcore/core.go, sdk/azcore/transport_default_http_client.go
Needed to simplify creation of custom HTTP transports.
Removed IterationDone as it's not used.
=> Export transportFunc

eng/pipelines/templates/steps/build-test.yml, sdk/storage/blob/2019-07-07/azblob/blockblob.go, sdk/storage/blob/2019-07-07/azblob/examples_test.go
refactor credentials to use environment credential
build endpoints specific to the examples
added dummy block blob content
added // Output clauses when running examples
=> base-64 encode block ID

sdk/storage/blob/2019-07-07/azblob/blockblob.go, sdk/storage/blob/2019-07-07/azblob/examples_test.go
Updated block blobs with latest codegen, reverting hand edits.
Fixed block blob sample based on codegen.
Fixed pathJoin to omit trailing '/'
=> Fix block blob operations

sdk/azcore/policy_retry.go, sdk/azcore/response.go, sdk/azcore/response_test.go
Since azcore.Response isn't directly exposed to callers they cannot use
this convenience method.  Changed it to a function.
=> Change RetryAfter() to a function

sdk/azcore/request.go, sdk/azcore/request_test.go, sdk/azcore/response.go, sdk/azcore/response_test.go
=> Add support for base-64 encoding and decoding of payloads

sdk/azcore/request.go, sdk/azcore/request_test.go, sdk/azcore/response.go, sdk/azcore/response_test.go
Swagger specifies 'byte' format for standard base-64 encoding and
'base64url' for base-64 URL encoding.  Update the byte array encoder
and decoder to specify which type to use.
=> Differentiate between standard and URL encoding

sdk/azidentity/default_azure_credential.go, sdk/azidentity/default_azure_credential_test.go
This PR renames DefaultTokenCredential to DefaultAzureCredential.
=> Renaming DefaultTokenCredential to DefaultAzureCredential

sdk/arm/network/2020-03-01/armnetwork/example_firewallpolicies_test.go, sdk/arm/network/2020-03-01/armnetwork/go.mod
This PR includes:
- Example for creating a FirewallPolicy
- Example for create a FirewallPolicyRuleGroup that first creates a resource group that will then have the firewall resources added to it. This example also uses FirewallPolicyRuleClassifications which are discriminated types and also uses the previously created FirewallPolicy for the FirewallPolicyRuleGroup.
- Example for deleting FirewallPolicyRuleGroup
- Example for deleting a ResourceGroup with a manual example for polling
=> Adding firewall policies sample with more complex examples

sdk/azidentity/aad_identity_client.go, sdk/azidentity/azidentity.go, sdk/azidentity/azure_cli_credential.go, sdk/azidentity/azure_cli_credential_test.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/managed_identity_credential.go
This PR ports the track1 CLI Credential implementation to track2 format, so that users can use the token provided when authenticating with the CLI.
=> Add initial work for CLI Credential

sdk/azcore/policy_body_download.go, sdk/azcore/policy_logging.go, sdk/azcore/policy_retry_test.go, sdk/azcore/progress_test.go, sdk/azcore/response.go
Only remaining issues is code in error.go.
=> Misc clean-up reported by golangci-lint

sdk/internal/mock/mock.go
WithSlowResponse() to simulate a slow HTTP response.
WithBodyReadError() returns an HTTP response that fails when reading the
body.
Fixed a bug with writing response headers.
=> Added new response mocking behavior

sdk/azidentity/aad_identity_client.go, sdk/azidentity/device_code_credential_test.go
This PR fixes a problem where the request path for a refresh token was in conflict with the previous request path set in the DeviceCodeCredential flow. Changes request creation to make a copy of the authority host in all of the requests related to DeviceCodeCredential, instead of changing the value on the credential.
=> Bug fix for conflicting request paths in DeviceCodeCredential

sdk/azidentity/aad_identity_client_test.go, sdk/azidentity/azidentity.go, sdk/azidentity/azure_cli_credential_test.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/device_code_credential_test.go
This PR increases test coverage for untested paths in Azure Identity. Increases package test coverage to 81.3%.
=> Azure Identity add more test coverage

sdk/azidentity/aad_identity_client.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/username_password_credential.go
Changing authority host path changes to a copy off of the authority host set in the credential, instead of changing authority host on the credential.
=> Azure Identity code improvements: Authority Host and path parsing

sdk/internal/runtime/frame_error.go, sdk/internal/runtime/frame_error_test.go, sdk/internal/runtime/response_error.go, sdk/internal/runtime/runtime.go, sdk/internal/runtime/runtime_test.go
Added NewFrameError() for wrapping errors with stack frame information.
Added NewResponseError() for wrapping errors and/or failed HTTP requests
with the underlying HTTP response.
=> Add new error types to sdk/internal/runtime package

sdk/internal/runtime/frame_error.go, sdk/internal/runtime/response_error.go
Export FrameError so it can be used for type assertions in test cases
outside the internal module.
Renamed Response() method to RawResponse() per new guidelines.
=> Fixes to sdk/internal/runtime

sdk/azcore/error.go, sdk/azcore/go.mod, sdk/azcore/go.sum
To be used by callers to access the raw HTTP response from an error in
the event of an API call failure.
Updated sdk/internal dependency to latest version.
=> Add HTTPResponse interface

sdk/armcore/go.mod, sdk/armcore/go.sum, sdk/armcore/policy_register_rp.go, sdk/armcore/policy_register_rp_test.go
This adds the armcore module with the automatic RP registration policy
which is specific to ARM.
=> Add armcore module for ARM-specific content

azure-pipelines.yml, eng/pipelines/templates/steps/build-test.yml, eng/pipelines/templates/steps/set-scope.yml, eng/scripts/get_module_dirs.ps1, eng/scripts/get_test_dirs.ps1, eng/scripts/scoped_discover.ps1
=> Build track 2 content in module-aware mode

eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/steps/build-test.yml, sdk/armcore/ci.yml, sdk/azcore/ci.yml, sdk/internal/ci.yml, sdk/to/ci.yml
This will enable us to shift from
`track 2 CI builds All sdk/...` TO `track 2 CI builds only the sdk/<service> where files have been affected`.
@jhendrixMSFT
=> Add service-level builds for track 2 sdk-for-go

sdk/internal/mock/mock.go, sdk/internal/mock/mock_test.go
Fixed a race condition when accessing the response stack.
Fixed a nil dereference when adding response headers.
Added missing tests.
Build and vet all child packages in CI.
=> Fixes to mock package

sdk/internal/mock/mock.go, sdk/internal/mock/mock_test.go
=> Fix nil pointer dereference for mock TLS server

sdk/azcore/request.go, sdk/azcore/request_test.go
If any field in a payload's object graph contains `azure:"ro"`, make a
clone of the object graph, omitting all fields with this annotation.
=> Omit read-only content from request payloads

sdk/azcore/core.go, sdk/azcore/go.mod, sdk/azcore/go.sum, sdk/azcore/policy_http_header.go, sdk/azcore/policy_http_header_test.go
Inserts an internal policy into the pipeline that can extract HTTP
header values from the caller's context, adding them to the request.
Use azcore.WithHTTPHeader to add HTTP headers to a context.
=> Add support for custom HTTP request headers

swagger_to_sdk_config.json
- Update `autorest.go` to `v2.1.153` to avoid some unexpect NPE when `namespace` is not set or not detected.
- Update `autorest.core` to `v2` instead of `previous` to catch the latest swagger definitions
=> Update autorest.go and autorest.core version to unblock the generation on some new swaggers

sdk/azcore/request.go, sdk/azcore/request_test.go
Even though the underlying transport will set this header, some
operations depend on this being available earlier (string-to-sign).
=> Set the Content-Length header in Request.SetBody

sdk/azidentity/username_password_credential.go
=> Removing azcore.TokenCredential reference from UsernamePasswordCredential

sdk/azidentity/aad_identity_client.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/fingerprint.go, sdk/azidentity/go.mod, sdk/azidentity/go.sum, sdk/azidentity/jwt.go
This is to keep parity with track 1 that only supported PFX.
Moved reading and parsing of certificate data into the
NewClientCertificateCredential constructor so it will fail earlier.
Fixed an issue with certificates containing intermediate authorities.
=> Add support for PFX files

sdk/azcore/policy_telemetry.go, sdk/azcore/policy_telemetry_test.go
Add support for application ID string.
Preserve any existing user-agent string data.
Add flag to disable telemetry info.
=> Improvements to telemetry policy

sdk/azcore/policy_body_download.go, sdk/azcore/policy_body_download_test.go
Always download the response body for error responses, i.e. HTTP status
codes >= 400.
=> Improvements to body download policy

tools/profileBuilder/cmd/latest.go, tools/profileBuilder/cmd/list.go, tools/profileBuilder/model/transforms.go
Makes the `profileBuilder` could ignore some certain directories when it is clearing output folder. The new requirement of profiles contains some combination of swaggers that is not present in the go SDK repo now (also its package version is occupied), therefore we should directly generate this profile using autorest, and let profileBuilder to ignore it when it is clearing output folder.
=> add `ignoredPaths` to profileBuilder

sdk/azidentity/default_azure_credential.go, sdk/azidentity/default_azure_credential_test.go
=> Adding AzureCLICredential to the DefaultAzureCredential chain

sdk/internal/mock/mock.go, sdk/internal/mock/mock_test.go
Make URL() return a string to align with pending azcore changes.
Server.Do() no longer takes a context as the context is on the request.
=> Updates to internal/mock package

sdk/azcore/core.go, sdk/azcore/error.go, sdk/azcore/go.mod, sdk/azcore/go.sum, sdk/azcore/policy_anonymous_credential.go, sdk/azcore/policy_anonymous_credential_test.go, sdk/azcore/policy_body_download.go, sdk/azcore/policy_body_download_test.go, sdk/azcore/policy_http_header.go, sdk/azcore/policy_http_header_test.go, sdk/azcore/policy_logging.go, sdk/azcore/policy_logging_test.go, sdk/azcore/policy_retry.go, sdk/azcore/policy_retry_test.go, sdk/azcore/policy_telemetry.go, sdk/azcore/policy_telemetry_test.go, sdk/azcore/policy_unique_request_id.go, sdk/azcore/policy_unique_request_id_test.go, sdk/azcore/progress_test.go, sdk/azcore/request.go, sdk/azcore/request_test.go, sdk/azcore/response_test.go, sdk/azcore/transport_default_http_client.go, sdk/azcore/version.go
The request and transport interfaces have been refactored to align with
the patterns in the standard library.
NewRequest() now uses http.NewRequestWithContext() and performs
additional validation.  It requires a context parameter.
The Policy and Transport interfaces have had their ctx parameter removed
as the context is associated with the underlying http.Request.
Pipeline.Do() will validate the HTTP request before sending it through
the pipeline, avoiding retrying on an malformed request.
The Retrier interface has been replaced with the NonRetriableError
interface, and the retry policy updated to test for this.
Request.SetBody() now requires a content type parameter for setting the
request's MIME type.
=> Refactor azcore public surface area

sdk/armcore/poller.go, sdk/armcore/poller_test.go
Added internal poller type to implement the Poller interface.  This
allows removal of duplicated code across trackers into the poller type.
=> Poller clean-up

sdk/azidentity/azidentity.go, sdk/azidentity/default_azure_credential_test.go, sdk/azidentity/environment_credential_test.go, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go
This PR adds support for App Service api-version 2019-08-01 in ManagedIdentityCredential, as well as cleans up redundant code in the same credential type. 
Add missing MaxRetryDelay to MSI credential pipelines.
=> Add new App Service version and improve Managed Identity Credential

sdk/azcore/log.go, sdk/azcore/log_test.go, sdk/azcore/policy_retry.go, sdk/azcore/version.go
Default console logger writes to stderr.  To enable it, set env var
AZURE_SDK_GO_LOGGING to the value 'all'.
Added Logger.Writef() to reduce the need for ShouldLog() checks.
=> Add default console logger

sdk/azidentity/azidentity.go, sdk/azidentity/azure_cli_credential.go, sdk/azidentity/azure_cli_credential_test.go, sdk/azidentity/bearer_token_policy_test.go, sdk/azidentity/chained_token_credential.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/default_azure_credential.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/device_code_credential_test.go, sdk/azidentity/environment_credential.go, sdk/azidentity/go.mod, sdk/azidentity/go.sum, sdk/azidentity/logging.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go, sdk/azidentity/username_password_credential.go, sdk/azidentity/username_password_credential_test.go
Updated calls to azcore.NewRequestLogPolicy() to pass nil options.
Ensure logging calls are no-op when logging is disabled.
Removed some duplicate stack trace logging.
Updated logMSIEnv() with new value.
=> Logging clean-up

sdk/azidentity/device_code_credential.go, sdk/azidentity/device_code_credential_test.go
This PR updates the DeviceCodeCredential callback to include more of the information returned from the service, to provide users more flexibility in displaying information through the callback. 
#12686 based on review feedback.
=> Add more data in Device Code callback

sdk/azidentity/bearer_token_policy_test.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/environment_credential.go
This PR adds the rest of the options structs for azidentity.
=> Add options structs for ClientSecretCredential and EnvironmentCredential

sdk/azidentity/authorization_code_credential_test.go, sdk/azidentity/azidentity.go, sdk/azidentity/azidentity_test.go, sdk/azidentity/bearer_token_policy_test.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/device_code_credential_test.go, sdk/azidentity/go.mod, sdk/azidentity/go.sum, sdk/azidentity/interactive_browser_credential_test.go, sdk/azidentity/username_password_credential_test.go
This PR adds a check for Authority Hosts to ensure that all authority host urls provided are HTTPS, since non-https authority hosts are not permitted. 
Addresses #12686
=> Make sure authority hosts are https

README.md, azure-pipelines.yml
Fixed build status badge to point to correct branch.
Removed travis CI badge as we no longer use travis.
Removed report card badge as the service chokes on the size of the repo.
=> Fixed badges in README

sdk/azidentity/authorization_code_credential.go, sdk/azidentity/authorization_code_credential_test.go, sdk/azidentity/azidentity.go, sdk/azidentity/azidentity_test.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/device_code_credential_test.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/interactive_browser_credential_test.go, sdk/azidentity/username_password_credential.go, sdk/azidentity/username_password_credential_test.go
Validate tenant IDs passed to credential types after Arch Board discussion with the Identity crew, adding corresponding tests.
=> Validate tenant ID passed to credentials

sdk/armcore/README.md, sdk/armcore/connection.go, sdk/armcore/connection_test.go, sdk/armcore/doc.go, sdk/armcore/go.mod, sdk/armcore/go.sum, sdk/armcore/policy_register_rp.go
The Connection type will be used for managing connections to ARM.
Updated documentation with examples.
=> Add Connection type

sdk/armcore/connection.go, sdk/armcore/connection_test.go
LROs and pagers require access to the Connection's pipeline.
=> Replace Connection's Do() with Pipeline()

sdk/azidentity/bearer_token_policy.go, sdk/azidentity/bearer_token_policy_test.go
If GetToken() fails the renewing flag wasn't reset, leading to a
deadlock.  Ensure the flag is reset before exiting.
=> Fix deadlock in bearer token refresh

generate_options.json, tools/apidiff/delta/delta.go, tools/apidiff/delta/delta_test.go, tools/apidiff/exports/package.go, tools/apidiff/exports/package_test.go, tools/generator/autorest/autorest.go, tools/generator/autorest/package.go, tools/generator/autorest/package_test.go, tools/generator/changelog/changelog.go, tools/generator/changelog/export.go, tools/generator/changelog/git.go, tools/generator/cmd/root.go, tools/generator/main.go, tools/generator/model/model.go, tools/generator/testdata/2020-10-29/foo/client.go, tools/generator/testdata/2020-10-29/foo/models.go, tools/generator/testdata/2020-10-29/foo/version.go, tools/generator/testdata/2020-10-30/foo/client.go, tools/generator/testdata/2020-10-30/foo/models.go, tools/generator/testdata/2020-10-30/foo/version.go
Some introductions of the new SDK automation pipeline: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/sdkautomation/sdk_customization.md
=> Add generator tool to run in the sdk automation pipeline

sdk/azcore/core.go, sdk/azcore/policy_anonymous_credential.go, sdk/azcore/policy_body_download.go, sdk/azcore/policy_http_header.go
They are needlessly allocated on the heap.
=> Don't implement stateless polices as first-class funcs

sdk/armcore/connection.go, sdk/armcore/connection_test.go, sdk/armcore/policy_register_rp.go, sdk/armcore/policy_register_rp_test.go
Renamed DefaultEndpoint to AzurePublicCloud.
Added const for the sovereign clouds.
Construct token scope based on the cloud.
Updated NewRPRegistrationPolicy() to take an endpoint param.
=> Add support for clouds other than public

sdk/azidentity/aad_identity_client.go, sdk/azidentity/authorization_code_credential.go, sdk/azidentity/authorization_code_credential_test.go
To align with the MSAL implementation which relies on the native client
redirect URL.
=> Remove RedirectURL parameter from auth code flow

sdk/azcore/policy_body_download.go, sdk/azcore/policy_body_download_test.go, sdk/azcore/response.go, sdk/azcore/response_test.go
=> Adding Seek() method and updating payload()

sdk/armcore/go.mod, sdk/armcore/go.sum, sdk/armcore/poller.go, sdk/azcore/version.go
=> Bug fix: adding body back to response

sdk/azcore/policy_telemetry.go, sdk/azcore/policy_telemetry_test.go, sdk/azcore/version.go
=> Include telemetry string in User-Agent

sdk/armcore/connection.go, sdk/armcore/connection_test.go, sdk/armcore/go.mod, sdk/armcore/go.sum, sdk/armcore/policy_register_rp.go, sdk/armcore/policy_register_rp_test.go, sdk/armcore/version.go
=> Add telemetry string to User-Agent

sdk/azidentity/aad_identity_client.go, sdk/azidentity/aad_identity_client_test.go, sdk/azidentity/azidentity.go, sdk/azidentity/go.mod, sdk/azidentity/go.sum, sdk/azidentity/managed_identity_client_test.go, sdk/azidentity/version.go
Adding version.go for azidentity, along with assigning user agent for azidentity telemetry.
=> Adding UserAgent string for azidentity telemetry

swagger_to_sdk_config.json, tools/generator/autorest/autorest.go, tools/generator/changelog/export.go, tools/generator/cmd/root.go, tools/generator/model/model.go
Because in the definition of GenerateOutput, `packages` is required in the schema. Therefore we should never produce null packages, instead we should produce an empty array of packages when there is not any
=> Fix generator

sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential_test.go
This PR updates managed identity credential to parse both Windows and Linux datetime strings for tokens expires on values and also updates the client ID param for app service api-version 2017-09-01.
=> Update MSI App Service 2017 api-version 

sdk/azidentity/aad_identity_client.go, sdk/azidentity/authorization_code_credential.go, sdk/azidentity/authorization_code_credential_test.go
=> Add redirectURI param back to auth code flow

sdk/azcore/policy_logging.go, sdk/azcore/policy_logging_test.go, sdk/azcore/request.go, sdk/azcore/response.go
Added IncludeBody to LogOptions to enable logging of HTTP request and
response bodies.  The default is false and cannot be enabled by way of
environment variable.
=> Add ability to log request/response bodies

sdk/azidentity/aad_identity_client.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/interactive_browser_credential_test.go, sdk/azidentity/interactive_browser_server.go
Users may need to set a specific port for their localhost server. Enable that option and also check that the authority host for interactive browser is in the right format for the string format it is going to be added into.
Fixes #14052.
=> Adding port option for interactive browser

sdk/azidentity/azure_cli_credential.go
If there was no output written to stderr, fall back to the message from
the error.
=> Ensure CLI CredentialUnavailableError has a message

sdk/tools/apidiff/cmd/changelog.go, sdk/tools/apidiff/cmd/common.go, sdk/tools/apidiff/cmd/diff.go, sdk/tools/apidiff/cmd/export.go, sdk/tools/apidiff/cmd/package.go, sdk/tools/apidiff/cmd/packages.go, sdk/tools/apidiff/cmd/root.go, sdk/tools/apidiff/delta/delta.go, sdk/tools/apidiff/delta/delta_test.go, sdk/tools/apidiff/delta/testdata/breaking/new/new.go, sdk/tools/apidiff/delta/testdata/breaking/old/old.go, sdk/tools/apidiff/delta/testdata/nonbreaking/new/new.go, sdk/tools/apidiff/delta/testdata/nonbreaking/old/old.go, sdk/tools/apidiff/exports/exports.go, sdk/tools/apidiff/exports/package.go, sdk/tools/apidiff/exports/package_test.go, sdk/tools/apidiff/exports/testdata/td.go, sdk/tools/apidiff/main.go, sdk/tools/apidiff/markdown/markdown.go, sdk/tools/apidiff/markdown/markdown_test.go, sdk/tools/apidiff/repo/repo.go, sdk/tools/apidiff/report/package.go, sdk/tools/apidiff/report/packages.go, sdk/tools/apidiff/report/report.go, sdk/tools/internal/dirs/dirs.go, sdk/tools/internal/dirs/dirs_test.go, sdk/tools/internal/ioext/ioext.go, sdk/tools/internal/modinfo/modinfo.go, sdk/tools/internal/modinfo/modinfo_test.go
This PR adds the API diff tool with some slight modifications so that the `diff` command outputs content that complied with track2 changelog release guidelines.
=> Adding track2 API diff tools

sdk/azcore/policy_logging.go, sdk/azcore/policy_retry.go, sdk/azcore/policy_retry_test.go, sdk/azcore/policy_telemetry.go, sdk/azcore/policy_telemetry_test.go
Specify zero-value options structs to accept default values.
Remove DefaultXxxOptions() methods.
Fixed up docs for RetryOptions.
=> Accept zero-value options for default values

sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential_test.go
This PR gives priority to checking the MSI_ENDPOINT and MSI_SECRET environment variables over the IDENTITY_ENDPOINT and IDENTITY_HEADER variables. This is because in Azure Functions on Linux consumptions hosts, the latest api-version is not yet supported and causes an error. 
Fixes #12981
=> Switching the environment variable check for ManagedIdentityCredential

tools/generator/validate/validation.go
=> The output-folder for a profile now no longer reports errors

sdk/azidentity/aad_identity_client_test.go, sdk/azidentity/authorization_code_credential.go, sdk/azidentity/authorization_code_credential_test.go, sdk/azidentity/azidentity.go, sdk/azidentity/azure_cli_credential.go, sdk/azidentity/azure_cli_credential_test.go, sdk/azidentity/bearer_token_policy_test.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/default_azure_credential_test.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/device_code_credential_test.go, sdk/azidentity/environment_credential.go, sdk/azidentity/go.mod, sdk/azidentity/go.sum, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/interactive_browser_credential_test.go, sdk/azidentity/managed_identity_client_test.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go, sdk/azidentity/username_password_credential.go, sdk/azidentity/username_password_credential_test.go
This PR removes the DefaultXxxOptions() funcs from every azidentity credential type.
=> azidentity: Remove DefaultXxxOptions() funcs 

sdk/azidentity/aad_identity_client.go, sdk/azidentity/authorization_code_credential.go, sdk/azidentity/authorization_code_credential_test.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/interactive_browser_credential_test.go
Implement as specified in RFC7636 to prevent auth code interception
attacks.  Enabled by default, can be disabled.
=> Add support for PKCE in interactive auth flow

azure-pipelines.yml, eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml, eng/pipelines/templates/jobs/archetype-sdk-client.yml, sdk/armcore/ci.yml
This change switches the unified pipelines to use the 1ES hosted pools. This is just a straight up switch from the Azure Pipelines pool (specifying a VM image) to using the 1ES pool (no image specified).
=> Enable 1ES hosted pools

eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml, eng/pipelines/templates/steps/analyze.yml
Limit analyze to the service directory (it was scanning all of track 2)
=> Fix analyze step to use Ubuntu

sdk/azcore/core.go, sdk/azcore/policy_retry_test.go
On rare occasion there is a nil response and error.  Ensure that the
transport returns a nil response in this case.
Moved custom TryTimeout value to the one test that relies on it and
fixed its validation logic.
=> Retry on a nil response

sdk/azidentity/aad_identity_client.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/interactive_browser_credential_test.go, sdk/azidentity/interactive_browser_server.go
Replaced WaitGroup with channel.
Flow context to WaitForCallback() and select on both channels.
Disabling PKCE should not be allowed.  The functionality was disabled
and the config option can be removed in the next breaking change.
=> Ensure interactive auth flow can be cancelled

tools/profileBuilder/cmd/latest.go, tools/profileBuilder/cmd/list.go, tools/profileBuilder/cmd/root.go, tools/profileBuilder/model/transforms.go
limit the maximum concurrency to 8 by default, add a flag to manually set this
=> Fix a concurrency issue in profileBuilder

tools/generator/cmd/metadata.go
=> [SDK automation] Now use commit hash instead of the spec root in changelog

tools/profileBuilder/cmd/root.go
=> ProfileBuilder: turn the concurrency off by default

sdk/azcore/transport_default_http_client.go
=> Use Clone() method to clone default transport

storage/client.go, storage/client_test.go
The account name restrictions for cosmosdb are different than the ones enforced by
azure storage. This change adds a new method to return a cosmos client that allows
cosmosdb account name as enforced by azure cosmos db.
The cosmos account name can only contain lowercase letters, numbers, and the hyphen (-)
character. It must be between 3-44 characters in length.
=> Add a new method to get cosmosdb client

eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml, eng/pipelines/templates/jobs/archetype-sdk-client.yml, sdk/azcore/ci.yml
This PR re-enables agent OS verification and depends on this PR being merged first:
https://github.com/Azure/azure-sdk-tools/pull/1371
=> Re-enable agent OS verification

storage/appendblob.go, storage/client.go, storage/recordings/AppendBlobSuite/TestPutAppendBlob.yaml, storage/recordings/AppendBlobSuite/TestPutAppendBlobAppendBlocks.yaml, storage/recordings/StorageBlobSuite/TestPutAppendBlobSpecialChars.yaml
Omit x-ms-blob-type request header for AppendBlock() operation.
Fixed XML error unmarshalling for some table APIs.
=> Storage fixes

sdk/azcore/core.go, sdk/azcore/core_test.go, sdk/azcore/doc.go, sdk/azcore/example_test.go, sdk/azcore/request.go, sdk/azcore/response.go
This adds NullValue() and IsNullValue() functions for setting and
detecting sentinel values used for encoding a JSON null.
Cleaned up some improper error wrapping and removed out-dated comments.
=> Add support for encoding JSON null values

sdk/azcore/request.go, sdk/azcore/request_test.go
Added method WriteMultipartFormData() to Request.
=> Add support for multi-part form data

sdk/armcore/connection.go, sdk/armcore/connection_test.go, sdk/armcore/version.go
Removed NewConnectionWithPipeline() in favor of policy slices in
ConnectionOptions.  The slices are to control where the policies are
injected in the pipeline, either before or after the retry policy.
Update version number for pending release.
=> Simplify injecting custom pipeline policies

README.md
Update content to MIT at a section of License on README.
=> Migrate license to MIT

sdk/armcore/connection.go, sdk/armcore/poller.go
This PR fixes linter warnings from gosimple.
=> Fix gosimple linter warnings

sdk/internal/runtime/response_error.go
ResponseError types are returned from failed API calls, e.g. the caller
provided invalid inputs.  Since these errors are not transient they
should be marked as NonRetriable() so customers can test for this.
=> Mark ResponseError as NonRetriable()

sdk/azcore/error.go, sdk/azcore/go.mod, sdk/azcore/go.sum
Ensure that ResponseError is a NonRetriableError
=> Update to latest internal module

azure-pipelines.yml, eng/pipelines/templates/steps/analyze.yml
Sending the -d switch to gofmt makes the build failure output more useful. Rather than just listing the file names that failed format checks, the file diffs will be displayed indicating what needs to be changed. Ex.
```bash
gofmt -s -l -d $(find . -name '*.go' -print)
./testcontext.go
diff -u ./testcontext.go.orig ./testcontext.go
--- ./testcontext.go.orig       2021-04-06 13:46:59.500000000 -0500
+++ ./testcontext.go    2021-04-06 13:46:59.500000000 -0500
@@ -34,4 +34,4 @@
}
func (c *testContext) Name() string {
return c.name
-}
+}
```
=> Send the -d switch to gofmt

sdk/azcore/log.go
The PR removes some duplicate code in azcore log.go:
- Remove the check on `l.lst` in `Logger.Writef` as it is checked in `Logger.Should` already
- Reuse `Logger.Writef` in `Logger.Write` to DRY.
=> Track2: azcore log remove some duplicate code

tools/generator/autorest/model/changelog.go, tools/generator/cmd/root.go, tools/generator/pipeline/model.go
=> [Generator] breaking change items will have empty array if there is not any

CHANGELOG.md
=> Change one link to absolute that is forgotten in v53.3.0

sdk/azcore/headers.go, sdk/azcore/policy_logging.go, sdk/azcore/poller.go, sdk/azcore/poller_test.go
Added type LROPoller and supporting types for basic polling on long
running operations.
Fixed content type detection bug in logging.
=> Support for basic LRO polling

tools/apidiff/markdown/markdown.go, tools/generator/autorest/model/changelog.go
=> [SDK Automation] generator no longer returns breaking change items with the `-` prefix

sdk/internal/testframework/recording.go
- Separate sanitizer for request bodies and response bodies (NOTE: I'm open to having just one body sanitizer with a field that specifies if it's meant to be used for the request, response or both. Let me know!)
- Assign default sanitizer to the recording sanitizer
- Export sanitizer on the recording to allow sanitizer customization
=> Testframework: various sanitizer fixes

CHANGELOG.md, CONTRIBUTING.md, azure-pipelines.yml
Adjust to use the verify-links template instead of directly calling the script to get benefits like link caching.
=> Use verify-links template

sdk/azcore/core.go, sdk/azcore/core_test.go, sdk/azcore/policy_body_download_test.go, sdk/azcore/response.go, sdk/azcore/response_test.go
Also export the `payload()` method on `Response`
=> Add support for null map and slice

sdk/azcore/policy_retry.go, sdk/azcore/policy_retry_test.go, sdk/azcore/request.go
This is to handle the case where a pipeline policy reads and restores a
request body without preserving the io.Seeker interface.
=> Cache the original request body on Request

sdk/armcore/LICENSE.txt, sdk/armcore/poller.go, sdk/armcore/version.go
If the success response doesn't return a final get URI used the value
that was previously calculated.
=> Don't overwrite final get URI with empty string

sdk/azcore/LICENSE.txt, sdk/azcore/request.go, sdk/azcore/version.go
pkg.go.dev requires each module to contain its license file.
Updated comment on Request type.
=> Add license.txt to azcore module

sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go
=> azidentity: move scope to resource conversion to GetToken in MSI cred

tools/apidiff/go.mod, tools/apidiff/go.sum, tools/deprecate/go.mod, tools/deprecate/go.sum, tools/generator/go.mod, tools/generator/go.sum, tools/indexer/go.mod, tools/indexer/go.sum, tools/internal/go.mod, tools/internal/go.sum, tools/pkgchk/go.mod, tools/pkgchk/go.sum, tools/profileBuilder/go.mod, tools/profileBuilder/go.sum
Step 2: switch everything to use the new released azure-sdk-for-go which does not contain `tools`
=> update dependency in every tool to use the official sdk

sdk/azcore/request.go, sdk/azcore/response.go, sdk/azcore/version.go
Moved guts of MarshalAsByteArray() and UnmarshalAsByteArray() into
stand-alone funcs to be used in code generation.
=> Improved support for byte arrays

Gopkg.lock, Gopkg.toml, azure-pipelines.yml, initScript.sh, swagger_to_sdk_config.json, tools/generator/cmd/root.go
We are facing some failures in CI with `dep ensure` after we introduce some new command to `tools/generator`.
Now `tools/generator` imports some modules with the major version greater than `v1`. The `dep` cannot properly import them and give us errors when running `dep ensure`.
This PR adds ignore clauses in the `Gopkg.toml` file to explicitly ignore those modules with greater than v2 major version to fix this issue.
=> Fix dependency issues with `dep ensure`

sdk/azidentity/aad_identity_client.go, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go
Fixes #12184
Adding support for passing in a resource ID instead of a client ID for managed identities.
=> azidentity: Adding Resource ID support in ManagedIdentityCredential

sdk/armcore/go.mod, sdk/armcore/go.sum, sdk/armcore/internal/pollers/async/async.go, sdk/armcore/internal/pollers/async/async_test.go, sdk/armcore/internal/pollers/body/body.go, sdk/armcore/internal/pollers/body/body_test.go, sdk/armcore/internal/pollers/loc/loc.go, sdk/armcore/internal/pollers/loc/loc_test.go, sdk/armcore/internal/pollers/pollers.go, sdk/armcore/internal/pollers/pollers_test.go, sdk/armcore/poller.go, sdk/armcore/poller_test.go, sdk/armcore/version.go
Simplified implementation of LRO pollers for ARM.
Public surface area has been slightly changed, making it identical to
the data-plane implementation.
The different polling mechanisms have been split into internal packages,
with an exported LROPoller that implements the overall polling algorithm.
=> LRO poller rewrite

tools/generator/cmd/automation/automationCmd.go, tools/generator/cmd/automation/pipeline/model.go
=> [SDK Automation] squash the package files

sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential_test.go
=> azidentity: add support for service fabric MSI environment

eng/pipelines/prepare-pipelines.yml
In order to automatically create new pipelines from PRs with pipeline yaml, we first need to define a repo-specific `prepare pipelines` pipeline (how many times can I say pipeline in one sentence...).
=> Add prepare pipelines pipeline

sdk/storage/azblob/ci.yml
=> Adding CI file

eng/pipelines/prepare-pipelines.yml
I added support for `/azp run prepare-pipelines` with https://github.com/Azure/azure-sdk-for-go/pull/14947, but the config was set to generate live test pipelines. Since none are currently defined for the repo, this will cause that step of the pipeline to fail (and therefore block the PR it was run for).
Commenting out the `TestsConventionOptions` parameter has the effect of skipping live test generation (https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/pipelines/templates/steps/prepare-pipelines.yml#L74).
=> Skip live test generation in prepare-pipelines

sdk/internal/recording/README.md
=> Fix README in `sdk/internal/recording` package

sdk/tables/aztable/shared_policy_shared_key_credential.go, sdk/tables/aztable/table_client.go, sdk/tables/aztable/table_client_test.go, sdk/tables/aztable/table_pagers.go, sdk/tables/aztable/table_pagers_test.go, sdk/tables/aztable/table_service_client.go, sdk/tables/aztable/table_service_client_test.go, sdk/tables/aztable/table_transactional_batch.go, sdk/tables/aztable/zc_table_constants.go, sdk/tables/aztable/zt_table_recorded_tests.go
Fixes up issues picked up by linter in Analyze step of CI. These are mostly error checking/reporting.
=> [Tables] linting Fixes

CONTRIBUTING.md, README.md, azure-pipelines.yml, eng/pipelines/templates/steps/build.yml
- Add some basic build documentation in CONTRIBUTING.md
- Remove stale line in readme
- Comment two CI scripts to disambiguate
=> Start documentation on build

eng/pipelines/templates/steps/analyze.yml
On the lint step of `Analyze`, if the exit code is not 0 this step will fail.
=> [EngSys] Stage fails if linter does not succeed

sdk/azcore/credential.go, sdk/azcore/policy_anonymous_credential.go, sdk/azcore/policy_anonymous_credential_test.go, sdk/azcore/request_test.go
=> [Core] Renamings for AuthPolicies

sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/interactive_browser_server.go
Fixes lint step. For now skipping `golangci-lint` step on the four issues that are flagged by the linter
=> [Identity] fixing lint step for azidentity

sdk/servicebus/armservicebus/LICENSE.txt, sdk/servicebus/armservicebus/ci.yml
=> track2 add servicebus ci.yml and LICENSE.txt file

eng/scripts/build.ps1, eng/scripts/meta_generation.ps1
=> [build.ps1] Add support for converting _meta.json to autorest.md during build

sdk/azcore/credential.go
Adding `AuxiliaryTenants` to `AuthenticationOptions` for multi-tenant support.
=> [core] Add auxiliary tenants for multi-tenant scenario

eng/.golangci.yml, eng/pipelines/templates/steps/build-test.yml, eng/scripts/create_coverage.ps1, sdk/azcore/ci.yml, sdk/azcore/log.go, sdk/internal/ci.yml, tools/internal/coverage/main.go
=> [EngSys] adding triggers on eng for internal and azcore

sdk/armcore/connection.go, sdk/armcore/connection_test.go, sdk/armcore/go.mod, sdk/armcore/go.sum, sdk/armcore/internal/pollers/async/async.go, sdk/armcore/internal/pollers/loc/loc_test.go, sdk/armcore/internal/pollers/pollers_test.go, sdk/armcore/policy_register_rp.go, sdk/armcore/policy_register_rp_test.go, sdk/armcore/poller.go, sdk/armcore/poller_test.go
Add AuxiliaryTenants in options for ARM clients, update code that depends on the latest changes in azcore, and fixing linting errors
Issue for checking linter comments: https://github.com/Azure/azure-sdk-for-go/issues/15173
Part of #14360
=> [armcore] Add auxiliary tenants to connection options

sdk/azidentity/aad_identity_client.go, sdk/azidentity/aad_identity_client_test.go, sdk/azidentity/authorization_code_credential.go, sdk/azidentity/authorization_code_credential_test.go, sdk/azidentity/azidentity.go, sdk/azidentity/azure_cli_credential.go, sdk/azidentity/bearer_token_policy.go, sdk/azidentity/bearer_token_policy_test.go, sdk/azidentity/chained_token_credential.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/device_code_credential_test.go, sdk/azidentity/environment_credential.go, sdk/azidentity/go.mod, sdk/azidentity/go.sum, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_client_test.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go, sdk/azidentity/username_password_credential.go, sdk/azidentity/username_password_credential_test.go
Update azidentity to depend on new changes in azcore v0.17.0.
=> [azidentity] Update code to use the latest azcore

sdk/azidentity/azidentity.go, sdk/azidentity/bearer_token_policy.go, sdk/azidentity/bearer_token_policy_test.go
Fixes #14360 
Re-design of the bearer token policy refresh algorithm and adding support for multi-tenant authentication.
=> [azidentity] Expiring resource rework w/ multi-tenant support

sdk/internal/logger/logger.go, sdk/internal/logger/logger_test.go
=> [internal] Move logging functionality to `internal`

README.md
=> Fix Samples Section 

eng/pipelines/templates/steps/build-test.yml
Removes `-race` and `-covermode atomic` flags from the `go test` command. These additional flags are causing race conditions in the azcore test pipeline.
=> [engsys] remove race and covermode flags from test statement

eng/scripts/build.ps1
=> enhance build.ps1 script

eng/pipelines/templates/steps/analyze.yml
Move the verify link step to the last. I notice that the failure of this step will make the CI to skip the following step (Linter check). We definitely do not want that. Therefore moving this step to the last so that we can check those important aspect for go code first.
=> move verify link to the last step

eng/pipelines/templates/steps/analyze.yml
=> redirect the output to stderr in gofmt checking so that we can give errors when the code is not formatted

sdk/armcore/README.md, sdk/azcore/README.md, sdk/azidentity/README.md, sdk/to/README.md
=> Fix build status and code coverage badges

sdk/azidentity/CHANGELOG.md
=> [azidentity] adding a changelog to azidentity

sdk/azcore/CHANGELOG.md
Adds a changelog with previous release information. 
closes #15234
=> [azcore] adding changelog

documentation/new-version-quickstart.md
=> Fixed small bugs

sdk/azcore/CHANGELOG.md, sdk/azcore/request.go, sdk/azcore/request_test.go
Also updates the changelog with previous updates
=> [azcore] JoinPaths will preserve query parameters

sdk/azcore/core.go, sdk/azcore/error.go, sdk/azcore/example_test.go, sdk/azcore/go.mod, sdk/azcore/go.sum, sdk/azcore/log.go, sdk/azcore/log_test.go, sdk/azcore/policy_anonymous_credential.go, sdk/azcore/policy_logging.go, sdk/azcore/policy_logging_test.go, sdk/azcore/policy_retry.go, sdk/azcore/policy_retry_test.go, sdk/azcore/poller.go, sdk/azcore/poller_test.go, sdk/azcore/progress.go, sdk/azcore/request.go, sdk/azcore/request_test.go
Unexported policyFunc
Renamed Transport to Transporter
Removed TransportFunc, Pager, and Poller interfaces
Added responseError (removed from internal)
Fixed logging type aliases
Updated logging usage based on internal/log refactor
Removed StatusCodesForRetry, ProgressReceiver, ErrNoMorePolicies
Renamed LROPoller to Poller
=> Removed and renamed some content

sdk/azcore/core.go, sdk/azcore/policy_anonymous_credential.go, sdk/azcore/policy_body_download.go, sdk/azcore/policy_body_download_test.go, sdk/azcore/policy_http_header.go, sdk/azcore/policy_logging.go, sdk/azcore/policy_retry.go, sdk/azcore/policy_retry_test.go, sdk/azcore/policy_telemetry.go, sdk/azcore/poller.go, sdk/azcore/poller_test.go, sdk/azcore/request.go, sdk/azcore/response.go, sdk/azcore/response_test.go
Just return an *http.Response instead.
Changed Response methods to functions.
=> Remove Response type

sdk/internal/recording/recording.go, sdk/internal/recording/recording_test.go, sdk/internal/recording/request_matcher.go, sdk/internal/recording/request_matcher_test.go, sdk/internal/recording/sanitizer.go, sdk/internal/recording/sanitizer_test.go
Fixes internal/recording package in the track2-tables package.
=> fixing internal

eng/scripts/build.ps1
=> fix: three dots in path in build script not work on linux

sdk/servicebus/azservicebus/processor.go, sdk/servicebus/azservicebus/samples/processor/processor_sample.go
Fixing build break. I had renamed some constants but not pushed the rest of the code changes.
=> [service-bus] Rename refactored ReceiveMode constants but didn't push the other files

eng/scripts/build.ps1
Add a `clearOutput` flag in `build.ps1` flag to allow us first clear all the auto-generated files before we generate anything new.
The option of `autorest` `--clear-output-folder` is not acceptable because it will remove everything in this directory.
=> add clear output flag to build.ps1

sdk/azidentity/CHANGELOG.md, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go
=> Prevent ManagedIdentityCredential mutating GetToken arguments

azure-pipelines.yml
Build_Test was running older versions of Go, bumping to be in line with `eng/pipelines/templates/jobs/archetype-sdk-client.yml` versions
=> bumping Build_Test to 1.16 and 1.17

sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential_test.go
IMDS is always available to a VM in that it responds to requests but, when the VM has no assigned identity, it responds 400 to token requests: IMDS is available but managed identity authentication is not. ManagedIdentityCredential doesn't make this distinction today. It considers managed identity available whenever IMDS responds and treats the lack of an assigned identity as an authentication error, i.e. it returns ClientAuthenticationError. That error causes DefaultAzureCredential (ChainedTokenCredential) to halt when it should instead try the next credential in the chain. With this PR ManagedIdentityCredential does that and, after receiving a 400 from IMDS, doesn't attempt another token request. The motivation for the latter change is that there's no reason to believe another token …
=> Return CredentialUnavailableError when IMDS has no assigned identity

tools/generator/template/rpName/packageName/README.md.tpl, tools/generator/template/rpName/packageName/build.go.tpl
=> update template accordingly

sdk/azcore/CHANGELOG.md, sdk/azcore/version.go, sdk/azidentity/CHANGELOG.md
=> Updating azcore & azidentity changelog

sdk/azidentity/CHANGELOG.md, sdk/azidentity/azure_cli_credential.go, sdk/azidentity/azure_cli_credential_test.go
`AzureCLICredentialOptions.TokenProvider` is a callback the credential invokes to acquire a token. It's needed in tests to fake invoking the CLI but we don't want it in the public API (~`ArbitraryCallbackCredential`~ `AzureCLICredential` 😉) so this PR makes it and its type unexported.
=> Unexport AzureCLITokenProvider

sdk/data/aztables/proxy_test.go, sdk/internal/recording/recording.go
=> [Tables] Merging internal

sdk/storage/azblob/zt_test.go
=> Rebased with main

documentation/MIGRATION_GUIDE.md, documentation/new-version-quickstart.md
=> update docs accordingly to recent changes in azcore and armcore

eng/pipelines/templates/steps/build-test.yml
CI builds are currently not filtering by service, and are building all packages.
=> Filter CI builds by service directory

tools/generator/cmd/v2/automation/automationCmd.go, tools/generator/cmd/v2/common/fileProcessor.go, tools/generator/cmd/v2/common/generation.go, tools/generator/cmd/v2/release/releaseCmd.go
=> fix: use abs spec path in sdk automation script for track2

sdk/azcore/CHANGELOG.md, sdk/azcore/runtime/transport_default_http_client.go
Type-asserting the http.DefaultTransport can fail if it was replaced
with a custom RoundTripper.  Instead, create a new http.Transport with
the settings copied from http.DefaultTransport.
=> Create a default transport

tools/generator/cmd/template/templateCmd.go, tools/generator/cmd/v2/common/fileProcessor.go, tools/generator/cmd/v2/common/generation.go, tools/generator/cmd/v2/release/releaseCmd.go, tools/generator/template/rpName/packageName/CHANGELOG.md.tpl
=> feat: remove 'v' and add release date for changelog generation

sdk/azcore/example_test.go
=> Example for `HTTPResponse` error

sdk/azidentity/CHANGELOG.md, sdk/azidentity/chained_token_credential.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/default_azure_credential.go
Per our last API review, this adds a placeholder options struct for ChainedTokenCredential. I opened this as a draft to get opinions on replacing NewChainedTokenCredential's variadic `sources` parameter with a slice. I think this is a better type because the variadic parameter doesn't do anything useful here; it just makes possible calling `NewChainedTokenCredential(nil)` to get a runtime error.
=> Add ChainedTokenCredentialOptions

sdk/azidentity/CHANGELOG.md, sdk/azidentity/default_azure_credential.go, sdk/azidentity/default_azure_credential_test.go
Per our last API review, this removes credential exclusion switches from, and adds common connection options to, `DefaultAzureCredentialOptions`. These exclusion switches shipped only in .NET and Python, where they've been useful for working around problems with `SharedTokenCacheCredential`, but not so useful that we added them to Java* SDKs. We don't plan to add `SharedTokenCacheCredential` to Go, and since 1.0 have come to prefer keeping `DefaultAzureCredential` simple, presenting it as a set of reasonable defaults for getting started and encouraging users to choose other credential types when it isn't a good fit, so it's best not to have these switches in the first stable `azidentity`.
=> Remove credential exclusion switches from DefaultAzureCredentialOptions

sdk/azidentity/CHANGELOG.md, sdk/azidentity/aad_identity_client.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/interactive_browser_credential_test.go, sdk/azidentity/interactive_browser_server.go
Removes a couple fields from InteractiveBrowserCredentialOptions:
- ClientSecret: not part of this credential's mainline scenario. We don't support it in other languages; neither does MSAL for Go.
- Port: redundant given we have RedirectURL, which is what we really need. Also not supported by MSAL for Go.
Speaking of RedirectURL, while doing this I discovered it doesn't work. I don't want to remove it, because we do need it, but neither do I want to fix it, because adopting MSAL entails deleting the code that needs fixing. So I instead documented that it doesn't work, and opened #15632 to track fixing it.
=> Remove ClientSecret and Port from browser credential options

eng/scripts/build.ps1
So you can generate code using any version of autorest.go, including a local one (e.g. `build.ps1 -goExtension=~/autorest.go ...`).
=> Add goExtension parameter to build.ps1

sdk/internal/mock/closer.go, sdk/internal/mock/closer_test.go
It behaves like a io.NopCloser but returns a tracker that, when invoked,
returns true if Close was called on the io.ReadCloser.
=> Add mock.NewTrackedCloser to help test when Close is called

sdk/messaging/azservicebus/client.go, sdk/messaging/azservicebus/client_test.go, sdk/messaging/azservicebus/example_sending_message_batch_test.go, sdk/messaging/azservicebus/go.mod, sdk/messaging/azservicebus/go.sum, sdk/messaging/azservicebus/internal/namespace.go, sdk/messaging/azservicebus/internal/namespace_test.go, sdk/messaging/azservicebus/internal/token_provider.go, sdk/messaging/azservicebus/liveTestHelpers_test.go, sdk/messaging/azservicebus/samples/processor/processor_sample.go, sdk/messaging/azservicebus/sender_test.go, sdk/messaging/azservicebus/stress/stress.go
This PR allows you to pass in a azure identity TokenCredential and authenticate to Service Bus.
I also took this opportunity to fix our refresh calculation interval to be dynamic when we use TokenCredentials since they have a built in expiration date. JS had some nice "wiggle-room" calculations which I've also incorporated.
Note for reviewers: this PR is built on top of https://github.com/Azure/azure-sdk-for-go/pull/15611. You'll want to review the code after this commit: https://github.com/Azure/azure-sdk-for-go/commit/0f3d40327b9339c2b6ff05d3eb1767faa848761e to see the additions this PR is bringing in.
Fixes #15542
Fixes #15638
=> [service-bus] Azure Identity support

sdk/azidentity/README.md
Just a small typo I noticed reading through the docs.
=> Typo: classificatons -> classifications

sdk/azcore/CHANGELOG.md, sdk/azcore/arm/connection.go, sdk/azcore/arm/connection_test.go, sdk/azcore/internal/shared/constants.go
This provides a clue for what values callers are supposed to pass.
Since the underlying type is a string, callers can still pass custom
endpoint strings using a cast.
=> Use a typedef for ARM endpoints

sdk/azidentity/CHANGELOG.md, sdk/azidentity/aad_identity_client.go, sdk/azidentity/authorization_code_credential_test.go, sdk/azidentity/azidentity.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/device_code_credential_test.go, sdk/azidentity/interactive_browser_credential_test.go, sdk/azidentity/managed_identity_client.go, sdk/azidentity/version.go
This removes `AADAuthenticationFailedError` so AAD response structure isn't part of our API, and because we don't need it; `AuthenticationFailedError` can encompass errors arising specifically from AAD auth failures. In practical terms, this change makes getting low-level details such as a correlation ID a bit more work. I think that's okay because this change also makes AAD's detailed error description part of `AuthenticationFailedError.Error()`, so the most important information is the most visible, and exposes the underlying `*http.Response` via `AuthenticationFailedError.RawResponse()`, so no information is lost.
=> Remove azidentity.AADAuthenticationFailedError

sdk/messaging/azservicebus/client.go, sdk/messaging/azservicebus/go.mod, sdk/messaging/azservicebus/go.sum, sdk/messaging/azservicebus/internal/amqpLinks.go, sdk/messaging/azservicebus/internal/amqpLinks_test.go, sdk/messaging/azservicebus/internal/amqp_test_utils.go, sdk/messaging/azservicebus/internal/mgmt.go, sdk/messaging/azservicebus/message.go, sdk/messaging/azservicebus/messageSettler.go, sdk/messaging/azservicebus/messageSettler_test.go, sdk/messaging/azservicebus/message_test.go, sdk/messaging/azservicebus/processor.go, sdk/messaging/azservicebus/processor_test.go, sdk/messaging/azservicebus/receiver.go, sdk/messaging/azservicebus/receiver_test.go
Adding in some of the critical receiver methods for deferring and retrieving deferred messages. Also, added in the track 2 compliant PeekMessages function.
There were also some bugs in how we were handling ReceiveMessages, which were found in some tests that I added.
This PR is built on top of a pending PR (https://github.com/Azure/azure-sdk-for-go/pull/15611) so you'll want to start reviewing this code from commit 0f3d40327b9339c2b6ff05d3eb1767faa848761e (my linkageddon commit) to see the relevant bits.
I've added in a temporary `replace` in the go.mod file so I can pick up this fix in go-amqp that hasn't yet released: https://github.com/Azure/go-amqp/pull/72).
=> [service-bus] Adding in PeekMessages, DeferMessage+ReceiveDeferredMessages support

sdk/data/azcosmos/ci.yml
Add Emulator tests into the CI to execute skipped tests.
The tests can only run on Windows and were being skipped if the environment variable was not set.
This PR adds a new step that runs only on Windows and sets the environment variable to enable running the emulator tests.
=> Cosmos DB - Enabling emulator tests

sdk/azidentity/CHANGELOG.md, sdk/azidentity/default_azure_credential.go, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go
Per our last API review, this moves NewManagedIdentityCredential's `id` parameter into its options bag, so it isn't necessary to pass an empty string in the common case of wanting to use the hosting environment's default identity.
=> Move NewManagedIdentityCredential's id parameter into ManagedIdentityCredentialOptions

sdk/messaging/azservicebus/client.go, sdk/messaging/azservicebus/client_test.go, sdk/messaging/azservicebus/example_sending_message_batch_test.go, sdk/messaging/azservicebus/liveTestHelpers_test.go, sdk/messaging/azservicebus/messageSettler.go, sdk/messaging/azservicebus/messageSettler_test.go, sdk/messaging/azservicebus/processor.go, sdk/messaging/azservicebus/processor_test.go, sdk/messaging/azservicebus/receiver.go, sdk/messaging/azservicebus/receiver_test.go, sdk/messaging/azservicebus/samples/processor/processor_sample.go, sdk/messaging/azservicebus/sender.go, sdk/messaging/azservicebus/sender_test.go, sdk/messaging/azservicebus/stress/stress.go
Just removing all the variadic config I had in Service Bus before beta release:
- Dead letter options
- Creating receivers (NewReceiverFor*)
- Creating processors (NewProcessorFor*)
- Creating a message batch
I also did one other change - I exported the ReceiveMessage and ReceiveDeferredMessage functions (that get only a single message).
=> [service-bus] Remove variadic config

sdk/data/azcosmos/README.md, sdk/data/azcosmos/cosmos_client.go, sdk/data/azcosmos/cosmos_client_connection.go, sdk/data/azcosmos/emulator_tests.go, sdk/data/azcosmos/shared_key_credential.go
The next version of azcore doesn't contain `azcore.Credential`, so client constructors must be explicit about the credential types they accept. Pretty straightforward here because there's only one credential type. I renamed the constructor NewCosmosClient -> NewClientWithSharedKey to align with upcoming guidelines for the SDK (the "good" name, NewClient, would go to a constructor taking `azcore.TokenCredential`, i.e. an Azure AD credential).
=> Refactor azcosmos client constructor

eng/config.json
Talking with Joel and Ben - the track 1 CI pipeline is triggering for the changes I've got in my main PR. 
This is unintentional, and I believe the only reason it's running at all is because the config.json file changed. Testing that theory now.
=> [service-bus] Separating code coverage changes out

eng/scripts/Language-Settings.ps1
This makes the service directory property we get from the properties match what we see in the ci.yml files.
=> Make Service Directory consistent

sdk/messaging/azservicebus/example_receiver_test.go, sdk/messaging/azservicebus/go.mod, sdk/messaging/azservicebus/go.sum, sdk/messaging/azservicebus/receiver.go, sdk/messaging/azservicebus/receiver_test.go
This PR changes the ReceiveMessages function so the overall timeout is controlled via the user's 'ctx' parameter, rather than having a separately specified 'MaxWaitTime' variable.
(This is based a previous API review)
Fixes #15981
=> [azservicebus] Make ReceiveMessages overall timeout is controlled by ctx

sdk/azidentity/aad_identity_client_test.go, sdk/azidentity/azidentity.go, sdk/azidentity/azidentity_test.go, sdk/azidentity/ci.yml, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/environment_credential_test.go, sdk/azidentity/logging.go, sdk/azidentity/username_password_credential_test.go
Adds live tests for service principal and user password authentication and the CI configuration necessary to run them. #15973 tracks recording these.
Closes #15403, closes #15876
=> Add live tests to azidentity pipeline

documentation/previous-versions-quickstart.md
Default role: Contributor is being deprecated for az ad sp create-for-rbac. Added --role Contributor to az ad sp create-for-rbac where the current role selection is left as default (no parameter). 
User story [1876839](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1876839)
=> 1876839: Add CLI contributor role

sdk/azcore/CHANGELOG.md, sdk/azcore/policy/policy.go, sdk/azcore/runtime/policy_logging.go, sdk/azcore/runtime/policy_logging_test.go, sdk/azcore/runtime/response.go
LogOptions now contains allow-lists for headers and query parameters.
Any header and/or query parameter not in the allow lists, combined with
the default set, will have its value written as REDACTED to the log.
=> Add allow-lists for headers and query parameters

sdk/azcore/arm/client_options.go, sdk/azcore/internal/shared/shared_test.go
Azure Germany closed (all subscriptions disabled) on 10/29: https://www.microsoft.com/en-us/cloud-platform/germany-cloud-regions
=> Remove AzureGermany Endpoint

sdk/azcore/CHANGELOG.md, sdk/azcore/arm/runtime/pipeline.go, sdk/azcore/arm/runtime/pipeline_test.go, sdk/azcore/arm/runtime/policy_bearer_token_test.go, sdk/azcore/arm/runtime/policy_register_rp.go, sdk/azcore/arm/runtime/policy_register_rp_test.go, sdk/azcore/arm/runtime/poller_test.go, sdk/azcore/example_test.go, sdk/azcore/runtime/pipeline.go, sdk/azcore/runtime/pipeline_test.go, sdk/azcore/runtime/policy_bearer_token_test.go, sdk/azcore/runtime/policy_http_header_test.go
Following from https://github.com/Azure/azure-sdk-for-go/pull/16076#pullrequestreview-798084846, this adds a new struct for pipeline and policy options intended for use by SDK developers. Pipeline constructors merge these options with the application's `azcore.ClientOptions` without mutating the latter.
=> Add options struct for NewPipeline

sdk/azidentity/authorization_code_credential.go, sdk/azidentity/azure_cli_credential.go, sdk/azidentity/chained_token_credential.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/default_azure_credential.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/doc.go, sdk/azidentity/environment_credential.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/username_password_credential.go
Revised all the credential doc comments, updating content and improving consistency. I deleted most of doc.go because on pkg.go.dev it appears after the readme, which has the overview content I think would belong in doc.go.
=> Revise azidentity doc comments

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/go.mod, sdk/messaging/azservicebus/go.sum, sdk/messaging/azservicebus/internal/constants.go
Prior version of go-amqp v0.16.3 had a race condition where a link error could potentially be set when the link is unwound that was not synchronized with reading the error.
Fixes #16092
=> [azservicebus] update to go-amqp@v0.16.4

sdk/messaging/azservicebus/migrationguide.md
Fixing some syntax errors in the migrationguide.md (signatures shifted around quite a bit).
=> [azservicebus] Fixing syntax errors in the migrationguide.md

sdk/messaging/azservicebus/main_test.go, sdk/messaging/azservicebus/messageSettler.go, sdk/messaging/azservicebus/messageSettler_test.go, sdk/messaging/azservicebus/receiver.go
Messages received in ReceiveModeReceiveAndDelete mode were panicking when settled. We had a check for this but it broke when I moved it to an interface, rather than an actual direct pointer type.
=> [azservicebus] Fixing messages received in ReceiveModeReceiveAndDelete settlement mode causing a panic

eng/pipelines/templates/jobs/archetype-go-release.yml, eng/scripts/Verify-NeedToRelease.ps1
As there are too many manual trigger works for SDK release, I added a release check stage before the release pipeline. The stage will check whether there is a new release and to trigger or skip release stage then.
=> feat: add check release to auto trigger internal release job

eng/tools/generator/autorest/model/changelog.go, eng/tools/generator/cmd/root.go, eng/tools/generator/cmd/template/templateCmd.go, eng/tools/generator/cmd/v2/common/fileProcessor.go, eng/tools/generator/cmd/v2/common/generation.go, eng/tools/generator/cmd/v2/common/workspaceProcessor.go, eng/tools/generator/cmd/v2/refresh/refreshCmd.go, eng/tools/generator/cmd/v2/release/releaseCmd.go, eng/tools/generator/repo/sdk.go, eng/tools/generator/template/rpName/packageName/autorest.md.tpl
1. change second generate cmd to version replacement for update release
2. refine changelog file content set based on new changelog format
3. add refresh-v2 cmd for convenience
4. add package config support for muliti-package rp onboard
=> feat: mgmt plane release tool update

sdk/keyvault/azkeys/README.md
* the link to go get github.com/.../azkeys was corrected.
* goget_azkey link never referenced in this README, so I removed it.
* goget_azkeys link was commented out, so none of the links referencing it were working. I uncommented it.
- [x ] The purpose of this PR is explained in this or a referenced issue.
=> fix a few azkey links

sdk/keyvault/azsecrets/client_test.go
In response to customer reported issue #16371 
Adds a test for cancelling a request sent to a bad vault URL after an allotted time (10 seconds for this test).
=> [Secrets] adding timeout test

README.md
ServiceBus follows the New Release guidelines.  It does not fit within this table.
=> Remove ServiceBus from the list of other packages

sdk/internal/CHANGELOG.md, sdk/internal/recording/recording.go, sdk/internal/recording/recording_test.go, sdk/internal/recording/sanitizer.go
Closes #16129 
Adds a variable storage for storing random names and retrieving them in future tests.
=> [Internal] Variable storage

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/client.go, sdk/messaging/azservicebus/client_test.go, sdk/messaging/azservicebus/example_client_test.go, sdk/messaging/azservicebus/internal/namespace.go
We were previously depending on a 3rd party package for websockets, but our interaction with it was pretty minimal. I've reduced this down to just a single function call and allow a customer to pass in that function so we can invert the dependency and not directly require a specific version of the websockets library, provided it understands how to create a net.Conn.
I've moved the code we used to have in the library into an example instead, so it's still a simple operation for a customer to join it up with a package of their choice.
Fixes #16201
=> [azservicebus] Invert the dependency for websockets so we don't directly depend on a 3rd party package

sdk/messaging/internal/go.mod, sdk/messaging/internal/go.sum, sdk/messaging/internal/rpc/rpc.go, sdk/messaging/internal/rpc/rpc_test.go
ErrLinkDetached has been removed - we should be using the existing *amqp.DetachError instead.
=> [messaging/internal] updating to latest go-amqp where amqp.ErrLinkDetached has been removed

eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/build-test.yml, eng/scripts/Invoke-DependencyCheck.ps1, eng/scripts/Invoke-MgmtTestgen.ps1, eng/scripts/build.ps1
=> feat: add dependency check step to build pipeline

sdk/azcore/CHANGELOG.md, sdk/azcore/internal/pipeline/request.go, sdk/azcore/internal/pipeline/request_test.go, sdk/azcore/internal/shared/shared.go, sdk/azcore/runtime/policy_body_download.go, sdk/azcore/runtime/policy_body_download_test.go, sdk/azcore/runtime/policy_retry_test.go, sdk/azcore/runtime/request.go, sdk/azcore/runtime/response_test.go, sdk/azcore/streaming/progress_test.go
It's not part of the Request, it's part of the body download policy.
Moved to a stand-alone function in runtime to decouple it.
=> Remove SkipBodyDownload from Request

eng/tools/generator/cmd/v2/automation/automationCmd.go
=> fix: wrong specRoot folder calculation for multi packages

sdk/storage/azblob/zc_storage_error.go, sdk/storage/azblob/zc_storage_error_test.go
Addresses #16542. Azurite returns error response bodies with newlines, and the SDK does not expect this. 
The fix is simply ignoring `CharData` nodes outside of XML elements. 
Kudos to @Leavrth for the detailed bug report (which included the fix!)
=> Handle error response XML with whitespace

sdk/storage/azblob/chunkwriting.go
When the buffer isn't filled to capacity a new slice is created that's
smaller than the original. In that case the smaller slice is returned to
the pool which prevents the rest of the capacity from being used again.
The solution is to pass the original slice through and attach the
length. This allows the original slice to be returned to the pool once
the operation is complete.
This change also simplifies the `sendChunk` method, ensuring that the
buffer is returned to the TransferManager even when no bytes were read
from the reader.
Copied from https://github.com/Azure/azure-storage-blob-go/pull/284
=> [chunkwriting] Return original buffer to the pool

sdk/storage/azblob/chunkwriting.go, sdk/storage/azblob/highlevel.go
This function only takes an io.Reader in azure-storage-blob-go,
& wal-g abstracts over multiple upload mechanisms which all operate on io.Reader
=> UploadStreamToBlockBlob: only require body be io.Reader

eng/tools/generator/cmd/automation/automationCmd.go
=> disable track 1 breaking change detection

sdk/azcore/CHANGELOG.md, sdk/azcore/arm/runtime/policy_register_rp.go, sdk/azcore/arm/runtime/poller.go, sdk/azcore/arm/runtime/poller_test.go, sdk/azcore/errors.go, sdk/azcore/example_test.go, sdk/azcore/internal/pollers/poller.go, sdk/azcore/internal/pollers/poller_test.go, sdk/azcore/internal/shared/response_error.go, sdk/azcore/internal/shared/response_error_test.go, sdk/azcore/internal/shared/shared.go, sdk/azcore/internal/shared/shared_test.go, sdk/azcore/runtime/errors.go, sdk/azcore/runtime/policy_body_download.go, sdk/azcore/runtime/policy_body_download_test.go, sdk/azcore/runtime/poller.go, sdk/azcore/runtime/poller_test.go, sdk/azcore/runtime/response.go
SDK APIs will now return an *azcore.ResponseError when a request is made
to the service and the service returns a non-success HTTP status code.
ResponseError provides the HTTP status code, error code when available,
and the raw *http.Response.
The Error() method provides pretty-printing of the error, see the tests
for example output.
Since user-defined errors are no longer returned, the LRO pollers no
longer need a callback to create them so this has been removed.
Payload() and NopClosingBytesReader have been moved to the internal,
shared package so ResponseError can use them.
Removed some unnecessary error unmarshallers in the register RP policy. …
=> Refactor error responses

sdk/storage/azblob/README.md
The container name should be all lowercase. Currently, running the sample code will cause an error that there are invalid characters in the container name.
=> Updated azblob README sample code

sdk/azcore/internal/shared/shared.go, sdk/azcore/internal/shared/shared_test.go
For example when given `https://centraluseuap.management.azure.com`, EndpointToScope will now return the correct scope `https://management.core.windows.net//.default`. (`https://management.azure.com//.default` would also work but [ARM REST documentation](https://docs.microsoft.com/en-us/rest/api/azure/#authorization-code-grant-interactive-clients) prefers the other.)
=> Make EndpointToScope resilient to subdomains

sdk/azidentity/CHANGELOG.md, sdk/azidentity/default_azure_credential.go, sdk/azidentity/logging.go, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_client_test.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go, sdk/azidentity/testdata/recordings/TestManagedIdentityCredential_IMDSClientIDLive.json, sdk/azidentity/testdata/recordings/TestManagedIdentityCredential_IMDSLive.json, sdk/azidentity/testdata/recordings/TestManagedIdentityCredential_IMDSResourceIDLive.json
Here's a few changes to behavior around IMDS managed identity to bring azidentity into alignment with the .NET SDK:
- A failed IMDS token request no longer stops a credential from requesting tokens in the future. All auth failures are now retriable without constructing new credentials or clients.
- ManagedIdentityCredential no longer probes IMDS to determine whether it's available before requesting a token from it. Transient latency spikes and connection failures don't disable the credential anymore.
- To minimize the impact of timeouts when IMDS really isn't available, initial requests from DefaultAzureCredential have a 1 second timeout. This timeout is removed when IMDS responds, and the credential uses its default configuration thereafter.
Closes #15396, closes #16116
=> Refactor IMDS discovery to remove probing, stop caching failures

eng/tools/generator/cmd/root.go, eng/tools/generator/cmd/v2/readme/readmeCmd.go
=> feat: add generator cmd to generate or update readme.go.md file for track2 sdk param

eng/config.json, sdk/keyvault/azkeys/client_test.go
The service disabled the Key Rotation endpoints while they investigate a service side bug. I am disabling these tests (and lowering code coverage), so I can release the library. When the service fixes the bug and enables the endpoints again the tests will be enabled (and coverage raised).
=> [KeyVault] Keys - disabling broken tests

eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/steps/build-test.yml
...rather than docker.
@seankane-msft 
I have no explanation (and can't get one short term) about why the test proxy refuses to properly start on our CI machines. I want to say that there is something wrong with the actual instances of the machines given the irregularity with which this appears.
=> Test-Proxy Runs using tool

eng/tools/generator/cmd/v2/common/fileProcessor.go
=> fix: version param name change in tools

README.md, documentation/new-version-quickstart.md, sdk/resourcemanager/aad/armaad/README.md, sdk/resourcemanager/securityinsight/armsecurityinsight/README.md
=> fix: some doc link and placeholder fix

sdk/keyvault/azsecrets/CHANGELOG.md, sdk/keyvault/azsecrets/client.go, sdk/keyvault/azsecrets/client_test.go, sdk/keyvault/azsecrets/internal/constants.go, sdk/keyvault/azsecrets/models.go, sdk/keyvault/azsecrets/testdata/recordings/TestBackupSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestBeginRecoverDeletedSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestDeleteSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestListDeletedSecrets.json, sdk/keyvault/azsecrets/testdata/recordings/TestListSecretVersions.json, sdk/keyvault/azsecrets/testdata/recordings/TestListSecrets.json, sdk/keyvault/azsecrets/testdata/recordings/TestPurgeDeletedSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestSecretTags.json, sdk/keyvault/azsecrets/testdata/recordings/TestSetGetSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestUpdateSecretProperties.json
I noticed this issue while fixing #16858 , on PATCH methods, properties would be erased if they are not explicitly set. This fixes that by setting generated values as `nil` if they are not explicitly specified.
=> [KeyVault] Fix issue with PATCH method

eng/tools/generator/autorest/model/changelog.go, sdk/resourcemanager/resources/armpolicy/CHANGELOG.md
=> fix: empty breaking or additive items in changelog

sdk/azcore/CHANGELOG.md, sdk/azcore/internal/shared/expiring_resource.go, sdk/azcore/internal/shared/expiring_resource_test.go
Today, `ExpiringResource` attempts to update its value when the resource is within 2 minutes of expiring. Call an update "eager" when it occurs within that 2 minute window, i.e. while the current value is still valid. This PR makes a couple changes to improve resilience around eager updates:
1. When an eager update fails, `ExpiringResource.GetResource()` now returns the current value--which is still valid--and no error
2. `ExpiringResource` waits at least 30 seconds between eager updates, to reduce the chance of hitting a rate limit
- this limit doesn't apply when the resource has expired or hasn't been acquired for the first time
I also enlarged the window for eager updates to 5 minutes, to align with other SDKs.
Closes #10567
=> More resilient updating of ExpiringResource

sdk/azcore/CHANGELOG.md, sdk/azcore/internal/pollers/poller.go, sdk/azcore/internal/shared/shared.go, sdk/azcore/runtime/policy_body_download.go
Poller.FinalResponse() wasn't restoring the response body after reading.
Removed duplicate definitions from GetJSON and bodyDownloadPolicy.
=> Use Payload() for reading response bodies

sdk/keyvault/azkeys/go.mod, sdk/keyvault/azkeys/go.sum, sdk/keyvault/azsecrets/go.mod, sdk/keyvault/azsecrets/go.sum, sdk/keyvault/internal/challenge_policy.go, sdk/keyvault/internal/go.mod
If the challenge request fails, return the response to the caller as it
won't contain an authentication header.
Make hard errors non retriable.
=> Avoid retries on terminal failures in challenge policy

sdk/messaging/azservicebus/internal/errors.go, sdk/messaging/azservicebus/internal/errors_test.go, sdk/messaging/azservicebus/session_receiver_test.go
Handle 500 as a retryable code (no link/connection recovery needed)
This can happen if, for instance, your link gets detached in the middle of an operation. Typically you'll get the 500, and then subsequent retries will work or reveal the underlying cause (ie, link detached, etc..).
=> [azservicebus] Handle 500 as a retryable code (no recovery needed)

sdk/messaging/azservicebus/internal/stress/templates/deploy-job.yaml
Make sure we always pull the stress test image.
Without this you'll end up in a situation where, if you're repeatedly testing, you end up running the last cached image, which is probably not what you want.
=> [azservicebus/stress] Make sure you pull the image always

sdk/azidentity/CHANGELOG.md, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential_test.go
Cloud Shell's token endpoint ignores unexpected parameters and always authenticates the signed in user. This means that when ManagedIdentityCredential requests a token for a user assigned identity, Cloud Shell returns a token for the signed in user instead. The credential should therefore return an authentication failed error when asked to get a token for a user assigned identity in Cloud Shell.
=> Cloud Shell doesn't support user assigned identities

sdk/azcore/CHANGELOG.md, sdk/azcore/core.go, sdk/azcore/core_test.go
Using reflect.New created a pointer to a zero-value underlying type.
For maps and slices this meant nil which lead to incorrect comparisons.
Instead, create an empty map which ensures a unique address.
For slices, create a slice with a length of one to avoid an apparent
optimization with zero-length slices.
=> Fix NullValue for maps and slices

sdk/azcore/core.go, sdk/azcore/core_test.go, sdk/azcore/example_test.go, sdk/azcore/to/to.go, sdk/azcore/to/to_test.go
NullValue now takes a generic type parameter instead of an interface arg
to determine the type of null sentinel value to create.
IsNullValue infers its generic parameter to determine the type of null
sentinel value to look for.
At present, there is no way to express a 'nillable' generic type
constraint so the funcs simply take a [T any] which should be fine as
they typically take/return pointer-to-types.
The 'to' package has been reduced to two funcs.
=> Convert to package, JSON null funcs to generics

azure-pipelines.yml, eng/scripts/run_tests.ps1, sdk/azcore/etag_test.go
It's broken due to lack of generics support.  Test failures will still
block CI though.
=> Disable publishing test results for now

sdk/azcore/arm/runtime/policy_bearer_token.go, sdk/azcore/internal/shared/expiring_resource.go, sdk/azcore/internal/shared/expiring_resource_test.go, sdk/azcore/runtime/policy_bearer_token.go
=> Migrate expiring resource to generics

sdk/storage/azblob/zc_container_client.go, sdk/storage/azblob/zc_service_client.go
#16295 was not fixed by #16354 because _all_ options must be repeated in following requests, not just marker. ie prefix would be dropped when paging
This PR opts to modify the passed in options. It's probably preferable to clone the options to a variable within scope to avoid mutating caller's options
=> azblob: fix ListBlob to preserve prefix while paging

sdk/azidentity/CHANGELOG.md, sdk/azidentity/authorization_code_credential.go, sdk/azidentity/azure_cli_credential.go, sdk/azidentity/chained_token_credential.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/default_azure_credential.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/environment_credential.go, sdk/azidentity/errors.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/username_password_credential.go
This makes error messages in general more consistent and improves them in some key scenarios. For example, when no inner credential can provide a token, DefaultAzureCredential.GetToken() now includes messages from those credentials' constructors (fixes #15923). There are a couple functional changes I doubt will have any impact:
- ChainedTokenCredential returns credentialUnavailableError if and only if all its sources return that type of error
- AzureCLICredential returns credentialUnavailableError on Windows when it can't identify a safe working directory
=> Revise azidentity error messages

sdk/messaging/azservicebus/README.md, sdk/messaging/azservicebus/migrationguide.md
Fixing docs issues in azservicebus
- Syntax errors in some of the samples for both the readme and the migrationguide.
- Adding in a section to describe how to enable the azcore logging specific things in azservicebus
Fixes the 'azservicebus' part of #16521
=> [azservicebus] Docs fixes

sdk/azcore/CHANGELOG.md, sdk/azcore/runtime/policy_logging.go
Customer request and it's been deemed by privacy to be safe to log.
=> Add WWW-Authenticate header to default allow-list

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/internal/errors.go, sdk/messaging/azservicebus/internal/errors_test.go
There are some errors coming from go-amqp that indicate internal or fatal errors with the connection. At the moment go-amqp does not recover from these so our only course of action is to treat them as "connection recovery" events and close and recreate the connection.
We're (jhendrix-msft and I) are still planning on a better error handling strategy, but this mitigation will be correct even after that change and will handle things until then.
Fixes #17017
=> [azservicebus] reset connection on network failures

sdk/azidentity/authorization_code_credential.go, sdk/azidentity/azure_cli_credential.go, sdk/azidentity/chained_token_credential.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/environment_credential.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/username_password_credential.go
Pointing out there's no need to pass an empty struct.
=> Document that nil credential options get default settings

sdk/messaging/azservicebus/admin/admin_client_subscription.go, sdk/messaging/azservicebus/admin/admin_client_test.go
Return topic name in subscription properties item when paging over subscriptions. Fixes #17058
=> Return topic name in subscription properties item

sdk/azidentity/CHANGELOG.md, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_client_test.go, sdk/azidentity/managed_identity_credential_test.go
Upgrading from 2017-09-01 to 2019-08-01 because the service team told us the newer version is available everywhere now. I tested this live in addition to updating the offline tests.
=> Upgrade App Service managed identity version

sdk/data/aztables/client.go, sdk/data/aztables/connection_string.go, sdk/data/aztables/service_client.go
Closes #17139 
* Adds a doc comment that non-successful HTTP responses return an error
* pass in nil for options to use default options.
=> [Tables] Improving documentation on client methods

sdk/azidentity/authorization_code_credential.go, sdk/azidentity/azure_cli_credential.go, sdk/azidentity/chained_token_credential.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/default_azure_credential.go, sdk/azidentity/default_azure_credential_test.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/environment_credential.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/logging.go, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/username_password_credential.go
A couple small changes I hope will make authentication logs less noisy and more useful:
- Stop logging errors returned from `GetToken()` because the application gets the error and is compelled to handle it
- Remove "Azure Identity => " prefix because listeners don't need it for filtering or formatting
=> Revise azidentity logging

sdk/internal/perf/perf.go, sdk/internal/perf/status.go
Closes #17176 
* ops/s is printed as a float with 2 decimal points of precision
* Removed print statements from previous PR
* Put argsument parsing in an `init` function.
* moves the `runtime.GOMAXPROCS` function to after calling `flag.Parse`
=> [Performance] fixing ops/s prints, small cleanup

sdk/azcore/CHANGELOG.md, sdk/azcore/runtime/examples_test.go, sdk/azcore/runtime/policy_include_response.go, sdk/azcore/runtime/policy_include_response_test.go, sdk/azcore/runtime/policy_retry_test.go, sdk/azcore/runtime/poller_test.go
Renamed IncludeResponse to WithCaptureResponse and changed its return
values to return a func used to retrieve the response.  This clarifies
the contract of the API and how to use it.
Removed ResponseFromContext as it's no longer required.
=> Refine HTTP response captuing APIs

sdk/messaging/azservicebus/internal/errors.go, sdk/messaging/azservicebus/internal/errors_test.go
Recategorize recovery for errors:
- amqp.ErrorInternalError and amqp.ErrSessionClosed are now categorized as connection level recovery.
- ErrorTransferLimitExceeded is a link recovery event. From what I can see it signals a mismatch between wanting to send and not having credit available. A link reset should cause a reset on both sides.
- Default to connection recovery except for specific fatal errors.
=> [azservicebus] Recategorize recovery for errors

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/internal/amqpLinks.go, sdk/messaging/azservicebus/internal/amqpLinks_test.go, sdk/messaging/azservicebus/internal/errors.go, sdk/messaging/azservicebus/internal/stress/tests/idle_fast_reconnect.go, sdk/messaging/azservicebus/internal/stress/tests/tests.go, sdk/messaging/azservicebus/internal/stress/values.yaml, sdk/messaging/azservicebus/internal/utils/retrier.go, sdk/messaging/azservicebus/internal/utils/retrier_test.go
Fixing the 'stale' sender by adding in some special double-iteration-0 logic in the 
amqpLinks.Retry().
This changes the semantics of how ResetAttempts() works but it wasn't used anywhere 
anymore and it makes more sense this way anyways.
Fixes #17182
=> [azservicebus] Quicker reattach of mostly-idle links

sdk/azidentity/CHANGELOG.md, sdk/azidentity/chained_token_credential.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/environment_credential_test.go
Fixes #17144 by adding synchronization around `ChainedTokenCredential.successfulCredential`. The field is assigned at most once, so I used a read lock to minimize performance impact on subsequent calls.
=> Prevent ChainedTokenCredential data race

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/admin/admin_client_queue.go, sdk/messaging/azservicebus/admin/admin_client_subscription.go, sdk/messaging/azservicebus/admin/admin_client_test.go, sdk/messaging/azservicebus/admin/admin_client_topic.go, sdk/messaging/azservicebus/internal/atom/entity_manager.go
Making it so our adminClient returns a nil result when the underlying entity is not found.
This avoids having to fabricate a fake status code (and possibly inconsistent HTTP response), which was the worse alternative.
Fixes #17065
=> [azservicebus] Return nil in adminClient functions for non-existent entities

sdk/data/aztables/CHANGELOG.md, sdk/data/aztables/constants.go, sdk/data/aztables/example_test.go, sdk/data/aztables/go.mod, sdk/data/aztables/go.sum, sdk/data/aztables/transaction_batch_test.go, sdk/data/aztables/transactional_batch.go
After discussion with Jeff, the `TransactionResponse` object is empty now and customers can parse the `azcore.ResponseError` to understand why the transaction failed.
=> [Tables] Batching response struct is now empty

eng/config.json
As we are starting to adding live test for resourcemanager, the test coverage is not too high at first. Set the config to zero to prevent ci failure when coverage check.
=> chore: add coverage for resourcemanager

sdk/messaging/azservicebus/receiver_test.go, sdk/messaging/azservicebus/receiver_unit_test.go
This adds in some tests for #17047, where we were concerned about which primitives can be both sent and deserialized properly.
go-amqp currently lacks support for decoding/encoding the AMQP primitives for TypeCodeDecimal and TypeCodeChar. These don't necessarily have a proper analog where we'd properly round-trip them so we'd need to think about how to implement this in Go, if needed.
Fixes #17047
=> [azservicebus] Add testing for primitive data types.

eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml, eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/jobs/live.tests.yml, eng/pipelines/templates/steps/build-test.yml, eng/scripts/run_tests.ps1, sdk/keyvault/azcertificates/ci.yml
It happens sporadically, but `azcertificates` (full of LROs) live tests will fail because the tests do not complete in >600s (the default in Go). This change provides a way to specify in the `ci.yml` for larger test suites.
=> [EngSys] Optionally extend test runtime

sdk/azcore/CHANGELOG.md, sdk/azcore/runtime/pager.go, sdk/azcore/runtime/pager_test.go
=> Add generic pager implementation

sdk/azcore/arm/runtime/poller.go, sdk/azcore/arm/runtime/poller_test.go, sdk/azcore/core.go, sdk/azcore/runtime/poller.go, sdk/azcore/runtime/poller_test.go
Due to lack of support for type aliasing a generic type, we have
duplicate definitions for ARM and data-plane.  We can consolidate the
definitions when type aliasing support is added in the future.
=> Add generic poller implementation

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/admin/admin_client.go, sdk/messaging/azservicebus/client.go, sdk/messaging/azservicebus/client_test.go, sdk/messaging/azservicebus/go.mod, sdk/messaging/azservicebus/go.sum, sdk/messaging/azservicebus/internal/atom/entity_manager.go, sdk/messaging/azservicebus/internal/namespace.go, sdk/messaging/azservicebus/internal/namespace_test.go, sdk/messaging/azservicebus/internal/sbauth/token_provider.go, sdk/messaging/azservicebus/internal/stress/tools/generate_sas.go, sdk/messaging/azservicebus/internal/stress/tools/tools.go
Adding support for parity with other Service Bus libraries allow you pass a connection string with a SharedAccessSignature, rather than an embedded SharedKey.
Fixes #16641
=> [azservicebus] Adding in support for embedded SharedAccessSignatures in connection strings

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/internal/stress/tests/constant_detachment.go, sdk/messaging/azservicebus/message_batch.go, sdk/messaging/azservicebus/message_batch_test.go
Message batches were being calculated incorrectly, using an assumed fixed size overhead which wasn't accurate. We're now doing this dynamically. 
This also made it so I could fix a stress test that's been broken because of the batch size.
Fixes #16090
Fixes #15562
=> [azservicebus] Fixing batch algorithm to calculate accurately

sdk/messaging/azservicebus/admin/admin_client_test.go, sdk/messaging/azservicebus/client.go, sdk/messaging/azservicebus/client_test.go, sdk/messaging/azservicebus/internal/amqpLinks.go, sdk/messaging/azservicebus/internal/amqpLinks_test.go, sdk/messaging/azservicebus/internal/amqp_test_utils.go, sdk/messaging/azservicebus/internal/namespace.go, sdk/messaging/azservicebus/internal/namespace_test.go, sdk/messaging/azservicebus/internal/test/test_helpers.go, sdk/messaging/azservicebus/receiver.go, sdk/messaging/azservicebus/receiver_test.go, sdk/messaging/azservicebus/sender.go, sdk/messaging/azservicebus/sender_test.go
Fixing a few errors related to either cleanup or closing:
- negotiateClaim() would cycle infinitely if there was a fatal error, rather than exiting
- the func() returned from negotiateClaim would return before the claim loop had completely exited. Not fatal, but the intention was that there was no further claim activity after the cancel func was called. Fixed.
- Connection was not being by client.Close(). Also, added in a "permanent close" error that gets returned from all the normal spots.
- Fixing some race conditions that were in the _test_ code
Fixes #17183
=> [azservicebus] Fixing a few errors related to either cleanup or closing

azure-pipelines.yml, eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml, eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/jobs/mgmt-mock-test.yml, eng/pipelines/templates/variables/globals.yml, eng/tools/smoketests/cmd/root.go, sdk/azcore/internal/pipeline/request.go
=> Migrate to latest two versions of Go

eng/pipelines/templates/steps/build-test.yml, eng/scripts/Build_Perf.ps1
* Runs `go build` and `go vet` on the testdata/perf directory if it exists
=> [EngSys] adding ci checks for performance

eng/pipelines/templates/steps/build-test.yml
Fixes invalid yaml syntax introduced in #17306 (related to #17364 as well).
The template pipeline triggers against `eng/` changes to catch potential issues. If there are syntactic errors in the yaml then the pipeline "fails to run" which isn't a valid criteria/event to get posted back to the check runs.
For example: [failing pipeline](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1456127&view=results)
Currently, the only way to verify eng pipeline yaml changes are valid would be to manually invoke the pipeline like `/azp run go - aztemplate` and make sure it was successfully run. I'm not sure if it's going to be possible to get the check runs to detect pipeline initialization failures.
=> Fix performance test build task

eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml, eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/build-test.yml, eng/pipelines/templates/variables/globals.yml, eng/scripts/MgmtTestLib.ps1, eng/scripts/run_tests.ps1, sdk/azcore/CHANGELOG.md, sdk/azcore/internal/shared/constants.go
Removed some temporary CI changes after rebasing on main.
Added missing entries to the changelog.
Bumped version to v0.23.0 for breaking changes.
=> Clean-up in prep for merging feature/generics to main

sdk/keyvault/azcertificates/README.md
The link right now is going to the Python library. Also fixed a couple errors in the sample code.
=> Fix pkg.go.dev link for certificates README

sdk/messaging/azservicebus/session_receiver.go
Use `maxMessages` instead of `numMessages` to match the right argument name
=> Use correct argument name in function description

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/client.go, sdk/messaging/azservicebus/client_test.go, sdk/messaging/azservicebus/internal/amqpLinks.go, sdk/messaging/azservicebus/internal/amqpLinks_test.go, sdk/messaging/azservicebus/internal/amqp_test_utils.go, sdk/messaging/azservicebus/internal/errors.go, sdk/messaging/azservicebus/internal/errors_test.go, sdk/messaging/azservicebus/internal/namespace.go, sdk/messaging/azservicebus/internal/rpc.go, sdk/messaging/azservicebus/receiver.go, sdk/messaging/azservicebus/receiver_test.go, sdk/messaging/azservicebus/sender.go, sdk/messaging/azservicebus/session_receiver.go
410 (lock lost) handling needed to be separated for sessions and non-session links.
For non-session links losing a link is essentially unrecoverable - the lock cannot be reobtained with just the lock token so further retries will always fail.
For _session_ based links it's different since you actually obtain a session lock by opening a link for a particular session ID. You can retry re-opening the link and there are cases where, on detach, that you might have some overlap until the session is actually available again (this is shown in the `TestSessionReceiver_Detach` test).
So the split here is simple - all retrying is really handled in amqpLinks, so now it takes a parameter giving it the proper function to determine if an error is fatal or retryable. As part of this I also made the …
=> [azservicebus] Handle 410 properly for session and non-session based links.

sdk/messaging/azservicebus/go.mod, sdk/messaging/azservicebus/go.sum
Reference by semver, rather than commit tag.
Without this `go get -u` will just grab the latest _commit_ for the package, even when you reference a specific commit in main. This is just an internal package so it's interface has changed in breaking ways - future updates are not guaranteed to be compatible with older packages until we reach GA.
Fixes #17357
=> [azservicebus] Reference `messaging/internal` by semver, rather than commit tag.

sdk/azcore/CHANGELOG.md, sdk/azcore/arm/internal/pollers/async/async.go, sdk/azcore/arm/runtime/poller.go, sdk/azcore/internal/pollers/loc/loc.go, sdk/azcore/internal/pollers/loc/loc_test.go, sdk/azcore/internal/pollers/op/op.go, sdk/azcore/internal/pollers/op/op_test.go, sdk/azcore/internal/pollers/poller.go, sdk/azcore/runtime/poller.go
Converted FinalStateVia to a const as its values are constrained.
NOTE: this makes the necessary changes to public surface area.  However, we don't have coverage in autorest for data-plane LROs at present, so the implementation is incomplete.  This doesn't impact the current behavior though.
Partially fixes https://github.com/Azure/azure-sdk-for-go/issues/17415
=> Add FinalStateVia to data-plane poller options

eng/scripts/Language-Settings.ps1
For things where we find perfdata or other go.mod files
without the other required properties we should just skip
them in processing
=> Skip invalid package modules

sdk/data/aztables/CHANGELOG.md, sdk/data/aztables/models.go
Appears this should be PossibleGeoReplicationStatus~Type~Values, following the GeoReplicationStatus~Type~ rename in the latest release
=> Rename PossibleGeoReplicationStatusTypeValues to match new type name

sdk/azidentity/CHANGELOG.md, sdk/azidentity/azure_cli_credential.go
The credential assumes `exec.Cmd.Output()` returns only `exec.ExitError`. However, that method can return other errors in uncommon cases, causing a panic. The fix is simple: handle the error as an `exec.ExitError` only when `errors.As` returns `true`.
Closes #17490
=> Prevent AzureCLICredential panic on unexpected error

eng/scripts/Language-Settings.ps1, eng/scripts/validate_go_mod.ps1
@benbp based on my searches this was the most elegant way to tackle this situation. I don't want to block a release if a perf test's go.mod file uses a replace directive, this checks if `testdata` is in the path for a go.mod file and skips it if this is correct.
Closes #17441
=> dont block release on perf go.mod files

sdk/data/aztables/access_policy_test.go, sdk/data/aztables/client.go, sdk/data/aztables/testdata/recordings/TestSetAccessPolicy.json, sdk/data/aztables/testdata/recordings/TestSetEmptyAccessPolicy.json, sdk/data/aztables/testdata/recordings/TestSetNullAccessPolicy.json
Brought on by Joel's comment [here](https://github.com/Azure/azure-sdk-for-go/pull/17570/files#r849644507), there is a reason to pass in `nil` options for `SetAccessPolicy`, it will remove any previously set access policies. AccessPolicies is `nil`-able and doesn't fit the same mold as what I have generally used in named parameters (that they can not be nil by the service).
=> [Tables] improving testing for access policies

sdk/azidentity/CHANGELOG.md, sdk/azidentity/azidentity_test.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/username_password_credential.go
Calling `GetToken()` without specifying a scope doesn't make sense--it's like saying "I want to access something but don't know what"--but our API allows it. I think that's okay because calling `GetToken()` directly is an advanced scenario whose users should know they must specify a scope. However, the error experience through MSAL is poor for users who don't know that, because MSAL will request a token for its implicit default scopes and return a confusing error (https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/304).
=> GetToken() returns an error when the caller specifies no scope

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/README.md, sdk/messaging/azservicebus/example_client_test.go, sdk/messaging/azservicebus/internal/amqpLinks.go, sdk/messaging/azservicebus/internal/amqpLinks_test.go, sdk/messaging/azservicebus/internal/amqp_test_utils.go, sdk/messaging/azservicebus/internal/atom/entity_manager.go, sdk/messaging/azservicebus/internal/namespace.go, sdk/messaging/azservicebus/internal/utils/retrier.go, sdk/messaging/azservicebus/internal/utils/retrier_test.go, sdk/messaging/azservicebus/liveTestHelpers_test.go, sdk/messaging/azservicebus/log.go, sdk/messaging/azservicebus/log_test.go, sdk/messaging/azservicebus/messageSettler.go, sdk/messaging/azservicebus/receiver.go, sdk/messaging/azservicebus/receiver_test.go, sdk/messaging/azservicebus/sender.go, sdk/messaging/azservicebus/session_receiver.go
Made the log constants publicly available so people can use them, rather than having to hardcode/know the strings that are there.
This also helps with intellisense to discover the set of available values.
Also:
- Added example for log constants and one for retry options
- Added a new log.Event for `Sender' (log.EventSender)
- Removed log.EventMgmtLink and just made them all log.EventReceiver or log.EventSender, which made more sense.
- Removed log.EventRetry in favor of inheriting/using whatever the actual client's EventType is.
Fixes #17553
=> [azservicebus] Export our log.Event constants 

sdk/azcore/internal/shared/response_error.go, sdk/azcore/internal/shared/response_error_test.go
Extending parsing on ResponseError to handle `odata.error` case from storage/tables
=> [Core] extending parsing for storage

documentation/previous-versions-quickstart.md
This is a bulk fix adding the --scopes parameter to `az ad sp create-for-rbac` commands in documentation.
=> Bulk fix adding --scopes Parameter to Documentation

sdk/azidentity/CHANGELOG.md, sdk/azidentity/README.md, sdk/azidentity/azidentity.go, sdk/azidentity/default_azure_credential.go, sdk/azidentity/default_azure_credential_test.go, sdk/azidentity/environment_credential.go, sdk/azidentity/environment_credential_test.go
DefaultCredential may not work when there are multiple managed
identities assigned on a VM/VMSS node. It's not possible to
distinguish the client ID to use in this case. The PR addresses
the issue by using the value set for AZURE_CLIENT_ID environment
variables.
Signed-off-by: Zhongcheng Lao <Zhongcheng.Lao@microsoft.com>
=> Distinguish client ID when multiple identities assigned with DefaultCredential

sdk/azcore/CHANGELOG.md, sdk/azcore/arm/client_options.go, sdk/azcore/arm/policy/policy.go, sdk/azcore/arm/runtime/pipeline.go, sdk/azcore/arm/runtime/policy_bearer_token.go, sdk/azcore/arm/runtime/policy_bearer_token_test.go, sdk/azcore/policy/policy.go
...because the related features require implementation in `azidentity` we intend to add after the next release (tracked by #14932, #17159). Closes #17580.
=> Remove multi- and cross-tenant authentication API

sdk/azidentity/MIGRATION.md
Migrating from track 1 to 2 authentication means rewriting code using `autorest/adal` to do the same thing with `azidentity`, so I focused this guide on before/after examples of common scenarios. Closes #17145
=> Add azidentity migration guide

sdk/appconfig/azappconfig/client.go
=> remove unnecessary setting to empty string

sdk/data/aztables/CHANGELOG.md, sdk/data/aztables/README.md, sdk/data/aztables/autorest.md, sdk/data/aztables/client.go, sdk/data/aztables/client_test.go, sdk/data/aztables/entity_test.go, sdk/data/aztables/example_test.go, sdk/data/aztables/internal/connection.go, sdk/data/aztables/internal/constants.go, sdk/data/aztables/internal/models.go, sdk/data/aztables/internal/models_serde.go, sdk/data/aztables/internal/response_types.go, sdk/data/aztables/internal/service_client.go, sdk/data/aztables/internal/table_client.go, sdk/data/aztables/internal/time_rfc1123.go, sdk/data/aztables/internal/time_rfc3339.go, sdk/data/aztables/proxy_test.go, sdk/data/aztables/service_client.go, sdk/data/aztables/service_client_test.go, sdk/data/aztables/shared_access_signature_test.go, sdk/data/aztables/transaction_batch_test.go
Regenerated code with latest code generator (no public changes).
Added directive to autorest.md to fix up parts of codegen.
=> Renamed pager APIs per new guidelines

sdk/azcore/CHANGELOG.md, sdk/azcore/arm/runtime/poller.go, sdk/azcore/arm/runtime/poller_test.go, sdk/azcore/runtime/poller.go, sdk/azcore/runtime/poller_test.go
Passing nil/zero-value options defaults to 30s polling frequency.
=> Add options bag to PollUntilDone method

sdk/keyvault/internal/CHANGELOG.md, sdk/keyvault/internal/challenge_policy.go, sdk/keyvault/internal/constants.go, sdk/keyvault/internal/expiring_resource.go, sdk/keyvault/internal/expiring_resource_test.go
It wasn't working anyways and has been removed in the upcoming release.
Refactored the expiring resource machinery to use generics.
=> Removed dependency on TokenRequestOptions.TenantID

azure-pipelines.yml
=> fix: wrong ref for global variables

sdk/azcore/CHANGELOG.md, sdk/azcore/arm/arm.go, sdk/azcore/arm/runtime/pipeline.go, sdk/azcore/arm/runtime/pipeline_test.go, sdk/azcore/cloud/cloud.go, sdk/azidentity/azidentity.go, sdk/azidentity/azidentity_test.go
Closes #17732.  https://github.com/Azure/autorest.go/pull/810 will make the corresponding codegen change.
=> Rename AzurePublicCloud -> AzurePublic

sdk/internal/CHANGELOG.md, sdk/internal/log/log.go, sdk/internal/log/log_test.go, sdk/internal/version.go
They should be defined in azcore/log, not here.
Added comments indicating which parts of log are public surface area.
=> Removed log constants

sdk/azcore/log/log.go
The constants in the internal package are going away.
=> Define log constants in the log package

sdk/azcore/internal/pollers/armloc/loc.go, sdk/azcore/internal/pollers/armloc/loc_test.go, sdk/azcore/internal/pollers/async/async.go, sdk/azcore/internal/pollers/async/async_test.go, sdk/azcore/internal/pollers/body/body.go, sdk/azcore/internal/pollers/body/body_test.go, sdk/azcore/internal/pollers/loc/loc.go, sdk/azcore/internal/pollers/loc/loc_test.go, sdk/azcore/internal/pollers/op/op.go, sdk/azcore/internal/pollers/op/op_test.go, sdk/azcore/internal/pollers/poller.go, sdk/azcore/internal/pollers/poller_test.go, sdk/azcore/internal/pollers/util.go, sdk/azcore/internal/pollers/util_test.go
Previously, the Poller.Poll() method was determining when an LRO failed.
While this works for well-known states, it's not extensible.  Instead,
the underlying polling implementation should be responsible for
determining if it's reached a terminal state (failure or otherwise).
=> Move LRO failure detection to the implementing poller

sdk/appconfig/azappconfig/CHANGELOG.md, sdk/appconfig/azappconfig/client.go, sdk/appconfig/azappconfig/client_test.go, sdk/appconfig/azappconfig/internal/generated/constants.go
We were using `Setting` struct as input parameter for client methods.
But it was not clear, which ones are mandatory (`key`, sometimes nullable `value`), which are optional (`label`), and which are ignored (the rest).
It was also confusing with `SetReadOnly()`: setting does have `IsReadOnly` field, and also `SetReadOnly()` has mandatory boolean argument. Now, `SetReadOnly()` takes `key`, and boolean `isReadOnly`.
Closes #17264.
=> AppConfig: inline method parameters instead of using Setting struct

sdk/keyvault/azkeys/client_test.go, sdk/keyvault/azkeys/test-resources.json
Copying the latest `test-resources.json` from .NET, setting the MHSM deployment region to westus3 to avoid contention, and skipping a troublesome test (which I'll unskip in a future PR). That should get the azkeys nightly run to pass 🤞
=> Update azkeys test-resources.json

sdk/azcore/CHANGELOG.md, sdk/azcore/runtime/pager.go, sdk/azcore/runtime/pager_test.go
This is to align the naming with PollingHandler which is similar in
concept but for pollers.
=> Renamed PageProcessor to PagingHandler

sdk/messaging/azservicebus/client.go, sdk/messaging/azservicebus/error.go, sdk/messaging/azservicebus/example_receiver_test.go, sdk/messaging/azservicebus/example_sender_test.go, sdk/messaging/azservicebus/internal/amqp_test_utils.go, sdk/messaging/azservicebus/internal/errors.go, sdk/messaging/azservicebus/internal/errors_test.go, sdk/messaging/azservicebus/internal/exported/error.go, sdk/messaging/azservicebus/internal/exported/error_test.go, sdk/messaging/azservicebus/internal/rpc.go, sdk/messaging/azservicebus/internal/rpc_test.go, sdk/messaging/azservicebus/messageSettler.go, sdk/messaging/azservicebus/messageSettler_test.go, sdk/messaging/azservicebus/receiver.go, sdk/messaging/azservicebus/receiver_test.go, sdk/messaging/azservicebus/receiver_unit_test.go, sdk/messaging/azservicebus/sender.go, sdk/messaging/azservicebus/sender_unit_test.go, sdk/messaging/azservicebus/session_receiver.go, sdk/messaging/azservicebus/session_receiver_test.go, sdk/messaging/azservicebus/session_receiver_unit_test.go
Created `azservicebus.Error` to represent errors that a customer can use programatically.
azservicebus.Error contains a code that customers can use, which is considered stable and part of the supported API. 
Today we only have two codes - CodeLockLost, which comes back if the lock has expired and CodeConnectionLost, which comes back if we failed on an error that is retryable.
Fixes #17283
=> [azservicebus] Adding `azservicebus.Error` to represent errors that a customer can use programatically.

sdk/azcore/CHANGELOG.md, sdk/azcore/arm/runtime/policy_register_rp.go
Cleaned up response envelopes per latest pattern.
=> Unexport some types that aren't supposed to be

sdk/azidentity/CHANGELOG.md, sdk/azidentity/chained_token_credential.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/default_azure_credential.go, sdk/azidentity/environment_credential_test.go, sdk/azidentity/errors.go, sdk/azidentity/managed_identity_credential_test.go, sdk/azidentity/username_password_credential_test.go
To be consistent with other errors returned from our SDKs.
=> Return AuthenticationFailedError by pointer

sdk/azcore/CHANGELOG.md, sdk/azcore/arm/runtime/pipeline_test.go, sdk/azcore/arm/runtime/policy_bearer_token.go, sdk/azcore/arm/runtime/policy_bearer_token_test.go, sdk/azcore/arm/runtime/policy_register_rp_test.go, sdk/azcore/core.go, sdk/azcore/runtime/policy_bearer_token.go, sdk/azcore/runtime/policy_bearer_token_test.go
Returning by pointer is cruft from an early design and not necessary.
=> Return AccessToken by value

sdk/azcore/CHANGELOG.md, sdk/azcore/runtime/poller.go, sdk/azcore/runtime/poller_test.go
Fixed the behavior of Poll and Result methods and updated their doc
comments explaining the behavior.
Clarified some other Poller doc comments and improved error messages.
=> Fixes to runtime.Poller

sdk/azcore/CHANGELOG.md, sdk/azcore/arm/runtime/pipeline.go, sdk/azcore/runtime/pipeline.go, sdk/azcore/runtime/pipeline_test.go
This ensures applications are always able to work around or counteract a client's default policies.
=> Place application specified policies after client default policies

sdk/azcore/internal/pollers/armloc/loc.go, sdk/azcore/internal/pollers/armloc/loc_test.go, sdk/azcore/internal/pollers/async/async.go, sdk/azcore/internal/pollers/async/async_test.go, sdk/azcore/internal/pollers/body/body.go, sdk/azcore/internal/pollers/body/body_test.go, sdk/azcore/internal/pollers/loc/loc.go, sdk/azcore/internal/pollers/loc/loc_test.go, sdk/azcore/internal/pollers/op/op.go, sdk/azcore/internal/pollers/op/op_test.go, sdk/azcore/internal/pollers/util.go, sdk/azcore/internal/pollers/util_test.go, sdk/azcore/runtime/poller.go
Always use the out parameter and remove the returned T.
=> Simplify the Result method on PollingHandler

sdk/azcore/CHANGELOG.md, sdk/azcore/runtime/policy_telemetry.go, sdk/azcore/runtime/policy_telemetry_test.go
Making this change was only a little more work than opening an issue to discuss the change, so here's a PR for discussion 😄 (I don't think this is a release blocker)
The other SDKs don't include their core library version in User-Agent strings, I suppose because the template in the [general design guidelines](https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy) doesn't include it. Does anyone recall the reasoning behind ourformat? Is `azcore` adoption interesting independent of client module adoption?
=> Remove azcore version info from default User-Agent

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/README.md, sdk/messaging/azservicebus/admin_client_test.go, sdk/messaging/azservicebus/client_test.go, sdk/messaging/azservicebus/example_receiver_test.go, sdk/messaging/azservicebus/message.go, sdk/messaging/azservicebus/message_test.go, sdk/messaging/azservicebus/receiver_test.go, sdk/messaging/azservicebus/sender_test.go, sdk/messaging/azservicebus/session_receiver_test.go
Changed ReceivedMessage.Body() to be a field of type `[]byte`. 
The entire reason it was a function was to return an error in the rare case that the underlying AMQP message was using the Value or Sequence section, rather than Data (or that Data itself was multiple byte arrays, not just a single one). Being a function makes it harder for users to create tests where they pass around `ReceivedMessage` since they can't create it themselves.
In the end it was agreed that just having a nil Body was enough signal for users to know that something was wrong, and that the error that was returned wouldn't have really been actionable (much like Body being nil, it was basically a true/false with exactly one error message).
Thanks to @ItalyPaleAle for pointing this out!
Fixes #17877
=> [azservicebus] Changing ReceivedMessage.Body() to ReceivedMessage.Body (a field)

sdk/azcore/internal/pollers/body/body_test.go, sdk/azcore/internal/pollers/loc/loc.go, sdk/azcore/internal/pollers/loc/loc_test.go
There are a few corner-cases for location polling where ARM can reply
with a provisioning state, so use it if available.
Fixed a test bug for body polling.
=> Check for provisioning state during location polling

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/internal/amqpLinks.go, sdk/messaging/azservicebus/internal/amqpLinks_test.go, sdk/messaging/azservicebus/internal/cbs.go, sdk/messaging/azservicebus/internal/namespace.go, sdk/messaging/azservicebus/internal/rpc.go, sdk/messaging/azservicebus/internal/stress/shared/stress_context.go, sdk/messaging/azservicebus/receiver.go
Found a bug while adding in some more debug logging.
- Fixing a bug where the prefetch cache might not be drained if the user had cancelled the receive call. The prefetch call was specifically made so it no longer incurs any network I/O, so cancellation is something we should NOT do as it could cause us to lose messages we've already received.
- Adding (and fixing) logging to make things easier on diagnostics later.
- Cleaning up the close of the RPCLink so you can distinguish errors from normal shutdown. This eliminates a source of noise where it appears the negotiateClaim()'s response router was dying, when it was actually just the client itself being closed.
=> [azservicebus] Quality of life fixes for logging, fix for prefetch.

sdk/data/azcosmos/cosmos_client.go, sdk/data/azcosmos/cosmos_policy_bearer_token.go, sdk/data/azcosmos/cosmos_policy_bearer_token_test.go
Related to https://github.com/Azure/azure-sdk-for-go/issues/17752
Refactor the internal AAD policy using the new types exposed in https://github.com/Azure/azure-sdk-for-go/pull/17798
Instead of rewriting the Auth header from the azcore AAD policy (which was a temporal workaround), we can now correctly create the header ourselves with the desired format.
=> Cosmos DB - Refactor AAD policy

sdk/keyvault/azsecrets/README.md, sdk/keyvault/azsecrets/client.go
Updating snippets, adding aka.ms links, making docs more consistent, removing references to access policy permissions because Key Vault now also supports RBAC, and other miscellany.
=> Revise azsecrets readme and doc comments

eng/scripts/Invoke-DependencyCheck.ps1
=> fix: ignore deprecated package when dep check

eng/tools/smoketests/cmd/models.go, eng/tools/smoketests/cmd/root.go, eng/tools/smoketests/go.mod, eng/tools/smoketests/go.sum
Old version cannot handle beta version like "1.1.0-beta.1". This fix will fix all the ci failure.
=> fix semver parse problem

sdk/messaging/azservicebus/admin/admin_client_queue.go, sdk/messaging/azservicebus/admin/admin_client_subscription.go, sdk/messaging/azservicebus/admin/admin_client_test.go, sdk/messaging/azservicebus/admin/admin_client_topic.go, sdk/messaging/azservicebus/internal/atom/converters.go, sdk/messaging/azservicebus/internal/atom/models.go
Return an error for a missing CountDetails node in the returned responses for Get<Entity>RuntimeProperties. This doesn't fix the issue in #17868 but it'll stop the panic, which is infinitely worse.
=> Handle a missing CountDetails node in the returned responses for Get<Entity>RuntimeProperties

eng/scripts/Invoke-DependencyCheck.ps1, eng/scripts/MgmtTestLib.ps1, eng/tools/generator/cmd/v2/common/fileProcessor.go, eng/tools/generator/cmd/v2/common/generation.go, sdk/resourcemanager/eventgrid/armeventgrid/autorest.md
This PR fix the release tool and script for mgmt. SDK new version. It will automatic add `vX` to module path to align with Go semantic version convention for SDK modules, test imports and dependency check script.
=> tool: release-v2, dep check and test generation support go semantic version convention

eng/pipelines/templates/steps/analyze.yml
There are many daily ci failure (e.g. [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1598529&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=45ee1ca9-5b97-59ac-94ed-a114ab499701)) because of the failure of golangci-lint install step. Add retry to resolve it.
Resolve https://github.com/Azure/azure-sdk-for-go/issues/18179
=> ci: add retry to the golangci-lint install step to prevent failure of network issue

sdk/keyvault/internal/CHANGELOG.md, sdk/keyvault/internal/constants.go, sdk/keyvault/internal/parse.go, sdk/keyvault/internal/parse_test.go
While adding test cases verifying we preserve ports when parsing Key Vault identifiers (closes #18190), I noticed we add trailing slashes to parsed vault URLs e.g., we return `https://foo.vault.com/` as the vault URL of `https://foo.vault.com/keys/mykey`. I think we should stop doing this because although I doubt the trailing slash breaks anything, it's unnecessary and semantically incorrect in implying a directory or an empty path.
=> Remove trailing slashes from parsed vault URLs

eng/pipelines/templates/jobs/archetype-sdk-client.yml
Temporary location override at the go repo level as part of https://github.com/Azure/azure-sdk-tools/issues/3398 to
address capacity restrictions.
=> Override live test location default to westus

eng/pipelines/templates/steps/build-test.yml
Fail the "install coverage and junit dependencies" step if any of the
tools fail to install.
Add a few retries if the step fails.
=> Fail tool installation when writing to stderr

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/admin/admin_client_queue.go, sdk/messaging/azservicebus/admin/admin_client_test.go, sdk/messaging/azservicebus/admin/admin_client_topic.go, sdk/messaging/azservicebus/internal/atom/entity_manager.go, sdk/messaging/azservicebus/internal/atom/models.go, sdk/messaging/azservicebus/internal/test/test_helpers.go, sdk/messaging/azservicebus/test-resources.bicep
Service Bus Premium allows you to configure the maximum message size. This change exposes that property, bringing it to parity with other SDKs.
Fixes #15917
=> [azservicebus] Allow setting the MaxMessageSizeInKilobytes property

sdk/keyvault/azkeys/client_test.go, sdk/keyvault/azkeys/utils_test.go
azkeys test runs have been timing out because one test case doesn't skip its MHSM subtest when lacking MHSM configuration. This PR moves the MHSM check into the helper function that initializes recording, ensuring all recorded tests execute it.
=> Prevent azkeys tests incorrectly targeting MHSM

sdk/messaging/azservicebus/CHANGELOG.md, sdk/messaging/azservicebus/internal/cbs.go, sdk/messaging/azservicebus/internal/namespace.go, sdk/messaging/azservicebus/internal/namespace_test.go
We weren't nil'ing out the ns.client value, so it was possible for any calls to ns.GetAMQPClient() to get an old (and closed) client. This would cause thrash during recovery since clients would get a stale connection, see it failed and try to start a recovery.
=> [azservicebus] Fixing bug where a closed namespace would not be properly revived by negotiateClaim.

sdk/azidentity/CHANGELOG.md, sdk/azidentity/azidentity.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/testdata/recordings/TestClientCertificateCredential_Regional.json, sdk/azidentity/version.go
Cherry-picking #18308 onto a release branch off the 1.0.1 tag because the beta feature comes before ESTS-R on main.
=> Prepare azidentity 1.1.0 release
