Azure/azure-sdk-for-go

sdk/keyvault/internal/CHANGELOG.md

Filling out details for release.

Prepare internal changelog for release

---

eng/common/scripts/Helpers/Metadata-Helpers.ps1
eng/common/scripts/Update-DocsMsMetadata.ps1
sdk/azcore/CHANGELOG.md
sdk/azcore/core.go
sdk/azcore/core_test.go

Rebase feature/generics

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/zc_container_client.go
sdk/storage/azblob/zc_sas_account.go
sdk/storage/azblob/zc_sas_query_params.go
sdk/storage/azblob/zc_sas_service.go
sdk/storage/azblob/zc_validators.go
sdk/storage/azblob/zm_blob_request_options.go

Fix SAS Creation + other issue

---

sdk/keyvault/azcertificates/CHANGELOG.md

[Certificates] Add Date to changelog

---

sdk/keyvault/azcertificates/CHANGELOG.md

Correct the date

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/liveTestHelpers_test.go
sdk/messaging/azservicebus/message.go
sdk/messaging/azservicebus/messageSettler_test.go
sdk/messaging/azservicebus/message_test.go
sdk/messaging/azservicebus/sender_test.go

Adding in State property for message.
The State gives you information about whether a message is Active, Deferred or Scheduled.
Fixes #16961

[azservicebus] Adding in MessageState property for message

---

sdk/keyvault/azkeys/client.go
sdk/keyvault/azkeys/client_test.go

@Duffney found an issue while writing samples with the DeleteKey poller. Fix for that issue here

[KeyVault] Fixing issue with returned empty struct from DeleteKey poller

---

sdk/keyvault/azkeys/client.go
sdk/keyvault/azkeys/client_test.go
sdk/keyvault/azkeys/crypto/crypto_client.go
sdk/keyvault/azkeys/crypto/responses/responses.go
sdk/keyvault/azkeys/responses/pagers.go
sdk/keyvault/azkeys/responses/pollers.go
sdk/keyvault/azkeys/responses/responses.go

remove raw responses

---

sdk/resourcemanager/securityinsight/armsecurityinsight/CHANGELOG.md
sdk/resourcemanager/securityinsight/armsecurityinsight/autorest.md
sdk/resourcemanager/securityinsight/armsecurityinsight/go.mod
sdk/resourcemanager/securityinsight/armsecurityinsight/zz_generated_constants.go

retract sdk/resourcemanager/securityinsight/armsecurityinsight

---

azure-pipelines.yml

Fixes https://github.com/Azure/azure-sdk-for-go/issues/16953

Add missing 'or' expression to find command in track 1 test discovery

---

services/compute/mgmt/2021-11-01/compute/_meta.json

modify the compute  _meta files

---

sdk/keyvault/azkeys/CHANGELOG.md
sdk/keyvault/azkeys/client.go
sdk/keyvault/azkeys/client_test.go
sdk/keyvault/azkeys/testdata/recordings/TestCreateOCTKey/TestCreateOCTKey_NON-HSM.json

[KeyVault] adding a comment about nil options

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go

Will release core 0.21.2 after merging this PR.

[Core] Changelog date for release

---

sdk/keyvault/azsecrets/CHANGELOG.md
sdk/keyvault/azsecrets/README.md
sdk/keyvault/azsecrets/client.go
sdk/keyvault/azsecrets/example_test.go
sdk/keyvault/azsecrets/go.mod
sdk/keyvault/azsecrets/go.sum

* bump azcore
* remove RawResponse
* add example for using runtime.WithCaptureResponse
* Readme docs for troubleshooting with *http.Response

[Secrets] Remove `RawResponse`

---

sdk/keyvault/azcertificates/CHANGELOG.md
sdk/keyvault/azcertificates/README.md
sdk/keyvault/azcertificates/client.go
sdk/keyvault/azcertificates/example_test.go
sdk/keyvault/azcertificates/go.mod
sdk/keyvault/azcertificates/go.sum

Remove `RawResponse` and add documentation

[Certificates] Remove `RawResponse`

---

sdk/resourcemanager/compute/armcompute/CHANGELOG.md
sdk/resourcemanager/compute/armcompute/autorest.md
sdk/resourcemanager/compute/armcompute/ze_generated_example_diskaccesses_client_test.go
sdk/resourcemanager/compute/armcompute/ze_generated_example_diskencryptionsets_client_test.go
sdk/resourcemanager/compute/armcompute/ze_generated_example_diskrestorepoint_client_test.go
sdk/resourcemanager/compute/armcompute/ze_generated_example_disks_client_test.go
sdk/resourcemanager/compute/armcompute/ze_generated_example_snapshots_client_test.go
sdk/resourcemanager/compute/armcompute/zz_generated_constants.go
sdk/resourcemanager/compute/armcompute/zz_generated_diskaccesses_client.go
sdk/resourcemanager/compute/armcompute/zz_generated_diskencryptionsets_client.go
sdk/resourcemanager/compute/armcompute/zz_generated_diskrestorepoint_client.go
sdk/resourcemanager/compute/armcompute/zz_generated_disks_client.go
sdk/resourcemanager/compute/armcompute/zz_generated_models.go
sdk/resourcemanager/compute/armcompute/zz_generated_snapshots_client.go

Fixed https://github.com/Azure/sdk-release-request/issues/2494

[Release] sdk/resourcemanager/compute/armcompute/0.5.0

---

sdk/messaging/azservicebus/client.go
sdk/messaging/azservicebus/internal/amqpLinks.go
sdk/messaging/azservicebus/internal/amqpLinks_test.go
sdk/messaging/azservicebus/internal/errors_test.go
sdk/messaging/azservicebus/internal/stress/tests/idle_fast_reconnect.go
sdk/messaging/azservicebus/internal/test/test_helpers.go
sdk/messaging/azservicebus/internal/utils/retrier.go
sdk/messaging/azservicebus/internal/utils/retrier_test.go

Making some test changes based on customer bugs and diagnosing issues.
- There were a few spots where the logging was spotty (or missing). Added and made a bit more consistent.
- Adding a Receiver test for our "quick reattach" change
- Add a test that shows that the session ID mismatch will result in a connection reset (only way to properly reset all state)

[azservicebus] Test and logging improvements

---

sdk/azidentity/README.md

Removing an outdated link and feature, fixing a code snippet typo

Update azidentity readme

---

eng/pipelines/templates/jobs/archetype-go-release.yml
eng/pipelines/templates/jobs/archetype-sdk-client.yml
sdk/resourcemanager/internal/CHANGELOG.md

Release resourcemanager internal

---

eng/pipelines/templates/jobs/archetype-go-release.yml
eng/pipelines/templates/jobs/archetype-sdk-client.yml

fix: pipeline quote bug

---

eng/pipelines/templates/jobs/archetype-go-release.yml

fix: pipeline bracket bug

---

services/preview/appinsights/mgmt/2022-01-11-preview/insights/_meta.json

fix core version in one package which is causing sdk automation issues

---

sdk/appconfig/azappconfig/setting_selector.go

[appconfig] Update documentation

---

sdk/storage/azblob/highlevel.go
sdk/storage/azblob/zt_client_provided_key_test.go
sdk/storage/azblob/zt_highlevel_test.go

Fixing Metadata and other properties setting in UploadStreamToBlockBlob

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

I missed passing `TestRunTime` into the `build-test.yml` script step.

[Eng] passing the runtime down through all stages

---

sdk/data/azcosmos/composite_index_order.go
sdk/data/azcosmos/conflict_resolution_mode.go
sdk/data/azcosmos/consistency_level.go
sdk/data/azcosmos/cosmos_client.go
sdk/data/azcosmos/cosmos_container.go
sdk/data/azcosmos/cosmos_container_properties.go
sdk/data/azcosmos/cosmos_database.go
sdk/data/azcosmos/cosmos_database_properties.go
sdk/data/azcosmos/data_type.go
sdk/data/azcosmos/indexing_directive.go
sdk/data/azcosmos/indexing_mode.go
sdk/data/azcosmos/indexing_policy.go
sdk/data/azcosmos/spatial_type.go
sdk/data/azcosmos/throughput_properties.go

We added a new tool for checking documentation on public methods, this PR makes that step in CI pass.

[Cosmos] fixing doc tool for cosmos

---

sdk/data/aztables/README.md
sdk/data/aztables/client.go
sdk/data/aztables/entity.go
sdk/data/aztables/example_test.go
sdk/data/aztables/service_client.go

* Adds a section to the README about writing query filters

[Tables] Adding filter section to readme

---

sdk/resourcemanager/apimanagement/armapimanagement/README.md
sdk/resourcemanager/appservice/armappservice/README.md
sdk/resourcemanager/authorization/armauthorization/README.md
sdk/resourcemanager/compute/armcompute/README.md
sdk/resourcemanager/containerregistry/armcontainerregistry/README.md
sdk/resourcemanager/containerservice/armcontainerservice/README.md
sdk/resourcemanager/cosmos/armcosmos/README.md
sdk/resourcemanager/eventgrid/armeventgrid/README.md
sdk/resourcemanager/eventhub/armeventhub/README.md
sdk/resourcemanager/keyvault/armkeyvault/README.md
sdk/resourcemanager/monitor/armmonitor/README.md
sdk/resourcemanager/network/armnetwork/README.md
sdk/resourcemanager/operationalinsights/armoperationalinsights/README.md
sdk/resourcemanager/postgresql/armpostgresql/README.md
sdk/resourcemanager/privatedns/armprivatedns/README.md
sdk/resourcemanager/redis/armredis/README.md
sdk/resourcemanager/resources/armresources/README.md
sdk/resourcemanager/servicebus/armservicebus/README.md
sdk/resourcemanager/sql/armsql/README.md
sdk/resourcemanager/storage/armstorage/README.md

Update sdk/resourcemanager/... service README.md samples path

---

.github/fabricbot.json

The focus of these changes is to add the rule for reacting when the `CXP Attention` rule is applied.

[Fabric Bot] Add CXP Responder

---

sdk/azcore/go.mod
sdk/azcore/testdata/perf/client_get.go
sdk/azcore/testdata/perf/go.mod
sdk/azcore/testdata/perf/go.sum
sdk/azcore/testdata/perf/main.go

Currently blocked by #17231
Closes #17213

[Perf] adding a performance test for runtime.Pipeline

---

sdk/resourcemanager/mobilenetwork/armmobilenetwork/CHANGELOG.md
sdk/resourcemanager/mobilenetwork/armmobilenetwork/autorest.md
sdk/resourcemanager/mobilenetwork/armmobilenetwork/go.mod
sdk/resourcemanager/mobilenetwork/armmobilenetwork/go.sum
sdk/resourcemanager/mobilenetwork/armmobilenetwork/ze_generated_example_attacheddatanetworks_client_test.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/ze_generated_example_datanetworks_client_test.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/ze_generated_example_mobilenetworks_client_test.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/ze_generated_example_operations_client_test.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/ze_generated_example_packetcorecontrolplanes_client_test.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/ze_generated_example_packetcoredataplanes_client_test.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/ze_generated_example_services_client_test.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/ze_generated_example_simpolicies_client_test.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/ze_generated_example_sims_client_test.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/ze_generated_example_sites_client_test.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/ze_generated_example_slices_client_test.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_attacheddatanetworks_client.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_constants.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_datanetworks_client.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_mobilenetworks_client.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_models.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_operations_client.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_packetcorecontrolplanes_client.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_packetcoredataplanes_client.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_services_client.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_simpolicies_client.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_sims_client.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_sites_client.go
sdk/resourcemanager/mobilenetwork/armmobilenetwork/zz_generated_slices_client.go

Fixes https://github.com/Azure/sdk-release-request/issues/2602

[Release] sdk/resourcemanager/mobilenetwork/armmobilenetwork/0.2.0

---

sdk/azcore/log/log.go

Add blurb about the APIs not being goroutine safe.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/17369

Update log API doc comments

---

sdk/azcore/CHANGELOG.md

Remove empty changelog section

---

sdk/azcore/testdata/perf/go.mod
sdk/azcore/testdata/perf/go.sum

Removing replace directives in testdata/perf

[Core] unblock core release

---

sdk/keyvault/internal/CHANGELOG.md
sdk/keyvault/internal/challenge_policy.go
sdk/keyvault/internal/challenge_policy_test.go
sdk/keyvault/internal/constants.go
sdk/keyvault/internal/doc.go
sdk/keyvault/internal/expiring_resource.go
sdk/keyvault/internal/expiring_resource_test.go
sdk/keyvault/internal/go.mod
sdk/keyvault/internal/go.sum
sdk/keyvault/internal/parse.go
sdk/keyvault/internal/parse_test.go

This will need a release after the azcore release

[KeyVault] Updating internal to go1.18

---

sdk/data/aztables/testdata/perf/go.mod
sdk/data/aztables/testdata/perf/go.sum

[Tables] fixing testdata go.mod

---

sdk/messaging/azservicebus/CHANGELOG.md

Updating changelog with date for release.

[azservicebus] Updating version and release date.

---

sdk/storage/azblob/go.mod
sdk/storage/azblob/go.sum
sdk/storage/azblob/zc_storage_error_test.go
sdk/storage/azblob/zt_access_policy_test.go
sdk/storage/azblob/zt_append_blob_client_test.go
sdk/storage/azblob/zt_blob_client_test.go
sdk/storage/azblob/zt_blob_tags_test.go
sdk/storage/azblob/zt_blob_versioning_test.go
sdk/storage/azblob/zt_block_blob_client_test.go
sdk/storage/azblob/zt_bytes_writer_test.go
sdk/storage/azblob/zt_client_provided_key_test.go
sdk/storage/azblob/zt_connection_string_test.go
sdk/storage/azblob/zt_container_client_test.go
sdk/storage/azblob/zt_highlevel_test.go
sdk/storage/azblob/zt_lease_client_test.go
sdk/storage/azblob/zt_list_wrappers_test.go
sdk/storage/azblob/zt_ors_test.go
sdk/storage/azblob/zt_page_blob_client_test.go
sdk/storage/azblob/zt_retry_reader_test.go
sdk/storage/azblob/zt_sas_query_params_test.go
sdk/storage/azblob/zt_section_writer_test.go
sdk/storage/azblob/zt_service_client_test.go
sdk/storage/azblob/zt_shared_access_signature_test.go
sdk/storage/azblob/zt_test.go
sdk/storage/azblob/zt_url_parsing_test.go

Replaced assert with require library.

---

eng/scripts/Invoke-MgmtTestgen.ps1
eng/scripts/MgmtTestLib.ps1
eng/scripts/build.ps1
eng/tools/generator/cmd/template/templateCmd.go
eng/tools/generator/cmd/v2/automation/automationCmd.go
eng/tools/generator/cmd/v2/refresh/refreshCmd.go
eng/tools/generator/cmd/v2/release/releaseCmd.go
eng/tools/generator/doc.go
eng/tools/generator/go.mod
eng/tools/generator/go.sum
eng/tools/generator/template/rpName/packageName/README.md.tpl

Upgrade tooling to the latest generator with go generic support

---

eng/tools/internal/go.mod

feat: mgmt tooling internal upgrade to go 1.18

---

eng/scripts/automation_init.sh
eng/tools/generator/go.mod
eng/tools/generator/go.sum

fix generator and automation go version problem

---

eng/scripts/MgmtTestLib.ps1

Fix mgmt mock test

---

sdk/keyvault/azkeys/README.md

Some of the repo links were under a random branch instead of being under main.

Update keys README - fix formatting and repo links

---

sdk/appconfig/azappconfig/CHANGELOG.md
sdk/appconfig/azappconfig/policy_hmac_auth.go

AppConfig: Fix HMAC auth for Germany West Central

---

sdk/data/aztables/client.go

Detail behavior when deleting a table.

Doc updates for aztables

---

sdk/internal/perf/README.md

[Performance] filling in documentation gaps

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/response_error.go
sdk/azcore/internal/shared/response_error_test.go
sdk/azcore/runtime/request.go

Fixes for handling XML content

---

sdk/resourcemanager/internal/testutil/credential.go
sdk/resourcemanager/internal/testutil/credential_test.go
sdk/resourcemanager/internal/testutil/helper.go
sdk/resourcemanager/internal/testutil/helper_test.go
sdk/resourcemanager/internal/testutil/recording.go
sdk/resourcemanager/internal/testutil/recording_test.go
sdk/resourcemanager/internal/testutil/testsuite_test.go
sdk/resourcemanager/internal/version.go
sdk/resourcemanager/resources/armresources/ze_generated_example_deployments_client_test.go
sdk/resourcemanager/resources/armresources/ze_generated_example_providerresourcetypes_client_test.go
sdk/resourcemanager/resources/armresources/ze_generated_example_providers_client_test.go
sdk/resourcemanager/resources/armresources/ze_generated_example_resourcegroups_client_test.go
sdk/resourcemanager/resources/armresources/ze_generated_example_tags_client_test.go
sdk/resourcemanager/resources/armsubscriptions/zt_tenants_client_live_test.go

fix: update to 1.18 go compile tag

---

sdk/azcore/CHANGELOG.md

Preparing for release of latest fixes

[Core] updating changelog for release

---

sdk/messaging/azservicebus/internal/log.go
sdk/messaging/azservicebus/log.go

Expose log constants via type-aliasing

---

eng/scripts/MgmtTestLib.ps1
eng/scripts/build.ps1

ci: upgrade to latest codegen

---

sdk/internal/perf/recording_test.go

fix flaky test

---

sdk/agfood/armagfood/go.mod
sdk/arm/compute/2020-09-30/armcompute/go.mod
sdk/arm/keyvault/2019-09-01/armkeyvault/go.mod
sdk/arm/keyvault/go.mod
sdk/arm/network/2020-07-01/armnetwork/go.mod
sdk/arm/resources/2020-06-01/armresources/go.mod
sdk/arm/storage/2019-06-01/armstorage/go.mod

build: deprecate previous track2 version

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/chunkwriting.go
sdk/storage/azblob/constants.go
sdk/storage/azblob/doc.go
sdk/storage/azblob/highlevel.go
sdk/storage/azblob/testdata/perf/download_blob.go
sdk/storage/azblob/testdata/perf/list_blobs.go
sdk/storage/azblob/testdata/perf/upload_blob.go
sdk/storage/azblob/transfer_manager.go
sdk/storage/azblob/zm_client_util.go
sdk/storage/azblob/zm_highlevel_util.go
sdk/storage/azblob/zm_service_client_util.go
sdk/storage/azblob/zt_chunkwriting_test.go
sdk/storage/azblob/zt_client_provided_key_test.go
sdk/storage/azblob/zt_examples_test.go
sdk/storage/azblob/zt_highlevel_test.go
sdk/storage/azblob/zt_test.go

Added Changelogs, Examples, and reformatting API

---

azure-pipelines.yml
eng/pipelines/templates/variables/globals.yml

Add go cli native scanning for component governance

---

documentation/MIGRATION_GUIDE.md
documentation/new-version-quickstart.md

doc: update quickstart and migration guide

---

sdk/data/aztables/CHANGELOG.md
sdk/data/aztables/shared_access_signature_test.go

The returned error codes are authentication errors, not table errors.

Fixed error code checks for live tests

---

sdk/messaging/azservicebus/messageSettler_test.go

Fixing a test that actually turned out to be close to correct. Deferred messages aren't _quite_ like normal messages - settlement functions do work but the effects aren't quite the same as with other messages.
Specifically:
- CompleteMessage() removes the message from the 'deferred' area
- AbandonMessage() updates the delivery count. The message remains deferred however.
Fixes #15626

[azservicebus] Updating test for deferred messages that was originally skipped

---

sdk/keyvault/azcertificates/CHANGELOG.md
sdk/keyvault/azcertificates/autorest.md
sdk/keyvault/azcertificates/build.go
sdk/keyvault/azcertificates/client.go
sdk/keyvault/azcertificates/client_test.go
sdk/keyvault/azcertificates/example_test.go
sdk/keyvault/azcertificates/internal/generated/constants.go
sdk/keyvault/azcertificates/internal/generated/keyvault_client.go

Removed duplicated pager creation code.

Renamed pager APIs per new guidelines

---

sdk/keyvault/azcertificates/README.md

clean up docs

---

eng/tools/generator/cmd/v2/common/changlogProcessor.go

fix: current api-version fetch

---

sdk/keyvault/internal/CHANGELOG.md

prepare for release

---

eng/scripts/MgmtTestLib.ps1
eng/scripts/automation/Invoke-MockTest.ps1

fix: wrong test output name

---

eng/tools/generator/cmd/v2/common/fileProcessor.go

fix: readme generation bug

---

eng/tools/generator/cmd/v2/common/changlogProcessor.go
eng/tools/generator/repo/workTree.go

fix: tag fetch problem for release_v2

---

sdk/azcore/internal/pollers/armloc/loc.go
sdk/azcore/internal/pollers/async/async.go
sdk/azcore/internal/pollers/body/body.go
sdk/azcore/internal/pollers/op/op.go
sdk/azcore/internal/pollers/op/op_test.go
sdk/azcore/internal/pollers/util.go

Use case-insensitive comparison for success case

---

sdk/azidentity/logging.go

Fixed logging bug on successful token acquisition

---

services/cognitiveservices/v3.3/customvision/training/client.go

Fixes https://github.com/Azure/azure-sdk-for-python/issues/24164

{azure-sdk-for-go} | Updating default and accepted values

---

sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_credential_test.go

Warn on unsupported managed identity configuration

---

sdk/azcore/cloud/doc.go

Making sure the code compiles and the content renders.

Fix azcore/cloud/doc.go

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_request_id.go
sdk/azcore/runtime/policy_request_id_test.go

Fix casing for request ID policy

---

sdk/synapse/azartifacts/go.mod
sdk/synapse/azartifacts/version.go

Deprecate azartifacts

---

sdk/azcore/doc.go

Add docs for pagers and pollers

---

sdk/keyvault/azkeys/client_test.go
sdk/keyvault/azkeys/testdata/recordings/TestCreateKeyRSATags.json
sdk/keyvault/azkeys/testdata/recordings/TestGetDeletedKey/TestGetDeletedKey_HSM.json
sdk/keyvault/azkeys/testdata/recordings/TestGetDeletedKey/TestGetDeletedKey_NON-HSM.json
sdk/keyvault/azkeys/testdata/recordings/TestGetKeyRotationPolicy/TestGetKeyRotationPolicy_HSM.json
sdk/keyvault/azkeys/testdata/recordings/TestGetKeyRotationPolicy/TestGetKeyRotationPolicy_NON-HSM.json
sdk/keyvault/azkeys/testdata/recordings/TestReleaseKey/TestReleaseKey_HSM.json
sdk/keyvault/azkeys/testdata/recordings/TestReleaseKey/TestReleaseKey_NON-HSM.json
sdk/keyvault/azkeys/testdata/recordings/TestRotateKey/TestRotateKey_HSM.json
sdk/keyvault/azkeys/testdata/recordings/TestRotateKey/TestRotateKey_NON-HSM.json
sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyPropertiesImmutable/TestUpdateKeyPropertiesImmutable_NON-HSM.json
sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyRotationPolicy/TestUpdateKeyRotationPolicy_NON-HSM.json
sdk/keyvault/azkeys/utils_test.go

Fixing some test setup issues and unskipping and re-recording rotation policy and secure key release tests.

Update skipped azkeys tests

---

sdk/resourcemanager/videoanalyzer/armvideoanalyzer/CHANGELOG.md
sdk/resourcemanager/videoanalyzer/armvideoanalyzer/autorest.md
sdk/resourcemanager/videoanalyzer/armvideoanalyzer/go.mod
sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_constants.go

Deprecate sdk/resourcemanger/videoanalyzer/armvideoanalyzer

---

services/preview/videoanalyzer/mgmt/2021-05-01-preview/videoanalyzer/version.go
services/preview/videoanalyzer/mgmt/2021-11-01-preview/videoanalyzer/version.go

Deprecated services/preview/videoanalyzer

---

sdk/internal/CHANGELOG.md
sdk/internal/version.go

prep for release

---

sdk/data/aztables/README.md

Update README with pager changes

---

sdk/data/azcosmos/CHANGELOG.md

Updates next version release to 5/10

Update Cosmos release date for next version

---

sdk/appconfig/azappconfig/CHANGELOG.md

Release work item: https://dev.azure.com/azure-sdk/Release/_workitems/edit/11793/

Update changelog for AppConfig release

---

sdk/keyvault/azkeys/client_test.go

It appears there may be an initialization race around the fake attestation service we use for SKR, causing this test to fail in the first job that runs it but not in the others, which typically start 2-5 minutes later. Hopefully a short retry loop will get the first job passing while I investigate the race.

Add retries to flaky azkeys test

---

sdk/internal/CHANGELOG.md

prep internal for release

---

sdk/azcore/CHANGELOG.md
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/internal/shared/constants.go

update net module to latest version

prep azcore for release

---

sdk/messaging/azservicebus/go.mod
sdk/messaging/azservicebus/go.sum

There is an azcore update and we're going to release a new preview of the azservicebus package.

[azservicebus] Update ref to `messaging/internal`

---

profiles/preview/preview/videoanalyzer/mgmt/videoanalyzer/models.go
sdk/resourcemanager/videoanalyzer/armvideoanalyzer/CHANGELOG.md
sdk/resourcemanager/videoanalyzer/armvideoanalyzer/autorest.md
sdk/resourcemanager/videoanalyzer/armvideoanalyzer/go.mod
sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_constants.go
services/preview/videoanalyzer/mgmt/2021-05-01-preview/videoanalyzer/version.go
services/preview/videoanalyzer/mgmt/2021-11-01-preview/videoanalyzer/version.go

Deprecated videoanalyzer and retract v0.4.1

---

eng/scripts/MgmtTestLib.ps1
eng/scripts/build.ps1

tool: upgrade codegen and testgen version

---

eng/scripts/MgmtTestLib.ps1
sdk/resourcemanager/internal/CHANGELOG.md

Release resourcemanager internal 1.0.0 and some ci minor fix

---

eng/tools/generator/cmd/v2/common/changlogProcessor.go
eng/tools/generator/cmd/v2/common/generation.go
eng/tools/generator/cmd/v2/refresh/refreshCmd.go

go through all the *.go file to find api version set sentence and judge if there exists preview API version

Mgmt. track2 release tool update

---

sdk/keyvault/azkeys/CHANGELOG.md
sdk/keyvault/azkeys/README.md
sdk/keyvault/azkeys/client.go
sdk/keyvault/azkeys/client_test.go
sdk/keyvault/azkeys/example_test.go
sdk/keyvault/azsecrets/CHANGELOG.md
sdk/keyvault/azsecrets/README.md
sdk/keyvault/azsecrets/client.go
sdk/keyvault/azsecrets/client_test.go
sdk/keyvault/azsecrets/example_test.go

Update azkeys and azsecrets pager constructors

---

sdk/data/azappconfig/CHANGELOG.md
sdk/data/azappconfig/internal/generated/constants.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/17905

Prep new azappconfig for release

---

eng/tools/generator/cmd/v2/common/generation.go

fix: isPreviewRelease varible set problem

---

documentation/new-version-quickstart.md

Per guidelines in https://aka.ms/azsdk/guideline/links

Remove locale in link

---

sdk/resourcemanager/cdn/armcdn/build.go

fix: typo for cdn build.go

---

sdk/messaging/azservicebus/receiver_unit_test.go

Making a unit test more reliable by blocking instead of relying on "hopeful" timing.
Fixes #18174

[azservicebus] Fix panicking receiver unit test

---

eng/tools/generator/cmd/v2/common/changlogProcessor.go
eng/tools/generator/cmd/v2/common/generation.go

fix: remove marsshal and unmarshal modification in changelog

---

sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/CHANGELOG.md
sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/autorest.md
sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/go.mod
sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/ze_generated_example_operations_client_test.go
sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/ze_generated_example_virtualmachineimagetemplates_client_test.go
sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/zz_generated_constants.go
sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/zz_generated_models.go
sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/zz_generated_models_serde.go
sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/zz_generated_operations_client.go
sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/zz_generated_polymorphic_helpers.go
sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/zz_generated_virtualmachineimagetemplates_client.go

fixes: https://github.com/Azure/sdk-release-request/issues/2839

[Release] sdk/resourcemanager/virtualmachineimagebuilder/armvirtualmachineimagebuilder/1.1.0

---

sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/CHANGELOG.md
sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/autorest.md
sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/zz_generated_constants.go
sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/zz_generated_models.go

https://github.com/Azure/sdk-release-request/issues/2869

[Release] sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/0.6.0

---

sdk/resourcemanager/cognitiveservices/armcognitiveservices/CHANGELOG.md
sdk/resourcemanager/cognitiveservices/armcognitiveservices/autorest.md
sdk/resourcemanager/cognitiveservices/armcognitiveservices/go.mod
sdk/resourcemanager/cognitiveservices/armcognitiveservices/go.sum
sdk/resourcemanager/cognitiveservices/armcognitiveservices/zz_generated_constants.go

https://github.com/Azure/sdk-release-request/issues/2901

[Release] sdk/resourcemanager/cognitiveservices/armcognitiveservices/1.1.0

---

eng/scripts/Invoke-DependencyCheck.ps1

Replace with local code if not released yet. Use local git cmd instead of eng commom script because the script will be used in public pipeline.
Resolve #18350

Fix dep check race condition

---

sdk/resourcemanager/digitaltwins/armdigitaltwins/CHANGELOG.md
sdk/resourcemanager/digitaltwins/armdigitaltwins/autorest.md
sdk/resourcemanager/digitaltwins/armdigitaltwins/go.mod
sdk/resourcemanager/digitaltwins/armdigitaltwins/go.sum
sdk/resourcemanager/digitaltwins/armdigitaltwins/ze_generated_example_digitaltwins_client_test.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/ze_generated_example_digitaltwinsendpoint_client_test.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/ze_generated_example_operations_client_test.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/ze_generated_example_privateendpointconnections_client_test.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/ze_generated_example_privatelinkresources_client_test.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/ze_generated_example_timeseriesdatabaseconnections_client_test.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_client.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_constants.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_endpoint_client.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_operations_client.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_privateendpointconnections_client.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_privatelinkresources_client.go
sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_timeseriesdatabaseconnections_client.go

https://github.com/Azure/sdk-release-request/issues/2916

[Release] sdk/resourcemanager/digitaltwins/armdigitaltwins/1.0.0

---

sdk/data/aztables/CHANGELOG.md

Prep aztables for release

---

eng/scripts/MgmtTestLib.ps1
eng/scripts/build.ps1

ci: upgrade codegen version in script

---

eng/tools/generator/cmd/v2/common/changlogProcessor.go
eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go

1. Need to add all package change before stash
2. SDKAutomation need to remove tag set in config

fix: release tool corner case

---

sdk/resourcemanager/internal/CHANGELOG.md
sdk/resourcemanager/internal/go.mod
sdk/resourcemanager/internal/go.sum
sdk/resourcemanager/internal/testutil/helper.go

upgrade `azcore` version and change test `poller` method

---

eng/tools/generator/cmd/v2/common/changlogProcessor.go

fix: null pointer when removing changelog

---

eng/pipelines/templates/jobs/archetype-sdk-eng-client.yml
eng/pipelines/templates/steps/analyze.yml
eng/tools/apidiff/ci.yml
eng/tools/deprecate/ci.yml
eng/tools/generator/ci.yml
eng/tools/indexer/ci.yml
eng/tools/internal/ci.yml
eng/tools/pkgchk/ci.yml
eng/tools/profileBuilder/ci.yml

Skip dumping package properties for eng directories

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_client.go
sdk/data/azcosmos/cosmos_client_test.go
sdk/data/azcosmos/doc.go
sdk/data/azcosmos/example_test.go

Resolved https://github.com/Azure/azure-sdk-for-go/issues/18520

Implement Cosmos db new client with connection string

---

sdk/data/azappconfig/README.md

Added missing comma to the **Get a configuration setting** sample

Added missing comma

---

eng/pipelines/templates/variables/globals.yml

Update to latest golangci-lint version

---

sdk/keyvault/azcertificates/client_test.go

Yesterday's live test run failed, apparently because it took more than 20 seconds to create a cert. This PR raises the time limit for creation to 40 seconds, ensures a better message when a test fails due to exceeding that time limit, and fixes a bug causing unnecessary polling.

Allow more time for certificate creation in tests

---

sdk/azidentity/CHANGELOG.md

Move the entry in CHANGELOG

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/chained_token_credential_test.go
sdk/azidentity/client_certificate_credential_test.go
sdk/azidentity/client_secret_credential_test.go
sdk/azidentity/environment_credential_test.go
sdk/azidentity/errors_test.go
sdk/azidentity/managed_identity_credential_test.go
sdk/azidentity/username_password_credential_test.go

Fix #18690
Adding to the tests to check some of the authentication failed error messages

Testing authentication failed error messages

---

eng/tools/generator/cmd/v2/automation/automationCmd.go

fix: change api view artifact path to relative path

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/doc.go

Reverts Azure/azure-sdk-for-go#18833

Revert "CHANGELOG File for release 0.5.0"

---

documentation/new-version-quickstart.md

Fix broken link

---

sdk/storage/azblob/README.md
sdk/storage/azblob/appendblob/client.go
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/blob/responses.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/client.go
sdk/storage/azblob/doc.go
sdk/storage/azblob/enums.go
sdk/storage/azblob/go.mod
sdk/storage/azblob/go.sum
sdk/storage/azblob/models.go
sdk/storage/azblob/pageblob/client.go
sdk/storage/azblob/responses.go
sdk/storage/azblob/testdata/perf/download_blob.go
sdk/storage/azblob/testdata/perf/go.mod
sdk/storage/azblob/testdata/perf/go.sum
sdk/storage/azblob/zt_access_policy_test.go
sdk/storage/azblob/zt_blob_client_test.go
sdk/storage/azblob/zt_blob_tags_test.go
sdk/storage/azblob/zt_blob_versioning_test.go
sdk/storage/azblob/zt_block_blob_client_test.go
sdk/storage/azblob/zt_client_provided_key_test.go
sdk/storage/azblob/zt_examples_test.go
sdk/storage/azblob/zt_highlevel_test.go
sdk/storage/azblob/zt_test.go

Upload/Download APIs in the tinyblob client

---

documentation/MIGRATION_GUIDE.md
documentation/new-version-guideline.md

Resolve: https://github.com/Azure/azure-sdk-for-go/issues/18780

refine migration guide and guildeline

---

eng/tools/generator/autorest/model/changelog.go
eng/tools/internal/delta/delta.go
eng/tools/internal/delta/delta_test.go
eng/tools/internal/delta/testdata/breaking/new/new.go
eng/tools/internal/exports/exports.go
eng/tools/internal/exports/package.go
eng/tools/internal/exports/package_test.go
eng/tools/internal/report/report.go

add support of type alias to changelog tool

---

sdk/resourcemanager/appservice/armappservice/README.md
sdk/resourcemanager/compute/armcompute/README.md
sdk/resourcemanager/containerservice/armcontainerservice/README.md
sdk/resourcemanager/cosmos/armcosmos/README.md
sdk/resourcemanager/eventgrid/armeventgrid/README.md
sdk/resourcemanager/machinelearning/armmachinelearning/README.md
sdk/resourcemanager/mediaservices/armmediaservices/README.md
sdk/resourcemanager/netapp/armnetapp/README.md
sdk/resourcemanager/storagecache/armstoragecache/README.md

Resolve: https://github.com/Azure/azure-sdk-for-go/issues/18881

Add v2 and above version upgrade method

---

sdk/messaging/azeventhubs/consumer_client.go
sdk/messaging/azeventhubs/consumer_client_test.go
sdk/messaging/azeventhubs/producer_client_test.go

[azeventhubs] Fixing bug where epoch value couldn't be specified

---

sdk/data/aztables/client.go

Correct the docs in the new client api

Correct new client apis

---

sdk/data/aztables/README.md

Just add the required protocol in the aad exemple

Correct example for AAD

---

sdk/internal/CHANGELOG.md

Prepare internal for release

---

eng/scripts/Language-Settings.ps1
eng/tools/generator/cmd/v2/automation/automationCmd.go

Resolve: #18875 
Hold merge to wait for API View service update

consolidate API View package name and enable API View for swagger review

---

sdk/resourcemanager/netapp/armnetapp/build.go

As 2.0.0 already applied this flag, then add to config permanently.

add -alwaysSetBodyParamRequired flag for netapp

---

.github/fabricbot.json

Add survey link to every issue and try to gather user feedback in a more active way.

Add survey comment to new issues.

---

eng/scripts/run_tests.ps1

Generate test report on test failures

---

sdk/resourcemanager/internal/CHANGELOG.md
sdk/resourcemanager/internal/testutil/recording.go
sdk/resourcemanager/internal/testutil/recording_test.go

fix seed num not stable for playback

---

.github/fabricbot.json

Add the survey link only to issues coming from outside the organization.

Adjust survey link on issues

---

sdk/storage/azblob/blob/models.go
sdk/storage/azblob/constants.go
sdk/storage/azblob/zt_examples_test.go

Azblob Tinyblob Examples

---

sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/constants.go
sdk/storage/azblob/container/client.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/container/constants.go
sdk/storage/azblob/container/examples_test.go
sdk/storage/azblob/container/models.go
sdk/storage/azblob/examples_test.go
sdk/storage/azblob/models.go
sdk/storage/azblob/service/client_test.go
sdk/storage/azblob/service/examples_test.go
sdk/storage/azblob/service/models.go

Use a struct of bools instead of a slice of options.

Simplify blob list options

---

eng/scripts/MgmtTestLib.ps1
eng/scripts/build.ps1
eng/tools/generator/template/rpName/packageName/build.go.tpl

Flag and opt in code gen new feature for mgmt. plane release

---

eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go

fix sdk automation with multi namespace config

---

eng/tools/generator/cmd/v2/common/generation.go

fix relative path problem

---

sdk/storage/azblob/bloberror/error_codes.go

Add helper for determining the blob error code

---

sdk/storage/azblob/README.md
sdk/storage/azblob/examples_test.go
sdk/storage/azblob/internal/generated/autorest.md

Used the same template as other languages.
Simplified examples and provided links to end-to-end examples. Added initial doc blurb on specialized clients.

Clean up README

---

sdk/storage/azblob/blockblob/client.go

Fail-fast if the block size exceeds the limit, preventing an upload that is guaranteed to fail and leaves lingering unstaged blocks.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/18975

Fix incorrect block size due to integer division

---

sdk/keyvault/azkeys/client_test.go

Key Vault recently changed to include a default action in key rotation policies, causing this test to break because it expects the policy retrieved from `GetKeyRotationPolicy` to have exactly one lifetime action. I relaxed the matching here because whether a default action exists is irrelevant to the test, which needs only to verify the presence of the action it added.

Relax key rotation policy matching in tests

---

sdk/keyvault/azcertificates/CHANGELOG.md
sdk/keyvault/azcertificates/client_test.go
sdk/keyvault/azcertificates/custom_client.go
sdk/keyvault/azcertificates/go.mod
sdk/keyvault/azcertificates/go.sum
sdk/keyvault/azkeys/CHANGELOG.md
sdk/keyvault/azkeys/client_test.go
sdk/keyvault/azkeys/custom_client.go
sdk/keyvault/azkeys/go.mod
sdk/keyvault/azkeys/go.sum
sdk/keyvault/azsecrets/CHANGELOG.md
sdk/keyvault/azsecrets/client_test.go
sdk/keyvault/azsecrets/custom_client.go
sdk/keyvault/azsecrets/go.mod
sdk/keyvault/azsecrets/go.sum

Draft pending `keyvault/internal` release

Add option to disable Key Vault challenge verification

---

sdk/data/azappconfig/CHANGELOG.md

Release updates for 0.4.1

---

sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/zz_constants.go

Fixing https://github.com/Azure/azure-sdk-for-go/issues/18767

Fixing StorageError typo

---

sdk/messaging/azservicebus/CHANGELOG.md

There are some bug fixes going out. No huge changes.

[azservicebus] Updating changelog for release next week

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/request.go
sdk/azcore/runtime/request_test.go

Slices of io.ReadSeekCloser was improperly handled.

Fixed bug in runtime.SetMultipartFormData

---

sdk/storage/azblob/CHANGELOG.md

Prepare for next release

---

sdk/data/azcosmos/cosmos_location_cache.go
sdk/data/azcosmos/cosmos_location_cache_test.go

Adds the LocationCache, an internally used feature to manage location availability.
closes #18982

Cosmos: Add Location Cache

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/consumer_client.go
sdk/messaging/azeventhubs/example_processor_test.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/processor_stress_tester.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/shared.go
sdk/messaging/azeventhubs/internal/errors.go
sdk/messaging/azeventhubs/internal/errors_test.go
sdk/messaging/azeventhubs/internal/exported/error.go
sdk/messaging/azeventhubs/internal/exported/websocket_conn_params.go
sdk/messaging/azeventhubs/internal/namespace.go
sdk/messaging/azeventhubs/internal/utils/retrier.go
sdk/messaging/azeventhubs/internal/utils/retrier_test.go
sdk/messaging/azeventhubs/partition_client.go
sdk/messaging/azeventhubs/processor_test.go
sdk/messaging/azeventhubs/producer_client.go

* Making the last few name changes that came out of arch board reviews + discussions with Jeff
* Fixing bug where you couldn't cancel the timeout associated with retries.
Fixes #19217

[azeventhubs] Last of the renames (for now!)

---

sdk/monitor/azquery/CHANGELOG.md
sdk/monitor/azquery/version.go

update version number and changelog

[azquery] prep for release

---

sdk/storage/azblob/service/client_test.go

From the last CI run for release.
```
2022-10-11T14:04:21.3397615Z === RUN   Test/TestContainerRestore
2022-10-11T14:04:21.3398354Z     client_test.go:711: 
2022-10-11T14:04:21.3399099Z         	Error Trace:	client_test.go:711
2022-10-11T14:04:21.3400185Z         	Error:      	Expected nil, but got: &exported.ResponseError{ErrorCode:"ConcurrentContainerOperationInProgress", StatusCode:409, RawResponse:(*http.Response)(0xc0002514d0)}
2022-10-11T14:04:21.3401308Z         	Test:       	Test/TestContainerRestore
```

Fix race condition in test

---

eng/tools/generator/cmd/template/templateCmd.go
eng/tools/generator/cmd/v2/automation/automationCmd.go
eng/tools/generator/cmd/v2/refresh/refreshCmd.go
eng/tools/generator/cmd/v2/release/releaseCmd.go
sdk/resourcemanager/devhub/armdevhub/CHANGELOG.md
sdk/resourcemanager/devhub/armdevhub/autorest.md
sdk/resourcemanager/devhub/armdevhub/constants.go
sdk/resourcemanager/devhub/armdevhub/go.mod
sdk/resourcemanager/hybridcontainerservice/armhybridcontainerservice/CHANGELOG.md
sdk/resourcemanager/hybridcontainerservice/armhybridcontainerservice/autorest.md
sdk/resourcemanager/hybridcontainerservice/armhybridcontainerservice/constants.go
sdk/resourcemanager/hybridcontainerservice/armhybridcontainerservice/go.mod
sdk/resourcemanager/nginx/armnginx/CHANGELOG.md
sdk/resourcemanager/nginx/armnginx/autorest.md
sdk/resourcemanager/nginx/armnginx/constants.go
sdk/resourcemanager/nginx/armnginx/go.mod

Fix wrong default Go version in mgmt. SDK release tool. Also, fix for some released modules.

fix wrong default Go version for mgmt. module release

---

sdk/resourcemanager/devhub/armdevhub/CHANGELOG.md
sdk/resourcemanager/devhub/armdevhub/autorest.md
sdk/resourcemanager/devhub/armdevhub/constants.go
sdk/resourcemanager/devhub/armdevhub/developerhubservice_client.go
sdk/resourcemanager/devhub/armdevhub/developerhubservice_client_example_test.go
sdk/resourcemanager/devhub/armdevhub/models.go
sdk/resourcemanager/devhub/armdevhub/workflow_client.go
sdk/resourcemanager/devhub/armdevhub/workflow_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/3198

[Release] sdk/resourcemanager/devhub/armdevhub/0.2.0

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_retry.go

Set default MaxRetryDelay to 60s

---

sdk/monitor/azquery/README.md
sdk/monitor/azquery/TROUBLESHOOTING.md

Troubleshooting guide to address potential errors for users.

[azquery] troubleshooting guide

---

CHANGELOG.md
services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/client.go
version/version.go

Release v67.0.1

---

eng/config.json

bump code coverage floor for azcore

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/client.go

Add service client accessor to azblob.Client

---

sdk/data/azappconfig/CHANGELOG.md

Prepare azappconfig for release

---

sdk/azcore/runtime/pipeline.go
sdk/azcore/runtime/policy_api_version.go
sdk/azcore/runtime/policy_api_version_test.go

Unexport APIVersionPolicy and constructor

---

sdk/azcore/arm/arm.go
sdk/azcore/cloud/cloud.go

This reverts commit 4042dff3fb02b1c3255592c6121652612df89b99.

Revert "move cloud content to inline initialization"

---

eng/tools/generator/cmd/issue/issueCmd.go
eng/tools/generator/cmd/issue/request/handlers.go
eng/tools/generator/cmd/issue/request/request.go
eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go
eng/tools/generator/cmd/v2/release/releaseCmd.go
eng/tools/generator/config/validate/validator.go

use the actual release date in the changelog

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/pipeline_test.go
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/runtime/pipeline_test.go

Updated internal to latest version.

Added concurrency test cases to pipelines

---

.github/CODEOWNERS

Update storage codeowners

---

sdk/data/azcosmos/ci.yml
sdk/data/azcosmos/emulator_cosmos_item_test.go
sdk/data/azcosmos/emulator_tests.go

* Modify the Emulator CI to include the Compute GW endpoint
* And Compute GW endpoint validation tests for ids

Adding Cosmos Compute GW tests for id validation

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/container/client.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/container/models.go
sdk/storage/azblob/testdata/recordings/Test/TestSetAccessPolicyWithNullId.json

Corrected formatting of start and expiry time. Fixes #18712 

Set Access Policy

---

sdk/messaging/azservicebus/CHANGELOG.md

Updating with the fix from #19571

[azservicebus] Updating changelog with fix.

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/blockblob/models.go
sdk/storage/azblob/client_test.go
sdk/storage/azblob/internal/shared/transfer_manager.go
sdk/storage/azblob/internal/testcommon/common.go

Jumbo blob tests

---

eng/pipelines/templates/steps/build-test.yml

Dump stacks for all goroutines on fatal panic

---

eng/tools/generator/autorest/model/changelog.go
eng/tools/generator/autorest/model/changelog_test.go

Resolve: https://github.com/Azure/azure-sdk-for-go/issues/19539

changelog sort

---

sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/build.go

Added build.go to simplify regeneration.

Fix invalid regex

---

sdk/storage/azblob/appendblob/client.go
sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/appendblob/examples_test.go
sdk/storage/azblob/appendblob/models.go
sdk/storage/azblob/appendblob/responses.go
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blob/constants.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/blob/responses.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/blockblob/examples_test.go
sdk/storage/azblob/blockblob/models.go
sdk/storage/azblob/blockblob/responses.go
sdk/storage/azblob/internal/exported/set_expiry.go

Remove set expiry from blob client

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/internal/exported/version.go

CHANGELOG.md for 0.6.0

---

documentation/developer_setup.md

Provides example on how to set up a skeleton module. Removed redundant/stale content, linking to the design guidelines.

Update developer on-boarding docs

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blockblob/mmf_unix.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/19684

Fix build break on Darwin OS

---

CHANGELOG.md
services/preview/workloadmonitor/mgmt/2018-08-31-preview/workloadmonitor/client.go
services/preview/workloadmonitor/mgmt/2020-01-13-preview/workloadmonitor/client.go
version/version.go

deprecated services/preview/workloadmonitor/mgmt

---

eng/codegen_to_sdk_config.json

remove mocktest from sdk generation pipeline

---

sdk/azidentity/default_azure_credential_test.go

Add DefaultAzureCredential constructor error message test

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azservicebus/CHANGELOG.md

Updating changelogs for release next week

---

sdk/azidentity/interactive_browser_credential.go

Removing an outdated link; this option works now.

Update RedirectURL documentation

---

eng/scripts/MgmtTestLib.ps1
eng/scripts/build.ps1

upgrade generator version for CI

---

eng/scripts/MgmtTestLib.ps1
sdk/resourcemanager/cosmos/armcosmos/testdata/recordings/TestCassandraresourcesTestSuite.json
sdk/resourcemanager/cosmos/armcosmos/testdata/recordings/TestDatabaseaccountsTestSuite.json
sdk/resourcemanager/cosmos/armcosmos/testdata/recordings/TestGremlinresourcesTestSuite.json
sdk/resourcemanager/cosmos/armcosmos/testdata/recordings/TestMongodbresourcesTestSuite.json
sdk/resourcemanager/cosmos/armcosmos/testdata/recordings/TestPrivateendpointconnectionsTestSuite.json
sdk/resourcemanager/cosmos/armcosmos/testdata/recordings/TestServiceTestSuite.json
sdk/resourcemanager/cosmos/armcosmos/testdata/recordings/TestSqlresourcesTestSuite.json
sdk/resourcemanager/cosmos/armcosmos/testdata/recordings/TestTableresourcesTestSuite.json

fix test failure in CI of mgmt. packages

---

sdk/storage/azqueue/ci.yml

Enable CI for azqueue

---

sdk/storage/azqueue/CHANGELOG.md
sdk/storage/azqueue/internal/generated/autorest.md
sdk/storage/azqueue/internal/generated/build.go
sdk/storage/azqueue/internal/generated/zz_constants.go
sdk/storage/azqueue/internal/generated/zz_messageid_client.go
sdk/storage/azqueue/internal/generated/zz_messages_client.go
sdk/storage/azqueue/internal/generated/zz_models.go
sdk/storage/azqueue/internal/generated/zz_models_serde.go
sdk/storage/azqueue/internal/generated/zz_queue_client.go
sdk/storage/azqueue/internal/generated/zz_response_types.go
sdk/storage/azqueue/internal/generated/zz_service_client.go
sdk/storage/azqueue/internal/generated/zz_time_rfc1123.go
sdk/storage/azqueue/internal/generated/zz_time_rfc3339.go
sdk/storage/azqueue/internal/generated/zz_xml_helper.go

Add build.go and format generated code.

Update to latest code generator for azqueue

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/responses.go
sdk/storage/azblob/container/models.go
sdk/storage/azblob/container/responses.go
sdk/storage/azblob/service/models.go
sdk/storage/azblob/service/responses.go

Export missing types

---

sdk/storage/azblob/common.go
sdk/storage/azblob/sas/account.go
sdk/storage/azblob/sas/account_test.go
sdk/storage/azblob/sas/query_params_test.go
sdk/storage/azblob/sas/service.go
sdk/storage/azblob/sas/service_test.go
sdk/storage/azblob/sas/url_parts_test.go

Added SAS missing permissions tests and fixed parsing logic

---

sdk/keyvault/internal/challenge_policy.go
sdk/keyvault/internal/challenge_policy_test.go
sdk/keyvault/internal/go.mod
sdk/keyvault/internal/go.sum

This refactors Key Vault's auth policy to use the extension API added in azcore v1.3.0.

Refactor KeyVaultChallengePolicy

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity.go
sdk/azidentity/azidentity_test.go
sdk/azidentity/go.mod
sdk/azidentity/go.sum
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/interactive_browser_credential_test.go

Add LoginHint option for InteractiveBrowserCredential

---

sdk/keyvault/internal/CHANGELOG.md

Whoops, this should have been in #19447

Update keyvault/internal changelog

---

eng/tools/generator/cmd/v2/common/changelogProcessor.go
eng/tools/generator/cmd/v2/common/changelogProcessor_test.go
eng/tools/generator/cmd/v2/common/generation.go
eng/tools/generator/cmd/v2/common/testdata/new/interfacetoany/interfacetoanyfilter.go
eng/tools/generator/cmd/v2/common/testdata/old/interfacetoany/interfacetoanyfilter.go

resolve: https://github.com/Azure/azure-sdk-for-go/issues/19830

remove item of interface{} to any

---

eng/scripts/Invoke-MgmtTestgen.ps1
eng/scripts/MgmtTestLib.ps1
sdk/resourcemanager/dashboard/armdashboard/build.go
sdk/resourcemanager/security/armsecurity/build.go
sdk/resourcemanager/storagecache/armstoragecache/build.go
sdk/resourcemanager/workloads/armworkloads/build.go

test generation should align with code generation flag

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/policy/policy.go
sdk/azcore/arm/runtime/pipeline.go
sdk/azcore/arm/runtime/policy_bearer_token.go
sdk/azcore/arm/runtime/policy_bearer_token_test.go
sdk/azcore/internal/exported/exported.go
sdk/azcore/internal/shared/constants.go

Copying #19309 to the azcore beta branch

Support ARM cross-tenant authentication

---

sdk/azcore/CHANGELOG.md
sdk/azcore/go.mod
sdk/azcore/go.sum

Update azcore dependencies

---

sdk/containers/azcontainerregistry/README.md

restore all url with pkg.go.dev as the package has already been indexed

restore all url with pkg.go.dev for ACR readme

---

sdk/azidentity/device_code_credential_test.go
sdk/azidentity/interactive_browser_credential_test.go
sdk/azidentity/live_test.go
sdk/azidentity/testdata/recordings/TestDeviceCodeCredential_Live/optional_tenant.json

The default tenant is "organizations", and MSAL may add special handling for it in the future.

Test DeviceCodeCredential with default tenant

---

sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/container/models.go
sdk/storage/azblob/sas/account.go
sdk/storage/azblob/service/client_test.go
sdk/storage/azblob/service/models.go

1. Added nil check in `GetSASURLOptions.format()` method.
2. Fixed Account SAS creation.

Adding nil check for GetSASURLOptions.format()

---

sdk/storage/azblob/CHANGELOG.md

Changelog updates for azblob GA release

Updating CHANGELOG.md

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/internal/constants.go

We made some additions to the API and also upgraded to the new azblobs package.

[azeventhubs] Upgrade to a new minor rev for Event Hubs

---

eng/tools/generator/autorest/model/changelog.go

runtime error: invalid memory address or nil pointer dereference

func typeToAny bug fix

---

sdk/internal/CHANGELOG.md

add changelog for https://github.com/Azure/azure-sdk-for-go/pull/20009

add changelog for https://github.com/Azure/azure-sdk-for-go/pull/20009

---

sdk/internal/CHANGELOG.md
sdk/internal/version.go

Prepare sdk/internal for release

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/pipeline.go
sdk/azcore/arm/runtime/policy_trace_namespace.go
sdk/azcore/arm/runtime/policy_trace_namespace_test.go
sdk/azcore/core.go
sdk/azcore/core_test.go
sdk/azcore/internal/exported/request.go
sdk/azcore/internal/exported/request_test.go
sdk/azcore/internal/shared/constants.go
sdk/azcore/internal/shared/shared.go
sdk/azcore/policy/policy.go
sdk/azcore/runtime/pager.go
sdk/azcore/runtime/pipeline.go
sdk/azcore/runtime/policy_http_trace.go
sdk/azcore/runtime/policy_http_trace_test.go
sdk/azcore/runtime/poller.go
sdk/azcore/runtime/poller_test.go
sdk/azcore/tracing/tracing.go
sdk/azcore/tracing/tracing_test.go

This includes new internal pipeline policies and other supporting types. See the changelog for a full description.
Added some missing doc comments.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/7358

Add supporting features to enable distributed tracing

---

sdk/resourcemanager/storagemover/armstoragemover/CHANGELOG.md
sdk/resourcemanager/storagemover/armstoragemover/agents_client.go
sdk/resourcemanager/storagemover/armstoragemover/agents_client_example_test.go
sdk/resourcemanager/storagemover/armstoragemover/autorest.md
sdk/resourcemanager/storagemover/armstoragemover/constants.go
sdk/resourcemanager/storagemover/armstoragemover/endpoints_client.go
sdk/resourcemanager/storagemover/armstoragemover/endpoints_client_example_test.go
sdk/resourcemanager/storagemover/armstoragemover/jobdefinitions_client.go
sdk/resourcemanager/storagemover/armstoragemover/jobdefinitions_client_example_test.go
sdk/resourcemanager/storagemover/armstoragemover/jobruns_client.go
sdk/resourcemanager/storagemover/armstoragemover/jobruns_client_example_test.go
sdk/resourcemanager/storagemover/armstoragemover/operations_client.go
sdk/resourcemanager/storagemover/armstoragemover/operations_client_example_test.go
sdk/resourcemanager/storagemover/armstoragemover/projects_client.go
sdk/resourcemanager/storagemover/armstoragemover/projects_client_example_test.go
sdk/resourcemanager/storagemover/armstoragemover/storagemovers_client.go
sdk/resourcemanager/storagemover/armstoragemover/storagemovers_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/3729

[Release] sdk/resourcemanager/storagemover/armstoragemover/1.0.0

---

eng/tools/generator/cmd/v2/common/generation.go
eng/tools/generator/cmd/v2/refresh/refreshCmd.go
eng/tools/generator/cmd/v2/release/releaseCmd.go

Whether to update the commit id in the autorest.md file

genertor tool add --original-commit flag

---

eng/scripts/MgmtTestLib.ps1
eng/scripts/build.ps1

update code generator version

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/client_test.go
sdk/messaging/azservicebus/error.go
sdk/messaging/azservicebus/internal/errors.go
sdk/messaging/azservicebus/internal/errors_test.go
sdk/messaging/azservicebus/internal/exported/error.go
sdk/messaging/azservicebus/internal/namespace.go
sdk/messaging/azservicebus/internal/rpc.go
sdk/messaging/azservicebus/internal/sas/sas.go
sdk/messaging/azservicebus/internal/sbauth/token_provider.go
sdk/messaging/azservicebus/internal/stress/tools/generate_sas.go
sdk/messaging/azservicebus/internal/test/test_helpers.go
sdk/messaging/azservicebus/liveTestHelpers_test.go
sdk/messaging/azservicebus/receiver_test.go
sdk/messaging/azservicebus/test-resources.bicep

Fixing some authentication issues:
- We used to treat authentication errors are retryable, which is incorrect and the comment that I had on there doesn't seem relevant anymore.
- Added in a new code: `CodeUnauthorizedAccess`, so you can distinguish between credential failures
Fixes #19966

Fixing some authentication issues:

---

.github/fabricbot.json

Updating notification for Compute

---

sdk/security/keyvault/TROUBLESHOOTING.md

Part of https://github.com/Azure/azure-sdk-for-go/issues/17906

[keyvault] move troubleshooting guide to security folder

---

sdk/security/keyvault/azcertificates/CHANGELOG.md
sdk/security/keyvault/azcertificates/README.md
sdk/security/keyvault/azcertificates/TROUBLESHOOTING.md
sdk/security/keyvault/azcertificates/assets.json
sdk/security/keyvault/azcertificates/autorest.md
sdk/security/keyvault/azcertificates/client.go
sdk/security/keyvault/azcertificates/client_test.go
sdk/security/keyvault/azcertificates/constants.go
sdk/security/keyvault/azcertificates/custom_client.go
sdk/security/keyvault/azcertificates/models.go
sdk/security/keyvault/azcertificates/models_serde.go
sdk/security/keyvault/azcertificates/response_types.go
sdk/security/keyvault/azcertificates/testdata/perf/go.sum
sdk/security/keyvault/azcertificates/time_unix.go

* update autorest go version to 4.0.0-preview.46
* updated certificate api version to 7.4

[keyvault] update azcertificates to api version 7.4

---

sdk/data/azcosmos/CHANGELOG.md

Setting release date and cleaning changelog

Cosmos DB: 0.3.4 release date

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/blob_client.go
sdk/storage/azblob/internal/generated/zz_appendblob_client.go
sdk/storage/azblob/internal/generated/zz_blob_client.go
sdk/storage/azblob/internal/generated/zz_blockblob_client.go
sdk/storage/azblob/internal/generated/zz_container_client.go
sdk/storage/azblob/internal/generated/zz_pageblob_client.go

Format time to GMT for conditional headers

---

sdk/keyvault/azsecrets/CHANGELOG.md
sdk/keyvault/azsecrets/autorest.md
sdk/keyvault/azsecrets/build.go
sdk/keyvault/azsecrets/client.go
sdk/keyvault/azsecrets/custom_client.go
sdk/keyvault/azsecrets/models.go
sdk/keyvault/azsecrets/models_serde.go
sdk/keyvault/azsecrets/response_types.go
sdk/keyvault/azsecrets/testdata/recordings/TestBackupRestore.json
sdk/keyvault/azsecrets/testdata/recordings/TestCRUD.json
sdk/keyvault/azsecrets/testdata/recordings/TestListDeletedSecrets.json
sdk/keyvault/azsecrets/testdata/recordings/TestListSecretVersions.json
sdk/keyvault/azsecrets/testdata/recordings/TestListSecrets.json
sdk/keyvault/azsecrets/testdata/recordings/TestRecover.json
sdk/keyvault/azsecrets/time_unix.go
sdk/keyvault/azsecrets/utils_test.go

- update autorest go version to 4.0.0-preview.46
- updated certificate api version to 7.4

[keyvault] update azsecrets (old) to api version 7.4

---

sdk/security/keyvault/azsecrets/TROUBLESHOOTING.md
sdk/security/keyvault/azsecrets/assets.json
sdk/security/keyvault/azsecrets/autorest.md
sdk/security/keyvault/azsecrets/client.go
sdk/security/keyvault/azsecrets/custom_client.go
sdk/security/keyvault/azsecrets/models.go
sdk/security/keyvault/azsecrets/models_serde.go
sdk/security/keyvault/azsecrets/response_types.go
sdk/security/keyvault/azsecrets/time_unix.go
sdk/security/keyvault/azsecrets/utils_test.go

- update autorest go version to 4.0.0-preview.46
- updated certificate api version to 7.4

[keyvault] update azsecrets to api version 7.4

---

documentation/MIGRATION_GUIDE.md
documentation/profile-migration-guide.md

add migration guide for profile

---

sdk/resourcemanager/communication/armcommunication/CHANGELOG.md
sdk/resourcemanager/communication/armcommunication/autorest.md
sdk/resourcemanager/communication/armcommunication/constants.go
sdk/resourcemanager/communication/armcommunication/domains_client.go
sdk/resourcemanager/communication/armcommunication/domains_client_example_test.go
sdk/resourcemanager/communication/armcommunication/emailservices_client.go
sdk/resourcemanager/communication/armcommunication/emailservices_client_example_test.go
sdk/resourcemanager/communication/armcommunication/operations_client.go
sdk/resourcemanager/communication/armcommunication/operations_client_example_test.go
sdk/resourcemanager/communication/armcommunication/senderusernames_client.go
sdk/resourcemanager/communication/armcommunication/senderusernames_client_example_test.go
sdk/resourcemanager/communication/armcommunication/services_client.go
sdk/resourcemanager/communication/armcommunication/services_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/3993

[Release] sdk/resourcemanager/communication/armcommunication/2.0.0

---

sdk/azcore/CHANGELOG.md

azcore: prepare for release

---

sdk/azcore/arm/policy/policy.go

Remove arm/ClientOptions.AuxiliaryTenants

---

eng/tools/generator/cmd/v2/common/cmdProcessor.go
eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/fileProcessor_test.go
eng/tools/generator/cmd/v2/common/generation.go
eng/tools/generator/cmd/v2/release/releaseCmd.go

https://github.com/Azure/azure-sdk-for-go/issues/20441

Add label for release PR.

---

sdk/azcore/policy/policy.go

Fixing #20578

---

sdk/keyvault/azcertificates/CHANGELOG.md
sdk/keyvault/azcertificates/autorest.md
sdk/keyvault/azcertificates/custom_client.go
sdk/keyvault/azcertificates/models.go
sdk/keyvault/azcertificates/models_serde.go
sdk/security/keyvault/azadmin/CHANGELOG.md
sdk/security/keyvault/azadmin/backup/autorest.md
sdk/security/keyvault/azadmin/backup/custom_client.go
sdk/security/keyvault/azadmin/backup/models.go
sdk/security/keyvault/azcertificates/CHANGELOG.md
sdk/security/keyvault/azcertificates/autorest.md
sdk/security/keyvault/azcertificates/custom_client.go
sdk/security/keyvault/azcertificates/models.go
sdk/security/keyvault/azcertificates/models_serde.go

Update keyvault libraries with partial errors to use a custom `ErrorInfo` struct.

[keyvault] update partial errors

---

sdk/containers/azcontainerregistry/CHANGELOG.md
sdk/containers/azcontainerregistry/assets.json
sdk/containers/azcontainerregistry/blob_custom_client.go
sdk/containers/azcontainerregistry/blob_custom_client_test.go

add fail over for blob digest calculator

---

eng/tools/generator/autorest/model/changelog.go
eng/tools/generator/autorest/model/changelog_test.go
eng/tools/generator/cmd/v2/common/changelogProcessor_test.go
eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go
eng/tools/generator/cmd/v2/release/releaseCmd.go
eng/tools/generator/config/validate/validator.go

changelog: https://github.com/Azure/azure-sdk-for-go/issues/20441
Configure the tag in autorest.md through the tag provided in the release-request.

`Refine changelog tool to combine similar item` and `Fix auto release set tag`

---

eng/config.json

azfile: Set coverage goal

---

sdk/data/azcosmos/CHANGELOG.md

Cleaning up changelog to prepare next release train

Preparing 0.3.5 release changelog

---

sdk/data/azcosmos/CHANGELOG.md

`Prepare-Release.ps1` updated the Changelog with the release date.

Adding automation date

---

sdk/storage/azfile/ci.yml
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/internal/testcommon/clients_auth.go
sdk/storage/azfile/test-resources.json

azfile: Live pipeline setup

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/README.md
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/doc.go
sdk/storage/azfile/file/client.go
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/file/mmf_windows.go
sdk/storage/azfile/file/models.go
sdk/storage/azfile/go.mod
sdk/storage/azfile/go.sum
sdk/storage/azfile/internal/exported/log_events.go
sdk/storage/azfile/internal/testcommon/clients_auth.go
sdk/storage/azfile/internal/testcommon/common.go
sdk/storage/azfile/lease/models.go
sdk/storage/azfile/log.go
sdk/storage/azfile/share/models.go

Adding readme, doc.go, changelog and log.go

azfile: Adding readme and changelog

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go

Update changelog with latest features

---

eng/tools/generator/cmd/v2/common/fileProcessor.go

Fix parsing specName from json files

generator release-v2 from json

---

sdk/security/keyvault/azadmin/settings/client_test.go

Fix flaky test by adding retry logic.
Sometimes this test faces a "conflict" error due to other tests running, so retrying it's that's the case.

[azadmin] fix flaky test

---

sdk/storage/azqueue/README.md

Edit pass for azqueue readme

---

sdk/storage/azfile/CHANGELOG.md

Updating changelog

---

sdk/storage/azblob/CHANGELOG.md

Changelog update for v1.0.1 release

Updating CHANGELOG.md for v1.0.1 (azblob)

---

sdk/monitor/azquery/CHANGELOG.md
sdk/monitor/azquery/MIGRATION.md

Added migration guide for azquery module.

[azquery] migration guide

---

sdk/messaging/azeventhubs/internal/eh/stress/deploy.ps1
sdk/messaging/azservicebus/internal/stress/deploy.ps1

Relies on https://github.com/Azure/azure-sdk-tools/pull/6103

Remove -Login and -PushImages parameters from stress helper

---

eng/tools/mgmtreport/mgmtreport.tpl

html header: Cache-Control: no-cache

mgmtreport set no-cache

---

sdk/containers/azcontainerregistry/CHANGELOG.md
sdk/containers/azcontainerregistry/blob_custom_client.go
sdk/containers/azcontainerregistry/ci.yml
sdk/containers/azcontainerregistry/cloud_config.go
sdk/containers/azcontainerregistry/custom_client.go
sdk/containers/azcontainerregistry/custom_constants.go

Also remove live test for China cloud as it always has network issue.
Resolve: #20835 

change default audience value for ACR

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go

Prepare for azcore beta release

---

sdk/messaging/azeventhubs/internal/eh/stress/readme.md
sdk/messaging/azservicebus/internal/stress/readme.md

Gives a light introduction to what the structure is, and a link to the documentation.
Fixes #19256

[azeventhubs/azservicebus] Add readmes for the stress projects

---

sdk/storage/azblob/README.md

- [ X] The purpose of this PR is explained in this or a referenced issue.
- [ x] The PR does not update generated files. - Only editorial updates to Readme

[Azblob][Readme] Edit pass

---

sdk/resourcemanager/newrelic/armnewrelicobservability/CHANGELOG.md
sdk/resourcemanager/newrelic/armnewrelicobservability/accounts_client.go
sdk/resourcemanager/newrelic/armnewrelicobservability/accounts_client_example_test.go
sdk/resourcemanager/newrelic/armnewrelicobservability/autorest.md
sdk/resourcemanager/newrelic/armnewrelicobservability/constants.go
sdk/resourcemanager/newrelic/armnewrelicobservability/models.go
sdk/resourcemanager/newrelic/armnewrelicobservability/monitors_client.go
sdk/resourcemanager/newrelic/armnewrelicobservability/monitors_client_example_test.go
sdk/resourcemanager/newrelic/armnewrelicobservability/operations_client.go
sdk/resourcemanager/newrelic/armnewrelicobservability/operations_client_example_test.go
sdk/resourcemanager/newrelic/armnewrelicobservability/organizations_client.go
sdk/resourcemanager/newrelic/armnewrelicobservability/organizations_client_example_test.go
sdk/resourcemanager/newrelic/armnewrelicobservability/plans_client.go
sdk/resourcemanager/newrelic/armnewrelicobservability/plans_client_example_test.go
sdk/resourcemanager/newrelic/armnewrelicobservability/response_types.go
sdk/resourcemanager/newrelic/armnewrelicobservability/tagrules_client.go
sdk/resourcemanager/newrelic/armnewrelicobservability/tagrules_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4051

[Release] sdk/resourcemanager/newrelic/armnewrelicobservability/1.0.0

---

sdk/resourcemanager/frontdoor/armfrontdoor/CHANGELOG.md
sdk/resourcemanager/frontdoor/armfrontdoor/autorest.md
sdk/resourcemanager/frontdoor/armfrontdoor/client_factory.go
sdk/resourcemanager/frontdoor/armfrontdoor/constants.go
sdk/resourcemanager/frontdoor/armfrontdoor/endpoints_client.go
sdk/resourcemanager/frontdoor/armfrontdoor/endpoints_client_example_test.go
sdk/resourcemanager/frontdoor/armfrontdoor/experiments_client_example_test.go
sdk/resourcemanager/frontdoor/armfrontdoor/frontdoors_client.go
sdk/resourcemanager/frontdoor/armfrontdoor/frontdoors_client_example_test.go
sdk/resourcemanager/frontdoor/armfrontdoor/frontendendpoints_client.go
sdk/resourcemanager/frontdoor/armfrontdoor/frontendendpoints_client_example_test.go
sdk/resourcemanager/frontdoor/armfrontdoor/managedrulesets_client.go
sdk/resourcemanager/frontdoor/armfrontdoor/managedrulesets_client_example_test.go
sdk/resourcemanager/frontdoor/armfrontdoor/models.go
sdk/resourcemanager/frontdoor/armfrontdoor/models_serde.go
sdk/resourcemanager/frontdoor/armfrontdoor/nameavailability_client.go
sdk/resourcemanager/frontdoor/armfrontdoor/nameavailability_client_example_test.go
sdk/resourcemanager/frontdoor/armfrontdoor/nameavailabilitywithsubscription_client.go
sdk/resourcemanager/frontdoor/armfrontdoor/nameavailabilitywithsubscription_client_example_test.go
sdk/resourcemanager/frontdoor/armfrontdoor/networkexperimentprofiles_client_example_test.go
sdk/resourcemanager/frontdoor/armfrontdoor/policies_client.go
sdk/resourcemanager/frontdoor/armfrontdoor/policies_client_example_test.go
sdk/resourcemanager/frontdoor/armfrontdoor/preconfiguredendpoints_client_example_test.go
sdk/resourcemanager/frontdoor/armfrontdoor/reports_client_example_test.go
sdk/resourcemanager/frontdoor/armfrontdoor/response_types.go
sdk/resourcemanager/frontdoor/armfrontdoor/rulesengines_client.go
sdk/resourcemanager/frontdoor/armfrontdoor/rulesengines_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4075

[Release] sdk/resourcemanager/frontdoor/armfrontdoor/1.2.0

---

sdk/containers/azcontainerregistry/CHANGELOG.md
sdk/containers/azcontainerregistry/blob_custom_client.go
sdk/containers/azcontainerregistry/blob_custom_client_test.go

fix: https://github.com/Azure/azure-sdk-for-go/issues/20870

do not re-calculate digest when retry

---

sdk/resourcemanager/liftrqumulo/armqumulo/CHANGELOG.md
sdk/resourcemanager/liftrqumulo/armqumulo/autorest.md
sdk/resourcemanager/liftrqumulo/armqumulo/constants.go
sdk/resourcemanager/liftrqumulo/armqumulo/filesystems_client.go
sdk/resourcemanager/liftrqumulo/armqumulo/filesystems_client_example_test.go
sdk/resourcemanager/liftrqumulo/armqumulo/models.go
sdk/resourcemanager/liftrqumulo/armqumulo/operations_client.go
sdk/resourcemanager/liftrqumulo/armqumulo/operations_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4095

[Release] sdk/resourcemanager/liftrqumulo/armqumulo/1.0.0

---

sdk/resourcemanager/devhub/armdevhub/CHANGELOG.md
sdk/resourcemanager/devhub/armdevhub/autorest.md
sdk/resourcemanager/devhub/armdevhub/constants.go
sdk/resourcemanager/devhub/armdevhub/developerhubservice_client.go
sdk/resourcemanager/devhub/armdevhub/developerhubservice_client_example_test.go
sdk/resourcemanager/devhub/armdevhub/models.go
sdk/resourcemanager/devhub/armdevhub/models_serde.go
sdk/resourcemanager/devhub/armdevhub/operations_client.go
sdk/resourcemanager/devhub/armdevhub/operations_client_example_test.go
sdk/resourcemanager/devhub/armdevhub/response_types.go
sdk/resourcemanager/devhub/armdevhub/workflow_client.go
sdk/resourcemanager/devhub/armdevhub/workflow_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4122

[Release] sdk/resourcemanager/devhub/armdevhub/0.4.0

---

sdk/resourcemanager/databox/armdatabox/CHANGELOG.md
sdk/resourcemanager/databox/armdatabox/autorest.md
sdk/resourcemanager/databox/armdatabox/constants.go
sdk/resourcemanager/databox/armdatabox/go.mod
sdk/resourcemanager/databox/armdatabox/jobs_client.go
sdk/resourcemanager/databox/armdatabox/jobs_client_example_test.go
sdk/resourcemanager/databox/armdatabox/management_client.go
sdk/resourcemanager/databox/armdatabox/management_client_example_test.go
sdk/resourcemanager/databox/armdatabox/models.go
sdk/resourcemanager/databox/armdatabox/models_serde.go
sdk/resourcemanager/databox/armdatabox/operations_client.go
sdk/resourcemanager/databox/armdatabox/operations_client_example_test.go
sdk/resourcemanager/databox/armdatabox/service_client.go
sdk/resourcemanager/databox/armdatabox/service_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4103

[Release] sdk/resourcemanager/databox/armdatabox/2.0.0

---

sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/CHANGELOG.md
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/autorest.md
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/constants.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/extensions_client.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/extensions_client_example_test.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/fluxconfigoperationstatus_client.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/fluxconfigoperationstatus_client_example_test.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/fluxconfigurations_client.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/fluxconfigurations_client_example_test.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/go.mod
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/models.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/models_serde.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/operations_client.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/operations_client_example_test.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/operationstatus_client.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/operationstatus_client_example_test.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/sourcecontrolconfigurations_client.go
sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/sourcecontrolconfigurations_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4106

[Release] sdk/resourcemanager/kubernetesconfiguration/armkubernetesconfiguration/2.0.0

---

sdk/messaging/azeventhubs/consumer_client_test.go

We use an ARM client in the azeventhubs test so (unlike other clients) we need to pass in an explicit Cloud value.
This is part of why we were seeing weekly failures with #19744.
There is another issue where the connectivity seems to be _very_ unreliable between our live tests and the cloud itself. EngSys is investigating that.

[azeventhubs] Pass in a cloud when we use the ARM client.

---

sdk/security/keyvault/azadmin/CHANGELOG.md
sdk/security/keyvault/azadmin/backup/autorest.md
sdk/security/keyvault/azadmin/backup/client.go
sdk/security/keyvault/azadmin/backup/client_test.go
sdk/security/keyvault/azadmin/backup/example_test.go
sdk/security/keyvault/azadmin/backup/models.go
sdk/security/keyvault/azadmin/backup/models_serde.go
sdk/security/keyvault/azadmin/backup/utils_test.go

Renames for the azadmin module based on feedback

[keyvault] azadmin renames

---

sdk/azcore/CHANGELOG.md

Prep for azcore beta release

---

sdk/containers/azcontainerregistry/README.md
sdk/containers/azcontainerregistry/TROUBLESHOOTING.md

resolve: https://github.com/Azure/azure-sdk-for-go/issues/20837

add TSG for azcontainerregistry

---

sdk/security/keyvault/azadmin/README.md
sdk/security/keyvault/azcertificates/README.md
sdk/security/keyvault/azkeys/README.md
sdk/security/keyvault/azsecrets/README.md

Removing some misleading copy pasta

Update Key Vault logging examples

---

sdk/containers/azcontainerregistry/CHANGELOG.md
sdk/containers/azcontainerregistry/custom_constants.go

add changelog for acr new version

---

sdk/storage/azblob/blockblob/mmf_unix.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/20908

Add AIX to build constraints

---

sdk/azcore/runtime/policy_retry.go

Replace pow util function with bit operation in runtime package

Replace pow util function with bit operation

---

sdk/security/keyvault/azadmin/CHANGELOG.md
sdk/security/keyvault/azadmin/internal/version.go

Updating version and release date

[keyvault] azadmin prep for release

---

sdk/security/keyvault/azsecrets/CHANGELOG.md
sdk/security/keyvault/azsecrets/assets.json
sdk/security/keyvault/azsecrets/autorest.md
sdk/security/keyvault/azsecrets/client.go
sdk/security/keyvault/azsecrets/client_test.go
sdk/security/keyvault/azsecrets/models.go
sdk/security/keyvault/azsecrets/version.go

* Update version and date for release
* Remove MaxResults option

[keyvault] azsecrets prep for release

---

sdk/azcore/CHANGELOG.md

Prep for azcore v1.7.0-beta.2 release

---

sdk/security/keyvault/azadmin/go.mod
sdk/security/keyvault/azadmin/go.sum
sdk/security/keyvault/azcertificates/CHANGELOG.md
sdk/security/keyvault/azcertificates/go.mod
sdk/security/keyvault/azcertificates/go.sum
sdk/security/keyvault/azcertificates/testdata/perf/go.mod
sdk/security/keyvault/azcertificates/testdata/perf/go.sum
sdk/security/keyvault/azcertificates/version.go
sdk/security/keyvault/azkeys/go.mod
sdk/security/keyvault/azkeys/go.sum
sdk/security/keyvault/azkeys/testdata/perf/go.mod
sdk/security/keyvault/azkeys/testdata/perf/go.sum
sdk/security/keyvault/azsecrets/go.mod
sdk/security/keyvault/azsecrets/go.sum
sdk/security/keyvault/azsecrets/testdata/perf/go.mod
sdk/security/keyvault/azsecrets/testdata/perf/go.sum

Updating key vault modules to the newest azcore version to pick up needed bug fixes.

[keyvault] update azcore 

---

.github/CODEOWNERS
sdk/tracing/azotel/CHANGELOG.md
sdk/tracing/azotel/README.md
sdk/tracing/azotel/go.mod
sdk/tracing/azotel/go.sum

Prep azotel for v0.1.0 release

---

sdk/containers/azcontainerregistry/CHANGELOG.md
sdk/containers/azcontainerregistry/digest_helper.go

some minor change commented in https://github.com/Azure/azure-sdk-for-go/pull/20887
cc: @shizhMSFT

refine some logics and comments according to ACR service team's review

---

sdk/security/keyvault/azadmin/CHANGELOG.md
sdk/security/keyvault/azkeys/CHANGELOG.md
sdk/security/keyvault/azkeys/autorest.md
sdk/security/keyvault/azkeys/client_test.go
sdk/security/keyvault/azkeys/example_test.go
sdk/security/keyvault/azkeys/models.go
sdk/security/keyvault/azkeys/models_serde.go
sdk/security/keyvault/azsecrets/CHANGELOG.md

* prep azkeys, azsecrets, azadmin for release
* rename azkeys.LifetimeActions to azkeys.LifetimeAction so it will match with azcertificates.

[keyvault] prep-for-release

---

sdk/resourcemanager/recoveryservices/armrecoveryservices/CHANGELOG.md
sdk/resourcemanager/recoveryservices/armrecoveryservices/assets.json
sdk/resourcemanager/recoveryservices/armrecoveryservices/autorest.md
sdk/resourcemanager/recoveryservices/armrecoveryservices/client.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/client_example_test.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/constants.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/models.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/models_serde.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/operations_client.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/operations_client_example_test.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/privatelinkresources_client.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/privatelinkresources_client_example_test.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/registeredidentities_client.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/registeredidentities_client_example_test.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/replicationusages_client.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/replicationusages_client_example_test.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/usages_client.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/usages_client_example_test.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/vaultcertificates_client.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/vaultcertificates_client_example_test.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/vaultextendedinfo_client.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/vaultextendedinfo_client_example_test.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/vaults_client.go
sdk/resourcemanager/recoveryservices/armrecoveryservices/vaults_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4164

[Release] sdk/resourcemanager/recoveryservices/armrecoveryservices/1.4.0

---

sdk/resourcemanager/selfhelp/armselfhelp/CHANGELOG.md
sdk/resourcemanager/selfhelp/armselfhelp/assets.json
sdk/resourcemanager/selfhelp/armselfhelp/autorest.md
sdk/resourcemanager/selfhelp/armselfhelp/constants.go
sdk/resourcemanager/selfhelp/armselfhelp/diagnostics_client.go
sdk/resourcemanager/selfhelp/armselfhelp/diagnostics_client_example_test.go
sdk/resourcemanager/selfhelp/armselfhelp/discoverysolution_client.go
sdk/resourcemanager/selfhelp/armselfhelp/discoverysolution_client_example_test.go
sdk/resourcemanager/selfhelp/armselfhelp/go.mod
sdk/resourcemanager/selfhelp/armselfhelp/models.go
sdk/resourcemanager/selfhelp/armselfhelp/operations_client.go
sdk/resourcemanager/selfhelp/armselfhelp/operations_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4176

[Release] sdk/resourcemanager/selfhelp/armselfhelp/1.0.0

---

sdk/resourcemanager/redis/armredis/CHANGELOG.md
sdk/resourcemanager/redis/armredis/assets.json
sdk/resourcemanager/redis/armredis/asyncoperationstatus_client.go
sdk/resourcemanager/redis/armredis/asyncoperationstatus_client_example_test.go
sdk/resourcemanager/redis/armredis/autorest.md
sdk/resourcemanager/redis/armredis/client.go
sdk/resourcemanager/redis/armredis/client_example_test.go
sdk/resourcemanager/redis/armredis/constants.go
sdk/resourcemanager/redis/armredis/firewallrules_client.go
sdk/resourcemanager/redis/armredis/firewallrules_client_example_test.go
sdk/resourcemanager/redis/armredis/linkedserver_client.go
sdk/resourcemanager/redis/armredis/linkedserver_client_example_test.go
sdk/resourcemanager/redis/armredis/models.go
sdk/resourcemanager/redis/armredis/models_serde.go
sdk/resourcemanager/redis/armredis/operations_client.go
sdk/resourcemanager/redis/armredis/operations_client_example_test.go
sdk/resourcemanager/redis/armredis/patchschedules_client.go
sdk/resourcemanager/redis/armredis/patchschedules_client_example_test.go
sdk/resourcemanager/redis/armredis/privateendpointconnections_client.go
sdk/resourcemanager/redis/armredis/privateendpointconnections_client_example_test.go
sdk/resourcemanager/redis/armredis/privatelinkresources_client.go
sdk/resourcemanager/redis/armredis/privatelinkresources_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4184

[Release] sdk/resourcemanager/redis/armredis/2.3.0

---

sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/CHANGELOG.md
sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/autorest.md
sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/constants.go
sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/go.mod

Deprecated: use github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cosmosforpostgresql/armcosmosforpostgresql instead.

Deprecated sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc

---

eng/tools/internal/report/packages.go

chore: slice replace loop

---

eng/scripts/MgmtTestLib.ps1

fix the ci failure of auto-release and mock test of mgmt. package.

update gotest version

---

sdk/azcore/core_test.go

Update test to ensure pipelines are equal

---

eng/pipelines/templates/steps/build-test.yml

Revert proxy upgrade until we resolve the multi-run issue.

Pin Original Proxy Version

---

sdk/azcore/CHANGELOG.md

Prep for azcore v1.7.0 release

---

sdk/tracing/azotel/CHANGELOG.md
sdk/tracing/azotel/go.mod
sdk/tracing/azotel/go.sum
sdk/tracing/azotel/internal/version.go

Prep azotel for release

---

sdk/security/keyvault/azadmin/CHANGELOG.md
sdk/security/keyvault/azadmin/internal/version.go

[azadmin] prep for release

---

sdk/security/keyvault/azsecrets/CHANGELOG.md
sdk/security/keyvault/azsecrets/version.go

[azsecrets] prep for release

---

sdk/security/keyvault/azcertificates/CHANGELOG.md

[azcertificates] prep-for-release

---

sdk/security/keyvault/azkeys/CHANGELOG.md
sdk/security/keyvault/azkeys/version.go

update changelog and version to prep for release

[azkeys] prep for release

---

sdk/resourcemanager/monitor/armmonitor/CHANGELOG.md
sdk/resourcemanager/monitor/armmonitor/autorest.md
sdk/resourcemanager/monitor/armmonitor/constants.go
sdk/resourcemanager/monitor/armmonitor/go.mod
sdk/resourcemanager/monitor/armmonitor/go.sum

Fixes https://github.com/Azure/azure-sdk-for-go/issues/21193

Prep armmonitor for release

---

sdk/cognitiveservices/azopenai/CHANGELOG.md
sdk/cognitiveservices/azopenai/example_client_getchatcompletions_test.go

(also updating changelog for release today)

[azopenai] Removing the constants in functions example, they seem to confuse more than help.

---

eng/scripts/MgmtTestLib.ps1
eng/scripts/build.ps1

upgrade to @autorest/go@4.0.0-preview.51

upgrade @autorest/go version

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client.go
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/directory/models.go
sdk/storage/azfile/directory/responses.go
sdk/storage/azfile/file/client.go
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/file/models.go
sdk/storage/azfile/file/responses.go
sdk/storage/azfile/internal/exported/smb_property.go
sdk/storage/azfile/internal/generated/autorest.md
sdk/storage/azfile/internal/generated/zz_directory_client.go
sdk/storage/azfile/internal/generated/zz_file_client.go
sdk/storage/azfile/internal/generated/zz_models.go
sdk/storage/azfile/internal/testcommon/common.go

azfile: Directory and file rename

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/directory/client.go
sdk/storage/azfile/go.mod
sdk/storage/azfile/go.sum
sdk/storage/azfile/internal/exported/log_events.go
sdk/storage/azfile/log.go
sdk/storage/azfile/service/client.go
sdk/storage/azfile/share/client.go

azfile: Update azcore to 1.7.0

---

.github/CODEOWNERS

The focus of these changes is to fix the naming pattern used in one of the IoT labels.

[CODEOWNERS] Fix label pattern

---

sdk/resourcemanager/batch/armbatch/CHANGELOG.md
sdk/resourcemanager/batch/armbatch/account_client.go
sdk/resourcemanager/batch/armbatch/account_client_example_test.go
sdk/resourcemanager/batch/armbatch/application_client.go
sdk/resourcemanager/batch/armbatch/application_client_example_test.go
sdk/resourcemanager/batch/armbatch/applicationpackage_client.go
sdk/resourcemanager/batch/armbatch/applicationpackage_client_example_test.go
sdk/resourcemanager/batch/armbatch/autorest.md
sdk/resourcemanager/batch/armbatch/certificate_client.go
sdk/resourcemanager/batch/armbatch/certificate_client_example_test.go
sdk/resourcemanager/batch/armbatch/constants.go
sdk/resourcemanager/batch/armbatch/go.mod
sdk/resourcemanager/batch/armbatch/go.sum
sdk/resourcemanager/batch/armbatch/location_client.go
sdk/resourcemanager/batch/armbatch/location_client_example_test.go
sdk/resourcemanager/batch/armbatch/models.go
sdk/resourcemanager/batch/armbatch/models_serde.go
sdk/resourcemanager/batch/armbatch/operations_client.go
sdk/resourcemanager/batch/armbatch/operations_client_example_test.go
sdk/resourcemanager/batch/armbatch/pool_client.go
sdk/resourcemanager/batch/armbatch/pool_client_example_test.go
sdk/resourcemanager/batch/armbatch/privateendpointconnection_client.go
sdk/resourcemanager/batch/armbatch/privateendpointconnection_client_example_test.go
sdk/resourcemanager/batch/armbatch/privatelinkresource_client.go
sdk/resourcemanager/batch/armbatch/privatelinkresource_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4244

[Release] sdk/resourcemanager/batch/armbatch/2.0.0

---

eng/scripts/MgmtTestLib.ps1
eng/scripts/build.ps1

- @autorest/go@4.0.0-preview.54 -> @autorest/go@4.0.0-preview.55
- @autorest/gotest@4.6.1 -> @autorest/gotest@4.6.2

upgrade autorest extension version

---

eng/tools/generator/cmd/v2/common/generation.go

When onboard and --package-config is set, it will repeat.

generator tool bug fix

---

sdk/storage/azfile/assets.json
sdk/storage/azfile/internal/testcommon/clients_auth.go
sdk/storage/azfile/service/client_test.go
sdk/storage/azfile/share/client_test.go

azfile: Premium File Shares - Updated for new bandwidth limits

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/exported/exported.go

This is the azcore API allowing clients to opt in to CAE. #21333 has the azidentity implementation.

Add TokenRequestOptions.EnableCAE

---

sdk/security/keyvault/internal/CHANGELOG.md

[keyvault internal] prep for release

---

.github/CODEOWNERS
sdk/ai/azopenai/event_reader_test.go

Also, updating CODEOWNERS to add @jhendrixMSFT to the `ai` folder.

[azopenai] Add test for different formats in chat completions streaming 

---

sdk/resourcemanager/compute/armcompute/README.md
sdk/resourcemanager/containerregistry/armcontainerregistry/README.md
sdk/resourcemanager/containerservice/armcontainerservice/README.md
sdk/resourcemanager/network/armnetwork/README.md
sdk/resourcemanager/resources/armresources/README.md
sdk/resourcemanager/resources/armsubscriptions/README.md
sdk/resourcemanager/storage/armstorage/README.md

Add doc links to fakes example

---

sdk/data/azcosmos/CHANGELOG.md

Release for bugfix related to https://github.com/Azure/azure-sdk-for-go/issues/21389

Cosmos DB: Changelog for 0.3.6 bugfix release

---

sdk/security/keyvault/azadmin/CHANGELOG.md
sdk/security/keyvault/azkeys/CHANGELOG.md
sdk/security/keyvault/azsecrets/CHANGELOG.md

Update changelog to prep for release

[keyvault] prep for release

---

sdk/storage/azfile/README.md
sdk/storage/azfile/directory/client.go
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/directory/constants.go
sdk/storage/azfile/directory/examples_test.go
sdk/storage/azfile/directory/models.go
sdk/storage/azfile/directory/responses.go
sdk/storage/azfile/file/client.go
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/file/examples_test.go
sdk/storage/azfile/file/models.go
sdk/storage/azfile/file/responses.go
sdk/storage/azfile/internal/exported/file_permissions.go
sdk/storage/azfile/internal/exported/smb_property.go
sdk/storage/azfile/service/constants.go
sdk/storage/azfile/share/constants.go
sdk/storage/azfile/share/examples_test.go

azfile: API View feedback + examples

---

sdk/monitor/azingest/README.md

Add links to monitor/azingest README

---

sdk/security/keyvault/azadmin/CHANGELOG.md
sdk/security/keyvault/azkeys/CHANGELOG.md

[keyvault] update date

---

sdk/resourcemanager/apimanagement/armapimanagement/apimapis_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimapiversionsets_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimauthorizationservers_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimcaches_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimdeployment_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimgateways_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimgroups_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimidentityprovider_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimnamedvalues_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimnotifications_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimopenidconnectproviders_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimpolicies_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimportalrevisions_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimportalsettings_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimprivatelink_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimproducts_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimreports_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimschema_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimsubscriptions_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimtags_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimtenant_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/apimusers_live_test.go
sdk/resourcemanager/apimanagement/armapimanagement/assets.json
sdk/resourcemanager/apimanagement/armapimanagement/go.mod
sdk/resourcemanager/apimanagement/armapimanagement/go.sum

https://github.com/Azure/azure-sdk-for-go/pull/21307

update armapimanagement live test

---

sdk/security/keyvault/azadmin/CHANGELOG.md

Update release date to today
PModule was delayed in release due to managed hsm deployment issues.

[azadmin] release date

---

.github/PULL_REQUEST_TEMPLATE.md

Do not refer to global CHANGELOG.md

---

sdk/azidentity/ci.yml
sdk/azidentity/test-resources.bicep

Remove duplicate identity test variables

---

sdk/monitor/azingest/CHANGELOG.md
sdk/monitor/azingest/README.md
sdk/monitor/azingest/TROUBLESHOOTING.md

Closes https://github.com/Azure/azure-sdk-for-go/issues/21257
Adds troubleshooting guide for the `azingest` module.

Monitor Ingestion Troubleshooting Guide

---

sdk/monitor/azingest/README.md

Adding the link to the new troubleshooting guide to the readme

[azingest] add troubleshooting link to readme

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/README.md

Cleaning up the CHANGELOG.md and README.md in preparation for potential release this or next week.

Cleaning up CHANGELOG.md and README.md

---

sdk/messaging/azeventhubs/internal/eh/stress/Dockerfile
sdk/messaging/azservicebus/internal/stress/Dockerfile

Updating stress to use mariner based images

Use mariner go image tag for service bus stress

---

sdk/azcore/CHANGELOG.md

Prep azcore for v1.8.0-beta.3 release

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/go.mod
sdk/storage/azfile/go.sum

azfile: STG 87 preview

---

eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go

https://github.com/Azure/azure-sdk-for-go/issues/21436

Upgrade the module version used in live test

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/internal/exported/version.go

Correcting and updating package version.

Updating Module Version + Changelog

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/internal/exported/version.go

The beta suffix isn't required for prerelease versions.

Clean up azdatalake pending version number

---

eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go
eng/tools/generator/cmd/v2/release/releaseCmd.go

release sdk/resourcemanger/containerregistry/armcontainerregistry stable version, the swagger input-files include preview.

generator tools add --force-stable-version flag

---

sdk/azidentity/errors.go

I run gocritic locally and this is its only complaint about azidentity.

Rewrite if-else chain as switch

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/policy_register_rp.go
sdk/azcore/arm/runtime/policy_register_rp_test.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/21604

Add another error code to the list of unregistered RP errors

---

sdk/ai/azopenai/example_client_getchatcompletions_extensions_test.go

[azopenai] Fixing unused variable in example.

---

sdk/messaging/azservicebus/admin/admin_client_queue.go
sdk/messaging/azservicebus/admin/admin_client_subscription.go
sdk/messaging/azservicebus/admin/admin_client_test.go
sdk/messaging/azservicebus/admin/admin_client_topic.go

[azservicebus] Adding in `(Queue|Topic|Subscription)Name` fields.

---

sdk/ai/azopenai/CONTRIBUTING.md
sdk/ai/azopenai/client_shared_test.go
sdk/ai/azopenai/testdata/tsp-location.yaml

[azopenai] Adding in a contributors guide, updating internal docs

---

sdk/azidentity/example_user_auth_test.go

Making the example from #21245 part of the docs

Add user authentication example

---

sdk/messaging/azeventgrid/client_test.go

[azeventgrid] Unskip tests now that the fix has been deployed.

---

sdk/azcore/messaging/cloud_event.go
sdk/azcore/messaging/cloud_event_test.go
sdk/azcore/messaging/example_usingcloudevent_test.go

Fix MIT license comment

---

sdk/azcore/CHANGELOG.md

Add breaking changes to release notes

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go

Updated changelog with v1.8.0 release notes.

azcore v1.9.0-beta.1 release

---

sdk/monitor/azingest/CHANGELOG.md
sdk/monitor/azingest/README.md
sdk/monitor/azingest/cloud_config.go
sdk/monitor/azingest/custom_client.go
sdk/monitor/azingest/utils_test.go

Adding sovereign cloud support for Monitor Ingestion.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/21648

[azingest] add sovereign support

---

sdk/monitor/azingest/README.md

Fix typo.
Thanks, @richardpark-msft! :)

[azingest] fix typo

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/internal/exported/blob_batch.go
sdk/storage/azblob/service/client_test.go

Blob Batch API fix when / is present in blob path

---

eng/tools/generator/config/validate/validator.go

Handle package names like package-netapp, but not multiple services

generator tool fix

---

sdk/azcore/runtime/pager.go

Capture err in a deferred func to get the updated value for endSpan.

Consolidate some duplicate code in Pager[T].NextPage

---

sdk/azidentity/errors.go
sdk/azidentity/errors_test.go

fix: handle nil request case

---

sdk/ai/azopenai/models.go
sdk/ai/azopenai/models_serde.go
sdk/ai/azopenai/testdata/tsp-location.yaml

They did a refactor and it removed an unused type.

[azopenai] Update to latest .tsp

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/checkpoints/blob_store.go
sdk/messaging/azeventhubs/checkpoints/blob_store_migration_test.go
sdk/messaging/azeventhubs/checkpoints/blob_store_test.go
sdk/messaging/azeventhubs/consumer_client_test.go
sdk/messaging/azeventhubs/internal/constants.go
sdk/messaging/azeventhubs/internal/eh/stress/Dockerfile
sdk/messaging/azeventhubs/internal/eh/stress/scenarios-matrix.yaml
sdk/messaging/azeventhubs/internal/eh/stress/stress.go
sdk/messaging/azeventhubs/internal/eh/stress/templates/stress-test-job.yaml
sdk/messaging/azeventhubs/internal/eh/stress/tests/checkpoints_stress_tester.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/metrics.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/shared.go
sdk/messaging/azeventhubs/processor_test.go
sdk/messaging/azservicebus/internal/stress/Dockerfile

- Fixing casing issue with blobs by adding an in-place migration to the proper lowercase blob path.
- Also adding in tests of all sorts - live and stress.
Fixes #21352

[azeventhubs] Fixing issue with checkpoint/ownership blob casing that would affect compatibility

---

sdk/resourcemanager/signalr/armsignalr/CHANGELOG.md
sdk/resourcemanager/signalr/armsignalr/assets.json
sdk/resourcemanager/signalr/armsignalr/autorest.md
sdk/resourcemanager/signalr/armsignalr/build.go
sdk/resourcemanager/signalr/armsignalr/client.go
sdk/resourcemanager/signalr/armsignalr/client_example_test.go
sdk/resourcemanager/signalr/armsignalr/constants.go
sdk/resourcemanager/signalr/armsignalr/customcertificates_client.go
sdk/resourcemanager/signalr/armsignalr/customcertificates_client_example_test.go
sdk/resourcemanager/signalr/armsignalr/customdomains_client.go
sdk/resourcemanager/signalr/armsignalr/customdomains_client_example_test.go
sdk/resourcemanager/signalr/armsignalr/models.go
sdk/resourcemanager/signalr/armsignalr/models_serde.go
sdk/resourcemanager/signalr/armsignalr/operations_client.go
sdk/resourcemanager/signalr/armsignalr/operations_client_example_test.go
sdk/resourcemanager/signalr/armsignalr/privateendpointconnections_client.go
sdk/resourcemanager/signalr/armsignalr/privateendpointconnections_client_example_test.go
sdk/resourcemanager/signalr/armsignalr/privatelinkresources_client.go
sdk/resourcemanager/signalr/armsignalr/privatelinkresources_client_example_test.go
sdk/resourcemanager/signalr/armsignalr/replicas_client.go
sdk/resourcemanager/signalr/armsignalr/replicas_client_example_test.go
sdk/resourcemanager/signalr/armsignalr/sharedprivatelinkresources_client.go
sdk/resourcemanager/signalr/armsignalr/sharedprivatelinkresources_client_example_test.go
sdk/resourcemanager/signalr/armsignalr/usages_client.go
sdk/resourcemanager/signalr/armsignalr/usages_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4614

[Release] sdk/resourcemanager/signalr/armsignalr/1.2.0-beta.2

---

sdk/azcore/core.go
sdk/azcore/policy/policy.go

Update docs for ClientOptions type

---

sdk/azcore/doc.go

Add doc section on fakes

---

sdk/azcore/fake/fake.go
sdk/azcore/fake/internal/exported/fake.go
sdk/azcore/fake/server/server.go
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/internal/shared/shared.go
sdk/azcore/runtime/policy_bearer_token.go
sdk/azcore/runtime/policy_bearer_token_test.go
sdk/azcore/runtime/poller_test.go
sdk/azcore/testdata/perf/go.mod
sdk/azcore/testdata/perf/go.sum

Used NonRetriableError from internal.

Update to latest internal module

---

sdk/tracing/azotel/CHANGELOG.md
sdk/tracing/azotel/examples_test.go
sdk/tracing/azotel/go.mod
sdk/tracing/azotel/go.sum
sdk/tracing/azotel/internal/version.go
sdk/tracing/azotel/otel.go
sdk/tracing/azotel/otel_test.go

Cleaned up example and fixed test with breaking change from beta.

Update azotel to latest version of azcore

---

sdk/messaging/azservicebus/ci.yml

Proof of concept for regional affinity testing with the China cloud

[azservicebus] Test china cloud with regional affinity pool

---

sdk/data/azappconfig/assets.json
sdk/data/azappconfig/client.go
sdk/data/azappconfig/internal/appconfiguration_ext.json
sdk/data/azappconfig/internal/autorest.md
sdk/data/azappconfig/internal/generated/zz_azureappconfiguration_client.go
sdk/data/azappconfig/internal/generated/zz_constants.go
sdk/data/azappconfig/internal/generated/zz_models.go
sdk/data/azappconfig/internal/generated/zz_models_serde.go
sdk/data/azappconfig/internal/generated/zz_response_types.go

add internal snapshot support for app config

---

sdk/data/azappconfig/CHANGELOG.md
sdk/data/azappconfig/client.go
sdk/data/azappconfig/go.mod
sdk/data/azappconfig/go.sum
sdk/data/azappconfig/internal/generated/custom_client.go
sdk/data/azappconfig/version.go

Add spans to azappconfig

---

sdk/security/keyvault/azkeys/CHANGELOG.md
sdk/security/keyvault/azkeys/autorest.md
sdk/security/keyvault/azkeys/custom_client.go
sdk/security/keyvault/azkeys/version.go

Fixed some values used in tracing.

Update azkeys to latest version of azcore

---

sdk/security/keyvault/azadmin/backup/autorest.md
sdk/security/keyvault/azadmin/backup/client.go
sdk/security/keyvault/azadmin/backup/custom_client.go
sdk/security/keyvault/azadmin/backup/internal/pollers/restore_poller.go
sdk/security/keyvault/azadmin/backup/models.go
sdk/security/keyvault/azadmin/rbac/autorest.md
sdk/security/keyvault/azadmin/rbac/client.go
sdk/security/keyvault/azadmin/settings/autorest.md
sdk/security/keyvault/azadmin/settings/client.go

Regenered code removed JSON tag from previous bad merge.

Fix regex to update all span names

---

eng/scripts/MgmtTestLib.ps1
eng/scripts/build.ps1

- autorest.go@4.0.0-preview.60
- autorest.gotest@4.7.0

upgrade script autorest.go version

---

sdk/data/azappconfig/client.go
sdk/data/azappconfig/internal/autorest.md
sdk/data/azappconfig/internal/generated/zz_models.go

We want this on by default and since the generated code isn't publicly available there's no breaking change.

Make remove pointers for slice elements

---

sdk/storage/azfile/CHANGELOG.md

Changelog update for azfile release v1.1.1

---

documentation/developer_setup.md

Add docs for committing/updating assets.json

---

sdk/monitor/azquery/CHANGELOG.md
sdk/monitor/azquery/autorest.md
sdk/monitor/azquery/custom_client.go
sdk/monitor/azquery/logs_client.go
sdk/monitor/azquery/metrics_client.go
sdk/monitor/azquery/version.go

Add tracing spans to azquery

---

sdk/data/aztables/README.md
sdk/data/aztables/client.go
sdk/data/aztables/client_test.go
sdk/data/aztables/doc.go
sdk/data/aztables/entity.go
sdk/data/aztables/entity_test.go
sdk/data/aztables/errors.go
sdk/data/aztables/example_test.go
sdk/data/aztables/recording_helpers_test.go
sdk/data/aztables/testdata/perf/insert_entity.go
sdk/data/aztables/transaction_batch_test.go
sdk/data/aztables/transactional_batch.go

Replace interface{} with any

---

sdk/data/aztables/README.md
sdk/data/aztables/client.go
sdk/data/aztables/entity.go
sdk/data/aztables/error_codes.go
sdk/data/aztables/example_test.go
sdk/data/aztables/sas_account.go
sdk/data/aztables/sas_query_params.go
sdk/data/aztables/sas_service.go
sdk/data/aztables/service_client.go
sdk/data/aztables/shared_policy_shared_key_credential.go
sdk/data/aztables/transactional_batch.go

Removed language-specific references.

Update links to docs

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/assets.json
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/internal/shared/shared.go
sdk/storage/azblob/internal/shared/shared_test.go

azblob: Remove blob tags

---

eng/tools/generator/cmd/v2/common/changelogProcessor.go
eng/tools/generator/template/rpName/packageName/README.md.tpl

- Removed nil panic
- README.md fake doc

geneator tool

---

documentation/developer_setup.md

Add docs on writing testable examples

---

sdk/internal/recording/recording.go
sdk/internal/recording/testdata/recordings/TestRecording/TestGenerateAlphaNumericID.json

Make the fix in a non-breaking way.

Refactor 4bc279bfefcf94d2049aee9801efd418a12e0314

---

sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/constants.go
sdk/storage/azblob/internal/generated/zz_appendblob_client.go
sdk/storage/azblob/internal/generated/zz_blob_client.go
sdk/storage/azblob/internal/generated/zz_blockblob_client.go
sdk/storage/azblob/internal/generated/zz_container_client.go
sdk/storage/azblob/internal/generated/zz_pageblob_client.go
sdk/storage/azblob/internal/generated/zz_service_client.go

azblob: STG 91 code generation

---

eng/tools/generator/autorest/model/changelog.go
eng/tools/generator/autorest/model/changelog_test.go
eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go

- add `ReplaceReadmeNewClientName` function, ensure that NewXxxClient exists
- public model.SortFuncItem function

feat: add ReplaceReadmeNewClientName function

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/appendblob/client.go
sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/assets.json
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/client.go
sdk/storage/azblob/client_test.go
sdk/storage/azblob/container/client.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/internal/base/clients.go
sdk/storage/azblob/internal/shared/challenge_policy.go
sdk/storage/azblob/internal/shared/challenge_policy_test.go
sdk/storage/azblob/pageblob/client.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azblob/service/client.go
sdk/storage/azblob/service/client_test.go

azblob: Add support for AAD audience

---

sdk/storage/azblob/README.md

azblob: Readme update for STG91

---

sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/client_test.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/internal/base/clients.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azblob/service/client_test.go

azblob: Updating type of audience field

---

sdk/storage/azdatalake/internal/generated/autorest.md
sdk/storage/azdatalake/internal/generated/zz_filesystem_client.go
sdk/storage/azdatalake/internal/generated/zz_models.go
sdk/storage/azdatalake/internal/generated/zz_path_client.go
sdk/storage/azdatalake/internal/generated/zz_response_types.go
sdk/storage/azdatalake/internal/generated/zz_service_client.go

[azdatalake] Swagger update to STG 90

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/internal/exported/version.go

azblob: STG 91 Preview

---

sdk/data/azappconfig/client.go
sdk/data/azappconfig/options.go

Missed one in last round of clean-up.

Replace string with azcore.ETag

---

.github/CODEOWNERS

Added Simon and Kushagra as code owners on GO Cosmos SDK

Added Simon and Kushagra as code owners on GO Cosmos SDK

---

sdk/containers/azcontainerregistry/CHANGELOG.md

release acr beta

---

sdk/monitor/azquery/metrics_client_test.go

Fixing flakey test in pipeline by changing check to be more general.

[azquery] fix flakey test

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/internal/exported/version.go

[azdatalake] v1.1.0 GA STG78-82

---

sdk/ai/azopenai/example_client_getchatcompletions_vision_test.go

[azopenai] Adding in an example for gpt-4-vision.

---

sdk/messaging/azwebpubsub/CHANGELOG.md

Update release date

---

sdk/storage/azfile/CHANGELOG.md

azfile: Updating changelog for azfile 1.2.1 release

---

sdk/storage/azdatalake/CHANGELOG.md

azdatalake: Updating changelog for azdatalake 1.1.1 release

---

sdk/storage/azblob/pageblob/examples_test.go

- [] Updates to module CHANGELOG.md are included.

[azblob] Pageblob documentation fix

---

eng/swagger_to_sdk_config.json

update breakingchange label config

---

sdk/messaging/eventgrid/aznamespaces/client_test.go

One of my tests was assuming that it could get all the messages in one call but shouldn't. It'd occasionally fail in CI as a result.

[aznamespaces] Fixing test that was unreliable in CI

---

sdk/monitor/query/azlogs/autorest.md
sdk/monitor/query/azlogs/client_test.go
sdk/monitor/query/azlogs/examples_test.go
sdk/monitor/query/azlogs/models.go

Changing the code so that slices generated don't use pointers.

[azlogs] remove pointers in generated slices

---

sdk/azidentity/TOKEN_CACHING.MD

v1.6.0-beta.2 included a new example.

Update example link in TOKEN_CACHING.MD

---

sdk/ai/azopenai/test-resources.bicep
sdk/ai/azopenaiassistants/test-resources.bicep
sdk/containers/azcontainerregistry/test-resources.bicep
sdk/messaging/azeventgrid/test-resources.bicep
sdk/messaging/azeventhubs/test-resources.bicep
sdk/messaging/azservicebus/internal/stress/stress-test-resources.bicep
sdk/messaging/azservicebus/test-resources.bicep
sdk/messaging/eventgrid/azeventgrid/test-resources.bicep
sdk/messaging/eventgrid/aznamespaces/test-resources.bicep
sdk/messaging/eventgrid/azsystemevents/test-resources.bicep
sdk/monitor/azingest/test-resources.bicep
sdk/monitor/azquery/test-resources.bicep
sdk/monitor/ingestion/azlogs/test-resources.bicep
sdk/monitor/query/azlogs/test-resources.bicep
sdk/monitor/query/azmetrics/test-resources.bicep

Bicep is mentioned in the [copyright header guidance](https://docs.opensource.microsoft.com/releasing/general-guidance/copyright-headers) so I suppose we should have these.

Add copyright header to bicep files

---

sdk/azidentity/azidentity.go
sdk/azidentity/azidentity_test.go

azidentity: treat empty tenant id as invalid

---

sdk/monitor/query/azlogs/autorest.md
sdk/monitor/query/azmetrics/CHANGELOG.md
sdk/monitor/query/azmetrics/assets.json
sdk/monitor/query/azmetrics/autorest.md
sdk/monitor/query/azmetrics/client.go

- update `query/azmetrics` to use API version 2024-02-01
- update `query/azlogs` to latest swagger commit

[Monitor Query] update to latest swaggers

---

eng/pipelines/templates/steps/analyze.yml
eng/scripts/Create-ApiReview.ps1
eng/scripts/Language-Settings.ps1

Generate API review using common script.

Updates to use common script to generate API review

---

sdk/resourcemanager/datafactory/armdatafactory/CHANGELOG.md
sdk/resourcemanager/datafactory/armdatafactory/activityruns_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/autorest.md
sdk/resourcemanager/datafactory/armdatafactory/changedatacapture_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/constants.go
sdk/resourcemanager/datafactory/armdatafactory/credentialoperations_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/dataflowdebugsession_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/dataflows_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/datasets_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/exposurecontrol_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/factories_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/globalparameters_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/integrationruntimenodes_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/integrationruntimeobjectmetadata_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/integrationruntimes_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/interfaces.go
sdk/resourcemanager/datafactory/armdatafactory/linkedservices_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/managedprivateendpoints_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/managedvirtualnetworks_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/models.go
sdk/resourcemanager/datafactory/armdatafactory/models_serde.go
sdk/resourcemanager/datafactory/armdatafactory/operations_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/pipelineruns_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/pipelines_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/polymorphic_helpers.go
sdk/resourcemanager/datafactory/armdatafactory/privateendpointconnection_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/privateendpointconnections_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/privatelinkresources_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/triggerruns_client_example_test.go
sdk/resourcemanager/datafactory/armdatafactory/triggers_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/4990

[Release] sdk/resourcemanager/datafactory/armdatafactory/6.1.0

---

sdk/ai/azopenai/CHANGELOG.md
sdk/ai/azopenai/assets.json
sdk/ai/azopenai/autorest.md
sdk/ai/azopenai/client.go
sdk/ai/azopenai/client_embeddings_test.go
sdk/ai/azopenai/client_embeddings_unit_test.go
sdk/ai/azopenai/client_shared_test.go
sdk/ai/azopenai/constants.go
sdk/ai/azopenai/custom_client_embeddings.go
sdk/ai/azopenai/models.go
sdk/ai/azopenai/models_serde.go
sdk/ai/azopenai/testdata/tsp-location.yaml
sdk/ai/azopenai/version.go

- Adds in the Dimensions parameter for Embeddings, allowing greater control over the size of the returned embeddings slice.
- Allow controlling the format the embeddings come back as, avoiding potential deserialization errors due to JSON deserialization.
Fixes #22483

[azopenai] Adding in support for the latest preview: 2024-03-01

---

sdk/azidentity/ci.yml

- Fix go identity matrix/pool selection
- Bump go version for azidentity matrix
- Fix managed identity weekly config

More fixes for managed identity weekly config

---

sdk/azidentity/.gitignore
sdk/azidentity/assets.json
sdk/azidentity/test-resources-post.ps1
sdk/azidentity/test-resources-pre.ps1
sdk/azidentity/test-resources.bicep
sdk/azidentity/testdata/managed-id-test/main.go
sdk/azidentity/workload_identity_test.go

Part of https://github.com/Azure/azure-sdk-for-go/issues/21118

Run live Workload Identity (AKS) test in weekly pipeline

---

sdk/internal/go.mod
sdk/internal/go.sum

Update sdk/internal dependencies

---

sdk/data/azcosmos/CHANGELOG.md

Change auto-generated by PrepareRelease

Prepare release changes for azcosmos 1.0

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/MIGRATION.md
sdk/azidentity/README.md
sdk/azidentity/TROUBLESHOOTING.md
sdk/azidentity/client_assertion_credential.go
sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_credential.go
sdk/azidentity/on_behalf_of_credential.go
sdk/azidentity/test-resources.bicep

Update Azure AD docs/learn.microsoft.com links to their Entra counterparts

Update Azure AD Learn links in Identity

---

sdk/azcore/CHANGELOG.md
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/testdata/perf/go.mod
sdk/azcore/testdata/perf/go.sum

Prep azcore@v1.11.0 for release

---

eng/pipelines/templates/steps/analyze.yml

Add a step in analyze job to validate and create a package work item for Go.

Add new step to validate and create package name

---

sdk/resourcemanager/network/armnetwork/CHANGELOG.md
sdk/resourcemanager/network/armnetwork/autorest.md
sdk/resourcemanager/network/armnetwork/constants.go
sdk/resourcemanager/network/armnetwork/go.mod
sdk/resourcemanager/network/armnetwork/go.sum

[Release] sdk/resourcemanager/network/armnetwork/5.1.1 

---

sdk/messaging/eventgrid/azeventgrid/CHANGELOG.md
sdk/messaging/eventgrid/azeventgrid/internal/version.go

Final APIView (unchanged since last release): https://apiview.dev/Assemblies/Review/e27ae788fd2d4751ad557223146ed488

[azeventgrid] Prepping for first GA of the Event Grid Basic package.

---

sdk/ai/azopenai/CHANGELOG.md
sdk/ai/azopenai/assets.json
sdk/ai/azopenai/autorest.md
sdk/ai/azopenai/client_chat_completions_test.go
sdk/ai/azopenai/client_shared_test.go
sdk/ai/azopenai/models.go
sdk/ai/azopenai/models_serde.go
sdk/ai/azopenai/testdata/tsp-location.yaml

[azopenai] Updating doc comments based on feedback from an issue, as well as previous PR feedback.

---

sdk/azcore/CHANGELOG.md

Prep azcore@v1.11.1 for release

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/assets.json
sdk/storage/azdatalake/filesystem/client.go
sdk/storage/azdatalake/filesystem/client_test.go
sdk/storage/azdatalake/filesystem/examples_test.go
sdk/storage/azdatalake/filesystem/models.go
sdk/storage/azdatalake/filesystem/responses.go

Data Lake Create Bundle

---

sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
sdk/messaging/eventgrid/azsystemevents/autorest.md
sdk/messaging/eventgrid/azsystemevents/constants.go
sdk/messaging/eventgrid/azsystemevents/internal/generate/generate.go
sdk/messaging/eventgrid/azsystemevents/models.go
sdk/messaging/eventgrid/azsystemevents/models_serde.go
sdk/messaging/eventgrid/azsystemevents/system_events2_test.go
sdk/messaging/eventgrid/azsystemevents/system_events4_test.go

* Renames that came out of the arch board.
* 'string' became a fleshed out enumeration

[azsystemevents] Updating to release commit for April ca560e400087f54b306f3a21df582c8a5bbd0abc

---

sdk/resourcemanager/migrationdiscovery/armmigrationdiscoverysap/ci.yml

fix armmigrationdiscoverysap ci.yml

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azfile/CHANGELOG.md

Changelog update for STG 91 Patch release - azblob, azfile

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/internal/exported/version.go

[AzDatalake] Changelog change for stg91 Preview

---

sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/zz_appendblob_client.go
sdk/storage/azblob/internal/generated/zz_blob_client.go
sdk/storage/azblob/internal/generated/zz_blockblob_client.go
sdk/storage/azblob/internal/generated/zz_container_client.go
sdk/storage/azblob/internal/generated/zz_options.go
sdk/storage/azblob/internal/generated/zz_pageblob_client.go
sdk/storage/azblob/internal/generated/zz_service_client.go
sdk/storage/azfile/internal/generated/autorest.md
sdk/storage/azfile/internal/generated/zz_directory_client.go
sdk/storage/azfile/internal/generated/zz_file_client.go
sdk/storage/azfile/internal/generated/zz_models.go
sdk/storage/azfile/internal/generated/zz_service_client.go
sdk/storage/azfile/internal/generated/zz_share_client.go

- [] The PR does not update generated files.

[storage- azblob, azfile] Swagger update to stg93

---

sdk/monitor/ingestion/azlogs/CHANGELOG.md
sdk/monitor/ingestion/azlogs/version.go

Releasing the GA version of Monitor Ingestion!

[Monitor Ingestion] prep for GA release

---

eng/config.json
sdk/monitor/ingestion/azlogs/README.md

[Monitor Ingestion] update README

---

sdk/monitor/query/azmetrics/README.md

[azmetrics] update readme

---

eng/pipelines/templates/steps/analyze.yml
eng/pipelines/templates/variables/globals.yml

Eng gogetu all

---

sdk/monitor/azquery/assets.json
sdk/monitor/azquery/metricsbatch_client_test.go

Update tests to fix flakiness in live pipeline

[azquery] update tests

---

sdk/storage/azblob/go.mod
sdk/storage/azblob/go.sum
sdk/storage/azblob/testdata/perf/go.mod
sdk/storage/azblob/testdata/perf/go.sum
sdk/storage/azdatalake/go.mod
sdk/storage/azdatalake/go.sum
sdk/storage/azfile/go.mod
sdk/storage/azfile/go.sum

Update indirect dependencies - storage - CI Fix

---

eng/pipelines/templates/variables/globals.yml

Disable the go get -u all check for now

---

sdk/azidentity/client_assertion_credential_test.go
sdk/azidentity/client_certificate_credential_test.go
sdk/azidentity/client_secret_credential_test.go
sdk/azidentity/environment_credential_test.go
sdk/azidentity/workload_identity_test.go

Temporary workaround for #22879 to unblock pipelines

Skip live service principal tests

---

sdk/security/keyvault/azkeys/client_test.go

Closes https://github.com/Azure/azure-sdk-for-go/issues/21911

[azkeys] re-enable mhsm test

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity_test.go
sdk/azidentity/azure_pipelines_credential.go
sdk/azidentity/azure_pipelines_credential_test.go
sdk/azidentity/ci.yml

Add AzurePipelinesCredential for service connection authentication

---

sdk/messaging/azwebpubsub/assets.json
sdk/messaging/azwebpubsub/client_shared_test.go
sdk/messaging/azwebpubsub/client_test.go

Part of #22869. Removed unused and redundant sanitizers, made new recordings.

Update azwebpubsub tests for new test proxy

---

sdk/data/azcosmos/README.md
sdk/data/azcosmos/doc.go

Update README for Azure Cosmos DB SDK

[Cosmos] Update README

---

eng/tools/generator/cmd/v2/common/generation.go

panic: runtime error: index out of range [0] with length 0

fix generator tool

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/assets.json
sdk/storage/azdatalake/directory/client_test.go
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/filesystem/client_test.go
sdk/storage/azdatalake/go.mod
sdk/storage/azdatalake/go.sum

Changelog update for azdatalake stg 91 GA release

Prep for azdatalake stg 91 GA release

---

sdk/data/azappconfig/assets.json
sdk/data/azappconfig/client_test.go
sdk/data/azappconfig/go.mod
sdk/data/azappconfig/go.sum
sdk/data/azappconfig/utils_test.go

Update azappconfig for new test proxy

---

sdk/data/aztables/assets.json
sdk/data/aztables/proxy_test.go
sdk/data/aztables/transaction_batch_test.go

Update aztables for new test proxy

---

sdk/azidentity/client_certificate_credential.go
sdk/azidentity/environment_credential.go
sdk/azidentity/example_test.go

Mentioning another limitation and suggesting a workaround

Clarify ParseCertificates documentation

---

sdk/containers/azcontainerregistry/utils_test.go

Fix cloud config for azcontainerregistry tests

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azure_pipelines_credential.go
sdk/azidentity/errors.go
sdk/azidentity/managed_identity_client.go

Closes #22955 by adding some details to help debugging.

Improve AzurePipelinesCredential errors

---

sdk/messaging/eventgrid/aznamespaces/CHANGELOG.md
sdk/messaging/eventgrid/aznamespaces/client_custom.go
sdk/messaging/eventgrid/aznamespaces/client_test.go
sdk/messaging/eventgrid/aznamespaces/example_publish_and_receive_test.go
sdk/messaging/eventgrid/aznamespaces/example_test.go
sdk/messaging/eventgrid/aznamespaces/internal/generate/generate.go
sdk/messaging/eventgrid/aznamespaces/main_test.go
sdk/messaging/eventgrid/aznamespaces/models.go
sdk/messaging/eventgrid/aznamespaces/models_serde.go
sdk/messaging/eventgrid/aznamespaces/options.go
sdk/messaging/eventgrid/aznamespaces/receiver_client.go
sdk/messaging/eventgrid/aznamespaces/receiver_client_custom.go
sdk/messaging/eventgrid/aznamespaces/responses.go
sdk/messaging/eventgrid/aznamespaces/sender_client.go
sdk/messaging/eventgrid/aznamespaces/sender_client_custom.go
sdk/messaging/eventgrid/aznamespaces/shared_test.go
sdk/messaging/eventgrid/aznamespaces/testdata/gen.ps1
sdk/messaging/eventgrid/aznamespaces/testdata/tsp-location.yaml

- Added 'Event' to methods, makes it a bit simpler to know what applies to what.
- Creating two separate options types for the individual clients

[aznamespaces] Taking on all the naming suggestions that came from the apiview.

---

sdk/messaging/eventgrid/aznamespaces/testdata/tsp-location.yaml

This doesn't result in any code changes - the PR merged in without any changes since my last generation.

[aznamespaces] Just updating to the official commit hash. 

---

sdk/resourcemanager/internal/CHANGELOG.md
sdk/resourcemanager/internal/assets.json
sdk/resourcemanager/internal/ci.resourcemanager.yml
sdk/resourcemanager/internal/go.mod
sdk/resourcemanager/internal/go.sum
sdk/resourcemanager/internal/testutil/credential.go
sdk/resourcemanager/internal/testutil/credential_test.go
sdk/resourcemanager/internal/testutil/helper_test.go
sdk/resourcemanager/internal/testutil/recording.go
sdk/resourcemanager/internal/testutil/testsuite_test.go
sdk/resourcemanager/internal/testutil/utils_test.go
sdk/resourcemanager/internal/version.go

resolve: https://github.com/Azure/azure-sdk-for-go/issues/22878

add start/stop recording proxy and remove useless policy

---

sdk/azidentity/CHANGELOG.md

Copying this from the release branch

Add v1.5.2 to azidentity changelog

---

eng/config.json
sdk/ai/azopenai/CHANGELOG.md
sdk/ai/azopenai/assets.json
sdk/ai/azopenai/autorest.md
sdk/ai/azopenai/client.go
sdk/ai/azopenai/client_chat_completions_extensions_test.go
sdk/ai/azopenai/client_shared_test.go
sdk/ai/azopenai/client_test.go
sdk/ai/azopenai/constants.go
sdk/ai/azopenai/custom_client.go
sdk/ai/azopenai/custom_client_image_test.go
sdk/ai/azopenai/custom_client_test.go
sdk/ai/azopenai/custom_models.go
sdk/ai/azopenai/example_client_createimage_test.go
sdk/ai/azopenai/interfaces.go
sdk/ai/azopenai/models.go
sdk/ai/azopenai/models_serde.go
sdk/ai/azopenai/polymorphic_helpers.go
sdk/ai/azopenai/testdata/package-lock.json
sdk/ai/azopenai/testdata/package.json
sdk/ai/azopenai/testdata/tsp-location.yaml

Just a simple update to use the latest TypeSpec surface for 2024-05-01.

[azopenai] Updating API version `2024-05-01`

---

sdk/resourcemanager/internal/go.mod
sdk/resourcemanager/internal/go.sum

github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/internal/v3

fix sdk/resourcemanager/internal module

---

sdk/ai/azopenai/client_shared_test.go
sdk/ai/azopenai/testdata/tsp-location.yaml

This PR updates the hash for the spec to the merged commit. It also includes fixes.

[azopenai] Updating hash to merged PR.

---

sdk/monitor/query/azmetrics/README.md

Closes https://github.com/Azure/azure-sdk-for-go/issues/21263
Add docs for finding metric documentation

[azmetrics] add docs

---

sdk/azcore/CHANGELOG.md
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/internal/shared/constants.go
sdk/azcore/testdata/perf/go.mod
sdk/azcore/testdata/perf/go.sum

Prep azcore v1.12.0 for release

---

sdk/data/azappconfig/CHANGELOG.md
sdk/data/azappconfig/version.go

Prep azappconfig v1.1.1-beta.1 for release

---

eng/.golangci.yml
eng/pipelines/templates/variables/globals.yml
sdk/azcore/arm/internal/resource/resource_identifier.go
sdk/azcore/arm/runtime/pipeline.go
sdk/azcore/etag_test.go
sdk/azcore/example_test.go
sdk/azcore/fake/internal/exported/fake_test.go
sdk/azcore/runtime/policy_http_header_test.go
sdk/internal/perf/perf_runner.go
sdk/internal/perf/recording.go
sdk/template/aztemplate/client_test.go

I suspect there will be some lint that needs to be cleaned up with this change.

Update to latest version of golangci-lint

---

sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
sdk/messaging/eventgrid/azsystemevents/constants.go
sdk/messaging/eventgrid/azsystemevents/models.go
sdk/messaging/eventgrid/azsystemevents/models_serde.go
sdk/messaging/eventgrid/azsystemevents/testdata/tsp-location.yaml

Updating to the latest TypeSpec in main

[azsystemevents] Picking up the last changes for release.

---

sdk/data/azappconfig/client_test.go
sdk/data/azappconfig/constants.go
sdk/data/azappconfig/internal/synctoken/cache_test.go

Clean up lint

---

sdk/containers/azcontainerregistry/example_blob_client_test.go

azcontainerregistry linting

---

sdk/storage/azdatalake/assets.json
sdk/storage/azdatalake/directory/client.go
sdk/storage/azdatalake/directory/client_test.go
sdk/storage/azdatalake/directory/models.go
sdk/storage/azdatalake/file/client.go
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/file/examples_test.go
sdk/storage/azdatalake/file/models.go
sdk/storage/azdatalake/file/retry_reader.go
sdk/storage/azdatalake/filesystem/client.go
sdk/storage/azdatalake/filesystem/client_test.go
sdk/storage/azdatalake/filesystem/models.go
sdk/storage/azdatalake/internal/exported/exported.go
sdk/storage/azdatalake/internal/generated/autorest.md
sdk/storage/azdatalake/internal/generated/zz_models_serde.go
sdk/storage/azdatalake/internal/shared/batch_transfer.go
sdk/storage/azdatalake/internal/testcommon/common.go
sdk/storage/azdatalake/lease/client_test.go
sdk/storage/azdatalake/sas/query_params.go
sdk/storage/azdatalake/sas/service.go

Fixes https://github.com/Azure/azure-rest-api-specs/issues/29233
Minor changes in multiple files are due to GoLintCLI warnings that were found in pipeline runs after this change https://github.com/Azure/azure-sdk-for-go/pull/23013

Storage [azdatalake] ETAG casing issue

---

sdk/storage/azdatalake/CHANGELOG.md

Patch release - [azdatalake] - changelog update

---

sdk/azcore/arm/runtime/pipeline_test.go
sdk/azcore/arm/runtime/policy_register_rp_test.go
sdk/azcore/streaming/progress_test.go
sdk/internal/CHANGELOG.md
sdk/internal/mock/mock.go

Fixed race conditions in some tests and infrastructure

---

sdk/azidentity/BREAKING_CHANGES.md

We have a minor one to document now that v1.6.0 has shipped.

azidentity breaking changes doc

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azfile/CHANGELOG.md

[Storage] Changelog updates for azblob and files

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/go.mod
sdk/storage/azdatalake/go.sum

[Storage] Changelog updates for release of azdatalake preview stg93

---

sdk/security/keyvault/azcertificates/test-resources.json
sdk/security/keyvault/azsecrets/test-resources.json

Fixes https://github.com/Azure/azure-sdk-for-go/issues/23076
Remove unnecessary code from azcertificates and azsecrets

[keyvault] update test-resources.json

---

sdk/data/azcosmos/CHANGELOG.md

Preparing changelog for 1.0.3 hotfix release

Cosmos DB - 1.0.3 release changelog

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/live.tests.yml
eng/pipelines/templates/steps/build-test.yml
sdk/data/azappconfig/ci.yml
sdk/data/azappconfig/test-resources.json

Test with federated auth on: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3882348&view=results
Test with federated auth off: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3882386&view=results

Federated auth for live tests

---

sdk/azidentity/TROUBLESHOOTING.md

Follow-up from https://github.com/Azure/azure-sdk-for-go/pull/23030

Update identity TROUBLESHOOTING.md for AzurePipelinesCredential

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/README.md
sdk/azidentity/TOKEN_CACHING.MD
sdk/azidentity/TROUBLESHOOTING.md
sdk/azidentity/azidentity_test.go
sdk/azidentity/azure_pipelines_credential.go
sdk/azidentity/azure_pipelines_credential_test.go
sdk/azidentity/errors.go
sdk/azidentity/version.go

This version is v1.6.0 plus AzurePipelinesCredential

azidentity v1.7.0

---

eng/ignore-links.txt
sdk/resourcemanager/compute/armcompute/fake_example_test.go
sdk/resourcemanager/search/armsearch/assets.json

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3892594&view=results
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3892599&view=results

fix release issue

---

sdk/ai/azopenaiassistants/autorest.md
sdk/ai/azopenaiassistants/client.go
sdk/ai/azopenaiassistants/client_custom_files.go
sdk/ai/azopenaiassistants/client_custom_pagers.go
sdk/ai/azopenaiassistants/client_custom_streaming.go
sdk/ai/azopenaiassistants/client_custom_streaming_test.go
sdk/ai/azopenaiassistants/client_test.go
sdk/ai/azopenaiassistants/client_vectorstores_test.go
sdk/ai/azopenaiassistants/event_reader.go
sdk/ai/azopenaiassistants/event_reader_test.go
sdk/ai/azopenaiassistants/example_assistants_streaming_test.go
sdk/ai/azopenaiassistants/internal/transform/shared.go
sdk/ai/azopenaiassistants/internal/transform/transform.go
sdk/ai/azopenaiassistants/internal/transform/transform_test.go
sdk/ai/azopenaiassistants/models.go
sdk/ai/azopenaiassistants/models_custom.go
sdk/ai/azopenaiassistants/models_custom_streameventdata.go
sdk/ai/azopenaiassistants/models_serde.go
sdk/ai/azopenaiassistants/shared_test.go
sdk/ai/azopenaiassistants/streaming_helpers_test.go

Adds streaming support in, similar to how we did in azopenai, with the new feature that the events all have different types rather than the same type.
There's a very simple example, and a lot of tests to go through all the scenarios.

[azopenaiassistants] Adding in streaming support for Assistants V2.

---

sdk/ai/azopenaiassistants/CHANGELOG.md
sdk/ai/azopenaiassistants/client_custom_streaming_test.go
sdk/ai/azopenaiassistants/example_assistants_code_interpreter_test.go
sdk/ai/azopenaiassistants/example_assistants_conversation_loop_test.go
sdk/ai/azopenaiassistants/example_assistants_functiontool_test.go
sdk/ai/azopenaiassistants/example_assistants_streaming_test.go
sdk/ai/azopenaiassistants/example_assistants_submit_tool_outputs_streaming_test.go

[azopenaiassistants] Updated changelog, added in examples for more complex scenarios.

---

sdk/storage/azqueue/internal/generated/zz_service_client.go
sdk/storage/azqueue/internal/shared/shared_test.go
sdk/storage/azqueue/internal/testcommon/common.go
sdk/storage/azqueue/sas/query_params.go
sdk/storage/azqueue/sas/service.go
sdk/storage/azqueue/sas/service_test.go
sdk/storage/azqueue/service_client_test.go

- [] Updates to module CHANGELOG.md are included.

[Storage][azqueue] solve linter issues

---

sdk/security/keyvault/azcertificates/example_test.go
sdk/security/keyvault/azkeys/example_test.go

Adding requested samples 
Closes https://github.com/Azure/azure-sdk-for-go/issues/22475

[keyvault] add more samples

---

sdk/messaging/azeventhubs/checkpoints/blob_store_test.go
sdk/messaging/azeventhubs/consumer_client_internal_test.go
sdk/messaging/azeventhubs/consumer_client_test.go
sdk/messaging/azeventhubs/example_consuming_with_checkpoints_test.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/batch_stress_tester.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/shared.go
sdk/messaging/azeventhubs/internal/links_test.go
sdk/messaging/azeventhubs/internal/rpc.go
sdk/messaging/azeventhubs/internal/test/test_helpers.go
sdk/messaging/azeventhubs/main_test.go
sdk/messaging/azeventhubs/processor_load_balancer.go
sdk/messaging/azeventhubs/producer_client.go
sdk/messaging/azservicebus/admin/admin_client_test.go
sdk/messaging/azservicebus/internal/mgmt.go
sdk/messaging/azservicebus/internal/rpc.go
sdk/messaging/azservicebus/internal/stress/tools/create_test_queue.go
sdk/messaging/azservicebus/internal/stress/tools/delete_using_regexp.go
sdk/messaging/azservicebus/internal/test/test_helpers.go
sdk/messaging/azservicebus/message.go

Catching up on some cleanup:
- gocritic is finding some good things that needed to be fixed.
- Swap over to Charles' test credential.

[azservicebus,azeventhubs] Fix lint issues that are breaking pipelines.

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/version.go

Copying content from the v1.7.0 release branch

Update azidentity changelog

---

sdk/messaging/azservicebus/env.ps1
sdk/messaging/azservicebus/example_client_autoRenewLocks_test.go
sdk/messaging/azservicebus/receiver2_test.go

Just a simple example for people that want to write their own renewer.
Also, for convenience, adding in a .ps1 file to generate the .env file if you already have a resource set up.
Fixes #20857

[azservicebus] Adding in an example of how you could write your own lock renewer

---

sdk/azcore/CHANGELOG.md
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/internal/shared/constants.go
sdk/azcore/testdata/perf/go.mod
sdk/azcore/testdata/perf/go.sum

Includes the NewRequestForRequest change, go get -u all, and go mod tidy (also for perf tests)

[azcore] prepping for release

---

sdk/azidentity/device_code_credential.go
sdk/azidentity/interactive_browser_credential.go

Update user credential ClientID docs

---

sdk/azidentity/TOKEN_CACHING.MD
sdk/azidentity/device_code_credential.go
sdk/azidentity/example_user_auth_test.go
sdk/azidentity/interactive_browser_credential.go

Rewriting TOKEN_CACHING.md in light of recent API changes. Closes #23180

Update token caching docs

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/internal/exported/version.go
sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/internal/exported/version.go

AzCore version refresh to the latest version has already been done before this PR and merged to main. 

[Storage] [Blob, Files] Prep for STG 93 GA release

---

sdk/azidentity/go.mod
sdk/azidentity/go.sum

azidentity references `cache` only in examples

Upgrade azidentity's cache dependency

---

sdk/resourcemanager/network/armnetwork/assets.json
sdk/resourcemanager/network/armnetwork/fake_example_test.go
sdk/resourcemanager/resources/armdeploymentscripts/assets.json
sdk/resourcemanager/resources/armdeploymentscripts/deploymentscripts_client_live_test.go
sdk/resourcemanager/resources/armdeploymentscripts/go.mod
sdk/resourcemanager/resources/armdeploymentscripts/go.sum

fix: https://github.com/Azure/azure-sdk-for-go/issues/23201

fix armdeploymentscripts and armnetwork record test

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/go.mod
sdk/storage/azdatalake/go.sum
sdk/storage/azdatalake/internal/exported/version.go

Version refreshes for stg93 GA azdatalake release

---

sdk/resourcemanager/containerservice/armcontainerservice/fake_example_test.go
sdk/resourcemanager/marketplaceordering/armmarketplaceordering/fake_example_test.go
sdk/resourcemanager/monitor/armmonitor/fake_example_test.go
sdk/resourcemanager/network/armnetwork/fake_example_test.go
sdk/resourcemanager/resourcegraph/armresourcegraph/fake_example_test.go
sdk/resourcemanager/resources/armresources/fake_example_test.go
sdk/resourcemanager/resources/armsubscriptions/fake_example_test.go

Clean up lint in fakes examples

---

sdk/azidentity/example_redis_test.go
sdk/azidentity/go.mod
sdk/azidentity/go.sum

Add go-redis authentication sample

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go

Prep azcore 1.14.0 for release

---

sdk/storage/azfile/assets.json
sdk/storage/azfile/share/client_test.go

Added AuthenticationErrorDetail

---

sdk/storage/azqueue/internal/shared/challenge_policy_test.go

Added challenge_policy_test.go

---

.github/CODEOWNERS

Updating CODEOWNERS to reflect changes

Cosmos DB: Update CODEOWNERS

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/go.mod
sdk/storage/azdatalake/go.sum
sdk/storage/azdatalake/internal/exported/version.go

storage stg94 preview adls

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/version.go

[Cosmos] versions upgrade for release

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/internal/exported/version.go
sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/internal/exported/version.go

[Storage] Prep for release - Changelog changes for blob and files release

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/go.mod
sdk/storage/azdatalake/go.sum
sdk/storage/azdatalake/internal/exported/version.go

- [] Tests are included and/or updated for code changes.

[Storage] stg94 Adls release

---

.github/CODEOWNERS

This PR is to update the code owner to remove Ray from the list.
I did a full search and those seems to be the only place to update.

Update the code owner to remove Ray from the list.

---

sdk/resourcemanager/servicenetworking/armservicenetworking/CHANGELOG.md
sdk/resourcemanager/servicenetworking/armservicenetworking/associationsinterface_client_example_test.go
sdk/resourcemanager/servicenetworking/armservicenetworking/autorest.md
sdk/resourcemanager/servicenetworking/armservicenetworking/constants.go
sdk/resourcemanager/servicenetworking/armservicenetworking/fake/securitypoliciesinterface_server.go
sdk/resourcemanager/servicenetworking/armservicenetworking/frontendsinterface_client_example_test.go
sdk/resourcemanager/servicenetworking/armservicenetworking/operations_client_example_test.go
sdk/resourcemanager/servicenetworking/armservicenetworking/securitypoliciesinterface_client.go
sdk/resourcemanager/servicenetworking/armservicenetworking/securitypoliciesinterface_client_example_test.go
sdk/resourcemanager/servicenetworking/armservicenetworking/trafficcontrollerinterface_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/5340

[Release] sdk/resourcemanager/servicenetworking/armservicenetworking/1.1.0-beta.2

---

sdk/ai/azopenai/client_shared_test.go

Azure OpenAI does requests on our behalf. If those fail then the error returned to us is a 400, not a 429.
This only affects us in tests as we care about this particular state for purposes of skipping tests when resources are oversubscribed.

Expand the error checking to also accomodate when the underlying OYD is throttling

---

eng/tools/generator/cmd/v2/common/cmdProcessor.go

change filtering words for typespec mpg tool

---

sdk/resourcemanager/avs/armavs/CHANGELOG.md
sdk/resourcemanager/avs/armavs/addons_client_example_test.go
sdk/resourcemanager/avs/armavs/authorizations_client_example_test.go
sdk/resourcemanager/avs/armavs/autorest.md
sdk/resourcemanager/avs/armavs/cloudlinks_client_example_test.go
sdk/resourcemanager/avs/armavs/clusters_client_example_test.go
sdk/resourcemanager/avs/armavs/constants.go
sdk/resourcemanager/avs/armavs/datastores_client_example_test.go
sdk/resourcemanager/avs/armavs/globalreachconnections_client_example_test.go
sdk/resourcemanager/avs/armavs/hcxenterprisesites_client_example_test.go
sdk/resourcemanager/avs/armavs/iscsipaths_client_example_test.go
sdk/resourcemanager/avs/armavs/locations_client_example_test.go
sdk/resourcemanager/avs/armavs/operations_client_example_test.go
sdk/resourcemanager/avs/armavs/placementpolicies_client_example_test.go
sdk/resourcemanager/avs/armavs/privateclouds_client_example_test.go
sdk/resourcemanager/avs/armavs/scriptcmdlets_client_example_test.go
sdk/resourcemanager/avs/armavs/scriptexecutions_client_example_test.go
sdk/resourcemanager/avs/armavs/scriptpackages_client_example_test.go
sdk/resourcemanager/avs/armavs/virtualmachines_client_example_test.go
sdk/resourcemanager/avs/armavs/workloadnetworks_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/5188

[Release] sdk/resourcemanager/avs/armavs/2.0.0

---

sdk/resourcemanager/computeschedule/armcomputeschedule/README.md

from service ask: https://github.com/Azure/sdk-release-request/issues/5495#issuecomment-2381137915

update armcomputeschedule readme

---

sdk/azcore/CHANGELOG.md
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/testdata/perf/go.mod
sdk/azcore/testdata/perf/go.sum

Update dependencies for azcore

---

sdk/azidentity/TOKEN_CACHING.MD
sdk/azidentity/azidentity.go
sdk/azidentity/azure_pipelines_credential.go
sdk/azidentity/client_assertion_credential.go
sdk/azidentity/client_certificate_credential.go
sdk/azidentity/client_secret_credential.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/example_persistent_cache_sp_test.go
sdk/azidentity/example_persistent_cache_user_test.go
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/internal/cache.go
sdk/azidentity/username_password_credential.go
sdk/azidentity/workload_identity.go

Documenting service principal credential types, clarifying, linking to stable docs

Update persistent token caching docs

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/share/client_test.go
sdk/storage/azfile/share/models.go

Premium Files – Paid Burst IOPS/Bandwidth  

---

.github/CODEOWNERS

I no longer work on the Azure AI Search team, so I'm removing myself from CODEOWNERS to stop having issues @-mention me.
- [n/a] Tests are included and/or updated for code changes.
- [n/a] Updates to module CHANGELOG.md are included.
- [n/a] MIT license headers are included in each file.

[Search] Remove myself from CODEOWNERS

---

sdk/azcore/CHANGELOG.md

Planned release thwarted by pipeline instability, let's try again Monday

Update azcore v1.15.0 release date

---

sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
sdk/messaging/eventgrid/azsystemevents/models.go
sdk/messaging/eventgrid/azsystemevents/models_serde.go
sdk/messaging/eventgrid/azsystemevents/testdata/tsp-location.yaml

APIView: https://apiview.dev/Assemblies/Review/db71641e728c4b7ba62abe3efde3cf7e/8ee7f0bfd9ec4ca8aa20dd4428211ec3?diffRevisionId=30899c3fdd28463c97343a495a230eea&doc=False&diffOnly=True

[azsystemevents] Updating with latest system event

---

sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/directory/constants.go
sdk/storage/azfile/directory/models.go
sdk/storage/azfile/file/constants.go
sdk/storage/azfile/file/models.go
sdk/storage/azfile/share/constants.go
sdk/storage/azfile/share/models.go

Reverts Azure/azure-sdk-for-go#23607

Revert "Revert "added new tests with recordings""

---

eng/pipelines/templates/steps/analyze.yml

Fix issue in APIView step in the pipeline when source branch name has space.

Update apiview step in pipeline to quote branch name param

---

sdk/resourcemanager/elasticsan/armelasticsan/CHANGELOG.md
sdk/resourcemanager/elasticsan/armelasticsan/autorest.md
sdk/resourcemanager/elasticsan/armelasticsan/constants.go
sdk/resourcemanager/elasticsan/armelasticsan/elasticsans_client.go
sdk/resourcemanager/elasticsan/armelasticsan/elasticsans_client_example_test.go
sdk/resourcemanager/elasticsan/armelasticsan/models.go
sdk/resourcemanager/elasticsan/armelasticsan/models_serde.go
sdk/resourcemanager/elasticsan/armelasticsan/operations_client.go
sdk/resourcemanager/elasticsan/armelasticsan/operations_client_example_test.go
sdk/resourcemanager/elasticsan/armelasticsan/privateendpointconnections_client.go
sdk/resourcemanager/elasticsan/armelasticsan/privateendpointconnections_client_example_test.go
sdk/resourcemanager/elasticsan/armelasticsan/privatelinkresources_client.go
sdk/resourcemanager/elasticsan/armelasticsan/privatelinkresources_client_example_test.go
sdk/resourcemanager/elasticsan/armelasticsan/skus_client.go
sdk/resourcemanager/elasticsan/armelasticsan/skus_client_example_test.go
sdk/resourcemanager/elasticsan/armelasticsan/volumegroups_client.go
sdk/resourcemanager/elasticsan/armelasticsan/volumegroups_client_example_test.go
sdk/resourcemanager/elasticsan/armelasticsan/volumes_client.go
sdk/resourcemanager/elasticsan/armelasticsan/volumes_client_example_test.go
sdk/resourcemanager/elasticsan/armelasticsan/volumesnapshots_client.go
sdk/resourcemanager/elasticsan/armelasticsan/volumesnapshots_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/5599

[Release] sdk/resourcemanager/elasticsan/armelasticsan/1.2.0-beta.1

---

.github/CODEOWNERS

@Pilchie @kirankumarkolli I think it makes sense for me to be a CODEOWNER here. I'm already doing some reviews and am happy to continue doing so given the work I'm already doing on Rust.

Add myself as a CODEOWNER for azcosmos

---

sdk/storage/azdatalake/assets.json
sdk/storage/azdatalake/filesystem/client_test.go
sdk/storage/azdatalake/service/constants.go

[Storage] Fix live tests azdatalake

---

sdk/azidentity/managed_identity_client.go

Improve Service Fabric managed identity error message

---

sdk/azcore/runtime/pager.go
sdk/azcore/runtime/poller.go

Note that Pager[T] and Poller[T] methods are not goroutine safe.

Add some doc comments

---

sdk/security/keyvault/azadmin/CHANGELOG.md

update date to today for release

release azadmin

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/share/client_test.go
sdk/storage/azfile/share/constants.go

Add Premium access tier to Files Shares

---

eng/emitter-package-lock.json
eng/emitter-package.json

upgrade typesspec-go version in config

upgrade typesspec-go

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/version.go

Updates changelog and version number for 1.2.0 release.

Cosmos: update for 1.2.0 release

---

eng/tools/generator/cmd/v2/common/cmdProcessor.go

to be compatible with different kinds of `tsp-client` output.

refine typespec release tool

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/internal/exported/version.go
sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/internal/exported/version.go
sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/internal/exported/version.go

[Storage] Prep for stg 95 GA release

---

eng/tools/generator/template/rpName/packageName/README.md.tpl
eng/tools/generator/template/typespec/README.md.tpl

modified: eng/tools/generator/template/rpName/packageName/README.md.tpl
modified: eng/tools/generator/template/typespec/README.md.tpl

update readme - remove pkg.go.dev check

---

.github/CODEOWNERS
eng/emitter-package-lock.json
eng/emitter-package.json

bump to typespec-go 0.3.3

---

sdk/resourcemanager/resources/armresources/cae_mock_test.go

resolve: https://github.com/Azure/azure-sdk-for-go/issues/23751

add cae support mock test for mgmt. library

---

eng/emitter-package-lock.json
eng/emitter-package.json

bump to typespec-go 0.3.4

---

sdk/storage/azfile/assets.json
sdk/storage/azfile/fileerror/error_codes.go
sdk/storage/azfile/share/client_test.go

Add error code in azfile error codes.go

---

eng/emitter-package-lock.json
eng/emitter-package.json

resolve: https://github.com/Azure/azure-sdk-for-go/issues/23873

bump to @azure-tools/typespec-go 0.3.5

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/internal/exported/version.go
sdk/storage/azdatalake/internal/testcommon/clients_auth.go

Adls sas url from user delegation key

---

eng/tools/generator/go.mod
eng/tools/generator/go.sum

missing from: https://github.com/Azure/azure-sdk-for-go/pull/23916

update sdk automation tool dependency

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/share/client_test.go
sdk/storage/azfile/share/models.go

[AzFiles] Provisioned v2 billing model

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/internal/exported/version.go
sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/internal/exported/version.go

This is for Blobs and files only. Another PR will be made for Datalake after changing Blob dependencies

Changelog and version upgrades for stg 96 preview

---

sdk/samples/fakes/examples_test.go
sdk/samples/fakes/go.mod
sdk/samples/fakes/go.sum

This was the only one that needed tidying.

Go mod tidy all SDKs

---

sdk/containers/azcontainerregistry/README.md
sdk/data/azcosmos/README.md
sdk/messaging/azeventhubs/README.md
sdk/messaging/azservicebus/README.md
sdk/messaging/azwebpubsub/README.md
sdk/messaging/eventgrid/azeventgrid/README.md
sdk/messaging/eventgrid/azsystemevents/README.md
sdk/security/keyvault/azadmin/README.md
sdk/security/keyvault/azcertificates/README.md
sdk/security/keyvault/azkeys/README.md
sdk/security/keyvault/azsecrets/README.md
sdk/storage/azdatalake/README.md
sdk/storage/azfile/README.md
sdk/storage/azqueue/README.md
sdk/template/aztemplate/README.md

Updated README url references of `docs.microsoft.com` to `learn.microsoft.com`

Updating README references of docs.microsoft.com to learn.microsoft.com

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/go.mod
sdk/storage/azdatalake/go.sum
sdk/storage/azdatalake/internal/exported/version.go

Release storage stg96 azdatalake preview

---

sdk/ai/azopenai/assets.json
sdk/ai/azopenai/client_chat_completions_test.go
sdk/ai/azopenai/client_shared_test.go
sdk/ai/azopenai/example_client_getchatcompletions_vision_test.go

This PR fixes some issues with failing tests in the `azopenai` package due to changes in the service.

[azopenai] Fixing failing tests

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
sdk/containers/azcontainerregistry/ci.yml
sdk/messaging/azeventhubs/ci.yml
sdk/messaging/azservicebus/ci.yml
sdk/security/keyvault/azkeys/ci.yml

Remove sovereign cloud testing references

Remove sovereign cloud testing references

---

sdk/storage/azblob/blob/client_test.go

Update duplicate test name

---

sdk/messaging/azeventhubs/test-resources.bicep

Also, a little cleanup to remove the IOT endpoint, which wasn't being used in our tests.

[azeventhubs] Fixing bicep to remove shared key/connection string auth

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/internal/exported/version.go
sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/internal/exported/version.go

[Storage] Prep for blob and files STG96 GA release

---

.github/CODEOWNERS

add jiaqi to mpg code owner list

---

eng/emitter-package-lock.json
eng/emitter-package.json

upgrade emitter version

---

eng/emitter-package-lock.json
eng/emitter-package.json

Upgrade tcgc version

---

.github/CODEOWNERS
.github/CODEOWNERS_baseline_errors.txt

Fixup a couple references and remove two exclusions that are now fixed

CodeOwner fixes

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/datalakeerror/error_codes.go
sdk/storage/azdatalake/directory/client_test.go
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/go.mod
sdk/storage/azdatalake/go.sum
sdk/storage/azdatalake/internal/exported/version.go

Prep for GA release - azdatalake

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/client.go
sdk/messaging/azservicebus/client_test.go
sdk/messaging/azservicebus/example_client_test.go
sdk/messaging/azservicebus/internal/constants.go

No other beta features are making it through to this release, as they aren't quite ready.

[azservicebus] Prepping for v1.8.0, releasing CustomEndpoint feature

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/directory/examples_test.go
sdk/storage/azfile/directory/models.go
sdk/storage/azfile/file/client.go
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/file/constants.go
sdk/storage/azfile/file/examples_test.go
sdk/storage/azfile/file/models.go
sdk/storage/azfile/file/responses.go
sdk/storage/azfile/internal/exported/file_permissions.go
sdk/storage/azfile/internal/exported/smb_property.go
sdk/storage/azfile/internal/testcommon/clients_auth.go
sdk/storage/azfile/service/client_test.go

[Storage] [AzFile] NFS over REST STG 97

---

sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/file/constants.go
sdk/storage/azfile/internal/exported/version.go
sdk/storage/azfile/internal/generated/autorest.md
sdk/storage/azfile/internal/generated/zz_constants.go
sdk/storage/azfile/internal/generated/zz_directory_client.go
sdk/storage/azfile/internal/generated/zz_file_client.go
sdk/storage/azfile/internal/generated/zz_options.go
sdk/storage/azfile/internal/generated/zz_response_types.go

Case change for NFSFileType

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azfile/CHANGELOG.md

[Storage] Prep for release stg97 - Blob and Files

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/go.mod
sdk/storage/azdatalake/go.sum

[Storage] Prep for azdatalake preview

---

sdk/data/aztables/entity.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/24109

Improve docs for EDMEntity properties

---

sdk/resourcemanager/logz/armlogz/CHANGELOG.md
sdk/resourcemanager/logz/armlogz/README.md
sdk/resourcemanager/logz/armlogz/autorest.md
sdk/resourcemanager/logz/armlogz/constants.go
sdk/resourcemanager/logz/armlogz/go.mod

resolve: https://github.com/Azure/azure-sdk-for-go/issues/24117

Deprecated sdk/resourcemanager/logz/armlogz

---

eng/tools/generator/cmd/v2/automation/automationCmd.go
eng/tools/generator/cmd/v2/common/changelogProcessor.go
eng/tools/generator/cmd/v2/common/constants.go
eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/fileProcessor_test.go
eng/tools/generator/cmd/v2/common/generation.go
eng/tools/generator/cmd/v2/release/releaseCmd.go
eng/tools/generator/config/typespecRequests.go
eng/tools/generator/config/validate/localValidator.go
eng/tools/generator/template/typespec/CHANGELOG.md.tpl
eng/tools/generator/template/typespec/README.md.tpl
eng/tools/generator/template/typespec/ci.yml.tpl
eng/tools/generator/template/typespec/go.mod.tpl
eng/tools/generator/typespec/tspconfig.go
eng/tools/generator/typespec/tspconfig_test.go
eng/tools/generator/typespec/typespec-go.go
eng/tools/generator/typespec/typespec-go_test.go

1. do not throw error is no exports found
2. support sub package generation

generator support sub package

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/README.md
sdk/azidentity/environment_credential.go
sdk/azidentity/username_password_credential.go

Closes https://github.com/Azure/azure-sdk-for-go-pr/issues/46

Deprecate UsernamePasswordCredential

---

eng/emitter-package-lock.json
eng/emitter-package.json

Upgrade emitter-package version

Upgrade emitter-package version

---

eng/tools/generator/cmd/v2/common/cmdProcessor.go

ignore warning messages to avoid breaking generator

fix generator error

---

eng/tools/generator/cmd/v2/common/cmdProcessor.go
eng/tools/generator/generatedInput.json

when detect generated successfully flag, ignore err message directly
related pr: https://github.com/Azure/azure-rest-api-specs-pr/pull/21606

ignore codegen warning message

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/internal/constants.go
sdk/messaging/azeventhubs/internal/links.go
sdk/messaging/azeventhubs/internal/links_unit_test.go

[azeventhubs] Fixed bug where AMQP sessions weren't being closed.

---

eng/pipelines/templates/steps/analyze.yml

Don't run apiview for eng changes
CC @JiaqiZhang-Dev

Don't run apiview for eng changes

---

eng/pipelines/templates/steps/analyze.yml

I'm not sure how but it seems this has been breaking main. Reverting while I figure out a fix.
CC @RickWinter

Revert "Don't run apiview for eng changes"

---

documentation/deprecation_guide.md

Instructions on how to deprecate a module in our repo.

[docs] module deprecation guide

---

eng/emitter-package-lock.json
eng/emitter-package.json

upgrade codegen version

---

sdk/ai/azopenai/client_extra_unit_test.go

Add unit tests for client extra functions

---

eng/pipelines/templates/steps/analyze.yml

- Ensure that step runs
- Should resolve https://github.com/Azure/azure-sdk-for-go/issues/24257

Ensure Create Go APIView Artifact Runs

---

sdk/security/keyvault/azcertificates/assets.json
sdk/security/keyvault/azcertificates/client_test.go

updating tests to fix pipeline failures

[azcertificates] fix tests

---

eng/pipelines/templates/steps/analyze.yml

Skip apireview creation on main scheduled+ci pipelines for non-sdk changes

Skip apireview creation on main scheduled+ci pipelines for non-sdk changes

---

sdk/ai/azopenai/client_custom_files_test.go

Adding test cases for custom files.

adding test cases for custom files

---

sdk/ai/azopenaiextensions/example_azure_content_filtering_test.go

Add content filtering sample

---

sdk/ai/azopenai/testdata/package-lock.json
sdk/ai/azopenai/testdata/package.json
sdk/ai/azopenaiassistants/testdata/package-lock.json
sdk/ai/azopenaiassistants/testdata/package.json

There are some generation differences that need to get looked at. Filed that follow-on work as #24313

[azopenai/azopenaiassistants] Updating our dependencies to move past a security issue.

---

sdk/ai/azopenaiextensions/build.go
sdk/ai/azopenaiextensions/client_assistants_test.go
sdk/ai/azopenaiextensions/client_audio_test.go
sdk/ai/azopenaiextensions/client_chat_completions_extensions_test.go
sdk/ai/azopenaiextensions/client_chat_completions_test.go
sdk/ai/azopenaiextensions/client_completions_test.go
sdk/ai/azopenaiextensions/client_embeddings_test.go
sdk/ai/azopenaiextensions/client_functions_test.go
sdk/ai/azopenaiextensions/client_rai_test.go
sdk/ai/azopenaiextensions/client_shared_test.go
sdk/ai/azopenaiextensions/constants.go
sdk/ai/azopenaiextensions/custom_client_image_test.go
sdk/ai/azopenaiextensions/custom_errors.go
sdk/ai/azopenaiextensions/custom_errors_test.go
sdk/ai/azopenaiextensions/custom_models.go
sdk/ai/azopenaiextensions/example_azure_content_filtering_test.go
sdk/ai/azopenaiextensions/example_azure_on_your_data_test.go
sdk/ai/azopenaiextensions/go.mod
sdk/ai/azopenaiextensions/go.sum
sdk/ai/azopenaiextensions/helpers_requests.go
sdk/ai/azopenaiextensions/helpers_responses.go
sdk/ai/azopenaiextensions/interfaces.go
sdk/ai/azopenaiextensions/internal/check_generation_test.go
sdk/ai/azopenaiextensions/models.go
sdk/ai/azopenaiextensions/models_serde.go
sdk/ai/azopenaiextensions/polymorphic_helpers.go
sdk/ai/azopenaiextensions/time_unix.go

[azopenaiextensions] Updating package to target  openai-go/v0.1.0-beta.2.

---

.vscode/cspell.json

Ignore cspell warnings for eng

Ignore cspell warnings for eng

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity.go
sdk/azidentity/azidentity_test.go
sdk/azidentity/cache/go.mod
sdk/azidentity/cache/go.sum
sdk/azidentity/confidential_client.go
sdk/azidentity/go.mod
sdk/azidentity/go.sum
sdk/azidentity/managed_identity_client.go
sdk/azidentity/public_client.go
sdk/azidentity/testdata/managed-id-test/go.mod
sdk/azidentity/testdata/managed-id-test/go.sum

azidentity sets AccessToken.RefreshOn

---

eng/pipelines/templates/steps/analyze.yml
eng/scripts/Language-Settings.ps1

[Discovered in azidentity](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4721711&view=results)

Resolve crashes in `analyze`

---

eng/scripts/Build_Perf.ps1

Just need to ensure that we handle the filter string using our common functionality.

Fix Perf Test Invocation (during Federated Auth)

---

sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/constants.go
sdk/storage/azblob/internal/generated/zz_appendblob_client.go
sdk/storage/azblob/internal/generated/zz_blob_client.go
sdk/storage/azblob/internal/generated/zz_blockblob_client.go
sdk/storage/azblob/internal/generated/zz_constants.go
sdk/storage/azblob/internal/generated/zz_container_client.go
sdk/storage/azblob/internal/generated/zz_options.go
sdk/storage/azblob/internal/generated/zz_pageblob_client.go
sdk/storage/azblob/internal/generated/zz_service_client.go
sdk/storage/azdatalake/internal/generated/autorest.md
sdk/storage/azdatalake/internal/generated/constants.go
sdk/storage/azdatalake/internal/generated/zz_filesystem_client.go
sdk/storage/azdatalake/internal/generated/zz_path_client.go
sdk/storage/azdatalake/internal/generated/zz_service_client.go
sdk/storage/azfile/go.mod
sdk/storage/azfile/go.sum
sdk/storage/azfile/internal/generated/autorest.md
sdk/storage/azfile/internal/generated/constants.go
sdk/storage/azfile/internal/generated/zz_directory_client.go
sdk/storage/azfile/internal/generated/zz_file_client.go
sdk/storage/azfile/internal/generated/zz_service_client.go
sdk/storage/azfile/internal/generated/zz_share_client.go

[Storage] Swagger updates stg 98

---

eng/scripts/Language-Settings.ps1

resolve pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4731786&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c

fix eng scripts

---

sdk/resourcemanager/storage/armstorage/CHANGELOG.md
sdk/resourcemanager/storage/armstorage/accounts_client.go
sdk/resourcemanager/storage/armstorage/accounts_client_example_test.go
sdk/resourcemanager/storage/armstorage/autorest.md
sdk/resourcemanager/storage/armstorage/blobcontainers_client_example_test.go
sdk/resourcemanager/storage/armstorage/blobinventorypolicies_client_example_test.go
sdk/resourcemanager/storage/armstorage/blobservices_client_example_test.go
sdk/resourcemanager/storage/armstorage/constants.go
sdk/resourcemanager/storage/armstorage/deletedaccounts_client_example_test.go
sdk/resourcemanager/storage/armstorage/encryptionscopes_client_example_test.go
sdk/resourcemanager/storage/armstorage/fileservices_client_example_test.go
sdk/resourcemanager/storage/armstorage/fileshares_client_example_test.go
sdk/resourcemanager/storage/armstorage/localusers_client_example_test.go
sdk/resourcemanager/storage/armstorage/managementpolicies_client_example_test.go
sdk/resourcemanager/storage/armstorage/models.go
sdk/resourcemanager/storage/armstorage/networksecurityperimeterconfigurations_client_example_test.go
sdk/resourcemanager/storage/armstorage/objectreplicationpolicies_client_example_test.go
sdk/resourcemanager/storage/armstorage/operations_client_example_test.go
sdk/resourcemanager/storage/armstorage/options.go
sdk/resourcemanager/storage/armstorage/privateendpointconnections_client_example_test.go
sdk/resourcemanager/storage/armstorage/privatelinkresources_client_example_test.go
sdk/resourcemanager/storage/armstorage/queue_client_example_test.go
sdk/resourcemanager/storage/armstorage/queueservices_client_example_test.go
sdk/resourcemanager/storage/armstorage/skus_client_example_test.go
sdk/resourcemanager/storage/armstorage/table_client_example_test.go
sdk/resourcemanager/storage/armstorage/tableservices_client_example_test.go
sdk/resourcemanager/storage/armstorage/taskassignmentinstancesreport_client_example_test.go
sdk/resourcemanager/storage/armstorage/taskassignments_client_example_test.go
sdk/resourcemanager/storage/armstorage/taskassignmentsinstancesreport_client_example_test.go
sdk/resourcemanager/storage/armstorage/usages_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/5997

[Release] sdk/resourcemanager/storage/armstorage/1.8.0

---

eng/swagger_to_sdk_config.json

Add stdout settings so that the errors can be displayed in the new pipelines.

add script error config

---

sdk/resourcemanager/standbypool/armstandbypool/CHANGELOG.md
sdk/resourcemanager/standbypool/armstandbypool/README.md
sdk/resourcemanager/standbypool/armstandbypool/constants.go
sdk/resourcemanager/standbypool/armstandbypool/fake/internal.go
sdk/resourcemanager/standbypool/armstandbypool/fake/operations_server.go
sdk/resourcemanager/standbypool/armstandbypool/fake/standbycontainergrouppoolruntimeviews_server.go
sdk/resourcemanager/standbypool/armstandbypool/fake/standbycontainergrouppools_server.go
sdk/resourcemanager/standbypool/armstandbypool/fake/standbyvirtualmachinepoolruntimeviews_server.go
sdk/resourcemanager/standbypool/armstandbypool/fake/standbyvirtualmachinepools_server.go
sdk/resourcemanager/standbypool/armstandbypool/fake/standbyvirtualmachines_server.go
sdk/resourcemanager/standbypool/armstandbypool/go.mod
sdk/resourcemanager/standbypool/armstandbypool/models.go
sdk/resourcemanager/standbypool/armstandbypool/models_serde.go
sdk/resourcemanager/standbypool/armstandbypool/operations_client.go
sdk/resourcemanager/standbypool/armstandbypool/operations_client_example_test.go
sdk/resourcemanager/standbypool/armstandbypool/standbycontainergrouppoolruntimeviews_client.go
sdk/resourcemanager/standbypool/armstandbypool/standbycontainergrouppoolruntimeviews_client_example_test.go
sdk/resourcemanager/standbypool/armstandbypool/standbycontainergrouppools_client.go
sdk/resourcemanager/standbypool/armstandbypool/standbycontainergrouppools_client_example_test.go
sdk/resourcemanager/standbypool/armstandbypool/standbyvirtualmachinepoolruntimeviews_client.go
sdk/resourcemanager/standbypool/armstandbypool/standbyvirtualmachinepoolruntimeviews_client_example_test.go
sdk/resourcemanager/standbypool/armstandbypool/standbyvirtualmachinepools_client.go
sdk/resourcemanager/standbypool/armstandbypool/standbyvirtualmachinepools_client_example_test.go
sdk/resourcemanager/standbypool/armstandbypool/standbyvirtualmachines_client.go
sdk/resourcemanager/standbypool/armstandbypool/standbyvirtualmachines_client_example_test.go
sdk/resourcemanager/standbypool/armstandbypool/tsp-location.yaml

https://github.com/Azure/sdk-release-request/issues/5969

[Release] sdk/resourcemanager/standbypool/armstandbypool/2.0.0

---

sdk/ai/azopenai/MIGRATION.md

Improving migration guide intro.

---

sdk/data/aztables/testdata/perf/go.mod
sdk/data/aztables/testdata/perf/go.sum
sdk/storage/azblob/testdata/perf/go.mod
sdk/storage/azblob/testdata/perf/go.sum

Go mod tidy perf tests

---

eng/pipelines/templates/steps/sparse-checkout-for-servicedirectory.yml

Fix link verification in analyze step

---

eng/tools/generator/cmd/v2/common/generation.go

resolve: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4789378&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=321

fix unreleased merged pr 

---

eng/tools/generator/cmd/v2/common/changelogProcessor.go

print error body of fetching release tags

---

sdk/resourcemanager/servicenetworking/armservicenetworking/CHANGELOG.md
sdk/resourcemanager/servicenetworking/armservicenetworking/associationsinterface_client.go
sdk/resourcemanager/servicenetworking/armservicenetworking/associationsinterface_client_example_test.go
sdk/resourcemanager/servicenetworking/armservicenetworking/constants.go
sdk/resourcemanager/servicenetworking/armservicenetworking/frontendsinterface_client.go
sdk/resourcemanager/servicenetworking/armservicenetworking/frontendsinterface_client_example_test.go
sdk/resourcemanager/servicenetworking/armservicenetworking/models.go
sdk/resourcemanager/servicenetworking/armservicenetworking/models_serde.go
sdk/resourcemanager/servicenetworking/armservicenetworking/operations_client.go
sdk/resourcemanager/servicenetworking/armservicenetworking/operations_client_example_test.go
sdk/resourcemanager/servicenetworking/armservicenetworking/securitypoliciesinterface_client.go
sdk/resourcemanager/servicenetworking/armservicenetworking/securitypoliciesinterface_client_example_test.go
sdk/resourcemanager/servicenetworking/armservicenetworking/trafficcontrollerinterface_client.go
sdk/resourcemanager/servicenetworking/armservicenetworking/trafficcontrollerinterface_client_example_test.go
sdk/resourcemanager/servicenetworking/armservicenetworking/tsp-location.yaml

https://github.com/Azure/sdk-release-request/issues/6095

[Release] sdk/resourcemanager/servicenetworking/armservicenetworking/1.2.0-beta.1

---

sdk/ai/azopenai/MIGRATION.md
sdk/ai/azopenai/example_createimage_test.go

Add more migration scenarios

---

sdk/ai/azopenai/CHANGELOG.md
sdk/ai/azopenai/example_responses_api_test.go

Add responses API samples

---

eng/emitter-package-lock.json
eng/emitter-package.json

updating the typespec emitter to use latest version

upgrade emitter

---

sdk/azidentity/TOKEN_CACHING.MD
sdk/azidentity/TROUBLESHOOTING.md
sdk/azidentity/environment_credential.go
sdk/azidentity/errors.go

Keeping docs on the type itself but removing references from other docs. Closes #23612

Remove doc references to UsernamePasswordCredential

---

eng/scripts/automation_init.sh

Do not use sudo for npm install in typespec automation init

Do not use sudo for npm install in typespec automation init

---

eng/scripts/automation_init.sh

upgrade tsp-client version

---

sdk/batch/azbatch/ci.yml

Our test subscription has a higher core quota in brazilsouth

Change azbatch live test region

---

sdk/storage/azfile/CHANGELOG.md

[Release] [Storage] Prep for stg98 preview release - files

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/appendblob/models.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blob/constants.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/blockblob/models.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azblob/pageblob/models.go

[Release] [Storage] Apiview comments resolve - azblob + prep for release

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/default_azure_credential.go
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/version.go

This lets applications select a subset of the default chain

DefaultAzureCredential reads AZURE_TOKEN_CREDENTIALS

---

eng/tools/generator/cmd/v2/automation/automationCmd.go

skip generate example for swagger

---

eng/common/TestResources/TestResources-Helpers.ps1
sdk/resourcemanager/appplatform/armappplatform/CHANGELOG.md
sdk/resourcemanager/appplatform/armappplatform/README.md
sdk/resourcemanager/appplatform/armappplatform/autorest.md
sdk/resourcemanager/appplatform/armappplatform/constants.go
sdk/resourcemanager/appplatform/armappplatform/go.mod

add deprecated note

---

eng/emitter-package-lock.json
eng/emitter-package.json
eng/tools/generator/cmd/v2/common/generation.go

only upgrade direct dependency & upgrade arm

---

eng/scripts/build.ps1

fix pipeline failures: 
https://dev.azure.com/azure-sdk/public/_build/results?buildId=4900858&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692&l=281
https://dev.azure.com/azure-sdk/public/_build/results?buildId=4901278&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692&l=265

only upgrade direct module version

---

eng/emitter-package-lock.json
eng/emitter-package.json

upgrade arm lib version

---

eng/tools/generator/cmd/v2/common/changelogProcessor.go
eng/tools/generator/cmd/v2/common/changelogProcessor_test.go
eng/tools/generator/cmd/v2/common/generation.go

resolve: https://github.com/Azure/azure-sdk-for-go/issues/24516

fix github throttle issue

---

sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/CHANGELOG.md
sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/constants.go
sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/operations_client.go
sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/operations_client_example_test.go
sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/organizations_client.go
sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/organizations_client_example_test.go
sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/tsp-location.yaml

https://github.com/Azure/sdk-release-request/issues/6149

[Release] sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/1.0.0

---

sdk/ai/azopenaiextensions/client_shared_test.go

Disabling live tests.

---

sdk/resourcemanager/containerservice/armcontainerservice/CHANGELOG.md
sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client.go
sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/assets.json
sdk/resourcemanager/containerservice/armcontainerservice/autorest.md
sdk/resourcemanager/containerservice/armcontainerservice/constants.go
sdk/resourcemanager/containerservice/armcontainerservice/machines_client.go
sdk/resourcemanager/containerservice/armcontainerservice/machines_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client.go
sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client.go
sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/models.go
sdk/resourcemanager/containerservice/armcontainerservice/models_serde.go
sdk/resourcemanager/containerservice/armcontainerservice/operations_client.go
sdk/resourcemanager/containerservice/armcontainerservice/operations_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client.go
sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client.go
sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client.go
sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client.go
sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client.go
sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client.go
sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/6269

[Release] sdk/resourcemanager/containerservice/armcontainerservice/7.1.0

---

sdk/ai/azopenai/example_azure_auth_methods_test.go

Add managed identity auth sample

---

eng/pipelines/templates/jobs/archetype-go-release.yml
eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml
eng/pipelines/templates/variables/image.yml

Update pool to azsdk-pool and linux image to ubuntu 24

Update pool to azsdk-pool and linux image to ubuntu 24

---

eng/emitter-package-lock.json

ai's result is not correct from this pr: https://github.com/Azure/azure-sdk-for-go/pull/24830

fix lock file problem

---

eng/pipelines/mgmt-auto-release.yml
eng/pipelines/templates/variables/image.yml
sdk/azidentity/ci.yml
sdk/azidentity/managed-identity-matrix.json

Remove linux next image/pool

---

eng/pipelines/templates/stages/1es-redirect.yml

Update pool for sdl stage

---

eng/emitter-package-lock.json
eng/emitter-package.json

upgrade tcgc

---

eng/emitter-package-lock.json
eng/emitter-package.json

fix: https://github.com/Azure/azure-rest-api-specs/pull/35464/checks?check_run_id=44751339222

revert tcgc version

---

sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
sdk/messaging/eventgrid/azsystemevents/tsp-location.yaml

Note, this is just picking the proper commit, it doesn't actually change any code or code generation at all.

[azsystemevents] Update with latest commit and prep for release. 

---

eng/pipelines/templates/jobs/archetype-go-release.yml
sdk/template/aztemplate/CHANGELOG.md
sdk/template/aztemplate/version.go

The deployment poolname MUST be hardcoded. TIL.

Fix go release pipeline (properly this time)

---

eng/scripts/MgmtTestLib.ps1

solve the installation failure of autorest.gotest: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5031998&view=logs&j=0ab14b9f-e499-56d5-97b1-fd98b70ea339&t=2e9e19b8-1db7-53d9-fe91-457c791ee9df

upgrade autorest.gotest

---

sdk/azcore/policy/policy.go

https://github.com/Azure/azure-sdk-for-go/blob/66275fadd8b6142396c9240592b13217fe434005/sdk/azcore/runtime/policy_retry.go#L43-L44

Correct RetryOptions.RetryDelay documentation

---

eng/pipelines/templates/jobs/archetype-go-release.yml

Fix path to major version mod script

Fix path to major version mod script

---

sdk/resourcemanager/containerservice/armcontainerservice/CHANGELOG.md
sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client.go
sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/assets.json
sdk/resourcemanager/containerservice/armcontainerservice/autorest.md
sdk/resourcemanager/containerservice/armcontainerservice/constants.go
sdk/resourcemanager/containerservice/armcontainerservice/machines_client.go
sdk/resourcemanager/containerservice/armcontainerservice/machines_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client.go
sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client.go
sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/models.go
sdk/resourcemanager/containerservice/armcontainerservice/models_serde.go
sdk/resourcemanager/containerservice/armcontainerservice/operations_client.go
sdk/resourcemanager/containerservice/armcontainerservice/operations_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client.go
sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client.go
sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client.go
sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/responses.go
sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client.go
sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client.go
sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client_example_test.go
sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client.go
sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client_example_test.go

https://github.com/Azure/sdk-release-request/issues/6340

[Release] sdk/resourcemanager/containerservice/armcontainerservice/7.2.0

---

sdk/azidentity/azidentity_test.go
sdk/azidentity/environment_credential_test.go
sdk/azidentity/username_password_credential_test.go

These tests can't pass because our test tenant now requires MFA

Skip live UsernamePasswordCredential tests

---

sdk/storage/azqueue/go.mod
sdk/storage/azqueue/go.sum
sdk/storage/azqueue/queueerror/error_codes.go

Remove import to v1 module

---

sdk/resourcemanager/dashboard/armdashboard/version.go

fix dashboard version

---

eng/scripts/MgmtTestLib.ps1
eng/scripts/build.ps1

Fix the SDK automation failure.

Update codegen version

---

eng/tools/generator/cmd/issue/request/request.go

link in issue changes ,
new example:https://github.com/Azure/sdk-release-request/issues/6478
old example:https://github.com/Azure/sdk-release-request/issues/6473

add parse link key

---

eng/pipelines/templates/jobs/archetype-go-release.yml
eng/pipelines/templates/jobs/archetype-sdk-client.yml
sdk/template/aztemplate/CHANGELOG.md
sdk/template/aztemplate/version.go

Mark a package as released in release plan

Mark package as released for Go

---

sdk/resourcemanager/workloadorchestration/armworkloadorchestration/CHANGELOG.md
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/configtemplates_client.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/configtemplates_client_example_test.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/contexts_client.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/contexts_client_example_test.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/diagnostics_client.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/diagnostics_client_example_test.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/dynamicschemaversions_client.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/configtemplates_server.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/contexts_server.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/diagnostics_server.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/dynamicschemaversions_server.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/schemas_server.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/solutions_server.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/targets_server.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/go.mod
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/go.sum
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/models.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/models_serde.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/schemas_client.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/schemas_client_example_test.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/solutions_client.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/solutions_client_example_test.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/targets_client.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/targets_client_example_test.go
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/tsp-location.yaml
sdk/resourcemanager/workloadorchestration/armworkloadorchestration/version.go

https://github.com/Azure/sdk-release-request/issues/6420#issuecomment-3223368278

[Release] sdk/resourcemanager/workloadorchestration/armworkloadorchestration/0.2.0

---

eng/scripts/build.ps1

resolved issue: https://github.com/Azure/autorest.go/issues/1697
autorest.go changelog:

upgrade autorest.go

---

sdk/resourcemanager/playwrighttesting/armplaywrighttesting/CHANGELOG.md
sdk/resourcemanager/playwrighttesting/armplaywrighttesting/README.md
sdk/resourcemanager/playwrighttesting/armplaywrighttesting/constants.go

Users/gupta kashish/deprecation date update

---

sdk/storage/azblob/internal/generated/constants.go
sdk/storage/azdatalake/internal/generated/autorest.md
sdk/storage/azdatalake/internal/generated/constants.go
sdk/storage/azdatalake/internal/generated/zz_filesystem_client.go
sdk/storage/azdatalake/internal/generated/zz_options.go
sdk/storage/azdatalake/internal/generated/zz_path_client.go
sdk/storage/azdatalake/internal/generated/zz_responses.go
sdk/storage/azdatalake/internal/generated/zz_service_client.go
sdk/storage/azfile/internal/generated/autorest.md
sdk/storage/azfile/internal/generated/constants.go
sdk/storage/azfile/internal/generated/zz_constants.go
sdk/storage/azfile/internal/generated/zz_directory_client.go
sdk/storage/azfile/internal/generated/zz_file_client.go
sdk/storage/azfile/internal/generated/zz_models.go
sdk/storage/azfile/internal/generated/zz_models_serde.go
sdk/storage/azfile/internal/generated/zz_options.go
sdk/storage/azfile/internal/generated/zz_response_types.go
sdk/storage/azfile/internal/generated/zz_service_client.go
sdk/storage/azfile/internal/generated/zz_share_client.go
sdk/storage/azqueue/internal/generated/autorest.md
sdk/storage/azqueue/internal/generated/zz_messageid_client.go
sdk/storage/azqueue/internal/generated/zz_messages_client.go
sdk/storage/azqueue/internal/generated/zz_models.go
sdk/storage/azqueue/internal/generated/zz_models_serde.go
sdk/storage/azqueue/internal/generated/zz_queue_client.go
sdk/storage/azqueue/internal/generated/zz_response_types.go
sdk/storage/azqueue/internal/generated/zz_service_client.go

Swagger updates for Files, DL, Queues

---

sdk/data/azcosmos/CHANGELOG.md

Updating changelog after 1.4.1 release.

Update Changelog After 1.4.1

---

sdk/resourcemanager/mongocluster/armmongocluster/testdata/_metadata.json
sdk/resourcemanager/mongocluster/armmongocluster/tsp-location.yaml

generation for these services which regenerated failed in this pipeline:https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5347370&view=logs&j=c28f120c-e125-5ec5-8d4c-ba1a4d871fcc&t=8400cb88-1923-54fa-d487-70fbfcd5d927

[Release-regeneration] sdk/resourcemanager/mongocluster/armmongocluster

---

sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applications_client_example_test.go
sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/testdata/_metadata.json
sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/tsp-location.yaml

generation for these services which regenerated failed in this pipeline:https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5347370&view=logs&j=c28f120c-e125-5ec5-8d4c-ba1a4d871fcc&t=8400cb88-1923-54fa-d487-70fbfcd5d927

[Release-regeneration] sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters

---

sdk/resourcemanager/servicenetworking/armservicenetworking/testdata/_metadata.json
sdk/resourcemanager/servicenetworking/armservicenetworking/tsp-location.yaml

generation for these services which regenerated failed in this pipeline:https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5347370&view=logs&j=c28f120c-e125-5ec5-8d4c-ba1a4d871fcc&t=8400cb88-1923-54fa-d487-70fbfcd5d927

[Release-regeneration] sdk/resourcemanager/servicenetworking/armservicenetworking

---

.github/CODEOWNERS

Add owner for App Configuration

Add owner for App Configuration
