Azure/azure-sdk-for-go

sdk/messaging/azservicebus/internal/amqpLinks_test.go
sdk/messaging/azservicebus/internal/errors.go
sdk/messaging/azservicebus/internal/errors_test.go
sdk/messaging/azservicebus/internal/go-amqp/conn.go
sdk/messaging/azservicebus/internal/go-amqp/errors.go
sdk/messaging/azservicebus/internal/go-amqp/internal/frames/frames.go
sdk/messaging/azservicebus/internal/go-amqp/link.go
sdk/messaging/azservicebus/internal/go-amqp/link_options.go
sdk/messaging/azservicebus/internal/go-amqp/receiver.go
sdk/messaging/azservicebus/receiver_unit_test.go
sdk/messaging/azservicebus/sender_unit_test.go
sdk/messaging/azservicebus/session_receiver_unit_test.go

Updating our internally vendored go-amqp to `18d378101570d5469d237799a76b77c0bf0c6fe3`
This mostly impacted us because the connection error is no longer a sentinel error.

[azservicebus] Update go-amqp

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/pollers/async/async.go
sdk/azcore/internal/pollers/async/async_test.go
sdk/azcore/internal/pollers/loc/loc.go
sdk/azcore/internal/pollers/loc/loc_test.go

If the initial response contains a provisioning state use it.  This will
prevent extra polling in the case the operation is in a terminal state.

Handle RELO LRO synchronous completion

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/amqp_message.go
sdk/messaging/azservicebus/amqp_message_test.go
sdk/messaging/azservicebus/example_receiver_test.go
sdk/messaging/azservicebus/example_sender_test.go
sdk/messaging/azservicebus/internal/constants.go
sdk/messaging/azservicebus/internal/mgmt.go
sdk/messaging/azservicebus/liveTestHelpers_test.go
sdk/messaging/azservicebus/message.go
sdk/messaging/azservicebus/messageSettler.go
sdk/messaging/azservicebus/message_batch.go
sdk/messaging/azservicebus/receiver.go
sdk/messaging/azservicebus/sender.go
sdk/messaging/azservicebus/sender_test.go

For sending AMQP messages you can use either Sender.SendAMQPMessages() or schedule them using Sender.ScheduleAMQPMessages().
For receiving, each ReceivedMessage now has a RawAMQPMessage property.
I've also added in a way to export the TLS pre-master key so you can easily wireshark and trace the actual AMQP interaction, which can be helpful in validating that things are encoding properly.
Fixes #15260

[azservicebus] Adding in raw AMQP support for sending and receiving messages.

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/amqp_message.go
sdk/messaging/azservicebus/amqp_message_test.go
sdk/messaging/azservicebus/example_receiver_test.go
sdk/messaging/azservicebus/example_sender_test.go
sdk/messaging/azservicebus/message.go
sdk/messaging/azservicebus/message_batch.go
sdk/messaging/azservicebus/sender.go
sdk/messaging/azservicebus/sender_test.go

Some naming changes to be more consistent with other track 2 SDKs as well as the AMQP spec:
- Rename the AMQPMessage to be AMQPAnnotatedMessage (track 2 consistency, also matches terminology in the spec)
- Create an AMQPAnnotatedMessageBody type to house the .Value, .Sequence and .Data fields. This matches more with the logical format of an AMQP message, where the Body is comprised of sections (Data, Value, Sequence), rather than them just being free-floating fields on a message.

[azservicebus] Some naming changes for raw AMQP message support for consistency with other stacks

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

This reverts commit 9ba043237a826b0ee4b6b7be114828416066e878.

Revert "Override live test location default to westus (#18307)"

---

documentation/new-version-quickstart.md
sdk/resourcemanager/compute/armcompute/README.md

The path appears to have changed with https://github.com/Azure-Samples/azure-sdk-for-go-samples/pull/348 and is now
breaking the link verification check in CI. FYI @tadelesh

Fix broken aka links

---

.gitignore
eng/tools/generator/template/rpName/packageName/go.mod.tpl

When onboarding, release tool will use template to generate an empty `go.mod`. Add `azcore` and `azidentity` dep to it to align with this [change](https://github.com/Azure/autorest.go/pull/835).

fix: add azcore and azidentity to the go.mod template

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/internal/amqpLinks.go
sdk/messaging/azservicebus/internal/amqpwrap/amqpwrap.go
sdk/messaging/azservicebus/internal/constants.go
sdk/messaging/azservicebus/receiver.go
sdk/messaging/azservicebus/receiver_unit_test.go

Attempting to shoe-horn the draining of the channel into the same goroutine doesn't work - it leads to a potential race condition or can lead to a blocking condition identified by @franklinkim in #18477.
The simplest fix is just to treat the original goroutine as a cancellable function call and then handle the return value logic inside of the main func instead. This ensures we always drain the 'done' channel, even if we decide to cancel early.
NOTE, this also unearthed a bug where we were sometimes passing (amqp.<type>, nil) instead of (<interface>, nil) in the amqp wrappers. This was fixed, along with the spot that was unintentionally using it even when there was an error.

[azservicebus] Fixing bug where cancelling link creation could leak resources

---

eng/pipelines/templates/steps/analyze.yml
eng/pipelines/templates/steps/build-test.yml

Normally the apiview step goes in the build job in other languages. Go has a combined build/test job, so the step was running multiple times as part of the job matrix. We don't want to fail all test steps if there is an apiview issue, so I'm moving the step into the Analyze job. I also removed the `continueOnError` line, so this will now block release if there is a failure due to lack of approvals.

Move api review step into analyze job. Block on apiview failures/missing approvals

---

sdk/keyvault/azkeys/test-resources-post.ps1

Closes #18289 by copying .NET's test-resources-post script, which prints any error returned by `Export-AzKeyVaultSecurityDomain`.

Log more information when MHSM provisioning fails

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_client.go
sdk/data/azcosmos/cosmos_client_test.go
sdk/data/azcosmos/cosmos_container.go
sdk/data/azcosmos/cosmos_offers.go
sdk/data/azcosmos/cosmos_query.go
sdk/data/azcosmos/cosmos_query_request_options.go
sdk/data/azcosmos/doc.go
sdk/data/azcosmos/emulator_cosmos_query_test.go
sdk/data/azcosmos/example_test.go

Adds support for parametrized queries: https://docs.microsoft.com/azure/cosmos-db/sql/sql-query-parameterized-queries
```
opt := &azcosmos.QueryOptions{
QueryParameters: []azcosmos.QueryParameter{
{"@value", "2"},
},
}
pk := azcosmos.NewPartitionKeyString("newPartitionKey")
queryPager := container.NewQueryItemsPager("select * from docs c where c.value = @value", pk, opt)
```
https://apiview.dev/Assemblies/Review/de637b8db22d4a19ab683fb3104df509/d69766f1fd2e469aa35d8af532c5d67e?diffRevisionId=6fa3698b49974793ac147e714bc5a4e0&doc=False&diffOnly=True
`doc.go` and `examples_test.go` have been updated to cover the support of parametrized queries.
Closes https://github.com/Azure/azure-sdk-for-go/issues/18332

Cosmos DB: Support for parametrized queries

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_paths.go
sdk/data/azcosmos/cosmos_paths_test.go
sdk/data/azcosmos/emulator_cosmos_item_test.go
sdk/data/azcosmos/partition_key.go
sdk/data/azcosmos/shared_key_credential.go
sdk/data/azcosmos/shared_key_credential_test.go

Changes use of `url.QueryEscape` to `url.PathEscape` to support ids with white spaces.
Also adds the same test scenarios as https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3307
One key difference are the `IdWithDisallowedCharForwardSlash` and `IdWithDisallowedCharBackSlash` scenarios that in .NET return: BadRequest and NotFound, but in Go, they return Created and BadRequest.

Cosmos DB: Fixes whitespace and supported special characters handling

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/internal/constants.go
sdk/messaging/azservicebus/internal/go-amqp/link.go
sdk/messaging/azservicebus/internal/go-amqp/manualCreditor.go
sdk/messaging/azservicebus/internal/go-amqp/session.go

Updating to the latest go-amqp (2d5210a953428af866002b3e28061cfa92d471bd), which fixes several bugs which could lead to incorrect message locking and deliveries:
- Requesting large quantities of messages in a single ReceiveMessages() call  could result in messages 
not being delivered, but still incrementing their delivery count and requiring the message lock 
timeout to expire.
- Link detach could result in messages being ignored, requiring the message lock timeout to expire.
In addition this also cleans up an issue where we would send excessive FLOW frames. There was no harm here, but it was unnecessary.

[azservicebus] Updating to latest go-amqp to get fixes around wasted message locking

---

sdk/messaging/azservicebus/internal/amqpLinks.go
sdk/messaging/azservicebus/internal/amqpLinks_test.go
sdk/messaging/azservicebus/internal/amqp_test_utils.go
sdk/messaging/azservicebus/internal/amqpwrap/amqpwrap.go
sdk/messaging/azservicebus/internal/amqpwrap/amqpwrap_test.go
sdk/messaging/azservicebus/internal/namespace.go
sdk/messaging/azservicebus/internal/stress/.helmignore
sdk/messaging/azservicebus/internal/stress/Chart.lock
sdk/messaging/azservicebus/internal/stress/Chart.yaml
sdk/messaging/azservicebus/internal/stress/shared/stress_context.go
sdk/messaging/azservicebus/internal/stress/shared/utils.go
sdk/messaging/azservicebus/internal/stress/tests/send_and_receive drain.go
sdk/messaging/azservicebus/internal/stress/tests/tests.go
sdk/messaging/azservicebus/internal/stress/values.yaml
sdk/messaging/azservicebus/receiver.go
sdk/messaging/azservicebus/receiver_helpers_test.go
sdk/messaging/azservicebus/receiver_test.go
sdk/messaging/azservicebus/receiver_unit_test.go

Changing Receiver.ReceiveMessages() from the existing implementation, which uses AMQP's flow+drain to doing amqp.Release() on messages that arrive when there is not an active listener.
It seems particularly hard for our AMQP stack to properly recover if we drain and then have to cancel, which can happen in some cases where the drain ACK takes a longer time to arrive. Switching over to simply releasing messages when there's not an active ReceiveMessages() call allows us to avoid waiting for the ACK (faster exit) as well as allowing us to keep the link alive for longer, which also avoids some scenarios where the link would get closed.
This change also modifies some stress tests that help demonstrate this problem and show that it now works properly.

[azservicebus] ReceiveMessages() algorithm change to use amqpReceiver.Release() instead of flow+drain

---

sdk/keyvault/azkeys/README.md

This adds back the `goget_azkeys` link reference which seems to have
been accidentally deleted in https://github.com/Azure/azure-sdk-for-go/commit/32be770a92b5199ac7fee8340344d1b7520b8a46,
making the rendered Markdown link clickable again.

Fix broken pkg.go.dev link in azkeys README

---

sdk/resourcemanager/compute/armcompute/CHANGELOG.md
sdk/resourcemanager/compute/armcompute/README.md
sdk/resourcemanager/compute/armcompute/autorest.md
sdk/resourcemanager/compute/armcompute/availabilitysets_client_live_test.go
sdk/resourcemanager/compute/armcompute/constants.go
sdk/resourcemanager/compute/armcompute/go.mod
sdk/resourcemanager/compute/armcompute/go.sum
sdk/resourcemanager/compute/armcompute/testdata/recordings/TestAvailabilitySetsClient.json
sdk/resourcemanager/compute/armcompute/testdata/recordings/TestVirtualMachineScaleSetsClient.json
sdk/resourcemanager/compute/armcompute/testdata/recordings/TestVirtualMachinesClient.json
sdk/resourcemanager/compute/armcompute/virtualmachines_client_live_test.go
sdk/resourcemanager/compute/armcompute/virtualmachinescalesets_client_live_test.go
sdk/resourcemanager/machinelearning/armmachinelearning/README.md
sdk/resourcemanager/mediaservices/armmediaservices/README.md
sdk/resourcemanager/netapp/armnetapp/README.md
sdk/resourcemanager/operationalinsights/armoperationalinsights/README.md
sdk/resourcemanager/securityinsights/armsecurityinsights/README.md
sdk/resourcemanager/servicebus/armservicebus/README.md
sdk/resourcemanager/storagecache/armstoragecache/README.md

Fix: #18706 
Fix wrong major version info in readme.md. For `armcompute`, also fix wrong major module import for live test and release a fix version.

fix: wrong major version in readme file and wrong major version module import in live test

---

README.md

Added a reference to the Microsoft Open Source Code of Conduct in the Contribute section of README.md
Adding this to the README.md to keep this repo in continuity with other Azure SDK repos.

Adding reference to Code of Conduct

---

sdk/keyvault/azkeys/test-resources.json

We've seen a string of deployment failures in live tests due to low MHSM capacity in westus3. The MHSM team has suggested uksouth as a higher capacity region, so let's give that a try.

Deploy live test MHSMs to higher capacity region

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/exported/request.go
sdk/azcore/internal/exported/request_test.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/18809
The unencoded semicolon was reported in https://github.com/Azure/azure-sdk-for-go/issues/15108 and fixed in `go-autorest`.

URL encode query parameters when creating a request

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/admin/admin_client.go
sdk/messaging/azservicebus/admin/admin_client_rules.go
sdk/messaging/azservicebus/admin/admin_client_test.go
sdk/messaging/azservicebus/admin/testdata/emptyrulefeed.json
sdk/messaging/azservicebus/admin/testdata/rulefeed.json
sdk/messaging/azservicebus/amqp_message.go
sdk/messaging/azservicebus/client.go
sdk/messaging/azservicebus/internal/amqpLinks.go
sdk/messaging/azservicebus/internal/atom/entity_manager.go
sdk/messaging/azservicebus/internal/atom/manager_common.go
sdk/messaging/azservicebus/internal/go-amqp/client.go
sdk/messaging/azservicebus/internal/go-amqp/internal/frames/frames.go
sdk/messaging/azservicebus/internal/go-amqp/link_options.go
sdk/messaging/azservicebus/internal/go-amqp/manualCreditor.go
sdk/messaging/azservicebus/internal/test/test_helpers.go

The individual properties for a rule in Service Bus come with an XML ns prefix. We don't actually care about this as we're just trying to figure out what the assigned type is (string, int, etc..) so this just strips out the prefix.
Fixes #18785

[azservicebus] Ignore the leading XMLNS for properties in subscription rules

---

eng/tools/generator/cmd/v2/automation/automationCmd.go

There is some issue for the api view rest api for go. Wait for fix and revert temporarily.

comment api view export temporary

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-eng-client.yml

Remove duplicate manifest publish in pipeline (minor fix for https://github.com/Azure/azure-sdk-for-go/pull/18805) to resolve pipeline failure.

remove duplicate manifest publish in pipeline

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/exported/request.go
sdk/azcore/internal/exported/request_test.go
sdk/azcore/runtime/request.go

Services are expected to return properly encoded URLs in payloads.
Updated doc comment for NewRequest stating the encoding requirement.
Reverts fix made for https://github.com/Azure/azure-sdk-for-go/issues/18809

Revert change for URL encoding query params

---

sdk/keyvault/azcertificates/README.md
sdk/keyvault/azkeys/README.md
sdk/keyvault/azkeys/autorest.md
sdk/keyvault/azkeys/client.go
sdk/keyvault/azkeys/models.go
sdk/keyvault/azsecrets/README.md

Closes #18505 by regenerating `azkeys` and replacing authentication and vault creation instructions with links to more comprehensive docs.

Update Key Vault documentation

---

sdk/keyvault/azcertificates/CHANGELOG.md
sdk/keyvault/azcertificates/custom_client.go
sdk/keyvault/azcertificates/utils_test.go
sdk/keyvault/azcertificates/version.go
sdk/keyvault/azkeys/CHANGELOG.md
sdk/keyvault/azkeys/custom_client.go
sdk/keyvault/azkeys/utils_test.go
sdk/keyvault/azkeys/version.go
sdk/keyvault/azsecrets/CHANGELOG.md
sdk/keyvault/azsecrets/custom_client.go
sdk/keyvault/azsecrets/utils_test.go
sdk/keyvault/azsecrets/version.go

Future features will require client options, so here's a type to hold them.

Add options type for Key Vault clients

---

sdk/storage/azblob/zt_append_blob_client_test.go
sdk/storage/azblob/zt_blob_client_test.go
sdk/storage/azblob/zt_blob_tags_test.go
sdk/storage/azblob/zt_blob_versioning_test.go
sdk/storage/azblob/zt_block_blob_client_test.go
sdk/storage/azblob/zt_client_provided_key_test.go
sdk/storage/azblob/zt_container_client_test.go
sdk/storage/azblob/zt_factory_test.go
sdk/storage/azblob/zt_page_blob_client_test.go
sdk/storage/azblob/zt_test.go

Removed duplicate definition of NopCloser.
Import blocks are properly formatted.

Test cleanup

---

sdk/messaging/azeventhubs/consumer_client.go
sdk/messaging/azeventhubs/consumer_client_test.go
sdk/messaging/azeventhubs/consumer_client_unit_test.go
sdk/messaging/azeventhubs/producer_client.go
sdk/messaging/azeventhubs/producer_client_test.go

Fixing two bugs and adding in some tests:
- When you send a batch of events you can choose to send it to any available partition. I missed a nil check, added in and added a test.
- The offset position filter strings were being incorrectly formatted. It appears that the sequence number one was accepted _anyways_, but I've now fixed it so they're aligned with what JS does.

[azeventhubs] Bug fixes: send to 'any' partition, also offset position strings were incorrect.

---

azure-pipelines.yml

This should hopefully also prevent the legacy CI from triggering when
changes to eng/config.json are made.

Constrain legacy CI to main and legacy branches

---

sdk/storage/azblob/common.go

Added SASQueryParameters and its dependent types so that callers can
create a BlobURLParts type.

Export types needed by BlobURLParts

---

sdk/azidentity/README.md

Related to https://github.com/Azure/azure-sdk-for-go/pull/18807
Add `ClientAssertionCredential` to the library's README

Add ClientAssertionCredential to Azure Identity README

---

sdk/storage/azblob/appendblob/client.go
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/client.go
sdk/storage/azblob/container/client.go
sdk/storage/azblob/container/models.go
sdk/storage/azblob/internal/exported/clients_utils.go
sdk/storage/azblob/pageblob/client.go
sdk/storage/azblob/service/client.go
sdk/storage/azblob/service/models.go
sdk/storage/azblob/testdata/perf/download_blob.go
sdk/storage/azblob/testdata/perf/go.mod
sdk/storage/azblob/testdata/perf/go.sum
sdk/storage/azblob/testdata/perf/list_blobs.go
sdk/storage/azblob/testdata/perf/upload_blob.go

Use the one from azcore instead.

Remove duplicate definition of client options

---

sdk/messaging/azeventhubs/consumer_client.go
sdk/messaging/azeventhubs/consumer_client_unit_test.go

This matches what we've done in other track 2 libraries.

[azeventhubs] Default start position is supposed to be latest, not earliest

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity_test.go
sdk/azidentity/client_certificate_credential.go
sdk/azidentity/client_certificate_credential_test.go
sdk/azidentity/environment_credential_test.go

The `ClientCertificateCredential` API accepts a cert chain but until now MSAL's corresponding API has not, so SNI auth didn't work in all cases. This PR updates `ClientCertificateCredential` to use the latest MSAL, fixing the bug and allowing us to forego some cert parsing and validation that's handled in MSAL now.

Support certificate chains in SNI auth

---

sdk/storage/azblob/appendblob/models.go
sdk/storage/azblob/autorest.md
sdk/storage/azblob/blob/constants.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/blob/utils.go
sdk/storage/azblob/constants.go
sdk/storage/azblob/internal/generated/zz_blob_client.go
sdk/storage/azblob/internal/generated/zz_constants.go
sdk/storage/azblob/internal/generated/zz_container_client.go
sdk/storage/azblob/internal/generated/zz_models.go
sdk/storage/azblob/internal/generated/zz_response_types.go
sdk/storage/azblob/pageblob/constants.go
sdk/storage/azblob/pageblob/models.go
sdk/storage/azblob/service/constants.go
sdk/storage/azblob/zt_client_provided_key_test.go
sdk/storage/azblob/zt_page_blob_client_test.go

Removed stuttering of some constant type names.
Pinned codegen to a specific commit for reproducible builds.
Added directives to export some generated, internal, methods.
Moved hand-edits of generated code elsewhere.

Export constants required by other exported types

---

sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/models.go

This allows the options for each API to independently evolve over time.
Fixed potential panic in some helper methods.

Split buffer and file download options into their own types

---

sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/blob/responses.go
sdk/storage/azblob/blob/retry_reader.go
sdk/storage/azblob/testdata/perf/download_blob.go
sdk/storage/azblob/zt_blob_client_test.go
sdk/storage/azblob/zt_blob_tags_test.go
sdk/storage/azblob/zt_blob_versioning_test.go
sdk/storage/azblob/zt_block_blob_client_test.go
sdk/storage/azblob/zt_client_provided_key_test.go
sdk/storage/azblob/zt_examples_test.go
sdk/storage/azblob/zt_highlevel_test.go
sdk/storage/azblob/zt_test.go

Removed method RetryReader.BodyReader as it's redundant.
Removed duplicate CPK options from RetryReaderOptions.  We now cache the
values used in the DownloadStream API call.
Renamed the fields in RetryReaderOptions to shorten them.
Stop exporting various helper types.

Clean up RetryReader

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_retry.go
sdk/azcore/runtime/policy_retry_test.go
sdk/internal/CHANGELOG.md
sdk/internal/perf/recording.go
sdk/internal/perf/recording_test.go
sdk/internal/recording/recording.go
sdk/internal/recording/recording_test.go

Adjusted the initial retry delay to align with the design guidelines.
Fixed an issue with modifying the original *http.Request that breaks
retries during recording playback.

Various bug fixes for azcore and internal

---

sdk/resourcemanager/internal/CHANGELOG.md
sdk/resourcemanager/internal/testdata/recordings/TestGenerateAlphaNumericID.json
sdk/resourcemanager/internal/testutil/recording.go
sdk/resourcemanager/internal/testutil/recording_test.go
sdk/resourcemanager/internal/version.go

In order to support generate random ID for `prefix` string in api scenario, introduce this help function to `testutil` in resourcemanager/internal.

Add GenerateAlphaNumericID feature to testutil of mgmt. plane interal.

---

sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/autorest.md
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blob/responses.go
sdk/storage/azblob/blob/retry_reader.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/blockblob/responses.go
sdk/storage/azblob/examples_test.go
sdk/storage/azblob/internal/generated/zz_appendblob_client.go
sdk/storage/azblob/internal/generated/zz_blob_client.go
sdk/storage/azblob/internal/generated/zz_blockblob_client.go
sdk/storage/azblob/internal/generated/zz_container_client.go
sdk/storage/azblob/internal/generated/zz_models.go
sdk/storage/azblob/internal/generated/zz_pageblob_client.go
sdk/storage/azblob/internal/generated/zz_response_types.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azblob/service/client_test.go

Use azcore.ETag instead of string

---

sdk/storage/azblob/appendblob/models.go
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/blob/responses.go
sdk/storage/azblob/blob/retry_reader.go
sdk/storage/azblob/blob/retry_reader_test.go
sdk/storage/azblob/blockblob/models.go
sdk/storage/azblob/client_test.go
sdk/storage/azblob/common.go
sdk/storage/azblob/internal/exported/exported.go
sdk/storage/azblob/internal/shared/shared.go
sdk/storage/azblob/pageblob/client.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azblob/pageblob/examples_test.go
sdk/storage/azblob/pageblob/models.go

Replaced Offset and Count int64 pairs with HTTPRange.

Use HTTPRange for specifying a range of bytes

---

sdk/messaging/azeventhubs/internal/eh/stress/stress.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/finite_processor_stress.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/finite_send_and_receive.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/infinite_processor.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/tracking_data.go
sdk/messaging/azeventhubs/internal/errors.go
sdk/messaging/azeventhubs/internal/errors_test.go
sdk/messaging/azeventhubs/internal/exported/error.go
sdk/messaging/azeventhubs/internal/links.go
sdk/messaging/azeventhubs/processor.go

- When running the processor our owner level should default to zero if none is chosen (otherwise exclusive ownership doesn't kick in on the Event Hubs side)
- CodeConditionLost was typed as a string, instead of a Code
- The ownership lost error is actually two errors - an outer amqp.DetachError, with an inner RemoteError that's actually the error with the condition we need to check. So that's fixed, and it's also marked as a fatal error, so we don't get weird contention for no reason.
- Bumped up some of the limits on the 'finite' tests - they were low, which isn't bad, but they could be bigger and more interesting.
Also, the processor stress test now brings in multiple parallel consumers, which makes it easier to spot this bug. Tests will be forthcoming in a near-future PR to add in …

[azeventhubs] Fixing epoch/owner level issues with the Processor

---

sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/blockblob/models.go
sdk/storage/azblob/blockblob/responses.go
sdk/storage/azblob/client.go
sdk/storage/azblob/client_test.go
sdk/storage/azblob/examples_test.go
sdk/storage/azblob/internal/shared/batch_transfer.go
sdk/storage/azblob/models.go
sdk/storage/azblob/responses.go

Use BlockSize and Concurrency consistenty across operations. Removed XMS prefix from ContentCRC64.
Renamed list blobs API and its dependent types to include the word Flat.

Fix various naming issues

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/checkpoint_store.go
sdk/messaging/azeventhubs/checkpoints/blob_store.go
sdk/messaging/azeventhubs/consumer_client.go
sdk/messaging/azeventhubs/event_data.go
sdk/messaging/azeventhubs/event_data_batch.go
sdk/messaging/azeventhubs/event_data_batch_unit_test.go
sdk/messaging/azeventhubs/example_consuming_events_test.go
sdk/messaging/azeventhubs/example_enabling_logging_test.go
sdk/messaging/azeventhubs/example_processor_test.go
sdk/messaging/azeventhubs/example_producing_events_test.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/shared.go
sdk/messaging/azeventhubs/mgmt.go
sdk/messaging/azeventhubs/partition_client.go
sdk/messaging/azeventhubs/processor.go
sdk/messaging/azeventhubs/processor_load_balancer.go
sdk/messaging/azeventhubs/processor_partition_client.go
sdk/messaging/azeventhubs/producer_client.go
sdk/messaging/azeventhubs/producer_client_test.go

The pkg.go.dev for this package looks pretty bad because of some simple conventions I accidentally violated:
1. Any comment that's directly above the `package` declaration will be included as the package comment, which resulted in a bunch of "Copyright Microsoft"'s being inserted into the Overview. Fixed that by just adding in a blank line.
2. Whole-file examples will not display the full file unless there's at least one other `package level` declaration in the file. I've introduced some that I think aren't too artificial.
I also found an inconsistency in the batch naming - it really should be NumEvents(), rather than NumMessages(), since we're going with the Events terminology rather than Messages (EventData, ReceivedEventData, SendEventDataBatch).

[azeventhubs] Fixing some issues with docs and samples

---

sdk/storage/azblob/migrationguide.md

Initial migration guide for azblob

---

sdk/keyvault/azcertificates/client_test.go

A couple of last week's test runs failed due to timeouts here.

Allow more time for cert creation in live tests

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/client.go
sdk/messaging/azservicebus/error.go
sdk/messaging/azservicebus/example_session_receiver_test.go
sdk/messaging/azservicebus/example_session_roundrobin_test.go
sdk/messaging/azservicebus/internal/errors.go
sdk/messaging/azservicebus/internal/exported/error.go
sdk/messaging/azservicebus/liveTestHelpers_test.go
sdk/messaging/azservicebus/receiver_test.go
sdk/messaging/azservicebus/sender_test.go
sdk/messaging/azservicebus/session_receiver.go
sdk/messaging/azservicebus/session_receiver_test.go

Adding a new error Code (`CodeTimeout`) for when we get back a `com.microsoft:timeout` error from Service Bus. The primary use is if we are doing an `AcceptNextSessionFor<Entity>()` and there aren't any available sessions.
This should allow customers to figure out if there's a genuine failure or if their session-enabled queue/subscription is simply "empty".
This also improves the tests and adds in some more customer exposed examples for reading through a a queue of sessions.
Fixes #19039

[azservicebus] Create a programmatically useful code for when a session is not available

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_retry.go
sdk/azcore/runtime/policy_retry_test.go

Don't retry when Retry-After has a delay greater than the configured
MaxRetryDelay value.

Retry-After delay shouldn't exceed MaxRetryDelay

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity_test.go
sdk/azidentity/default_azure_credential.go
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/go.mod
sdk/azidentity/go.sum
sdk/azidentity/live_test.go
sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_credential.go
sdk/azidentity/managed_identity_credential_test.go

Internal changes that add token caching to `ManagedIdentityCredential` courtesy of MSAL. Draft pending the next MSAL release. Closes #16765.

ManagedIdentityCredential caches tokens

---

sdk/messaging/azeventhubs/checkpoint_store.go
sdk/messaging/azeventhubs/checkpoints/blob_store.go
sdk/messaging/azeventhubs/checkpoints/blob_store_test.go
sdk/messaging/azeventhubs/checkpoints/doc.go
sdk/messaging/azeventhubs/consumer_client.go
sdk/messaging/azeventhubs/consumer_client_test.go
sdk/messaging/azeventhubs/doc.go
sdk/messaging/azeventhubs/event_data_batch.go
sdk/messaging/azeventhubs/event_data_batch_unit_test.go
sdk/messaging/azeventhubs/example_consuming_events_test.go
sdk/messaging/azeventhubs/example_processor_test.go
sdk/messaging/azeventhubs/example_producing_events_test.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/finite_processor_stress.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/finite_send_and_receive.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/infinite_processor.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/shared.go
sdk/messaging/azeventhubs/internal/exported/new_websocket_conn_args.go
sdk/messaging/azeventhubs/internal/namespace.go
sdk/messaging/azeventhubs/partition_client.go
sdk/messaging/azeventhubs/processor.go
sdk/messaging/azeventhubs/processor_load_balancer.go
sdk/messaging/azeventhubs/processor_load_balancers_test.go
sdk/messaging/azeventhubs/processor_partition_client.go
sdk/messaging/azeventhubs/processor_test.go
sdk/messaging/azeventhubs/processor_unit_test.go
sdk/messaging/azeventhubs/producer_client.go
sdk/messaging/azeventhubs/producer_client_test.go
sdk/messaging/azeventhubs/test_checkpoint_store_test.go

Some great discussion in the archboard. There are still some bigger issues that need to be discussed, but these were some of the discussion that are easily resolveable:
- Added a lot of documentation to areas, making it clear which types require Closing, and added a bunch of self-referential docs as well between the type descriptions to get to examples, from sub-types to show which types actually instantiate them (ie: PartitionClient, ProcessorPartitionClient both mention their parent types and which function you use to create them).
- All types that used to say 'New*Options' types are properly renamed to just be *Options instead, avoiding 'New' clutter at the package level.
- Flatten the CheckpointStore's Ownership and Checkpoint types. This removed 3 extra clutter types (OwnershipData, …

[azeventhubs] Updating the documentation and API surface based on arch board feedback

---

sdk/storage/azblob/blockblob/chunkwriting.go
sdk/storage/azblob/blockblob/chunkwriting_test.go

`c.getErr` can return before slow writes complete. If there is more than one write and those writes result in errors, the second write blocks on a full `errCh`. The result is a deadlocked `copyFromReader` call because the wait groups never clear.
The test included tests demonstrates the deadlock. 
This PR causes `close` to simultaneously drain the `errCh` while it waits for writes to complete. It combines any errors that are returned.
I looked at the CHANGELOG, but not sure this change fits. Let me know if I need to do something else.

Fix deadlock when erroring writes are slow

---

sdk/storage/azblob/container/client.go
sdk/storage/azblob/container/models.go
sdk/storage/azblob/container/responses.go
sdk/storage/azblob/service/client.go
sdk/storage/azblob/service/client_test.go
sdk/storage/azblob/service/examples_test.go
sdk/storage/azblob/service/models.go
sdk/storage/azblob/service/responses.go

Added code for restoring soft-deleted container

Container soft delete

---

sdk/storage/azblob/CHANGELOG.md

Updates to changelog for 0.5.0 beta release.

Updating CHANGELOG.md for azblob 0.5.0 beta release

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/internal/utils/retrier.go
sdk/messaging/azservicebus/internal/utils/retrier_test.go

The sleep between retries was not cancellable but it should have been. This changes it to use a context.WithTimeout() instead.

[azservicebus] Make it so retry sleeps can be cancelled.

---

sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/client_test.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/internal/testcommon/clients_auth.go
sdk/storage/azblob/internal/testcommon/cpk.go
sdk/storage/azblob/lease/client_test.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azblob/service/client_test.go
sdk/storage/azblob/test-resources.json

Hook up live tests

---

sdk/messaging/azeventhubs/migrationguide.md

Recent customer issue in the previous eventhubs repo has reminded me that connection sharing is actually pretty important.
Adding to the migration guide for now as it's a simple differentiator (at least, for producing events) and will eventually update help as well.

[azeventhubs] Adding in a section about TCP connection sharing to the migration guide

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/request.go
sdk/azcore/runtime/request_test.go
sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/container/client.go
sdk/storage/azblob/service/client.go

JoinPaths: don't add "/" before the query string

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/appendblob/client.go
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/client.go
sdk/storage/azblob/container/client.go
sdk/storage/azblob/lease/blob_client.go
sdk/storage/azblob/lease/container_client.go
sdk/storage/azblob/pageblob/client.go
sdk/storage/azblob/service/client.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/19274

Improve doc comments for client constructors

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/request.go
sdk/azcore/runtime/request_test.go

Fixes https://github.com/Azure/autorest.go/issues/843

Retain contents of read-only fields when sending requests

---

sdk/azidentity/azidentity.go
sdk/azidentity/client_assertion_credential.go
sdk/azidentity/client_certificate_credential.go
sdk/azidentity/client_secret_credential.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/username_password_credential.go

This consolidates setting the core MSAL options required by all credential types into a couple of helpers.

Consolidate common MSAL options

---

sdk/azidentity/azidentity.go
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/environment_credential.go
sdk/azidentity/environment_credential_test.go

A future PR will add more references to these strings, and we can tidy them up now to make that PR less noisy.

Add constants for azidentity environment variables

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/consumer_client_internal_test.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/batch_stress_tester.go

This is just a simple update for QA, no fixes and also pushing the changelog date forward since it got delayed.
- Added in some more tests for recovery. There were some incidents in the stress cluster but they turned out to be red herrings. They did reveal that some more granular tests should exist and now we have them for both link and connection level recovery.
- Fixed a bug in one of the stress tests. We kept getting an odd (but non-fatal) error as the test tore down (after passing!) about the connection idling out. Turns out it was accurate - the batch test is a little unusual in that it doesn't send events continually - it sends them once at the beginning of the test and the consumers just keep rewinding to pick them up again. So the producer client just needed to be closed after …

[azeventhubs] Prep for release, fixing tests

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/pipeline.go
sdk/azcore/arm/runtime/pipeline_test.go
sdk/azcore/internal/shared/constants.go
sdk/azcore/policy/policy.go
sdk/azcore/runtime/pipeline.go
sdk/azcore/runtime/policy_api_version.go
sdk/azcore/runtime/policy_api_version_test.go

...with code like this:
```go
armsubscription.NewSubscriptionsClient(cred, &arm.ClientOptions{
ClientOptions: azcore.ClientOptions{
APIVersion: "42",
}
})
```
To get this API for ARM clients, users can simply upgrade `azcore`--no code gen required. For data plane clients, we'll need to release new versions that tell the new pipeline policy which header/query param to set. It's therefore possible for a user to upgrade `azcore` and set the new option for a data plane client that won't respect it. In this case I have the policy's `Do()` return an error (a constructor error isn't possible). That's bad, but I like it better than silently ignoring configuration. Let me know if you see a better alternative.

Enable users to override client default API versions

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/pollers/async/async.go
sdk/azcore/internal/pollers/async/async_test.go
sdk/azcore/internal/pollers/body/body.go
sdk/azcore/internal/pollers/body/body_test.go
sdk/azcore/internal/pollers/op/op.go
sdk/azcore/internal/pollers/op/op_test.go
sdk/azcore/internal/pollers/util_test.go

Per LRO guidelines, operation/RELO must return a success HTTP status code when checking the status regardless of the operation's state. If polling on an LRO returns an unsuccessful HTTP status code, it should be surfaced as an *azcore.ResponseError.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/19330

Check HTTP status code before looking for LRO status

---

sdk/data/azappconfig/CHANGELOG.md
sdk/data/azappconfig/policy_sync_token.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/19223

Don't touch resp when err is non nil

---

sdk/data/azappconfig/policy_sync_token.go
sdk/data/azappconfig/policy_sync_token_test.go

For bug caught during live testing in the release pipeline.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1933645&view=logs&j=5ec87896-d90a-5d4a-c9b7-f77bbdb1fe36&t=fe393d95-4d2a-5621-96a7-be5b73339968
```
2022-10-20T19:13:31.2559466Z --- FAIL: TestClient (0.06s)
2022-10-20T19:13:31.2560888Z panic: assignment to entry in nil map [recovered]
2022-10-20T19:13:31.2562284Z 	panic: assignment to entry in nil map
2022-10-20T19:13:31.2562956Z 
2022-10-20T19:13:31.2563992Z goroutine 6 [running]:
2022-10-20T19:13:31.2565241Z testing.tRunner.func1.2({0x6e54c0, 0x7b9440})
2022-10-20T19:13:31.2566792Z 	/opt/hostedtoolcache/go/1.18.2/x64/src/testing/testing.go:1389 +0x24e
2022-10-20T19:13:31.2568219Z testing.tRunner.func1()
2022-10-20T19:13:31.2569571Z …
```

Fix panic due to nil map

---

.gitignore
eng/scripts/run_tests.ps1
sdk/internal/CHANGELOG.md
sdk/internal/recording/recording.go
sdk/internal/recording/recording_test.go
sdk/internal/version.go

Fixes https://github.com/Azure/azure-sdk-tools/issues/4257
This adds support to the recording package to work with [test proxy asset sync](https://github.com/Azure/azure-sdk-tools/blob/main/tools/test-proxy/documentation/asset-sync/README.md), which will allow the test recordings to be moved out of the go repository into https://github.com/Azure/azure-sdk-assets.
The primary behavior change is: if an `assets.json` file is found in the current test service directory or any parent, the recording framework will request external assets via the test proxy during test setup. If there is no `assets.json`, then pre-existing recordings will be used instead. This change should support running tests via `run_tests.ps1` or invoking `go test` directly.
I also added some minor improvements to the …

Add support for making recordings external to the repository

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/exported/request_test.go
sdk/azcore/internal/shared/shared_test.go
sdk/azcore/runtime/pipeline.go
sdk/azcore/runtime/policy_body_download_test.go
sdk/azcore/runtime/policy_logging_test.go
sdk/azcore/runtime/policy_retry_test.go

Specify slice length when creating destination for copy operation.
Added additional tests to improve code coverage.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/15755

Fixed bug when combining pipeline and client allow lists

---

sdk/azcore/CHANGELOG.md
sdk/azcore/policy/policy.go
sdk/azcore/tracing/constants.go
sdk/azcore/tracing/tracing.go
sdk/azcore/tracing/tracing_test.go

This package contains the definitions needed to implement distributed tracing in SDKs and client-side providers.
https://apiview.dev/Assemblies/Review/4bc716d2a1de445ea75a731f427dec52#azcore/tracing
Fixes
- https://github.com/Azure/azure-sdk-for-go/issues/7358
- https://github.com/Azure/azure-sdk-for-go/issues/19280

Add tracing package

---

sdk/messaging/azservicebus/internal/amqp_test_utils.go
sdk/messaging/azservicebus/internal/errors.go
sdk/messaging/azservicebus/internal/errors_test.go
sdk/messaging/azservicebus/receiver.go
sdk/messaging/azservicebus/receiver_unit_test.go

We seem to have some customers that can reproduce an issue where the receiver is "active" but no longer receiving any messages.
Currently, our keep-alive check is only checking things at the connection level, including our keep-alive. However, if our link were to be disconnected on the service side, and we somehow missed the detach notification, there'd be no confirmation on our end that the link is actually alive since we don't re-issue credits unless something changes (and nothing will).
This change makes it so we give it a max 5 minutes of pure-idle time on the client. If we don't receive anything for that time we'll just restart the link, which is a pretty cheap operation and it will guarantee that the link is active. I've also added in some error messages specifically around this …

[azservicebus] Idle timer

---

sdk/azidentity/azidentity_test.go
sdk/azidentity/client_assertion_credential_test.go
sdk/azidentity/client_certificate_credential_test.go
sdk/azidentity/environment_credential_test.go
sdk/azidentity/managed_identity_client_test.go
sdk/azidentity/managed_identity_credential_test.go

Constants always cast to `[]byte` in use may as well be `[]byte` to begin with. Also removing magic constants from fake metadata (the tenant IDs).

Improve azidentity test constants

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/pipeline.go
sdk/azcore/runtime/pipeline.go
sdk/azcore/runtime/policy_api_version.go
sdk/azcore/runtime/policy_api_version_test.go

Following from Joel's comment that it's awkward for `PipelineOptions` to have two fields for `APIVersionPolicy` options, and what if we later want to add a third, this PR consolidates them in a new type. The result is easier to extend but still awkward because although it seems best for the policy constructor to take this new type, its values are logically required. That is to say, it doesn't make sense to construct `APIVersionPolicy` without telling it where on to set the version on requests. Functionally speaking though, these values are optional because the policy is a no-op when they aren't set. (That's a workaround for `NewPipeline()` being unable to return an error.) So, please look it over and share your thoughts--maybe there's a tidier third way here.

Consolidate API version policy options

---

sdk/monitor/azquery/CHANGELOG.md
sdk/monitor/azquery/README.md
sdk/monitor/azquery/autorest.md
sdk/monitor/azquery/example_test.go
sdk/monitor/azquery/logs_client.go
sdk/monitor/azquery/logs_client_test.go
sdk/monitor/azquery/metrics_client.go
sdk/monitor/azquery/metrics_client_test.go
sdk/monitor/azquery/models.go
sdk/monitor/azquery/models_serde.go
sdk/monitor/azquery/response_types.go
sdk/monitor/azquery/utils_test.go

Renaming and type updates to make the library clearer and more in line with the other Monitor Query language libraries.
Method Name Updates:
1. NewListMetricDefinitionsPager -> NewListDefinitionsPager
2. NewListMetricNamespacesPager -> NewListNamespacesPager
3. Batch -> QueryBatch
Type Update:
Render and Statistics field would go from being of type interface{} to []byte

[azquery] renaming

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/internal/eh/stress/Chart.yaml
sdk/messaging/azeventhubs/internal/links.go
sdk/messaging/azeventhubs/internal/rpc.go
sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/internal/amqpLinks.go
sdk/messaging/azservicebus/internal/rpc.go
sdk/messaging/azservicebus/internal/stress/Chart.yaml

When looking for leaks in negotiateClaim I missed the most "obvious" one - if you cancel the function we still need to close the link we opened. If we don't we leak it, and the service will then start failing future negotiations to open it.
This showed up in https://github.com/Azure/azure-sdk-for-go/issues/19347, originally, but a fix I made recently in SB to test attaching/detaching links made it even more obvious.
Fixes #19347

[azservicebus/azeventhubs] Fix "$cbs node has already been opened" issue

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go
sdk/azcore/policy/policy.go
sdk/azcore/runtime/policy_bearer_token.go
sdk/azcore/runtime/policy_bearer_token_test.go

Closes #17554 by adding a couple of extension points SDK developers can use to insert custom logic around BearerTokenPolicy's default behavior. These allow clients to elicit challenges (to discover auth parameters) and to handle them, without having to copy and tweak BearerTokenPolicy, as we've done for Key Vault and ARM. This will simplify supporting CAE and ARM cross-tenant authentication. #19447 has a draft implementation for Key Vault showing this new API in use.

Add optional auth challenge handling to BearerTokenPolicy

---

sdk/internal/CHANGELOG.md
sdk/internal/temporal/resource.go
sdk/internal/temporal/resource_test.go
sdk/internal/version.go

Read from shared state when the lock is held.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/19528

Fix race condition when fetching expiring resource

---

sdk/azidentity/README.md

No need to specify a version now that the latest stable has the docs

Update ClientAssertionCredential docs link

---

sdk/keyvault/internal/CHANGELOG.md
sdk/keyvault/internal/challenge_policy.go
sdk/keyvault/internal/challenge_policy_test.go

Oops, looks like I introduced a bug in #19123 by misplacing a closing brace. We must add the scope `/.default` to AADv1 resource strings like `https://vault.azure.net` regardless of whether challenge resource verification is enabled.

Set correct Key Vault scope when challenge verification disabled

---

sdk/keyvault/azcertificates/client_test.go
sdk/keyvault/azcertificates/testdata/recordings/TestOperationCRUD.json

This test has failed a few times due to a 409 when deleting the cert operation. I guess this is because it executes while the update is pending, so here I add a retry loop around the delete in the belief that such conflict is transient. I also changed the test cert's policy to require a manual step before Key Vault can issue the certificate. That will prevent the test trying to update or delete a completed operation, which I haven't seen cause a failure but imagine is another lurking race.

Make azcertificates operation test more robust

---

sdk/messaging/azservicebus/client.go
sdk/messaging/azservicebus/liveTestHelpers_test.go
sdk/messaging/azservicebus/receiver.go
sdk/messaging/azservicebus/receiver_test.go
sdk/messaging/azservicebus/session_receiver.go
sdk/messaging/azservicebus/session_receiver_test.go

Session links, unlike non-session links, have a lock renewal method that will affirm that the link is alive. Doing our own client-side link checking just complicates things and, in some cases, makes it so you lose the lock for a session you once owned.
Fixes #19566

[azservicebus] Disable the idle link tracking on session links

---

sdk/messaging/azeventhubs/internal/eh/stress/templates/deploy-job.yaml

This is really the only test that runs for long enough to really impact our budget. It's done pretty well so, for the most part, we'll leave logging off and figure out a better solution soon.

[azeventhubs] stress: We can't commit this much logging to the forward thrusters.

---

sdk/storage/azblob/service/examples_test.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/19590

Don't use unexported type in example code

---

sdk/internal/CHANGELOG.md
sdk/internal/recording/recording.go
sdk/internal/recording/recording_test.go

Recorded tests trigger the race detector when run concurrently because our `recording` package stores metadata in a map. This PR replaces that map with a `sync.Map`. I also tweaked an existing test not to require a value for `PROXY_CERT`. (There's no functional reason for the test to do so.)
Closes #18763

Prevent data races in internal/recording

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blockblob/responses.go
sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/zz_appendblob_client.go
sdk/storage/azblob/internal/generated/zz_blob_client.go
sdk/storage/azblob/internal/generated/zz_blockblob_client.go
sdk/storage/azblob/internal/generated/zz_pageblob_client.go
sdk/storage/azblob/internal/generated/zz_response_types.go

Remove XMS prefix for ContentCRC64 response field

---

sdk/messaging/azservicebus/session_receiver.go
sdk/messaging/azservicebus/session_receiver_test.go

The functionality was always there but it wasn't documented and there wasn't a test for it.

[azservicebus] Add in a simple "clearing of session state" test

---

sdk/messaging/azservicebus/internal/stress/Chart.lock
sdk/messaging/azservicebus/internal/stress/scenarios-matrix.yaml
sdk/messaging/azservicebus/internal/stress/shared/stress_context.go
sdk/messaging/azservicebus/internal/stress/shared/utils.go
sdk/messaging/azservicebus/internal/stress/templates/deploy-job.yaml
sdk/messaging/azservicebus/internal/stress/tests/empty_sessions.go
sdk/messaging/azservicebus/internal/stress/tests/finite_sessions.go
sdk/messaging/azservicebus/internal/stress/tests/idle_fast_reconnect.go
sdk/messaging/azservicebus/internal/stress/tests/infinite_send_and_receive.go
sdk/messaging/azservicebus/internal/stress/tests/tests.go
sdk/messaging/azservicebus/session_receiver.go

Adding in a test that lets us test sessions by repeatedly creating them (ie, sending a message with a session ID) and then receiving on it. 
The session tests (since it holds open more receivers) uses more memory, so we account for that now by specifying a memory limit for each test.
Part of the fix for #19511.

[azservicebus] Adding in a session manager test - create and receive on sessions repeatedly.

---

sdk/messaging/azservicebus/client_test.go

Adding in a workaround for the annoying "send claims" bug that manifests in CI. 
Fixes #19609

[azservicebus] Do a sleep in our azidentity test if it initially reports that we don't have Send claims

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/client_test.go
sdk/storage/azblob/internal/shared/batch_transfer.go

Uploads larger than 256MB could fail depending on their size. Refactored some internal code to follow convention.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/19651

Fix uploads larger than 256MB

---

sdk/storage/azblob/internal/exported/set_expiry.go

The type is exported but is not meant for external implementation.

Prevent ExpiryType from being publicly implementable

---

sdk/azidentity/managed_identity_credential.go

This dead code was causing compile errors under go1.20.
- [N/A] Tests are included and/or updated for code changes.
- [N/A] Updates to [CHANGELOG.md][] are included.
- [N/A] MIT license headers are included in each file.

Remove dead code in managed_identity_credentials.go 

---

sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/internal/testcommon/clients_auth.go

The MMF change introduced a change to UploadStream that would internally switch to Upload if the source size was smaller than one block.  When this happens, the MD5 is calculated and returned which the test didn't expect to happen.
Introduced in https://github.com/Azure/azure-sdk-for-go/pull/19635

Fix live test after MMF change

---

sdk/messaging/azeventhubs/example_producing_events_test.go

While testing out some of the Go Event Hubs examples I go an error. Changing the following lines to use the declaration and assignment operator seems to fix it. 

[Event Hubs] Example fix

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity.go
sdk/azidentity/azidentity_test.go
sdk/azidentity/example_test.go
sdk/azidentity/on_behalf_of_credential.go
sdk/azidentity/on_behalf_of_credential_test.go

Add OnBehalfOfCredential

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azure_cli_credential.go

It isn't possible today for an application to allow more than the credential's default 10 seconds for authentication because the credential indiscriminately calls `context.WithTimeout(..., 10*time.Second)`, which will shorten any longer deadline the application may have set. With this change, the credential imposes its default timeout only when the application hasn't already set a deadline. Closes #19575

AzureCLICredential respects application deadlines

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/zz_service_client.go
sdk/storage/azblob/pageblob/client_test.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/17421
Golang's Encoding method returns '+' instead of '%20' for spaces, causing issues with encoding. The change is made in a transformative script. 

Adding tests for FilterBlobs and fixing encoding issue

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azure_cli_credential.go
sdk/azidentity/azure_cli_credential_test.go

Currently it does so in local time, unlike all other credential types. This change doesn't affect comparisons through the `time` API because those are location-aware, however it is a breaking change for anyone who took a dependency on this value's specific location. I can't imagine why anyone would have done that.

AzureCLICredential reports token expiration time in UTC

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/policy/policy.go
sdk/azcore/arm/runtime/pipeline.go
sdk/azcore/arm/runtime/policy_bearer_token.go
sdk/azcore/arm/runtime/policy_bearer_token_test.go
sdk/azcore/internal/exported/exported.go
sdk/azcore/internal/shared/constants.go

ARM cross-tenant auth needs support from `azcore` and `azidentity` to function end to end (see [ARM docs](https://learn.microsoft.com/azure/azure-resource-manager/management/authenticate-multi-tenant) for a rundown of how this feature works). This PR is the `azcore` part, with new API for specifying auxiliary tenants for ARM clients and requesting access tokens from arbitrary tenants. #19529 has the `azidentity` part--it depends on this PR and the next MSAL release.
Usage will look like this:
```go
// cred will request tokens from the primary tenant unless another is specified in GetToken args
cred, err := azidentity.NewClientSecretCredential("primary-tenant", "client-id", "secret", &azidentity.ClientSecretCredentialOptions{
// cred will (attempt to) authenticate in any requested tenant; …
```

Support ARM cross-tenant authentication

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/exported/request.go
sdk/azcore/internal/exported/request_test.go

Today, sending a `Request` without its body (Key Vault clients do this) requires copying it and/or modifying the underlying `http.Request` because `Request.SetBody()` won't overwrite a non-empty body with an empty one. This is apparently an oversight--`SetBody` will overwrite a non-empty body or set an empty body, but it won't do both at once.

Request.SetBody() allows overwriting with an empty body

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/internal/eh/stress/Chart.lock
sdk/messaging/azeventhubs/internal/eh/stress/scenarios-matrix.yaml
sdk/messaging/azeventhubs/internal/eh/stress/templates/deploy-job.yaml
sdk/messaging/azeventhubs/internal/eh/stress/tests/batch_stress_tester.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/processor_stress_tester.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/shared.go
sdk/messaging/azeventhubs/processor.go

- Added the option to configure prefetch count for ProcessorPartitionClient's created from the Processor
- Fixed some issues with the stress tests. Batch tests were using a really large batch size, which was too large for the amount of memory we're using in our test containers.
- Processor tests weren't configuring a prefetch value (prior to this PR the setting wasn't exposed)
Also, just generally made the stress tests a bit cleaner, leveragin the scenario-matrix more for configuring values.
Fixes #19770

[azeventhubs] Adding in prefetch value for the Processor, updating stress tests

---

sdk/data/azappconfig/CHANGELOG.md
sdk/data/azappconfig/client.go
sdk/data/azappconfig/client_test.go

Just added a `ContentType` near the `Label` in `*SettingOptions`, to be used as it was before the v0.3.0 breaking changes.

[azappconfig] Handle setting content type in AddSetting and SetSetting (#19797)

---

sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/blockblob/examples_test.go
sdk/storage/azblob/internal/exported/log_events.go
sdk/storage/azblob/log.go

- Create a new logging event to track number of blocks and size of each block calculated during upload.

Add logs to dump calculate block size and count during upload

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/processor.go
sdk/messaging/azeventhubs/processor_unit_test.go

Remove the epoch options for the Processor. This wasn't intended to be configurable and should always be set and always be zero.
Fixes #19848

[azeventhubs] Remove the epoch options for the Processor

---

sdk/storage/azblob/lease/models.go

Removed proposedLeaseID from the option bag for ChangeLease(), since it is already part of the method as a required parameter.

Removed proposedLeaseID from the option bag for ChangeLease method

---

sdk/azidentity/default_azure_credential.go
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/example_credential_unavailable_test.go
sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_credential_test.go

A couple of users have asked us to export the internal API DefaultAzureCredential uses to impose a timeout on managed identity authentication, to avoid a long timeout when IMDS is unavailable (#19699, #19721). We don't want to do that because it means adding a redundant, esoteric cancellation mechanism that conflicts with cancellation via `context.Context`. This example shows how to reimplement this DefaultAzureCredential behavior with Context and a small wrapper.
I'm also tempted to replace the internal API with this wrapper. That would steer future readers of the source in the right direction, and I believe it would simplify some of the implementation as well. Thoughts?

Replace internal IMDS timeout with public API workaround

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/bloberror/error_codes.go
sdk/storage/azblob/container/client.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/service/client.go
sdk/storage/azblob/service/client_test.go

Related to:https://github.com/Azure/azure-sdk-for-go/issues/19864
Added MissingSharedKeyCredential errortype and tests for GetSASURL.

Fixing documentation for GetSASURL and Creating ErrorType 

---

sdk/keyvault/azkeys/ci.yml

We need to allow more time because de/provisioning resources (MHSM) can be very slow (~50 minutes).

Increase timeout for azkeys live tests

---

sdk/data/aztables/shared_access_signature_test.go

The SAS tests used hard-coded start and expiry times which are no longer valid and cause false failures.

Fix live tests for aztables

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/policy_bearer_token.go
sdk/azcore/arm/runtime/policy_bearer_token_test.go
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/internal/exported/exported.go
sdk/azcore/internal/shared/constants.go
sdk/azcore/runtime/policy_bearer_token_test.go

This is the azcore side of #14931. I'm targeting the beta branch because the end-to-end scenario requires an azidentity beta. ARM is the only SDK service that supports CAE (continuous access evaluation) today. Briefly, it works like this: ARM evaluates security policies for the access token attached to each request. When a token doesn't satisfy policy, ARM responds 401 with an authentication challenge. The client must retry the request with a new access token having the claims specified by the challenge. So, this PR adds challenge handling to ARM's auth policy, and a `TokenRequestOptions.Claims` field that enables the policy to request claims when calling `GetToken()`.

CAE support for ARM clients

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity.go
sdk/azidentity/azidentity_test.go
sdk/azidentity/client_assertion_credential.go
sdk/azidentity/client_certificate_credential.go
sdk/azidentity/client_secret_credential.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/on_behalf_of_credential.go
sdk/azidentity/username_password_credential.go

This is the azidentity side of #14931. Credentials must do two things to enable the end-to-end feature: specify client capability "CP1" to indicate the client can handle claims challenges, and pass claims through `GetToken` to MSAL. We send CP1 by default so applications are secure by default. Doing so has no effect when the RP doesn't support CAE or the tenant isn't configured for it. However, we provide an environment variable opt out for applications that can't handle claims challenges, for example because they need to upgrade a client library first.

CAE support for azidentity

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/internal/amqpLinks.go
sdk/messaging/azservicebus/internal/amqpLinks_test.go
sdk/messaging/azservicebus/internal/stress/shared/stress_context.go
sdk/messaging/azservicebus/internal/stress/tests/empty_sessions.go
sdk/messaging/azservicebus/internal/stress/tests/infinite_send_and_receive.go
sdk/messaging/azservicebus/internal/stress/tests/metric_names.go
sdk/messaging/azservicebus/internal/stress/tests/rapid_open_close.go

* On recovery check for the specific errConnResetNeeded error rather than a cancellation error.
I've merged those code paths into one.
* Update the empty sessions test to be more realistic, handle connection failures, etc..
* Make the rapid open/close test do more rounds and more iterations.
* Add in some logging for the "link error being upgraded to a connection error".

[azservicebus] Fixing error check in recovery, adding some more tests

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/policy_register_rp.go
sdk/azcore/arm/runtime/policy_register_rp_test.go

If the error response is unrecognized, return the response to the calling API so its error unmarshalling will handle it.  Added a test to cover this case.
Converted RP registration tests to use a fake client which is more of a real-world scenario.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/19956

Propagate unknown errors from RP registration policy

---

sdk/monitor/azquery/CHANGELOG.md
sdk/monitor/azquery/README.md
sdk/monitor/azquery/TROUBLESHOOTING.md
sdk/monitor/azquery/autorest.md
sdk/monitor/azquery/custom_client.go
sdk/monitor/azquery/example_test.go
sdk/monitor/azquery/logs_client.go
sdk/monitor/azquery/logs_client_test.go
sdk/monitor/azquery/metrics_client.go
sdk/monitor/azquery/metrics_client_test.go
sdk/monitor/azquery/models.go
sdk/monitor/azquery/models_serde.go
sdk/monitor/azquery/utils_test.go
sdk/monitor/azquery/version.go

1. Preps for release
2. README updates
3. Makes LogsQueryOptions.String() private (request by Jeff)

[azquery] Release prep and final updates

---

sdk/containers/azcontainerregistry/blob_client_test.go
sdk/containers/azcontainerregistry/client_test.go
sdk/resourcemanager/internal/testutil/credential_test.go
sdk/resourcemanager/internal/testutil/helper_test.go

fix wrong order of require.Equal arguments

---

sdk/storage/azqueue/internal/generated/autorest.md
sdk/storage/azqueue/internal/generated/zz_models.go
sdk/storage/azqueue/internal/generated/zz_models_serde.go
sdk/storage/azqueue/internal/generated/zz_response_types.go
sdk/storage/azqueue/models.go
sdk/storage/azqueue/sas/account.go
sdk/storage/azqueue/service_client_test.go
sdk/storage/azqueue/test-resources.json

Remove `item` suffix from generated and client code.
Add live pipeline.

Queues Live Pipeline + APIViews Feedback

---

eng/scripts/Language-Settings.ps1

Fix for https://github.com/Azure/azure-sdk-for-go/pull/19879#discussion_r1093893548 to support packages like `security/keyvault/internal` for #19879 
Needs to go in with https://github.com/Azure/azure-sdk/pull/5534

Update package regex to detect arbitrary length directory trees

---

eng/tools/generator/cmd/v2/common/changelogProcessor.go
eng/tools/generator/cmd/v2/common/changelogProcessor_test.go
eng/tools/generator/cmd/v2/common/testdata/new/lro/lrofilter.go
eng/tools/generator/cmd/v2/common/testdata/new/operation/funcfilter.go
eng/tools/generator/cmd/v2/common/testdata/old/lro/lrofilter.go
eng/tools/generator/cmd/v2/common/testdata/old/operation/funcfilter.go

Should be comparing the first return value, not the function name.

fix changelog function filter

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/internal/mgmt.go
sdk/messaging/azservicebus/internal/mock/emulation/mock_data_receiver.go
sdk/messaging/azservicebus/internal/mock/mock_helpers.go
sdk/messaging/azservicebus/internal/test/test_helpers.go
sdk/messaging/azservicebus/internal/utils/retrier_test.go
sdk/messaging/azservicebus/receiver.go
sdk/messaging/azservicebus/receiver_simulated_test.go
sdk/messaging/azservicebus/receiver_unit_test.go
sdk/messaging/azservicebus/session_receiver_test.go

Fixing issues where we could over-request credit (#19965) or allow for negative/zero credits (#19743), both of which could cause issues with go-amqp..
Fixes #19965
Fixes #19743

[azservicebus] Validate that credits are within limits (not over or under)

---

sdk/data/aztables/ci.yml

So that I can avoid manually triggering this pipeline before merging an update to `eng/common/testproxy/target_version.txt`.

Trigger `aztables` when proxy files are updated

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/emulator_cosmos_item_test.go
sdk/data/azcosmos/partition_key.go
sdk/data/azcosmos/partition_key_test.go

- [ x] The purpose of this PR is explained in this or a referenced issue.
- [ x] The PR does not update generated files.
- [ x] Tests are included and/or updated for code changes.
- [ x] Updates to [CHANGELOG.md][] are included.
- [ x] MIT license headers are included in each file.

Null Partition Key for Cosmos

---

sdk/messaging/azeventhubs/internal/eh/stress/Dockerfile
sdk/messaging/azeventhubs/internal/eh/stress/stress.go
sdk/messaging/azeventhubs/partition_client.go
sdk/messaging/azeventhubs/partition_client_unit_test.go

The current go-amqp can have issues if your active credits are greater than the session window size. We have a blocking-release bug here: https://github.com/Azure/go-amqp/issues/240.
I've also added validation to prevent asking for <= 0 credits as well, which isn't supported.

[azeventhubs] Fix credit requesting errors

---

eng/pipelines/templates/steps/build-test.yml

To make the debug of CI occasionally failure easier.

Show SDK log for CI test

---

sdk/internal/recording/recording.go
sdk/internal/recording/recording_test.go
sdk/internal/recording/testdata/recordings/TestGenerateAlphaNumericID.json

1. Add GenerateAlphaNumericID function.
2. Store random seed in each recording file.
3. This change is to move the similar function under `sdk/resourcemanger/internal` as it should be part of our recording system. 
Part of #19984

Add GenerateAlphaNumericID for test-proxy to recording package

---

sdk/messaging/azeventhubs/internal/eh/stress/scenarios-matrix.yaml
sdk/messaging/azeventhubs/internal/eh/stress/templates/deploy-job.yaml

Adding in a chaos policy deployment for the Event Hubs stress tests. Also, bumped up the tests to use larger limits.
Fixes #15371

[azeventhubs] Adding in network chaos to a few tests

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/poller.go
sdk/azcore/runtime/poller_test.go

This ensures that the custom handler is used in the event that the custom poller has the same shape as an in-box poller.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/20051

Favor custom PollingHandler when rehydrating a poller

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/policy/policy.go
sdk/azcore/arm/policy/policy_test.go
sdk/azcore/arm/runtime/pipeline.go

Also fix a bug for `arm/runtime.NewPipeline`.

Add `Clone()` method for `arm/policy.ClientOptions`

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/consumer_client.go
sdk/messaging/azeventhubs/consumer_client_test.go
sdk/messaging/azeventhubs/internal/constants.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/processor_stress_tester.go
sdk/messaging/azeventhubs/partition_client.go
sdk/messaging/azeventhubs/producer_client.go
sdk/messaging/azeventhubs/producer_client_test.go

Event Hubs has an optional parameter you can pass that lets you identify a consumer link. This name will come back in error messages like when link ownership is contested. Given the distributed nature of consumers this identifier can help diagnose issues where consumers are battling over links.
Fixes #15074

[azeventhubs] Client identifier support

---

sdk/messaging/azeventhubs/example_checkpoint_migration_test.go
sdk/messaging/azeventhubs/example_consuming_events_test.go
sdk/messaging/azeventhubs/example_processor_test.go
sdk/messaging/azeventhubs/migrationguide.md

Adding in a migration guide section that shows how to migrate We want to make it easy for customers using the previous `azure-event-hubs-go` package to use this package (`github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs`).
Fixes #19849

[azeventhubs] Adding a section to the migration guide that shows how to migrate from older checkpoints to a newer checkpoint store

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go

The target branch here is `release/azcore-1.4.0-beta` with the latest `main` merged in, so v1.5.0-beta.1 combines v1.4.0-beta.1 and the released v1.4.0.

Prepare azcore v1.5.0-beta.1 for release

---

sdk/containers/azcontainerregistry/CHANGELOG.md
sdk/containers/azcontainerregistry/assets.json
sdk/containers/azcontainerregistry/authentication_policy.go
sdk/containers/azcontainerregistry/authentication_policy_test.go
sdk/containers/azcontainerregistry/ci.yml

Two problems:
1. When cloning challenge request in the auth policy, the previous code will erase the original request's "Content-Length"
2. When retry, the previous code will do another redundant challenge request
Previous failure example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2194977&view=logs&j=a20abffc-7e85-5d60-a753-b6154d45fe99&t=b38a3d44-54a5-5a70-e115-78df002fe247.
Live test result after fix: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2198625&view=results
Fix: https://github.com/Azure/azure-sdk-for-go/issues/20007

Fix test failure because of "CONTENT_LEN_INVALID"

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/internal/cbs.go
sdk/messaging/azeventhubs/internal/errors.go
sdk/messaging/azeventhubs/internal/links_test.go
sdk/messaging/azeventhubs/internal/test/test_helpers.go
sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/internal/amqpLinks_test.go
sdk/messaging/azservicebus/internal/cbs.go
sdk/messaging/azservicebus/internal/errors.go

You're only allowed to have one Sender+Receiver for the $cbs endpoint. In some cases, where there are connection failures or link cleanup is cancelled it's possible for the link to remain open. The only way to fix this is to restart the connection.
Fixes #19504
Likely related to dapr/components-contrib/issues/2617

[azservicebus,azeventhubs] Fixing issue where $cbs link being incompletely closed prevented the connection from recovering

---

eng/scripts/Language-Settings.ps1

Change to support https://github.com/Azure/azure-sdk-for-go/pull/18841, see [discussion](https://github.com/Azure/azure-sdk-for-go/pull/18841#issuecomment-1451179175).
Paired with https://github.com/Azure/azure-sdk/pull/5748

Support profile directory as top level directory for package properties

---

sdk/messaging/azeventhubs/internal/eh/stress/templates/deploy-job.yaml
sdk/messaging/azservicebus/internal/stress/templates/deploy-job.yaml

Updating the chaos-mesh policies so we don't set startingDeadlineSeconds and concurrencyPolicy to conflicting values.

[azservicebus,azeventhubs] Updating the chaos-mesh policies

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity.go
sdk/azidentity/azidentity_test.go
sdk/azidentity/azure_cli_credential.go
sdk/azidentity/client_assertion_credential.go
sdk/azidentity/client_certificate_credential.go
sdk/azidentity/client_certificate_credential_test.go
sdk/azidentity/client_secret_credential.go
sdk/azidentity/default_azure_credential.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/device_code_credential_test.go
sdk/azidentity/environment_credential.go
sdk/azidentity/errors.go
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/logging.go
sdk/azidentity/managed_identity_credential.go
sdk/azidentity/on_behalf_of_credential.go
sdk/azidentity/syncer.go
sdk/azidentity/syncer_test.go
sdk/azidentity/username_password_credential.go
sdk/azidentity/workload_identity.go

Sharing a credential instance among goroutines can produce redundant token requests because goroutines may race to populate the credential's cache. This PR refactors `GetToken()` into two callbacks, one for silent auth (checking the cache) and one for requesting a new token, and adds a new `syncer` type to synchronize them. (Credentials that don't distinguish checking the cache from requesting a token use the same method for both callbacks.) Credentials will allow only one goroutine to authenticate at a time, and waiting goroutines will check the cache again when they wake up. Closes #20044

Synchronize goroutines within GetToken

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/pollers/util.go
sdk/azcore/internal/pollers/util_test.go

While they're non-conformant per the RPC spec, we've seen these in the wild and changing them now would be breaking for REST clients.
Fixes
- https://github.com/Azure/azure-sdk-for-go/issues/19209
- https://github.com/Azure/azure-sdk-for-go/issues/20342

Added some additional LRO terminal state values

---

.github/CODEOWNERS

Updating the code owners for the key vault. Key vault modules will be moving from sdk/keyvault to sdk/security/keyvault

Update keyvault code owners

---

documentation/developer_setup.md

The standalone test proxy executable should be easier to run and have fewer edge case issues (volume mount/cross-OS issues, missing dependency issues) for go developers than the docker or dotnet install processes.

Document using standalone test proxy

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/chained_token_credential.go
sdk/azidentity/chained_token_credential_test.go
sdk/azidentity/default_azure_credential.go
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/errors.go
sdk/azidentity/errors_test.go
sdk/azidentity/managed_identity_client.go

There is a race between error propagation and closing a context's
deadline channel.  The result is that while the API that takes a context
returns the correct error, context.Err() might return nil.
See https://github.com/golang/go/issues/31863 for more info.

Use underlying error when checking for context errors

---

sdk/data/azappconfig/client_test.go

Ensure key name is unique so it doesn't collide with stale data.
Example: https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/2623568/logs/485
Use sync token to ensure updates are visible, see https://learn.microsoft.com/en-us/azure/azure-app-configuration/rest-api-consistency

Fix flakey live test

---

eng/tools/generator/autorest/model/changelog.go
eng/tools/generator/cmd/v2/common/changelogProcessor.go
eng/tools/generator/cmd/v2/common/changelogProcessor_test.go
eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go
eng/tools/generator/cmd/v2/common/testdata/new/parameter/parameter.go
eng/tools/generator/cmd/v2/common/testdata/old/parameter/parameter.go
eng/tools/generator/cmd/v2/release/releaseCmd.go
eng/tools/generator/config/validate/validator.go

1. tag comes from `Readme Tag` in [release-request](https://github.com/Azure/sdk-release-request) and release-v2 command `--package-config` flag
2. filter function parameters：from interface{} type to any type is not a breaking change

generator release-v2: Automatically write tag into autorest.md and filter function parameters

---

sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/assets.json
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/ci.yml
sdk/storage/azblob/go.mod
sdk/storage/azblob/go.sum
sdk/storage/azblob/internal/testcommon/clients_auth.go
sdk/storage/azblob/pageblob/client_test.go

- Delete containers having immutability policies and legal holds in live test runs
- Add OAuth in azblob pipeline

Cleanup after SetImmutabilityPolicy() and SetLegalHold() tests

---

sdk/azcore/CHANGELOG.md
sdk/azcore/policy/policy.go
sdk/azcore/runtime/policy_retry.go
sdk/azcore/runtime/policy_retry_test.go

Allows for finer-grained control over when to retry.

Add RetryOptions.Predicate field

---

sdk/security/keyvault/azadmin/settings/client_test.go

Deleting extra test from azadmin.
TestUpdateSetting_InvalidUpdateSettingRequest hits the same functionality as TestUpdateSetting_InvalidSettingName, so removing to prevent test conflicts.

[keyvault] delete extra test

---

sdk/messaging/azeventhubs/example_consuming_with_checkpoints_test.go

A customer noticed our example file refers to an constant `ErrorCodeOwnershipLost` by it's `internal/exported` name. This is some fallout from the way that we expose the constants using aliases, and autocomplete.

[azeventhubs] example file was referring to an internal constant

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/appendblob/client.go
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/container/client.go
sdk/storage/azblob/internal/shared/challenge_policy.go
sdk/storage/azblob/internal/shared/challenge_policy_test.go
sdk/storage/azblob/pageblob/client.go
sdk/storage/azblob/pageblob/managed_disk_test.go
sdk/storage/azblob/service/client.go

Resolves https://github.com/Azure/azure-sdk-for-go/issues/20355

Added support for storage managed disk challenge

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity.go
sdk/azidentity/azidentity_test.go
sdk/azidentity/client_assertion_credential.go
sdk/azidentity/client_certificate_credential.go
sdk/azidentity/client_secret_credential.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/on_behalf_of_credential.go
sdk/azidentity/username_password_credential.go

In the current design--as shipped by other Azure SDKs--CAE is on by default. We want to make it opt-in instead but haven't designed the options for that yet.

azidentity: Remove CAE support

---

sdk/storage/azblob/appendblob/client.go
sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/blockblob/client_test.go

There are two tests with the same name and depending on timing, the container might not have finished being deleted.  Use unique names to avoid the race.
Cleaned up linter warnings for error strings.

Use unique container names for tests TestSetBlobTagsWithLeaseId

---

sdk/messaging/azeventhubs/internal/go-amqp/message.go
sdk/messaging/azeventhubs/internal/go-amqp/receiver.go
sdk/messaging/azservicebus/amqp_message.go
sdk/messaging/azservicebus/internal/go-amqp/message.go
sdk/messaging/azservicebus/internal/go-amqp/receiver.go
sdk/messaging/azservicebus/message.go
sdk/messaging/azservicebus/message_test.go
sdk/messaging/azservicebus/receiver.go

One more change from go-amqp to pick up.

EH/SB remove Message.LinkName

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/policy_bearer_token.go
sdk/azcore/arm/runtime/policy_bearer_token_test.go
sdk/azcore/internal/exported/exported.go

The azidentity side of this feature will stay in beta pending a new design. Although I believe the azcore side won't change, I think we shouldn't ship it in a stable version because for the time being using the feature end-to-end will require an azidentity beta.

azcore: Remove CAE support

---

eng/config.json

We're not at the target of 90% set in #15756 but we can document where we're at currently.

[azservicebus,azeventhubs] Updating code coverage numbers to reflect what they are today

---

sdk/internal/CHANGELOG.md
sdk/internal/exported/exported.go
sdk/internal/exported/exported_test.go
sdk/internal/poller/util.go
sdk/internal/poller/util_test.go
sdk/internal/version.go

This simplifies the creation of custom PollerHandler[T] by SDK authors. The payload helpers were also moved as the LRO helpers depend on them. The contents are directly copied from azcore with the exception of the Payload func which adds an options parameter.

Move LRO and payload helpers to the internal module

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/appendblob/client.go
sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/assets.json
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/blob/responses.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/container/client.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/container/models.go
sdk/storage/azblob/container/responses.go
sdk/storage/azblob/pageblob/client.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azblob/service/client.go
sdk/storage/azblob/service/client_test.go

Resolves https://github.com/Azure/azure-sdk-for-go/issues/20537

Added support for get account info in blob and container clients

---

sdk/storage/azblob/blob/client_test.go

Single test contains positive & negative check for user provided MD5 (CopyBlobFromURL has a parameter called SourceContentMD5)

Transaction Validation - Blob Client

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/appendblob/models.go
sdk/storage/azblob/assets.json
sdk/storage/azblob/internal/testcommon/clients_auth.go
sdk/storage/azblob/internal/testcommon/common.go

Added support for copy source authorization to append block from url

---

sdk/storage/azblob/internal/shared/challenge_policy.go
sdk/storage/azblob/internal/shared/challenge_policy_test.go

Note: Changelog entry is not necessary since this hasn't been released yet
I re-ran the test in pageblob/managed_disk_test.go manually and it passed. 

Fixed issue in challenge policy to prevent multiple requests from being sent in the happy case.

---

sdk/azcore/CHANGELOG.md

`TokenRequestOptions.TenantID` field remains and shouldn't be removed; it's part of ARM cross-tenant auth, not the CAE support which was removed.

Fix azcore changelog entry

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_query_response.go
sdk/data/azcosmos/cosmos_query_response_test.go
sdk/data/azcosmos/emulator_cosmos_query_test.go

Value queries like `select value c.id from c` fail to be executed with the error:
```
unmarshalling type *azcosmos.queryServiceResponse: json: cannot unmarshal string into Go struct field queryServiceResponse.Documents of type map[string]interface {}
```
Closes https://github.com/Azure/azure-sdk-for-go/issues/20651

Cosmos DB: Fixes value queries

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/internal/shared/shared.go
sdk/storage/azblob/internal/shared/shared_test.go

HNS accounts do not currently support tags. If a customer passes nil OR and empty map, we should not set the x-ms-tags header.

Fix issue where tags header is passed if map is empty

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/sas/service.go
sdk/storage/azblob/sas/service_test.go

This is necessary for AzCopy tests to support setting tags. 

Added tags permission for container SAS

---

sdk/azcore/arm/policy/policy.go
sdk/azcore/arm/runtime/pipeline.go
sdk/azcore/arm/runtime/policy_bearer_token.go
sdk/azcore/arm/runtime/policy_bearer_token_test.go
sdk/azcore/internal/exported/exported.go
sdk/azidentity/azidentity_test.go
sdk/azidentity/azure_cli_credential.go
sdk/azidentity/azure_cli_credential_test.go
sdk/azidentity/client_assertion_credential.go
sdk/azidentity/client_certificate_credential.go
sdk/azidentity/client_secret_credential.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/on_behalf_of_credential.go
sdk/azidentity/syncer.go
sdk/azidentity/username_password_credential.go

Previously removed these to enable releasing a stable azcore from main without them because end-to-end scenarios require azidentity, which was staying in beta. I plan to ship stable versions of both features next month.

Restore multitenant and ARM cross-tenant authentication API

---

sdk/messaging/azservicebus/internal/go-amqp/sender.go
sdk/messaging/azservicebus/message_batch.go
sdk/messaging/azservicebus/sender.go
sdk/messaging/azservicebus/sender_test.go

Return an error when you try to send a message that's too large.
This now works just like the message batch - you'll get an ErrMessageTooLarge
if you attempt to send a message that's too large for the link's configured
size.
NOTE: there's a patch to `internal/go-amqp/Sender.go` to match what's in go-amqp's
main so it returns a programmatically useful error when the message is too large.
Fixes #20647

[azservicebus] Return ErrMessageTooLarge if a message is too big to send

---

sdk/messaging/azeventhubs/internal/eh/stress/deploy.ps1
sdk/messaging/azeventhubs/internal/eh/stress/templates/stress-test-job.yaml
sdk/messaging/azservicebus/internal/stress/deploy.ps1
sdk/messaging/azservicebus/internal/stress/templates/stress-test-job.yaml

Had a bug in the kubernetes job yaml where I wasn't redirecting stderr which is probably why I sometimes see empty log files for tests that have disappeared.

[azservicebus/azeventhubs] Redirect stderr and stdout to tee

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/checkpoints/blob_store.go
sdk/messaging/azeventhubs/checkpoints/blob_store_test.go
sdk/messaging/azeventhubs/internal/test/test_helpers.go

The checkpoint store wasn't guarding against multiple owners claiming for the first time - fixing this by using IfNoneMatch
Fixes #20717

[azeventhubs] Fixing checkpoint store race condition

---

sdk/resourcemanager/postgresql/armpostgresql/assets.json
sdk/resourcemanager/postgresql/armpostgresql/postgresql_live_test.go
sdk/resourcemanager/postgresql/armpostgresql/privateendpointconnections_live_test.go
sdk/resourcemanager/postgresql/armpostgresql/serversecurityalertpolicies_live_test.go

add sdk/resourcemanager/postgresql/armpostgresql live test

---

sdk/storage/azfile/file/client.go
sdk/storage/azfile/file/models.go
sdk/storage/azfile/lease/examples_test.go
sdk/storage/azfile/service/examples_test.go
sdk/storage/azfile/share/examples_test.go

azfile: Service and share clients examples

---

sdk/messaging/azeventhubs/inmemory_checkpoint_store_test.go
sdk/messaging/azeventhubs/internal/errors.go
sdk/messaging/azeventhubs/processor_load_balancer.go

We shouldn't be resetting the etag to nil - it's what we use to enforce a "single winner" when doing ownership claims.
The bug here was two-fold: I had bad logic in my previous claim ownership, which I fixed in a previous PR, but we need to reflect that same constraint properly in our in-memory checkpoint store for these tests.

[azeventhubs] Improperly resetting etag in the checkpoint store

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/client_assertion_credential.go
sdk/azidentity/client_assertion_credential_test.go
sdk/azidentity/client_certificate_credential.go
sdk/azidentity/client_certificate_credential_test.go
sdk/azidentity/client_secret_credential.go
sdk/azidentity/client_secret_credential_test.go
sdk/azidentity/default_azure_credential.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/device_code_credential_test.go
sdk/azidentity/environment_credential.go
sdk/azidentity/environment_credential_test.go
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/interactive_browser_credential_test.go
sdk/azidentity/on_behalf_of_credential.go
sdk/azidentity/username_password_credential.go
sdk/azidentity/username_password_credential_test.go
sdk/azidentity/workload_identity.go
sdk/azidentity/workload_identity_test.go

Reverting #20674, going back to `DisableInstanceDiscovery` per architect discussions

Revert instance discovery option name change

---

sdk/monitor/azquery/CHANGELOG.md
sdk/monitor/azquery/autorest.md
sdk/monitor/azquery/build.go
sdk/monitor/azquery/logs_client.go
sdk/monitor/azquery/models.go
sdk/monitor/azquery/models_serde.go
sdk/monitor/azquery/version.go

* Update doc comments updates from new swagger commit
* Update statistics and visualization byte generation
* prep for release/update version

[azquery] update doc comments

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/pipeline.go
sdk/azcore/arm/runtime/policy_trace_namespace.go
sdk/azcore/arm/runtime/policy_trace_namespace_test.go
sdk/azcore/core.go
sdk/azcore/core_test.go
sdk/azcore/internal/exported/request.go
sdk/azcore/internal/exported/request_test.go
sdk/azcore/internal/shared/constants.go
sdk/azcore/internal/shared/shared.go
sdk/azcore/policy/policy.go
sdk/azcore/runtime/pager.go
sdk/azcore/runtime/pipeline.go
sdk/azcore/runtime/policy_http_trace.go
sdk/azcore/runtime/policy_http_trace_test.go
sdk/azcore/runtime/poller.go
sdk/azcore/runtime/poller_test.go
sdk/azcore/tracing/tracing.go
sdk/azcore/tracing/tracing_test.go

For the next `azcore` beta.
Previously reviewed in https://github.com/Azure/azure-sdk-for-go/pull/20301

Restore supporting features to enable distributed tracing

---

sdk/azcore/arm/runtime/policy_bearer_token.go
sdk/azcore/arm/runtime/policy_bearer_token_test.go
sdk/azcore/internal/exported/exported.go

This should go into the next azcore beta. The end-to-end feature requires azidentity support which has shipped in v1.3.0-beta.3 but won't be part of the stable v1.3.0.

Restore ARM CAE support

---

sdk/azcore/CHANGELOG.md
sdk/azcore/fake/example_test.go
sdk/azcore/fake/fake.go
sdk/azcore/fake/fake_test.go
sdk/azcore/internal/exported/response_error.go
sdk/azcore/internal/exported/response_error_test.go
sdk/azcore/internal/pollers/fake/fake.go
sdk/azcore/internal/pollers/fake/fake_test.go
sdk/azcore/internal/shared/constants.go
sdk/azcore/internal/shared/shared.go
sdk/azcore/runtime/poller.go
sdk/azcore/runtime/poller_test.go
sdk/azcore/runtime/request.go

This is the supporting infrastructure for the generated SDK fakes.
Partial fix for https://github.com/Azure/azure-sdk-for-go/issues/16613
To be released in the next `azcore` beta.

Add fake package to azcore

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_retry.go
sdk/azcore/runtime/policy_retry_test.go

This ensures that the entirety of the request is restored on retries.

Retry policy will always clone the *http.Request

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/pipeline_test.go
sdk/azcore/arm/runtime/policy_register_rp.go
sdk/azcore/arm/runtime/policy_register_rp_test.go

There's more than one error code returned from unregistered RPs.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/20823

Handle more error codes when an RP isn't registered

---

sdk/monitor/azquery/README.md

Now that the resource-centric logs query feature exists, a workspace isn't required. Update the prereqs section accordingly and making it more consistent with the other languages.

Update logs query prereqs

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client.go
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/share/client.go

Remove trailing slash from directory or subdirectory name

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/policy_register_rp.go
sdk/azcore/arm/runtime/policy_register_rp_test.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/19900

Add another non-standard error code for RP registration

---

sdk/azcore/fake/example_test.go
sdk/azcore/fake/fake.go
sdk/azcore/fake/fake_test.go
sdk/azcore/internal/exported/exported.go
sdk/azcore/internal/exported/request.go
sdk/azcore/internal/shared/constants.go
sdk/azcore/runtime/request.go
sdk/azcore/runtime/response.go

Deeper testing uncovered some deficiencies as well as general API improvements like slight renaming and adding options types.
Marshalling APIs (used by fake server) now take an any type instead of a Responder[T] in order to handle cases where we marshal from a scalar.
Added support for binary, text, and XML formats (binary was halfway there already, supporting form and multipart but not vanilla).
Added support for specifying an HTTP status code in a fake response.
Added and cleaned up various doc comments.

Some refactoring of the fakes package

---

sdk/messaging/azeventhubs/internal/amqpwrap/amqp_error.go
sdk/messaging/azeventhubs/internal/amqpwrap/amqpwrap.go
sdk/messaging/azeventhubs/internal/amqpwrap/amqpwrap_test.go
sdk/messaging/azeventhubs/internal/amqpwrap/mock_amqp_test.go
sdk/messaging/azeventhubs/internal/amqpwrap/rpc.go
sdk/messaging/azeventhubs/internal/cbs_test.go
sdk/messaging/azeventhubs/internal/errors.go
sdk/messaging/azeventhubs/internal/errors_test.go
sdk/messaging/azeventhubs/internal/links_unit_test.go
sdk/messaging/azeventhubs/internal/mock/mock_amqp.go
sdk/messaging/azeventhubs/internal/mock/mock_helpers.go
sdk/messaging/azeventhubs/internal/namespace.go
sdk/messaging/azeventhubs/internal/namespace_test.go
sdk/messaging/azeventhubs/internal/rpc.go
sdk/messaging/azeventhubs/internal/rpc_test.go
sdk/messaging/azeventhubs/internal/test/mock_helpers.go
sdk/messaging/azeventhubs/internal/test/test_helpers.go

Make it so the lower level primitives and errors carry more information about the connection ID, rather than requiring us to shuttle it around externally.
- Adding (AMQPReceiver|AMQPSender|AMQPSession).ConnID() fields (and AMQPClient.ID()) fields.
- Errors are now wrapped immediately when returned from the underlying `amqpwrap` types. This is prep for another issue I found where we'd fail to recover a connection in some cases because we didn't have enough context to do it.
- Moved out some universally useful helpers for gomock into the `test` package (basically, splitting up mock_helpers.go into two files).
- Regenerating mocks

[azeventhubs] Changes to make errors and low level types carry connectionID and linkID

---

sdk/messaging/azeventhubs/consumer_client.go
sdk/messaging/azeventhubs/consumer_client_internal_test.go
sdk/messaging/azeventhubs/internal/amqp_fakes.go
sdk/messaging/azeventhubs/internal/amqpwrap/amqp_error.go
sdk/messaging/azeventhubs/internal/amqpwrap/amqpwrap.go
sdk/messaging/azeventhubs/internal/amqpwrap/amqpwrap_test.go
sdk/messaging/azeventhubs/internal/amqpwrap/mock_amqp_test.go
sdk/messaging/azeventhubs/internal/cbs_test.go
sdk/messaging/azeventhubs/internal/errors.go
sdk/messaging/azeventhubs/internal/links.go
sdk/messaging/azeventhubs/internal/links_test.go
sdk/messaging/azeventhubs/internal/links_unit_test.go
sdk/messaging/azeventhubs/internal/mock/mock_amqp.go
sdk/messaging/azeventhubs/internal/rpc.go
sdk/messaging/azeventhubs/internal/rpc_test.go
sdk/messaging/azeventhubs/partition_client.go
sdk/messaging/azeventhubs/producer_client.go

In Event Hubs, Links runs AMQP operations inside of a retry loop - a failure in the loop will be picked up and checked in the next iteration. One quirk that I introduced here (and not in SB) is that we no-op if you ask to recover and there's no link information. This could cause to waste a retry loop iteration, resulting in unnecessary delays.
The simplest fix here was just to make sure that all errors carry enough information along to allow for recovery in contexts where we didn't get a link, which is what I plumbed in in #20867. I've extended it to also carry PartitionID, which makes full recovery possible.

[azeventhubs] Fixing issue where we'd waste a recovery cycle in some cases

---

sdk/azcore/runtime/policy_bearer_token.go

Deleting a one-off error made redundant by #20866

BearerTokenPolicy uses shared.NonRetriableError()

---

sdk/messaging/azservicebus/admin/admin_client_test.go
sdk/messaging/azservicebus/liveTestHelpers_test.go
sdk/messaging/azservicebus/sender_test.go

Some tests fixes.
- Some of the new DefaultRule tests were defer'ing their cleanup a bit late.
- The ScheduleMessages() tests were inconsistent and relying on way too much internal behavior/timing. I've changed them to be more reliable and only use public behavior.

[azservicebus] Some cleanup in prep for release

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity.go
sdk/azidentity/azidentity_test.go
sdk/azidentity/client_assertion_credential.go
sdk/azidentity/client_certificate_credential.go
sdk/azidentity/client_secret_credential.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/go.mod
sdk/azidentity/go.sum
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/on_behalf_of_credential.go
sdk/azidentity/username_password_credential.go
sdk/azidentity/version.go

Enable CAE by default in azidentity beta

---

sdk/azidentity/azidentity_test.go

Hoping this fixes https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2820123&view=logs&j=7c2e6c09-e0bf-5c90-9850-b294a30ca1c6&t=7e9f3157-adb3-5d75-4c4d-fb078b70e051

Use t.Setenv for setting/unsetting test-specific env vars

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/pipeline_test.go
sdk/azcore/arm/runtime/policy_register_rp.go
sdk/azcore/arm/runtime/policy_register_rp_test.go
sdk/azcore/runtime/policy_retry.go
sdk/azcore/runtime/policy_retry_test.go

Cherry-picked the following commits.
- a3b2c13cc1ead2102feb0bd20c4e304a08812fe1
- 889be5860054a17042773c62f658f655a77fec97
- 6879d7e3f9977286c4b28a52e921ca3343d67ade

Prep azcore v1.6.1 for release

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/policy_trace_namespace.go
sdk/azcore/arm/runtime/policy_trace_namespace_test.go
sdk/azcore/runtime/policy_http_trace.go
sdk/azcore/tracing/tracing.go
sdk/azcore/tracing/tracing_test.go
sdk/tracing/azotel/ci.yml
sdk/tracing/azotel/go.mod
sdk/tracing/azotel/otel.go
sdk/tracing/azotel/otel_test.go

This contains breaking changes against the previous beta.
Fixes the following:
- https://github.com/Azure/azure-sdk-for-go/issues/20924
- https://github.com/Azure/azure-sdk-for-go/issues/20933
- https://github.com/Azure/azure-sdk-for-go/issues/20935

Refactor some public surface in azcore/tracing

---

sdk/security/keyvault/azkeys/CHANGELOG.md
sdk/security/keyvault/azkeys/assets.json
sdk/security/keyvault/azkeys/autorest.md
sdk/security/keyvault/azkeys/client.go
sdk/security/keyvault/azkeys/client_test.go
sdk/security/keyvault/azkeys/constants.go
sdk/security/keyvault/azkeys/example_test.go
sdk/security/keyvault/azkeys/models.go
sdk/security/keyvault/azkeys/models_serde.go
sdk/security/keyvault/azkeys/response_types.go
sdk/security/keyvault/azkeys/testdata/perf/get_key.go
sdk/security/keyvault/azkeys/utils_test.go
sdk/security/keyvault/azkeys/version.go

Renames for azkeys based on feedback

[keyvault] azkeys renames

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/client.go
sdk/azcore/core.go
sdk/azcore/internal/shared/shared.go
sdk/azcore/internal/shared/shared_test.go

SDKs that contain one or more clients in sub-packages could have their module name incorrectly set in the telemetry string.

Fix populating module name in telemetry policy

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/client.go
sdk/azcore/core.go
sdk/azcore/internal/shared/shared.go
sdk/azcore/internal/shared/shared_test.go

Cherry-picked ff8cc21d9da4611312f03232985c7ea1a016b31b

Fix populating module name in telemetry policy (#20967)

---

sdk/tracing/azotel/go.sum
sdk/tracing/azotel/otel.go

Document the version in use.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/20934

Set telemetry schema on tracers

---

eng/scripts/build.ps1
sdk/containers/azcontainerregistry/build.go

The code generator MUST be the ONLY source of this value.

Remove autorest core version from build scripts

---

sdk/storage/azfile/migrationguide.md

azfile: Adding migration guide

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/assets.json
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blob/constants.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/internal/testcommon/clients_auth.go
sdk/storage/azblob/pageblob/client_test.go

1. Added AccessTierCold to constants.go in blob
2. Added tests or updated tests for the following APIs:
- Container - Flat List Blob, Hierarchy List Blobs
- BlockBlob - Upload(), UploadBlobFromURL/PutBlobFromURL(), CommitBlockList()
- Blob - SetTier(), GetPropertiest(), CopyFromURL(), StartCopyFromURL()
3. Test for Inferred Access Tier in premium account in pageblob/client-test.go

[Feature STG 85/86] Cold Tier 

---

sdk/messaging/azeventgrid/assets.json
sdk/messaging/azeventgrid/autorest.md
sdk/messaging/azeventgrid/build.go
sdk/messaging/azeventgrid/ci.yml
sdk/messaging/azeventgrid/client.go
sdk/messaging/azeventgrid/client_custom.go
sdk/messaging/azeventgrid/client_test.go
sdk/messaging/azeventgrid/go.mod
sdk/messaging/azeventgrid/go.sum
sdk/messaging/azeventgrid/models.go
sdk/messaging/azeventgrid/models_serde.go
sdk/messaging/azeventgrid/response_types.go
sdk/messaging/azeventgrid/shared_test.go
sdk/messaging/azeventgrid/test-resources.bicep
sdk/messaging/azeventgrid/time_rfc3339.go

Switch over to using the CloudEvent model from azcore, rather than the generated one. Also, removing some more auto-generated dead code (all in autorest.md).
Completes the entire round-trip for #20970

[azeventgrid] Use the common azcore/messaging/CloudEvent model

---

sdk/cognitiveservices/azopenai/README.md
sdk/cognitiveservices/azopenai/assets.json
sdk/cognitiveservices/azopenai/client_test.go
sdk/cognitiveservices/azopenai/custom_client.go
sdk/cognitiveservices/azopenai/custom_client_test.go
sdk/cognitiveservices/azopenai/examples_client_test.go
sdk/cognitiveservices/azopenai/policy_apikey.go
sdk/cognitiveservices/azopenai/policy_apikey_test.go

Fixing a few things based on feedback from @JeffreyRichter.
- Example had a typo and a hardcoded calculation. 
- Adding a constructor for KeyCredential.

[azopenai] Fixing example's typo, creating a constructor for KeyCredential

---

sdk/security/keyvault/azcertificates/CHANGELOG.md
sdk/security/keyvault/azcertificates/assets.json
sdk/security/keyvault/azcertificates/autorest.md
sdk/security/keyvault/azcertificates/client.go
sdk/security/keyvault/azcertificates/client_test.go
sdk/security/keyvault/azcertificates/constants.go
sdk/security/keyvault/azcertificates/example_test.go
sdk/security/keyvault/azcertificates/models.go
sdk/security/keyvault/azcertificates/models_serde.go
sdk/security/keyvault/azcertificates/response_types.go

Renames for azcertificates based on feedback.
This pull request just contains renames for the module. Exploring the more structural suggestions now for a later pull request.

[keyvault] azcertificates renames

---

sdk/azcore/CHANGELOG.md
sdk/azcore/core.go
sdk/azcore/core_test.go

This allows for multiple clients to share the same underlying pipeline while having the correct client name string in traces.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/20973

Add support for shallow cloning azcore.Client instances

---

sdk/messaging/azeventhubs/internal/cbs.go
sdk/messaging/azeventhubs/internal/links.go
sdk/messaging/azeventhubs/internal/links_recover.go
sdk/messaging/azeventhubs/producer_client.go

chore: pkg imported more than once

---

eng/tools/generator/autorest/generation.go
eng/tools/generator/autorest/model/changelog.go
eng/tools/generator/cmd/v2/common/changelogProcessor_test.go

chore: fmt modify

---

sdk/cognitiveservices/azopenai/assets.json
sdk/cognitiveservices/azopenai/client_chat_completions_test.go
sdk/cognitiveservices/azopenai/client_completions_test.go
sdk/cognitiveservices/azopenai/client_embeddings_test.go
sdk/cognitiveservices/azopenai/client_shared_test.go
sdk/cognitiveservices/azopenai/client_test.go
sdk/cognitiveservices/azopenai/custom_client.go
sdk/cognitiveservices/azopenai/custom_client_test.go
sdk/cognitiveservices/azopenai/custom_models.go
sdk/cognitiveservices/azopenai/sample.env

Also, did some cleanup/moving around of code to make it easier to find tests, etc...
Fixes #21052

[azopenai] Adding in streaming for ChatCompletions, like we have for Completions.

---

sdk/security/keyvault/azsecrets/CHANGELOG.md
sdk/security/keyvault/azsecrets/autorest.md
sdk/security/keyvault/azsecrets/models.go

Updating `azsecrets` so that all [key vault object identifiers](https://learn.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates#object-identifiers) use the module's custom `ID` type.

[keyvault] update ID type

---

sdk/tracing/azotel/CHANGELOG.md
sdk/tracing/azotel/otel.go

This PR allows custom tracer providers to be used by accepting a tracer provider interface, instead of relying on the specific struct used in otelsdk.
For an example scenario, one might want to get the globally configured tracer provider, instead of defining a new one.
```go
sc, err := aztables.NewServiceClientFromConnectionString("...", &aztables.ClientOptions{
ClientOptions: azcore.ClientOptions{
TracingProvider: azotel.NewTracingProvider(otel.GetTracerProvider(), nil),
},
})
```
`otel.GetTracerProvider()` returns the registered global trace provider. If none is registered …

Use otel tracerProvider interface instead of specific type

---

sdk/azidentity/default_azure_credential.go

Pointing out that pipeline options don't apply to credentials like AzureCLICredential which don't use an azcore pipeline

Update DefaultAzureCredentialOptions docs

---

sdk/cognitiveservices/azopenai/assets.json
sdk/cognitiveservices/azopenai/client_chat_completions_test.go
sdk/cognitiveservices/azopenai/client_shared_test.go
sdk/cognitiveservices/azopenai/custom_client_image.go
sdk/cognitiveservices/azopenai/custom_client_image_test.go
sdk/cognitiveservices/azopenai/custom_client_test.go

Code that was handwritten needs to check and return ResponseError's by hand. Added in code to fix this for image generation, and to add in testing for all the areas that have hand-written code (ChatCompletions and Completions streaming and Dall-E integration with OpenAI).
Fixes #21120

[azopenai] Errors weren't propagating properly in image generation for OpenAI

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azure_cli_credential.go
sdk/azidentity/default_azure_credential.go
sdk/azidentity/default_azure_credential_test.go

Closes #21053, though that issue is misleading in that multitenant auth already works for workload identities. This change only makes it easier in the context of DefaultAzureCredential.

DefaultAzureCredential TenantID applies to workload identity

---

eng/pipelines/templates/steps/analyze.yml

The dependency checking tool has some broken corner-cases.  Until those are fixed, we need a flag to skip it in order to release.
See https://github.com/Azure/azure-sdk-for-go/pull/21098#issuecomment-1625580494 for more info on why this is needed.

Add flag to enable skipping of dependency checks

---

sdk/azcore/CHANGELOG.md
sdk/azcore/core.go
sdk/azcore/core_test.go

This allows for multiple clients to share the same underlying pipeline while having the correct client name string in traces.
This is a cherry-pick of 1d8ba7bcb350a85f1f86b388b1847a1fadb9d9e3 with a slightly modified CHANGELOG to reflect the current sequence of releases.  The feature's implementation has also been slightly changed as the current incarnation in `main` was built on features added in the `v1.7.0-beta` series.

Add support for shallow cloning azcore.Client instances (#21065)

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go

Prepare for azcore 1.8.0-beta.1 release

---

sdk/messaging/azeventgrid/go.mod
sdk/messaging/azeventgrid/go.sum

[azeventgrid] Prep for release

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/file/mmf_unix.go

Since DragonFlyBSD is already listed as supported in ed939da099c54c2ae8708bfa0316021d081f36fe , add it to azfile too.

Add DragonFlyBSD in azfile

---

sdk/azidentity/syncer.go

We may as well just have a simple mutex here because the condition is never waited upon; no goroutine calls `Wait()` because locking around the loop guarantees only one goroutine is in the loop at any moment.

Simplify GetToken synchronization

---

.github/CODEOWNERS

The FabricBot rule for @ mentioning people based upon the service label when the **Service Attention** label was added should have been generated from the CODEOWNERS file for each repository. As it turns out, for Go, this wasn't the case. These entries were copied from either Java, JS, Net or Python (don't know, don't care, it was incorrect either way).  github-event-processor uses the CODEOWNERS file to get this information which, because of the aforementioned FabricBot rule copy, was never actually in the CODEOWNERS file. This PR just takes the IssueRouting entries, from the FabricBot.json file that was removed from this repository at the time github-event-processor was enabled and adds them as NotInRepo entries which is the interim fix.

Add Service Labels to CODEOWNERS

---

sdk/azidentity/client_certificate_credential_test.go

Regional STS (westus2 at least) has begun responding with an error when we claim CP1 in a token request: `AADSTS100034: AAD Regional does not support issuing tokens with CAE claims`. This seems weird to me because the prior behavior, silently ignoring the claim, was a deliberate part of the design and harmless so far as I know, however we can just forego the claim in this test because CAE is irrelevant to it.
If your application is affected by this, set environment variable `AZURE_IDENTITY_DISABLE_CP1` to `true` or switch to a stable azidentity version.

Disable CP1 for regional STS test

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity_test.go
sdk/azidentity/azure_cli_credential.go
sdk/azidentity/azure_cli_credential_test.go
sdk/azidentity/client_assertion_credential.go
sdk/azidentity/client_certificate_credential.go
sdk/azidentity/client_secret_credential.go
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/managed_identity_credential.go
sdk/azidentity/mock_test.go
sdk/azidentity/on_behalf_of_credential.go
sdk/azidentity/on_behalf_of_credential_test.go
sdk/azidentity/syncer.go
sdk/azidentity/syncer_test.go
sdk/azidentity/username_password_credential.go
sdk/azidentity/workload_identity_test.go

While refactoring `syncer` to add an internal options bag for an upcoming feature, I noticed a bug that would cause `AzureCLICredential.GetToken()` and `OnBehalfOfCredential.GetToken()` to make a second authentication attempt immediately after their first attempt fails. They should instead return an error because there's no reason to believe a second attempt would succeed and in the case of the `AzureCLICredential`, trying again is particularly expensive.

AzureCLICredential and OnBehalfOfCredential return errors immediately on failure

---

sdk/storage/azblob/assets.json
sdk/storage/azblob/blockblob/constants.go
sdk/storage/azblob/container/client_test.go

Missed adding this simple helper method to access the constants in this PR: https://github.com/Azure/azure-sdk-for-go/pull/21128

Adding PossibleBlobCopySourceTagsValues() Method for CopySourceTags

---

sdk/azidentity/azidentity_test.go
sdk/azidentity/client_assertion_credential_test.go
sdk/azidentity/client_certificate_credential_test.go
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/device_code_credential_test.go
sdk/azidentity/environment_credential_test.go
sdk/azidentity/interactive_browser_credential_test.go
sdk/azidentity/live_test.go
sdk/azidentity/managed_identity_client_test.go
sdk/azidentity/managed_identity_credential_test.go
sdk/azidentity/mock_test.go
sdk/azidentity/workload_identity_test.go

Simplifying mocking, improving manual test output

azidentity test cleanup

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/assets.json
sdk/storage/azblob/service/client.go
sdk/storage/azblob/service/client_test.go
sdk/storage/azblob/service/models.go

Added System to ListContainersInclude to allow listing of system contain (i.e., '$logs').

List System Containers

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_http_trace.go
sdk/azcore/tracing/tracing.go
sdk/azcore/tracing/tracing_test.go

The method has been in GA since v1.2.0 so we can't change it.
Thanks to @heaths for pointing this out.

Revert breaking change to Span.End()

---

sdk/storage/azqueue/CHANGELOG.md
sdk/storage/azqueue/queue_client_test.go
sdk/storage/azqueue/sas/service.go
sdk/storage/azqueue/sas/service_test.go

azqueue: SAS creation fix when stored access policy is used

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/sas/service.go
sdk/storage/azfile/sas/service_test.go
sdk/storage/azfile/share/client_test.go

azfile: SAS creation fix when stored access policy is used

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/sas/service.go
sdk/storage/azblob/sas/service_test.go

This PR will fix https://github.com/Azure/azure-sdk-for-go/issues/21229
In addition it adds non-existing unit tests for the fixed method.

[azblob][sas] Fix SignWithSharedKey if stored access policy is used  @stotz89

---

sdk/internal/telemetry/telemetry_test.go

Regexp checks for major, minor and patch level, but fails with golang release candidate versions, as doesn't match regexp.
Example:
azsdk-go-azservicebus/v1.0.0 (go1.21rc3; linux)
- [] The purpose of this PR is explained in this or a referenced issue.
- [] Updates to [CHANGELOG.md][] are included.

[internal] Extend telemetry test regexp

---

sdk/internal/perf/recording_test.go
sdk/internal/recording/matchers_test.go
sdk/internal/recording/recording_test.go
sdk/internal/recording/server.go
sdk/internal/recording/server_test.go

Marking this well known test proxy variable private to lower public api surface area.

Make recording.proxyManualStartEnv private

---

sdk/azcore/runtime/examples_test.go

Improve example for runtime.WithCaptureResponse

---

sdk/ai/azopenai/CHANGELOG.md
sdk/ai/azopenai/event_reader.go
sdk/ai/azopenai/event_reader_test.go

Return the result of reader.Close() to the caller.

Don't swallow error on Close()

---

sdk/ai/azopenai/example_client_getchatcompletions_test.go
sdk/ai/azopenai/example_client_getcompletions_test.go

The EventReader is the reader for the body when streaming results. Not closing it leaks resources.

[azopenai] Make sure we defer close the eventreader in our examples.

---

eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go

The major version was upgraded when the fake was generated, and the module in fake _server.go needs to be replaced.

Major version upgrade when processing fake

---

eng/tools/generator/cmd/v2/release/releaseCmd.go
eng/tools/generator/template/rpName/packageName/README.md.tpl

When using `generateFromRequest`, encountering a generate error does not directly panic.

generator tool fix

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/sas/account.go
sdk/storage/azblob/sas/query_params.go
sdk/storage/azblob/sas/service.go

Adding encryption sas to blob, account, and identity sas

Encryption Scope SAS

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/file/constants.go
sdk/storage/azfile/file/models.go
sdk/storage/azfile/internal/exported/copy_file_smb_options.go

* Added `x-ms-file-change-time` request header in
* Create File/Directory
* Set File/Directory Properties
* Copy File
* Added `x-ms-file-last-write-time` request header in Put Range and Put Range from URL.

azfile: Additional header support

---

sdk/storage/azblob/blockblob/client_test.go

Test to test the encryption scope support for CopyFromURL

Test Encryption Scope support for Sync Blob Copy (SyncCopyFromUrl) 

---

sdk/ai/azopenai/CHANGELOG.md
sdk/ai/azopenai/custom_models_test.go
sdk/ai/azopenai/event_reader.go
sdk/ai/azopenai/event_reader_test.go

If the scanner reaches the end of stream and we haven't gotten the '[done]' token then return an error instead of silently failing.
Minor stuff:
- Fixing casing of error message - shouldn't have a leading uppercase letter.
- Fixing misspelled comment

[azopenai] EventReader should return an error if the stream is closed

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/internal/testcommon/clients_auth.go
sdk/storage/azfile/lease/client_test.go
sdk/storage/azfile/sas/account.go
sdk/storage/azfile/sas/query_params.go
sdk/storage/azfile/sas/query_params_test.go
sdk/storage/azfile/service/client_test.go

Updated the SAS Version to `2022-11-02` and added `Encryption Scope` to Account SAS.

azfile: Add encryption scope in account SAS

---

sdk/storage/azblob/assets.json
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/internal/generated/models.go

- Test to check that invalid blob names are parsed correctly when List Flat & List Hierarchy 
- Changed decoding behavior from `base64.StdEncoding.DecodeString` to `url.QueryUnescape` because of error message `unmarshalling type *generated.ListBlobsFlatSegmentResponse: illegal base64 data at input byte 4`

Test List Blobs Fix for Invalid XML Characters 

---

sdk/azidentity/client_assertion_credential_test.go
sdk/azidentity/environment_credential_test.go
sdk/azidentity/managed_identity_client_test.go
sdk/azidentity/managed_identity_credential_test.go
sdk/azidentity/workload_identity_test.go

This increases coverage by ~3% by testing some error cases. Closes #18980

Increase azidentity test coverage

---

sdk/cognitiveservices/azopenai/CHANGELOG.md
sdk/cognitiveservices/azopenai/go.mod
sdk/cognitiveservices/azopenai/version.go

Formally retract this package. Retracting the entire range (first to last release) will also delist it from pkg.go.dev.
Second to last part of #21260

[azopenai] Retract old congitiveservices/azopenai package.

---

sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_client_test.go

This makes the message more helpful, especially when the client gets a response from something other than IMDS. Closes #19510

Include response body in IMDS 400 error message

---

sdk/security/keyvault/azadmin/settings/client_test.go

Having test pipeline failures with the KeyVault Administration service. Not getting consistent error codes from the service, so changing to check that an error was thrown instead of the specific error message.

[keyvault] azadmin fix tests

---

sdk/azcore/arm/runtime/policy_bearer_token.go
sdk/azcore/arm/runtime/policy_bearer_token_test.go

CAE is now disabled by default, so clients for RPs like ARM which support CAE must declare explicitly opt in. I renamed `acquire` to clarify that it's called only for auxiliary tenants. This would be an important distinction if it turns out we shouldn't request CAE tokens from auxiliary tenants.

ARM auth policy opts in to CAE

---

sdk/storage/azblob/CHANGELOG.md

Minor updates to changelog

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/file/client_test.go

azfile: Trailing dot support

---

sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/internal/generated/models.go

azfile: Support for invalid XML characters

---

sdk/data/azcosmos/cosmos_container.go

Updated `cosmos_container.go`: `PatchItem` function to respect `enableContentResponseOnWrite` option similar to how it is handled in `CreateItem`, `ReplaceItem`
Issue for this bugfix: https://github.com/Azure/azure-sdk-for-go/issues/21389

Updated cosmos_container.go: PatchItem function to respect enableContentResponseOnWrite 

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_http_trace.go
sdk/azcore/runtime/policy_http_trace_test.go

The inner SDK span must be omitted.  However, any REST span it creates must be a child of the outer SDK method span.
https://azure.github.io/azure-sdk/general_implementation.html#distributed-tracing

Suppress nested SDK method spans

---

sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/zz_blob_client.go
sdk/storage/azblob/internal/generated/zz_constants.go
sdk/storage/azblob/internal/generated/zz_response_types.go

Regenerating AzBlob to STG 87-90

---

sdk/azidentity/default_azure_credential.go
sdk/azidentity/default_azure_credential_test.go

The helper I'm deleting implies that `NewDefaultAzureCredential` should return an error when all the constructors it calls return errors. That sounds good but never happens for a couple reasons:
1. the check for "all constructors returned errors" is whether the slice of constructed credentials is empty, but it never is because failed constructors are represented therein by instances of `defaultCredentialErrorReporter`
2. it isn't possible for all these constructors to return errors because `NewAzureCLICredential` never does
We could fix reason 1, but reason 2 means doing so would just preserve dead code.
Closes #21301

Remove dead code in NewDefaultAzureCredential error handling

---

sdk/security/keyvault/azadmin/CHANGELOG.md
sdk/security/keyvault/azcertificates/autorest.md
sdk/security/keyvault/azcertificates/constants.go
sdk/security/keyvault/azcertificates/models.go
sdk/security/keyvault/azkeys/CHANGELOG.md
sdk/security/keyvault/azkeys/autorest.md
sdk/security/keyvault/azkeys/constants.go
sdk/security/keyvault/azkeys/example_test.go
sdk/security/keyvault/azkeys/models.go
sdk/security/keyvault/azkeys/response_types.go
sdk/security/keyvault/azsecrets/CHANGELOG.md

When we changed some of the names, not all the doc comments were changed to match the new names. This pull request that issue and updates the doc comments

[keyvault] fix doc comments

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/assets.json
sdk/storage/azdatalake/directory/client.go
sdk/storage/azdatalake/directory/client_test.go
sdk/storage/azdatalake/file/client.go
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/filesystem/client.go
sdk/storage/azdatalake/internal/shared/policy_include_blob_response.go
sdk/storage/azdatalake/service/client.go

This is duplication of the azcore includeResponsePolicy, this is necessary for some APIs like directory/file
GetProperties. Under the hood, these APIs grab the raw response to construct the datalake properties
(owner, group, permission) in addition to the blob properties. If we use the includeResponsePolicy, this can
result in the customer not being able to retrieve the response themselves.

Fixed issue where customers could not capture response of directory and file GetProperties calls

---

sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/constants.go
sdk/storage/azblob/internal/generated/zz_appendblob_client.go
sdk/storage/azblob/internal/generated/zz_blob_client.go
sdk/storage/azblob/internal/generated/zz_blockblob_client.go
sdk/storage/azblob/internal/generated/zz_container_client.go
sdk/storage/azblob/internal/generated/zz_pageblob_client.go
sdk/storage/azblob/internal/generated/zz_service_client.go

Created an enum `ServiceVersion` to make it easier to update the service version.
`ServiceVersion` replaces all instances of `[]string{"2021-12-02"}` in blob, appendblob, blockblob, pageblob, container, and service client.

Update AzBlob Service Version to 2023-08-03

---

sdk/security/keyvault/azkeys/test-resources.json

Part of https://github.com/Azure/azure-sdk-for-go/issues/20750
Changing region for azkeys to region with more capacity.

[azkeys] change managed hsm region

---

sdk/security/keyvault/azadmin/test-resources.json

Part of https://github.com/Azure/azure-sdk-for-go/issues/20750
Changing the region for azadmin to a region with more capacity.

[azadmin] change managed hsm region 

---

sdk/storage/azfile/fileerror/error_codes.go
sdk/storage/azfile/internal/generated/autorest.md
sdk/storage/azfile/internal/generated/zz_response_types.go
sdk/storage/azfile/internal/generated/zz_share_client.go
sdk/storage/azfile/service/client_test.go
sdk/storage/azfile/share/client_test.go

azfile: API View feedback

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_client_test.go

We want credential chains to try their next credential, if any, when a managed identity isn't available i.e., we want `ManagedIdentityCredential` to return `credentialUnavailableError`. This requires a special case for Docker Desktop containers because some component of that infrastructure responds 403 Forbidden to IMDS token requests. Closes #21417

Handle Docker Desktop 403 response from IMDS endpoint

---

eng/pipelines/templates/jobs/archetype-go-release.yml
eng/pipelines/templates/steps/build-test.yml
eng/scripts/Replace-azcore.ps1

Off by default, set Use.AzcoreFromMain to true to enable.

Add option to use azcore from main in CI

---

eng/pipelines/templates/jobs/archetype-go-release.yml
eng/pipelines/templates/steps/build-test.yml
eng/pipelines/templates/variables/globals.yml
eng/scripts/Build_Perf.ps1

This ensures that any updated dependencies are propagated.

Execute go mod tidy for perf tests when using live azcore

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/message.go
sdk/messaging/azservicebus/message_test.go
sdk/messaging/azservicebus/receiver_test.go

[azservicebus] Add a helper function to get a Message from a ReceivedMessage

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/internal/atom/entity_manager.go
sdk/messaging/azservicebus/internal/atom/entity_manager_test.go

Previously we were setting request.Raw().Body directly, instead of using the request.SetBody() function. 
This made it so the request body itself was no longer rewindable, which made subsequent requests send an empty body instead.
Fixes #21489

[azservicebus] Fixing issue where the body was populated incorrectly, making it empty on retries since it can't be rewound.

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go

The target branch was created by branching from tag `sdk/azcore/v1.7.1` and the following commits were cherry-picked.
https://github.com/Azure/azure-sdk-for-go/commit/68baa6f9cc9838b3ff5f4ab7661f4330947674c1
https://github.com/Azure/azure-sdk-for-go/commit/5b55febc172332cc903e396f5c6dedad7ad6a543

Prep azcore v1.7.2 for release

---

sdk/azidentity/confidential_client.go

#21333 made constructing MSAL clients and setting a credential's regional endpoint lazy. It's better to set the endpoint in the credential constructor so the value is predictable regardless of when the credential constructs MSAL clients.

Set confidential client region at construction

---

eng/scripts/Language-Settings.ps1

`Get-GoModuleVersionInfo` logs a warning for modules lacking version info, such as our perf test harnesses. This produces many irrelevant warnings:
These are irrelevant because we don't ship anything in `**/testdata/*`. It seems excessive to add whatever artifacts are needed to satisfy the script(s), so how about having the script(s) simply skip over these modules?

Skip getting module properties for **/testdata/*

---

sdk/data/azappconfig/CHANGELOG.md
sdk/data/azappconfig/client.go
sdk/data/azappconfig/constants.go
sdk/data/azappconfig/options.go
sdk/data/azappconfig/response_types.go
sdk/data/azappconfig/setting.go
sdk/data/azappconfig/setting_selector.go
sdk/data/azappconfig/version.go

Moved options and response types to their respective files. Moved methods on Setting to its respective file.
Inlined various from* conversion funcs to their call sites. Renamed paged response types to have the Response suffix per guidelines. Fixed an issue parsing the time value returned in the Last-Modified header. The expected format was incorrect and the error was previously silently dropped.

Some refactoring of azappconfig

---

sdk/data/azappconfig/assets.json
sdk/data/azappconfig/client.go
sdk/data/azappconfig/client_test.go
sdk/data/azappconfig/options.go
sdk/data/azappconfig/response_types.go

Improved docs on some APIs.
Simplify handling of optional params type.
Use context.Background() in tests.
Added test for setting with nil value.
Fix sort order of fields in options and response types.

Some azappconfig cleanup

---

sdk/data/azappconfig/CHANGELOG.md
sdk/data/azappconfig/assets.json
sdk/data/azappconfig/client_test.go
sdk/data/azappconfig/policy_hmac_auth.go

URL.Path contains the decoded path which can be different from the path used in the HTTP request.  As a result, the string-to-sign doesn't match the request, causing it to fail with a 401 unauthorized.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/19874

Fix string-to-sign when path contains URL-encoded values

---

sdk/azcore/CHANGELOG.md
sdk/azcore/core.go
sdk/azcore/core_test.go
sdk/azcore/internal/exported/exported.go
sdk/azcore/internal/exported/exported_test.go
sdk/azcore/runtime/policy_key_credential.go
sdk/azcore/runtime/policy_key_credential_test.go
sdk/azcore/runtime/policy_sas_credential.go
sdk/azcore/runtime/polilcy_sas_credential_test.go

Includes supporting pipeline policies, config options, etc.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/20541

Add KeyCredential and SASCredential types

---

sdk/data/azappconfig/client.go
sdk/data/azappconfig/internal/auth/policy_hmac_auth.go
sdk/data/azappconfig/internal/auth/policy_hmac_auth_parse_test.go

Move the HMAC auth policy to an internal package

---

sdk/data/azappconfig/assets.json
sdk/data/azappconfig/internal/auth/policy_hmac_auth.go

Rewind the body instead. And if it was nil, leave it as nil. Removed some unnecessary local vars.

Don't recreate body after reading

---

sdk/data/azappconfig/CHANGELOG.md
sdk/data/azappconfig/internal/auth/policy_hmac_auth.go
sdk/data/azappconfig/internal/auth/policy_hmac_auth_test.go

Include failure details instead of a generic error message. Some other minor cleanup.

Return specific errors when parsing connection strings

---

sdk/data/azappconfig/CHANGELOG.md
sdk/data/azappconfig/internal/synctoken/policy.go
sdk/data/azappconfig/internal/synctoken/policy_test.go

Some responses, e.g. http.StatusBadRequest, won't return a Sync-Token.

Check for Sync-Token before updating the cache

---

sdk/azidentity/assets.json
sdk/azidentity/authentication_record.go
sdk/azidentity/authentication_record_test.go
sdk/azidentity/azidentity_test.go
sdk/azidentity/confidential_client.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/errors.go
sdk/azidentity/go.mod
sdk/azidentity/go.sum
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/public_client.go
sdk/azidentity/username_password_credential.go

This API lets applications access data cached during previous executions and control when interactive authentication happens. Usage looks like this in application code (with `TokenCachePersistenceOptions` from #21244):
```go
cred, err := azidentity.NewInteractiveBrowserCredential(&azidentity.InteractiveBrowserCredentialOptions{
// By default, credentials begin interactive authentication whenever necessary. Set this option to
// have the credential's GetToken method instead return an error when user interaction is necessary.
DisableAutomaticAuthentication: true,
// By default, credentials cache in memory. Set TokenCachePersistenceOptions to enable persistent caching.
TokenCachePersistenceOptions: &azidentity.TokenCachePersistenceOptions{
// optionally, set Name to isolate this credential's …
```

User authentication API

---

sdk/ai/azopenai/CHANGELOG.md
sdk/ai/azopenai/autorest.md
sdk/ai/azopenai/client_chat_completions_test.go
sdk/ai/azopenai/models.go
sdk/ai/azopenai/models_serde.go

APIView: [link](https://apiview.dev/Assemblies/Review/aac23326de874fd39ce9e7332f95a2f7?diffRevisionId=fbb72eb82b6b4070b0cc18aca589bb15&diffOnly=False&revisionId=4b7e6fffcf6042578f5490a4526194ac&doc=False)

[azopenai] prep release

---

sdk/azidentity/ci.yml
sdk/azidentity/test-resources-pre.ps1

Updating the identity live tests to remove logic and env setting from yaml in favor of a dedicated keyvault config. This will make it possible to improve local and sovereign cloud testing, and make cross-language config updates more easily.
Related: https://github.com/Azure/azure-sdk-for-net/pull/38473

Use identity subscription config and pre script for live test variables

---

sdk/azidentity/assets.json
sdk/azidentity/azidentity_test.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/interactive_browser_credential.go
sdk/azidentity/public_client.go
sdk/azidentity/username_password_credential.go

Credentials which authenticate users need to pass AuthenticationRecords to the public client so it can access previously cached data.

Add AuthenticationRecord to publicClientOptions

---

sdk/ai/azopenai/ci.yml
sdk/ai/azopenai/test-resources.bicep

Use subscription configuration variables for openai live tests

---

eng/config.json
sdk/azidentity/cache/CHANGELOG.md
sdk/azidentity/cache/LICENSE.txt
sdk/azidentity/cache/README.md
sdk/azidentity/cache/linux.go
sdk/azidentity/cache/linux_test.go
sdk/azidentity/cache/mock_test.go
sdk/azidentity/cache/windows_test.go

This skips testing the Linux persistent cache implementation when it isn't useable, as in our CI where the user who executes tests apparently isn't allowed to write files. Skipping those tests requires setting a low coverage bar. I also added a changelog, readme and license file to get the analyze job passing.

Fix azidentity/cache CI

---

eng/scripts/Language-Settings.ps1

Similarly to #21510, this PR prevents spurious warnings by skipping another tree containing unversioned modules we never ship.

Skip getting module properties for sdk/samples/*

---

sdk/messaging/azeventgrid/publisher/client_test.go

Copy/paste error from another PR.

[azeventgrid] Use CE instead of EG (otherwise we're generating a SAS based on a separate topic)

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/internal/exported/smb_property.go

This is fixing a bug introduced in this PR. https://github.com/Azure/azure-sdk-for-go/commit/0c1dfe5e2c8f27f557e67b39ba8d74618533634d#diff-b94011e17ec4244b354bbf2cdfdec36490abd7480e993f4879e3b4a649b46705R42

Defensively trim suffix and prefix of | to prevent invalid attributes

---

sdk/azidentity/README.md
sdk/azidentity/TOKEN_CACHING.MD

This doc, largely copied from other SDKs, describes in detail how credentials cache tokens. Closes #19358, closes #19660, closes #21343

Document azidentity token caching

---

sdk/storage/azfile/test-resources.json

This PR Modifies the storage ARM template to point to built-in Files RBAC role

Modified ARM template to built-in Files RBAC role

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_logging.go
sdk/azcore/runtime/policy_logging_test.go

Don't canonicalize HTTP headers when logging

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/policy_trace_namespace.go
sdk/azcore/runtime/policy_http_trace.go
sdk/azcore/runtime/policy_http_trace_test.go

Unwrap *url.Error types to avoid disclosure of unsanitized URLs. Skip generating trace info for no-op tracers.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/21783

Include error message in traces when transport fails

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

We missed a spot extending the `-timeout` argument to `go test` so overridden values aren't getting plumbed through.

Plumb TestRunTime parameter through job generation template

---

sdk/ai/azopenai/ci.yml
sdk/ai/azopenai/client_audio_test.go
sdk/ai/azopenai/client_shared_test.go

Raising the test timeout. We work across two APIs, both of which can be on the slower side and as I write more tests, push us over the default 15m limit.

[azopenai] Increasing test time to account for longer/slower API calls.

---

sdk/azcore/CHANGELOG.md
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/runtime/transport_default_http_client.go
sdk/azcore/testdata/perf/go.mod
sdk/azcore/testdata/perf/go.sum

If the health check fails, the connection will be closed and a new one created.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/21346

Enable health checks for HTTP/2 connections

---

sdk/messaging/azeventhubs/example_consumerclient_test.go
sdk/messaging/azeventhubs/example_producerclient_test.go
sdk/messaging/azservicebus/example_client_test.go
sdk/messaging/azservicebus/migrationguide.md

DefaultAzureCredential is great for getting started but, ultimately, users are expected to look at other more specific credentials. I've added in some text to the spots in our examples (and migration guide) that mention it, with a pointer to the docs so they can figure out what the right credential type is.
Fixes #21504

[azservicebus] Update some of the areas where we mention the DefaultAzureCredential

---

sdk/messaging/azservicebus/client.go
sdk/messaging/azservicebus/receiver.go
sdk/messaging/azservicebus/sender.go
sdk/messaging/azservicebus/session_receiver.go

According to https://github.com/Azure/azure-sdk-for-go/issues/19758, customers are sometimes confused about the feature altogether. Adding in a link to the longer-form description from the Service Bus team.
Fixes #16897

[azservicebus] Updating to include link to the message browsing documentation.

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_bearer_token.go
sdk/azcore/runtime/policy_bearer_token_test.go
sdk/azcore/runtime/policy_key_credential.go
sdk/azcore/runtime/policy_key_credential_test.go
sdk/azcore/runtime/policy_sas_credential.go
sdk/azcore/runtime/policy_sas_credential_test.go

Return consistent error message for all failed HTTPS checks. Fix misspelled file name.

Require TLS protected endpoints for key and SAS authentication

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_bearer_token.go
sdk/azcore/runtime/policy_bearer_token_test.go
sdk/azcore/runtime/policy_key_credential.go
sdk/azcore/runtime/policy_key_credential_test.go
sdk/azcore/runtime/policy_sas_credential.go
sdk/azcore/runtime/policy_sas_credential_test.go

Just skip the authorization step.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/21821

Don't panic on a nil credential value

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/exported/response_error.go
sdk/azcore/internal/exported/response_error_test.go

If RawResponse is nil (unit test scenarios), print "Missing RawResponse" instead of panicing.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/21838

Prevent panic in ResponseError.Error()

---

sdk/azcore/CHANGELOG.md
sdk/azcore/fake/fake.go
sdk/azcore/fake/fake_test.go
sdk/azcore/fake/internal/exported/fake.go
sdk/azcore/fake/internal/exported/fake_test.go

Fetching the next page, or an error, is predicated on the page response's next link field being populated.
Always set the next link field even if the next "page" is an error response.

Don't omit trailing error response for fake pages

---

sdk/internal/errorinfo/errorinfo_test.go

This PR adds testing functionality to unwrap an error of type NonRetriable.

add unwrap test scenario to NonRetriable

---

sdk/internal/CHANGELOG.md
sdk/internal/version.go

Releases non-retriable error wrapper for /sdk

Release non-retriable error wrapper. v1.5.0

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/policy_bearer_token_test.go
sdk/azcore/arm/runtime/policy_register_rp.go
sdk/azcore/internal/shared/shared.go
sdk/azcore/internal/shared/shared_test.go
sdk/azcore/runtime/policy_bearer_token.go
sdk/azcore/runtime/policy_http_trace.go
sdk/azcore/runtime/policy_http_trace_test.go

This prevents things like custom HTTP headers from showing up in an authentication request.
Removed duplicate import from a test.
Fixes:
- https://github.com/Azure/azure-sdk-for-go/issues/21784
- https://github.com/Azure/azure-sdk-for-go/issues/21847

Deny context values from flowing across disjoint requests

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/runtime/policy_trace_namespace.go
sdk/azcore/core.go
sdk/azcore/core_test.go
sdk/azcore/internal/shared/constants.go
sdk/azcore/runtime/pipeline.go

Use a shared constant for the tracing namespace attribute.

Consolidate tracing options within pipeline options

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/assets.json
sdk/azidentity/live_test.go
sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_credential_test.go

Though Azure ML doesn't directly support deploying Go, this support in the SDK will enable using Go tools in Azure ML compute environments, for example to move data (see #21396).

Support Azure ML managed identity

---

sdk/azidentity/azidentity.go

Rune comparison is faster and doesn't allocate:
```
BenchmarkValidTenantID/regex-8            205578                 5057 ns/op         2552 B/op         38 allocs/op
BenchmarkValidTenantID/runes-8          17023394                63.21 ns/op            0 B/op          0 allocs/op
```

Replace regex match with rune comparison

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/client.go
sdk/azcore/arm/client_test.go
sdk/azcore/core.go
sdk/azcore/core_test.go
sdk/azcore/internal/shared/shared.go
sdk/azcore/internal/shared/shared_test.go
sdk/azcore/tracing/tracing.go

Per spec, the tracer name should be the name of the module. Removed some unnecessary code.

Rename clientName param to moduleName

---

sdk/azcore/runtime/policy_telemetry.go
sdk/azcore/runtime/policy_telemetry_test.go

If a fully qualified module name is provided.

Strip off package name for telemetry policy

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/file/constants.go
sdk/storage/azfile/file/models.go

CRC64 not optional in UploadRangeFromURL

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/appendblob/client.go
sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/internal/base/clients.go
sdk/storage/azblob/internal/testcommon/clients_auth.go
sdk/storage/azblob/pageblob/client.go
sdk/storage/azblob/pageblob/client_test.go

This PR contains the following fixes/features - 
1. Expose GetSASURL on specialized clients - This will let customers call getSASUrl without creating outer BlobClient
2. client.BlobClient() should pass the credential as well.

azblob: Added support for getSASURL from specialized clients

---

documentation/developer_setup.md
sdk/security/keyvault/azcertificates/utils_test.go
sdk/security/keyvault/azkeys/utils_test.go
sdk/security/keyvault/azsecrets/utils_test.go

- Fix keyvault tests using recording options with correct process port - we were using the default options which don't include the newly assigned proxy port
- Fix tabs in developer setup docs

Fix keyvault test recording options. Update docs

---

sdk/azidentity/client_certificate_credential_test.go

Our SNI cert has expired and we may not be able to get a new one. Pending a final determination on that point (#21988), let's skip these live tests. We don't really need them and can continue using the recordings for coverage.

Skip live SNI authentication tests

---

sdk/storage/azblob/bloberror/error_codes.go

It is not listed in https://learn.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes but it occurs when you try to delete the "delete marker" version of a blob i.e. when `NewListBlobsFlatPager`->`ListBlobsInclude` has `DeletedWithVersions` and the blob version with `HasVersionsOnly=true` is attempted to be deleted.
Same with `ImmutabilityPolicyDeleteOnLockedPolicy` - which happens when trying to remove an immutability policy from a blob when it's a locked policy

Add `OperationNotAllowedOnRootBlob` & `ImmutabilityPolicyDeleteOnLockedPolicy` to blob errors

---

sdk/internal/CHANGELOG.md
sdk/internal/recording/recording.go
sdk/internal/recording/recording_test.go
sdk/internal/recording/testdata/recordings/TestRecording/TestGenerateAlphaNumericID.json

Things like LROs can use the original HTTP request when polling, so we must ensure that the *http.Request associated with a *http.Response has the correct scheme and host.

Restore scheme/host when recording HTTP(S)

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blockblob/chunkwriting.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/internal/shared/shared.go

azblob: Return io.ErrUnexpectedEOF as error in UploadStream

---

sdk/storage/azblob/blob/models.go
sdk/storage/azblob/common.go
sdk/storage/azblob/internal/exported/exported.go
sdk/storage/azdatalake/common.go
sdk/storage/azdatalake/file/models.go
sdk/storage/azdatalake/internal/exported/exported.go
sdk/storage/azfile/file/models.go
sdk/storage/azfile/internal/exported/exported.go

storage: Doc fix

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go
sdk/azcore/internal/shared/shared.go
sdk/azcore/internal/shared/shared_test.go

Include the headers that provide sub-second granularity.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/22120

Add more retry after headers to check during retries

---

sdk/ai/azopenai/CHANGELOG.md
sdk/ai/azopenai/assets.json
sdk/ai/azopenai/autorest.md
sdk/ai/azopenai/client_chat_completions_test.go
sdk/ai/azopenai/client_functions_test.go
sdk/ai/azopenai/constants.go
sdk/ai/azopenai/custom_models.go
sdk/ai/azopenai/interfaces.go
sdk/ai/azopenai/models.go
sdk/ai/azopenai/models_serde.go
sdk/ai/azopenai/polymorphic_helpers.go

- Fixing issue where the response format is actually an object, not a string.
- Adding models for ToolChoice

[azopenai] Fixing some issues with incorrect/incomplete types in generation

---

eng/config.json
sdk/ai/azopenai/assets.json
sdk/ai/azopenai/client_audio_test.go
sdk/ai/azopenai/client_chat_completions_test.go
sdk/ai/azopenai/client_shared_test.go

- Do proper test recordings for audio so we can enable those.
- Bring back vision, and also target Azure.
Overall, this brings our test coverage back up to 32% from 24%.
Fixes #21598

[azopenai] Re-enable tests that were temporarily disabled

---

sdk/data/azcosmos/cosmos_global_endpoint_manager.go
sdk/data/azcosmos/cosmos_global_endpoint_manager_test.go
sdk/data/azcosmos/cosmos_location_cache.go
sdk/data/azcosmos/cosmos_location_cache_test.go
sdk/data/azcosmos/cosmos_paths.go
sdk/data/azcosmos/emulator_cosmos_global_endpoint_manager_test.go
sdk/data/azcosmos/shared_key_credential.go
sdk/data/azcosmos/shared_key_credential_test.go

Adds the global endpoint manager to the SDK. For now it's just the basic functionality, exposing the location cache methods to the GEM and adding the API request to fetch the database account information. Issue: https://github.com/Azure/azure-sdk-for-go/issues/18983
Next steps would be to develop the policy that uses the global endpoint manager to refresh account information every 5 minutes, as well as making changes to the first call to fetch the database account information in order to include retries to any preferred regions set.
Closes https://github.com/Azure/azure-sdk-for-go/issues/18983

[Cosmos] Add Global Endpoint Manager

---

eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go

https://github.com/Azure/azure-sdk-for-go/issues/22131

Added replaceReadmeModule function

---

sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/internal/generated/autorest.md
sdk/storage/azfile/internal/generated/constants.go
sdk/storage/azfile/internal/generated/zz_constants.go
sdk/storage/azfile/internal/generated/zz_directory_client.go
sdk/storage/azfile/internal/generated/zz_file_client.go
sdk/storage/azfile/internal/generated/zz_models.go
sdk/storage/azfile/internal/generated/zz_service_client.go
sdk/storage/azfile/internal/generated/zz_share_client.go

azfile: STG 91 code generation

---

sdk/internal/CHANGELOG.md
sdk/internal/exported/exported.go
sdk/internal/exported/exported_test.go

Treat a nil response body as no body.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/22147

Prevent panic in exported.Payload

---

README.md

Add notice for version 1 deprecation

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/file/examples_test.go

azfile: Upload range from URL using OAuth tests

---

sdk/resourcemanager/connectedvmware/armconnectedvmware/CHANGELOG.md
sdk/resourcemanager/connectedvmware/armconnectedvmware/README.md
sdk/resourcemanager/connectedvmware/armconnectedvmware/autorest.md
sdk/resourcemanager/connectedvmware/armconnectedvmware/constants.go

https://github.com/Azure/azure-sdk-for-go/issues/22158
The `NewVirtualMachinesClient` function was removed in v1.0.0.

fix sdk/resourcemanager/connectedvmware/armconnectedvmware README

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client.go
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/file/client.go
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/internal/base/clients.go
sdk/storage/azfile/internal/shared/shared.go
sdk/storage/azfile/service/client.go
sdk/storage/azfile/service/client_test.go
sdk/storage/azfile/share/client.go
sdk/storage/azfile/share/client_test.go

azfile: Add support for AAD audience

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity.go
sdk/azidentity/azidentity_test.go
sdk/azidentity/live_test.go

Some authorities might require certain headers to be passed.
For example, in our dSTS auth flow, the request form contains `client_info`, which needs to be accompanied by `X-Client-SKU=MSAL.Go` header, else the API call produces
```
AADSTS501791: Client_info is only supported for MSAL/ADAL,
please ensure that MSAL/ADAL custom headers are being sent.
```
The `doForClient` function creates new `runtime.Request` from the incoming request, but it fails to propagate the respective headers.
This PR is addressing that. It also adds a short unit test for the `doForClient` method, which was missing.
*I recommend not to squash the commits. Both of them work on their own and have concise message attached.*

fix(azidentity): do not strip away request headers in doForClient

---

sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/internal/base/clients.go
sdk/storage/azfile/service/client_test.go
sdk/storage/azfile/share/client_test.go

azfile: Updating type of audience field

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/README.md
sdk/storage/azblob/appendblob/client.go
sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/assets.json
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/client.go
sdk/storage/azblob/client_test.go
sdk/storage/azblob/container/client.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/internal/base/clients.go
sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/constants.go
sdk/storage/azblob/internal/generated/zz_appendblob_client.go
sdk/storage/azblob/internal/generated/zz_blob_client.go
sdk/storage/azblob/internal/generated/zz_blockblob_client.go
sdk/storage/azblob/internal/generated/zz_container_client.go
sdk/storage/azblob/internal/generated/zz_pageblob_client.go
sdk/storage/azblob/internal/generated/zz_service_client.go
sdk/storage/azblob/internal/shared/challenge_policy.go
sdk/storage/azblob/internal/shared/challenge_policy_test.go
sdk/storage/azblob/pageblob/client.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azblob/service/client.go
sdk/storage/azblob/service/client_test.go

azblob: STG91 upgrade

---

sdk/data/azappconfig/client_test.go
sdk/data/azappconfig/response_types.go
sdk/data/azappconfig/snapshot.go

Update BeginCreateSnapshot to return the complete Snapshot type. Remove unused response types.
Added some missed error checking in a few tests.

More azappconfig cleanup

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/inmemory_checkpoint_store_test.go
sdk/messaging/azeventhubs/internal/eh/stress/scenarios-matrix.yaml
sdk/messaging/azeventhubs/internal/eh/stress/stress-test-resources.json
sdk/messaging/azeventhubs/internal/eh/stress/stress.go
sdk/messaging/azeventhubs/internal/eh/stress/templates/stress-test-job.yaml
sdk/messaging/azeventhubs/internal/eh/stress/tests/balance_tester.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/batch_stress_tester.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/multi_balance_tester.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/processor_stress_tester.go
sdk/messaging/azeventhubs/internal/eh/stress/tests/shared.go
sdk/messaging/azeventhubs/processor_load_balancer.go
sdk/messaging/azeventhubs/processor_load_balancers_test.go
sdk/messaging/azeventhubs/processor_unit_test.go

Fixing an issue where a processor wouldn't grab partitions even when it didn't own any. This became especially bad in conditions where all the partitions were claimed.
- Adding stress test (not enabled, but useful for debugging/manual testing)
- Adding a lot of more unit tests around different ownership splits.
Fixes #22097

[azeventhubs] Fixing an issue where a processor wouldn't grab partitions

---

sdk/data/azappconfig/client.go
sdk/data/azappconfig/options.go

Use azcore.ETag instead of string for public surface area. Add doc comments for non-standard ETag option names.

Clean up ETags in azappconfig

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/receiver.go
sdk/messaging/azservicebus/receiver_test.go
sdk/messaging/azservicebus/receiver_unit_test.go

Updating batching to allow for a configurable wait time. Can lead to fuller batches for people that want to tune it.
Fixes #19172

[azservicebus] Updating batching to allow for a configurable wait time

---

eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go

current version: v3.0.0-beta.1
to release: v2.7.0 (compare v2.6.0, not BreakingChange)
The above does not replace the import module in fake and live_test.
ref: https://github.com/Azure/azure-sdk-for-go/pull/22184/commits/b8368c704ce55b61adfc37894e6786d47b5aedac#diff-878839ecfc6b682d3adbdd34fdeff0178e7018301d85ea4dca7453563d9ca93c

fix generator tool

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/go.mod
sdk/storage/azdatalake/go.sum
sdk/storage/azdatalake/internal/exported/version.go

[azdatalake] Preview STG 82

---

eng/scripts/modtidy.ps1

Currently the script will not fail (due to exits being ignored in the parallel run context) which could present problems in the future if it is called in pipelines.

Handle errors in mod tidy script

---

eng/pipelines/templates/jobs/archetype-go-release.yml

Depends on https://github.com/Azure/azure-sdk-tools/pull/7445
Fixes https://github.com/Azure/azure-sdk-for-go/issues/21737

Use package filter to prevent recursive package publish

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/variables/globals.yml

Selectively turning on component governance checks for scheduled CI. Turning CG off explicitly for PR builds to hopefully reduce scanning cost on the CG team side of things.

Add selective component governance step

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/go.mod
sdk/messaging/azservicebus/go.sum
sdk/messaging/azservicebus/receiver_test.go

go-amqp got a fix recently that replaces its internal tracking map with a counter, which eliminates a rare memory leak we'd see if you were settling a message on a separate receiver _while_ the other receiver was still alive.
In recovery scenarios, we discard the old Receiver instance, making this a non-issue for our typical use case.
Fixes #22157

[azservicebus] Fixing memory leak with go-amqp update.

---

sdk/azidentity/azidentity_test.go
sdk/azidentity/interactive_browser_credential.go

Looks like I broke this in #21333 and since v1.4.0 it hasn't been possible to specify additional tenants for `InteractiveBrowserCredential` 😞 
There was a test gap here because at the time the feature could only be tested manually with live resources. The addition of `DisableAutomaticAuthentication` has since made an offline unit test possible because tenant resolution happens before authentication.

Fix allowed tenants for InteractiveBrowserCredential

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_client_test.go

Broaden special case for 403 responses from IMDS

---

sdk/storage/azblob/appendblob/client.go
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/container/client.go
sdk/storage/azblob/internal/exported/version.go
sdk/storage/azblob/internal/shared/shared.go
sdk/storage/azblob/pageblob/client.go
sdk/storage/azblob/service/client.go
sdk/storage/azblob/service/client_test.go
sdk/storage/azdatalake/directory/client.go
sdk/storage/azdatalake/file/client.go
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/filesystem/client.go
sdk/storage/azdatalake/internal/exported/version.go
sdk/storage/azdatalake/internal/shared/shared.go
sdk/storage/azdatalake/service/client.go
sdk/storage/azdatalake/service/client_test.go
sdk/storage/azfile/directory/client.go
sdk/storage/azfile/file/client.go
sdk/storage/azfile/internal/exported/version.go
sdk/storage/azfile/internal/shared/shared.go
sdk/storage/azfile/service/client.go
sdk/storage/azfile/service/client_test.go
sdk/storage/azfile/share/client.go

- [] Updates to module CHANGELOG.md are included.

Storage/fix Module Name in azfile, azdatalake, azblob

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azure_cli_credential.go
sdk/azidentity/azure_cli_credential_test.go

When `az` specifies `expires_on`, we prefer that because it's a POSIX timestamp i.e. straightforward to parse. Otherwise, we fall back to parsing `expiresOn`, a local timestamp, as we do today. Closes #21886

AzureCLICredential prefers expires_on value

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/exported/request.go
sdk/azcore/internal/exported/request_test.go
sdk/azcore/runtime/request.go

The codegen for TypeSpec can explicitly set the Content-Type header. We must prefer this value when set.

JSON marshaling helpers will preserve Content-Type

---

eng/pipelines/templates/jobs/archetype-go-release.yml
eng/pipelines/templates/steps/analyze.yml

The purpose is to gate on the REST API specifications used to release SDK are from the main branch of Azure/azure-rest-api-specs repository.
The common script and pipeline are merged by another PR.
https://github.com/Azure/azure-sdk-tools/pull/7451
FYI - The same change has been added to the other four tier 1 language release pipelines.
https://github.com/Azure/azure-sdk-for-net/pull/40783
Because Go SDK doesn't have package generated, it needs to add a step to publish the `PackageInfo` as artifact. `PackageInfo` will be used in downstream step to get the sdk directory and the version info.
This PR should hold on the merge until below PR is merged.
https://github.com/Azure/azure-sdk-tools/pull/7585
[aztemplate test pipeline run](https://dev.azure.com/azure-sdk/internal/_build/results?build …

Added spec location verification to the release pipeline

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/assets.json
sdk/storage/azdatalake/filesystem/client_test.go
sdk/storage/azdatalake/internal/testcommon/clients_auth.go
sdk/storage/azdatalake/service/client_test.go

[azdatalake] HNS encryption scope

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blob/client.go

In Download File API, method aquireBuffer() in https://github.com/Azure/azure-sdk-for-go/commit/1dc804a987bde7cc943c339b0b374f98c99d30e1 is not thread safe. 
If 2 threads acquire the buffer and both try to increment the _count_ of buffers allocated at the same time, this leads to a Data Race.  

Fix azblob/download data race

---

sdk/messaging/azservicebus/amqp_message.go
sdk/messaging/azservicebus/client_test.go
sdk/messaging/azservicebus/internal/mgmt.go
sdk/messaging/azservicebus/internal/mock/emulation/events.go
sdk/messaging/azservicebus/internal/stress/Chart.lock
sdk/messaging/azservicebus/internal/stress/Dockerfile
sdk/messaging/azservicebus/internal/stress/scenarios-matrix.yaml
sdk/messaging/azservicebus/internal/stress/shared/streaming_batch.go
sdk/messaging/azservicebus/internal/stress/shared/utils.go
sdk/messaging/azservicebus/internal/stress/templates/stress-test-job.yaml
sdk/messaging/azservicebus/internal/stress/tests/benchmarks/backup_settlement_leak_test.go
sdk/messaging/azservicebus/internal/stress/tests/benchmarks/main_test.go
sdk/messaging/azservicebus/internal/stress/tests/benchmarks/readme.md
sdk/messaging/azservicebus/message.go
sdk/messaging/azservicebus/messageSettler.go
sdk/messaging/azservicebus/messageSettler_test.go
sdk/messaging/azservicebus/message_test.go
sdk/messaging/azservicebus/receiver.go
sdk/messaging/azservicebus/receiver_simulated_test.go
sdk/messaging/azservicebus/receiver_test.go
sdk/messaging/azservicebus/sender_test.go

go-amqp holds onto some tracking data that won't get cleared if we don't try to settle through the original Receiver. Our fix in here, combined with go-amqp's changes to route to the original receiver, should seal that up.
Benchmark added that also doubles as a stress test.
Fixes #22318

[azservicebus] Fixing a memory leak when doing cross receiver settlement.

---

eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml
eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-eng-client.yml
eng/pipelines/templates/stages/platform-matrix.json
eng/pipelines/templates/steps/build-test.yml
sdk/internal/telemetry/telemetry_test.go

Go 1.22 changed some code coverage internals which is causing some cases to under-report coverage. Disabling for now until this is resolved.
See https://github.com/golang/go/issues/65570

Disable code coverage redesign in CI

---

sdk/azcore/CHANGELOG.md
sdk/azcore/core.go

Note that since IsNullValue is on a hot path, it must never block in the common case.

Fix potential race between NullValue and IsNullValue

---

sdk/internal/CHANGELOG.md
sdk/internal/recording/matchers.go
sdk/internal/recording/matchers_test.go
sdk/internal/version.go

#21168 changed the default port for `Set*Matcher()` to a non-deterministic value. That prevents configuring matchers on a test proxy not started by `recording.StartTestProxy` because the default port can't be known before `go test` starts. This PR adds proxy configuration options to these functions, which enables overriding the default port and aligns these functions with the rest of the API e.g. `Add*Sanitizer()`.

SetBodilessMatcher & SetDefaultMatcher take RecordingOptions

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/assets.json
sdk/storage/azblob/internal/exported/shared_key_credential.go
sdk/storage/azblob/service/client_test.go
sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/assets.json
sdk/storage/azdatalake/internal/exported/shared_key_credential.go
sdk/storage/azdatalake/service/client_test.go
sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/internal/exported/shared_key_credential.go
sdk/storage/azfile/service/client_test.go

Revert the change made in #22183 and #21841.
Discussion with PM and some concerns raised on github for this reveals that Azure Stack and Azurite users either prefer or in some cases forced to use HTTP. Not allowing HTTP from SDK side block their setup. Similar issues were faced by AzCopy and Blobfuse in their pipelines to test against Azurite. Hence reverting back the changes and allowing HTTP with key credentials.

Storage: Re-enable HTTP endpoints for shared key credential

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/exported/response_error.go
sdk/azcore/internal/exported/response_error_test.go
sdk/azcore/internal/log/log.go
sdk/azcore/internal/shared/constants.go
sdk/azcore/log/log.go
sdk/azcore/runtime/errors.go
sdk/azcore/runtime/errors_test.go

This event is logged whenever an azcore.ResponseError is created. The contents are from ResponseError.Error().
Add NewResponseErrorWithErrorCode to support creating ResponseErrors when the error code is in a non-standard location.

Add logging event EventResponseError

---

sdk/data/aztables/client.go
sdk/data/aztables/models.go
sdk/data/aztables/options.go
sdk/data/aztables/responses.go
sdk/data/aztables/service_client.go
sdk/data/aztables/transactional_batch.go

Moved options and response types to their respective files. Helper funcs that were used in one place have been removed, their contents made inline.
Replaced appending to slices with making the correct size and populating them in place.

Some cleanup in aztables

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/directory/client_test.go
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/internal/path/responses.go

Exposing x-ms-resource-type response header in GetProperties API for file and directory

Exposing x-ms-resource-type response header 

---

sdk/data/aztables/constants.go
sdk/data/aztables/models.go
sdk/data/aztables/sas_query_params.go
sdk/data/aztables/service_client.go
sdk/data/aztables/transactional_batch.go

Moved constant definitions to constants.go.
Moved struct definitions to models.go.
Moved internal helper funcs next to their types.

More cleanup in aztables

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/request.go
sdk/azcore/runtime/request_test.go

For compat reasons, url.ParseQuery will reject semicolons within query params. So, we must escape them first.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/22408

Escape semicolons in query params before parsing

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blob/client.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blockblob/client.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/client_test.go
sdk/storage/azblob/internal/shared/batch_transfer.go

Fixes #22426 
Evaluated perf of random vs sequential write when DownloadFile method is used to download 10GB blob. Saw similar perf numbers in both cases for premium SSD as well as standard HDD. Current sequential write logic also has some sync issues. So, reverting the code back to use random write logic.
Time taken to download 10GB blob in premium SSD.
```
Concurrency  |  Sequential  |  Random
5      |      42.42s  |    42.02s
8      |      42.16s  |    42.09s
16     |     42.02s   |    42.66s
```
Time taken to download 10GB blob in standard HDD.
```
Concurrency  |  Sequential  |  Random
5      |      1m26s   |   1m29s
8      |      1m29s   |    1m30s
16 …
```

azblob: Random write in DownloadFile

---

sdk/data/aztables/proxy_test.go
sdk/data/aztables/recording_helpers_test.go
sdk/data/aztables/transactional_batch.go

Clean up lint in aztables

---

sdk/data/aztables/CHANGELOG.md
sdk/data/aztables/client.go
sdk/data/aztables/service_client.go

Per the docs, if there are no continuation header values, there are no more entities to return.
Removed some superfluous if checks.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/22456

NewListEntitiesPager fix

---

sdk/azcore/CHANGELOG.md
sdk/azcore/etag.go

Add MatchConditions to azcore

---

sdk/data/aztables/CHANGELOG.md
sdk/data/aztables/assets.json
sdk/data/aztables/client.go
sdk/data/aztables/client_test.go
sdk/data/aztables/constants.go
sdk/data/aztables/internal/version.go
sdk/data/aztables/models.go
sdk/data/aztables/options.go
sdk/data/aztables/responses.go
sdk/data/aztables/service_client.go
sdk/data/aztables/service_client_test.go

Include returned metadata in more APIs.
Make the amount of returned metadata configurable.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/22438

Updates for aztables metadata

---

sdk/azcore/CHANGELOG.md
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/runtime/request.go
sdk/azcore/testdata/perf/go.mod
sdk/azcore/testdata/perf/go.sum

Prep azcore for release

---

sdk/data/aztables/CHANGELOG.md
sdk/data/aztables/autorest.md
sdk/data/aztables/internal/zz_time_rfc1123.go
sdk/data/aztables/internal/zz_time_rfc3339.go

Exit early if the value is empty.
This was observed in a test run. https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/3530520/logs/449
Per the [docs](https://learn.microsoft.com/en-us/rest/api/storageservices/get-table-service-stats#response-body), `LastSyncTime` might be empty in some cases.
This will need to be fixed in codegen, but fixing it here for now.

Don't error on empty time value

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/go.mod
sdk/messaging/azeventhubs/go.sum
sdk/messaging/azeventhubs/internal/eh/stress/Chart.lock
sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/go.mod
sdk/messaging/azservicebus/go.sum
sdk/messaging/azservicebus/internal/stress/scenarios-matrix.yaml
sdk/messaging/azservicebus/internal/stress/shared/stress_context.go
sdk/messaging/azservicebus/internal/stress/templates/stress-test-job.yaml
sdk/messaging/azservicebus/internal/stress/tests/open_close_measurements.go
sdk/messaging/azservicebus/internal/stress/tests/tests.go

Pulling in a new AMQP version with my fix for the "body size < frame size" that would cause to hang for 26 seconds while closing a session on a link that was idle.
Fixes #21684

[azservicebus, azeventhubs] Updating to take in the new AMQP version.

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/internal/test/test_helpers.go
sdk/messaging/azeventhubs/processor.go
sdk/messaging/azeventhubs/processor_unit_test.go

Fixed a race condition between Processor.Run() and Processor.NextPartitionClient() where cancelling Run() quickly could lead to NextPartitionClient hanging indefinitely, waiting for a channel that would never be closed.
Fixes #22539

[azeventhubs] Fix race condition between Processor.Run being cancelled and NextPartitionClient

---

eng/.golangci.yml
eng/pipelines/templates/steps/analyze.yml

Fails the build if go.mod or go.sum isn't current.

Ensure modules are current and tidy in CI

---

sdk/data/azcosmos/cosmos_query_response.go
sdk/data/azcosmos/cosmos_query_response_test.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/22523

[Cosmos] Use []json.RawMessage for cosmos list unmarshal to avoid MaxInt64 mishandling

---

sdk/monitor/azingest/CHANGELOG.md
sdk/monitor/azingest/README.md
sdk/monitor/azingest/go.mod

The `azingest` module is being deprecated. Monitor Ingestion can now be found at `sdk/monitor/ingestion/azlogs`.
Part of https://github.com/Azure/azure-sdk-for-go/issues/22377

[monitor ingestion] deprecate azingest

---

sdk/data/azcosmos/cosmos_global_endpoint_manager.go

While working with the sdk, I ran into this data race issue
```
WARNING: DATA RACE01:26
Read at 0x00c000362058 by goroutine 39:01:26
github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos.(*globalEndpointManager).ShouldRefresh()01:26
/home/semaphore/git/go/1.21.7/pkg/mod/github.com/confluentinc/azure-sdk-for-go/sdk/data/azcosmos@v0.0.0-20240306185250-2945d4e6c7bc/cosmos_global_endpoint_manager.go:84 +0x5a01:26
github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos.(*globalEndpointManagerPolicy).Do()01:26
/home/semaphore/git/go/1.21.7/pkg/mod/github.com/confluentinc/azure-sdk-for-go/sdk/data/azcosmos@v0.0.0-20240306185250-2945d4e6c7bc/cosmos_global_endpoint_manager_policy.go:18 +0x2601:26
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next()01:26 …
```

[Cosmos] Fix data race issue with cosmos_global_endpoint_manager

---

sdk/messaging/eventgrid/aznamespaces/CHANGELOG.md
sdk/messaging/eventgrid/aznamespaces/assets.json
sdk/messaging/eventgrid/aznamespaces/autorest.md
sdk/messaging/eventgrid/aznamespaces/client.go
sdk/messaging/eventgrid/aznamespaces/client_custom.go
sdk/messaging/eventgrid/aznamespaces/client_test.go
sdk/messaging/eventgrid/aznamespaces/client_unit_test.go
sdk/messaging/eventgrid/aznamespaces/example_test.go
sdk/messaging/eventgrid/aznamespaces/internal/version.go
sdk/messaging/eventgrid/aznamespaces/main_test.go
sdk/messaging/eventgrid/aznamespaces/options.go
sdk/messaging/eventgrid/aznamespaces/shared_test.go

This is a more efficient way of sending CloudEvents as it avoids JSON serialization for the body. It has some restrictions/caveats, which are documented.
Fixes #22304

[aznamespaces] Adding in the ability to send events using BinaryMode.

---

eng/tools/generator/template/rpName/packageName/ci.yml.tpl
sdk/azidentity/cache/ci.azidentity.yml
sdk/cognitiveservices/azopenai/ci.cognitiveservices.yml
sdk/messaging/eventgrid/azeventgrid/ci.basic.yml
sdk/monitor/ingestion/azlogs/ci.ingestion.yml
sdk/resourcemanager/internal/ci.resourcemanager.yml
sdk/resourcemanager/resources/armmanagedapplications/ci.resources.yml
sdk/resourcemanager/solutions/armmanagedapplications/ci.solutions.yml
sdk/security/keyvault/internal/ci.keyvault.yml

Swapping a few more `ci.yml` files to `extends` vs `stages` at their root.
Follow-up from #22590 and [the follow-up commit](https://github.com/Azure/azure-sdk-for-go/commit/88d8a7ebb55562f8b5fdc48644d31cc13d383c7d)
Not certain how it escaped the first ctrl-shift-f, but they did!

A few more yml updates

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/policy/policy.go
sdk/azcore/arm/runtime/policy_bearer_token_test.go
sdk/azcore/arm/runtime/policy_register_rp.go
sdk/azcore/arm/runtime/policy_register_rp_test.go
sdk/azcore/internal/shared/constants.go

This lets customers work around services with non-conformant behavior. Replaced custom resource type parsing with in-box version.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/22563
I chose not to expose `StatusCodes` in `arm/policy.ClientOptions` as it should be very rare (not to mention temporal as the RP should fix their code). This does require one to disable the in-box registration policy and create their own version.
```go
regPol, err := armruntime.NewRPRegistrationPolicy(cred, &armpolicy.RegistrationOptions{
StatusCodes: []int{http.StatusConflict, http.StatusNotFound},
})
if err != nil {
// TODO: handle error
}
client, err := armmonitor.NewActivityLogsClient("subscription-id", cred, &arm.ClientOptions{
ClientOptions: azcore.ClientOptions{
PerCallPolicies: …
```

Add StatusCodes option to ARM RP registration policy

---

sdk/azidentity/ci.yml
sdk/azidentity/managed-identity-matrix.json

The matrix generation, due to 1es pt limitations, was changed to filter against OS variables and run one generation pass for each OS type. This had a mismatch with the identity matrix, so this PR updates the config to work with the generation jobs filters.

Fix go identity matrix/pool selection

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/policy/policy.go
sdk/azcore/arm/policy/policy_test.go
sdk/azcore/arm/runtime/pipeline.go
sdk/azcore/arm/runtime/policy_bearer_token.go
sdk/azcore/arm/runtime/policy_bearer_token_test.go
sdk/azcore/policy/policy.go
sdk/azcore/runtime/policy_bearer_token.go
sdk/azcore/runtime/policy_bearer_token_test.go
sdk/azcore/runtime/policy_key_credential.go
sdk/azcore/runtime/policy_key_credential_test.go
sdk/azcore/runtime/policy_sas_credential.go
sdk/azcore/runtime/policy_sas_credential_test.go

When true, allows authenticated requests over HTTP.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/22482

Add AllowInsecureAuth to ClientOptions

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/assets.json
sdk/storage/azdatalake/file/client.go
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/file/models.go
sdk/storage/azdatalake/file/responses.go
sdk/storage/azdatalake/filesystem/client_test.go
sdk/storage/azdatalake/internal/path/responses.go
sdk/storage/azdatalake/internal/testcommon/clients_auth.go

This PR contains the following features -
STG87 : Data Lake Encryption Context
STG88 : Add Encryption Context to File Upload Options

HNS Encryption Context support

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/request.go
sdk/azcore/runtime/request_test.go
sdk/azcore/streaming/progress.go
sdk/azcore/streaming/progress_test.go

Added type MultipartContent to allow specifying Content-Type and file name for a payload.
Fixed an issue in SetMultipartFormData that would incorrectly quote raw JSON data.

Improved support for multipart/form payloads

---

sdk/azidentity/assets.json
sdk/azidentity/client_certificate_credential_test.go
sdk/azidentity/live_test.go
sdk/azidentity/test-resources-pre.ps1

The cert we used to test SNI auth has expired and we can't get another because requirements for issuing them have tightened (this is a 1P prod feature). Fortunately we don't need the live tests because this feature is straightforward to test with fakes and recordings, and we already do that. Closes #21988

Remove live SNI auth tests

---

sdk/messaging/azeventgrid/CHANGELOG.md
sdk/messaging/azeventgrid/README.md
sdk/messaging/azeventgrid/go.mod
sdk/messaging/azeventgrid/internal/version.go
sdk/messaging/azeventgrid/publisher/README.md

Both packages that were hosted in this module have moved and been published in their new places:
* Event Grid Basic client has moved to github.com/Azure/azure-sdk-for-go/sdk/messaging/eventgrid/azeventgrid
* Event Grid Namespaces client has moved to github.com/Azure/azure-sdk-for-go/sdk/messaging/eventgrid/aznamespaces
We can deprecate this, publish it one more time and then scrub it from the repo.
Fixes #22554

[azeventgrid(old)] Officially deprecating this module

---

sdk/messaging/azeventgrid/client_test.go

I needed to port this text fix over so the tests will pass so I can release the library once again to deprecate it.

[azeventgrid(old)] Fixing a test error so we can deprecate this library

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/assets.json
sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_credential_test.go
sdk/azidentity/test-resources-post.ps1

IMDS observes both `msi_res_id` and `mi_res_id` as the query parameter specifying an identity by its resource ID. We should prefer `msi_res_id` because it's the [documented parameter](https://github.com/Azure/azure-rest-api-specs/blob/dba6ed1f03bda88ac6884c0a883246446cc72495/specification/imds/data-plane/Microsoft.InstanceMetadataService/stable/2018-10-01/imds.json#L233-L239) and because Azure Container Instances, which has a different implementation based on the IMDS API, observes only `msi_res_id`.

Correct IMDS resource ID query parameter

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/pollers/loc/loc.go
sdk/azcore/internal/pollers/loc/loc_test.go

If the polling request is being throttled, preserve the current state and return the *http.Response.

Don't consider 429 as terminal failure for Location poller

---

sdk/azidentity/managed_identity_credential_test.go
sdk/azidentity/test-resources-post.ps1
sdk/azidentity/test-resources.bicep
sdk/azidentity/workload_identity_test.go

Live Azure Container Instances managed identity test

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/internal/constants.go
sdk/messaging/azeventhubs/internal/exported/connection_string_properties.go
sdk/messaging/azeventhubs/internal/exported/connection_string_properties_test.go
sdk/messaging/azeventhubs/internal/namespace.go
sdk/messaging/azeventhubs/internal/namespace_test.go
sdk/messaging/azeventhubs/internal/sbauth/token_provider.go
sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/admin/admin_client_test.go
sdk/messaging/azservicebus/admin_client_test.go
sdk/messaging/azservicebus/internal/atom/entity_manager.go
sdk/messaging/azservicebus/internal/conn/conn.go
sdk/messaging/azservicebus/internal/conn/conn_test.go
sdk/messaging/azservicebus/internal/constants.go
sdk/messaging/azservicebus/internal/namespace.go
sdk/messaging/azservicebus/internal/namespace_test.go
sdk/messaging/azservicebus/internal/sas/sas.go
sdk/messaging/azservicebus/internal/sbauth/token_provider.go

Emulators are coming and the SDKs needed to allow non-TLS connections but it's restricted to localhost, and emulators _only_, which you signal with the new 'UseDevelopmentEmulator=true' property in your connection string.
Fixes #22370
Fixes #22371

[azservicebus,azeventhubs] Adding in support for connecting to an emulator

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/pollers/loc/loc.go
sdk/azcore/internal/pollers/loc/loc_test.go

Treat 408 the same as 429, preserving state and returning the response.

Don't consider 408 as terminal failure for Location poller

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/pollers/loc/loc.go
sdk/azcore/internal/pollers/util.go
sdk/azcore/internal/pollers/util_test.go
sdk/azcore/runtime/poller.go
sdk/azcore/runtime/poller_test.go

If the underlying error when retrieving the final result is non terminal, don't mark the poller as done so callers can retry.

runtime.Poller.Result won't be done on non-terminal error

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/assets.json
sdk/azidentity/default_azure_credential.go
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_credential.go

Because requests sent to IMDS can take a very long time to time out when IMDS isn't available, DefaultAzureCredential imposes a 1 second timeout on managed identity token requests until one receives a response. This approach creates a (very small) chance of canceling a token request that would have succeeded given more time. This PR lowers that probability by adding a probing step in which the credential sends a malformed request to IMDS with the same 1 second timeout. Request validation is faster than acquiring an access token, so we assume IMDS will respond faster to this probe than to a token request. If the credential receives any response to a probe, it takes that to mean IMDS is available and thereafter sends normal token requests with no special timeout. This affects only …

DefaultAzureCredential probes IMDS before sending it a token request

---

sdk/ai/azopenai/CHANGELOG.md
sdk/ai/azopenai/event_reader.go
sdk/ai/azopenai/event_reader_test.go

SSE, from what I can tell, does not have a restriction on the size of chunks that are allowed when streaming. This makes bufio.Scanner a bad fit, since it has a (large) but hard limit on the amount of text it can read.
This change swaps us over to use bufio.Reader, which doesn't have that restriction and is high level enough for us to use for our use case.
Credit to [ChrisTrenkamp](https://github.com/ChrisTrenkamp) for finding the issue and suggesting a fix.

[azopenai] bufio.Scanner has an implicit max size for it's internal buffer which can limit reading larger chunks in SSE

---

sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/managed_identity_client.go

Whoops, I overlooked this in #22676

Disable retries for DefaultAzureCredential's IMDS probe

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_client.go
sdk/data/azcosmos/cosmos_client_test.go
sdk/data/azcosmos/cosmos_container_request_options.go
sdk/data/azcosmos/cosmos_container_request_options_test.go
sdk/data/azcosmos/cosmos_database.go
sdk/data/azcosmos/cosmos_database_request_options.go
sdk/data/azcosmos/cosmos_database_request_options_test.go
sdk/data/azcosmos/cosmos_database_test.go
sdk/data/azcosmos/cosmos_query_response.go

During https://github.com/Azure/azure-sdk-for-go/pull/22623 we fixed `ContinuationToken` to be `*string` but we missed some other places.
* QueryContainersOptions
* QueryDatabasesOptions
* QueryContainersResponse
* QueryDatabasesResponse

azcosmos - Fix continuations types

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/assets.json
sdk/storage/azdatalake/directory/client.go
sdk/storage/azdatalake/directory/client_test.go
sdk/storage/azdatalake/file/client.go
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/filesystem/client.go
sdk/storage/azdatalake/filesystem/client_test.go
sdk/storage/azdatalake/go.mod
sdk/storage/azdatalake/go.sum
sdk/storage/azdatalake/internal/base/clients.go
sdk/storage/azdatalake/internal/shared/challenge_policy.go
sdk/storage/azdatalake/internal/shared/challenge_policy_test.go
sdk/storage/azdatalake/service/client.go
sdk/storage/azdatalake/service/client_test.go

[azdatalake] Support for AAD Audience and  Integrate InsecureAllowCredentialWithHTTP with Client Options

---

sdk/monitor/query/azlogs/CHANGELOG.md
sdk/monitor/query/azlogs/README.md
sdk/monitor/query/azlogs/autorest.md
sdk/monitor/query/azlogs/build.go
sdk/monitor/query/azlogs/client_test.go
sdk/monitor/query/azlogs/cloud_config.go
sdk/monitor/query/azlogs/constants.go
sdk/monitor/query/azlogs/custom_client.go
sdk/monitor/query/azlogs/examples_test.go
sdk/monitor/query/azlogs/models.go
sdk/monitor/query/azlogs/options.go
sdk/monitor/query/azlogs/utils_test.go

Final cleanup of the API before GA. Removing stuttering by removing "logs" from type names.

[azlogs] remove logs prefix

---

sdk/monitor/query/azmetrics/CHANGELOG.md
sdk/monitor/query/azmetrics/autorest.md
sdk/monitor/query/azmetrics/models.go
sdk/monitor/query/azmetrics/models_serde.go

Cleaning up names. Changing `MetricsValues` to `MetricData` to avoid confusion with the existing `MetricValue` struct.

[azmetrics] rename MetricValues to MetricData

---

eng/pipelines/templates/steps/build-test.yml
sdk/internal/CHANGELOG.md
sdk/internal/recording/default_sanitizers.go
sdk/internal/recording/default_sanitizers_test.go
sdk/internal/recording/recording.go
sdk/internal/recording/sanitizer.go
sdk/internal/recording/server.go

These will apply to all future recordings made through the proxy but don't affect existing recordings. Some of the new target values may not be secret, however we're scrubbing them all anyway to prevent false positives. We can revisit them later if sanitizing them causes any problems.
I marked `NewRecording` deprecated because it doesn't use the test proxy and isn't called anywhere in the repo. We should delete it and the rest of the vestigial `go-vcr` based code because we only support recording via the proxy (#22744).
Also, I reverted #21142 because it pinned our CI pipelines to an old version of the proxy that doesn't support adding sanitizers in bulk, apparently to work around an azdatalake issue. The azdatalake pipelines pass with this change so I guess the underlying problem has …

Default test recording sanitizers

---

sdk/storage/azblob/README.md
sdk/storage/azblob/go.mod
sdk/storage/azblob/go.sum
sdk/storage/azdatalake/README.md
sdk/storage/azfile/README.md

This PR adds latest build statuses and code coverage percentages from public pipelines of each component - azfile, azblob and azdatalake.
The output will be similar to the following - 

Add build status and coverage percentage in README.md

---

sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/constants.go
sdk/storage/azdatalake/internal/generated/autorest.md
sdk/storage/azfile/internal/generated/autorest.md
sdk/storage/azfile/internal/generated/constants.go

Azdatalake serviceVersion is already updated to 2024-05-04, updating only azblob and azfile in this PR

Service version upgrade for stg 93 storage

---

sdk/internal/CHANGELOG.md
sdk/internal/recording/sanitizer.go

This constant isn't referenced on main. I anticipate using it to fix tests broken by the new test proxy's default sanitizers, which replace values with "**S**anitized".

recording.SanitizedValue matches test proxy

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/example_receiver_test.go
sdk/messaging/azservicebus/go.mod
sdk/messaging/azservicebus/go.sum
sdk/messaging/azservicebus/internal/amqpLinks_test.go
sdk/messaging/azservicebus/internal/amqpwrap/rpc.go
sdk/messaging/azservicebus/internal/constants.go
sdk/messaging/azservicebus/internal/errors_test.go
sdk/messaging/azservicebus/internal/mgmt.go
sdk/messaging/azservicebus/internal/utils/types.go
sdk/messaging/azservicebus/internal/utils/types_test.go
sdk/messaging/azservicebus/liveTestHelpers_test.go
sdk/messaging/azservicebus/message.go
sdk/messaging/azservicebus/messageSettler_test.go
sdk/messaging/azservicebus/receiver.go
sdk/messaging/azservicebus/receiver_test.go
sdk/messaging/azservicebus/sender_test.go
sdk/messaging/azservicebus/session_receiver.go
sdk/messaging/azservicebus/session_receiver_test.go

[azservicebus] Adding in the DeleteMessages feature. This is a new feature in preview.

---

eng/config.json
sdk/azidentity/cache/CHANGELOG.md
sdk/azidentity/cache/internal/jwe/jwe_test.go
sdk/azidentity/cache/linux.go
sdk/azidentity/cache/linux_test.go

This prevents the errors that made testing the Linux keyring storage implementation impossible in CI. These errors were caused by the `go test` process having permission to add keys to the user keyring but not to read those keys or find them in a search. This weird situation arose because the process was accessing the user keyring as its owner, not as a possessor, and the owner has lesser privilege. (Ownership doesn't imply possession in the keyring permissions model, I guess to enable processes running as the same UID to protect secrets from each other.) The fix is to link the session keyring possessed by the process to the user keyring, transitively granting the process possession of keys linked to the user keyring. Most systems do this automatically on login but apparently our CI …

Fix persistent cache errors caused by Linux keyring permissions

---

sdk/internal/CHANGELOG.md

And add release date to enable releasing a new version of this package.

Update the `internal` changelog to reflect new proxy version override feature

---

sdk/messaging/eventgrid/aznamespaces/go.mod
sdk/messaging/eventgrid/aznamespaces/go.sum
sdk/resourcemanager/resources/armdeploymentscripts/go.mod
sdk/resourcemanager/resources/armdeploymentscripts/go.sum

This reverts the upgrade from an unstable to stable dependency version that broke these modules in #22835. The affected modules will build and their tests will pass, but their pipelines will still fail because of the upgrade check in the analyze job.

Revert breaking dependency upgrades

---

eng/scripts/Create-ApiReview.ps1

I do not think there are any pipelines where we need/want to be recursing on packages, as we keep to a one pipeline per package convention in go data plane. Currently nested packages, i.e. azidentity/cache are blocking parent packages from releasing if they don't have an api review approval.

Do not create or block on api review for nested packages

---

sdk/azidentity/cache/CHANGELOG.md
sdk/azidentity/cache/version.go

v0.2.1 already published because of a bug in release scripts, and this bug also skipped its post-release automation.

Update azidentity/cache changelog and version

---

sdk/security/keyvault/azkeys/ci.yml

Part of [21934](https://github.com/Azure/azure-sdk-for-go/issues/21934)
Fix the ci.yml file to allow the tests to run live on managed HSM's weekly.

[azkeys] enable managed HSM's on weekly pipelines

---

sdk/internal/CHANGELOG.md
sdk/internal/version.go

This will stop requiring API approval for every release because changing the value of `Version` counts as a public API change. No module on main uses these constants and none has any reason to. Even `internal` itself doesn't use them, because it doesn't create a pipeline. I removed `Module` but kept `version` because our post-release automation updates that value.

Unexport unused sdk/internal constants

---

sdk/monitor/query/azmetrics/CHANGELOG.md
sdk/monitor/query/azmetrics/README.md
sdk/monitor/query/azmetrics/ci.yml
sdk/monitor/query/azmetrics/cloud_config.go
sdk/monitor/query/azmetrics/custom_client.go
sdk/monitor/query/azmetrics/utils_test.go

Closes https://github.com/Azure/azure-sdk-for-go/issues/22547
* Adding sovereign cloud support to `azmetrics`
* Adding weekly live testing for the US Gov and China clouds

[azmetrics] add sovereign cloud support

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/internal/exported/connection_string_properties.go
sdk/messaging/azeventhubs/internal/exported/connection_string_properties_test.go
sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/internal/conn/conn.go
sdk/messaging/azservicebus/internal/conn/conn_test.go

Removing the restriction that emulator behavior is only available on localhost. 
This supports scenarios where you're using Docker's private networking, where each container has an individual hostname that is _NOT_ localhost.

[azservicebus, azeventhubs] emulators should allow for non-localhost as well

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/example_test.go
sdk/azidentity/on_behalf_of_credential.go
sdk/azidentity/on_behalf_of_credential_test.go

Closes #22825 by adding an `OnBehalfOfCredential` constructor that takes a callback providing client assertions.

Support federated credentials in on-behalf-of flow

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/pager.go
sdk/azcore/runtime/pager_test.go

Add option to specify additional HTTP status codes indicating success in pager helper.

Support additional success codes when fetching pages

---

eng/config.json
sdk/ai/azopenaiassistants/README.md

Links were stale and pointed to azopenai, not azopenaiassistants.

[azopenaiassistants] Fixing readme to point to azopenaiassistants

---

sdk/containers/azcontainerregistry/assets.json
sdk/containers/azcontainerregistry/client_test.go
sdk/containers/azcontainerregistry/utils_test.go

Pipeline runs are failing due to rate limiting while importing images. I guess this is because I parallelized that step in #22920, so this PR reverts that change. Edit: that may have been part of the problem but it wasn't sufficient, so I also reduced the amount of imported data.

Avoid throttling in azcontainerregistry live tests

---

eng/scripts/Language-Settings.ps1

I am not seeing any uses of the recurse function here actually needing to go down a directory level(s), but to be safe I want to run this for a week and do a search across our pipeline log db.

Add debug logging for recursive go.mod searches

---

sdk/containers/azcontainerregistry/assets.json
sdk/containers/azcontainerregistry/client_test.go
sdk/containers/azcontainerregistry/utils_test.go

Tests are still occasionally getting throttled while uploading images. This should help because eclipse-mosquitto is about 63MB smaller than nginx so, less I/O required. If this doesn't solve the problem, next step is to upgrade the ACR SKU from Basic to Premium, which has higher limits.

Use smaller image in ACR test

---

eng/pipelines/templates/jobs/archetype-go-release.yml
eng/scripts/Create-ApiReview.ps1
eng/scripts/Language-Settings.ps1

Fixes #22881 
This PR fixes the issue we had with finding nested go modules when not intended, by making `Get-AllPackageInfoFromRepo` search recursively ONLY when service directory is not specified, otherwise we search with `-Depth 1`.
With #22950 I was able to trace instances where we picked up multiple modules via the scripts. There were three categories, two of which are updated here to no longer search recursively.
1. Dependency Check step in the analyze job. This seems to be intended and calls `Get-AllPackageInfoFromRepo` without passing in a service directory argument.
2. CI for core, security, data and template SDKs. All matches here were just picking up the nested `testdata/perf/go.mod` file which I think is not intended since we test perf specifically later in the pipeline.
3. …

Do not recursively search for go modules when service directory is known

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/request.go
sdk/azcore/runtime/request_test.go

For use by generated code to produce UUIDs.
Part of https://github.com/Azure/autorest.go/issues/770

Add NewUUID to runtime package

---

sdk/messaging/azeventhubs/internal/eh/stress/Chart.lock
sdk/messaging/azeventhubs/internal/eh/stress/stress-test-resources.json
sdk/messaging/azservicebus/internal/stress/Chart.lock
sdk/messaging/azservicebus/internal/stress/shared/stress_context.go
sdk/messaging/azservicebus/internal/stress/stress-test-resources.bicep

- Service Bus stress tests were using the wrong environment variables
- Event Hub stress-test-resources.json needed to output endpoints instead of connection strings.

[azservicebus,azeventhubs] some more stress test fixes

---

sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/assets.json
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/go.mod
sdk/storage/azblob/go.sum
sdk/storage/azblob/internal/testcommon/clients_auth.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azblob/testdata/perf/go.mod
sdk/storage/azblob/testdata/perf/go.sum
sdk/storage/azfile/assets.json
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/go.mod
sdk/storage/azfile/go.sum

Github issue : https://github.com/Azure/azure-sdk-for-go/issues/22869
Test Proxy update commit : [Upgrade test proxy, broken tests run only in live and recording modes · Azure/azure-sdk-for-go@c99558a (github.com)](https://github.com/Azure/azure-sdk-for-go/commit/c99558aa66d7b232efa1c684de8c97f8d19ede5a#diff-46d0ebc9894234059b248ce60e42668700b633985d10b9a0dd5032157a48a9a9)
Changes in few variable names are due to errors with conflicting variable name `policy` with the import `github.com/Azure/azure-sdk-for-go/sdk/azcore/policy`
Testa for blob and files are re-recorded in this PR 

Blob, Files - Tests refactor after testproxy update

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azure_pipelines_credential.go
sdk/azidentity/azure_pipelines_credential_test.go

Whoops, overlooked this when I renamed the credential type.

Fix AzurePipelinesCredential options name

---

sdk/messaging/azservicebus/internal/stress/stress-test-resources.bicep
sdk/messaging/azservicebus/test-resources.bicep

Deploying the main test-resources.bicep as a module, and parameterized the deployment of the Premium resource since we don't use that in stress testing.

[azservicebus] Updating templates so we use the same stuff for stress and normal integration testing

---

sdk/azcore/CHANGELOG.md
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/internal/pollers/async/async.go
sdk/azcore/internal/pollers/body/body.go
sdk/azcore/internal/pollers/fake/fake.go
sdk/azcore/internal/pollers/loc/loc.go
sdk/azcore/internal/pollers/op/op.go
sdk/azcore/internal/pollers/op/op_test.go
sdk/azcore/internal/pollers/util.go
sdk/azcore/internal/pollers/util_test.go
sdk/azcore/runtime/poller_test.go
sdk/azcore/testdata/perf/go.mod
sdk/azcore/testdata/perf/go.sum

When a status monitor includes the "final response", it's found in a JSON property named "result". When making a "final GET", the JSON path isn't used.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/22433

Operation-Location poller checks result property

---

sdk/storage/azfile/assets.json
sdk/storage/azfile/file/client_test.go

ClientName field is returned by List Handle API currently in the codebase. This PR tests this functionality.
API - https://learn.microsoft.com/en-us/rest/api/storageservices/list-handles#response
Since the testing requires File shares to be created, open file handles, and execute the test while holding the handle, the test cannot be made Live in pipeline, and is playback only.
Though live testing was completed successfully as given below -
PS C:\Windows\System32> net use S: \\xxxx.file.core.windows.net\tanyafileshare The command completed successfully.
Holding file handle and executing the test -
ClientName field is populated.

ListHandles Return additional ClientName field

---

sdk/azidentity/azidentity_test.go
sdk/azidentity/azure_pipelines_credential.go
sdk/azidentity/azure_pipelines_credential_test.go

This is the planned final constructor API. I'll update markdown docs in another PR.

Add AzurePipelinesCredential parameters to its constructor

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/assets.json
sdk/storage/azdatalake/directory/client_test.go
sdk/storage/azdatalake/file/client.go
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/file/examples_test.go
sdk/storage/azdatalake/file/models.go
sdk/storage/azdatalake/file/responses.go
sdk/storage/azdatalake/file/retry_reader.go
sdk/storage/azdatalake/filesystem/models.go
sdk/storage/azdatalake/internal/exported/exported.go
sdk/storage/azdatalake/internal/generated/zz_filesystem_client.go
sdk/storage/azdatalake/internal/generated/zz_path_client.go
sdk/storage/azdatalake/internal/generated/zz_service_client.go
sdk/storage/azdatalake/internal/path/responses.go
sdk/storage/azdatalake/internal/testcommon/common.go
sdk/storage/azdatalake/lease/client_test.go
sdk/storage/azdatalake/sas/service.go

[azdatalake] Added ACL response headers

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-eng-client.yml
eng/pipelines/templates/jobs/ci.tests.yml
eng/pipelines/templates/steps/build-test.yml
eng/scripts/run_tests.ps1
sdk/azcore/ci.yml
sdk/internal/ci.yml

This is a stop-gap until a more general solution is found. Some tests will cause an OOM when the race detector is enabled. For now, allow SDKs to opt in to the race detector if their tests don't cause an OOM.

Allow opt-in for Go race detector per SDK

---

sdk/security/keyvault/azcertificates/ci.yml
sdk/security/keyvault/azkeys/ci.yml
sdk/security/keyvault/azsecrets/ci.yml

Fixes https://github.com/Azure/azure-sdk-for-go/issues/22854
Adds sovereign cloud testing to weekly live tests

[keyvault] add sovereign cloud testing

---

eng/scripts/Language-Settings.ps1

It seems search depth 1 is going one directory deep when we want is to only search the current directory.

Change module search depth to 0

---

eng/pipelines/templates/steps/analyze.yml

This was changed in #23015 but go calls this script directly instead of via yaml templates due to artifact list typing issues

Fix validate package script to use new service connection

---

sdk/azidentity/azure_pipelines_credential_test.go
sdk/azidentity/ci.yml

Setting `UseFederatedAuth: true` and using environment variables set by the AzurePowerShell@5 task

Update AzurePipelinesCredential live test

---

sdk/internal/CHANGELOG.md
sdk/internal/go.mod
sdk/internal/go.sum

Need to ship upgraded dependencies so Component Governance stops flagging consumers

Prepare sdk/internal v1.9.1 for release

---

sdk/ai/azopenaiassistants/testdata/package-lock.json
sdk/ai/azopenaiassistants/testdata/package.json
sdk/messaging/eventgrid/aznamespaces/testdata/package-lock.json
sdk/messaging/eventgrid/aznamespaces/testdata/package.json
sdk/messaging/eventgrid/azsystemevents/testdata/package-lock.json
sdk/messaging/eventgrid/azsystemevents/testdata/package.json

A CVE for braces 3.0.2 affects these packages via the TSP compiler:
```
└─┬ @azure-tools/typespec-go 0.1.0-dev.4-20240517.1
└─┬ @typespec/compiler 0.56.0
└─┬ globby 14.0.1
└─┬ fast-glob 3.3.2
└─┬ micromatch 4.0.5
└── braces 3.0.2
```
typespec/compiler 0.58.0 upgrades around the problem but hasn't shipped and may contain breaking changes we can't immediately accommodate in `typespec-go`, so overriding `braces` is the simplest way to stop getting flagged for the CVE today.

Upgrade TSP dependencies affected by CVE

---

.github/CODEOWNERS

Need to have backup reviewers now that CODEOWNERS is bring strictly enforced.

CODEOWNERS needs a temp update in case of vacations

---

.github/CODEOWNERS
sdk/ai/azopenai/autorest.md

Nothing actually changes in the client, as it is today, because we've properly typed all 'any' fields.
Fixes #21009

[azopenai] Updating to use the rawjson-as-bytes config option. No code changes.

---

sdk/data/aztables/client_test.go

This doesn't have any functional impact, I just noticed while grepping for credential constructions that this test doesn't need a real credential.

Use fake credental in aztables client constructor test

---

sdk/messaging/eventgrid/aznamespaces/assets.json
sdk/messaging/eventgrid/aznamespaces/client_test.go
sdk/messaging/eventgrid/aznamespaces/example_publish_and_receive_test.go
sdk/messaging/eventgrid/aznamespaces/main_test.go
sdk/messaging/eventgrid/aznamespaces/shared_test.go

Fixing a few things:
- I had some workaround code for TokenCredential that's no longer necessary now that the service fix has been deployed.
- Using Charles's new test credential
- Fixing recordings to work again.
Fixes #22961

[aznamespaces] Test cleanup

---

sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/internal/testcommon/clients_auth.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azdatalake/internal/testcommon/clients_auth.go
sdk/storage/azfile/internal/testcommon/clients_auth.go

[credential.New()](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/internal/test/credential/credential.go#L22) enables deleting redundant code and simplifies keeping tests up to date with authentication changes in CI.

Use sdk/internal credential factory in storage tests

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/exported/exported_test.go
sdk/azcore/internal/exported/request.go
sdk/azcore/runtime/request.go

Adds a new function (NewRequestFromRequest) which lets you pass in an already created *http.Request and get back a policy.Request. 
This is used in situations where we want to run a pipeline outside of an Azure generated client.

[azcore] Adding in a function create a policy.Request using an existing *http.Request

---

sdk/ai/azopenai/CHANGELOG.md
sdk/ai/azopenai/custom_client.go

This PR enables `InsecureAllowCredentialWithHTTP` option for ai sdk custom_client

chore: Update custom_client.go to enable insecure credential with HTTP

---

.github/CODEOWNERS_baseline_errors.txt

Ran a script that:
- Check if the account with an exception is really used. If not, it should not be in exception
- Check if the account with an exception is now valid (using azure sdk tools script from @jsquire). If it's valid, no exception needed anymore.

Clean codeowner baseline

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blob/client.go
sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/file/client.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/23142
There are no tests in this PR since the existing tests for _DownloadFile_ are very much capable of testing if the functionality is still working correctly or not. 
The tests check if the downloaded file is correct or not by verifying the checksums. 
This PR reduces the number of calls to _GetProperties_ by populating the blob/file size in the options just after it is fetched from the properties call, so that they needn't be fetched again. 
Also, changes are done in AzBlob and AzFile, and not in AzDatalake, since datalake uses the _DownloadFile_ implemented in AzBlob. 

DownloadFile without Range.Count incurs 2 calls to GetProperties 

---

sdk/azidentity/device_code_credential.go
sdk/azidentity/interactive_browser_credential.go

The old link is still active and lands at the same page, so our published package docs are okay for now.

Update app registration guide link

---

sdk/resourcemanager/internal/CHANGELOG.md

* Use `sdk/internal` credential factory in tests
* Deprecated `testutil.FakeCredential`

[Release] sdk/resourcemanager/internal/v3.1.0

---

sdk/messaging/azservicebus/go.mod
sdk/messaging/azservicebus/go.sum

This is a quick fix to stop Component Governance flagging azservicebus. It isn't permanent because I believe the `replace` will block the release pipeline. `yaml.v2` arrives like this: 
```
github.com/microsoft/ApplicationInsights-Go@v0.4.4
└─── github.com/onsi/gomega@v1.5.0
└─── gopkg.in/yaml.v2@v2.2.1
```
Interesting that it appears in `go.sum` but not `go.mod`.

Upgrade azservicebus indirect yaml.v2 requirement

---

sdk/ai/azopenai/CHANGELOG.md
sdk/ai/azopenai/client_test.go
sdk/ai/azopenai/custom_client.go

Just finishing up the work to plumb InsecureAllowCredentialWithHTTP through all the client constructors for the azopenai Client.

[azopenai] Plumb `InsecureAllowCredentialWithHTTP` through every client constructor

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/managed_identity_client.go

This should create a better experience for some apps using DefaultAzureCredential on networks hosting something other than IMDS on `169.254.169.254`. ManagedIdentityCredential behavior when used directly is unchanged.
Closes #23250

DefaultAzureCredential continues after an unexpected IMDS response

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_http_trace.go
sdk/azcore/runtime/policy_http_trace_test.go

This simplifies creating spans with preset span attributes.

Add Attributes field to StartSpanOptions

---

eng/tools/generator/cmd/v2/common/cmdProcessor.go

fix: https://github.com/Azure/azure-rest-api-specs/pull/30000/checks?check_run_id=28389745036
filter go: downloading log...

fix generator tool: ExecuteGoGenerate func

---

sdk/containers/azcontainerregistry/authentication_policy.go
sdk/containers/azcontainerregistry/authentication_policy_test.go

The Go documentation strongly discourages structs from having methods with both pointer recievers and non-pointer recievers. For the auth policy, `getChallengeRequest` presumably did not have a pointer reciever since it did not make use of the struct at all. We can simply move this to a function.

azcontainerregistry: move method to function

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_client_test.go
sdk/azidentity/managed_identity_credential.go
sdk/azidentity/managed_identity_credential_test.go

NewManagedIdentityCredential returns an error for unsupported ID options

---

eng/emitter-package-lock.json
eng/emitter-package.json
eng/pipelines/mgmt-auto-release.yml
eng/scripts/automation_init.sh
eng/tools/generator/cmd/v2/automation/automationCmd.go
eng/tools/generator/cmd/v2/common/cmdProcessor.go

fix: https://github.com/Azure/azure-rest-api-specs/pull/29330/checks?check_run_id=28435203799

fix(generator tool): filter tsp-client diagnostics log

---

sdk/containers/azcontainerregistry/.gitignore
sdk/containers/azcontainerregistry/authentication_client.go
sdk/containers/azcontainerregistry/authentication_client_test.go
sdk/containers/azcontainerregistry/authentication_custom_client.go
sdk/containers/azcontainerregistry/authentication_custom_client_test.go
sdk/containers/azcontainerregistry/authentication_policy.go
sdk/containers/azcontainerregistry/authentication_policy_test.go
sdk/containers/azcontainerregistry/autorest.md
sdk/containers/azcontainerregistry/blob_custom_client.go
sdk/containers/azcontainerregistry/constants.go
sdk/containers/azcontainerregistry/constants_test.go
sdk/containers/azcontainerregistry/custom_client.go
sdk/containers/azcontainerregistry/models.go
sdk/containers/azcontainerregistry/models_serde.go
sdk/containers/azcontainerregistry/options.go
sdk/containers/azcontainerregistry/response_types.go

The ACR authentication API is a public-facing API. Consumers would like to use the well-tested code in the SDK to interface with this API instead of having to roll their own. This commit simply exposes all of the structs, functions and constants that are necessary to consume this API.
Part of https://github.com/Azure/azure-sdk-for-go/issues/20571

azcontainerregistry: expose authentication client, options

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_client.go
sdk/data/azcosmos/cosmos_client_retry_policy_test.go
sdk/data/azcosmos/cosmos_client_test.go
sdk/data/azcosmos/cosmos_container.go
sdk/data/azcosmos/cosmos_container_test.go
sdk/data/azcosmos/cosmos_database.go
sdk/data/azcosmos/cosmos_database_test.go
sdk/data/azcosmos/cosmos_global_endpoint_manager_test.go
sdk/data/azcosmos/emulator_cosmos_aad_test.go
sdk/data/azcosmos/emulator_cosmos_batch_test.go
sdk/data/azcosmos/emulator_cosmos_container_test.go
sdk/data/azcosmos/emulator_cosmos_database_test.go
sdk/data/azcosmos/emulator_cosmos_global_endpoint_manager_test.go
sdk/data/azcosmos/emulator_cosmos_item_test.go
sdk/data/azcosmos/emulator_cosmos_query_test.go
sdk/data/azcosmos/emulator_tests.go
sdk/data/azcosmos/go.mod
sdk/data/azcosmos/go.sum
sdk/data/azcosmos/operation_type.go
sdk/data/azcosmos/otel_constants.go
sdk/data/azcosmos/otel_constants_test.go
sdk/data/azcosmos/tracing_test.go
sdk/data/azcosmos/version.go

This PR modifies `Client` to have the internal `azcore.Client` embedded to leverage the Pipeline and Trace.
All the methods (except Pagers because they internally already do it) that execute an async operation will now start a Span respectively.
Added a helper SpanValidator to be used in tests to validate that the expected Spans are generated.
Reference: https://github.com/open-telemetry/semantic-conventions/blob/v1.27.0/docs/database/cosmosdb.md
* The code defines the `TracingOptions` to set `az.namespace` to `Microsoft.DocumentDB`
* `db.system` = `cosmosdb`
* `db.cosmosdb.connection_mode` = `gateway`
* `db.namespace` (when applicable) = datbase id
* `db.collection.name` (when applicable) = container id
* `db.operation.name` = span name (for example `create_container`)
* `server.address` …

Cosmos DB: Add support for Span

---

sdk/storage/azfile/share/client_test.go

This reverts commit bdf95c4373b69ac828e25bbfc0fc8e5a0ef1993c.

Revert "Added AuthenticationErrorDetail test"

---

sdk/resourcemanager/servicefabricmesh/armservicefabricmesh/secretvalue_client_example_test.go

The current fake value sets off secret scanners because it has a realistic shape. I've opened https://github.com/Azure/azure-rest-api-specs/pull/30166 to upstream this new, faker value but am making the change manually here to more quickly block false positives.

Make Service Fabric example secret more obviously fake

---

sdk/ai/azopenai/CHANGELOG.md

We got a community contribution to plumb the insecure flag through the library and it didn't get released last time.
Fixes #23313

[azopenai] prep for release (bugfix)

---

sdk/azidentity/ci.yml
sdk/azidentity/test-resources-post.ps1

The post script uses the Azure CLI to deploy test applications. Switching the pipeline to federated auth broke its login because the test resource deployment script no longer provides a service principal secret. With this PR the script instead logs in a federated identity using a token acquired in a pre step (this token isn't available in the Azure PowerShell task that runs the script).

Authorize azidentity test app deployment with WIF

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/internal/eh/stress/Chart.lock
sdk/messaging/azeventhubs/internal/eh/stress/templates/stress-test-job.yaml
sdk/messaging/azeventhubs/internal/eh/stress/tests/shared.go
sdk/messaging/azeventhubs/internal/links.go
sdk/messaging/azeventhubs/internal/links_recover.go
sdk/messaging/azeventhubs/internal/links_test.go

Fixing a customer issue where they cancel in the middle of our retry loop and prevent our recovery from happening.
This simplifies the overall logic and should be just fine - some of the cases it was trying to handle aren't needed anymore because of changes in the recovery code, etc...
Also, updated stress tests to include pipefail, which makes sure that, if the underlying test fails, the script _exits_ instead of potentially reporting okay because `tee` happened to work :) Also, the stress tests were incorrectly using the test credential, and we can't/don't use that in stress testing.
Fixes #23282

[azeventhubs] Fixing a bug where a cancelled recovery could result in a perpetually broken client

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_client_retry_policy.go
sdk/data/azcosmos/cosmos_client_retry_policy_test.go
sdk/data/azcosmos/cosmos_global_endpoint_manager.go
sdk/data/azcosmos/cosmos_global_endpoint_manager_test.go
sdk/data/azcosmos/cosmos_location_cache.go

Metadata read requests (not item operations) can be routed to any available regions. Metadata write requests, should always be routed to the primary / hub region.
In cases where the account is Single Write Region, this rule applies correctly.
The SDK allows users to define a list of Preferred Regions to route requests preferably. This preference applies in the following way:
* Single Write Region: Affects read operations
* Multi Write Region: Affects read and write operations
The problem is that the above rules should apply for Item operations. Metadata operations, even on a Multi Write Region account, cannot be routed to secondary regions.
Currently when routing requests, the Global Endpoint Manager is treating all requests the same way and for Metadata write operations and Multi Write …

Cosmos DB: Fixes metadata routing on multi-master

---

sdk/containers/azcontainerregistry/assets.json
sdk/containers/azcontainerregistry/authentication_policy_test.go
sdk/containers/azcontainerregistry/blob_client_test.go
sdk/containers/azcontainerregistry/blob_custom_client_test.go
sdk/containers/azcontainerregistry/ci.yml
sdk/containers/azcontainerregistry/client_test.go
sdk/containers/azcontainerregistry/go.mod
sdk/containers/azcontainerregistry/go.sum
sdk/containers/azcontainerregistry/test-resources-post.ps1
sdk/containers/azcontainerregistry/test-resources.bicep
sdk/containers/azcontainerregistry/testdata/Dockerfile
sdk/containers/azcontainerregistry/utils_test.go

Live tests are flaky and usually fail today because they import images from Docker Hub to the test registry, and Docker Hub throttles anonymous pulls. Furthermore, the test suite is hard to maintain because relationships and dependencies between imported images and test cases aren't clear. Some tests refer to images by name, some refer to images or their layers by hard-coded digest, tests can break each other by performing destructive operations on a shared image, etc. This PR addresses these problems by building images on demand via ACR scheduled tasks and organizing tests around the images they operate on so tests own images and don't need to hard-code any details.
Closes #22988

azcontainerregistry tests build images instead of importing them

---

sdk/security/keyvault/TROUBLESHOOTING.md
sdk/security/keyvault/azadmin/TROUBLESHOOTING.md
sdk/security/keyvault/azcertificates/MIGRATION.md
sdk/security/keyvault/azkeys/MIGRATION.md
sdk/security/keyvault/azsecrets/MIGRATION.md

Closes https://github.com/Azure/azure-sdk-for-go/issues/21078
Update troubleshooting guide
Add migration guide

[keyvault] troubleshooting and migration guide

---

sdk/messaging/azservicebus/go.mod
sdk/messaging/azservicebus/go.sum
sdk/messaging/azservicebus/internal/errors.go
sdk/messaging/azservicebus/internal/errors_test.go
sdk/messaging/azservicebus/internal/stress/Chart.lock
sdk/messaging/azservicebus/internal/stress/stress-test-resources.bicep
sdk/messaging/azservicebus/receiver_test.go
sdk/messaging/azservicebus/test-resources.bicep

Found a few bugs that came in as we crossed between go-amqp versions. We weren't properly unwrapping errors, which meant that our AMQP condition based recovery code wasn't running. This still works most of the time, but it's best to correct it now.
- Upgrading to latest go-amqp, which lets us errors.As() for the AMQP error.
- GetRecoveryKind() should check the AMQP errors's condition first as it has more specific information about what's broken
- Updated all the tests to account for this new possiblity (wrapped error being ignored in favor of the AMQP condition in the inner AMQP error)
- Deleted two unused error types (ErrConnectionClosed, ErrNotFound)
- Did a small amount of cleanup to eliminate some lint warnings, and to delete unused error types that were left over from our original …

[azservicebus] Fixing error checking to take error wrapping into account

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/zz_blockblob_client.go
sdk/storage/azblob/internal/generated/zz_responses.go

Add crc header in put blob response

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/internal/constants.go
sdk/messaging/azeventhubs/internal/rpc.go
sdk/messaging/azeventhubs/internal/rpc_test.go
sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/internal/rpc.go
sdk/messaging/azservicebus/internal/rpc_test.go

Fixing a bug where we could end up getting our management link stuck.
The problem was basically a combination of errors:
1. We were missing the sender settlement mode, which made it so we were only 1/2 in the "receive and delete" mode that we intended to be.
2. Ignoring that, our AcceptMessage() call was actually load bearing and critical and _wasn't_ getting called in some cases, like if you cancelled the call.

[azservicebus] Fixing a bug where our management link would hang in certain circumstances

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_dedicated_gateway_request_options.go
sdk/data/azcosmos/cosmos_http_constants.go
sdk/data/azcosmos/cosmos_item_request_options.go
sdk/data/azcosmos/cosmos_item_request_options_test.go
sdk/data/azcosmos/cosmos_query_request_options.go
sdk/data/azcosmos/cosmos_query_request_options_test.go

Ref: https://github.com/Azure/azure-sdk-for-go/issues/23368
Add support for the `MaxIntegratedCacheStaleness` param as Azure docs point to this option being configurable https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-configure-integrated-cache?tabs=dotnet#adjust-maxintegratedcachestaleness.

Add support for MaxIntegratedCacheStaleness option

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity_test.go
sdk/azidentity/azure_cli_credential_test.go
sdk/azidentity/azure_developer_cli_credential_test.go
sdk/azidentity/azure_pipelines_credential.go
sdk/azidentity/chained_token_credential.go
sdk/azidentity/chained_token_credential_test.go
sdk/azidentity/confidential_client.go
sdk/azidentity/errors.go
sdk/azidentity/errors_test.go
sdk/azidentity/managed_identity_client.go
sdk/azidentity/public_client.go

```
DefaultAzureCredential authentication failed. failed to acquire a token.
Attempted credentials:
EnvironmentCredential: missing environment variable AZURE_TENANT_ID
WorkloadIdentityCredential: no client ID specified. Check pod configuration or set ClientID in the options
ManagedIdentityCredential authentication failed. ManagedIdentityCredential authentication failed. authentication failed
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 401 Unauthorized
--------------------------------------------------------------------------------
{
"error": "unauthorized"
}
--------------------------------------------------------------------------------
To troubleshoot, visit …
```

Remove redundant auth error content

---

.github/CODEOWNERS

Add Operator Nexus - Network Cloud to CODEOWNERS file to receive bot notifications

Adding Operator Nexus - Network Cloud to CODEOWNERS

---

.github/CODEOWNERS

(otherwise we have to rely on Wes/Ben to do it every time)

Updating CODEOWNERS so the Go SDK team can approve changes to config.json

---

sdk/azidentity/README.md

Move DAC and ChainedTokenCredential to a new section in the README. It's misleading to include them in a section titled "Authenticating Azure Hosted Applications".

Create credential chains section in Azure Identity README

---

sdk/storage/azblob/internal/generated/autorest.md
sdk/storage/azblob/internal/generated/constants.go
sdk/storage/azblob/internal/generated/zz_appendblob_client.go
sdk/storage/azblob/internal/generated/zz_blob_client.go
sdk/storage/azblob/internal/generated/zz_blockblob_client.go
sdk/storage/azblob/internal/generated/zz_container_client.go
sdk/storage/azblob/internal/generated/zz_pageblob_client.go
sdk/storage/azblob/internal/generated/zz_service_client.go
sdk/storage/azfile/internal/generated/autorest.md
sdk/storage/azfile/internal/generated/constants.go
sdk/storage/azfile/internal/generated/zz_constants.go
sdk/storage/azfile/internal/generated/zz_directory_client.go
sdk/storage/azfile/internal/generated/zz_file_client.go
sdk/storage/azfile/internal/generated/zz_models.go
sdk/storage/azfile/internal/generated/zz_models_serde.go
sdk/storage/azfile/internal/generated/zz_options.go
sdk/storage/azfile/internal/generated/zz_response_types.go
sdk/storage/azfile/internal/generated/zz_service_client.go
sdk/storage/azfile/internal/generated/zz_share_client.go

Only swagger change is in files, others use the previous swagger and only updates in the service version

[Storage] Swagger update for stg95

---

sdk/security/keyvault/azadmin/backup/client_test.go

Modifying the poller so that it polls every second instead of every 30 seconds in playback mode. Now in playback mode it'll take the tests 2 seconds to complete instead of 67.

[azadmin] change frequency of poller in tests

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/TROUBLESHOOTING.md
sdk/azidentity/azure_pipelines_credential.go
sdk/azidentity/azure_pipelines_credential_test.go

* enable logging for a couple DevOps response headers the service team uses when debugging and include them in errors. Closes #23444
* instruct OIDC endpoint to return 401 instead of 302 when given an invalid access token. Closes #23482

Improve AzurePipelinesCredential diagnosability

---

eng/scripts/run_tests.ps1

Powershell passes the empty string default value for race detector as a positional argument, which is causing the go command line to treat it as the test selector argument, instead of `./...`. This has been causing all pipelines to not run any tests in sub-directories since June 2024.
Hat tip to @gracewilcox for discovering this issue.

Pass race detector value in only when it is set

---

sdk/azcore/CHANGELOG.md
sdk/azcore/errors.go
sdk/azcore/internal/exported/response_error.go
sdk/azcore/internal/exported/response_error_test.go

The *http.Request inside the *http.Response contains fields that aren't marshalable (func). Since the RawResponse is used to construct the error message which isn't contractual, just omit it from the payload.
Fixes https://github.com/Azure/azure-sdk-for-go/issues/23454

Omit RawResponse from JSON payload

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_retry.go
sdk/azcore/runtime/policy_retry_test.go

The current `calcDelay` overflows when `try` >= 36 when using default retry options settings (800ms). Example: https://go.dev/play/p/-w0DcQsN1cD . This pull request fixed by adding bound checks on the values.
The new implementation does not increase the overhead of the function per the benchmark results:
```
$ go test -v -bench=. -run=BenchmarkCalcDelay -benchtime=20s
goos: linux
goarch: amd64
pkg: github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime
cpu: AMD EPYC 7763 64-Core Processor                
BenchmarkCalcDelay_defaultSettings
BenchmarkCalcDelay_defaultSettings-2    1000000000              17.03 ns/op
BenchmarkCalcDelay_overflow
BenchmarkCalcDelay_overflow-2           1000000000              16.64 ns/op
PASS
ok      github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime    37.016s …
```

fix: integer overflow on calcDelay

---

eng/pipelines/mgmt-auto-release.yml
eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml
eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-eng-client.yml
eng/pipelines/templates/jobs/mgmt-mock-test.yml
eng/pipelines/templates/stages/ci-platform-matrix-complete.json
eng/pipelines/templates/stages/ci-platform-matrix.json
eng/pipelines/templates/stages/platform-matrix.json
eng/pipelines/templates/variables/globals.yml
eng/scripts/automation_init.sh
sdk/azcore/messaging/cloud_event_test.go
sdk/internal/log/log.go
sdk/internal/recording/recording.go
sdk/internal/recording/server.go

Remove setting nocoverageredesign as the underlying issue has been fixed, so it's no longer required.
Update to latest version of golangci-lint.

Update to the latest two versions of Go

---

sdk/azidentity/client_assertion_credential_test.go
sdk/azidentity/device_code_credential_test.go
sdk/azidentity/on_behalf_of_credential_test.go

The latest golangci-lint adds `SA1029: should not use empty anonymous struct as key for value; define your own type to avoid collisions`

Name anonymous struct types in azidentity tests

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/live.tests.yml
sdk/azidentity/ci.yml
sdk/azidentity/test-resources-post.ps1
sdk/containers/azcontainerregistry/ci.yml
sdk/containers/azcontainerregistry/test-resources-post.ps1
sdk/containers/azcontainerregistry/utils_test.go

This should fix the weekly pipelines for azidentity and azcontainerregistry (this one still fails, but it's not engsys' fault anymore).
Relies on https://github.com/Azure/azure-sdk-tools/pull/9099 going in first.

Use common OIDC token env vars in post scripts

---

sdk/storage/azblob/assets.json
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/container/client_test.go
sdk/storage/azblob/internal/exported/shared_key_credential.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azdatalake/directory/client_test.go
sdk/storage/azdatalake/file/client_test.go
sdk/storage/azdatalake/internal/exported/shared_key_credential.go
sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/internal/exported/shared_key_credential.go
sdk/storage/azfile/service/client_test.go
sdk/storage/azfile/share/client_test.go

Fixed a Panic in the test :- TestUploadBlobWithMD5WithCPK() which was caused due to a functional issue in the compareHeaders custom sorting algorithm. 

fixing the compareHeaders sorting algorithm

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_http_trace.go
sdk/azcore/runtime/policy_http_trace_test.go

This PR adds a `Kind` field to azcore's StartSpanOptions so that consumers of `azcore.StartSpan` can customize the span kind.
I plan to follow up with a PR against azcosmos where it can classify its spans as Client spans so that consumers of azcosmos have its spans show up like db client spans.

Allow the span kind to be set via StartSpanOptions

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go
sdk/azcore/runtime/policy_bearer_token.go
sdk/azcore/runtime/policy_bearer_token_test.go

`http.Client` is not kind: it reads every request body and never rewinds. `BearerTokenPolicy` must therefore rewind bodies before retrying requests, to ensure the transport includes content when sending a retry.

BearerTokenPolicy rewinds bodies before retrying

---

sdk/security/keyvault/internal/CHANGELOG.md
sdk/security/keyvault/internal/challenge_policy_test.go
sdk/security/keyvault/internal/constants.go
sdk/security/keyvault/internal/go.mod
sdk/security/keyvault/internal/go.sum

Closes https://github.com/Azure/azure-sdk-for-go-pr/issues/43
Adding CAE support to key vault libraries:
* Upgrade to the latest version of azcore with CAE support
* Add tests to the key vault challenge policy to ensure that it's compatible with CAE

[keyvault] add cae support

---

sdk/storage/azfile/assets.json
sdk/storage/azfile/directory/client_test.go
sdk/storage/azfile/directory/constants.go
sdk/storage/azfile/directory/models.go
sdk/storage/azfile/file/constants.go
sdk/storage/azfile/file/models.go
sdk/storage/azfile/share/constants.go
sdk/storage/azfile/share/models.go

This reverts commit ff52c44237a6bcdbd6ef1bbc2435f984c0581274.

Revert "added new tests with recordings"

---

sdk/security/keyvault/internal/CHANGELOG.md
sdk/security/keyvault/internal/challenge_policy.go
sdk/security/keyvault/internal/challenge_policy_test.go

This fix allows the KeyVault client to access resources across tenants by correctly placing the tenant ID returned by the challenge into the `policy.TokenRequestOptions`.
Fixes #22928.

Allow the Key Vault client to access resources across tenants

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_client.go
sdk/data/azcosmos/cosmos_client_test.go
sdk/data/azcosmos/emulator_cosmos_aad_test.go
sdk/data/azcosmos/emulator_cosmos_batch_test.go
sdk/data/azcosmos/emulator_cosmos_container_test.go
sdk/data/azcosmos/emulator_cosmos_database_test.go
sdk/data/azcosmos/emulator_cosmos_global_endpoint_manager_test.go
sdk/data/azcosmos/emulator_cosmos_item_test.go
sdk/data/azcosmos/emulator_cosmos_query_test.go
sdk/data/azcosmos/tracing_test.go

When https://github.com/Azure/azure-sdk-for-go/pull/23268 was being considered there was [a request](https://github.com/Azure/azure-sdk-for-go/pull/23268#discussion_r1712146494) to add attributes based on the response.
This PR adds `db.cosmosdb.request_charge` and `db.cosmosdb.status_code` to all requests (at least the ones that make use of `executeAndEnsureSuccessResponse` which appear to be all of them right now.
I could not figure out how to get the sub status code out of the HTTP response. I'd be happy to add it here or in a follow up if I can get some help as to where to find it in the response.
Refs: https://github.com/Azure/azure-sdk-for-go/issues/23308
[Azure/autorest.go]: …

Add some response values as attributes to the azcosmos traces

---

sdk/security/keyvault/azadmin/CHANGELOG.md
sdk/security/keyvault/azadmin/backup/client_test.go
sdk/security/keyvault/azadmin/backup/custom_client.go
sdk/security/keyvault/azadmin/rbac/client_test.go
sdk/security/keyvault/azadmin/rbac/custom_client.go
sdk/security/keyvault/azadmin/settings/client_test.go
sdk/security/keyvault/azadmin/settings/custom_client.go
sdk/security/keyvault/azcertificates/CHANGELOG.md
sdk/security/keyvault/azcertificates/client_test.go
sdk/security/keyvault/azcertificates/custom_client.go
sdk/security/keyvault/azkeys/CHANGELOG.md
sdk/security/keyvault/azkeys/client_test.go
sdk/security/keyvault/azkeys/custom_client.go
sdk/security/keyvault/azsecrets/CHANGELOG.md
sdk/security/keyvault/azsecrets/client_test.go
sdk/security/keyvault/azsecrets/custom_client.go

Closes https://github.com/Azure/azure-sdk-for-go/issues/22396
Adds API version support. Instead of only being able to use the default version, users can now set the API version themselves.

[key vault] add api version support

---

sdk/azidentity/BREAKING_CHANGES.md

Documenting new constructor errors in v1.8.0

Update azidentity's BREAKING_CHANGES.md

---

sdk/azidentity/cache/CHANGELOG.md
sdk/azidentity/cache/cache.go

Closes #23588 by randomizing the name of the cache used to test the storage implementation. This makes it feasible for at least 90 processes on Linux and 1000+ on macOS and Windows to call `cache.New` simultaneously.

Enable concurrent process to construct persistent caches

---

sdk/azidentity/ci.yml

TME subscription (#23570) lacks quota for the necessary resources in the default region (westus)

Run live managed identity tests in westus2

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_client.go
sdk/data/azcosmos/cosmos_container.go
sdk/data/azcosmos/cosmos_database.go
sdk/data/azcosmos/emulator_cosmos_container_test.go
sdk/data/azcosmos/emulator_cosmos_database_test.go
sdk/data/azcosmos/emulator_cosmos_query_test.go

- Refs https://github.com/Azure/azure-sdk-for-go/issues/23294
Originally the thought was that the azcore Pager should provide a way to better customize the spans it creates, and that the azcosmos Pager based spans could take advantage of that.
As I was digging it to try to make that work I did realize a few things.
1. The spans being set within the azcosmos Fetcher functions are currently being surpressed due to the StartSpan code policy to not allow nested spans most of the time.
2. Adding a way to customize the span creation in the azcore Pager would add complexity for what is currently just a simple wrapper around the Fetcher function
3. If a Tracer is not set on the PagingHandler a null Tracer is used which results in StartSpan not adding an active span to the context.
Considering all …

Azcosmos no tracer to pager

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity.go
sdk/azidentity/confidential_client.go
sdk/azidentity/confidential_client_test.go
sdk/azidentity/public_client.go
sdk/azidentity/public_client_test.go

Today, user credentials log scopes correctly only after acquiring a token from the cache. After acquiring a new token, the logged scopes are always `""`

User credential types consistently log token scopes

---

sdk/storage/azblob/internal/shared/mmf_unix.go

Add support for zos to storage/azblob. This is mainly to enable building modules that depend on the azure-sdk module in some capacity.
Due to hardware requirements tests are not updated.

Add zos support to storage/azblob

---

eng/tools/generator/typespec/typespec-go.go
eng/tools/generator/typespec/typespec-go_test.go

(NOTE: I'm not sure if this is the true home for this code, or just a copy - please advise!)
Data plane module paths don't include `resourcemanager` and `arm`, so they were failing the previous regex. I modified it to allow both types, and, if it's data plane, to allow 'az' as the prefix.
This was causing a build failure for me here: https://github.com/Azure/azure-rest-api-specs/pull/31719/checks?check_run_id=33822699487

Allow data plane module paths

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/pollers/op/op.go
sdk/azcore/internal/pollers/op/op_test.go
sdk/azcore/runtime/poller.go
sdk/azcore/runtime/poller_test.go

The result path must be configurable instead of hard-coded to result.

Add OperationLocationResultPath to NewPollerOptions[T]

---

sdk/messaging/azeventhubs/CHANGELOG.md
sdk/messaging/azeventhubs/consumer_client.go
sdk/messaging/azeventhubs/example_consumerclient_test.go
sdk/messaging/azeventhubs/example_producerclient_test.go
sdk/messaging/azeventhubs/internal/constants.go
sdk/messaging/azeventhubs/internal/namespace.go
sdk/messaging/azeventhubs/producer_client.go
sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/client.go
sdk/messaging/azservicebus/example_client_test.go
sdk/messaging/azservicebus/internal/constants.go
sdk/messaging/azservicebus/internal/namespace.go

This is a feature that .NET has, and it's handy for when you need to route your TCP traffic through a proxy. It also enables some testing scenarios.
APIViews:
- azservicebus: https://apiview.dev/Assemblies/Review/0579bbe5a2324f17a48f1a2bca2ff383?revisionId=e548a02147214107802f26ba47e2a9bf&diffOnly=True&doc=False&diffRevisionId=868bd2a67e9641a3bad83fb66cde2dc4
- azeventhubs: https://apiview.dev/Assemblies/Review/e1445c654ad0416c821be30b02dc445c/3c935256189a453ead108bc9fd3ec9f2?diffRevisionId=51318a1ab3b44f2486db3d3f860834f1&doc=False&diffOnly=True

[azservicebus/azeventhubs] Enable custom endpoints, which allows our library to be used with TCP proxies

---

sdk/messaging/eventgrid/azeventgrid/internal/version.go
sdk/messaging/eventgrid/aznamespaces/internal/version.go
sdk/messaging/eventgrid/azsystemevents/internal/version.go
sdk/template/aztemplate/version.go

Fixing all the outdated projects - ModuleName is intended to be the full module path, not just the folder name.
Also, updated the template project.

Fixing ModuleName to be compliant with the standard

---

sdk/azcore/CHANGELOG.md
sdk/azcore/arm/internal/resource/resource_identifier.go
sdk/azcore/arm/internal/resource/resource_identifier_test.go

It would be handy for [ResourceID](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/internal/resource#ResourceID) to support the [encoding.TextMarshaler](https://pkg.go.dev/encoding@go1.23.0#TextMarshaler) and [encoding.TextUnmarshaler](https://pkg.go.dev/encoding@go1.23.0#TextUnmarshaler) interfaces so that, for example, JSON data that includes a resource ID string can be unmarshaled directly to a [ResourceID](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/internal/resource#ResourceID) struct (and vice versa for marshaling).

[azcore] Add text [un]marshalling support to ResourceID

---

sdk/monitor/query/azmetrics/CHANGELOG.md
sdk/monitor/query/azmetrics/client_test.go
sdk/monitor/query/azmetrics/custom_client.go
sdk/monitor/query/azmetrics/version.go

Closes #23819
Adds API version support. Instead of only being able to use the default version, users can now set the API version themselves.

[azmetrics] add api version support

---

documentation/code-generation.md

Add documentation for Management Plane Generation of SDKs using TypeSpec

Add Documentation for MPG SDK generation

---

sdk/storage/azblob/client.go

Documentation correction for create container error

---

eng/tools/generator/cmd/v2/automation/automationCmd.go
eng/tools/generator/cmd/v2/release/releaseCmd.go
eng/tools/generator/typespec/tspconfig.go
eng/tools/generator/typespec/tspconfig_test.go

fix: https://github.com/Azure/azure-sdk-for-go/issues/23820

enhance generator code to support different module path config

---

sdk/monitor/azquery/ci.yml
sdk/monitor/ingestion/azlogs/ci.ingestion.yml
sdk/monitor/query/azlogs/ci.yml
sdk/monitor/query/azmetrics/ci.yml
sdk/security/keyvault/azcertificates/ci.yml
sdk/security/keyvault/azkeys/ci.yml
sdk/security/keyvault/azsecrets/ci.yml

Eng sys team currently has the USGov testing tenant shutdown.
Disabling all sovereign cloud tests in the weekly pipelines until they come to a decision on sovereign cloud testing.

disable sovereign cloud

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity.go
sdk/azidentity/azidentity_test.go
sdk/azidentity/azure_cli_credential.go
sdk/azidentity/azure_developer_cli_credential.go
sdk/azidentity/default_azure_credential.go
sdk/azidentity/device_code_credential.go
sdk/azidentity/interactive_browser_credential.go

This PR prevents tenant verification errors when these credentials are configured with default options. For example, this GetToken call returns an error in the last release:
```go
cred, _ := azidentity.NewAzureCLICredential(nil)
_, err := cred.GetToken(context.TODO(), policy.TokenRequestOptions{
Scopes: scopes,
TenantID: "A",
}
```
> AzureCLICredential isn't configured to acquire tokens for tenant "A". To enable acquiring tokens for this tenant add it to the AdditionallyAllowedTenants...
With this PR, tenant verification applies only when the credential's `TenantID` option is set. So, the above call will no longer return an error, but this one will, because the credential's configured tenant doesn't match the requested tenant:
```go
cred, _ := …
```

Relax tenant verification for credentials having optional tenant IDs

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_container.go
sdk/data/azcosmos/cosmos_headers_policy.go
sdk/data/azcosmos/cosmos_http_constants.go
sdk/data/azcosmos/cosmos_query_request_options.go
sdk/data/azcosmos/emulator_cosmos_query_test.go
sdk/data/azcosmos/emulator_tests.go
sdk/data/azcosmos/shared_key_credential.go

This PR adds very limited support for cross-partition queries to the Cosmos Go SDK.
It works by _always_ adding the `enablecrosspartitionquery` header to the query request. We didn't want to make a separate option because in the future we're hoping to have richer support for cross partition queries that can be lit up automatically.
> [!IMPORTANT]
> The cross-partition query functionality added here is **limited** to cross-partition queries that can be successfully executed against the Gateway API. See https://learn.microsoft.com/en-us/rest/api/cosmos-db/querying-cosmosdb-resources-using-the-rest-api#queries-that-cannot-be-served-by-gateway for more details. The doc comments describe this limitation.
I'm hoping the doc comments largely explain things, so I don't want to get too deep here, …

[azcosmos] Add LIMITED cross-partition query support

---

sdk/ai/azopenaiassistants/client_vectorstores_test.go
sdk/ai/azopenaiassistants/shared_test.go

As files are updated on the backend, the iteration order changes. The paging aspect of this isn't critical, so I'm just removing it, making the test reliable again.

[azopenaiassistants] Removing a bit that was making an assistants test less reliable

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/filesystem/client.go
sdk/storage/azdatalake/filesystem/client_test.go
sdk/storage/azdatalake/filesystem/examples_test.go
sdk/storage/azdatalake/filesystem/models.go
sdk/storage/azdatalake/filesystem/responses.go
sdk/storage/azdatalake/internal/generated/autorest.md
sdk/storage/azdatalake/internal/generated/zz_constants.go
sdk/storage/azdatalake/internal/generated/zz_filesystem_client.go
sdk/storage/azdatalake/internal/generated/zz_options.go
sdk/storage/azdatalake/internal/generated/zz_path_client.go

`azure-sdk-for-go` issue:  #23852 
other relevant issue: https://github.com/Azure/azure-rest-api-specs/issues/31894
@tanyasethi-msft  Please review :slightly_smiling_face:

feat: Add NewListDirectoryPathsPager for azuredatalake

---

sdk/internal/recording/server.go
sdk/internal/recording/server_test.go

This prevents overwriting arbitrary files outside the target directory. We already return an error for such paths in zips but not in tarballs. I added a test for both cases.

Return an error for nonlocal paths in test proxy archives

---

sdk/azidentity/azure_cli_credential.go

The set of characters we allow for a subscription name is drawn from general Azure guidelines because subscription name requirements aren't well documented. We disallow some characters that are valid in a subscription name, such as `()`. Rather than allow valid characters that may be unsafe to interpolate into a command line, this PR clarifies the error message and recommends customers work around a validation error by using the subscription's ID (a UUID) instead of its name.

Clarify AzureCLICredential invalid Subscription error

---

eng/tools/doccheck/main.go
eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/indexer/util/util.go
eng/tools/internal/coverage/coverage.go
eng/tools/internal/report/packages.go
eng/tools/profileBuilder/model/latest.go
eng/tools/profileBuilder/model/transforms.go
eng/tools/smoketests/cmd/root.go

filepath.Walk calls os.Lstat for every file or directory to retrieve os.FileInfo, which can be slower. filepath.WalkDir avoids unnecessary system calls since it provides a fs.DirEntry, which includes file type information without requiring a stat call.

Perf: Use WalkDir for optimized directory traversal

---

sdk/messaging/azeventhubs/internal/test/test_helpers.go
sdk/messaging/azeventhubs/test-resources.bicep
sdk/messaging/azservicebus/admin/admin_client_test.go
sdk/messaging/azservicebus/client_test.go
sdk/messaging/azservicebus/internal/test/test_helpers.go
sdk/messaging/azservicebus/receiver_test.go
sdk/messaging/azservicebus/test-resources.bicep

Local resources can no longer contain any connection strings so we need to enable it conditionally. 
A change in New-TestResources.ps1 will pass the flag, so this is just making the change ahead of time and is okay to merge.

Conditionally allow and test connection strings (only in TME)

---

eng/tools/generator/cmd/issue/link/common.go
eng/tools/generator/cmd/v2/common/changelogProcessor.go
eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/refresh/refreshCmd.go
eng/tools/generator/cmd/v2/release/releaseCmd.go
eng/tools/internal/coverage/coverage.go
eng/tools/mgmtreport/main.go
eng/tools/profileBuilder/model/latest.go
eng/tools/profileBuilder/model/transforms.go
eng/tools/smoketests/cmd/root.go
sdk/internal/recording/server.go

Remove strings.Contains to: 
- Update findCoverageFile to match exact file names.
- Enhance includePreviewPredicate for exact names.
- Direct file checking of go.mod.
- Remove hardcoded previewSubdir const
Remove path packge methods: 
- Use path/filepath methods to make it cross platform.
- Use filepath.Ext for file extension.

fix: make it os compatible. 

---

sdk/azidentity/MIGRATION.md
sdk/azidentity/README.md
sdk/azidentity/cache/README.md
sdk/data/azappconfig/README.md
sdk/data/azcosmos/README.md
sdk/data/aztables/README.md
sdk/messaging/azeventhubs/README.md
sdk/messaging/azservicebus/README.md
sdk/security/keyvault/azcertificates/README.md
sdk/security/keyvault/azkeys/README.md
sdk/security/keyvault/azsecrets/README.md
sdk/storage/azblob/README.md

Pixels like these were used to track impressions on READMEs, deleteing them in accordance to latest policy
```markdown
```

Removing impression tracking pixels from READMEs ***NO_CI***

---

eng/tools/generator/cmd/v2/common/generation.go

always do beta release for first release & refactor generator

---

sdk/azcore/CHANGELOG.md
sdk/azcore/core_test.go
sdk/azcore/internal/shared/constants.go
sdk/azcore/tracing/tracing.go
sdk/azcore/tracing/tracing_test.go

Adding Propagator and Links to `azcore/tracing`. This will allow context propagation and span links in the SDK.

[azcore/tracing] Add propagator and link wrapper

---

sdk/storage/azdatalake/directory/client_test.go
sdk/storage/azdatalake/file/client.go
sdk/storage/azdatalake/file/client_test.go

Convert to dfs error while getproperties call

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/version.go

Updates changelog and version number for 1.3.0 release.
Details, including a link to the included PR, can be found in the Changelog. The only thing in this release is the limited support for cross-partition queries that can be served from the gateway.

Changelog updates for Cosmos release 1.3.0

---

eng/emitter-package-lock.json
eng/emitter-package.json

Upgrading the liftr base package version to 0.7.0 as per azure spec repo. Facing failure in https://github.com/Azure/azure-rest-api-specs/pull/32582

Updating Liftr base package version

---

sdk/security/keyvault/azsecrets/CHANGELOG.md
sdk/security/keyvault/internal/CHANGELOG.md
sdk/security/keyvault/internal/challenge_policy.go
sdk/security/keyvault/internal/challenge_policy_test.go
sdk/security/keyvault/internal/ci.keyvault.yml
sdk/security/keyvault/internal/go.mod
sdk/security/keyvault/internal/go.sum

Closes https://github.com/Azure/azure-sdk-for-go/issues/24031
Same PR as https://github.com/Azure/azure-sdk-for-go/pull/24032
This PR fixes the race condition in the keyvault internal module's challenge policy.
Thank you @strager for your hard work!

[keyvault] make challenge policy thread safe

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/managed_identity_client.go
sdk/azidentity/managed_identity_credential_test.go

Log user-assigned managed identity IDs

---

sdk/security/keyvault/internal/CHANGELOG.md
sdk/security/keyvault/internal/challenge_policy.go
sdk/security/keyvault/internal/challenge_policy_test.go
sdk/security/keyvault/internal/doc.go
sdk/security/keyvault/internal/fake_challenge.go
sdk/security/keyvault/internal/fake_challenge_test.go
sdk/security/keyvault/internal/parse.go
sdk/security/keyvault/internal/parse_test.go

Part of https://github.com/Azure/azure-sdk-for-go/issues/23355
Adding FakeChallenge to Key Vault to allow fakes support

[keyvault] add fakes support to internal

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_http_trace.go
sdk/azcore/runtime/policy_http_trace_test.go

* Added `tracing.SpanOptions.Link` when starting a span with `runtime.StartSpan` to support Span Links.
* Added Span Attribute `error.type` to report an error when ending a span with `runtime.StartSpan`. This follows the guideline from https://opentelemetry.io/docs/specs/semconv/attributes-registry/error/ and was recommended in [this PR comment](https://github.com/Azure/azure-sdk-for-go/pull/23860#discussion_r1927981899).

[azcore/runtime] add error.type attribute and span links to runtime.StartSpan

---

sdk/azidentity/managed_identity_credential_test.go
sdk/azidentity/test-resources-post.ps1

Something recently changed in either the Azure CLI or DevOps such that `script` as used in our live ACI test no longer exits in a reasonable amount of time. Happily, we don't need this workaround anymore because the new test subscription allows opening a port to the internet.

Trigger live ACI test via HTTP

---

eng/tools/generator/template/typespec/CHANGELOG.md.tpl

Fixed wrong package path of typespec changelog template. related pr: https://github.com/Azure/azure-sdk-for-go/pull/24141

fix typespec changelog template

---

sdk/internal/CHANGELOG.md
sdk/internal/recording/recording.go
sdk/internal/recording/recording_test.go

`RecordingHTTPClient.Do` returns the proxy's 404, from which the (service) client produces a ResponseError containing the proxy's error message as raw JSON:
```
--- FAIL: TestPool (8.17s)
client_test.go:381: 
Error: Received unexpected error:
POST https://batch.local/pools/nope
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE UNAVAILABLE
--------------------------------------------------------------------------------
{
"Message": "Unable to find a record for the request POST https://batch.local/pools/nope?api-version
=2024-07-01.20.0\nUri doesn\u0027t match:\n    request \u003Chttps://batch.local/pools/nope?api-version=2024-07-01
.20.0\u003E\n    record  \u003Chttps://batch.local/pools?api-version=2024-07-01.20.0\u003E\ …
```

Improve presentation of test proxy recording mismatch errors

---

sdk/security/keyvault/azcertificates/CHANGELOG.md
sdk/security/keyvault/azcertificates/assets.json
sdk/security/keyvault/azcertificates/build.go
sdk/security/keyvault/azcertificates/client.go
sdk/security/keyvault/azcertificates/client_test.go
sdk/security/keyvault/azcertificates/models.go
sdk/security/keyvault/azcertificates/models_serde.go
sdk/security/keyvault/azcertificates/tsp-location.yaml

part of https://github.com/Azure/azure-sdk-for-go/issues/24022
Added `PreserveCertOrder` feature

[azcertificates] generate 7.6-preview.2 

---

sdk/azidentity/README.md

Removes mention of `UsernamePasswordCredential` and the env vars that support it. We want to shift the README to demonstrating best practices, as it's a starting point for many customers.

Remove deprecated flow content from README

---

eng/pipelines/templates/jobs/archetype-go-release.yml
sdk/template/aztemplate/CHANGELOG.md
sdk/template/aztemplate/version.go

Resolves #24055
@benbp the main issue I see with this PR is this useless dependency job that we're using to keep the environment approval gate in place. Given that go literally tags the repo _to release_ we can't exactly avoid a checkout.

Address 1ES Release Warning

---

sdk/containers/azcontainerregistry/CHANGELOG.md
sdk/containers/azcontainerregistry/cloud_config.go

Default Audience of ACR of all clouds to `https://containerregistry.azure.net` to narrow down the default scope of the audience.

chore: Default Audience of ACR of all clouds to https://containerregistry.azure.net

---

eng/scripts/automation_init.sh

Customer can not successfully install generator by referencing this doc: https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/code-generation.md. Since the automation_init.sh write some hard code to check if go'version is 1.23 and required an outputfile (It should not be required for customer scenario).
fix: https://teams.microsoft.com/l/message/19:104f00188bb64ef48d1b4d94ccb7a361@thread.skype/1741136820626?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1741136820626&teamName=Azure%20SDK&channelName=Language%20-%20Go&createdTime=1741136820626

refine automation script

---

eng/pipelines/templates/steps/build-test.yml
eng/pipelines/templates/variables/globals.yml
eng/scripts/MgmtTestLib.ps1
eng/scripts/run_tests.ps1

It appears the underlying issues in the redesign have not yet been fully fixed, causing discrepancies in code coverage numbers. Update test and code coverage tools used in CI.

Reinstate nocoverageredesign

---

sdk/internal/CHANGELOG.md
sdk/internal/temporal/resource.go
sdk/internal/temporal/resource_test.go

This adds a callback that indicates whether the underlying resource should be refreshed despite its not having expired. Part of #22837

Make temporal.Resource refreshing configurable

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/internal/constants.go
sdk/messaging/azservicebus/message.go
sdk/messaging/azservicebus/receiver_test.go

These annotations are considered internal to Service Bus, but they are settable and nil is a perfectly valid AMQP value, even for the expected type of string.
Fixes #24305

[azservicebus] Check that an annotation isn't nil before casting it to a string.

---

eng/emitter-package-lock.json
eng/emitter-package.json
eng/scripts/build.ps1
eng/tools/generator/cmd/v2/automation/automationCmd.go

1. Upgrade emitter version: autorest.go(4.0.0-preview.70 -> 4.0.0-preview.71),  typespec-go(0.4.0 -> 0.4.1)
2. Upgrade typespec@0.67
3. Do not report sdk breaking change in spec pr when pr is first beta or first GA

Upgrade emitter version

---

sdk/azcore/CHANGELOG.md
sdk/azcore/go.mod
sdk/azcore/go.sum
sdk/azcore/internal/exported/exported.go
sdk/azcore/runtime/policy_bearer_token.go
sdk/azcore/runtime/policy_bearer_token_test.go
sdk/azcore/testdata/perf/go.mod
sdk/azcore/testdata/perf/go.sum

Continuing on from #24268, this adds AccessToken.RefreshOn and updates BearerTokenPolicy to observe it when deciding whether to request a token. Part of #22837

BearerTokenPolicy observes issuer's suggested token refresh time

---

eng/pipelines/templates/stages/platform-matrix.json
eng/pipelines/templates/steps/build-test.yml
eng/pipelines/templates/variables/globals.yml
sdk/azidentity/managed-identity-matrix.json
sdk/security/keyvault/azadmin/platform-matrix.json
sdk/security/keyvault/azkeys/platform-matrix.json

Defining these in `globals.yml` and referencing them via matrix environment variable syntax allows us to have one single place to rev versions for testing.

Use commonly defined go N0, N-1 versions in test matrix configs

---

sdk/messaging/azwebpubsub/CHANGELOG.md
sdk/messaging/azwebpubsub/client_custom.go
sdk/messaging/azwebpubsub/client_test.go
sdk/messaging/azwebpubsub/go.mod
sdk/messaging/azwebpubsub/go.sum

To maintain consistency, we should standardize on using only the latest v5 version.
https://github.com/Azure/azure-sdk-for-go/blob/674ac20511182bcf01023ec918d2c7aa88be44d5/sdk/messaging/azwebpubsub/go.mod#L9-L10

Remove duplicate `golang-jwt/jwt` dependency in azwebpubsub

---

eng/scripts/Language-Settings.ps1

I noticed this:
The reason is because I renamed the function argument in `Get-AllPackageInfoFromRepo` in `go - pullrequest` from `$ServiceDirectory` to the more correct-to-usage `$filterString`.
That is incompatible with [this line](https://github.com/Azure/azure-sdk-for-go/blob/4dce954538e4e89f983a2bbc3c4af4a36d1fa594/eng/common/scripts/Package-Properties.ps1#L492) in `Package-Properties.ps1`. This PR accomodates that function signature requirement while I update the eng/common to just pass the $ServiceDirectory without naming the argument.
There is only a single place in the common implementation that we call this Language-Settings function, so this should be a straightforward eng/common update.

Ensure that service directory builds don't build overaggressively

---

sdk/internal/recording/server.go

The failure  [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4721712&view=logs&j=61e427a2-922a-5e90-f757-655b788f203e&t=c9ee2177-f099-57dc-a461-780ae6f4ee65&s=6884a131-87da-5381-61f3-d7acc3b91d76) ISNT that identity has a specific config, it's just that it expects the proxy to be on the port that it assigns, and it's NOT because PROXY_MANUAL_START was set.

If in CI, always allow `proxy` to start

---

sdk/internal/CHANGELOG.md
sdk/internal/version.go

We need to get the version from #24394 available so that `go - pullrequest` can stop crashing on every package that has `UsePipelineProxy` set to false.

Prepare changelog and version file for release of the internal package

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_http_trace.go
sdk/azcore/runtime/policy_http_trace_test.go
sdk/azcore/tracing/tracing.go
sdk/azcore/tracing/tracing_test.go

Cherry-pick tracing changes into v1.19.0-beta branch

[azcore] Cherry-pick tracing changes into v1.19.0-beta branch

---

sdk/containers/azcontainerregistry/CHANGELOG.md
sdk/containers/azcontainerregistry/test-resources-pre.ps1
sdk/containers/azcontainerregistry/utils_test.go

It appears making post-deploy scripts "self-contained" (https://github.com/Azure/azure-sdk-tools/pull/10099) made this pipeline's script ineffective in that its `az login` no longer applies during the test run (this module is unique in using the CLI during live test runs). The quick fix here is to move the login step to a pre-deployment script; deployment is too fast for this to cause problems. I kept the no-op post script because `PersistOidcToken: true`, which we need to log in to the CLI in either a pre- or post-script, makes a post-deploy script mandatory.
@benbp I imagine there's a better way to address this but finding one isn't urgent because only this module needs a logged-in CLI to run live tests

Fix azcontainerregistry live test authentication

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_global_endpoint_manager_policy.go
sdk/data/azcosmos/cosmos_global_endpoint_manager_test.go
sdk/data/azcosmos/version.go

This fixes #24351 by passing the Context associated with the request in to the GEM when calling `Update` _during_ the processing of a request. This ensures that any key/value pairs stored in that Context flow through the GEM requests as well, which ensures telemetry spans line up properly (among other things).
As discussed in the issue, I didn't flow the full context through. Specifically, the context provided when calling `Update` **excludes** the cancellation signal from the original request context. That means if the request is cancelled, the GEM update will **not** be cancelled and will complete fully.
The test I wrote failed as expected without this change. Initially, it fails because the expected context value is not present in the context when the GEM requests are made (the …

[Cosmos] Pass request context through on GEM requests

---

eng/scripts/apiview-helpers.ps1

I feel like we should be copying the package specific files into the directory highlighted in `$sdk.Name`. Thoughts @benbp ?
We're copying the source code, but the top level will only ever be `sdk` or `eng`, so I'm uncertain what we are _trying_ to copy.

Ensure that multi-service packages will copy without error

---

sdk/data/azcosmos/cosmos_container_query_engine.go
sdk/data/azcosmos/internal/mock_query_engine.go
sdk/data/azcosmos/unstable/queryengine/cosmos_query_engine.go

This PR has some small tidy-ups to the preview Query Engine API:
* I had introduced a `PipelineResult` type to combine "Items" and "Requests", but wasn't actually using it. This PR fixes that.
* I renamed `NextBatch` to `Run` to align with some changes happening in the query engine

[Cosmos] some tidy up to Cosmos query engine API

---

sdk/monitor/azquery/CHANGELOG.md
sdk/monitor/azquery/custom_client.go
sdk/monitor/azquery/metrics_client_test.go

closes https://github.com/Azure/azure-sdk-for-go/issues/24460
Allows customers to override the API version for metrics clients.

[azquery] allow API version override

---

.github/CODEOWNERS

- Also, adding in glecaros as the service owner, so he'll get tagged as issues get filed as well.

Adding in PratibhaShrivastav18, now that their orgs are setup.

---

eng/scripts/Language-Settings.ps1

I'm resolving a failure that looks like [this](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4796434&view=logs&jobId=76992fd1-2312-5fae-7c45-7baba86b87ae&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=d34cfe88-f3e1-5ca1-ec50-18a5cea1099a).
The issue is that during serialization of the `aztemplate.json` file to disk, we serialize _everything_ in the object. The issue isn't that the actual `PackageProps` details are infinitely looped, it's that the `VersionFile` is a pwsh `FileInfo` object with a TON of nested metadata. To me it almost feels like the FileInfo obj has a self-referential loop somewhere, and that's why we're just endlessly expanding into memory. This DID occur locally in my go integration tests for `Get-PrPkgProperties`. By changing this `VersionFile` to be a string, …

Fix dump of `aztemplate.json`

---

sdk/storage/azblob/CHANGELOG.md
sdk/storage/azblob/appendblob/client_test.go
sdk/storage/azblob/appendblob/models.go
sdk/storage/azblob/blob/client_test.go
sdk/storage/azblob/blob/constants.go
sdk/storage/azblob/blob/models.go
sdk/storage/azblob/blockblob/client_test.go
sdk/storage/azblob/blockblob/models.go
sdk/storage/azblob/pageblob/client_test.go
sdk/storage/azblob/pageblob/models.go
sdk/storage/azblob/sas/service.go
sdk/storage/azdatalake/sas/service.go

Apart from support for request intent for File->Blob Copy, this PR also contains changes about user delegation sas where newlines were added.

[Storage][Azblob] Add support for request intent for File->Blob Copy 

---

sdk/data/azcosmos/CHANGELOG.md

This just updates the Cosmos Changelog to mark 1.4.0 as released. After merging this, we'll make the actual release.

Cosmos changelog update for 1.4.0 release

---

eng/scripts/automation_init.sh
eng/tools/generator/cmd/v2/common/constants.go
eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/fileProcessor_test.go
eng/tools/generator/cmd/v2/common/generation.go
sdk/resourcemanager/quota/armquota/README.md

1. update NewClientFactory definition in readme by generated code. https://github.com/Azure/azure-sdk-for-go/pull/24088
2. remove temporary compiled generator, https://github.com/Azure/azure-sdk-for-go/issues/24315#issuecomment-2822641653

update ClientFactory params in readme

---

eng/emitter-package-lock.json
eng/emitter-package.json
eng/tools/generator/cmd/v2/common/cmdProcessor.go

1. upgrade typespec-go version to 0.4.9
2. resolve: https://github.com/Azure/azure-sdk-for-go/issues/24646

upgrade_emitter_version

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azure_cli_credential.go
sdk/azidentity/azure_developer_cli_credential.go

By default, `Cmd.Output()` blocks indefinitely when the subprocess fails to exit after its Context is canceled or exits without closing stdout/err. This PR sets `Cmd.WaitDelay` to impose a timeout in these cases. If the subprocess wrote to stdout before exiting, credentials swallow the timeout error and try to unmarshal a token from stdout.

Prevent CLI credentials waiting indefinitely for subprocess output

---

sdk/batch/azbatch/client_test.go

These fail because of a change in service behavior (#24713)

Skip azbatch certificates tests

---

sdk/data/azcosmos/CHANGELOG.md

This PR updates the Changelog in preparation for a 1.5.0-beta.0 release of the Azure Cosmos DB SDK for Go. The main functionality added here is initial support for an external query engine (i.e. the Cosmos Client Engine, under development).
I'm not planning to release this until Monday, after I've done a few more tests to make sure things work together, but I wanted to get this PR ready to merge. I'll merge it and make the release on Monday (assuming it's approved by then).

cosmos: changelog for 1.5.0-beta.0

---

eng/scripts/mgmt-auto-release.sh
eng/tools/generator/cmd/issue/issueCmd.go

This change aims to change the auto release script to daily auto generate the PRs of the issue that labeled `SDK released by service owner` , [like this issue](https://github.com/Azure/sdk-release-request/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22SDK%20released%20by%20service%20owner%22)

Update auto release script for issues labeled `SDK released by service owner`

---

sdk/azidentity/test-resources-post.ps1

azidentity's live managed identity test pipeline is failing because `az` made a breaking change to require an explicit audience when creating a federated identity. This PR addresses that by specifying the default audience used by the previous `az`.

Fix live managed identity test deployment

---

sdk/storage/azdatalake/CHANGELOG.md
sdk/storage/azdatalake/directory/client.go
sdk/storage/azdatalake/directory/client_test.go
sdk/storage/azdatalake/file/client.go
sdk/storage/azdatalake/file/client_test.go

[Storage][Azdatalake][BugFix] Fix panic on auth failure

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/exported/request.go
sdk/azcore/runtime/policy_retry_test.go

This ensures that the same instance is propagated across policies and that any values are retained across retries.

Populate Request.values on creation

---

sdk/storage/azfile/CHANGELOG.md
sdk/storage/azfile/assets.json
sdk/storage/azfile/file/client_test.go
sdk/storage/azfile/file/models.go

[Storage][Azfile] Fixed create File Api on passing permissionKey

---

sdk/storage/azqueue/CHANGELOG.md
sdk/storage/azqueue/internal/generated/autorest.md
sdk/storage/azqueue/internal/generated/zz_queue_client.go
sdk/storage/azqueue/internal/generated/zz_response_types.go
sdk/storage/azqueue/queue_client_test.go

 [Storage][azqueue] Deprecate existing QueueProperties.ApproximateMessagesCount and convert int32 to int64 

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_container_properties.go
sdk/data/azcosmos/cosmos_container_properties_test.go
sdk/data/azcosmos/emulator_cosmos_container_test.go
sdk/data/azcosmos/full_text_policy.go
sdk/data/azcosmos/indexing_policy.go
sdk/data/azcosmos/vector_embedding_policy.go

This PR adds support for setting vector embedding policies in the Cosmos SDK. The PR **does not** bring any support for **executing** vector queries yet, but it does allow for _creating_ containers with the appropriate configuration.
I'll be merging this in to the `1.5.0.beta` branch as well, since I'm hoping to use this along with the query engine integration to start bringing vector query support. However, it's not something that needs to be in preview, so I'm putting it in `main` for now.

cosmos: enable support for creating containers with vector and full-text policies

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_container_properties.go
sdk/data/azcosmos/cosmos_container_properties_test.go
sdk/data/azcosmos/emulator_cosmos_container_test.go
sdk/data/azcosmos/full_text_policy.go
sdk/data/azcosmos/indexing_policy.go
sdk/data/azcosmos/vector_embedding_policy.go

This PR is a simple cherry-pick of the changes in #24833 from `main` over to the release branch for the preview release that includes query engine support. That seemed like the smoothest way to get something into this branch quickly to unblock vector scenarios there. I expect we'll release a `1.5.0` and move the query engine preview over to `1.6.0-beta` soon, and I'll reconcile things like CHANGELOG when that happens. Until then, I'd like to be able to make a preview release to allow folks to actually try Vector search with the query engine.

cosmos: Cherry-Pick Vector/FT container policies to 1.5.0 branch

---

.devcontainer/init.sh
.github/copilot-instructions.md
.github/instructions/README.md
.github/instructions/go-code.instructions.md
.github/instructions/go-examples.instructions.md
.github/instructions/go-mod-standards.instructions.md
.github/instructions/go-tests.instructions.md
.github/instructions/tsp-location.instructions.md

This is a "demo" that I think we can just check in. The instructions.md files are split out, based on file type, which lets me give more specific instructions for different types of files, and keeps it more readable.
For instance, I have a specific instructions for go.mod files: https://github.com/Azure/azure-sdk-for-go/pull/24872/files#diff-d3692df77e0694faf2a712cde75a5a4117d8ede6ff4a84678cfccaf1529354ae, and one specifically for [examples](https://github.com/Azure/azure-sdk-for-go/pull/24872/files#diff-9610976b8147e9ff3c72954b763729b4ab8c357a0cb38fb5d883edcc3f1ebda6), vs tests vs just normal package code. Since we have a fairly solid naming convention we could easily add in more, and keep them small.
When you are working with a file that has a corresponding instruction sfile, Copilot …

Adding in some copilot instructions that are targeted at specific file names as well as a devcontainer update

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/managed_identity_client.go

Closes #24842 with a small tweak to IMDS retry configuration. Our retry policy doesn't allow setting retry options based on a response, so this PR allows another retry in any case and shortens the `MaxRetryDelay` so the total retry period is about 70 seconds.
Here's a sample of the change's effect. Delays for retries 1-3 are unchanged (jitter causes the variation) but now there's a 5th retry, which like the 4th is limited to 25s.
| Retry | Delay before | Delay after |
|-------|----------------|---------------|
| 1     | 2.11s          | 1.71s         |
| 2     | 5.69s          | 7.46s         |
| 3     | 12.37s         | 13.38s        |
| 4     | 31.80s         | 25.00s        |
| 5     | —              | 25.00s        |
| **Total** | **51.97s**     | **72.55s**      |

Allow an additional retry for IMDS managed identity requests

---

sdk/data/azcosmos/CHANGELOG.md
sdk/data/azcosmos/cosmos_container.go
sdk/data/azcosmos/cosmos_feed_range.go
sdk/data/azcosmos/cosmos_feed_range_test.go
sdk/data/azcosmos/emulator_cosmos_container_test.go

Add a method to the Go SDK as a Cosmos container operation to retrieve the `MinInclusive` and `MaxExclusive` values from a pkrange and store them in a `FeedRange` struct.
FeedRanges allow the SDK to encapsulate the complexity of partition management, making client code simpler and more robust to backend changes. With this, we can parallelize change feed processing based on logical key ranges, independent of the number or identity of physical partitions.
- This PR builds on:
- https://github.com/Azure/azure-sdk-for-go/pull/24835
- **Please review after** the above PRs are merged, as this change set is rebased on top of them.
- Changes in this PR start from commit: [0e9704e](https://github.com/Azure/azure-sdk-for-go/pull/24889/commits/0e9704ec97bc74086f61eabea0fc23317ce935ca) (first unique …

cosmos: enable support for obtaining feed ranges from a pkrange in a container

---

sdk/monitor/ingestion/azlogs/build.go
sdk/monitor/ingestion/azlogs/testdata/_metadata.json
sdk/monitor/ingestion/azlogs/tsp-location.yaml
sdk/monitor/query/azmetrics/build.go
sdk/monitor/query/azmetrics/client.go
sdk/monitor/query/azmetrics/fake/server.go
sdk/monitor/query/azmetrics/models_serde.go
sdk/monitor/query/azmetrics/testdata/_metadata.json
sdk/monitor/query/azmetrics/time_rfc3339.go
sdk/monitor/query/azmetrics/tsp-location.yaml

* Updating location of the typespec files
* Updating to new emitter, `build.go` file no longer necessary. Run `tsp-client` update instead.

[monitor] update tsp-location and emitter

---

sdk/messaging/azservicebus/CHANGELOG.md
sdk/messaging/azservicebus/example_receiver_test.go
sdk/messaging/azservicebus/internal/constants.go
sdk/messaging/azservicebus/messageSettler.go
sdk/messaging/azservicebus/receiver2_test.go
sdk/messaging/azservicebus/receiver_test.go

There is a useful pattern (cross-receiver settlement) where you serialize ONLY the lock token (16 bytes of data) for a message, and then keep the message alive and eventually complete it on a different machine/process than you got it. 
This PR enables this for non-SB-session usage (sessions would require service support). 
Prior art here: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample16_CrossReceiverMessageSettlement.md
Fixes #24952

[azservicebus] Make it possible to settle and renew a message using a lock token

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/policy_bearer_token.go
sdk/azcore/runtime/policy_bearer_token_test.go

They normally are in the one case I'm modifying here, but only because all `azidentity` errors are `NonRetriable`. Custom credential implementations may return non-NonRetriable errors and thereby cause RetryPolicy to send doomed retries.

BearerTokenPolicy ensures authN errors are NonRetriable

---

eng/tools/generator/CHANGELOG.md
eng/tools/generator/README.md
eng/tools/generator/cmd/v2/common/fileProcessor.go
eng/tools/generator/cmd/v2/common/generation.go
eng/tools/generator/cmd/v2/refresh/refreshCmd.go
eng/tools/generator/cmd/v2/release/releaseCmd.go
eng/tools/generator/typespec/tspconfig.go
eng/tools/generator/typespec/tspconfig_test.go

This PR update generator tool to adopt the new emitter config changes.
1. Remove `version-number` config for `release` and `refresh` command because we have no scenario to hard code the module version. Accordingly, remove the `SpecificVersion` in `GenerateParam`.
2. Support `module` setting with major version suffix to extract the module path.

Support module config with major version suffix

---

.github/CODEOWNERS

The Monitor Query Logs library is now owned by the service team. Add a CODEOWNERS entry with their GitHub team.

Update CODEOWNERS for Monitor Query Logs

---

sdk/azcore/core_test.go

Closes #20516
Adding test to verify that our client's default transport automatically works when interacting with a server that uses IPv6.

IPv6 Client Test

---

sdk/azcore/CHANGELOG.md
sdk/azcore/internal/shared/constants.go
sdk/azcore/runtime/policy_api_version.go
sdk/azcore/runtime/policy_api_version_test.go

For an API version in a path segment, it is assumed that the client has replaced the applicable path segment with the API version. In this case, the pipeline policy is a no-op.
Example generated client constructor.
```go
func NewVersionedClientWithNoCredential(endpoint string, options *VersionedClientOptions) (*VersionedClient, error) {
if options == nil {
options = &VersionedClientOptions{}
}
cl, err := azcore.NewClient(moduleName, moduleVersion, runtime.PipelineOptions{
APIVersion: runtime.APIVersionOptions{
Location: runtime.APIVersionLocationPath,
},
}, &options.ClientOptions)
if err != nil {
return nil, err
}
apiVersion := "2022-12-01-preview"
if options.APIVersion != "" {
apiVersion = options.APIVersion
}
client := &VersionedClient{
endpoint:   endpoint,
internal:   cl,
apiVersion: …
```

Update API version policy to handle path params

---

sdk/azidentity/TROUBLESHOOTING.md

Pod Identity is being retired at the end of Sept. 2025, since Workload ID replaced it. Remove supporting content from the troubleshooting guide.

Remove pod identity content from TSG

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/azidentity_test.go
sdk/azidentity/azure_cli_credential.go
sdk/azidentity/azure_cli_credential_test.go
sdk/azidentity/azure_developer_cli_credential.go
sdk/azidentity/azure_developer_cli_credential_test.go
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/developer_credential_util.go

...by returning errors explaining what must be done before they can acquire a token. For AzureCLICredential this means GetToken always returns an error when given claims because the user must run `az login`. AzureDeveloperCLICredential runs `azd` with the given claims and returns an error only when `azd` doesn't return a token. Most of this PR is from refactoring these credentials to share code for executing commands in a shell (doing so made the feature easier to implement and test).

CLI credentials handle claims

---

sdk/azcore/CHANGELOG.md
sdk/azcore/runtime/poller.go

This is a back-stop to handle legacy services that misbehave.

Return ResponseError for LROs with an unsuccessful initial response

---

sdk/security/keyvault/azadmin/backup/build.go
sdk/security/keyvault/azadmin/rbac/build.go
sdk/security/keyvault/azcertificates/build.go
sdk/security/keyvault/azkeys/build.go
sdk/security/keyvault/azsecrets/build.go

Using `gofmt` over `goimports`
`goimports` requires extra installation, causing failures when running in pipelines

[keyvault] Switch to gofmt

---

sdk/storage/azfile/assets.json
sdk/storage/azfile/share/client_test.go
sdk/storage/azfile/share/models.go

[Storage][Files] Making SMB Directory leases configurable on a share level 

---

eng/tools/generator/CHANGELOG.md
eng/tools/generator/changelog/changelog_filter.go
eng/tools/generator/changelog/changelog_filter_test.go
eng/tools/generator/changelog/testdata/new/operation/funcfilter.go
eng/tools/generator/changelog/testdata/old/operation/funcfilter.go

resolve automation failure for this PR: https://github.com/Azure/azure-rest-api-specs/pull/37303
pipeline: https://dev.azure.com/azure-sdk/public/_build/results?buildId=5330747&view=logs&j=406f67d9-8952-5074-7a53-dcb346cb6a5f&t=ccc7497c-4498-591f-65a2-fc3e28e61219&l=364

Fix `FuncFilter` to be compatible with unchanged parameter signatures.

---

sdk/azidentity/CHANGELOG.md
sdk/azidentity/default_azure_credential.go
sdk/azidentity/default_azure_credential_test.go
sdk/azidentity/version.go

Closes #25265. Targeting a release branch based on [sdk/azidentity/v1.12.0](https://github.com/Azure/azure-sdk-for-go/tree/sdk/azidentity/v1.12.0) to keep #25057 in beta

DefaultAzureCredential: disable IMDS probe when ManagedIdentityCredential selected

---

sdk/azidentity/README.md

Removes the Azure AD reference from the Identity library's README, per the recommendation at https://learn.microsoft.com/entra/fundamentals/how-to-rename-azure-ad#communicate-the-change-to-your-customers to keep the old name reference for only 1 year.

Remove Azure AD reference from Identity README

---

sdk/azidentity/internal/customtokenproxy/transport.go
sdk/azidentity/internal/customtokenproxy/transport_test.go
sdk/azidentity/workload_identity_test.go

A Policy implementation made sense when this feature was first designed because at that time only token requests were sent to the proxy; other requests were to proceed via the Pipeline's configured Transporter. However, the design now has all requests going to the proxy so it's more logical and (a tiny bit) simpler to implement the feature as a Transporter.

Simplify WIC identity binding mode implementation
