Azure/azure-sdk-for-go

profiles/latest/maps/mgmt/maps/models.go, profiles/preview/maps/mgmt/maps/models.go, services/maps/mgmt/2018-05-01/maps/models.go
Created to accumulate context: maps/resource-manager
=> [AutoPR] maps/resource-manager

services/preview/storage/mgmt/2015-05-01-preview/storage/models.go, services/preview/storage/mgmt/2018-03-01-preview/storage/models.go, services/storage/mgmt/2015-06-15/storage/models.go, services/storage/mgmt/2016-01-01/storage/models.go, services/storage/mgmt/2016-05-01/storage/models.go, services/storage/mgmt/2016-12-01/storage/models.go, services/storage/mgmt/2017-06-01/storage/models.go, services/storage/mgmt/2017-10-01/storage/models.go, services/storage/mgmt/2018-02-01/storage/models.go, services/storage/mgmt/2018-07-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4938
=> [AutoPR storage/resource-manager] [Storage] Fix the UseSubDomainName

services/network/mgmt/2016-03-30/network/networkapi/interfaces.go, services/network/mgmt/2016-03-30/network/virtualnetworkgatewayconnections.go, services/network/mgmt/2016-06-01/network/networkapi/interfaces.go, services/network/mgmt/2016-06-01/network/virtualnetworkgatewayconnections.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4940
=> [AutoPR network/resource-manager] Fix errors in old Network API version

services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontendendpoints.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4991
=> [AutoPR frontdoor/resource-manager] fixing invalid paths in frontdoor

services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go, services/containerservice/mgmt/2018-03-31/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/managedclusters.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/managedclusters.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4948
=> [AutoPR containerservices/resource-manager] [AKS]: Remove 200/OK response from reset SP/AAD api

services/containerservice/mgmt/2018-03-31/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4980
=> [AutoPR containerservices/resource-manager] [AKS] fix schema and example validation warnings

services/network/mgmt/2015-06-15/network/networkapi/interfaces.go, services/network/mgmt/2015-06-15/network/virtualnetworkgatewayconnections.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5002
=> [AutoPR network/resource-manager] Fix duplicate path in old Network API version

profiles/preview/preview/apimanagement/mgmt/apimanagement/models.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5000
=> [AutoPR apimanagement/resource-manager] OpenAPIv3 support documented

services/eventgrid/mgmt/2019-01-01/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5006
=> [AutoPR eventgrid/resource-manager] Add tag: package-2019-01 to ruby and go readme files

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, profiles/preview/preview/datafactory/mgmt/datafactory/models.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5031
=> [AutoPR datafactory/resource-manager] [Azure Data Factory] Add winauth support in SSIS Activity

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, profiles/preview/preview/datafactory/mgmt/datafactory/models.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5019
=> [AutoPR datafactory/resource-manager] [DataFactory]Support schema property for dataset

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, profiles/preview/preview/datafactory/mgmt/datafactory/models.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4986
=> [AutoPR datafactory/resource-manager] For preview api: Change type of Ssis actitvity to support expression

profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanainstances.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanaonazureapi/interfaces.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5039
=> [AutoPR hanaonazure/resource-manager] [Hub Generated] Review request for Microsoft.HanaOnAzure to add version 2017-11-03-preview

services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5051
=> [AutoPR blueprint/resource-manager] typo: blueprint/resource-manager/Microsoft.Blueprint

profiles/latest/containerregistry/mgmt/containerregistry/models.go, profiles/preview/containerregistry/mgmt/containerregistry/models.go, services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5047
=> [AutoPR containerregistry/resource-manager] Update swagger to add target and credentials flag to the requests, and add examples.

services/web/mgmt/2018-02-01/web/apps.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5048
=> [AutoPR web/resource-manager] Merge changes from release microsoft.web ant79

profiles/latest/recoveryservices/mgmt/backup/models.go, profiles/preview/recoveryservices/mgmt/backup/models.go, services/recoveryservices/mgmt/2016-12-01/backup/backupapi/interfaces.go, services/recoveryservices/mgmt/2016-12-01/backup/models.go, services/recoveryservices/mgmt/2016-12-01/backup/protectablecontainers.go, services/recoveryservices/mgmt/2016-12-01/backup/resourcestorageconfigs.go, services/recoveryservices/mgmt/2017-07-01/backup/backupapi/interfaces.go, services/recoveryservices/mgmt/2017-07-01/backup/jobdetails.go, services/recoveryservices/mgmt/2017-07-01/backup/models.go, services/recoveryservices/mgmt/2017-07-01/backup/protectablecontainers.go, services/recoveryservices/mgmt/2017-07-01/backup/resourcestorageconfigs.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4976
=> [AutoPR recoveryservicesbackup/resource-manager] Generating latest spec

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5010
=> [AutoPR datafactory/resource-manager] [Datafactory] Add Azure Function to Swagger

services/servicebus/mgmt/2015-08-01/servicebus/models.go, services/servicebus/mgmt/2015-08-01/servicebus/namespaces.go, services/servicebus/mgmt/2015-08-01/servicebus/queues.go, services/servicebus/mgmt/2015-08-01/servicebus/topics.go, services/servicebus/mgmt/2017-04-01/servicebus/disasterrecoveryconfigs.go, services/servicebus/mgmt/2017-04-01/servicebus/migrationconfigs.go, services/servicebus/mgmt/2017-04-01/servicebus/models.go, services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go, services/servicebus/mgmt/2017-04-01/servicebus/queues.go, services/servicebus/mgmt/2017-04-01/servicebus/topics.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4765
=> [AutoPR servicebus/resource-manager] typo: servicebus/resource-manager/Microsoft.ServiceBus

services/preview/security/mgmt/2017-08-01-preview/security/workspacesettings.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5071
=> [AutoPR security/resource-manager] Add description to empty result in Workspace Settings Get

services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5073
=> [AutoPR hdinsight/resource-manager] [HDInsight] - Support MSI for ADLS gen2

services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5035
=> [AutoPR cognitiveservices/resource-manager] Adding customSubDomainName property.

services/cognitiveservices/v1.0/face/models.go, services/cognitiveservices/v1.0/face/snapshot.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5094
=> [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Refine the documentation for Face API's new Snapshot features. 

services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5062
=> [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web/stable/2018-02-01/WebApps.json

services/containerservice/mgmt/2018-03-31/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5101
=> [AutoPR containerservice/resource-manager] [AKS] add apiServerAuthorizedIPRanges property

services/containerservice/mgmt/2018-03-31/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Created to accumulate context: containerservice/resource-manager
=> [AutoPR] containerservice/resource-manager

services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5107
=> [AutoPR hanaonazure/resource-manager] Add new field 'proximityPlacementGroup' to properties of HanaInstance

services/cognitiveservices/v2.0/luis/runtime/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5100
=> [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Add dispatch child to LUIS Runtime response

services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5114
=> [AutoPR sql/resource-manager] Update managedInstances.json

profiles/latest/eventgrid/eventgrid/models.go, profiles/preview/eventgrid/eventgrid/models.go, services/eventgrid/2018-01-01/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5109
=> [AutoPR eventgrid/data-plane] Add Helm Events to ACR Schema for Event Grid

services/eventhub/mgmt/2017-04-01/eventhub/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5105
=> [AutoPR eventhub/resource-manager] Eventhub: Added skipEmptyArchives to Eventhub CaptureDescription

services/recoveryservices/mgmt/2016-12-01/backup/models.go, services/recoveryservices/mgmt/2017-07-01/backup/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5133
=> [AutoPR recoveryservicesbackup/resource-manager] Fixing a minor bug in Recovery Services (Backup) 

profiles/preview/preview/security/mgmt/security/models.go, services/preview/security/mgmt/2017-08-01-preview/security/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4902
=> [AutoPR security/resource-manager] Adding new api-version to Microsoft.Security Alerts resource

profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/alertrules.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/securityinsightapi/interfaces.go
Created to accumulate context: securityinsights/resource-manager
=> [AutoPR] securityinsights/resource-manager

services/compute/mgmt/2018-10-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4866
=> [AutoPR compute/resource-manager] Update compute.json to add ProtectFromScaleIn property to VMScaleSetVM properties

services/containerservice/mgmt/2018-03-31/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5150
=> [AutoPR containerservice/resource-manager] Revert "[AKS] add apiServerAuthorizedIPRanges property"

profiles/latest/kusto/mgmt/kusto/models.go, profiles/preview/kusto/mgmt/kusto/models.go, services/kusto/mgmt/2019-01-21/kusto/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5162
=> [AutoPR azure-kusto/resource-manager] Ga kc 1

services/containerservice/mgmt/2018-03-31/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5120
=> [AutoPR containerservice/resource-manager] [AKS] add availabilityZones to agent pool profile

profiles/latest/kusto/mgmt/kusto/models.go, profiles/preview/kusto/mgmt/kusto/models.go, services/kusto/mgmt/2019-01-21/kusto/models.go
Created to accumulate context: azure-kusto/resource-manager
=> [AutoPR] azure-kusto/resource-manager

services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5168
=> [AutoPR policyinsights/resource-manager] typo: aliase -> alias

services/keyvault/mgmt/2016-10-01/keyvault/models.go, services/keyvault/mgmt/2018-02-14/keyvault/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5172
=> [AutoPR keyvault/resource-manager] add description of access policies required condition

services/operationalinsights/mgmt/2015-03-20/operationalinsights/operationalinsightsapi/interfaces.go, services/operationalinsights/mgmt/2015-03-20/operationalinsights/workspaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5182
=> [AutoPR operationalinsights/resource-manager] Add gateways API

profiles/latest/cognitiveservices/computervision/models.go, profiles/preview/cognitiveservices/computervision/models.go, services/cognitiveservices/v2.0/computervision/client.go, services/cognitiveservices/v2.0/computervision/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5141
=> [AutoPR cognitiveservices/data-plane/ComputerVision] Analyze brands

services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/productsettings.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5205
=> [AutoPR securityinsights/resource-manager] typo: securityinsights/resource-manager/Microsoft.SecurityInsights

services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5220
=> [AutoPR blueprint/resource-manager] [Hub Generated] Review request for Microsoft.Blueprint to add version 2018-11-01-preview

services/cognitiveservices/v2.0/luis/authoring/model.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5216
=> [AutoPR cognitiveservices/data-plane/LUIS/Authoring] [Cogsvcs] LUIS - add text to simple entity description

services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5196
=> [AutoPR hanaonazure/resource-manager] Add hwRevision field to HanaInstance definition

services/cognitiveservices/v2.0/luis/authoring/model.go
Created to accumulate context: cognitiveservices/data-plane/LUIS/Authoring
=> [AutoPR] cognitiveservices/data-plane/LUIS/Authoring

profiles/latest/web/mgmt/web/models.go, profiles/preview/web/mgmt/web/models.go, services/web/mgmt/2018-02-01/web/client.go, services/web/mgmt/2018-02-01/web/models.go, services/web/mgmt/2018-02-01/web/recommendations.go, services/web/mgmt/2018-02-01/web/webapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5228
=> [AutoPR web/resource-manager] [App Service] Update swagger spec for ANT80 (#5111)

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/datafactoryapi/interfaces.go, services/datafactory/mgmt/2018-06-01/datafactory/pipelines.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5239
=> [AutoPR datafactory/resource-manager] [Datafactory] Support create pipeline run with recovery mode

profiles/latest/cognitiveservices/textanalytics/models.go, profiles/preview/cognitiveservices/textanalytics/models.go, services/cognitiveservices/v2.1/textanalytics/client.go, services/cognitiveservices/v2.1/textanalytics/models.go, services/cognitiveservices/v2.1/textanalytics/textanalyticsapi/interfaces.go, services/cognitiveservices/v2.1/textanalytics/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5187
=> [AutoPR cognitiveservices/data-plane/TextAnalytics] Users/laramume/addv2.1 swagger

services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5224
=> [AutoPR sql/resource-manager] Update swagger file and examples with time zone parameter [DO NOT MERGE]

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/datafactoryapi/interfaces.go, services/datafactory/mgmt/2018-06-01/datafactory/pipelines.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5254
=> [AutoPR datafactory/resource-manager] [Datafactory] Fixing the API version in entity files

profiles/preview/preview/blueprint/mgmt/blueprint/models.go, services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5272
=> [AutoPR blueprint/resource-manager] Update lock modes

services/web/mgmt/2016-09-01/web/appserviceplans.go, services/web/mgmt/2018-02-01/web/appserviceplans.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4351
=> [AutoPR web/resource-manager] Add 201 response to AppServicePlans_CreateOrUpdate

services/search/mgmt/2015-08-19/search/searchapi/interfaces.go, services/search/mgmt/2015-08-19/search/services.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5123
=> [AutoPR search/resource-manager] [WaitForARMFeedback] Add api get_services_by_subscription of Azure Search

profiles/preview/preview/blueprint/mgmt/blueprint/models.go, services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5263
=> [AutoPR blueprint/resource-manager] Updating Blueprint spec to include resource group tags

profiles/latest/containerservice/mgmt/containerservice/models.go, profiles/preview/containerservice/mgmt/containerservice/models.go, services/containerservice/mgmt/2019-02-01/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5286
=> [AutoPR containerservice/resource-manager] including apiServerAuthorizedIPRanges

services/iothub/mgmt/2018-04-01/devices/models.go, services/preview/iothub/mgmt/2018-12-01-preview/devices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5290
=> [AutoPR iothub/resource-manager] changes to improve documentation of endpoint health statuses for routing

services/iothub/mgmt/2018-04-01/devices/models.go, services/preview/iothub/mgmt/2018-12-01-preview/devices/models.go
Created to accumulate context: iothub/resource-manager
=> [AutoPR] iothub/resource-manager

services/preview/monitor/mgmt/2018-03-01/insights/actiongroups.go, services/preview/monitor/mgmt/2018-03-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5292
=> [AutoPR monitor/resource-manager] new application insignts api version for unified schema in action

profiles/latest/eventgrid/eventgrid/models.go, profiles/preview/eventgrid/eventgrid/models.go, services/eventgrid/2018-01-01/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5309
=> [AutoPR eventgrid/data-plane] Added Azure App Configuration event data schema.

services/preview/netapp/mgmt/2017-08-15/netapp/accounts.go, services/preview/netapp/mgmt/2017-08-15/netapp/mounttargets.go, services/preview/netapp/mgmt/2017-08-15/netapp/netappapi/interfaces.go, services/preview/netapp/mgmt/2017-08-15/netapp/pools.go, services/preview/netapp/mgmt/2017-08-15/netapp/snapshots.go, services/preview/netapp/mgmt/2017-08-15/netapp/volumes.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5256
=> [AutoPR netapp/resource-manager] Bringing consistency between to "ResourceGroup" definition

services/containerservice/mgmt/2019-02-01/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5310
=> [AutoPR containerservice/resource-manager] mark the new features as PREVIEW in description 

services/containerservice/mgmt/2018-03-31/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5324
=> [AutoPR containerservice/resource-manager] Add regex validation for ManagedClusterAgentPoolProfile.name

profiles/latest/network/mgmt/network/models.go, profiles/preview/network/mgmt/network/models.go, services/network/mgmt/2018-12-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5317
=> [AutoPR network/resource-manager] Add support for Local Sku

services/preview/netapp/mgmt/2017-08-15/netapp/accounts.go, services/preview/netapp/mgmt/2017-08-15/netapp/mounttargets.go, services/preview/netapp/mgmt/2017-08-15/netapp/netappapi/interfaces.go, services/preview/netapp/mgmt/2017-08-15/netapp/pools.go, services/preview/netapp/mgmt/2017-08-15/netapp/snapshots.go, services/preview/netapp/mgmt/2017-08-15/netapp/volumes.go
Created to accumulate context: netapp/resource-manager
=> [AutoPR] netapp/resource-manager

services/datalake/analytics/2016-11-01-preview/catalog/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5329
=> [AutoPR datalake-analytics/data-plane] [ADLA] - Catalog - Add stream path to USqlTableFragment

services/batch/2018-12-01.8.0/batch/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5305
=> [AutoPR batch/data-plane] Update some descriptions.

services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5360
=> [AutoPR eventhub/resource-manager] EventHub : corrected typo 

services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/serversecurityalertpolicies.go, services/preview/sql/mgmt/2017-03-01-preview/sql/sqlapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5070
=> [AutoPR sql/resource-manager] Added List Policies API to SecurityAlerts

services/edgegateway/mgmt/2019-03-01/edgegateway/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5376
=> [AutoPR edgegateway/resource-manager] typo: upto -> up to

services/graphrbac/1.6/graphrbac/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5375
=> [AutoPR graphrbac/data-plane] typo: graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6

services/preview/security/mgmt/v1.0/security/models.go, services/preview/security/mgmt/v2.0/security/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5354
=> [AutoPR security/resource-manager] Correlation Key property added

profiles/latest/mediaservices/mgmt/media/models.go, profiles/preview/mediaservices/mgmt/media/models.go, services/mediaservices/mgmt/2018-07-01/media/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5340
=> [AutoPR mediaservices/resource-manager] Add filter to StreamingLocator and Streaming presets.

services/iothub/mgmt/2018-04-01/devices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5388
=> [AutoPR iothub/resource-manager] making the health status description shorter

profiles/latest/search/mgmt/search/models.go, profiles/preview/search/mgmt/search/models.go, services/search/mgmt/2015-08-19/search/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5386
=> [AutoPR search/resource-manager] Add L-Series SKU values to management plane

profiles/preview/preview/iothub/mgmt/devices/models.go, services/iothub/mgmt/2018-04-01/devices/models.go, services/preview/iothub/mgmt/2018-12-01-preview/devices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5405
=> [AutoPR iothub/resource-manager] [Hub Generated] Review request for Microsoft.Devices to change version 2018-12-01-preview

README.md
=> Updated README.md to correct logging values

services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/marketplaceagreements.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5412
=> [AutoPR marketplaceordering/resource-manager] [Hub Generated] Review request for Microsoft.MarketplaceOrdering to add version 2015-06-01

profiles/preview/preview/netapp/mgmt/netapp/models.go, services/preview/netapp/mgmt/2017-08-15/netapp/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5370
=> [AutoPR netapp/resource-manager] Update to Release 3.5 standard (pre GA)

services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5321
=> [AutoPR sql/resource-manager] typo: Winodws -> Windows

services/consumption/mgmt/2019-01-01/consumption/budgets.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5429
=> [AutoPR consumption/resource-manager] [Hub Generated] Review request for Microsoft.Consumption to add version 2018-11-01-preview

services/containerregistry/mgmt/2017-10-01/containerregistry/models.go, services/containerregistry/mgmt/2018-09-01/containerregistry/models.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5390
=> [AutoPR containerregistry/resource-manager] [ACR] Update Webhook Event Target Schema to Add Name and Version

profiles/latest/mediaservices/mgmt/media/models.go, profiles/preview/mediaservices/mgmt/media/models.go, services/mediaservices/mgmt/2018-07-01/media/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5413
=> [AutoPR mediaservices/resource-manager] Add preset enum ContentAwareEncodingExperimental

services/preview/managedservices/mgmt/2018-06-01/managedservices/managedservicesapi/interfaces.go, services/preview/managedservices/mgmt/2018-06-01/managedservices/models.go, services/preview/managedservices/mgmt/2018-06-01/managedservices/registrationassignments.go, services/preview/managedservices/mgmt/2018-06-01/managedservices/registrationdefinitions.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5452
=> [AutoPR managedservices/resource-manager] Fixed typos

services/storage/mgmt/2018-11-01/storage/accounts.go, services/storage/mgmt/2018-11-01/storage/storageapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5453
=> [AutoPR storage/resource-manager] Added feature revoke user delegation key

services/preview/managedservices/mgmt/2018-06-01/managedservices/managedservicesapi/interfaces.go, services/preview/managedservices/mgmt/2018-06-01/managedservices/registrationassignments.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5457
=> [AutoPR managedservices/resource-manager] typo: registraton -> registration

services/graphrbac/1.6/graphrbac/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5456
=> [AutoPR graphrbac/data-plane] typo: informations -> information about

services/preview/managedservices/mgmt/2018-06-01/managedservices/managedservicesapi/interfaces.go, services/preview/managedservices/mgmt/2018-06-01/managedservices/registrationassignments.go
Created to accumulate context: managedservices/resource-manager
=> [AutoPR] managedservices/resource-manager

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, profiles/preview/preview/datafactory/mgmt/datafactory/models.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5278
=> [AutoPR datafactory/resource-manager] Remove enum from catalogPricingTier

services/cognitiveservices/v3.0/translatortext/translator.go
Created to accumulate context: cognitiveservices/data-plane/TranslatorText
=> [AutoPR] cognitiveservices/data-plane/TranslatorText

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5468
=> [AutoPR datafactory/resource-manager] [Datafactory] Webhook activity

services/preview/billing/mgmt/2018-11-01-preview/billing/billingapi/interfaces.go, services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesections.go, services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesectionsbybillingaccountname.go, services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesectionswithcreatesubscriptionpermission.go, services/preview/billing/mgmt/2018-11-01-preview/billing/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5486
=> [AutoPR billing/resource-manager] [Hub Generated] Review request for Microsoft.Billing to add version 2018-11-01-preview

profiles/preview/preview/blueprint/mgmt/blueprint/models.go, services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/artifacts.go, services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/assignmentoperations.go, services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/assignments.go, services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprintapi/interfaces.go, services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprints.go, services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go, services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/publishedartifacts.go, services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/publishedblueprints.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5470
=> [AutoPR blueprint/resource-manager] Blueprints API update for excludedPrincipals and whoIsBlueprint

Gopkg.lock, services/network/mgmt/2018-12-01/network/models.go, services/preview/frontdoor/mgmt/2019-04-01/frontdoor/models.go, services/preview/frontdoor/mgmt/2019-04-01/frontdoor/policies.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5483
=> [AutoPR network/resource-manager/frontdoor/resource-manager] typo: frontdoor/resource-manager/Microsoft.Network

services/cognitiveservices/v1.0/face/largefacelist.go, services/cognitiveservices/v1.0/face/largepersongroup.go, services/cognitiveservices/v1.0/face/persongroup.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5482
=> [AutoPR cognitiveservices/data-plane/Face] typo: cognitiveservices/data-plane/Face/stable/v1

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5473
=> [AutoPR datafactory/resource-manager] [DataFactory] validation activity

services/appinsights/mgmt/2015-05-01/insights/analyticsitems.go, services/appinsights/mgmt/2015-05-01/insights/annotations.go, services/appinsights/mgmt/2015-05-01/insights/apikeys.go, services/appinsights/mgmt/2015-05-01/insights/componentavailablefeatures.go, services/appinsights/mgmt/2015-05-01/insights/componentcurrentbillingfeatures.go, services/appinsights/mgmt/2015-05-01/insights/componentfeaturecapabilities.go, services/appinsights/mgmt/2015-05-01/insights/componentquotastatus.go, services/appinsights/mgmt/2015-05-01/insights/components.go, services/appinsights/mgmt/2015-05-01/insights/exportconfigurations.go, services/appinsights/mgmt/2015-05-01/insights/favorites.go, services/appinsights/mgmt/2015-05-01/insights/proactivedetectionconfigurations.go, services/appinsights/mgmt/2015-05-01/insights/webtestlocations.go, services/appinsights/mgmt/2015-05-01/insights/webtests.go, services/appinsights/mgmt/2015-05-01/insights/workbooks.go, services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5505
=> [AutoPR applicationinsights/resource-manager] [App Insights control plane] fix: validate subId, apiVersion, rgName

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/preview/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/preview/storage/mgmt/2018-03-01-preview/storage/blobcontainers.go, services/preview/storage/mgmt/2018-03-01-preview/storage/models.go, services/preview/storage/mgmt/2018-03-01-preview/storage/storageapi/interfaces.go, services/storage/mgmt/2018-02-01/storage/blobcontainers.go, services/storage/mgmt/2018-02-01/storage/models.go, services/storage/mgmt/2018-02-01/storage/storageapi/interfaces.go, services/storage/mgmt/2018-07-01/storage/blobcontainers.go, services/storage/mgmt/2018-07-01/storage/models.go, services/storage/mgmt/2018-07-01/storage/storageapi/interfaces.go, services/storage/mgmt/2018-11-01/storage/blobcontainers.go, services/storage/mgmt/2018-11-01/storage/models.go, services/storage/mgmt/2018-11-01/storage/storageapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5480
=> [AutoPR storage/resource-manager] [DO NOT REVIEW/MERGE] Swagger for Lease Container API from Oct17 to latest

services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5512
=> [AutoPR imagebuilder/resource-manager] [Hub Generated] Review request for Microsoft.VirtualMachineImages to add version preview/2019-02-01-preview

services/postgresql/mgmt/2017-12-01/postgresql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5511
=> [AutoPR postgresql/resource-manager] add missed parameters in Postgres Update Server API to stop replication

services/compute/mgmt/2018-10-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5515
=> [AutoPR compute/resource-manager] Update doNotRunExtensionsOnOverProvisioned Vms property description

profiles/latest/cdn/mgmt/cdn/models.go, profiles/preview/cdn/mgmt/cdn/models.go, services/cdn/mgmt/2017-10-12/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5533
=> [AutoPR cdn/resource-manager] add Premium_ChinaCdn support to cdn specification 2017-10-12

services/preview/monitor/mgmt/2018-03-01/insights/models.go, services/preview/monitor/mgmt/2018-09-01/insights/models.go, services/preview/monitor/mgmt/2018-11-01-preview/insights/models.go, services/preview/monitor/mgmt/2019-03-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5462
=> [AutoPR monitor/resource-manager] #5326 Fix the criteria definition

profiles/latest/web/mgmt/web/models.go, profiles/preview/web/mgmt/web/models.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5536
=> [AutoPR web/resource-manager] Update managedserviceidentity type enum

services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5542
=> [AutoPR web/resource-manager] Add Managed Identity envelope to SitePatchResource

services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/client.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5545
=> [AutoPR apimanagement/resource-manager] ApiManagement : Moved all definitions to a common file for automation

services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/models.go
Created to accumulate context: imagebuilder/resource-manager
=> [AutoPR] imagebuilder/resource-manager

profiles/latest/containerservice/mgmt/containerservice/models.go, profiles/preview/containerservice/mgmt/containerservice/models.go, services/containerservice/mgmt/2019-04-01/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5556
=> [AutoPR containerservice/resource-manager] adding load balancer sku property to network profile

profiles/latest/consumption/mgmt/consumption/models.go, profiles/preview/consumption/mgmt/consumption/models.go, services/consumption/mgmt/2019-01-01/consumption/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5599
=> [AutoPR consumption/resource-manager] [Hub Generated] Review request for Microsoft.Consumption to add version stable/2019-01-01

services/costmanagement/mgmt/2019-01-01/costmanagement/exports.go, services/costmanagement/mgmt/2019-01-01/costmanagement/query.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5612
=> [AutoPR cost-management/resource-manager] [Hub Generated] Review request for Microsoft.CostManagement to add version stable/2019-01-01

profiles/latest/compute/mgmt/compute/models.go, profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2019-03-01/compute/computeapi/interfaces.go, services/compute/mgmt/2019-03-01/compute/models.go, services/compute/mgmt/2019-03-01/compute/virtualmachinescalesets.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5640
=> [AutoPR compute/resource-manager] Fix operation id of API convertToSinglePlacementGroup

services/preview/frontdoor/mgmt/2019-04-01/frontdoor/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5624
=> [AutoPR frontdoor/resource-manager] typo: frontdoor/resource-manager/Microsoft.Network

services/preview/sql/mgmt/2017-03-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/sensitivitylabels.go, services/preview/sql/mgmt/2017-03-01-preview/sql/sqlapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5083
=> [AutoPR sql/resource-manager] [DO NOT MERGE] Sensitivity labels: Disable/Enable recommended sensitivity labels

services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5672
=> [AutoPR policyinsights/resource-manager] [Hub Generated] Review request for Microsoft.PolicyInsights to add version preview/2018-07-01-preview

services/preview/cognitiveservices/v1.0/anomalydetector/client.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5686
=> [AutoPR cognitiveservices/data-plane/AnomalyDetector] Fix Go SDK for cognitiveservices/anomalydetector

services/preview/cognitiveservices/v1.0/anomalydetector/client.go
Created to accumulate context: cognitiveservices/data-plane/AnomalyDetector
=> [AutoPR] cognitiveservices/data-plane/AnomalyDetector

services/batch/2018-12-01.8.0/batch/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5668
=> [AutoPR batch/data-plane/batch/resource-manager] Batch doc change: Update supported os family

services/batch/mgmt/2015-12-01/batch/models.go, services/batch/mgmt/2017-01-01/batch/models.go, services/batch/mgmt/2017-05-01/batch/models.go, services/batch/mgmt/2017-09-01/batch/models.go, services/batch/mgmt/2018-12-01/batch/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5720
=> [AutoPR batch/resource-manager] Dev batch microsoft.batch 2019 04 01- Fix swagger spec incorrect nullable property

services/batch/mgmt/2015-12-01/batch/models.go, services/batch/mgmt/2017-01-01/batch/models.go, services/batch/mgmt/2017-05-01/batch/models.go, services/batch/mgmt/2017-09-01/batch/models.go, services/batch/mgmt/2018-12-01/batch/models.go
Created to accumulate context: batch/resource-manager
=> [AutoPR] batch/resource-manager

services/batch/2018-12-01.8.0/batch/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5700
=> [AutoPR batch/data-plane/batch/resource-manager] [Don't merge] Improve Batch documentation

services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5655
=> [AutoPR web/resource-manager] VnetInfo CertBlob format changed to string

profiles/latest/cognitiveservices/luis/authoring/models.go, profiles/preview/cognitiveservices/luis/authoring/models.go, services/cognitiveservices/v2.0/luis/authoring/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5741
=> [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Add ErrorResponse to "AddIntent" post

profiles/latest/cognitiveservices/luis/authoring/models.go, profiles/preview/cognitiveservices/luis/authoring/models.go, services/cognitiveservices/v2.0/luis/authoring/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5747
=> [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Refactor enum list of /definitions/ReadableType

services/preview/netapp/mgmt/2017-08-15/netapp/accounts.go, services/preview/netapp/mgmt/2017-08-15/netapp/models.go, services/preview/netapp/mgmt/2017-08-15/netapp/pools.go, services/preview/netapp/mgmt/2017-08-15/netapp/snapshots.go, services/preview/netapp/mgmt/2017-08-15/netapp/volumes.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5683
=> [AutoPR netapp/resource-manager] Initial stable version

.gitattributes
=> chore: Add gitattributes for line endings

profiles/latest/apimanagement/mgmt/apimanagement/models.go, profiles/preview/apimanagement/mgmt/apimanagement/models.go, services/apimanagement/mgmt/2019-01-01/apimanagement/apimanagementapi/interfaces.go, services/apimanagement/mgmt/2019-01-01/apimanagement/apioperationpolicy.go, services/apimanagement/mgmt/2019-01-01/apimanagement/apipolicy.go, services/apimanagement/mgmt/2019-01-01/apimanagement/models.go, services/apimanagement/mgmt/2019-01-01/apimanagement/policy.go, services/apimanagement/mgmt/2019-01-01/apimanagement/productpolicy.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5732
=> [AutoPR apimanagement/resource-manager] [Hub Generated] Review request for Microsoft.ApiManagement to add version stable/2019-01-01

profiles/latest/compute/mgmt/compute/models.go, profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2019-03-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5740
=> [AutoPR compute/resource-manager] Add hyperVGeneration enum property to ImageProperties

services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5760
=> [AutoPR sql/resource-manager] Sqldb serverless

profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5769
=> [AutoPR hanaonazure/resource-manager] Updating the schema to adhere to the new design changes

profiles/latest/apimanagement/mgmt/apimanagement/models.go, profiles/preview/apimanagement/mgmt/apimanagement/models.go, services/apimanagement/mgmt/2019-01-01/apimanagement/apimanagementapi/interfaces.go, services/apimanagement/mgmt/2019-01-01/apimanagement/apioperationpolicy.go, services/apimanagement/mgmt/2019-01-01/apimanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5763
=> [AutoPR apimanagement/resource-manager] Revert not support formats xml-link and rawxml-link

services/datafactory/mgmt/2018-06-01/datafactory/datafactoryapi/interfaces.go, services/datafactory/mgmt/2018-06-01/datafactory/exposurecontrol.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5591
=> [AutoPR datafactory/resource-manager] [Datafactory] Adding getFeatureValue API in factory scope

profiles/2019-03-01/resources/mgmt/insights/models.go, profiles/preview/preview/monitor/mgmt/insights/models.go, services/preview/monitor/mgmt/2018-03-01/insights/models.go, services/preview/monitor/mgmt/2018-09-01/insights/models.go, services/preview/monitor/mgmt/2018-11-01-preview/insights/models.go, services/preview/monitor/mgmt/2019-03-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5677
=> [AutoPR monitor/resource-manager] Add dynamic metric alert api

profiles/latest/containerservice/mgmt/containerservice/models.go, profiles/preview/containerservice/mgmt/containerservice/models.go, services/containerservice/mgmt/2019-04-30/containerservice/agentpools.go, services/containerservice/mgmt/2019-04-30/containerservice/managedclusters.go, services/containerservice/mgmt/2019-04-30/containerservice/models.go, services/containerservice/mgmt/2019-04-30/containerservice/operations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5797
=> [AutoPR containerservice/resource-manager] Dev containerservice microsoft.container service 2019 04 01

services/resources/mgmt/2016-09-01/locks/locksapi/interfaces.go, services/resources/mgmt/2016-09-01/locks/managementlocks.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5757
=> [AutoPR resources/resource-manager] Add list_by_scope

services/containerservice/mgmt/2019-04-30/containerservice/containerservices.go, services/containerservice/mgmt/2019-04-30/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5819
=> [AutoPR containerservice/resource-manager] Update list-orchestrator for api spec 2019-04-01

services/storage/mgmt/2019-04-01/storage/blobcontainers.go, services/storage/mgmt/2019-04-01/storage/models.go, services/storage/mgmt/2019-04-01/storage/storageapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5562
=> [AutoPR storage/resource-manager] Support nextLink for list container request.

services/graphrbac/1.6/graphrbac/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5873
=> [AutoPR graphrbac/data-plane] graph: fix invalid types of accountEnabled

profiles/latest/kusto/mgmt/kusto/models.go, profiles/preview/kusto/mgmt/kusto/models.go, services/kusto/mgmt/2019-01-21/kusto/dataconnections.go, services/kusto/mgmt/2019-01-21/kusto/kustoapi/interfaces.go, services/kusto/mgmt/2019-01-21/kusto/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5648
=> [AutoPR azure-kusto/resource-manager] Added data connection check name availability operation

profiles/latest/cdn/mgmt/cdn/models.go, profiles/preview/cdn/mgmt/cdn/models.go, services/cdn/mgmt/2019-04-15/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5897
=> [AutoPR cdn/resource-manager] add premium_chinaCdn to CDN sku

services/appinsights/mgmt/2015-05-01/insights/insightsapi/interfaces.go, services/appinsights/mgmt/2015-05-01/insights/models.go, services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5870
=> [AutoPR applicationinsights/resource-manager] Update Application Insights Schema to support WorkItemConfig operations

services/web/mgmt/2018-02-01/web/deletedwebapps.go, services/web/mgmt/2018-02-01/web/models.go, services/web/mgmt/2018-02-01/web/webapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5905
=> [AutoPR web/resource-manager] Add location based deleted Web Apps

services/analysisservices/mgmt/2017-08-01/analysisservices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5930
=> [AutoPR analysisservices/resource-manager] Fix incorrect type of enablePowerBIService property

services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5927
=> [AutoPR web/resource-manager] Add Source Web App Location

services/preview/cognitiveservices/v1.0/formrecognizer/client.go, services/preview/cognitiveservices/v1.0/formrecognizer/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5957
=> [AutoPR cognitiveservices/data-plane/FormRecognizer] FormRecognizer - Minor update to help text.

services/preview/cognitiveservices/v1.0/formrecognizer/client.go, services/preview/cognitiveservices/v1.0/formrecognizer/version.go
Created to accumulate context: cognitiveservices/data-plane/FormRecognizer
=> [AutoPR] cognitiveservices/data-plane/FormRecognizer

profiles/latest/datalake/store/mgmt/account/models.go, profiles/preview/datalake/store/mgmt/account/models.go, services/datalake/store/mgmt/2016-11-01/account/accountapi/interfaces.go, services/datalake/store/mgmt/2016-11-01/account/locations.go, services/datalake/store/mgmt/2016-11-01/account/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5977
=> [AutoPR datalake-store/resource-manager] [ADLS] add Get Usages API

profiles/latest/datalake/store/mgmt/account/models.go, profiles/preview/datalake/store/mgmt/account/models.go, services/datalake/store/mgmt/2016-11-01/account/accountapi/interfaces.go, services/datalake/store/mgmt/2016-11-01/account/locations.go, services/datalake/store/mgmt/2016-11-01/account/models.go
Created to accumulate context: datalake-store/resource-manager
=> [AutoPR] datalake-store/resource-manager

profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5908
=> [AutoPR hanaonazure/resource-manager] Added new SKUs

profiles/latest/cognitiveservices/mgmt/cognitiveservices/models.go, profiles/preview/cognitiveservices/mgmt/cognitiveservices/models.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6009
=> [AutoPR cognitiveservices/resource-manager] Add NetworkRuleSet Support.

profiles/latest/mysql/mgmt/mysql/models.go, profiles/preview/mysql/mgmt/mysql/models.go, services/mysql/mgmt/2017-12-01/mysql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6007
=> [AutoPR mysql/resource-manager] MySQL intelligent performance APIs

services/preview/billing/mgmt/2018-11-01-preview/billing/billingapi/interfaces.go, services/preview/billing/mgmt/2018-11-01-preview/billing/paymentmethods.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6052
=> [AutoPR billing/resource-manager] Billing new Py path

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5752
=> [AutoPR datafactory/resource-manager] [Datafactory] add missing ssis entity types

services/containerservice/mgmt/2019-04-30/containerservice/agentpools.go, services/containerservice/mgmt/2019-04-30/containerservice/containerserviceapi/interfaces.go, services/containerservice/mgmt/2019-04-30/containerservice/managedclusters.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5949
=> [AutoPR containerservice/resource-manager] set hard limit on resourceName for AKS managed cluster.

profiles/latest/mariadb/mgmt/mariadb/models.go, profiles/latest/mysql/mgmt/mysql/models.go, profiles/latest/postgresql/mgmt/postgresql/models.go, profiles/preview/mariadb/mgmt/mariadb/models.go, profiles/preview/mysql/mgmt/mysql/models.go, profiles/preview/postgresql/mgmt/postgresql/models.go, services/mariadb/mgmt/2018-06-01/mariadb/models.go, services/mysql/mgmt/2017-12-01/mysql/models.go, services/postgresql/mgmt/2017-12-01/postgresql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5939
=> [AutoPR mariadb/resource-manager/postgresql/resource-manager/mysql/resource-manager] Add AutoGrow flag for MariaDB, MySQL and PostgreSQL

services/preview/servicefabric/mgmt/2019-03-01/servicefabric/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6058
=> [AutoPR servicefabric/resource-manager] typo: servicefabric/resource-manager/Microsoft.ServiceFabric

profiles/2017-03-09/resources/mgmt/subscriptions/models.go, profiles/2017-03-09/resources/mgmt/subscriptions/subscriptionsapi/models.go, profiles/2018-03-01/resources/mgmt/subscriptions/models.go, profiles/2018-03-01/resources/mgmt/subscriptions/subscriptionsapi/models.go, services/resources/mgmt/2016-06-01/subscriptions/operations.go, services/resources/mgmt/2016-06-01/subscriptions/subscriptions.go, services/resources/mgmt/2016-06-01/subscriptions/subscriptionsapi/interfaces.go, services/resources/mgmt/2016-06-01/subscriptions/tenants.go, services/resources/mgmt/2018-06-01/subscriptions/client.go, services/resources/mgmt/2018-06-01/subscriptions/operations.go, services/resources/mgmt/2018-06-01/subscriptions/subscriptions.go, services/resources/mgmt/2018-06-01/subscriptions/tenants.go, services/resources/mgmt/2018-06-01/subscriptions/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6093
=> [AutoPR resources/resource-manager] Fix api version for subscription

services/preview/iothub/mgmt/2018-12-01-preview/devices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6102
=> [AutoPR iothub/resource-manager] [Hub Generated] Review request for Microsoft.Devices to add version preview/2019-03-22-preview

profiles/latest/advisor/mgmt/advisor/models.go, profiles/preview/advisor/mgmt/advisor/models.go, services/advisor/mgmt/2017-04-19/advisor/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6067
=> [AutoPR advisor/resource-manager] [Microsoft.Advisor] Add isAlertable property to metadata entity properties. (API is not live yet)

services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5890
=> [AutoPR cosmos-db/resource-manager] Fix limit and currentValue properties

services/preview/security/mgmt/v1.0/security/regulatorycomplianceassessments.go, services/preview/security/mgmt/v1.0/security/regulatorycompliancecontrols.go, services/preview/security/mgmt/v1.0/security/regulatorycompliancestandards.go, services/preview/security/mgmt/v1.0/security/securityapi/interfaces.go, services/preview/security/mgmt/v2.0/security/regulatorycomplianceassessments.go, services/preview/security/mgmt/v2.0/security/regulatorycompliancecontrols.go, services/preview/security/mgmt/v2.0/security/regulatorycompliancestandards.go, services/preview/security/mgmt/v2.0/security/securityapi/interfaces.go, services/preview/security/mgmt/v3.0/security/regulatorycomplianceassessments.go, services/preview/security/mgmt/v3.0/security/regulatorycompliancecontrols.go, services/preview/security/mgmt/v3.0/security/regulatorycompliancestandards.go, services/preview/security/mgmt/v3.0/security/securityapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6121
=> [AutoPR security/resource-manager] Remove redundent resourceGroup scope from all paths

services/cognitiveservices/v2.0/computervision/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6056
=> [AutoPR cognitiveservices/data-plane/ComputerVision] [Cogs OCR] Fix bugs in OCR swagger file

profiles/latest/mediaservices/mgmt/media/models.go, profiles/preview/mediaservices/mgmt/media/models.go, services/mediaservices/mgmt/2018-07-01/media/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6143
=> [AutoPR mediaservices/resource-manager] [Hub Generated] Review request for Microsoft.Media to add version stable/2018-07-01

services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6144
=> [AutoPR cosmos-db/resource-manager] CosmosDB add Availability Zone option for locations

profiles/latest/automation/mgmt/automation/models.go, profiles/preview/automation/mgmt/automation/models.go, profiles/preview/preview/automation/mgmt/automation/models.go, services/automation/mgmt/2015-10-31/automation/models.go, services/preview/automation/mgmt/2017-05-15-preview/automation/models.go, services/preview/automation/mgmt/2018-01-15-preview/automation/models.go, services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6032
=> [AutoPR automation/resource-manager] Adding support for minute schedule

profiles/latest/signalr/mgmt/signalr/models.go, profiles/preview/signalr/mgmt/signalr/models.go, services/signalr/mgmt/2018-10-01/signalr/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5661
=> [AutoPR signalr/resource-manager] Add a new field to SignalR Resource property

services/resources/mgmt/2019-03-01/resources/client.go, services/resources/mgmt/2019-03-01/resources/deploymentoperations.go, services/resources/mgmt/2019-03-01/resources/deployments.go, services/resources/mgmt/2019-03-01/resources/groups.go, services/resources/mgmt/2019-03-01/resources/operations.go, services/resources/mgmt/2019-03-01/resources/providers.go, services/resources/mgmt/2019-03-01/resources/resources.go, services/resources/mgmt/2019-03-01/resources/tags.go, services/resources/mgmt/2019-03-01/resources/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5737
=> [AutoPR resources/resource-manager] Add deployment APIs for Microsoft.Resources

profiles/latest/mariadb/mgmt/mariadb/models.go, profiles/latest/mysql/mgmt/mysql/models.go, profiles/preview/mariadb/mgmt/mariadb/models.go, profiles/preview/mysql/mgmt/mysql/models.go, services/mariadb/mgmt/2018-06-01/mariadb/models.go, services/mysql/mgmt/2017-12-01/mysql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6045
=> [AutoPR mariadb/resource-manager/mysql/resource-manager] MariaDB intelligent performance

profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanainstances.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanaonazureapi/interfaces.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5976
=> [AutoPR hanaonazure/resource-manager] Microsoft.HanaOnAzure: Add Delete HanaInstance API

services/preview/cognitiveservices/v1.0/formrecognizer/client.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5886
=> [AutoPR cognitiveservices/data-plane/FormRecognizer] Fix version in form recognizer

profiles/latest/postgresql/mgmt/postgresql/models.go, profiles/preview/postgresql/mgmt/postgresql/models.go, services/postgresql/mgmt/2017-12-01/postgresql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6175
=> [AutoPR postgresql/resource-manager] Enable PG 11

services/containerregistry/mgmt/2019-05-01/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6193
=> [AutoPR containerregistry/resource-manager] typo: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry

services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6146
=> [AutoPR sqlvirtualmachine/resource-manager] [Hub Generated] Review request for Microsoft.SqlVirtualMachine to add version preview/2017-03-01-preview

profiles/latest/resourcegraph/mgmt/resourcegraph/models.go, profiles/preview/resourcegraph/mgmt/resourcegraph/models.go, services/resourcegraph/mgmt/2019-04-01/resourcegraph/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6148
=> [AutoPR resourcegraph/resource-manager] [Resource Graph] result format option added

profiles/latest/resourcegraph/mgmt/resourcegraph/models.go, profiles/preview/resourcegraph/mgmt/resourcegraph/models.go, services/resourcegraph/mgmt/2019-04-01/resourcegraph/models.go
Created to accumulate context: resourcegraph/resource-manager
=> [AutoPR] resourcegraph/resource-manager

profiles/latest/advisor/mgmt/advisor/models.go, profiles/preview/advisor/mgmt/advisor/models.go, services/advisor/mgmt/2017-04-19/advisor/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6112
=> [AutoPR storagesync/resource-manager] [Hub Generated] Review request for Microsoft.StorageSync to add version stable/2019-03-01

services/batch/2019-06-01.9.0/batch/account.go, services/batch/2019-06-01.9.0/batch/application.go, services/batch/2019-06-01.9.0/batch/certificate.go, services/batch/2019-06-01.9.0/batch/computenode.go, services/batch/2019-06-01.9.0/batch/file.go, services/batch/2019-06-01.9.0/batch/job.go, services/batch/2019-06-01.9.0/batch/jobschedule.go, services/batch/2019-06-01.9.0/batch/models.go, services/batch/2019-06-01.9.0/batch/pool.go, services/batch/2019-06-01.9.0/batch/task.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6205
=> [AutoPR batch/data-plane] Make Batch Resources Proper Nouns

services/preview/security/mgmt/v1.0/security/regulatorycomplianceassessments.go, services/preview/security/mgmt/v1.0/security/regulatorycompliancecontrols.go, services/preview/security/mgmt/v1.0/security/regulatorycompliancestandards.go, services/preview/security/mgmt/v1.0/security/securityapi/interfaces.go, services/preview/security/mgmt/v2.0/security/regulatorycomplianceassessments.go, services/preview/security/mgmt/v2.0/security/regulatorycompliancecontrols.go, services/preview/security/mgmt/v2.0/security/regulatorycompliancestandards.go, services/preview/security/mgmt/v2.0/security/securityapi/interfaces.go, services/preview/security/mgmt/v3.0/security/regulatorycomplianceassessments.go, services/preview/security/mgmt/v3.0/security/regulatorycompliancecontrols.go, services/preview/security/mgmt/v3.0/security/regulatorycompliancestandards.go, services/preview/security/mgmt/v3.0/security/securityapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6241
=> [AutoPR security/resource-manager] chore: jsonfmt security

services/storage/mgmt/2019-04-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6243
=> [AutoPR storage/resource-manager] [SRP] Default value change for account property supportsHttpsTrafficOnly

profiles/preview/preview/frontdoor/mgmt/frontdoor/models.go, services/preview/frontdoor/mgmt/2019-04-01/frontdoor/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5918
=> [AutoPR frontdoor/resource-manager] [Hub Generated] Review request for Microsoft.Network to add version preview/2019-03-01-preview

services/mediaservices/mgmt/2018-07-01/media/assets.go, services/mediaservices/mgmt/2018-07-01/media/contentkeypolicies.go, services/mediaservices/mgmt/2018-07-01/media/jobs.go, services/mediaservices/mgmt/2018-07-01/media/models.go, services/mediaservices/mgmt/2018-07-01/media/transforms.go, services/preview/mediaservices/mgmt/2018-03-30-preview/media/assets.go, services/preview/mediaservices/mgmt/2018-03-30-preview/media/contentkeypolicies.go, services/preview/mediaservices/mgmt/2018-03-30-preview/media/models.go, services/preview/mediaservices/mgmt/2018-06-01-preview/media/assets.go, services/preview/mediaservices/mgmt/2018-06-01-preview/media/contentkeypolicies.go, services/preview/mediaservices/mgmt/2018-06-01-preview/media/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6145
=> [AutoPR mediaservices/resource-manager] typo: mediaservices/resource-manager/Microsoft.Media

services/netapp/mgmt/2019-05-01/netapp/client.go, services/netapp/mgmt/2019-05-01/netapp/netappapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6187
=> [AutoPR netapp/resource-manager] chore: jsonfmt netapp

profiles/preview/preview/cognitiveservices/formrecognizer/models.go, services/preview/cognitiveservices/v1.0/formrecognizer/client.go, services/preview/cognitiveservices/v1.0/formrecognizer/formrecognizerapi/interfaces.go, services/preview/cognitiveservices/v1.0/formrecognizer/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6176
=> [AutoPR cognitiveservices/data-plane/FormRecognizer] FormRecognizer: Updating Train API to take optional parameter.

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/storage/mgmt/2019-04-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6250
=> [AutoPR storage/resource-manager] [SRP] Remove azureFilesAadIntegration and add AzureFilesIdentityBased Authentication in storage account properties

profiles/latest/containerregistry/mgmt/containerregistry/models.go, profiles/preview/containerregistry/mgmt/containerregistry/models.go, services/containerregistry/mgmt/2019-04-01/containerregistry/models.go, services/containerregistry/mgmt/2019-05-01/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6221
=> [AutoPR containerregistry/resource-manager] [ACR] Populate Task Timer Trigger in Run Response

services/resources/mgmt/2016-02-01/resources/models.go, services/resources/mgmt/2016-07-01/resources/models.go, services/resources/mgmt/2016-09-01/resources/models.go, services/resources/mgmt/2017-05-10/resources/models.go, services/resources/mgmt/2018-02-01/resources/models.go, services/resources/mgmt/2018-05-01/resources/models.go, services/resources/mgmt/2019-03-01/resources/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6276
=> [AutoPR resources/resource-manager] Add additional ExportTemplate options

services/appinsights/mgmt/2015-05-01/insights/insightsapi/interfaces.go, services/appinsights/mgmt/2015-05-01/insights/models.go, services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go, services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5851
=> [AutoPR applicationinsights/resource-manager/operationalinsights/resource-manager] Improve documentation for App Insights/Log Analytics purge

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/storage/mgmt/2019-04-01/storage/blobcontainers.go, services/storage/mgmt/2019-04-01/storage/models.go, services/storage/mgmt/2019-04-01/storage/storageapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6298
=> [AutoPR storage/resource-manager] Fix List containers

services/appinsights/mgmt/2015-05-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6305
=> [AutoPR applicationinsights/resource-manager] chore: jsonfmt applicationinsights

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, profiles/preview/preview/datafactory/mgmt/datafactory/models.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6314
=> [AutoPR datafactory/resource-manager] Add Dataset and CopySource for SAP HANA

profiles/preview/preview/eventhub/mgmt/eventhub/models.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/clusters.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6352
=> [AutoPR eventhub/resource-manager] Add missing multi-api EventHub

profiles/preview/preview/eventhub/mgmt/eventhub/models.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/clusters.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6063
=> [AutoPR eventhub/resource-manager] chore: jsonfmt eventhub

profiles/preview/preview/resources/mgmt/managementgroups/models.go, services/preview/resources/mgmt/2018-03-01-preview/managementgroups/managementgroups.go, services/preview/resources/mgmt/2018-03-01-preview/managementgroups/managementgroupsapi/interfaces.go, services/preview/resources/mgmt/2018-03-01-preview/managementgroups/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5917
=> [AutoPR managementgroups/resource-manager] Add managementGroups/{id}/descendants route to allow pagination of descendants

profiles/latest/cdn/mgmt/cdn/models.go, profiles/preview/cdn/mgmt/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6316
=> [AutoPR cdn/resource-manager] chore: jsonfmt cdn

profiles/preview/preview/alertsmanagement/mgmt/alertsmanagement/models.go, services/preview/alertsmanagement/mgmt/2019-05-05/alertsmanagement/actionrules.go, services/preview/alertsmanagement/mgmt/2019-05-05/alertsmanagement/alerts.go, services/preview/alertsmanagement/mgmt/2019-05-05/alertsmanagement/alertsmanagementapi/interfaces.go, services/preview/alertsmanagement/mgmt/2019-05-05/alertsmanagement/models.go, services/preview/alertsmanagement/mgmt/2019-05-05/alertsmanagement/smartgroups.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6326
=> [AutoPR alertsmanagement/resource-manager] Update alert and smart group operations in 2019-05-05-preview

services/compute/mgmt/2019-03-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6351
=> [AutoPR compute/resource-manager] Update enableAutomaticUpdates and enableAutomaticOSUpgrade descriptions to reflect exclusivity

services/cosmos-db/mgmt/2015-04-08/documentdb/collection.go, services/cosmos-db/mgmt/2015-04-08/documentdb/collectionpartition.go, services/cosmos-db/mgmt/2015-04-08/documentdb/collectionpartitionregion.go, services/cosmos-db/mgmt/2015-04-08/documentdb/collectionregion.go, services/cosmos-db/mgmt/2015-04-08/documentdb/database.go, services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccountregion.go, services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccounts.go, services/cosmos-db/mgmt/2015-04-08/documentdb/partitionkeyrangeid.go, services/cosmos-db/mgmt/2015-04-08/documentdb/partitionkeyrangeidregion.go, services/cosmos-db/mgmt/2015-04-08/documentdb/percentile.go, services/cosmos-db/mgmt/2015-04-08/documentdb/percentilesourcetarget.go, services/cosmos-db/mgmt/2015-04-08/documentdb/percentiletarget.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6312
=> [AutoPR cosmos-db/resource-manager] Regex and length validation for Cosmos DB Accounts

services/eventgrid/2018-01-01/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6345
=> [AutoPR eventgrid/data-plane] Update a property name of SignalRService

services/eventhub/mgmt/2015-08-01/eventhub/eventhubapi/interfaces.go, services/eventhub/mgmt/2015-08-01/eventhub/eventhubs.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6407
=> [AutoPR eventhub/resource-manager] Eventhub: fixed typo in 2015 API version swagger

services/notificationhubs/mgmt/2014-09-01/notificationhubs/models.go, services/notificationhubs/mgmt/2016-03-01/notificationhubs/models.go, services/notificationhubs/mgmt/2017-04-01/notificationhubs/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6420
=> [AutoPR notificationhubs/resource-manager] typo: notificationhubs

services/cdn/mgmt/preview/2019-06-15-preview/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6417
=> [AutoPR cdn/resource-manager] typo: CDN

services/preview/servicefabric/mgmt/2017-07-01-preview/servicefabric/models.go, services/servicefabric/mgmt/2016-09-01/servicefabric/models.go, services/servicefabric/mgmt/2018-02-01/servicefabric/models.go
Created to accumulate context: servicefabric/resource-manager
=> [AutoPR] servicefabric/resource-manager

services/preview/servicefabric/mgmt/2017-07-01-preview/servicefabric/models.go, services/servicefabric/mgmt/2016-09-01/servicefabric/models.go, services/servicefabric/mgmt/2018-02-01/servicefabric/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6398
=> [AutoPR servicefabric/resource-manager/servicefabric/data-plane] chore: jsonfmt servicefabric

services/preview/softwareplan/mgmt/2019-06-01-preview/softwareplan/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6440
=> [AutoPR softwareplan/resource-manager] typo: softwareplan

services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprintapi/interfaces.go, services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/publishedblueprints.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6399
=> [AutoPR blueprint/resource-manager] [Blueprints] Add published blueprint object to the payload to support change notes

services/preview/softwareplan/mgmt/2019-06-01-preview/softwareplan/models.go
Created to accumulate context: softwareplan/resource-manager
=> [AutoPR] softwareplan/resource-manager

profiles/2018-03-01/authorization/mgmt/authorization/authorizationapi/models.go, profiles/2018-03-01/authorization/mgmt/authorization/models.go, profiles/2019-03-01/authorization/mgmt/authorization/authorizationapi/models.go, profiles/2019-03-01/authorization/mgmt/authorization/models.go, profiles/latest/authorization/mgmt/authorization/authorizationapi/models.go, profiles/latest/authorization/mgmt/authorization/models.go, profiles/preview/authorization/mgmt/authorization/authorizationapi/models.go, profiles/preview/authorization/mgmt/authorization/models.go, services/authorization/mgmt/2015-07-01/authorization/authorizationapi/interfaces.go, services/authorization/mgmt/2015-07-01/authorization/globaladministrator.go, services/authorization/mgmt/2015-07-01/authorization/models.go, services/preview/authorization/mgmt/2017-10-01-preview/authorization/authorizationapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6357
=> [AutoPR authorization/resource-manager] Authorization cleaning

services/costmanagement/mgmt/2019-01-01/costmanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6442
=> [AutoPR cost-management/resource-manager] Updated description for ExportDeliveryDestination

services/compute/mgmt/2018-04-01/compute/models.go, services/compute/mgmt/2018-06-01/compute/models.go, services/compute/mgmt/2018-10-01/compute/models.go, services/compute/mgmt/2019-03-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6404
=> [AutoPR compute/resource-manager] Update ProximityPlacementGroupType description to scope out 'Ultra' from usage

services/vmwarecloudsimple/mgmt/2019-04-01/vmwarecloudsimple/dedicatedcloudservice.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6415
=> [AutoPR vmwarecloudsimple/resource-manager] typo: vmwarecloudsimple

services/vmwarecloudsimple/mgmt/2019-04-01/vmwarecloudsimple/dedicatedcloudservice.go
Created to accumulate context: vmwarecloudsimple/resource-manager
=> [AutoPR] vmwarecloudsimple/resource-manager

services/preview/botservice/mgmt/2017-12-01/botservice/models.go, services/preview/botservice/mgmt/2018-07-12/botservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6418
=> [AutoPR botservice/resource-manager] typo: botservice

profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/models.go, services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6524
=> [AutoPR sqlvirtualmachine/resource-manager] introducing the SqlManagement in Microsoft.SqlVirtualMachine

services/preview/cognitiveservices/v3.0/luis/runtime/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6359
=> [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Update LUIS Runtime swagger to an auto generated version

swagger_to_sdk_config.json
Add sdk_generation_pull_request_base and main_branch properties to swagger_to_sdk_config.json file.
=> Add sdk_generation_pull_request_base and main_branch

profiles/preview/preview/reservations/mgmt/reservations/models.go, services/preview/reservations/mgmt/2019-04-01/reservations/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6539
=> [AutoPR reservations/resource-manager] [Hub Generated] Review request for Microsoft.Capacity to add version preview/2019-04-01

azure-pipelines.yml
=> add azure devops pipeline

README.md, azure-pipelines.yml, storage/file.go, tools/apidiff/cmd/packages.go, tools/apidiff/delta/delta_test.go, tools/apidiff/exports/package_test.go, tools/deprecate/cmd/package.go, tools/profileBuilder/model/latest.go, tools/profileBuilder/model/latest_test.go, tools/profileBuilder/model/paths_test.go, tools/versioner/cmd/root_test.go
Add devops badge to README
Fix lint and vet steps
=> Fixes to devops CI

profiles/latest/cosmos-db/mgmt/documentdb/models.go, profiles/preview/cosmos-db/mgmt/documentdb/models.go, services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6550
=> [AutoPR cosmos-db/resource-manager] Adding cassandra connector properties for cosmos db C* account -

services/cognitiveservices/v2.0/luis/authoring/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6384
=> [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Updating Authoring for roles

profiles/latest/cdn/mgmt/cdn/models.go, profiles/preview/cdn/mgmt/cdn/models.go, services/cdn/mgmt/2019-04-15/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6599
=> [AutoPR cdn/resource-manager] [Hub Generated] Review request for Microsoft.Cdn to add UrlRewrite and CacheKeyQueryString action to 2019-04-15

profiles/latest/cdn/mgmt/cdn/models.go, profiles/preview/cdn/mgmt/cdn/models.go, services/cdn/mgmt/2019-04-15/cdn/models.go
Move changes to 2019-04-15 version.
=> Generated from 537e9475d4ec21dcc8ede20cd45ec73f3f20c729 (#5236)

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6568
=> [AutoPR datafactory/resource-manager] support teradata dataset in adf

services/storage/mgmt/2019-04-01/storage/managementpolicies.go, services/storage/mgmt/2019-04-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6551
=> [AutoPR storage/resource-manager] [Bug fix] Remove read-only constraint for management policy

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, profiles/preview/preview/datafactory/mgmt/datafactory/models.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6548
=> [AutoPR datafactory/resource-manager] SSIS File System Support

swagger_to_sdk_config.json
=> update to latest code generator

profiles/latest/cosmos-db/mgmt/documentdb/models.go, profiles/preview/cosmos-db/mgmt/documentdb/models.go, services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6587
=> [AutoPR cosmos-db/resource-manager] Fixing incorrectly formatted Cosmos DB list keys response

services/machinelearningservices/mgmt/2019-05-01/machinelearningservices/machinelearningservicesapi/interfaces.go, services/machinelearningservices/mgmt/2019-05-01/machinelearningservices/usages.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6656
=> [AutoPR machinelearningservices/resource-manager] [READY TO MERGE] Add missing usages api optional parameter

profiles/latest/cognitiveservices/contentmoderator/models.go, profiles/preview/cognitiveservices/contentmoderator/models.go, services/cognitiveservices/v1.0/contentmoderator/contentmoderatorapi/interfaces.go, services/cognitiveservices/v1.0/contentmoderator/listmanagementterm.go, services/cognitiveservices/v1.0/contentmoderator/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6638
=> [AutoPR cognitiveservices/data-plane/ContentModerator] fix: cognitive services create example

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, profiles/preview/preview/datafactory/mgmt/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/activityruns.go, services/datafactory/mgmt/2018-06-01/datafactory/datasets.go, services/datafactory/mgmt/2018-06-01/datafactory/exposurecontrol.go, services/datafactory/mgmt/2018-06-01/datafactory/factories.go, services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimenodes.go, services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimeobjectmetadata.go, services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go, services/datafactory/mgmt/2018-06-01/datafactory/linkedservices.go, services/datafactory/mgmt/2018-06-01/datafactory/operations.go, services/datafactory/mgmt/2018-06-01/datafactory/pipelineruns.go, services/datafactory/mgmt/2018-06-01/datafactory/pipelines.go, services/datafactory/mgmt/2018-06-01/datafactory/reruntriggers.go, services/datafactory/mgmt/2018-06-01/datafactory/triggerruns.go, services/datafactory/mgmt/2018-06-01/datafactory/triggers.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/activityruns.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/datasets.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/factories.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/integrationruntimenodes.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/integrationruntimes.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/linkedservices.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/operations.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/pipelineruns.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/pipelines.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/triggers.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6617
=> [AutoPR datafactory/resource-manager] [DataFactory]Add AzurePostgreSql Sink and Oracle/SapTable/Netezza Partitions and Several Relational sets

services/compute/mgmt/2019-03-01/compute/models.go, services/compute/mgmt/2019-07-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6710
=> [AutoPR compute/resource-manager] removing non-ascii character

services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6711
=> [AutoPR hanaonazure/resource-manager] Added Keyvault and MSI parameters to create SAP Monitor

.gitignore, swagger_to_sdk_config.json
=> Update swagger_to_sdk_config.json and ignore *.zip files

swagger_to_sdk_config.json
=> Enable SDK Automation pull requests

profiles/latest/signalr/mgmt/signalr/models.go, profiles/preview/signalr/mgmt/signalr/models.go, services/signalr/mgmt/2018-10-01/signalr/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6478
=> [AutoPR signalr/resource-manager] Add new property for CORS settings

profiles/preview/preview/security/mgmt/security/models.go, services/preview/security/mgmt/v3.0/security/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6563
=> [AutoPR security/resource-manager] Michal dev security microsoft.security 2017 08 01 preview

profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/hdinsightapi/interfaces.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/locations.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6665
=> [AutoPR hdinsight/resource-manager] [HDInsight] Add Capabilities to Stable API version,Modify ApplicationType,AccessModes to enum

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/storage/mgmt/2019-04-01/storage/blobservices.go, services/storage/mgmt/2019-04-01/storage/models.go, services/storage/mgmt/2019-04-01/storage/storageapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6657
=> [AutoPR storage/resource-manager] [SRP] Add new API ListBlobServices

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6762
=> [AutoPR datafactory/resource-manager] [Datafactory] Add one new connector and new properties into three connectors

profiles/preview/preview/healthcareapis/mgmt/healthcareapis/models.go, services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6777
=> [AutoPR healthcareapis/resource-manager] Update the possible Kind values to include FHIR R4

profiles/preview/preview/healthcareapis/mgmt/healthcareapis/models.go, services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/models.go
Created to accumulate context: healthcareapis/resource-manager
=> [AutoPR] healthcareapis/resource-manager

services/preview/alertsmanagement/mgmt/2019-05-05/alertsmanagement/actionrules.go, services/preview/alertsmanagement/mgmt/2019-05-05/alertsmanagement/alerts.go, services/preview/alertsmanagement/mgmt/2019-05-05/alertsmanagement/smartgroups.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6812
=> [AutoPR alertsmanagement/resource-manager] fixing subscription id issue

services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6704
=> [AutoPR sql/resource-manager] fix: Microsoft.Sql/stable/2014-04-01 model validation

services/datafactory/mgmt/2018-06-01/datafactory/datafactoryapi/interfaces.go, services/datafactory/mgmt/2018-06-01/datafactory/triggerruns.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6342
=> [AutoPR datafactory/resource-manager] [DataFactory] add TriggerRuns_Rerun api

services/storage/mgmt/2019-04-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6392
=> [AutoPR storage/resource-manager] updating description - clarify encryption enabled by default

profiles/preview/preview/cognitiveservices/inkrecognizer/models.go, services/preview/cognitiveservices/v1.0/inkrecognizer/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6776
=> [AutoPR cognitiveservices/data-plane/InkRecognizer] [Hub Generated] Review request for InkRecognizer to add version preview/v1.0

profiles/preview/preview/cognitiveservices/inkrecognizer/models.go, services/preview/cognitiveservices/v1.0/inkrecognizer/models.go
Created to accumulate context: cognitiveservices/data-plane/InkRecognizer
=> [AutoPR] cognitiveservices/data-plane/InkRecognizer

services/servicefabric/6.2/servicefabric/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6687
=> [AutoPR servicefabric/data-plane] fix: servicefabric character encoding

services/preview/security/mgmt/v2.0/security/models.go, services/preview/security/mgmt/v2.0/security/pricings.go, services/preview/security/mgmt/v3.0/security/models.go, services/preview/security/mgmt/v3.0/security/pricings.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6691
=> [AutoPR security/resource-manager] Adding more documentation to ASC Pricing API

storage/table.go
Fixes https://github.com/Azure/azure-sdk-for-go/issues/5425
=> Fix table query continuation token

tools/apidiff/repo/repo.go, tools/major-updater/cmd/root.go, tools/major-updater/cmd/updateSDK.go
Remove the created branch when the tool ends with error or interrupted.
=> Major-updater tool update

services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6885
=> [AutoPR datamigration/resource-manager] Added "caseManipulation" to MigrateOracleAzureDbPostgreSqlSyncDatabaseInput object

services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6853
=> [AutoPR hanaonazure/resource-manager] Adding managed resource group and log Analytics Workspace to the GET API

services/batch/2019-08-01.10.0/batch/models.go, services/batch/mgmt/2019-08-01/batch/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6867
=> [AutoPR batch/resource-manager/batch/data-plane] Update Batch Swagger documentation

profiles/latest/kusto/mgmt/kusto/models.go, profiles/preview/kusto/mgmt/kusto/models.go, services/kusto/mgmt/2019-01-21/kusto/clusters.go, services/kusto/mgmt/2019-01-21/kusto/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6197
=> [AutoPR azure-kusto/resource-manager] Updating the skus names and clarified capacity description

services/network/mgmt/2019-02-01/network/models.go, services/network/mgmt/2019-04-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6716
=> [AutoPR network/resource-manager] Update definition of ApplicationGatewayOnDemandProbe

profiles/latest/cognitiveservices/qnamaker/models.go, profiles/preview/cognitiveservices/qnamaker/models.go, services/cognitiveservices/v4.0/qnamaker/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6901
=> [AutoPR cognitiveservices/data-plane/QnAMaker] fix schema property naming

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6965
=> [AutoPR datafactory/resource-manager] chore: jsonfmt datafactory

services/machinelearning/mgmt/2016-04-01/workspaces/workspaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6968
=> [AutoPR machinelearning/resource-manager] Mark ownerEmail as required properties for workspace RP

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6954
=> [AutoPR datafactory/resource-manager] [Data Factory]Add property blockSizeInMB for AzureBlobStorageWriteSettings and AzureBlobFSWriteSettings

services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6839
=> [AutoPR hanaonazure/resource-manager] Added Key Vault ID for GET and LIST SapMonitor

swagger_to_sdk_config.json
=> Update to latest Go code generator

services/containerregistry/mgmt/2019-05-01/containerregistry/models.go, services/containerregistry/mgmt/2019-06-01-preview/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7006
=> [AutoPR containerregistry/resource-manager] [ACR] Update retention policy schema

services/compute/mgmt/2019-03-01/compute/models.go, services/compute/mgmt/2019-07-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7025
=> [AutoPR compute/resource-manager] Updating an incorrect description for uploadsizebytes

services/network/mgmt/2019-04-01/network/models.go, services/network/mgmt/2019-04-01/network/privateendpoints.go, services/network/mgmt/2019-04-01/network/privatelinkservices.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6959
=> [AutoPR network/resource-manager] Update 2019-04-01 API as changes from 2019-06-01.

tools/major-updater/cmd/afterscripts.go, tools/major-updater/cmd/autorest.go, tools/major-updater/cmd/work.go
=> Major updater update

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7076
=> [AutoPR datafactory/resource-manager] [Data Factory] Add Chainingtrigger

profiles/latest/eventhub/mgmt/eventhub/models.go, profiles/preview/eventhub/mgmt/eventhub/models.go, services/eventhub/mgmt/2017-04-01/eventhub/eventhubapi/interfaces.go, services/eventhub/mgmt/2017-04-01/eventhub/models.go, services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7052
=> [AutoPR eventhub/resource-manager] Eventhub: added NetworkRuleSets list API

services/compute/mgmt/2016-03-30/compute/availabilitysets.go, services/compute/mgmt/2016-03-30/compute/computeapi/interfaces.go, services/compute/mgmt/2017-03-30/compute/availabilitysets.go, services/compute/mgmt/2017-03-30/compute/computeapi/interfaces.go, services/compute/mgmt/2017-12-01/compute/availabilitysets.go, services/compute/mgmt/2017-12-01/compute/computeapi/interfaces.go, services/compute/mgmt/2018-04-01/compute/availabilitysets.go, services/compute/mgmt/2018-04-01/compute/computeapi/interfaces.go, services/compute/mgmt/2018-06-01/compute/availabilitysets.go, services/compute/mgmt/2018-06-01/compute/computeapi/interfaces.go, services/compute/mgmt/2018-10-01/compute/availabilitysets.go, services/compute/mgmt/2018-10-01/compute/computeapi/interfaces.go, services/compute/mgmt/2019-03-01/compute/availabilitysets.go, services/compute/mgmt/2019-03-01/compute/computeapi/interfaces.go, services/compute/mgmt/2019-07-01/compute/availabilitysets.go, services/compute/mgmt/2019-07-01/compute/computeapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7078
=> [AutoPR compute/resource-manager] [Compute] Add missing $expand parameter to AvSet list by subscription API

services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/client.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7042
=> [AutoPR cognitiveservices/resource-manager] Fix check domain path

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6969
=> [AutoPR datafactory/resource-manager] support Express Custom Setup

profiles/preview/preview/sql/mgmt/sql/models.go, services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go, services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6902
=> [AutoPR sql/resource-manager] Updating databases for new read scale property

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/activityruns.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7040
=> [AutoPR datafactory/resource-manager] [Data Factory]Add ORC Dataset/Copy Source/Copy Sink

profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/bookmarks.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/cases.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7108
=> [AutoPR securityinsights/resource-manager] Sorted definitions and parameters by ABC

profiles/latest/kusto/mgmt/kusto/models.go, profiles/preview/kusto/mgmt/kusto/models.go, services/kusto/mgmt/2019-05-15/kusto/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7100
=> [AutoPR azure-kusto/resource-manager] Update Kusto.json with TSVE data format

profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/bookmarks.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/cases.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7128
=> [AutoPR securityinsights/resource-manager] chore: jsonfmt securityinsights/

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/storage/mgmt/2019-04-01/storage/fileservices.go, services/storage/mgmt/2019-04-01/storage/fileshares.go, services/storage/mgmt/2019-04-01/storage/models.go, services/storage/mgmt/2019-04-01/storage/storageapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7049
=> [AutoPR storage/resource-manager] Add change feed properties to 2019-04-01 Storage.

services/keyvault/2015-06-01/keyvault/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7083
=> [AutoPR keyvault/resource-manager/keyvault/data-plane] [Hub Generated] Review request for Microsoft.KeyVault to add version preview/7.0

profiles/preview/preview/sql/mgmt/sql/models.go, services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go, services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7102
=> [AutoPR sql/resource-manager] invalid non ascii character was causing problems

services/network/mgmt/2019-06-01/network/connectionmonitors.go, services/network/mgmt/2019-06-01/network/networkapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7131
=> [AutoPR network/resource-manager] Added priority field in the request routing rule

profiles/latest/compute/mgmt/compute/models.go, profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2016-03-30/compute/availabilitysets.go, services/compute/mgmt/2016-03-30/compute/computeapi/interfaces.go, services/compute/mgmt/2017-03-30/compute/availabilitysets.go, services/compute/mgmt/2017-03-30/compute/computeapi/interfaces.go, services/compute/mgmt/2017-12-01/compute/availabilitysets.go, services/compute/mgmt/2017-12-01/compute/computeapi/interfaces.go, services/compute/mgmt/2018-04-01/compute/availabilitysets.go, services/compute/mgmt/2018-04-01/compute/computeapi/interfaces.go, services/compute/mgmt/2018-06-01/compute/availabilitysets.go, services/compute/mgmt/2018-06-01/compute/computeapi/interfaces.go, services/compute/mgmt/2018-10-01/compute/availabilitysets.go, services/compute/mgmt/2018-10-01/compute/computeapi/interfaces.go, services/compute/mgmt/2019-03-01/compute/availabilitysets.go, services/compute/mgmt/2019-03-01/compute/computeapi/interfaces.go, services/compute/mgmt/2019-03-01/compute/models.go, services/compute/mgmt/2019-07-01/compute/availabilitysets.go, services/compute/mgmt/2019-07-01/compute/computeapi/interfaces.go, services/compute/mgmt/2019-07-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7034
=> [AutoPR compute/resource-manager] Add VMScaleSet ScaleIn Policy

services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/activityruns.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7162
=> [AutoPR datafactory/resource-manager] [DataFactory] Update Databricks linked service swagger related to warm pools

services/batch/mgmt/2019-08-01/batch/applicationpackage.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7177
=> [AutoPR batch/resource-manager] [Batch] Update documentation around app packages

services/network/mgmt/2019-06-01/network/connectionmonitors.go, services/network/mgmt/2019-06-01/network/networkapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7075
=> [AutoPR network/resource-manager] Support for changes in ConnectionMonitor API

profiles/latest/compute/mgmt/compute/models.go, profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2019-03-01/compute/models.go, services/compute/mgmt/2019-07-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7166
=> [AutoPR compute/resource-manager] added missing packages to compute release

services/apimanagement/mgmt/2019-01-01/apimanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6844
=> [AutoPR apimanagement/resource-manager] Orphan property removed

services/network/mgmt/2018-07-01/network/models.go, services/network/mgmt/2018-08-01/network/models.go, services/network/mgmt/2018-10-01/network/models.go, services/network/mgmt/2018-11-01/network/models.go, services/network/mgmt/2018-12-01/network/models.go, services/network/mgmt/2019-02-01/network/models.go, services/network/mgmt/2019-04-01/network/models.go, services/network/mgmt/2019-04-01/network/privateendpoints.go, services/network/mgmt/2019-04-01/network/privatelinkservices.go, services/network/mgmt/2019-06-01/network/connectionmonitors.go, services/network/mgmt/2019-06-01/network/networkapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7169
=> [AutoPR network/resource-manager] Add Mssql value to Application Rule Type enum of AzureFirewall Microsoft.Network resource to stable/2019-07-01

services/cognitiveservices/v1.0/localsearch/client.go, services/cognitiveservices/v1.0/localsearch/local.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7113
=> [AutoPR cognitiveservices/data-plane/LocalSearch] Fix Local Search Swagger

profiles/latest/network/mgmt/network/models.go, profiles/preview/network/mgmt/network/models.go, services/network/mgmt/2019-06-01/network/bastionhosts.go, services/network/mgmt/2019-06-01/network/connectionmonitors.go, services/network/mgmt/2019-06-01/network/models.go, services/network/mgmt/2019-06-01/network/networkapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7208
=> [AutoPR network/resource-manager] Network August release

services/cognitiveservices/v1.0/spellcheck/client.go
Created to accumulate context: cognitiveservices/data-plane/SpellCheck
=> [AutoPR] cognitiveservices/data-plane/SpellCheck

services/cognitiveservices/v1.0/localsearch/client.go, services/cognitiveservices/v1.0/localsearch/local.go
Created to accumulate context: cognitiveservices/data-plane/LocalSearch
=> [AutoPR] cognitiveservices/data-plane/LocalSearch

services/appinsights/mgmt/2015-05-01/insights/components.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7157
=> [AutoPR applicationinsights/resource-manager] Add purge API details.

profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7130
=> [AutoPR securityinsights/resource-manager] Adding kinds for AlertRules endpoints, updating AlertRuleTemplates endpoints

profiles/preview/containerregistry/mgmt/containerregistry/models.go, services/containerregistry/mgmt/2019-05-01-preview/containerregistry/models.go, services/containerregistry/mgmt/2019-06-01-preview/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7223
=> [AutoPR containerregistry/resource-manager] [ACR] Scope map updates

services/preview/frontdoor/mgmt/2019-04-01/frontdoor/models.go, services/preview/frontdoor/mgmt/2019-05-01/frontdoor/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7220
=> [AutoPR frontdoor/resource-manager] [AFD WAF] Add defaultState and defaultAction to managed rule set definitions

services/datamigration/mgmt/2018-04-19/datamigration/models.go, services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/models.go, services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7236
=> [AutoPR datamigration/resource-manager] Fix eligibility typo

services/containerservice/mgmt/2019-06-01/containerservice/agentpools.go, services/containerservice/mgmt/2019-06-01/containerservice/containerserviceapi/interfaces.go, services/containerservice/mgmt/2019-08-01/containerservice/agentpools.go, services/containerservice/mgmt/2019-08-01/containerservice/containerserviceapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7217
=> [AutoPR containerservice/resource-manager] fix getting agent pool available versions api path

profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7197
=> [AutoPR securityinsights/resource-manager] Add item to AttackTactic enum

services/preview/managednetwork/mgmt/2019-06-01-preview/managednetwork/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7233
=> [AutoPR managednetwork/resource-manager] Update ManagedNetwork

services/machinelearningservices/mgmt/2019-06-01/machinelearningservices/machinelearningservicesapi/interfaces.go, services/machinelearningservices/mgmt/2019-06-01/machinelearningservices/usages.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7251
=> [AutoPR machinelearningservices/resource-manager] Restoring quota patch overwritten during 2019-06-01 version update

services/preview/managednetwork/mgmt/2019-06-01-preview/managednetwork/models.go
Created to accumulate context: managednetwork/resource-manager
=> [AutoPR] managednetwork/resource-manager

services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7278
=> [AutoPR datamigration/resource-manager] Add aad domain name for windows login migration support

profiles/preview/containerregistry/mgmt/containerregistry/models.go, services/containerregistry/mgmt/2019-05-01-preview/containerregistry/models.go, services/containerregistry/mgmt/2019-06-01-preview/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7291
=> [AutoPR containerregistry/resource-manager] enum name must be fixed here as well

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7242
=> [AutoPR datafactory/resource-manager] [DataFactory] - Add CosmosDbSqlApi dataset

profiles/preview/preview/datashare/mgmt/datashare/models.go, services/preview/datashare/mgmt/2018-11-01-preview/datashare/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7347
=> [AutoPR datashare/resource-manager] SQL changes

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/datafactoryapi/interfaces.go, services/datafactory/mgmt/2018-06-01/datafactory/dataflowdebugsession.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7325
=> [AutoPR datafactory/resource-manager] [Data Factory] Add data flow compute property in IR.

services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7351
=> [AutoPR datafactory/resource-manager] [DataFactory]Add property to event triggers

services/compute/mgmt/2015-06-15/compute/virtualmachines.go, services/compute/mgmt/2016-03-30/compute/virtualmachines.go, services/compute/mgmt/2017-03-30/compute/virtualmachines.go, services/compute/mgmt/2017-12-01/compute/virtualmachines.go, services/compute/mgmt/2017-12-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2017-12-01/compute/virtualmachinescalesetvms.go, services/compute/mgmt/2018-04-01/compute/virtualmachines.go, services/compute/mgmt/2018-04-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2018-04-01/compute/virtualmachinescalesetvms.go, services/compute/mgmt/2018-06-01/compute/virtualmachines.go, services/compute/mgmt/2018-06-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2018-06-01/compute/virtualmachinescalesetvms.go, services/compute/mgmt/2018-10-01/compute/virtualmachines.go, services/compute/mgmt/2018-10-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetvms.go, services/compute/mgmt/2019-03-01/compute/virtualmachines.go, services/compute/mgmt/2019-03-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2019-03-01/compute/virtualmachinescalesetvms.go, services/compute/mgmt/2019-07-01/compute/virtualmachines.go, services/compute/mgmt/2019-07-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2019-07-01/compute/virtualmachinescalesetvms.go, services/preview/compute/mgmt/2016-04-30-preview/compute/virtualmachines.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7294
=> [AutoPR compute/resource-manager] Improve the description for VM redeploy operation

profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/models.go, services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go, services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/sqlvirtualmachineapi/interfaces.go, services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/sqlvirtualmachines.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7324
=> [AutoPR sqlvirtualmachine/resource-manager] Update SQL VM Rest API

services/containerregistry/mgmt/2019-05-01-preview/containerregistry/models.go, services/containerregistry/mgmt/2019-05-01-preview/containerregistry/scopemaps.go, services/containerregistry/mgmt/2019-06-01-preview/containerregistry/models.go, services/containerregistry/mgmt/2019-06-01-preview/containerregistry/scopemaps.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7252
=> [AutoPR containerregistry/resource-manager] [ACR] Scope map property updates

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7404
=> [AutoPR datafactory/resource-manager] [Data Factory] Add Switch activity

services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7379
=> [AutoPR datamigration/resource-manager] Fixing incorrect output of the CheckOCIDriver task

services/compute/mgmt/2015-06-15/compute/virtualmachines.go, services/compute/mgmt/2016-03-30/compute/virtualmachines.go, services/compute/mgmt/2017-03-30/compute/virtualmachines.go, services/compute/mgmt/2017-12-01/compute/virtualmachines.go, services/compute/mgmt/2017-12-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2017-12-01/compute/virtualmachinescalesetvms.go, services/compute/mgmt/2018-04-01/compute/virtualmachines.go, services/compute/mgmt/2018-04-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2018-04-01/compute/virtualmachinescalesetvms.go, services/compute/mgmt/2018-06-01/compute/virtualmachines.go, services/compute/mgmt/2018-06-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2018-06-01/compute/virtualmachinescalesetvms.go, services/compute/mgmt/2018-10-01/compute/virtualmachines.go, services/compute/mgmt/2018-10-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetvms.go, services/compute/mgmt/2019-03-01/compute/models.go, services/compute/mgmt/2019-03-01/compute/virtualmachines.go, services/compute/mgmt/2019-03-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2019-03-01/compute/virtualmachinescalesetvms.go, services/compute/mgmt/2019-07-01/compute/models.go, services/compute/mgmt/2019-07-01/compute/virtualmachines.go, services/compute/mgmt/2019-07-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2019-07-01/compute/virtualmachinescalesetvms.go, services/preview/compute/mgmt/2016-04-30-preview/compute/virtualmachines.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7355
=> [AutoPR compute/resource-manager] vmss: support for passing a health probe to update

services/compute/mgmt/2019-07-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7385
=> [AutoPR compute/resource-manager] updating the description of storage account id

services/compute/mgmt/2019-07-01/compute/disks.go, services/compute/mgmt/2019-07-01/compute/models.go, services/compute/mgmt/2019-07-01/compute/snapshots.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7456
=> [AutoPR compute/resource-manager] Private temp

services/compute/mgmt/2019-07-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7510
=> [AutoPR compute/resource-manager] Update swagger

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/storage/mgmt/2019-04-01/storage/accounts.go, services/storage/mgmt/2019-04-01/storage/models.go, services/storage/mgmt/2019-04-01/storage/storageapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7506
=> [AutoPR storage/resource-manager] [SRP] Support Active Directory and regenerate kerb keys

services/compute/mgmt/2018-10-01/compute/models.go, services/compute/mgmt/2019-03-01/compute/models.go, services/compute/mgmt/2019-07-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7513
=> [AutoPR compute/resource-manager] Include doNotRunExtensionsOnOverprovisionedVMs property in updateVMSS

services/network/mgmt/2019-09-01/network/applicationgateways.go, services/network/mgmt/2019-09-01/network/inboundnatrules.go, services/network/mgmt/2019-09-01/network/interfacesgroup.go, services/network/mgmt/2019-09-01/network/interfacetapconfigurations.go, services/network/mgmt/2019-09-01/network/loadbalancers.go, services/network/mgmt/2019-09-01/network/localnetworkgateways.go, services/network/mgmt/2019-09-01/network/models.go, services/network/mgmt/2019-09-01/network/natgateways.go, services/network/mgmt/2019-09-01/network/privateendpoints.go, services/network/mgmt/2019-09-01/network/privatelinkservices.go, services/network/mgmt/2019-09-01/network/profiles.go, services/network/mgmt/2019-09-01/network/publicipaddresses.go, services/network/mgmt/2019-09-01/network/publicipprefixes.go, services/network/mgmt/2019-09-01/network/routes.go, services/network/mgmt/2019-09-01/network/routetables.go, services/network/mgmt/2019-09-01/network/securitygroups.go, services/network/mgmt/2019-09-01/network/securityrules.go, services/network/mgmt/2019-09-01/network/serviceendpointpolicies.go, services/network/mgmt/2019-09-01/network/serviceendpointpolicydefinitions.go, services/network/mgmt/2019-09-01/network/subnets.go, services/network/mgmt/2019-09-01/network/virtualnetworkgatewayconnections.go, services/network/mgmt/2019-09-01/network/virtualnetworkgateways.go, services/network/mgmt/2019-09-01/network/virtualnetworkpeerings.go, services/network/mgmt/2019-09-01/network/virtualnetworks.go, services/network/mgmt/2019-09-01/network/virtualnetworktaps.go, services/network/mgmt/2019-09-01/network/watchers.go, services/network/mgmt/2019-09-01/network/webapplicationfirewallpolicies.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7488
=> [AutoPR network/resource-manager] Network: Mark read-only properties as such

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7452
=> [AutoPR datafactory/resource-manager] [DataFactory]Add CompressionCodec property for ORC Dataset

profiles/preview/preview/appplatform/mgmt/appplatform/models.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7537
=> [AutoPR appplatform/resource-manager] Add "Allocating","Upgrading" and "Compiling" enum into DeploymentResourceStatus.

services/network/mgmt/2019-09-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7532
=> [AutoPR network/resource-manager] add additional properties to template and examples

profiles/latest/containerservice/mgmt/containerservice/models.go, profiles/preview/containerservice/mgmt/containerservice/models.go, profiles/preview/preview/containerservice/mgmt/containerservice/models.go, services/containerservice/mgmt/2019-08-01/containerservice/containerserviceapi/interfaces.go, services/containerservice/mgmt/2019-08-01/containerservice/managedclusters.go, services/containerservice/mgmt/2019-08-01/containerservice/models.go, services/preview/containerservice/mgmt/2019-09-30-preview/containerservice/containerserviceapi/interfaces.go, services/preview/containerservice/mgmt/2019-09-30-preview/containerservice/managedclusters.go, services/preview/containerservice/mgmt/2019-09-30-preview/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7436
=> [AutoPR containerservice/resource-manager] [WIP]add aks rotate-certs operation for 2019-08-01

profiles/latest/network/mgmt/network/models.go, profiles/preview/network/mgmt/network/models.go, services/network/mgmt/2019-09-01/network/models.go, services/network/mgmt/2019-09-01/network/networkapi/interfaces.go, services/network/mgmt/2019-09-01/network/privatelinkservices.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7545
=> [AutoPR network/resource-manager] Network: add missing default responses

profiles/preview/preview/reservations/mgmt/reservations/models.go, services/preview/reservations/mgmt/2019-04-01/reservations/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7541
=> [AutoPR reservations/resource-manager] Updating swagger spec to fix billing plans schema in catalogs response.

services/preview/datashare/mgmt/2018-11-01-preview/datashare/datasetmappings.go, services/preview/datashare/mgmt/2018-11-01-preview/datashare/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7582
=> [AutoPR datashare/resource-manager] Update data set related documentation comments for AzureDataShare

services/preview/datashare/mgmt/2018-11-01-preview/datashare/datasetmappings.go, services/preview/datashare/mgmt/2018-11-01-preview/datashare/models.go
Created to accumulate context: datashare/resource-manager
=> [AutoPR] datashare/resource-manager

profiles/latest/containerservice/mgmt/containerservice/models.go, profiles/preview/containerservice/mgmt/containerservice/models.go, services/containerservice/mgmt/2019-10-01/containerservice/containerserviceapi/interfaces.go, services/containerservice/mgmt/2019-10-01/containerservice/managedclusters.go, services/containerservice/mgmt/2019-10-01/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7614
=> [AutoPR containerservice/resource-manager] added missing part from 2019-08-01

profiles/preview/preview/appplatform/mgmt/appplatform/models.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/appplatformapi/interfaces.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/apps.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7594
=> [AutoPR appplatform/resource-manager] Make PUT and PATCH against App resource supports async

services/storagecache/mgmt/2019-11-01/storagecache/caches.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7584
=> [AutoPR storagecache/resource-manager] Microsoft Azure StorageCache - Add 204 response code to cache flush, start, stop and upgrade operation.

services/storagecache/mgmt/2019-11-01/storagecache/caches.go
Created to accumulate context: storagecache/resource-manager
=> [AutoPR] storagecache/resource-manager

services/preview/cognitiveservices/v1.0/visualsearch/client.go, services/preview/cognitiveservices/v1.0/visualsearch/images.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7610
=> [AutoPR cognitiveservices/data-plane/VisualSearch] Adding EU compliance not to description

services/preview/sql/mgmt/2018-06-01-preview/sql/databases.go, services/preview/sql/mgmt/2018-06-01-preview/sql/models.go, services/preview/sql/mgmt/2018-06-01-preview/sql/sqlapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7405
=> [AutoPR sql/resource-manager] Failover Database Readable Secondary

services/network/mgmt/2019-09-01/network/ipgroups.go, services/network/mgmt/2019-09-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7662
=> [AutoPR network/resource-manager] Improve Network's descriptions

profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7670
=> [AutoPR hanaonazure/resource-manager] Update HanaOnAzure Swagger to support new Cascade Lake SKUs

profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7645
=> [AutoPR securityinsights/resource-manager] Add Azure Security Center for IoT to productFilter enum

services/storage/mgmt/2019-06-01/storage/blobservices.go, services/storage/mgmt/2019-06-01/storage/fileservices.go, services/storage/mgmt/2019-06-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7626
=> [AutoPR storage/resource-manager] [SRP] Add delete retention policy for blob container and file share

profiles/preview/preview/sql/mgmt/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7684
=> [AutoPR storagecache/resource-manager] Fix issue with CloudError in Storage Cache

profiles/latest/signalr/mgmt/signalr/models.go, profiles/preview/signalr/mgmt/signalr/models.go, services/signalr/mgmt/2018-10-01/signalr/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7635
=> [AutoPR signalr/resource-manager] fix missing status code in SignalR

profiles/preview/preview/sql/mgmt/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7674
=> [AutoPR hybridcompute/resource-manager] Make OSName, OSVersion properties writable

profiles/preview/preview/sql/mgmt/sql/models.go
Created to accumulate context: hybridcompute/resource-manager
=> [AutoPR] hybridcompute/resource-manager

services/preview/eventgrid/mgmt/2020-01-01-preview/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7681
=> [AutoPR eventgrid/resource-manager] add azureActiveDirectoryTenantId

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/storage/mgmt/2019-06-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7689
=> [AutoPR storage/resource-manager] [Routing Preference] Adding routing preferences API changes, private repo PR# 973

services/network/mgmt/2019-09-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7205
=> [AutoPR network/resource-manager] add PreferredIPVersion to ConnectivityCheck

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/storage/mgmt/2019-06-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7703
=> [AutoPR storage/resource-manager] [SRP][Fix Typo] DeleteRetentionPolicy is a common class that applies to both file and blob

services/storage/mgmt/2019-06-01/storage/blobservices.go, services/storage/mgmt/2019-06-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7706
=> [AutoPR storage/resource-manager] [SRP] Remove a recent added property for container soft delete

services/storage/mgmt/2019-06-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7714
=> [AutoPR storage/resource-manager] Rout update1

CHANGELOG.md, services/preview/eventgrid/mgmt/2020-01-01-preview/eventgrid/models.go, version/version.go
=> Minor version 36.1.0

profiles/preview/preview/security/mgmt/security/models.go, services/preview/security/mgmt/v3.0/security/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7283
=> [AutoPR security/resource-manager] Add 'unmaskedIpLoggingStatus' to IotSecuritySolution

services/preview/servicefabric/mgmt/2017-07-01-preview/servicefabric/models.go, services/preview/servicefabric/mgmt/2019-03-01-preview/servicefabric/models.go, services/servicefabric/mgmt/2018-02-01/servicefabric/models.go, services/servicefabric/mgmt/2019-03-01/servicefabric/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7722
=> [AutoPR servicefabric/resource-manager] remove locale from links

profiles/latest/storage/mgmt/storage/models.go, profiles/preview/storage/mgmt/storage/models.go, services/storage/mgmt/2019-06-01/storage/blobservices.go, services/storage/mgmt/2019-06-01/storage/fileservices.go, services/storage/mgmt/2019-06-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7694
=> [AutoPR storage/resource-manager] [SRP] Add account sku to file/blob service response

services/signalr/mgmt/2018-10-01/signalr/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7723
=> [AutoPR signalr/resource-manager] remove locale from link

services/network/mgmt/2019-08-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7498
=> [AutoPR network/resource-manager] Fix Virtual Wan Point to site feature resources property names from swagger.

services/cdn/mgmt/2019-04-15/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7715
=> [AutoPR cdn/resource-manager] update description for UrlRewrite Action

services/preview/sql/mgmt/2017-03-01-preview/sql/managedinstanceadministrators.go, services/preview/sql/mgmt/2017-03-01-preview/sql/sqlapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7377
=> [AutoPR sql/resource-manager] AdministratorName parameter should take value which is defined in enum 

sdk/storage/azblob/examples_test.go, sdk/storage/azblob/go.mod, sdk/storage/azblob/go.sum, sdk/storage/azblob/models.go, sdk/storage/azblob/service.go, sdk/storage/azstorage/go.mod, sdk/storage/azstorage/go.sum, sdk/storage/azstorage/policy_shared_key_credential.go
=> small azblob for end-to-end sample

profiles/latest/policyinsights/mgmt/policyinsights/models.go, profiles/preview/policyinsights/mgmt/policyinsights/models.go, services/policyinsights/mgmt/2019-10-01/policyinsights/models.go, services/policyinsights/mgmt/2019-10-01/policyinsights/remediations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7717
=> [AutoPR policyinsights/resource-manager] Microsoft.PolicyInsights/remediations 2019-07-01

services/cognitiveservices/v4.0/qnamaker/knowledgebase.go, services/cognitiveservices/v4.0/qnamaker/models.go, services/cognitiveservices/v4.0/qnamakerruntime/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7729
=> [AutoPR cognitiveservices/data-plane/QnAMaker] [QnA Maker] Update API data fields.

services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7759
=> [AutoPR sql/resource-manager] Sql auditing swagger - add queueDelayMs property

services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7732
=> [AutoPR hanaonazure/resource-manager] Added enableCustomerAnalytics Flag to create SapMonitor

services/preview/security/mgmt/v1.0/security/alerts.go, services/preview/security/mgmt/v1.0/security/securityapi/interfaces.go, services/preview/security/mgmt/v2.0/security/alerts.go, services/preview/security/mgmt/v2.0/security/securityapi/interfaces.go, services/preview/security/mgmt/v3.0/security/alerts.go, services/preview/security/mgmt/v3.0/security/securityapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7752
=> [AutoPR security/resource-manager] fix swagger completeness issue

services/web/mgmt/2016-09-01/web/apps.go, services/web/mgmt/2018-02-01/web/apps.go, services/web/mgmt/2019-08-01/web/apps.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7775
=> [AutoPR web/resource-manager] Fixing description for deleteEmptyServerFarm

profiles/preview/preview/virtualmachineimagebuilder/mgmt/virtualmachineimagebuilder/models.go, services/preview/virtualmachineimagebuilder/mgmt/2019-05-01-preview/virtualmachineimagebuilder/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7655
=> [AutoPR imagebuilder/resource-manager] [Hub Generated] Review request for Microsoft.VirtualMachineImages to add version preview/2019-05-01-preview

services/keyvault/v7.0/keyvault/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7762
=> [AutoPR keyvault/data-plane] Update Certificate Type description

services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7728
=> [AutoPR hanaonazure/resource-manager] Update swagger spec to add existing log analytics workspace

services/policyinsights/mgmt/2019-10-01/policyinsights/models.go, services/policyinsights/mgmt/2019-10-01/policyinsights/policyinsightsapi/interfaces.go, services/policyinsights/mgmt/2019-10-01/policyinsights/policymetadata.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7805
=> [AutoPR policyinsights/resource-manager] Fix Microsoft.policyInsights/policyMetadata query parameter

services/network/mgmt/2019-08-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7788
=> [AutoPR network/resource-manager] Committing changes to remove verbs from Swagger descriptions

services/containerservice/mgmt/2019-10-01/containerservice/containerserviceapi/interfaces.go, services/containerservice/mgmt/2019-10-01/containerservice/managedclusters.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7799
=> [AutoPR containerservice/resource-manager] add AKS listClusterMonitoringUserCredential API

services/storage/mgmt/2019-06-01/storage/fileshares.go, services/storage/mgmt/2019-06-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7824
=> [AutoPR storage/resource-manager] [SRP] Increase the max file share quota for LFS

profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/models.go, services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7819
=> [AutoPR sqlvirtualmachine/resource-manager] Add new License type enum value for DR

services/preview/managednetwork/mgmt/2019-06-01-preview/managednetwork/models.go, services/preview/managednetwork/mgmt/2019-06-01-preview/managednetwork/scopeassignments.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7665
=> [AutoPR managednetwork/resource-manager/web/resource-manager] Fixed scope assignments and some documentation

services/maps/mgmt/2017-01-01-preview/maps/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7606
=> [AutoPR maps/resource-manager] adding missing readonly property (#7428)

sdk/azcore/core.go, sdk/azcore/internal/mock/mock.go, sdk/azcore/policy_anonymous_credential_test.go, sdk/azcore/policy_body_download.go, sdk/azcore/policy_body_download_test.go, sdk/azcore/policy_logging_test.go, sdk/azcore/policy_retry.go, sdk/azcore/policy_retry_test.go, sdk/azcore/policy_telemetry.go, sdk/azcore/policy_telemetry_test.go, sdk/azcore/policy_unique_request_id.go, sdk/azcore/policy_unique_request_id_test.go
This gets us to 39.9% code coverage of `azcore`
=> add internal mock package for testing

profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/bookmarks.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7663
=> [AutoPR securityinsights/resource-manager] Adding incident info to GetBookmarks

services/preview/resourcegraph/mgmt/2018-09-01/resourcegraph/graphquery.go, services/preview/resourcegraph/mgmt/2018-09-01/resourcegraph/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7838
=> [AutoPR resourcegraph/resource-manager] Microsoft.ResoureGraph/queries path typo fix

sdk/azidentity/client_secret_credential.go
also avoids using an expired token
=> improved token refresh logic

services/network/mgmt/2019-08-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7747
=> [AutoPR network/resource-manager] virtual wan/gateway disconnect vpn connections

services/preview/resources/mgmt/2018-03-01-preview/managementgroups/managementgroups.go, services/preview/resources/mgmt/2019-11-01/managementgroups/managementgroups.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7856
=> [AutoPR managementgroups/resource-manager] fix api method

profiles/preview/preview/cdn/mgmt/cdn/models.go, services/preview/cdn/mgmt/2019-06-15-preview/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7442
=> [AutoPR cdn/resource-manager] [CDN] Copy changes from API version 2019-04-15 into 2019-06-15-preview.

profiles/latest/cosmos-db/mgmt/documentdb/models.go, profiles/preview/cosmos-db/mgmt/documentdb/models.go, profiles/preview/preview/cosmos-db/mgmt/documentdb/models.go, services/cosmos-db/mgmt/2019-08-01/documentdb/models.go, services/preview/cosmos-db/mgmt/2019-08-01-preview/documentdb/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7790
=> [AutoPR cosmos-db/resource-manager] Fix response structure

profiles/latest/mysql/mgmt/mysql/models.go, profiles/preview/mysql/mgmt/mysql/models.go, profiles/preview/preview/mysql/mgmt/mysql/models.go, services/mysql/mgmt/2017-12-01/mysql/models.go, services/preview/mysql/mgmt/2017-12-01-preview/mysql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7864
=> [AutoPR mysql/resource-manager] Support MySQL ServerVersion 8.0

sdk/azcore/core.go, sdk/azcore/policy_body_download_test.go, sdk/azcore/policy_retry.go, sdk/azcore/policy_retry_test.go, sdk/azcore/progress.go, sdk/azcore/progress_test.go, sdk/azcore/request.go, sdk/azcore/request_test.go, sdk/azcore/response_test.go, sdk/azidentity/azidentity.go, sdk/internal/mock/mock.go
added test for progress reporting
don't retry on terminal errors
other clean-up and refactoring
=> added tests for request and response type

profiles/latest/datafactory/mgmt/datafactory/models.go, profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7860
=> [AutoPR datafactory/resource-manager] [DataFactory]Support partition of SAP HANA

services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/appplatformapi/interfaces.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/apps.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/bindings.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/deployments.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/services.go
Created to accumulate context: appplatform/resource-manager
=> [AutoPR] appplatform/resource-manager

services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/appplatformapi/interfaces.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/apps.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/bindings.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/deployments.go, services/preview/appplatform/mgmt/2019-05-01-preview/appplatform/services.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7877
=> [AutoPR appplatform/resource-manager] Changed some orders of parameters in `appplatform` to comply with the convention of SDK

services/storage/mgmt/2019-06-01/storage/fileshares.go, services/storage/mgmt/2019-06-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7891
=> [AutoPR storage/resource-manager] [Storage] Fix the share max quota to right value 102400

sdk/azcore/core.go, sdk/azidentity/aad_identity_client.go, sdk/azidentity/azidentity.go, sdk/azidentity/default_azure_credential.go, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go, sdk/storage/azblob/examples_test.go, sdk/storage/azblob/service.go, sdk/storage/azstorage/go.mod, sdk/storage/azstorage/go.sum, sdk/storage/azstorage/policy_shared_key_credential.go
made MSI client ctor no-fail
fixed up shared key credential
=> move pipeline options to clients

profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/bookmarks.go, services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7843
=> [AutoPR mediaservices/resource-manager] MediaServices: update to specify autorest.java version

.github/no-response.yml
=> Add no-response bot configuration

CHANGELOG.md, services/iotcentral/mgmt/2018-09-01/iotcentral/models.go, version/version.go
=> Minor version 37.1.0

services/resources/mgmt/2019-09-01/policy/assignments.go, services/resources/mgmt/2019-09-01/policy/client.go, services/resources/mgmt/2019-09-01/policy/definitions.go, services/resources/mgmt/2019-09-01/policy/policyapi/interfaces.go, services/resources/mgmt/2019-09-01/policy/setdefinitions.go
=> [ReleasePR resources/mgmt/2019-09-01] Add missing properties for Application and ApplicationDefinition

profiles/preview/preview/containerregistry/runtime/containerregistry/containerregistryapi/models.go, profiles/preview/preview/containerregistry/runtime/containerregistry/models.go
=> Re-generate profiles

.github/sla.yml
=> Config for sla notification bot

.github/sla.yml, CHANGELOG.md, services/preview/enterpriseknowledgegraphservice/2018-12-03/enterpriseknowledgegraphservice/client.go, services/preview/enterpriseknowledgegraphservice/2018-12-03/enterpriseknowledgegraphservice/enterpriseknowledgegraph.go, services/preview/enterpriseknowledgegraphservice/2018-12-03/enterpriseknowledgegraphservice/enterpriseknowledgegraphserviceapi/interfaces.go, services/preview/enterpriseknowledgegraphservice/2018-12-03/enterpriseknowledgegraphservice/operations.go, tools/major-updater/cmd/updateSDK.go, version/version.go
=> Update latest branch to sync master

LICENSE, README.md
I just cleaned up a few bits of formatting in the README.md, feel free to adopt these changes or drop them. I ignored the change log because no code was changed.
I also updated the licensing date in the Licence.md.
=> Cleaned up and formatted README.md

profiles/latest/containerservice/mgmt/containerservice/containerserviceapi/models.go, profiles/latest/containerservice/mgmt/containerservice/models.go, profiles/preview/containerservice/mgmt/containerservice/containerserviceapi/models.go, profiles/preview/containerservice/mgmt/containerservice/models.go
=> Regenerated profiles

Gopkg.lock, Gopkg.toml, swagger_to_sdk_config.json
=> update go-autorest and code generator to latest versions

README.md
=> Refine README to include version requirement of go-autorest

profiles/latest/compute/mgmt/compute/computeapi/models.go, profiles/latest/compute/mgmt/compute/models.go, profiles/preview/compute/mgmt/compute/computeapi/models.go, profiles/preview/compute/mgmt/compute/models.go
=> Refresh profiles

eng/pipelines/templates/steps/build-test.yml, sdk/azidentity/bearer_token_policy.go, sdk/storage/blob/2019-07-07/azblob/appendblob.go, sdk/storage/blob/2019-07-07/azblob/blob.go, sdk/storage/blob/2019-07-07/azblob/blockblob.go, sdk/storage/blob/2019-07-07/azblob/client.go, sdk/storage/blob/2019-07-07/azblob/container.go, sdk/storage/blob/2019-07-07/azblob/directory.go, sdk/storage/blob/2019-07-07/azblob/examples_test.go, sdk/storage/blob/2019-07-07/azblob/go.mod, sdk/storage/blob/2019-07-07/azblob/go.sum, sdk/storage/blob/2019-07-07/azblob/models.go, sdk/storage/blob/2019-07-07/azblob/pageblob.go, sdk/storage/blob/2019-07-07/azblob/policy_shared_key_credential.go, sdk/storage/blob/2019-07-07/azblob/service.go
This PR adds:
- updated generated code for azblob, including a hand-written client that accepts credential types for authentication
- samples for several valuable blob storage scenarios that cover:  creating/deleting containers, creating/deleting block blobs, creating/deleting/updating append blobs
=> Adding initial Storage Samples for azblob 

sdk/storage/blob/2019-07-07/azblob/examples_test.go
Add support for shared key authorization.
Added example for listing containers.
Fixed append blob creation.
Updated blob listing for both blobs.
=> More updates to storage examples

swagger_to_sdk_config.json
=> Update autorest.go version

sdk/azidentity/aad_identity_client_test.go, sdk/azidentity/azidentity.go, sdk/azidentity/azidentity_test.go
=> Adding KnownAuthorities to Azure Identity

CHANGELOG.md, services/databricks/mgmt/2018-04-01/databricks/models.go, services/databricks/mgmt/2018-04-01/databricks/workspaces.go, version/version.go
=> Minor release v42.1.0

.github/sla.yml
=> Update SLA bot config

.github/PULL_REQUEST_TEMPLATE.md
=> update PR template since we are not using the latest branch

CONTRIBUTING.md
=> Update contributing.md since we are not using the latest branch

sdk/arm/network/2020-03-01/armnetwork/models.go
=> Updated codegen with latest generator

sdk/arm/resources/2019-05-01/armresources/example_test.go, sdk/arm/resources/2019-05-01/armresources/go.mod, sdk/arm/resources/2019-05-01/armresources/go.sum
This PR includes: 
- Sample to create a resource group
- Sample for deleting a resource group that shows manual polling usage
=> Adding resources samples

sdk/arm/network/2020-03-01/armnetwork/example_config.go, sdk/arm/network/2020-03-01/armnetwork/example_networkinterfaces_test.go
This PR includes:
- Sample for creating a Network Interface that also gets a subnet and IP that exist in Azure
- Sample for getting a Network Interface
- Sample for deleting a Network Interface
=> Adding Network interface samples

sdk/azidentity/aad_identity_client.go, sdk/azidentity/azidentity_test.go, sdk/azidentity/azure_cli_credential.go, sdk/azidentity/bearer_token_policy_test.go, sdk/azidentity/device_code_credential_test.go, sdk/azidentity/fingerprint.go, sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential.go
Adding fixes for linting errors shown from golangci-lint.
=> Adding golangci-lint fixes

sdk/azcore/credential.go, sdk/azcore/go.mod, sdk/azcore/go.sum, sdk/azcore/policy_body_download.go, sdk/azcore/policy_body_download_test.go, sdk/azcore/policy_retry_test.go, sdk/azcore/request.go
Fixed a bug in body download policy.
Added a missing comment on an exported field.
=> Add a few more tests to azcore

sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go
=> Adding check for ClientID env var in msi credential

README.md
..and added link to Issue that led to this PR (https://github.com/Azure/azure-sdk-for-go/issues/10814)
=> Add mention for auth.NewAuthorizerFromCLIWithResource() to README

eng/pipelines/templates/jobs/archetype-sdk-client.yml, sdk/ci.yml
Refactor reference to azure-sdk-tools to latest released ref / enable auto-update of refs.
=> Pull from latest resource ref

sdk/to/to_test.go
=> Add tests for to module

sdk/armcore/ci.yml, sdk/azcore/ci.yml, sdk/internal/ci.yml, sdk/to/ci.yml
Title describes.
Build definitions are present, so we should get checks firing on this one.
=> Correct archetype-sdk-client from service level ci.yml

sdk/azcore/go.mod, sdk/azcore/go.sum, sdk/azcore/response_test.go
Includes updated dependency on internal module to fix race condition.
=> Fix flaky tests in azcore

sdk/azidentity/ci.yml
=> add ci.yml for azidentity

sdk/ci.yml
=> only trigger for track2 branch

sdk/internal/mock/mock.go, sdk/internal/mock/mock_test.go
Allows for dynamic responses based on a request predicate.
See documentation for more details.
=> Added mock.WithPredicate ResponseOption

sdk/armcore/ci.yml, sdk/azcore/ci.yml, sdk/azidentity/ci.yml, sdk/internal/ci.yml, sdk/to/ci.yml
This PR adjusts the headers in a lot of files, we are getting rid of the misleading comment and instead adding a link to a (yet to be created aka.ms link).
=> Adjust CI YAML headers

sdk/armcore/go.mod, sdk/armcore/go.sum, sdk/armcore/policy_register_rp.go, sdk/armcore/policy_register_rp_test.go
Set Attempts to zero to disable the policy and added a test for it.
=> RPRegistrationPolicy improvements

tools/apidiff/cmd/changelog.go, tools/apidiff/report/markdown.go, tools/apidiff/report/markdown_test.go
=> Fix some format issues in apidiff changelog command

sdk/armcore/poller.go
=> fix linter issues (no functional changes)

README.md, SECURITY.md, eng/pipelines/templates/steps/analyze.yml, services/classic/management/README.md, storage/README.md
The PR is to turn on the link check flag.
1. Disable the relative links.
2. Remove locale "en-us" from link.
=> Replaced relative link with absolute links and remove locale

sdk/azcore/error.go, sdk/azcore/log.go, sdk/azcore/log_test.go, sdk/azcore/policy_logging.go, sdk/azcore/policy_logging_test.go, sdk/azcore/policy_retry.go, sdk/azcore/version.go
Removed LogError and LogSlowResponse.
Renamed options in RequestLogOptions.
Updated NewRequestLogPolicy() to follow standard pattern for options.
Refactored requestLogPolicy.Do() per above changes.
Added missing slow response test.
Cleaned up/added logging in retry policy.
=> Logging refactor

sdk/armcore/go.mod, sdk/armcore/go.sum, sdk/armcore/policy_register_rp.go, sdk/armcore/poller_test.go
=> update based on azcore logging changes

sdk/azidentity/environment_credential.go, sdk/azidentity/environment_credential_test.go
This PR updates environment credential to include clientCertificateCredential and usernamePasswordCredential.
=> Update environment credential

sdk/azidentity/aad_identity_client.go, sdk/azidentity/default_azure_credential.go, sdk/azidentity/go.mod, sdk/azidentity/go.sum, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/interactive_browser_credential_test.go, sdk/azidentity/interactive_browser_server.go
This PR adds interactive browser credential along with its tests to azidentity
=> Adding interactive browser credential to azidentity

sdk/azidentity/aad_identity_client.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/device_code_credential_test.go
This PR updates DeviceCodeCredential to have only optional parameters. 
Fixes #11877
=> Update DeviceCodeCredential parameters

sdk/armcore/go.mod, sdk/armcore/go.sum, sdk/armcore/policy_register_rp.go, sdk/armcore/poller_test.go
=> Update armcore with latest azcore

sdk/azidentity/authorization_code_credential.go, sdk/azidentity/authorization_code_credential_test.go
This PR adds AuthorizationCodeCredential along with its tests.
=> Add AuthorizationCodeCredential

sdk/azidentity/azidentity.go, sdk/azidentity/azure_cli_credential_test.go, sdk/azidentity/bearer_token_policy_test.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/device_code_credential_test.go, sdk/azidentity/go.mod, sdk/azidentity/go.sum, sdk/azidentity/managed_identity_credential_test.go, sdk/azidentity/username_password_credential_test.go
Fixed logging policy name.
Fixed default telemetry params.
Removed unique request ID policy.
Consolidated pipeline creation for tests.
=> Update to latest azcore

sdk/azcore/README.md, sdk/azcore/core.go, sdk/azcore/doc.go, sdk/azcore/example_test.go, sdk/azcore/log.go, sdk/azcore/transport_default_http_client.go, sdk/azcore/version.go
=> Azcore docs

sdk/azcore/doc.go
=> fixed doc formatting issue

sdk/azidentity/managed_identity_client.go, sdk/azidentity/managed_identity_credential_test.go
This PR provides the necessary additions to support Azure Arc server managed identity environments.
=> Add Azure Arc managed identity environment

sdk/azidentity/azidentity.go
=> Include inner error message when available

sdk/azidentity/README.md
=> Add status badges to README.md

sdk/azcore/policy_retry.go
Clarified operation being tried and when it ends.
Added missing log entries when aborting due to context error.
=> Improvement in retry policy logging

sdk/samples/ci.yml
=> Adding ci for samples dir

eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml, eng/pipelines/templates/steps/build.yml, sdk/samples/azidentity/example_SDKV1_test.go, sdk/samples/ci.yml
Add scripts that only build and vet for samples.
=> Adding CI scripts for samples

sdk/azidentity/aad_identity_client.go, sdk/azidentity/authorization_code_credential.go, sdk/azidentity/authorization_code_credential_test.go, sdk/azidentity/azidentity.go, sdk/azidentity/azidentity_test.go, sdk/azidentity/bearer_token_policy_test.go, sdk/azidentity/chained_token_credential_test.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/device_code_credential_test.go, sdk/azidentity/environment_credential.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/interactive_browser_credential_test.go, sdk/azidentity/username_password_credential.go, sdk/azidentity/username_password_credential_test.go
Flatten all credential options into the main credential options structs. Addresses: #13014
=> Flatten credential options

sdk/azidentity/authorization_code_credential.go, sdk/azidentity/azidentity.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/username_password_credential.go
Updating tenantID validation error message and updating client certificate path parameter name. Fixes #13014
=> Addressing consistency review feedback

sdk/azcore/policy_telemetry.go, sdk/azcore/policy_telemetry_test.go, sdk/azcore/request.go
Updated telemetry policy to check for telemetry data in options bag.
=> Add Telemetry() method to Request

generate_options.json, initScript.sh, swagger_to_sdk_config.json
=> Config files update for SDK automation pipeline

sdk/arm/compute/ci.yml, sdk/arm/keyvault/ci.yml, sdk/arm/network/ci.yml, sdk/arm/resources/ci.yml, sdk/arm/storage/ci.yml
Adding ci.yml for upcoming track2 ARM modules:
- keyvault
- storage
- network
- compute
- resources
=> Adding CI yamls for track2 ARM modules

sdk/arm/compute/ci.yml, sdk/arm/keyvault/ci.yml, sdk/arm/network/ci.yml, sdk/arm/resources/ci.yml, sdk/arm/storage/ci.yml
=> fix path to eng directory

tools/generator/autorest/package.go
This is only a workaround for the current failures, not the real fix.
=> quick fix for generator

sdk/armcore/connection.go
=> Add logging options to ConnectionOptions

sdk/azidentity/authorization_code_credential.go, sdk/azidentity/azidentity.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/environment_credential.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/username_password_credential.go
=> Add logging options to all option types

sdk/azidentity/aad_identity_client.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/client_secret_credential_test.go, sdk/azidentity/jwt.go
=> azidentity: Adding SubjectName/Issuer support

sdk/azidentity/client_certificate_credential.go, sdk/azidentity/doc.go
=> azidentity: Adding doc.go

tools/apidiff/exports/exports.go, tools/apidiff/exports/package.go, tools/internal/modinfo/modinfo.go
=> Exclude tests when parsing packages

tools/apidiff/exports/exports.go
This PR adds necessary updates so that the content can be generated correctly for libraries, such as azcore, azidentity, armcore, etc. It has been tested with the previously mentioned modules.
=> APIDIFF: Fixing bugs in content generation

generate_options.json
=> Fix the autorest.go version in SDK automation pipeline

sdk/armcore/connection.go, sdk/armcore/connection_test.go, sdk/armcore/go.mod, sdk/armcore/go.sum, sdk/armcore/policy_register_rp.go, sdk/armcore/policy_register_rp_test.go
=> Armcore defaults

tools/generator/autorest/changelog.go, tools/generator/autorest/generationMetadata.go, tools/generator/cmd/root.go
=> [Generator] fix changelog generation error

tools/generator/cmd/clean.go, tools/generator/cmd/root.go
=> [SDK Automation] fix clean up packages

sdk/azidentity/authorization_code_credential.go, sdk/azidentity/azure_cli_credential.go, sdk/azidentity/client_certificate_credential.go, sdk/azidentity/client_secret_credential.go, sdk/azidentity/device_code_credential.go, sdk/azidentity/doc.go, sdk/azidentity/environment_credential.go, sdk/azidentity/interactive_browser_credential.go, sdk/azidentity/managed_identity_credential.go, sdk/azidentity/username_password_credential.go
=> Azidentity doc updates

tools/apidiff/cmd/diff.go, tools/apidiff/markdown/markdown.go, tools/apidiff/markdown/markdown_test.go, tools/apidiff/report/package.go, tools/apidiff/report/packages.go
Updating the apidiff tool to use track2 format.
=> Updating apidiff tool to use track2 format

eng/pipelines/templates/steps/analyze.yml
=> Fix linting and add extra debug spew

eng/pipelines/templates/steps/analyze.yml
=> fix working dir for analyze steps

eng/pipelines/templates/steps/analyze.yml
=> fix working dir again and remove extra slash

eng/pipelines/templates/steps/analyze.yml
=> fix incorrect paths for analyze tasks

sdk/arm/keyvault/2019-09-01/armkeyvault/CHANGELOG.md, sdk/arm/keyvault/2019-09-01/armkeyvault/go.mod, sdk/arm/keyvault/2019-09-01/armkeyvault/go.sum, sdk/arm/keyvault/2019-09-01/armkeyvault/zz_generated_connection.go, sdk/arm/keyvault/2019-09-01/armkeyvault/zz_generated_enums.go, sdk/arm/keyvault/2019-09-01/armkeyvault/zz_generated_keys.go, sdk/arm/keyvault/2019-09-01/armkeyvault/zz_generated_models.go, sdk/arm/keyvault/2019-09-01/armkeyvault/zz_generated_operations.go, sdk/arm/keyvault/2019-09-01/armkeyvault/zz_generated_privateendpointconnections.go, sdk/arm/keyvault/2019-09-01/armkeyvault/zz_generated_privatelinkresources.go, sdk/arm/keyvault/2019-09-01/armkeyvault/zz_generated_vaults.go
=> update armkeyvault with latest codegen and swagger

sdk/arm/resources/2020-06-01/armresources/CHANGELOG.md, sdk/arm/resources/2020-06-01/armresources/go.mod, sdk/arm/resources/2020-06-01/armresources/go.sum, sdk/arm/resources/2020-06-01/armresources/zz_generated_connection.go, sdk/arm/resources/2020-06-01/armresources/zz_generated_deploymentoperations.go, sdk/arm/resources/2020-06-01/armresources/zz_generated_deployments.go, sdk/arm/resources/2020-06-01/armresources/zz_generated_enums.go, sdk/arm/resources/2020-06-01/armresources/zz_generated_models.go, sdk/arm/resources/2020-06-01/armresources/zz_generated_operations.go, sdk/arm/resources/2020-06-01/armresources/zz_generated_providers.go, sdk/arm/resources/2020-06-01/armresources/zz_generated_resourcegroups.go, sdk/arm/resources/2020-06-01/armresources/zz_generated_resources.go, sdk/arm/resources/2020-06-01/armresources/zz_generated_tags.go
=> update armresources with latest codegen and swagger

sdk/arm/storage/2019-06-01/armstorage/CHANGELOG.md, sdk/arm/storage/2019-06-01/armstorage/go.mod, sdk/arm/storage/2019-06-01/armstorage/go.sum, sdk/arm/storage/2019-06-01/armstorage/zz_generated_blobcontainers.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_blobservices.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_connection.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_encryptionscopes.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_enums.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_fileservices.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_fileshares.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_managementpolicies.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_models.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_objectreplicationpolicies.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_operations.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_privateendpointconnections.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_privatelinkresources.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_queue.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_queueservices.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_skus.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_storageaccounts.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_table.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_tableservices.go, sdk/arm/storage/2019-06-01/armstorage/zz_generated_usages.go
=> update armstorage with latest codegen and swagger

tools/generator/cmd/root.go
=> update the error handling in generator

tools/apidiff/cmd/changelog.go, tools/apidiff/cmd/diff.go
Update APIDIFF changelog command to output track2 format and revert diff command changes.
=> Update APIDIFF changelog command

sdk/storage/azblob/zc_service_codes_common.go, sdk/storage/azblob/zc_storage_error.go, sdk/storage/azblob/zt_blob_client_test.go, sdk/storage/azblob/zt_blob_tags_test.go, sdk/storage/azblob/zt_examples_test.go, sdk/storage/azblob/zt_highlevel_test.go, sdk/storage/azblob/zt_sas_blob_snapshot_test.go, sdk/storage/azblob/zt_service_client_test.go, sdk/storage/azblob/zt_user_delegation_sas_test.go
All TODOs taken care of.  Finished test cases writing except list related tests.
Pending Items 
- Listing API Changes
- Retry Policy (`zc_policy_retry.go` tells the pipeline what kind of retry policy to use)
- NewUniqueRequestIDPolicyFactory (`zc_policy_unique_request_id.go`, creates a UniqueRequestIDPolicyFactory object hat sets the request's x-ms-client-request-id header if it doesn't already exist.)
=> All TODOs taken care of.

sdk/azcore/core.go
=> Add Pager and Poller interfaces to azcore

sdk/to/to.go, sdk/to/to_test.go
=> Add helper for time.Time

services/preview/cosmos-db/mgmt/2020-09-01-preview/documentdb/CHANGELOG.md, services/preview/cosmos-db/mgmt/2020-09-01-preview/documentdb/documentdbapi/interfaces.go, services/preview/cosmos-db/mgmt/2020-09-01-preview/documentdb/models.go, services/preview/cosmos-db/mgmt/2020-09-01-preview/documentdb/version.go
=> fix generation metadata in cosmos-db/2020-09-01-preview

eng/pipelines/templates/steps/analyze.yml
Add call to `eng-common-workflow-enforcer.yml`. Makes sure all eng/common changes follow the [eng/common workflow](https://github.com/Azure/azure-sdk-tools/blob/master/doc/common/common_engsys.md#workflow)
=> add eng/common workflow enforcer

tools/apidiff/report/report.go
Update the generator to apply the changes from #14164 
=> [SDK automation] update the changelog's header format in generator

sdk/azidentity/aad_identity_client.go, sdk/azidentity/azidentity.go, sdk/azidentity/client_certificate_credential_test.go, sdk/azidentity/interactive_browser_credential.go
=> Adding ADFS support

sdk/to/to.go, sdk/to/to_test.go
=> Add helpers for arrays

tools/generator/autorest/autorest.go, tools/generator/autorest/changelog.go, tools/generator/autorest/format.go, tools/generator/autorest/generationMetadata.go, tools/generator/autorest/generationMetadata_test.go, tools/generator/autorest/metadata.go, tools/generator/autorest/model/changelog.go, tools/generator/autorest/model/metadata.go, tools/generator/autorest/model/option.go, tools/generator/autorest/model/options.go, tools/generator/cmd/clean.go, tools/generator/cmd/generation.go, tools/generator/cmd/metadata.go, tools/generator/cmd/root.go, tools/generator/main.go, tools/generator/pipeline/io.go, tools/generator/pipeline/model.go, tools/generator/utils/listPackages.go, tools/generator/utils/listPackages_test.go, tools/generator/utils/path.go, tools/generator/utils/testdata/nottrack1package/version.go, tools/generator/utils/testdata/track1package/track1packageapi/interfaces.go, tools/generator/utils/testdata/track1package/version.go, tools/generator/validate/validation.go, tools/pkgchk/packages/packages.go, tools/pkgchk/packages/verifiers.go, tools/pkgchk/track1/packages.go, tools/pkgchk/track1/packages_test.go, tools/pkgchk/track1/verifiers.go
=> Add some missing headers in `tools` directory

tools/generator/autorest/generationMetadata.go
=> Fix regression after introducing metadata

sdk/storage/azblob/zc_blobClient.go, sdk/storage/azblob/zc_containerClient.go, sdk/storage/azblob/zc_leaseClient.go, sdk/storage/azblob/zc_leaseRequestOptions.go, sdk/storage/azblob/zc_serviceClient.go, sdk/storage/azblob/zt_examples_test.go, sdk/storage/azblob/zt_lease_client_test.go
=> ArchBoard Review - 2

sdk/azcore/response.go, sdk/azcore/response_test.go
=> add helper method for service error unmarshal failures

services/kusto/mgmt/2021-01-01/kusto/CHANGELOG.md, services/kusto/mgmt/2021-01-01/kusto/_meta.json, services/preview/confidentialledger/mgmt/2020-12-01-preview/confidentialledger/CHANGELOG.md, services/preview/confidentialledger/mgmt/2020-12-01-preview/confidentialledger/_meta.json, services/preview/iothub/mgmt/2021-03-03-preview/devices/CHANGELOG.md, services/preview/iothub/mgmt/2021-03-03-preview/devices/_meta.json, services/preview/securityinsight/mgmt/2019-01-01-preview/securityinsight/CHANGELOG.md, services/preview/securityinsight/mgmt/2019-01-01-preview/securityinsight/_meta.json, services/preview/webpubsub/mgmt/2021-04-01-preview/webpubsub/CHANGELOG.md, services/preview/webpubsub/mgmt/2021-04-01-preview/webpubsub/_meta.json
=> Adding metadata for v53.4.0 packages

sdk/azidentity/interactive_browser_server.go
Simplify the callback handling in the auth code flow. Also add a missing failed page if the the "code" is missing.
=> azidentity: simplify auth_code flow cb code

sdk/azcore/response.go, sdk/azcore/response_test.go, sdk/azcore/version.go
Fixed up version.go to match impending release.
=> Remove extra * in UnmarshalAsByteArray()

sdk/azcore/core.go
Most minor PR to adjust two comments, for completeness.
=> adjust comment for completeness

sdk/synapse/azartifacts/go_mod_tidy_hack.go
=> Carve out azartifacts module

sdk/azidentity/LICENSE.txt, sdk/azidentity/version.go
Bump version info to match latest release.
=> Add license file to azidentity

sdk/network/armnetwork/LICENSE.txt
=> add license for network track 2 modules

sdk/compute/armcompute/LICENSE.txt
=> add license for compute track 2 module

sdk/resources/armresources/LICENSE.txt
=> add license for resources track 2 module

sdk/storage/armstorage/LICENSE.txt, sdk/storage/armstorage/README.md
=> add license for storage track 2 module

sdk/storage/armstorage/go.mod, sdk/storage/armstorage/go.sum
=> go mod tidy for storage track 2 module

tools/apidiff/go.sum, tools/generator/go.sum, tools/pkgchk/go.sum, tools/profileBuilder/go.sum
=> refresh dependencies in each tools

swagger_to_sdk_config.json
=> enable breaking change tracking

sdk/agfood/armagfood/LICENSE.txt, sdk/agfood/armagfood/ci.yml
This PR creates the agfood module
Release request: https://github.com/Azure/sdk-release-request/issues/1528
=> initial release of agfood track 2 module

sdk/compute/armcompute/go.mod, sdk/compute/armcompute/go.sum, sdk/compute/armcompute/go_mod_tidy_hack.go, sdk/keyvault/armkeyvault/go.mod, sdk/keyvault/armkeyvault/go.sum, sdk/keyvault/armkeyvault/go_mod_tidy_hack.go, sdk/network/armnetwork/go.mod, sdk/network/armnetwork/go.sum, sdk/network/armnetwork/go_mod_tidy_hack.go, sdk/resources/armresources/go.mod, sdk/resources/armresources/go.sum, sdk/resources/armresources/go_mod_tidy_hack.go, sdk/storage/armstorage/go.mod, sdk/storage/armstorage/go.sum, sdk/storage/armstorage/go_mod_tidy_hack.go, sdk/synapse/azartifacts/go.mod, sdk/synapse/azartifacts/go.sum
=> add mod tidy hack to all the service packages

sdk/authorization/armauthorization/LICENSE.txt, sdk/authorization/armauthorization/ci.yml, sdk/containerservice/armcontainerservice/LICENSE.txt, sdk/containerservice/armcontainerservice/ci.yml, sdk/monitor/armmonitor/LICENSE.txt, sdk/monitor/armmonitor/ci.yml, sdk/privatedns/armprivatedns/LICENSE.txt, sdk/privatedns/armprivatedns/ci.yml
=> introduce 4 new rps

sdk/armcore/connection.go
=> fix spelling of Resourece to Resource

sdk/azidentity/README.md
=> fix link in README of `azidentity`

azure-pipelines.yml, tools/generator/autorest/model/options_test.go, tools/generator/autorest/validate.go, tools/generator/ci.yml
=> Introduce CI for tools/generator

sdk/azcore/response.go
=> Fix logging message when content type is empty

sdk/azcore/credential.go, sdk/azcore/version.go
Necessary for multi-tenant auth scenarios.
=> Add tenantID on TokenRequestOptions

sdk/azidentity/version.go
=> azidentity: update version.go

.github/CODEOWNERS, CODEOWNERS, NOTICE, NOTICE.txt
=> Update CodeOwners and Notice.txt

sdk/containerregistry/armcontainerregistry/LICENSE.txt, sdk/containerregistry/armcontainerregistry/ci.yml
=> onboard track2: containerregistry

eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml, eng/pipelines/templates/jobs/archetype-sdk-client.yml
Update Ubuntu VM image from 18 to 20
=> Update Ubuntu 18 to 20

sdk/azidentity/managed_identity_credential.go, sdk/azidentity/managed_identity_credential_test.go
=> azidentity: Add environment variable for resource ID

sdk/web/armweb/LICENSE.txt, sdk/web/armweb/ci.yml
=> web track 2 module onboarding

sdk/sql/armsql/LICENSE.txt, sdk/sql/armsql/ci.yml
=> Add sql ci.yml and LICENSE.txt file track2

.github/CODEOWNERS
=> update the code owner to include renhe

sdk/tables/aztable/table_client.go, sdk/tables/aztable/table_service_client.go, sdk/tables/aztable/table_service_client_test.go, sdk/tables/aztable/zt_table_recorded_tests.go
=> [Tables] Adding Table suffix to Create, Delete, and List methods

eng/scripts/build.ps1
@benbp - Is there a better way of doing this?
=> [build.ps1] Early return error if autorest fails

tools/generator/autorest/changelog.go, tools/generator/autorest/generation.go, tools/generator/autorest/model/changelog.go, tools/generator/cmd/automation/automationCmd.go, tools/generator/cmd/automation/pipeline/model.go, tools/generator/cmd/issue/issueCmd.go, tools/generator/cmd/issue/link/common.go, tools/generator/cmd/root.go, tools/generator/cmd/template/templateCmd.go, tools/generator/template/rpName/packageName/CHANGELOG.md.tpl, tools/generator/template/rpName/packageName/LICENSE.txt.tpl, tools/generator/template/rpName/packageName/README.md.tpl, tools/generator/template/rpName/packageName/autorest.md.tpl, tools/generator/template/rpName/packageName/build.go.tpl, tools/generator/template/rpName/packageName/ci.yml.tpl, tools/generator/template/rpName/packageName/go.mod.tpl, tools/generator/template/rpName/packageName/go_mod_tidy_hack.go.tpl
=> [tools/generator] add the template command

tools/generator/autorest/changelog.go, tools/generator/template/rpName/packageName/README.md.tpl
=> fix typo in template

sdk/cosmos/azcosmos/cosmos_client.go, sdk/cosmos/azcosmos/cosmos_client_connection.go, sdk/cosmos/azcosmos/cosmos_client_connection_test.go, sdk/cosmos/azcosmos/cosmos_client_options_test.go, sdk/cosmos/azcosmos/cosmos_container.go, sdk/cosmos/azcosmos/cosmos_container_properties.go, sdk/cosmos/azcosmos/cosmos_container_properties_test.go, sdk/cosmos/azcosmos/cosmos_container_response.go, sdk/cosmos/azcosmos/cosmos_container_response_test.go, sdk/cosmos/azcosmos/cosmos_database.go, sdk/cosmos/azcosmos/cosmos_database_properties.go, sdk/cosmos/azcosmos/cosmos_database_properties_test.go, sdk/cosmos/azcosmos/cosmos_database_response.go, sdk/cosmos/azcosmos/cosmos_database_response_test.go, sdk/cosmos/azcosmos/cosmos_headers.go, sdk/cosmos/azcosmos/cosmos_paths.go, sdk/cosmos/azcosmos/cosmos_response.go, sdk/cosmos/azcosmos/go.mod, sdk/cosmos/azcosmos/partition_key_definition.go, sdk/cosmos/azcosmos/partition_key_definition_version.go, sdk/cosmos/azcosmos/resource_throttle_retry_policy.go, sdk/cosmos/azcosmos/resource_throttle_retry_policy_test.go, sdk/cosmos/azcosmos/unixtime.go
Introduces:
* CosmosContainer
* CosmosDatabase
* CosmosContainerResponse & CosmosContainerProperties
* CosmosDatabaseResponse & CosmosDatabaseProperties
Closes #15223
=> Cosmos DB: Adding CosmosContainer and CosmosDatabase

sdk/cosmos/azcosmos/composite_index_order.go, sdk/cosmos/azcosmos/conflict_resolution_mode.go, sdk/cosmos/azcosmos/conflict_resolution_policy.go, sdk/cosmos/azcosmos/cosmos_container_properties.go, sdk/cosmos/azcosmos/cosmos_container_properties_test.go, sdk/cosmos/azcosmos/data_type.go, sdk/cosmos/azcosmos/indexing_mode.go, sdk/cosmos/azcosmos/indexing_policy.go, sdk/cosmos/azcosmos/spatial_type.go, sdk/cosmos/azcosmos/unique_key_policy.go
Extending Container Properties to include the extra missing policies
Closes https://github.com/Azure/azure-sdk-for-go/issues/15232
=> [Cosmos DB] Adding Indexing Policy, Unique Key Policy, and Conflict Resolution Policy

sdk/internal/errinfo/errinfo.go, sdk/internal/errorinfo/errorinfo.go
=> Add errinfo package with error types

sdk/storage/azblob/recordings/Test/TestCopyBlobWithRehydratePriority-variables.yaml, sdk/storage/azblob/recordings/Test/TestCopyBlobWithRehydratePriority.yaml, sdk/storage/azblob/recordings/Test/TestRehydrateStatus-variables.yaml, sdk/storage/azblob/recordings/Test/TestRehydrateStatus.yaml, sdk/storage/azblob/recordings/Test/TestSetStandardBlobTierWithRehydratePriority-variables.yaml, sdk/storage/azblob/recordings/Test/TestSetStandardBlobTierWithRehydratePriority.yaml, sdk/storage/azblob/zt_block_blob_client_test.go, sdk/storage/azblob/zt_test.go
=> Tiers & Rehydrate Priority

documentation/new-version-quickstart.md
=> Fixed bugs in Resource Group demo code

azure-pipelines.yml, tools/apidiff/ci.yml, tools/deprecate/ci.yml, tools/indexer/ci.yml, tools/internal/ci.yml, tools/pkgchk/ci.yml, tools/profileBuilder/ci.yml
=> introduce pipelines to the modules in tools directory

eng/scripts/build.ps1
=> upgrade build.ps1 autorest version 25->27

azure-pipelines.yml
=> Update Ubuntu vm image to version 20.04

tools/generator/template/rpName/packageName/autorest.md.tpl
=> add the lisence header to template

sdk/azcore/CHANGELOG.md, sdk/azcore/README.md, sdk/azcore/arm/doc.go, sdk/azcore/doc.go, sdk/azcore/log/doc.go, sdk/azcore/policy/doc.go, sdk/azcore/runtime/doc.go, sdk/azcore/runtime/policy_logging.go, sdk/azcore/streaming/doc.go, sdk/azcore/to/doc.go
Updates doc.go with latest azcore updates.
=> [azcore] updating doc.go

documentation/new-version-quickstart.md
=> udpate docs on the `github.com/Azure/azure-sdk-for-go/sdk/to` module

sdk/storage/azblob/README.md
=> Updated README.md

.github/CODEOWNERS
Remove jhendrixMSFT from all track 2 content.
=> Add /sdk/internal to CODEOWNERS

sdk/cosmos/azcosmos/async_cache_test.go, sdk/cosmos/azcosmos/cosmos_error_test.go, sdk/cosmos/azcosmos/cosmos_paths_test.go, sdk/cosmos/azcosmos/doc.go, sdk/cosmos/azcosmos/resource_type.go, sdk/cosmos/azcosmos/shared_key_credential.go, sdk/cosmos/azcosmos/throughput_properties.go, sdk/cosmos/azcosmos/throughput_response.go
Fixing linter errors that block main merge
=> Cosmos DB - Lint errors

tools/generator/cmd/v2/common/fileProcessor.go, tools/generator/template/rpName/packageName/README.md.tpl
=> fix: auto replacement of NewClient method corner case in release tool

sdk/storage/azblob/README.md, sdk/storage/azblob/doc.go, sdk/storage/azblob/highlevel.go, sdk/storage/azblob/swagger/README.md
=> Added doc.go and README.md

tools/generator/cmd/v2/common/generation.go, tools/generator/doc.go, tools/generator/repo/sdk.go
=> fix: path compatible for automation-v2

eng/scripts/Language-Settings.ps1
- Add group of tools required for runing prepare-release
=> Add Language Settings file 2

sdk/data/aztables/CHANGELOG.md, sdk/data/aztables/ci.yml, sdk/data/aztables/transactional_batch.go
=> [Tables] patch

sdk/data/aztables/CHANGELOG.md, sdk/data/aztables/proxy_test.go, sdk/data/aztables/service_client.go, sdk/data/aztables/zc_client_options.go
=> [Tables] Fix ClientOptions struct

sdk/data/azcosmos/README.md
Cosmos DB README.md for Go SDK
- [ X] The purpose of this PR is explained in this or a referenced issue.
- [X ] The PR does not update generated files.
- [ X] MIT license headers are included in each file.
=> Cosmos DB GO SDK README .md

sdk/postgresql/armpostgresqlflexibleservers/build.go
=> fix: wrong postgresql track2 build config

eng/scripts/automation_init.sh, eng/tools/apidiff/go.mod, eng/tools/apidiff/go.sum, eng/tools/generator/go.mod, eng/tools/generator/go.sum, eng/tools/pkgchk/go.mod, eng/tools/pkgchk/go.sum, eng/tools/profileBuilder/go.mod, eng/tools/profileBuilder/go.sum
=> fix: sdk automation path and generator tool mod

eng/tools/generator/cmd/automation/automationCmd.go
=> Quick fix for generator automation

eng/pipelines/templates/steps/build-test.yml, sdk/data/aztables/README.md
=> [Tables] fixing link

sdk/data/aztables/CHANGELOG.md
=> Fixing changelog

azure-pipelines.yml
=> Skip track 2 content in track 1 CI

eng/scripts/Language-Settings.ps1, eng/scripts/Update-ModuleVersion.ps1
Required for Azure/azure-sdk-tools#1542
=> Add ReplaceLatestEntryTitle parameter for updating changelog

sdk/data/aztables/CHANGELOG.md, sdk/data/aztables/go.mod, sdk/data/aztables/go.sum, sdk/data/aztables/internal/constants.go, sdk/data/aztables/service_client.go
Updating options to make sure end user option struct is not manipulated 
=> [Tables] updating options

sdk/data/azcosmos/cosmos_client.go, sdk/data/azcosmos/cosmos_container.go, sdk/data/azcosmos/cosmos_database.go, sdk/data/azcosmos/emulator_tests.go
Changing methods that return DatabaseClient and ContainerClient to return pointers.
=> [Cosmos DB] DatabaseClient and ContainerClient as pointers

sdk/data/aztables/proxy_test.go, sdk/data/aztables/service_client.go
=> [Tables] fixing SAS in ServiceClient.NewClient

sdk/storage/azblob/CHANGELOG.md, sdk/storage/azblob/zz_generated_constants.go
Updating module version and release date
=> Prepare azblob 0.2.0 release

sdk/data/aztables/CHANGELOG.md, sdk/data/aztables/client.go, sdk/data/aztables/client_test.go, sdk/data/aztables/internal/constants.go, sdk/data/aztables/testdata/recordings/TestContinuationTokens/TestContinuationTokens_cosmos.json, sdk/data/aztables/testdata/recordings/TestContinuationTokens/TestContinuationTokens_storage.json
=> [Tables] Adding ContinuationToken support

sdk/azidentity/environment_credential.go, sdk/azidentity/errors.go, sdk/azidentity/logging.go
Following comments on [apiview](https://apiview.dev/Assemblies/Review/6aabdad838aa46a2b1e0258cca0b7904).
=> Incorporate azidentity architecture review feedback

sdk/data/aztables/README.md, sdk/data/aztables/example_test.go
=> [Tables] Updating Documentation

sdk/keyvault/azsecrets/CHANGELOG.md, sdk/keyvault/azsecrets/client.go, sdk/keyvault/azsecrets/client_test.go, sdk/keyvault/azsecrets/go.mod, sdk/keyvault/azsecrets/go.sum, sdk/keyvault/azsecrets/internal/constants.go, sdk/keyvault/azsecrets/testdata/recordings/TestBackupSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestBeginRecoverDeletedSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestDeleteSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestListDeletedSecrets.json, sdk/keyvault/azsecrets/testdata/recordings/TestListSecretVersions.json, sdk/keyvault/azsecrets/testdata/recordings/TestListSecrets.json, sdk/keyvault/azsecrets/testdata/recordings/TestPurgeDeletedSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestSetGetSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestUpdateSecretProperties.json
* Update client authentication policy to use the `internal.NewKeyVaultChallengePolicy`
* Add recordings for new auth policy
=> [KeyVault] Update azsecrets authentication policy

sdk/data/azcosmos/ci.yml
Emulator CI stopped working complaining about GoWorkspace parameter
=> [Cosmos DB] Fix emulator CI

documentation/README.md, documentation/developer_setup.md, documentation/release.md
=> Update Developer Documentation

sdk/internal/CHANGELOG.md
Updating changelog to release latest changes to internal
=> Update CHANGELOG.md for release

sdk/internal/LICENSE.txt, sdk/internal/doc.go
=> add missing license file and update doc.go

sdk/resourcemanager/compute/armcompute/CHANGELOG.md, sdk/resourcemanager/compute/armcompute/autorest.md, sdk/resourcemanager/compute/armcompute/go.mod, sdk/resourcemanager/compute/armcompute/go.sum, sdk/resourcemanager/keyvault/armkeyvault/CHANGELOG.md, sdk/resourcemanager/keyvault/armkeyvault/autorest.md, sdk/resourcemanager/keyvault/armkeyvault/go.mod, sdk/resourcemanager/keyvault/armkeyvault/go.sum, sdk/resourcemanager/network/armnetwork/CHANGELOG.md, sdk/resourcemanager/network/armnetwork/autorest.md, sdk/resourcemanager/network/armnetwork/go.mod, sdk/resourcemanager/network/armnetwork/go.sum, sdk/resourcemanager/resources/armresources/CHANGELOG.md, sdk/resourcemanager/resources/armresources/autorest.md, sdk/resourcemanager/resources/armresources/go.mod, sdk/resourcemanager/resources/armresources/go.sum, sdk/resourcemanager/storage/armstorage/CHANGELOG.md, sdk/resourcemanager/storage/armstorage/autorest.md, sdk/resourcemanager/storage/armstorage/go.mod, sdk/resourcemanager/storage/armstorage/go.sum
=> refresh dependencies for ring 0 RPs with examples

sdk/data/aztables/README.md, sdk/data/aztables/client_test.go
Addresses customer reported issue #14750 . Adds a single test for running the Tables service against Azurite.
=> [Tables] Adding azurite test for Tables

sdk/messaging/azservicebus/README.md, sdk/messaging/azservicebus/admin/admin_client_subscription.go, sdk/messaging/azservicebus/admin/example_admin_client_test.go
A few minor fixes (mostly comments) I found while exploring Go SDK support for Service Bus.
=> Minor fixes

README.md
Cleanup the readme to give clarity between the New Releases vs Previous Releases
=> Readme cleanup for the New vs Previous

sdk/messaging/azservicebus/README.md, sdk/messaging/azservicebus/admin/doc.go, sdk/messaging/azservicebus/doc.go, sdk/messaging/azservicebus/example_client_test.go, sdk/messaging/azservicebus/example_receiver_test.go, sdk/messaging/azservicebus/example_sender_test.go
Readme had some out of date examples. Also enhancing the doc strings a bit.
=> [azservicebus] Fixing readme being out of date and other small doc changes

eng/tools/generator/template/rpName/packageName/CHANGELOG.md.tpl, eng/tools/generator/template/rpName/packageName/go.mod.tpl
=> chore: change generator tool template

sdk/messaging/azservicebus/README.md
Based off feedback from @mikekistler
=> [azservicebus] Updating readme with AAD/Service Principal related information

sdk/data/aztables/README.md
closes #16496 
* specify to login to az cli
* Added a section on authenticating with shared key that was missing
=> [Tables] Address Doc Bug Bash comments

eng/pipelines/templates/jobs/archetype-go-release.yml
=> ci: skip version pump for mgmt. plane sdk release

eng/tools/generator/cmd/automation/pipeline/model.go, eng/tools/generator/cmd/v2/automation/automationCmd.go, eng/tools/generator/cmd/v2/common/fileProcessor.go, eng/tools/generator/cmd/v2/common/generation.go
=> Change automation-v2 tool to be compatible with new codegen platform

eng/pipelines/templates/steps/analyze.yml
=> Disable the Dependency Check step until GA

sdk/keyvault/azsecrets/README.md, sdk/keyvault/azsecrets/client_test.go, sdk/keyvault/azsecrets/consts.go, sdk/keyvault/azsecrets/models.go, sdk/keyvault/azsecrets/testdata/recordings/TestUpdateSecretProperties.json
=> [Secrets] Doc BugBash Fixes

eng/tools/generator/autorest/model/changelog.go, eng/tools/generator/cmd/automation/automationCmd.go, eng/tools/generator/cmd/v2/automation/automationCmd.go, eng/tools/generator/cmd/v2/common/fileProcessor.go, eng/tools/generator/cmd/v2/common/generation.go
=> feat: enhance changelog format and fix some small bugs

CHANGELOG.md
=> [Changelog] Rename windowsesu path

documentation/MIGRATION_GUIDE.md, documentation/new-version-quickstart.md
Make the migration guide and quickstarts match the current code (they
weren't updated after the last refactor).
=> Update migration guide and quickstarts

sdk/azidentity/errors.go
=> Update AuthenticationFailedError after azcore refactor

README.md
Add trademark section to root readme
=> Add trademark section to root readme

sdk/resourcemanager/web/armweb/CHANGELOG.md, sdk/resourcemanager/web/armweb/autorest.md, sdk/resourcemanager/web/armweb/go.mod
=> Rename web to appservice

sdk/storage/azblob/highlevel.go
=> uncomment o.Progress(progress) in getDownloadBlobOptions()

eng/config.json, sdk/keyvault/azkeys/client_test.go
Fixes a broken live test for `azkeys`
=> [KeyVault] fixing broken live test

eng/generate_options.json
=> By pass the swagger validator to fix the issues in track 1 generation

sdk/azidentity/azidentity_test.go, sdk/azidentity/managed_identity_credential_test.go
=> Add offline test for Azure Arc managed identity

sdk/azcore/CHANGELOG.md
=> [Core] Update Changelog.md

eng/scripts/Invoke-MgmtTestgen.ps1, eng/scripts/build.ps1
=> chore: pump codegen version in scripts

sdk/keyvault/azkeys/go.mod, sdk/keyvault/azkeys/go.sum, sdk/keyvault/azsecrets/go.mod, sdk/keyvault/azsecrets/go.sum, sdk/keyvault/azsecrets/testdata/recordings/TestBackupSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestBeginRecoverDeletedSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestDeleteSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestListDeletedSecrets.json, sdk/keyvault/azsecrets/testdata/recordings/TestListSecretVersions.json, sdk/keyvault/azsecrets/testdata/recordings/TestListSecrets.json, sdk/keyvault/azsecrets/testdata/recordings/TestPurgeDeletedSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestSetGetSecret.json, sdk/keyvault/azsecrets/testdata/recordings/TestUpdateSecretProperties.json
Update go.mod for secrets and keys to reference just released keyvault/internal package.
=> [KeyVaul] updating to latest internal for keyvault

eng/scripts/Invoke-MgmtTestgen.ps1
=> chore: upgrade to latest @autorest/gotest

eng/tools/generator/cmd/v2/refresh/refreshCmd.go
=> feat: add rp filter to refresh-v2 tool

sdk/data/azcosmos/CHANGELOG.md, sdk/data/azcosmos/cosmos_client.go, sdk/data/azcosmos/cosmos_client_test.go, sdk/data/azcosmos/cosmos_container_response_test.go, sdk/data/azcosmos/cosmos_database_response_test.go, sdk/data/azcosmos/cosmos_error.go, sdk/data/azcosmos/cosmos_error_test.go, sdk/data/azcosmos/cosmos_headers_policy_test.go, sdk/data/azcosmos/cosmos_item_response_test.go, sdk/data/azcosmos/cosmos_offers.go, sdk/data/azcosmos/example_test.go, sdk/data/azcosmos/go.mod, sdk/data/azcosmos/go.sum, sdk/data/azcosmos/throughput_response_test.go, sdk/data/azcosmos/version.go
=> Update azcosmos with the latest azcore

sdk/azcore/policy/policy.go
=> clarify usage of ApplicationID

eng/scripts/build.ps1
=> fix: add go.clear-output-folder flag

services/storage/datalake/2019-10-31/storagedatalake/models.go
=> fix json model Path for Azure Data Lake Storage. Fix #16401

eng/scripts/build.ps1
=> chore: upgrade codegen version

eng/scripts/Invoke-MgmtTestgen.ps1
=> chore: update autorest core version

eng/scripts/Invoke-MgmtTestgen.ps1
=> chore: update codegen version in test script

sdk/azidentity/go.mod, sdk/azidentity/go.sum, sdk/azidentity/testdata/recordings/TestAuthorizationCodeCredential_ConfidentialInvalidCodeLive.json, sdk/azidentity/testdata/recordings/TestAuthorizationCodeCredential_ConfidentialLive.json, sdk/azidentity/testdata/recordings/TestAuthorizationCodeCredential_PublicInvalidCodeLive.json, sdk/azidentity/testdata/recordings/TestAuthorizationCodeCredential_PublicLive.json, sdk/azidentity/testdata/recordings/TestClientCertificateCredential_InvalidCertLive.json, sdk/azidentity/testdata/recordings/TestClientCertificateCredential_Live/PEM.json, sdk/azidentity/testdata/recordings/TestClientCertificateCredential_Live/PKCS12.json, sdk/azidentity/testdata/recordings/TestClientCertificateCredential_Live/SNI.json, sdk/azidentity/testdata/recordings/TestClientSecretCredential_InvalidSecretLive.json, sdk/azidentity/testdata/recordings/TestClientSecretCredential_Live.json, sdk/azidentity/testdata/recordings/TestDeviceCodeCredential_Live.json, sdk/azidentity/testdata/recordings/TestEnvironmentCredential_ClientSecretLive.json, sdk/azidentity/testdata/recordings/TestEnvironmentCredential_InvalidClientSecretLive.json, sdk/azidentity/testdata/recordings/TestEnvironmentCredential_InvalidPasswordLive.json, sdk/azidentity/testdata/recordings/TestEnvironmentCredential_UserPasswordLive.json, sdk/azidentity/testdata/recordings/TestManagedIdentityCredential_IMDSClientIDLive.json, sdk/azidentity/testdata/recordings/TestManagedIdentityCredential_IMDSLive.json, sdk/azidentity/testdata/recordings/TestManagedIdentityCredential_IMDSResourceIDLive.json, sdk/azidentity/testdata/recordings/TestUsernamePasswordCredential_InvalidPasswordLive.json, sdk/azidentity/testdata/recordings/TestUsernamePasswordCredential_Live.json
Upgrading `internal` and re-recording tests so playback works with the latest test proxy
=> Update azidentity recordings

sdk/messaging/azservicebus/internal/amqp_test_utils.go, sdk/messaging/azservicebus/internal/stress/tests/receive_cancellation.go, sdk/messaging/azservicebus/internal/stress/tests/tests.go, sdk/messaging/azservicebus/internal/stress/values.yaml, sdk/messaging/azservicebus/receiver.go, sdk/messaging/azservicebus/receiver_test.go
Fixing use of links when they haven't been initialized.
Partial fix for #16923
=> [azservicebus] Fixing panic() when the links haven't been initialized (early cancellation)

sdk/messaging/azservicebus/CHANGELOG.md
Fixes and PRs have come in, just updating the changelog to be current.
=> [azservicebus] Updating changelog to be more current.
