clients/storage/blob.go
needs to be merged as soon as possible for docker-registry integration. thanks.
cc: @hopetobelievein
=> fix block id length by zero padding

clients/storage/blob.go
This one has been bugging me for a while now... so while we're waiting for #19, I might as well get this in (or is this dependent upon the CLA as well?)
=> blob.go: more idiomatic and clearer 'for' loop

clients/storage/blob.go, clients/storage/blob_test.go
* changed BlockResponse.Size from uint64 to int64 for consistency
* added method to create an empty block blob
=> make block.Size int64, add CreateBlockBlob

azure/storage/client.go
Followup fix to #41 
cc: @jen20
=> storage: fix missing return err

README.md
=> Fix the package names in the README

management/hostedservice/client.go, management/http.go, management/osimage/client.go, management/osimage/entities.go, management/virtualmachine/client.go, management/virtualmachineimage/client.go, management/virtualmachineimage/entities.go
Making the distinction between https://msdn.microsoft.com/en-us/library/azure/dn499771.aspx and https://msdn.microsoft.com/en-us/library/azure/dn499771.aspx
=> Separate VM and OS images

management/storageservice/client.go, management/storageservice/entities.go, management/virtualmachine/client.go
AccountType property replaces GeoReplicationEnabled and SecondaryReadEnabled
=> Fix 'Create storage service'

management/virtualmachine/client.go, management/virtualmachine/entities.go, management/virtualmachine/entities_test.go, management/virtualmachinedisk/entities.go, management/virtualmachineimage/entities.go
Also cleaned up the code a bit. Preparing another PR for moving the utility methods to a different package.
=> Update virtual machine entities to latest spec

management/virtualmachinedisk/client.go
Also give async control to caller.
=> Make deleting blob data optional for vmdisk.DeleteDisk

management/hostedservice/client.go, management/vmutils/integration_test.go
Also give async control to caller
=> Make deleting media optional for hostedservice.DeleteHostedService

management/vmutils/examples_test.go, management/vmutils/integration_test.go, management/vmutils/vmutils.go, management/vmutils/vmutils_test.go
=> Fix: NewVmConfiguration never returns error

management/virtualmachine/client.go, management/virtualmachine/entities.go
=> Add virtualmachine.UpdateRole

management/virtualmachine/entities.go
=> Add types for RoleInstance.ResourceExtensionStatusList

management/hostedservice/client.go, management/http.go, management/operations.go, management/storageservice/client.go, management/virtualmachine/client.go, management/virtualmachinedisk/client.go, management/virtualmachineimage/client.go, management/virtualnetwork/client.go, management/vmutils/examples_test.go, management/vmutils/integration_test.go
@ahmetalpbalkan Is this what you meant before in a PR? (can't find the exact comment)
=> Introduce Azure OperationId type

management/vmutils/integration_test.go, management/vmutils/rolestate.go
Role operations were changed to async, so now have to waited on.
=> Fix integration_test

management/hostedservice/client.go
comp=media is added by func, depending on parameter
=> Fix DeleteHostedService

management/virtualmachine/client.go
This was giving "non-pointer passed to Unmarshal"
=> Fix bug in GetDeployment

management/storageservice/client.go
Sorry for having this wrong in the first place... :frowning:
=> Fix url for GetStorageServiceKeys

storage/blob.go, storage/blob_test.go
Removing various blob upload convenience methods that maintain some
internal logic that makes it hard to operate on these blobs afterwards.
I plan to refactor and move such methods to a `blobutil` package later
on. Fixes #71. 
review: @paulmey
=> Remove blob helper methods from storage package

management/http.go, management/networksecuritygroup/client.go, management/networksecuritygroup/entities.go
This needs just a little more testing, but first tests look good.
Of course this one is a little different as most other packages in this SDK, but personally I really like this approach which also use a more Go like style…
=> Add support for network security groups

management/hostedservice/client.go
=> Remove client-side logic from CreateHostedService

management/client.go, management/operations.go, management/publishSettings.go
Fixes #89.
Also made some code cleanup to have 1 path for default
config initialization.
Signed-off-by: Ahmet Alp Balkan
cc: @paulmey
=> Configurable operation polling intervals

management/storageservice/client.go
Renamed storage.IsAvailable to `CheckStorageAccountNameAvailability`.
(Fixes #94) Also fixed the method signature by returning the right
response struct type.
Signed-off-by: Ahmet Alp Balkan <ahmetalpbalkan@gmail.com>
cc: @paulmey
=> management/storage: Refactor IsAvailable

management/client.go, management/hostedservice/client.go, management/hostedservice/entities.go, management/location/client.go, management/location/entities.go, management/networksecuritygroup/client.go, management/networksecuritygroup/entities.go, management/osimage/client.go, management/osimage/entities.go, management/storageservice/client.go, management/storageservice/entities.go, management/virtualmachine/client.go, management/virtualmachine/entities.go, management/virtualmachinedisk/client.go, management/virtualmachinedisk/entities.go, management/virtualmachineimage/client.go, management/virtualmachineimage/entities.go, management/virtualnetwork/client.go, management/virtualnetwork/entities.go, management/vmutils/vmutils.go, storage/client.go
Consistent and precise godoc comments for packages.
=> Godoc fixes for packages

management/osimage/client.go, management/osimage/entities.go, management/vmutils/integration_test.go
More work for unifying the method signatures and eliminating
client side client logic.
cc: @paulmey pls review&merge
=> management/osimage: Fix inconsistencies

management/virtualmachineimage/client.go, management/virtualmachineimage/entities.go, management/vmutils/integration_test.go
More work for unifying the method signatures and eliminating
client side client logic.
cc: @paulmey pls review&merge
=> mgmt/virtualmachineimage: Fix inconsistencies

management/vmutils/deployment.go, management/vmutils/integration_test.go, management/vmutils/vmutils_test.go
I know this would probably go into an option struct, but I think that should be another refactor. So for now just added a `bool`.
And while touching this file I also made it’s 100+ lines a little shorter which makes reviewing on GH a lot nicer.
=> Make installing the guest agent configurable for VMImages

management/location/client.go, management/location/entities.go, management/vmutils/integration_test.go, management/vmutils/rolesize.go
- Removed client side logic from `management/location`
- Renamed return structs to reflect operations better
- Moved helpers to where they are needed
cc: @paulmey
=> management/location: Refactoring

management/client.go, management/errors.go, management/http.go
=> Cleanup in AzureError struct

management/hostedservice/client.go, management/hostedservice/entities.go
=> Fix typo in ListHostedServiceResponse

management/storageservice/client.go, management/storageservice/entities.go, management/vmutils/integration_test.go
Fixed method signature and struct name inconsistencies in `management/storageservice`
package.
=> management/storageservice: Fix inconsistencies

management/http.go
Biggest issue was that `doAzureOperation` was now always sending empty values as `contentType` and `data` parameters, breaking a lot of API calls of course.
Next to that some minor fixes/tweaks to make things play nice and little more robust.
=> Fix a few things that got broken while refactoring

management/hostedservice/entities.go
This one is also broken, so just restoring services here...
=> Fixing the hostedservice

management/virtualmachine/entities.go, management/vmutils/datadisks.go, management/vmutils/vmutils_test.go
=> Fix struct ordering to satify the API

management/storageservice/client.go, management/vmutils/integration_test.go
- Added `DeleteStorageService` (fixes #147)
- Renamed `CreateAsync` to `CreateStorageService` for consistency
@paulmey pls review & merge.
=> mgmt/storageservice: DeleteStorageService

management/client.go, management/http.go, management/operations.go
Allows tests to stub out at the HTTP client level.
cc: @aznashwan @ahmetalpbalkan
=> Extract interface for management.Client

management/client.go, management/virtualmachinedisk/entities.go
=> Updating bad struct field ordering

storage/blob.go, storage/blob_test.go, storage/client.go, storage/client_test.go, storage/util.go, storage/util_test.go
Some refactoring to reduce duplication for upcoming Queue SDK.
- Updated comments to point to docs uniformly
- Easy & generic check for expected status code
- Easy way to create clients in test code
cc: @paulmey I'm mostly confident but please take a look.
=> Refactor storage pkg for cosmetics

storage/blob_test.go, storage/client_test.go, storage/util_test.go
> 
cheers to a lot cleaner, readable and maintainable tests. :beers: 
cc: @paulmey
=> storage: Use gocheck for tests

management/testutils/managementclient.go
Provides some more context when integration tests fail
=> Add test request logging

management/client.go, management/http.go
Required for https://github.com/Azure/azure-sdk-for-go/pull/171
=> Added POST method which also returns the response to management.Client.

management/sql/client.go, management/sql/entities.go
Added support for database server and service CR_D.
This pull depends on: https://github.com/Azure/azure-sdk-for-go/pull/173
=> Added database server and service support.

management/sql/client.go, management/sql/entities.go
Added database update operation.
Also added some waiting features on more time-consuming operations, as well as a wait for database creation function.
=> Added Database Update operation and waiting features.

management/sql/entities.go
I realized just now that I got the fields of the create and update request structs mixed up a little.
On the bright side; the rest of everything got a much more thorough testthrough as Terraform provisions all the SQL's like a champ now :smile:
=> Fixed Database Service update request struct.

arm/README.md, arm/examples/check.go, arm/examples/check_test.go, arm/examples/create.go, arm/examples/create_test.go
This PR cleans up the examples a bit and provides trivial test files to ease executing them.
Signed-off-by: Brendan Dixon <brendand@microsoft.com>
=> Converted examples to use Test for execution

storage/client.go
see #197 for the reason behind this
=> Exposing UnexpectedStatusCodeError.Got to support (fixes #197)

storage/blob_test.go, storage/client.go, storage/file.go, storage/file_test.go
Support for CreateShare/DeleteShare calls.
@paulmey PTAL.
=> storage/file: Preliminary support for Azure File Service

arm/README.md
=> Fix typo in arm/README.md

storage/client.go
The Content-Length header is never used by the Go runtime.
Instead, the ContentLength field on the request struct is used to set the header
when writing the actual request. This field is only set for [certain types of io.Readers](https://golang.org/src/net/http/request.go?s=18140:18370#L536 ).
Azure storage signatures include the Content-Length header, hence, it needs to be
respected, even if the io.Reader is some other type that is not recognized by the Go
runtime.
=> Use the Content-Length header if it is set

management/vmutils/vmutils.go
Fixes the comment I made on #187
=> Fixing PR #187

management/http.go
RDFE uses HTTP 307's to bounce traffic between its deployments. So in these cases the host name is the only thing that changes in the url. I added an iterative construct to the sendRequest method, because after getting a response from the redirected-to-endpoint, we should return to using the original management endpoint in case retries are necessary.
=> Follow management endpoint redirects

management/vmutils/deployment.go, management/vmutils/integration_test.go, management/vmutils/rolestate.go, management/vmutils/vmutils_test.go
Did some additional integration testing. Deploying user VM images never worked before using this method.
=> Distinguish between deploying Public VM images and User VM images

LICENSE
Signed-off-by: Ahmet Alp Balkan
=> Apply copyright to LICENSE

management/osimage/client.go, management/osimage/entities.go
fixes #388 
i intend to follow up with some additional API call bindings to `services/images` endpoint if that would be accepted.
=> some small improvements to management/osimage

storage/blob.go, storage/blob_test.go
Added ability to create snapshots as per https://msdn.microsoft.com/en-us/library/azure/ee691971.aspx
=> Sas blob signing

storage/queue.go, storage/queue_test.go
Add support for queue UpdateMessage operation in Azure Go SDK
=> Add support for queue UpdateMessage operation in Azure Go SDK

arm/README.md
=> Updated ARM readme

storage/file.go, storage/file_test.go, storage/util.go
This change adds support for file storage operations on directories and
files; this includes creation, deletion and getting/setting of properties
and metadata.
=> Add support for more file storage APIs.

arm/README.md
This in response to issue Azure/azure-sdk-for-go#370
=> Updating ARM README to ref. the Node SDK's Auth tutorial

storage/authorization.go, storage/authorization_test.go, storage/blob.go, storage/blob_test.go, storage/client.go, storage/client_test.go, storage/file.go, storage/fileserviceclient.go, storage/queue.go, storage/table.go, storage/table_entities.go, storage/table_test.go
Authorization was a bit messy and incomplete, moved all of it to its own files too.
PTAL!
@marstr @jhendrixMSFT
=> Refactored Authorization

storage/client.go
- Added consts for their base URLs
- Added funcs to create clients as easy as it is for the public cloud
PTAL @marstr @jhendrixMSFT
=> Added some love for sovereign clouds

storage/directory.go, storage/file.go, storage/file_test.go, storage/fileserviceclient.go, storage/share.go
Implement PR for https://github.com/Azure/azure-sdk-for-go/issues/535  (CopyFile).
Timeout is passed via a struct FileRequestOptions. Currently it only has a single option (Timeout) but can start expanding as more functionality added.
=> CopyFile implemented and tests

management/README.md
=> Forgot to get rid of these lines in readme

Gododir/gen.go
There it is!
@marstr @jhendrixMSFT
=> Modified gen.go to support comp swaggers gen

storage/client.go, storage/client_test.go
Fixes https://github.com/Azure/azure-sdk-for-go/issues/584
=> Check validity of storage accounts

storage/client_test.go
=> Fix travis

CHANGELOG.md, dataplane/keyvault/models.go, glide.lock, glide.yaml
This in Response to Azure/autorest#2245
=> Regenerating to support UnixTime

storage/blobserviceclient.go, storage/container.go, storage/container_test.go, storage/entity.go, storage/entity_test.go, storage/fileserviceclient.go, storage/table.go, storage/table_batch.go, storage/table_batch_test.go, storage/tableserviceclient.go
Fixes https://github.com/Azure/azure-storage-go/issues/51
PTAL @marstr @jhendrixMSFT
=> All GetReference return pointers

Gododir/gen.go
=> Readded slash

storage/container.go, storage/container_test.go
Fixes https://github.com/Azure/azure-sdk-for-go/issues/613
PTAL @marstr @jhendrixMSFT
=> List blobs assigns container to blobs

arm/examples/check/check.go, arm/examples/create/create.go, arm/examples/dns/README.md, arm/examples/dns/create.go, arm/examples/dns/paging/paging.go, arm/examples/helpers/helpers.go
Examples didn't build after go-autorest https://github.com/Azure/go-autorest/pull/122 was merged
=> Fixed examples to use new go-autorest adal package

storage/blob.go, storage/blob_test.go, storage/recordings/StorageBlobSuite/TestGetBlobRange.yaml
PTAL
@marstr @jhendrixMSFT 
fixes https://github.com/Azure/azure-sdk-for-go/issues/659
=> Do not overwrite ContentLength in blob.GetRange

storage/blockblob.go
If a reader passed to (*Blob).CreateBlockBlobFromReader is already
a *bytes.Buffer value (or any other cached reeader like bytes.Reader,
strings.Reader etc.), we shouldn't buffer it again in order to
get its length - we use Len() method for those types instead.
Just mentioning - another possible optimisation would be to handle
io.ReadSeeker as well (e.g. *os.File), and get the length by seeking
to the end of the reader. I do not need it atm, so leaving for
possibly some other PR.
=> storage: try to avoid unnecessary buffering

storage/README.md, storage/client_test.go, storage/util_test.go
PTAL
@jhendrixMSFT @marstr
Fixes https://github.com/Azure/azure-sdk-for-go/issues/673
=> Overwrite recordings

storage/blob.go, storage/recordings/AppendBlobSuite/TestPutAppendBlobAppendBlocks.yaml, storage/recordings/PageBlobSuite/TestPutPagesClear.yaml, storage/recordings/PageBlobSuite/TestPutPagesUpdate.yaml, storage/recordings/StorageBlobSuite/TestGetBlobRange.yaml, storage/recordings/StorageBlobSuite/TestPutAppendBlobSpecialChars.yaml
PTAL
@marstr @jhendrixMSFT 
This should unblock tests in https://github.com/Azure/azure-sdk-for-go/pull/664
=> Set GetContentMD5 only when true

.travis.yml
=> CI uses go 1.8 only

.travis.yml, glide.lock, glide.yaml
Pick up latest go-autorest for RetriableRequest fix.
Updated other dependencies via "glide up".
=> Update go-autorest to 8.1.1.

storage/appendblob.go, storage/blob.go, storage/blockblob.go, storage/pageblob.go
I've added some bits to the docs for things I found confusing when doing my integration.
=> Improve storage docs

CHANGELOG.md, management/README.md
=> Correct wording for ASM package status

storage/authorization.go, storage/blobsasuri.go, storage/blobsasuri_test.go, storage/recordings/BlobSASURISuite/TestBlobSASURICorrectness.yaml
PTAL @jhendrixMSFT @marstr 
Fixes https://github.com/Azure/azure-sdk-for-go/issues/731
=> Fixes stringToSign for SASURI

storage/authorization.go, storage/authorization_test.go, storage/blobsasuri.go
PTAL @jhendrixMSFT @marstr 
Broke something else https://github.com/Azure/azure-sdk-for-go/issues/731
=> Fix canonicalized resource

Gododir/gen.go, glide.lock
=> Update gen.go to use new go generator repo

storage/table.go
=> Fix golint issue

storage/appendblob.go, storage/appendblob_test.go, storage/recordings/AppendBlobSuite/TestPutAppendBlobAppendBlocks.yaml
Fixes https://github.com/Azure/azure-sdk-for-go/issues/757
=> Add md5 support for append blobs

arm/deployment/deployment.go, arm/helpers/helpers.go
=> Add deployment helper

Gododir/gen.go
=> generates SDK is parallel, also reports failures at the end

arm/containerregistry/models.go, arm/containerregistry/version.go, management/version.go
Regen container registry SDK
I want to release this with https://github.com/Azure/azure-sdk-for-go/pull/800 as v11.1.0-beta
=> Containerregistry

storage/blob.go, storage/blob_test.go, storage/container_test.go
Fixes https://github.com/Azure/azure-sdk-for-go/issues/774
=> Correctly unmarshal blob types

arm/README.md
PTAL
@jhendrixMSFT @marstr 
Based on [python's docs](https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-file).
=> Added auth file documentation

tools/generator/program.go, tools/profileBuilder/program.go
This PR depends on https://github.com/Azure/autorest.go/pull/45. It should not be merged for it.
---
=> Generator user agent

Gopkg.lock, Gopkg.toml, storage/entity.go, storage/entity_test.go, storage/table_batch.go, storage/table_batch_test.go
=> fix old usage of satori/uuid

storage/entity.go, storage/entity_test.go
Binary data should be encoded using base64.
Previous conversions see PR #908.
=> Fix bug: Binary data is not properly encoded.

Gopkg.lock, tools/profileBuilder/program.go
Fixes #920 
- Using the same package goimports uses we can resolve missing packages.
=> Auto import used packages in profiles

swagger_to_sdk_config.json
Discussed with @marstr, please assign him the PR
=> Add common Autorest parameters in SwaggerToSdk conf

Gopkg.lock, Gopkg.toml, services/cosmos-db/mongodb/client.go, storage/table_batch.go
Fixes https://github.com/Azure/azure-sdk-for-go/issues/958
=> Replacing mongoDB driver

tools/profileBuilder/cmd/latest.go, tools/profileBuilder/cmd/list.go
=> +Viper instances for each profileBuilder command.

storage/README.md
cc @seguler @marstr 
updated links, removed the test notes since not needed for most users, and put notice about new blobs repo at the top.
=> update storage README to reflect preview state

README.md
notable updates:
* removed preview notices but still hinted at possible breaking changes and recommended dep
* replace references to "ADAL" with "auth"
* cleaned up versioning section to reflect latest consensus
* added blobs and app insights repo to Resources
=> update README for v14.0.0

profiles/2017-03-09/generate.go, swagger_to_sdk_config.json, tools/profileBuilder/README.md, tools/profileBuilder/cmd/list.go
=> Update Profile Builder to allow a specified file for list input

swagger_to_sdk_config.json
=> Changing profileBuilder strategy in Swagger -> SDK

storage/README.md
Looks like this didn't land correctly in master so trying again for inclusion in next point release. Thanks!
=> update storage README to reflect recommended practices

services/location/mgmt/2017-01-01-preview/location/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2533
=> [AutoPR locationbasedservices/resource-manager] locationbasedservices py conf

services/servicebus/mgmt/2015-08-01/servicebus/version.go, services/servicebus/mgmt/2017-04-01/servicebus/models.go, services/servicebus/mgmt/2017-04-01/servicebus/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2534
=> [AutoPR servicebus/resource-manager] ServiceBus: Added enableBatchedOperations property to ServiceBus Queue

services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2550
=> [AutoPR marketplaceordering/resource-manager] Add a directive for node and TS to delete format: "date-time".

services/datamigration/mgmt/2017-11-15-preview/datamigration/models.go, services/datamigration/mgmt/2017-11-15-preview/datamigration/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2553
=> [AutoPR datamigration/resource-manager] DataMigration py conf

services/compute/mgmt/2015-06-15/compute/version.go, services/compute/mgmt/2016-03-30/compute/version.go, services/compute/mgmt/2016-04-30-preview/compute/version.go, services/compute/mgmt/2017-03-30/compute/version.go, services/compute/mgmt/2017-12-01/compute/models.go, services/compute/mgmt/2017-12-01/compute/version.go, services/containerservice/mgmt/2015-11-01-preview/containerservice/version.go, services/containerservice/mgmt/2016-03-30/containerservice/version.go, services/containerservice/mgmt/2016-09-30/containerservice/version.go, services/containerservice/mgmt/2017-01-31/containerservice/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2551
=> [AutoPR compute/resource-manager] Compute spec change for zone resilient images

services/datamigration/mgmt/2017-11-15-preview/datamigration/models.go, services/datamigration/mgmt/2017-11-15-preview/datamigration/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2531
=> [AutoPR datamigration/resource-manager] Update Azure Database Migration Service to add Managed Instance as target 

services/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go, services/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2564
=> [AutoPR hanaonazure/resource-manager] Remove unused HANA API

services/datafactory/mgmt/2017-09-01-preview/datafactory/models.go, services/datafactory/mgmt/2017-09-01-preview/datafactory/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2568
=> [AutoPR datafactory/resource-manager] Add AzureDatabricks Linked Service and DatabricksNote Activity

services/redis/mgmt/2015-08-01/redis/version.go, services/redis/mgmt/2016-04-01/redis/version.go, services/redis/mgmt/2017-02-01/redis/version.go, services/redis/mgmt/2017-10-01/redis/models.go, services/redis/mgmt/2017-10-01/redis/patchschedules.go, services/redis/mgmt/2017-10-01/redis/redis.go, services/redis/mgmt/2017-10-01/redis/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2537
=> [AutoPR redis/resource-manager] Swagger completeness for Redis Cache

services/web/mgmt/2016-09-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2580
=> [AutoPR web/resource-manager] Add missing type specifier to enum definition.

CHANGELOG.md, storage/container.go, storage/container_test.go, storage/recordings/ContainerSuite/TestGetContainerProperties.yaml, version/version.go
Added Container.GetProperties() method.
Added PublicAccess field to ContainerProperties struct.
=> Fixes to blob storage containers.

services/sql/mgmt/2017-03-01-preview/sql/restorepoints.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2593
=> [AutoPR sql/resource-manager] Sksinghspecs

.travis.yml
=> Update travis build matrix with Go 1.10.x

swagger_to_sdk_config.json, version/version.go
Prepping for merging into `latest` branch.
=> Updating version number in latest branch

services/authorization/mgmt/2015-07-01/authorization/version.go, services/authorization/mgmt/2017-10-01-preview/authorization/classicadministrators.go, services/authorization/mgmt/2017-10-01-preview/authorization/version.go, services/authorization/mgmt/2018-01-01-preview/authorization/classicadministratorsgroup.go, services/authorization/mgmt/2018-01-01-preview/authorization/models.go, services/authorization/mgmt/2018-01-01-preview/authorization/permissionsgroup.go, services/authorization/mgmt/2018-01-01-preview/authorization/provideroperationsmetadatagroup.go, services/authorization/mgmt/2018-01-01-preview/authorization/roleassignmentsgroup.go, services/authorization/mgmt/2018-01-01-preview/authorization/roledefinitionsgroup.go, services/authorization/mgmt/2018-01-01-preview/authorization/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2586
=> [AutoPR authorization/resource-manager] update roledefinition filters to be in sync with the filters present in service

swagger_to_sdk_config.json
Contains bugfix when generating pageable types.
=> Update autorest.go generator version.

services/resources/mgmt/2015-01-01/locks/models.go, services/resources/mgmt/2015-10-01-preview/policy/models.go, services/resources/mgmt/2015-11-01/resources/models.go, services/resources/mgmt/2016-02-01/resources/models.go, services/resources/mgmt/2016-04-01/policy/models.go, services/resources/mgmt/2016-06-01/subscriptions/models.go, services/resources/mgmt/2016-07-01/resources/models.go, services/resources/mgmt/2016-09-01-preview/managedapplications/models.go, services/resources/mgmt/2016-09-01/links/models.go, services/resources/mgmt/2016-09-01/locks/models.go, services/resources/mgmt/2016-09-01/resources/models.go, services/resources/mgmt/2016-12-01/policy/models.go, services/resources/mgmt/2017-05-10/resources/models.go, services/resources/mgmt/2017-06-01-preview/policy/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2613
=> [AutoPR resources/resource-manager] Fix java code generation for resources

services/compute/mgmt/2015-06-15/compute/models.go, services/compute/mgmt/2016-03-30/compute/models.go, services/compute/mgmt/2016-04-30-preview/compute/models.go, services/compute/mgmt/2017-03-30/compute/models.go, services/compute/mgmt/2017-12-01/compute/models.go, services/compute/mgmt/2017-12-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2017-12-01/compute/virtualmachinescalesetvms.go, services/containerservice/mgmt/2015-11-01-preview/containerservice/models.go, services/containerservice/mgmt/2016-03-30/containerservice/models.go, services/containerservice/mgmt/2016-09-30/containerservice/models.go, services/containerservice/mgmt/2017-01-31/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2589
=> [AutoPR compute/resource-manager] Adding 2 new APIs for VMSS: Redeploy and PerformMaintenance

services/dns/mgmt/2015-05-04-preview/dns/models.go, services/dns/mgmt/2016-04-01/dns/models.go, services/dns/mgmt/2017-09-01/dns/models.go, services/dns/mgmt/2017-10-01/dns/models.go, services/dns/mgmt/2017-10-01/dns/zones.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2612
=> [AutoPR dns/resource-manager] Fix SDK breaking change in 2017-10-01 DNS Swagger

services/cdn/mgmt/2015-06-01/cdn/models.go, services/cdn/mgmt/2015-06-01/cdn/version.go, services/cdn/mgmt/2016-04-02/cdn/models.go, services/cdn/mgmt/2016-04-02/cdn/version.go, services/cdn/mgmt/2016-10-02/cdn/models.go, services/cdn/mgmt/2016-10-02/cdn/version.go, services/cdn/mgmt/2017-04-02/cdn/models.go, services/cdn/mgmt/2017-04-02/cdn/version.go, services/cdn/mgmt/2017-10-12/cdn/models.go, services/cdn/mgmt/2017-10-12/cdn/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2516
=> [AutoPR cdn/resource-manager] Change the default tag to 2017-10

tools/apidiff/cmd/common.go, tools/apidiff/cmd/package.go, tools/apidiff/cmd/packages.go, tools/apidiff/cmd/root.go, tools/apidiff/delta/delta.go, tools/apidiff/delta/delta_test.go, tools/apidiff/delta/testdata/breaking/new/new.go, tools/apidiff/delta/testdata/breaking/old/old.go, tools/apidiff/delta/testdata/nonbreaking/new/new.go, tools/apidiff/delta/testdata/nonbreaking/old/old.go, tools/apidiff/exports/exports.go, tools/apidiff/exports/package.go, tools/apidiff/exports/package_test.go, tools/apidiff/exports/testdata/td.go, tools/apidiff/main.go, tools/apidiff/repo/repo.go
This tool will generate a report in JSON format describing changes to
public surface area between two specified commits.  It can work on
individual packages or a set of packages under a specified directory.
Please see the help for details on usage of the tool.
=> Add apidiff tool.

services/cognitiveservices/mgmt/2016-02-01-preview/cognitiveservices/models.go, services/cognitiveservices/mgmt/2016-02-01-preview/cognitiveservices/version.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/accounts.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/client.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/operations.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2627
=> [AutoPR cognitiveservices/resource-manager] [Cognitive Services] Change type of limit/currentValue to double from integer

services/billing/mgmt/2018-03-01-preview/billing/enrollmentaccounts.go, services/billing/mgmt/2018-03-01-preview/billing/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2626
=> [AutoPR billing/resource-manager] [Billing RP] Rename BillingAccount->EnrollmentAccount.

services/cognitiveservices/mgmt/2016-02-01-preview/cognitiveservices/models.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/accounts.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/client.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/operations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2641
=> [AutoPR cognitiveservices/resource-manager] Remove advisor Java block from CognitiveServices readme.md

services/postgresql/mgmt/2017-04-30-preview/postgresql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2629
=> [AutoPR postgresql/resource-manager] correct tier enum for postgres

services/keyvault/mgmt/2015-06-01/keyvault/models.go, services/keyvault/mgmt/2015-06-01/keyvault/version.go, services/keyvault/mgmt/2016-10-01/keyvault/models.go, services/keyvault/mgmt/2016-10-01/keyvault/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2650
=> [AutoPR keyvault/resource-manager] Add node config to keyvault for Swagger to SDK

services/managementpartner/mgmt/2018-02-01/managementpartner/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2665
=> [AutoPR managementpartner/resource-manager] Add partner name for managmentparnter action response

services/eventhub/mgmt/2015-08-01/eventhub/models.go, services/eventhub/mgmt/2017-04-01/eventhub/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2272
=> [AutoPR eventhub/resource-manager] [DO NOT MERGE UNTIL SERVICE TEAM DECIDES] Adding preview version of Event Hubs Cluster to Azure REST API specs.

services/containerservice/mgmt/2017-07-01/containerservice/containerservices.go, services/containerservice/mgmt/2017-08-31/containerservice/containerservicesgroup.go, services/containerservice/mgmt/2017-08-31/containerservice/managedclustersgroup.go, services/containerservice/mgmt/2017-08-31/containerservice/models.go, services/containerservice/mgmt/2017-09-30/containerservice/containerservices.go, services/containerservice/mgmt/2017-09-30/containerservice/managedclusters.go, services/containerservice/mgmt/2017-09-30/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2669
=> [AutoPR containerservices/resource-manager] [AKS] specify byte format for base64-encoded kubeconfig

services/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2674
=> [AutoPR datafactory/resource-manager] Add package-version for ADF

services/containerinstance/mgmt/2018-02-01-preview/containerinstance/models.go
Created to accumulate context: containerinstance/resource-manager
=> [AutoPR] containerinstance/resource-manager

services/timeseriesinsights/mgmt/2017-11-15/timeseriesinsights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2675
=> [AutoPR timeseriesinsights/resource-manager] [SwaggerSpec update - Time Series Insights] Added optional parameter to reference data set create/update

services/resources/mgmt/2016-06-01/subscriptions/client.go, services/resources/mgmt/2016-06-01/subscriptions/subscriptions.go, services/resources/mgmt/2016-06-01/subscriptions/tenants.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2670
=> [AutoPR resources/resource-manager] Move subscriptionId to global

services/cdn/mgmt/2015-06-01/cdn/customdomains.go, services/cdn/mgmt/2015-06-01/cdn/endpoints.go, services/cdn/mgmt/2015-06-01/cdn/models.go, services/cdn/mgmt/2015-06-01/cdn/nameavailability.go, services/cdn/mgmt/2015-06-01/cdn/origins.go, services/cdn/mgmt/2015-06-01/cdn/profiles.go, services/cdn/mgmt/2016-04-02/cdn/customdomains.go, services/cdn/mgmt/2016-04-02/cdn/endpoints.go, services/cdn/mgmt/2016-04-02/cdn/models.go, services/cdn/mgmt/2016-04-02/cdn/nameavailability.go, services/cdn/mgmt/2016-04-02/cdn/origins.go, services/cdn/mgmt/2016-04-02/cdn/profiles.go, services/cdn/mgmt/2016-10-02/cdn/client.go, services/cdn/mgmt/2016-10-02/cdn/customdomains.go, services/cdn/mgmt/2016-10-02/cdn/endpoints.go, services/cdn/mgmt/2016-10-02/cdn/models.go, services/cdn/mgmt/2016-10-02/cdn/origins.go, services/cdn/mgmt/2016-10-02/cdn/profiles.go, services/cdn/mgmt/2017-04-02/cdn/client.go, services/cdn/mgmt/2017-04-02/cdn/customdomains.go, services/cdn/mgmt/2017-04-02/cdn/endpoints.go, services/cdn/mgmt/2017-04-02/cdn/models.go, services/cdn/mgmt/2017-04-02/cdn/origins.go, services/cdn/mgmt/2017-04-02/cdn/profiles.go, services/cdn/mgmt/2017-10-12/cdn/client.go, services/cdn/mgmt/2017-10-12/cdn/customdomains.go, services/cdn/mgmt/2017-10-12/cdn/endpoints.go, services/cdn/mgmt/2017-10-12/cdn/models.go, services/cdn/mgmt/2017-10-12/cdn/origins.go, services/cdn/mgmt/2017-10-12/cdn/profiles.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2700
=> [AutoPR cdn/resource-manager]  Add example for checkNameAvailability

services/cdn/mgmt/2015-06-01/cdn/customdomains.go, services/cdn/mgmt/2015-06-01/cdn/endpoints.go, services/cdn/mgmt/2015-06-01/cdn/models.go, services/cdn/mgmt/2015-06-01/cdn/nameavailability.go, services/cdn/mgmt/2015-06-01/cdn/origins.go, services/cdn/mgmt/2015-06-01/cdn/profiles.go, services/cdn/mgmt/2016-04-02/cdn/customdomains.go, services/cdn/mgmt/2016-04-02/cdn/endpoints.go, services/cdn/mgmt/2016-04-02/cdn/models.go, services/cdn/mgmt/2016-04-02/cdn/nameavailability.go, services/cdn/mgmt/2016-04-02/cdn/origins.go, services/cdn/mgmt/2016-04-02/cdn/profiles.go, services/cdn/mgmt/2016-10-02/cdn/client.go, services/cdn/mgmt/2016-10-02/cdn/customdomains.go, services/cdn/mgmt/2016-10-02/cdn/endpoints.go, services/cdn/mgmt/2016-10-02/cdn/models.go, services/cdn/mgmt/2016-10-02/cdn/origins.go, services/cdn/mgmt/2016-10-02/cdn/profiles.go, services/cdn/mgmt/2017-04-02/cdn/client.go, services/cdn/mgmt/2017-04-02/cdn/customdomains.go, services/cdn/mgmt/2017-04-02/cdn/endpoints.go, services/cdn/mgmt/2017-04-02/cdn/models.go, services/cdn/mgmt/2017-04-02/cdn/origins.go, services/cdn/mgmt/2017-04-02/cdn/profiles.go, services/cdn/mgmt/2017-10-12/cdn/client.go, services/cdn/mgmt/2017-10-12/cdn/customdomains.go, services/cdn/mgmt/2017-10-12/cdn/endpoints.go, services/cdn/mgmt/2017-10-12/cdn/models.go, services/cdn/mgmt/2017-10-12/cdn/origins.go, services/cdn/mgmt/2017-10-12/cdn/profiles.go
Created to accumulate context: cdn/resource-manager
=> [AutoPR] cdn/resource-manager

services/billing/mgmt/2018-03-01-preview/billing/enrollmentaccounts.go, services/billing/mgmt/2018-03-01-preview/billing/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2698
=> [AutoPR billing/resource-manager] [Billing RP] Minor EnrollmentAccount API consistency tweaks

services/network/mgmt/2018-01-01/network/models.go, services/network/mgmt/2018-01-01/network/watchers.go
Created to accumulate context: network/resource-manager
=> [AutoPR] network/resource-manager

services/billing/mgmt/2018-03-01-preview/billing/enrollmentaccounts.go, services/billing/mgmt/2018-03-01-preview/billing/models.go
Created to accumulate context: billing/resource-manager
=> [AutoPR] billing/resource-manager

services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2701
=> [AutoPR cosmos-db/resource-manager] added descriptions to include Cosmos DB ARM template values

services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Created to accumulate context: cosmos-db/resource-manager
=> [AutoPR] cosmos-db/resource-manager

services/appinsights/mgmt/2015-05-01/insights/annotations.go, services/appinsights/mgmt/2015-05-01/insights/apikeys.go, services/appinsights/mgmt/2015-05-01/insights/client.go, services/appinsights/mgmt/2015-05-01/insights/componentavailablefeatures.go, services/appinsights/mgmt/2015-05-01/insights/componentcurrentbillingfeatures.go, services/appinsights/mgmt/2015-05-01/insights/componentfeaturecapabilities.go, services/appinsights/mgmt/2015-05-01/insights/componentquotastatus.go, services/appinsights/mgmt/2015-05-01/insights/components.go, services/appinsights/mgmt/2015-05-01/insights/exportconfigurations.go, services/appinsights/mgmt/2015-05-01/insights/favorite.go, services/appinsights/mgmt/2015-05-01/insights/favorites.go, services/appinsights/mgmt/2015-05-01/insights/operations.go, services/appinsights/mgmt/2015-05-01/insights/proactivedetectionconfigurations.go, services/appinsights/mgmt/2015-05-01/insights/webtestlocations.go, services/appinsights/mgmt/2015-05-01/insights/webtests.go, services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2618
=> [AutoPR applicationinsights/resource-manager] migrate from apis in private repo to preview (new pricing model api and migration apis)

services/appinsights/mgmt/2015-05-01/insights/annotations.go, services/appinsights/mgmt/2015-05-01/insights/apikeys.go, services/appinsights/mgmt/2015-05-01/insights/client.go, services/appinsights/mgmt/2015-05-01/insights/componentavailablefeatures.go, services/appinsights/mgmt/2015-05-01/insights/componentcurrentbillingfeatures.go, services/appinsights/mgmt/2015-05-01/insights/componentfeaturecapabilities.go, services/appinsights/mgmt/2015-05-01/insights/componentquotastatus.go, services/appinsights/mgmt/2015-05-01/insights/components.go, services/appinsights/mgmt/2015-05-01/insights/exportconfigurations.go, services/appinsights/mgmt/2015-05-01/insights/favorite.go, services/appinsights/mgmt/2015-05-01/insights/favorites.go, services/appinsights/mgmt/2015-05-01/insights/operations.go, services/appinsights/mgmt/2015-05-01/insights/proactivedetectionconfigurations.go, services/appinsights/mgmt/2015-05-01/insights/webtestlocations.go, services/appinsights/mgmt/2015-05-01/insights/webtests.go, services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go
Created to accumulate context: applicationinsights/resource-manager
=> [AutoPR] applicationinsights/resource-manager

services/resources/mgmt/2016-06-01/subscriptions/client.go, services/resources/mgmt/2016-06-01/subscriptions/subscriptions.go, services/resources/mgmt/2016-06-01/subscriptions/tenants.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2710
=> [AutoPR resources/resource-manager] Fix subscription paramter in SubscriptionClient

services/apimanagement/mgmt/2017-03-01/apimanagement/apirevisions.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2721
=> [AutoPR apimanagement/resource-manager] Fix issue with 2017-03-01 version of api-management

services/apimanagement/mgmt/2017-03-01/apimanagement/apirevisions.go
Created to accumulate context: apimanagement/resource-manager
=> [AutoPR] apimanagement/resource-manager

services/resources/mgmt/2017-05-10/resources/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2678
=> [AutoPR resources/resource-manager] Fix some of the error in ARM swagger spec

services/network/mgmt/2018-01-01/network/models.go, services/network/mgmt/2018-01-01/network/watchers.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2720
=> [AutoPR network/resource-manager] Fixed operationIds for non-CRUD operations in ExpressRouteCrossConnections

services/preview/subscription/mgmt/2018-03-01-preview/subscription/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2736
=> [AutoPR subscription/resource-manager] [Subscription RP] Add AdditionalParameters property to SubscriptionCreationParameters

services/servicebus/mgmt/2017-04-01/servicebus/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2730
=> [AutoPR servicebus/resource-manager] ServiceBus: added 'properties' to CorrelationFilter

services/network/mgmt/2018-01-01/network/models.go, services/network/mgmt/2018-01-01/network/watchers.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2642
=> [AutoPR network/resource-manager] Merge Network-2018-02-01 to Master Networking Swagger Changes for Feb 2018

services/monitor/mgmt/2018-03-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2620
=> [AutoPR monitor/resource-manager] [Monitoring] Add metric alerts api 2018-03-01

services/network/mgmt/2018-01-01/network/models.go, services/network/mgmt/2018-01-01/network/watchers.go
Reverts Azure/azure-sdk-for-go#1402
=> Revert "[AutoPR network/resource-manager] Merge Network-2018-02-01 to Master Networking Swagger Changes for Feb 2018"

services/servicebus/mgmt/2017-04-01/servicebus/models.go
Created to accumulate context: servicebus/resource-manager
=> [AutoPR] servicebus/resource-manager

services/automation/mgmt/2015-10-31/automation/dscconfiguration.go, services/automation/mgmt/2015-10-31/automation/models.go, services/automation/mgmt/2017-05-15-preview/automation/dscconfiguration.go, services/automation/mgmt/2017-05-15-preview/automation/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2688
=> [AutoPR automation/resource-manager] Adding patch API for Configurations

services/monitor/mgmt/2018-03-01/insights/models.go
Created to accumulate context: monitor/resource-manager
=> [AutoPR] monitor/resource-manager

README.md
Hi, 
I recently hit a problem using the SDK and after a lot of digging I found this awesome `go-autorest` feature which helped me out by letting me intercept and review the requests and responses. 
I thought it was worth adding to the docs to help others but I understand it's likely more useful when using less common resources with no samples so I wasn't sure if the `Readme.md` was the right place. Let me know what you think. 
- [NA] I've tested my changes, adding unit tests where applicable.
- [ NA] I've added Apache 2.0 Headers to the top of any new source files.
- [NA] If I'm targeting the …
=> Docs: Added notes on using RequestInspector and ResponseInspector

.travis.yml
=> Use binary release of dep

services/datamigration/mgmt/2017-11-15-preview/datamigration/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2760
=> [AutoPR datamigration/resource-manager] Remove TaskOutput base object.

services/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2735
=> [AutoPR datafactory/resource-manager] [ADF] Swagger Change for Responsys Source

services/mysql/mgmt/2017-12-01/mysql/models.go, services/postgresql/mgmt/2017-12-01/postgresql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2765
=> [AutoPR mysql/resource-manager/postgresql/resource-manager] Add GeoRestore to MySQL and PostgreSQL

services/compute/mgmt/2015-06-15/compute/models.go, services/compute/mgmt/2015-06-15/compute/virtualmachineextensions.go, services/compute/mgmt/2016-03-30/compute/models.go, services/compute/mgmt/2016-03-30/compute/virtualmachineextensions.go, services/compute/mgmt/2016-03-30/compute/virtualmachines.go, services/compute/mgmt/2016-04-30-preview/compute/models.go, services/compute/mgmt/2016-04-30-preview/compute/virtualmachineextensions.go, services/compute/mgmt/2016-04-30-preview/compute/virtualmachines.go, services/compute/mgmt/2017-03-30/compute/models.go, services/compute/mgmt/2017-03-30/compute/virtualmachineextensions.go, services/compute/mgmt/2017-03-30/compute/virtualmachines.go, services/compute/mgmt/2018-04-01/compute/models.go, services/compute/mgmt/2018-04-01/compute/virtualmachineextensions.go, services/compute/mgmt/2018-04-01/compute/virtualmachines.go
Created to accumulate context: compute/resource-manager
=> [AutoPR] compute/resource-manager

services/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to accumulate context: datafactory/resource-manager
=> [AutoPR] datafactory/resource-manager

services/datamigration/mgmt/2017-11-15-preview/datamigration/models.go
Created to accumulate context: datamigration/resource-manager
=> [AutoPR] datamigration/resource-manager

services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/accounts.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/client.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/operations.go
Created to accumulate context: cognitiveservices/resource-manager
=> [AutoPR] cognitiveservices/resource-manager

services/network/mgmt/2018-02-01/network/client.go, services/network/mgmt/2018-02-01/network/interfaces.go, services/network/mgmt/2018-02-01/network/models.go, services/network/mgmt/2018-02-01/network/publicipaddresses.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2797
=> [AutoPR network/resource-manager] fix the Version for vmss public ip and nic

swagger_to_sdk_config.json
Over the week-end thinking:
- Create a customized container will be complicated to handle at the AKS level
- The update here is not that bad to support, and should fit your need.
Do not merge until it's implemented of course :)
Thoughts?
(note that "repotag" is required and I forgot you didn't have it :p)
=> Add GOPATH support to SwaggerToSdk

services/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2716
=> [AutoPR datafactory/resource-manager] Add properties in ADF ExecuteSSISPackage Activity 

services/cognitiveservices/v1.0/contentmoderator/models.go, services/cognitiveservices/v1.0/contentmoderator/textmoderation.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2815
=> [AutoPR cognitiveservices/data-plane/ContentModerator] Add SSN parameter

services/monitor/mgmt/2018-03-01/insights/actiongroups.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2820
=> [AutoPR monitor/resource-manager] Add extra description for Subscribe API

services/cognitiveservices/v1.0/contentmoderator/models.go, services/cognitiveservices/v1.0/contentmoderator/textmoderation.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2815
=> [AutoPR cognitiveservices/data-plane/ContentModerator] Add SSN parameter to Content Moderator Screen text API

services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go, services/operationalinsights/mgmt/2015-11-01-preview/operationalinsights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2827
=> [AutoPR operationalinsights/resource-manager] Update with new workspace Sku - PerGB2018

services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go, services/operationalinsights/mgmt/2015-11-01-preview/operationalinsights/models.go
Created to accumulate context: operationalinsights/resource-manager
=> [AutoPR] operationalinsights/resource-manager

services/cognitiveservices/v1.0/contentmoderator/models.go, services/cognitiveservices/v1.0/contentmoderator/textmoderation.go
Created to accumulate context: cognitiveservices/data-plane/ContentModerator
=> [AutoPR] cognitiveservices/data-plane/ContentModerator

services/eventhub/mgmt/2017-04-01/eventhub/models.go, services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2846
=> [AutoPR eventhub/resource-manager] EventHub: Revert removing of messaging plan and updated with examples

swagger_to_sdk_config.json
=> Run the profile builder as part of swagger->sdk

.travis.yml, tools/profileBuilder/main.go, tools/profileBuilder/model/noop.go
=> port CI fix from master

services/preview/apimanagement/mgmt/2018-01-01/apimanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2881
=> [AutoPR apimanagement/resource-manager] add readonly property private ip address in addtional location

services/preview/apimanagement/mgmt/2018-01-01/apimanagement/apiissue.go, services/preview/apimanagement/mgmt/2018-01-01/apimanagement/apiissueattachment.go, services/preview/apimanagement/mgmt/2018-01-01/apimanagement/apiissuecomment.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2893
=> [AutoPR apimanagement/resource-manager] ApiIssue HEAD operation name consistent across the spec

CODEOWNERS
=> +List of owners for each source file in the repo

profiles/latest/timeseriesinsights/mgmt/timeseriesinsights/models.go, profiles/preview/timeseriesinsights/mgmt/timeseriesinsights/models.go, services/timeseriesinsights/mgmt/2017-11-15/timeseriesinsights/models.go
Created to accumulate context: timeseriesinsights/resource-manager
=> [AutoPR] timeseriesinsights/resource-manager

profiles/latest/appinsights/mgmt/insights/models.go, profiles/preview/appinsights/mgmt/insights/models.go, services/appinsights/mgmt/2015-05-01/insights/models.go, services/appinsights/mgmt/2015-05-01/insights/workbook.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2898
=> [AutoPR applicationinsights/resource-manager] Modify Workbook Resource Type to include RG and remove unused endpoint

profiles/latest/recoveryservices/mgmt/siterecovery/models.go, profiles/preview/recoveryservices/mgmt/siterecovery/models.go, services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go, services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationprotectioncontainermappings.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2908
=> [AutoPR recoveryservicessiterecovery/resource-manager] Updating swagger spec for RecoveryServices.SiteRecovery service (2018-01-10).

profiles/latest/containerregistry/mgmt/containerregistry/models.go, profiles/preview/containerregistry/mgmt/containerregistry/models.go, services/containerregistry/mgmt/2017-10-01/containerregistry/models.go, services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go
Created to accumulate context: containerregistry/resource-manager
=> [AutoPR] containerregistry/resource-manager

profiles/latest/recoveryservices/mgmt/siterecovery/models.go, profiles/preview/recoveryservices/mgmt/siterecovery/models.go, services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go, services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationprotectioncontainermappings.go
Created to accumulate context: recoveryservicessiterecovery/resource-manager
=> [AutoPR] recoveryservicessiterecovery/resource-manager

services/batch/2018-03-01.6.1/batch/job.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2930
=> [AutoPR batch/data-plane] Batch API: Fix the wrong statement in description

profiles/latest/cognitiveservices/luis/runtime/models.go, profiles/preview/cognitiveservices/luis/runtime/models.go, services/cognitiveservices/v2.0/luis/programmatic/client.go, services/cognitiveservices/v2.0/luis/programmatic/version.go, services/cognitiveservices/v2.0/luis/runtime/client.go, services/cognitiveservices/v2.0/luis/runtime/models.go, services/cognitiveservices/v2.0/luis/runtime/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2883
=> [AutoPR cognitiveservices/data-plane/LUIS/Authoring/cognitiveservices/data-plane/LUIS/Runtime] Changing luis sdk namespace and package version

services/batch/2018-03-01.6.1/batch/job.go
Created to accumulate context: batch/data-plane
=> [AutoPR] batch/data-plane

services/servicebus/mgmt/2015-08-01/servicebus/namespaces.go, services/servicebus/mgmt/2015-08-01/servicebus/queues.go, services/servicebus/mgmt/2015-08-01/servicebus/subscriptions.go, services/servicebus/mgmt/2015-08-01/servicebus/topics.go, services/servicebus/mgmt/2017-04-01/servicebus/disasterrecoveryconfigs.go, services/servicebus/mgmt/2017-04-01/servicebus/eventhubs.go, services/servicebus/mgmt/2017-04-01/servicebus/migrationconfigs.go, services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go, services/servicebus/mgmt/2017-04-01/servicebus/queues.go, services/servicebus/mgmt/2017-04-01/servicebus/regions.go, services/servicebus/mgmt/2017-04-01/servicebus/rules.go, services/servicebus/mgmt/2017-04-01/servicebus/subscriptions.go, services/servicebus/mgmt/2017-04-01/servicebus/topics.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2952
=> [AutoPR servicebus/resource-manager] Service Bus: added $skip and $top to list commands

services/eventgrid/2018-01-01/eventgrid/client.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2955
=> [AutoPR eventgrid/data-plane] EventGrid Py conf to 1.0.0

services/keyvault/2015-06-01/keyvault/client.go, services/keyvault/2016-10-01/keyvault/client.go, services/keyvault/2016-10-01/keyvault/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2972
=> [AutoPR keyvault/data-plane] Update description for DeleteRecoveryLevel fields

services/eventgrid/2018-01-01/eventgrid/client.go
Created to accumulate context: eventgrid/data-plane
=> [AutoPR] eventgrid/data-plane

services/eventhub/mgmt/2015-08-01/eventhub/consumergroups.go, services/eventhub/mgmt/2015-08-01/eventhub/eventhubs.go, services/eventhub/mgmt/2015-08-01/eventhub/namespaces.go, services/eventhub/mgmt/2017-04-01/eventhub/consumergroups.go, services/eventhub/mgmt/2017-04-01/eventhub/disasterrecoveryconfigs.go, services/eventhub/mgmt/2017-04-01/eventhub/eventhubs.go, services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go, services/eventhub/mgmt/2017-04-01/eventhub/regions.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/clusters.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/configuration.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2958
=> [AutoPR eventhub/resource-manager] EventHub: added $skip and $top to list calls

Gopkg.lock, Gopkg.toml, services/keyvault/auth/auth.go
=> Add keyvault auth

CHANGELOG.md, Gopkg.lock, Gopkg.toml, services/keyvault/auth/auth.go, version/version.go
=> Add keyvault auth helper func

profiles/latest/cognitiveservices/textanalytics/models.go, profiles/preview/cognitiveservices/textanalytics/models.go, services/cognitiveservices/v2.0/textanalytics/client.go, services/cognitiveservices/v2.0/textanalytics/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2985
=> [AutoPR cognitiveservices/data-plane/TextAnalytics] Update CognitiveServices/Text-Analytics Swagger with new /entities endpoint

services/preview/signalr/mgmt/2018-03-01-preview/signalr/signalr.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3004
=> [AutoPR signalr/resource-manager] update CheckNameAvailability resource to add extra location in its route

profiles/latest/cognitiveservices/textanalytics/models.go, profiles/preview/cognitiveservices/textanalytics/models.go, services/cognitiveservices/v2.0/textanalytics/client.go, services/cognitiveservices/v2.0/textanalytics/models.go
Created to accumulate context: cognitiveservices/data-plane/TextAnalytics
=> [AutoPR] cognitiveservices/data-plane/TextAnalytics

services/preview/signalr/mgmt/2018-03-01-preview/signalr/signalr.go
Created to accumulate context: signalr/resource-manager
=> [AutoPR] signalr/resource-manager

profiles/preview/trafficmanager/mgmt/trafficmanager/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3006
=> [AutoPR trafficmanager/resource-manager] fix trafficmanager API version directory for Go

profiles/preview/trafficmanager/mgmt/trafficmanager/models.go
Created to accumulate context: trafficmanager/resource-manager
=> [AutoPR] trafficmanager/resource-manager

profiles/latest/recoveryservices/mgmt/siterecovery/models.go, profiles/preview/recoveryservices/mgmt/siterecovery/models.go, services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go, services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationprotectableitems.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3016
=> [AutoPR recoveryservicessiterecovery/resource-manager] BugFixes: Representing enums as string and moving away from complex odata fields.

profiles/preview/trafficmanager/mgmt/trafficmanager/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2960
=> [AutoPR machinelearning/resource-manager] Moving Swagger file for consistency

services/web/mgmt/2016-09-01/web/apps.go, services/web/mgmt/2018-02-01/web/apps.go
Created to accumulate context: web/resource-manager
=> [AutoPR] web/resource-manager

services/cognitiveservices/v2.0/luis/runtime/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3022
=> [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Update sentiment signature in the endpoint reponse

profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3029
=> [AutoPR hanaonazure/resource-manager] Update Swagger constraints to allow HANA Very Large Instances

profiles/preview/preview/resources/mgmt/management/models.go, services/preview/resources/mgmt/2018-01-01-preview/management/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3041
=> [AutoPR managementgroups/resource-manager] Fix error in the possible values for an enum - Management Groups

services/cognitiveservices/v2.0/luis/runtime/models.go
Created to accumulate context: cognitiveservices/data-plane/LUIS/Runtime
=> [AutoPR] cognitiveservices/data-plane/LUIS/Runtime

services/storage/mgmt/2018-02-01/storage/usage.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3014
=> [AutoPR storage/resource-manager] [Storage] Add Get Location Usage support

profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to accumulate context: hanaonazure/resource-manager
=> [AutoPR] hanaonazure/resource-manager

profiles/preview/preview/resources/mgmt/management/models.go, services/preview/resources/mgmt/2018-01-01-preview/management/models.go
Created to accumulate context: managementgroups/resource-manager
=> [AutoPR] managementgroups/resource-manager

services/batchai/mgmt/2018-05-01/batchai/experiments.go, services/batchai/mgmt/2018-05-01/batchai/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3038
=> [AutoPR batchai/resource-manager] BatchAI. Several fixes

profiles/preview/preview/datafactory/mgmt/datafactory/models.go, profiles/preview/trafficmanager/mgmt/trafficmanager/models.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3008
=> [AutoPR datafactory/resource-manager] [DataFactory] blob events trigger

profiles/latest/datalake/analytics/catalog/models.go, profiles/preview/datalake/analytics/catalog/models.go, services/datalake/analytics/2016-11-01-preview/catalog/catalog.go, services/datalake/analytics/2016-11-01-preview/catalog/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3013
=> [AutoPR datalake-analytics/data-plane] [ADLA] - Catalog - Support table preview

profiles/preview/cognitiveservices/customvision/prediction/models.go, profiles/preview/cognitiveservices/customvision/training/models.go, services/cognitiveservices/v1.1/customvision/prediction/client.go, services/cognitiveservices/v1.1/customvision/prediction/models.go, services/cognitiveservices/v1.1/customvision/prediction/version.go, services/cognitiveservices/v1.2/customvision/training/client.go, services/cognitiveservices/v1.2/customvision/training/models.go, services/cognitiveservices/v1.2/customvision/training/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3026
=> [AutoPR cognitiveservices/data-plane/CustomVision/Prediction/cognitiveservices/data-plane/CustomVision/Training] Add Custom vision 2.0 Swagger

services/batchai/mgmt/2018-05-01/batchai/experiments.go, services/batchai/mgmt/2018-05-01/batchai/models.go
Created to accumulate context: batchai/resource-manager
=> [AutoPR] batchai/resource-manager

profiles/latest/eventgrid/eventgrid/models.go, profiles/preview/eventgrid/eventgrid/models.go, services/eventgrid/2018-01-01/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3097
=> [AutoPR eventgrid/data-plane] Adding Media Services Event Grid schema

profiles/latest/compute/mgmt/compute/models.go, profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2018-04-01/compute/disks.go, services/compute/mgmt/2018-04-01/compute/models.go, services/compute/mgmt/2018-04-01/compute/snapshots.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3053
=> [AutoPR compute/resource-manager] Upgrade Compute API version and Fix the response of POST response

services/containerservice/mgmt/2017-08-31/containerservice/managedclusters.go, services/containerservice/mgmt/2017-09-30/containerservice/managedclusters.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3098
=> [AutoPR containerservices/resource-manager] [AKS] add POST endpoint for fetching accessProfiles

services/containerservice/mgmt/2017-08-31/containerservice/managedclusters.go, services/containerservice/mgmt/2017-09-30/containerservice/managedclusters.go
Created to accumulate context: containerservices/resource-manager
=> [AutoPR] containerservices/resource-manager

profiles/latest/cognitiveservices/computervision/models.go, profiles/preview/cognitiveservices/computervision/models.go, services/cognitiveservices/v1.0/computervision/client.go, services/cognitiveservices/v1.0/computervision/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3090
=> [AutoPR cognitiveservices/data-plane/ComputerVision] Update CognitiveService ComputerVision Swagger for new extensions

services/appinsights/mgmt/2015-05-01/insights/webtests.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3126
=> [AutoPR applicationinsights/resource-manager] [AppInsights] Added webtests-by-component API to 2015-05-01

services/keyvault/2016-10-01/keyvault/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3120
=> [AutoPR keyvault/data-plane] Small doc tweaks

services/keyvault/2016-10-01/keyvault/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3136
=> [AutoPR keyvault/data-plane] RSA key size examples, ECC descriptions

services/keyvault/2016-10-01/keyvault/models.go
Created to accumulate context: keyvault/data-plane
=> [AutoPR] keyvault/data-plane

profiles/latest/cognitiveservices/computervision/models.go, profiles/preview/cognitiveservices/computervision/models.go, services/cognitiveservices/v1.0/computervision/client.go, services/cognitiveservices/v1.0/computervision/models.go
Created to accumulate context: cognitiveservices/data-plane/ComputerVision
=> [AutoPR] cognitiveservices/data-plane/ComputerVision

services/network/mgmt/2018-04-01/network/models.go, services/network/mgmt/2018-04-01/network/virtualnetworkgateways.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3163
=> [AutoPR network/resource-manager] reverted methods removal

profiles/latest/compute/mgmt/compute/models.go, profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2018-04-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3159
=> [AutoPR compute/resource-manager] [Disk swagger] Removing resourceUpdate, adding contents to diskupdate and snapshotupdate

services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessmentrulebaselines.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3143
=> [AutoPR sql/resource-manager] Adding new value to VA baseline name

profiles/latest/compute/mgmt/compute/models.go, profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2018-04-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3152
=> [AutoPR compute/resource-manager] [Compute] Fix List VM Extension API name, description updates and other fixes.

services/eventgrid/2018-01-01/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3174
=> [AutoPR eventgrid/data-plane] Replacing # with &#35;

profiles/preview/preview/iotcentral/mgmt/iotcentral/models.go, services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/apps.go, services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/client.go, services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/operations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3185
=> [AutoPR iotcentral/resource-manager] Remove subscriptionId uuid format for IotCentral

profiles/preview/preview/iotcentral/mgmt/iotcentral/models.go, services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/apps.go, services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/client.go, services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/operations.go
Created to accumulate context: iotcentral/resource-manager
=> [AutoPR] iotcentral/resource-manager

services/keyvault/2015-06-01/keyvault/models.go, services/keyvault/2016-10-01/keyvault/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3199
=> [AutoPR keyvault/data-plane] [KeyVault] Adding descriptions to JsonWebKey kty values

services/keyvault/2015-06-01/keyvault/models.go, services/keyvault/2016-10-01/keyvault/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3198
=> [AutoPR keyvault/data-plane] [KeyVault] Adding crv to KeyProperties for EC certificate support

services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2906
=> [AutoPR datafactory/resource-manager] [Data Factory]Add schema mapping for hierarchical data

services/network/mgmt/2015-06-15/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3200
=> [AutoPR network/resource-manager] Add primary flag to 2015-06-15  NetworkInterfaceIPConfiguration 

services/resources/mgmt/2018-03-01/policy/definitions.go, services/resources/mgmt/2018-03-01/policy/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3209
=> [AutoPR resources/resource-manager] Minor updates to description properties to improve docs

services/dns/mgmt/2016-04-01/dns/recordsets.go, services/dns/mgmt/2016-04-01/dns/zones.go, services/dns/mgmt/2017-09-01/dns/recordsets.go, services/dns/mgmt/2017-09-01/dns/zones.go, services/dns/mgmt/2017-10-01/dns/recordsets.go, services/dns/mgmt/2017-10-01/dns/zones.go, services/preview/dns/mgmt/2015-05-04-preview/dns/recordsets.go, services/preview/dns/mgmt/2015-05-04-preview/dns/zones.go, services/preview/dns/mgmt/2018-03-01-preview/dns/recordsets.go, services/preview/dns/mgmt/2018-03-01-preview/dns/zones.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3219
=> [AutoPR dns/resource-manager] Move DNS to use the common definition for resource groups

profiles/preview/reservations/mgmt/reservations/models.go, services/reservations/mgmt/2018-06-01/reservations/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3220
=> [AutoPR reservations/resource-manager] Reservations RP: adding x-ms-enum

services/resources/mgmt/2018-03-01/policy/definitions.go, services/resources/mgmt/2018-03-01/policy/models.go
Created to accumulate context: resources/resource-manager
=> [AutoPR] resources/resource-manager

services/dns/mgmt/2016-04-01/dns/recordsets.go, services/dns/mgmt/2016-04-01/dns/zones.go, services/dns/mgmt/2017-09-01/dns/recordsets.go, services/dns/mgmt/2017-09-01/dns/zones.go, services/dns/mgmt/2017-10-01/dns/recordsets.go, services/dns/mgmt/2017-10-01/dns/zones.go, services/preview/dns/mgmt/2015-05-04-preview/dns/recordsets.go, services/preview/dns/mgmt/2015-05-04-preview/dns/zones.go, services/preview/dns/mgmt/2018-03-01-preview/dns/recordsets.go, services/preview/dns/mgmt/2018-03-01-preview/dns/zones.go
Created to accumulate context: dns/resource-manager
=> [AutoPR] dns/resource-manager

services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3240
=> [AutoPR sql/resource-manager] adding new state value to keep backward competiblity

profiles/preview/reservations/mgmt/reservations/models.go, services/reservations/mgmt/2018-06-01/reservations/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3235
=> [AutoPR reservations/resource-manager] Reservations RP: adding x-ms-enum and changing some enums to type string

profiles/preview/preview/operationsmanagement/mgmt/operationsmanagement/models.go, services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/models.go, services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/solutions.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3226
=> [AutoPR operationsmanagement/resource-manager] Change Response for Solution PUT call

profiles/preview/preview/monitor/mgmt/insights/models.go, services/preview/monitor/mgmt/2018-03-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3249
=> [AutoPR monitor/resource-manager] Changing Case

services/operationalinsights/v1/operationalinsights/client.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3244
=> [AutoPR operationalinsights/data-plane] Add nodejs generation for Operational Insights

profiles/preview/preview/operationsmanagement/mgmt/operationsmanagement/models.go, services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/models.go, services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/solutions.go
Created to accumulate context: operationsmanagement/resource-manager
=> [AutoPR] operationsmanagement/resource-manager

services/operationalinsights/v1/operationalinsights/client.go
Created to accumulate context: operationalinsights/data-plane
=> [AutoPR] operationalinsights/data-plane

services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccounts.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3233
=> [AutoPR cosmos-db/resource-manager] Cosmos DB - POST operation for retrieving read only keys

services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to accumulate context: sql/resource-manager
=> [AutoPR] sql/resource-manager

services/logic/mgmt/2016-06-01/logic/agreements.go, services/logic/mgmt/2016-06-01/logic/maps.go, services/logic/mgmt/2016-06-01/logic/partners.go, services/logic/mgmt/2016-06-01/logic/schemas.go, services/logic/mgmt/2016-06-01/logic/sessions.go, services/logic/mgmt/2016-06-01/logic/workflowrunactions.go, services/logic/mgmt/2016-06-01/logic/workflowruns.go, services/logic/mgmt/2016-06-01/logic/workflows.go, services/logic/mgmt/2016-06-01/logic/workflowtriggerhistories.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3263
=> [AutoPR logic/resource-manager] Adding in description of available filter options

README.md
Thank you @devigned!
cc @sptramer
=> add Service Bus to list of Azure packages

profiles/preview/reservations/mgmt/reservations/models.go, services/reservations/mgmt/2018-06-01/reservations/models.go
Created to accumulate context: reservations/resource-manager
=> [AutoPR] reservations/resource-manager

services/logic/mgmt/2016-06-01/logic/agreements.go, services/logic/mgmt/2016-06-01/logic/maps.go, services/logic/mgmt/2016-06-01/logic/partners.go, services/logic/mgmt/2016-06-01/logic/schemas.go, services/logic/mgmt/2016-06-01/logic/sessions.go, services/logic/mgmt/2016-06-01/logic/workflowrunactions.go, services/logic/mgmt/2016-06-01/logic/workflowruns.go, services/logic/mgmt/2016-06-01/logic/workflows.go, services/logic/mgmt/2016-06-01/logic/workflowtriggerhistories.go
Created to accumulate context: logic/resource-manager
=> [AutoPR] logic/resource-manager

services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccounts.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3266
=> [AutoPR cosmos-db/resource-manager] Fix Java multi api namespace for cosmos DB

services/cognitiveservices/v2.0/computervision/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3259
=> [AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision add tag.hint

profiles/preview/preview/keyvault/keyvault/models.go, services/keyvault/2016-10-01/keyvault/models.go, services/preview/keyvault/v7.0/keyvault/client.go, services/preview/keyvault/v7.0/keyvault/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3277
=> [AutoPR keyvault/data-plane] EC curve and algorithm name updates

services/preview/apimanagement/mgmt/2018-01-01/apimanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3272
=> [AutoPR apimanagement/resource-manager] Fix contract for Error in OperationResultContract

Gopkg.lock, Gopkg.toml
=> update go-autorest dependency

services/preview/storage/mgmt/2018-03-01-preview/storage/models.go, services/storage/mgmt/2018-02-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3289
=> [AutoPR storage/resource-manager] [Storage] Support HDFS feature and web endpoint in Account properties 

services/operationalinsights/v1/operationalinsights/client.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3269
=> [AutoPR operationalinsights/data-plane] Update Java configuration for Log Analytics

services/preview/storage/mgmt/2018-03-01-preview/storage/models.go, services/storage/mgmt/2018-02-01/storage/models.go
Created to accumulate context: storage/resource-manager
=> [AutoPR] storage/resource-manager

services/preview/containerregistry/mgmt/2018-02-01/containerregistry/buildtasks.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3303
=> [AutoPR containerregistry/resource-manager] [ACR] Add 2018-02-preview version to Java SDK

services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3313
=> [AutoPR containerregistry/resource-manager] [ACR] Fix list builds odata query

profiles/preview/preview/signalr/mgmt/signalr/models.go, services/preview/signalr/mgmt/2018-03-01-preview/signalr/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3318
=> [AutoPR signalr/resource-manager] Add a new tier for Azure SignalR serivce

services/servicebus/mgmt/2017-04-01/servicebus/models.go, services/servicebus/mgmt/2017-04-01/servicebus/queues.go, services/servicebus/mgmt/2017-04-01/servicebus/rules.go, services/servicebus/mgmt/2017-04-01/servicebus/subscriptions.go, services/servicebus/mgmt/2017-04-01/servicebus/topics.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3314
=> [AutoPR servicebus/resource-manager] ServiceBus: Added property pendingReplicationOperationsCount to GeoDR and Migration

profiles/latest/advisor/mgmt/advisor/models.go, profiles/preview/advisor/mgmt/advisor/models.go, services/advisor/mgmt/2017-04-19/advisor/models.go, services/advisor/mgmt/2017-04-19/advisor/recommendations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3213
=> [AutoPR advisor/resource-manager] Add C# SDK generation settings for Advisor

services/servicebus/mgmt/2017-04-01/servicebus/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3330
=> [AutoPR servicebus/resource-manager] ServiceBus: Removed space from pendingReplicationOperationsCount

profiles/preview/batchai/mgmt/batchai/models.go, services/batchai/mgmt/2018-05-01/batchai/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3328
=> [AutoPR batchai/resource-manager] Rename MPI to CustomMPI to match Batch AI service

services/eventhub/mgmt/2017-04-01/eventhub/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3329
=> [AutoPR eventhub/resource-manager] EventHub: Removed space from pendingReplicationOperationsCount

profiles/latest/advisor/mgmt/advisor/models.go, profiles/preview/advisor/mgmt/advisor/models.go, services/advisor/mgmt/2017-04-19/advisor/models.go, services/advisor/mgmt/2017-04-19/advisor/recommendations.go
Created to accumulate context: advisor/resource-manager
=> [AutoPR] advisor/resource-manager

profiles/latest/postgresql/mgmt/postgresql/models.go, profiles/preview/postgresql/mgmt/postgresql/models.go, services/postgresql/mgmt/2017-12-01/postgresql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3355
=> [AutoPR postgresql/resource-manager] Add support for PG 10

services/preview/botservice/mgmt/2017-12-01/botservices/botconnection.go, services/preview/botservice/mgmt/2017-12-01/botservices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3280
=> [AutoPR botservice/resource-manager] misc fixes to oauth related api's on botservice swagger

profiles/latest/postgresql/mgmt/postgresql/models.go, profiles/preview/postgresql/mgmt/postgresql/models.go, services/postgresql/mgmt/2017-12-01/postgresql/models.go
Created to accumulate context: postgresql/resource-manager
=> [AutoPR] postgresql/resource-manager

services/batch/2017-05-01.5.0/batch/account.go, services/batch/2017-05-01.5.0/batch/application.go, services/batch/2017-05-01.5.0/batch/certificate.go, services/batch/2017-05-01.5.0/batch/computenode.go, services/batch/2017-05-01.5.0/batch/file.go, services/batch/2017-05-01.5.0/batch/job.go, services/batch/2017-05-01.5.0/batch/jobschedule.go, services/batch/2017-05-01.5.0/batch/pool.go, services/batch/2017-05-01.5.0/batch/task.go, services/batch/2018-03-01.6.1/batch/account.go, services/batch/2018-03-01.6.1/batch/application.go, services/batch/2018-03-01.6.1/batch/certificate.go, services/batch/2018-03-01.6.1/batch/computenode.go, services/batch/2018-03-01.6.1/batch/file.go, services/batch/2018-03-01.6.1/batch/job.go, services/batch/2018-03-01.6.1/batch/jobschedule.go, services/batch/2018-03-01.6.1/batch/models.go, services/batch/2018-03-01.6.1/batch/pool.go, services/batch/2018-03-01.6.1/batch/task.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3320
=> [AutoPR batch/data-plane] Update documentation of possible errors and size limits for Batch

profiles/preview/resources/mgmt/resources/models.go, services/resources/mgmt/2018-05-01/resources/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3283
=> [AutoPR resources/resource-manager] Add userAssignedIdentities

profiles/preview/datafactory/mgmt/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go, services/datafactory/mgmt/2018-06-01/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3345
=> [AutoPR datafactory/resource-manager] [ADF v2]Add integration runtime sharing feature.

profiles/latest/search/mgmt/search/models.go, profiles/preview/search/mgmt/search/models.go, services/search/mgmt/2015-08-19/search/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3377
=> [AutoPR search/resource-manager] Azure Search: Add resource identity (MSI) support

services/preview/automation/mgmt/2018-01-preview/automation/nodecountinformation.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3404
=> [AutoPR automation/resource-manager] Add x-ms-parameter-location property

profiles/latest/search/mgmt/search/models.go, profiles/preview/search/mgmt/search/models.go, services/search/mgmt/2015-08-19/search/models.go
Created to accumulate context: search/resource-manager
=> [AutoPR] search/resource-manager

profiles/latest/search/mgmt/search/models.go, profiles/preview/search/mgmt/search/models.go, services/search/mgmt/2015-08-19/search/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3397
=> [AutoPR search/resource-manager] Bump minor version in search management NPM package

services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to accumulate context: hdinsight/resource-manager
=> [AutoPR] hdinsight/resource-manager

services/compute/mgmt/2018-06-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3406
=> [AutoPR compute/resource-manager] Add missing ScaleSet properties

profiles/preview/preview/automation/mgmt/automation/models.go, services/automation/mgmt/2015-10-31/automation/models.go, services/automation/mgmt/2015-10-31/automation/runbook.go, services/automation/mgmt/2015-10-31/automation/runbookdraft.go, services/preview/automation/mgmt/2017-05-15-preview/automation/job.go, services/preview/automation/mgmt/2017-05-15-preview/automation/models.go, services/preview/automation/mgmt/2017-05-15-preview/automation/runbook.go, services/preview/automation/mgmt/2017-05-15-preview/automation/runbookdraft.go, services/preview/automation/mgmt/2018-01-preview/automation/job.go, services/preview/automation/mgmt/2018-01-preview/automation/models.go, services/preview/automation/mgmt/2018-01-preview/automation/nodecountinformation.go, services/preview/automation/mgmt/2018-01-preview/automation/runbook.go, services/preview/automation/mgmt/2018-01-preview/automation/runbookdraft.go
Created to accumulate context: automation/resource-manager
=> [AutoPR] automation/resource-manager

services/preview/resources/mgmt/2018-03-01-preview/management/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3370
=> [AutoPR managementgroups/resource-manager] Updating 2018-03-01-preview to include a few extra fields and parameters

services/preview/apimanagement/mgmt/2018-01-01/apimanagement/models.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3430
=> [AutoPR apimanagement/resource-manager] Add revision and Version Description to Contract

services/automation/mgmt/2015-10-31/automation/runbookdraft.go, services/preview/automation/mgmt/2017-05-15-preview/automation/runbookdraft.go, services/preview/automation/mgmt/2018-01-preview/automation/nodecountinformation.go, services/preview/automation/mgmt/2018-01-preview/automation/runbookdraft.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3420
=> [AutoPR automation/resource-manager] Changing schema from string to file

README.md
=> Fix spelling typo in README.md

profiles/preview/web/mgmt/web/models.go, services/web/mgmt/2018-02-01/web/apps.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3444
=> [AutoPR web/resource-manager] [Do Not Merge] Add API for adding external storage account configurations to a web app

services/compute/mgmt/2015-06-15/compute/models.go, services/compute/mgmt/2016-03-30/compute/models.go, services/compute/mgmt/2017-03-30/compute/models.go, services/compute/mgmt/2018-06-01/compute/models.go, services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3462
=> [AutoPR compute/resource-manager] Fixing instance view object definition in VMSSVMProperties

profiles/preview/preview/monitor/mgmt/insights/models.go, services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go, services/preview/monitor/mgmt/2018-03-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3468
=> [AutoPR monitor/resource-manager] updated description of recurrent frequency

profiles/preview/cognitiveservices/computervision/models.go, services/cognitiveservices/v2.0/computervision/client.go, services/cognitiveservices/v2.0/computervision/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3440
=> [AutoPR cognitiveservices/data-plane/ComputerVision] Enable Computer Vision Client to customize endpoint.

profiles/preview/datafactory/mgmt/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go, services/datafactory/mgmt/2018-06-01/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3483
=> [AutoPR datafactory/resource-manager] Updating User Properties

profiles/latest/dns/mgmt/dns/models.go, profiles/preview/preview/dns/mgmt/dns/models.go, services/dns/mgmt/2016-04-01/dns/models.go, services/dns/mgmt/2016-04-01/dns/recordsets.go, services/dns/mgmt/2016-04-01/dns/zones.go, services/dns/mgmt/2017-09-01/dns/models.go, services/dns/mgmt/2017-09-01/dns/recordsets.go, services/dns/mgmt/2017-09-01/dns/zones.go, services/dns/mgmt/2017-10-01/dns/models.go, services/dns/mgmt/2017-10-01/dns/recordsets.go, services/dns/mgmt/2017-10-01/dns/zones.go, services/preview/dns/mgmt/2015-05-04-preview/dns/models.go, services/preview/dns/mgmt/2015-05-04-preview/dns/recordsets.go, services/preview/dns/mgmt/2015-05-04-preview/dns/zones.go, services/preview/dns/mgmt/2018-03-01-preview/dns/models.go, services/preview/dns/mgmt/2018-03-01-preview/dns/recordsets.go, services/preview/dns/mgmt/2018-03-01-preview/dns/zones.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3502
=> [AutoPR dns/resource-manager] Use common arm definitions for dns

services/network/mgmt/2016-03-30/network/models.go, services/network/mgmt/2016-06-01/network/models.go, services/network/mgmt/2018-04-01/network/models.go, services/network/mgmt/2018-04-01/network/vpnconnections.go, services/preview/network/mgmt/2015-05-01-preview/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3535
=> [AutoPR network/resource-manager] Python conf for Network 2018-06

services/automation/mgmt/2015-10-31/automation/runbookdraft.go, services/preview/automation/mgmt/2017-05-15-preview/automation/runbookdraft.go, services/preview/automation/mgmt/2018-01-preview/automation/runbookdraft.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3534
=> [AutoPR automation/resource-manager] Update automation management Node.js package version to 5.0.0-preview

services/cognitiveservices/v2.0/luis/runtime/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3456
=> [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Changing Entity Index to integer

services/cognitiveservices/v2.0/computervision/client.go, services/cognitiveservices/v2.0/computervision/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3486
=> [AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision: bug fixes for /describe and /analyze [breaking]

Gopkg.lock, services/preview/storage/mgmt/2018-03-01-preview/storage/models.go, services/storage/mgmt/2017-06-01/storage/models.go, services/storage/mgmt/2017-10-01/storage/models.go, services/storage/mgmt/2018-02-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3463
=> [AutoPR storage/resource-manager] [Storage] Set the SignedResource as optional in ListServiceSAS

Gopkg.lock, services/web/mgmt/2018-02-01/web/apps.go, services/web/mgmt/2018-02-01/web/appserviceenvironments.go, services/web/mgmt/2018-02-01/web/appserviceplans.go, services/web/mgmt/2018-02-01/web/recommendations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3550
=> [AutoPR web/resource-manager] Fix documentation issues with metrics APIs

Gopkg.lock
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3556
=> [AutoPR containerinstance/resource-manager] Add Contaienr Group Stop and Restart API

services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3389
=> [AutoPR servicefabricmesh/resource-manager] Azure Service Fabric Mesh Preview 2018-07-01 REST API specification

.travis.yml
=> update dep to v0.5.0

Gopkg.lock, profiles/preview/datafactory/mgmt/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go, services/datafactory/mgmt/2018-06-01/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3331
=> [AutoPR datafactory/resource-manager] add 2 storage linked service type: AzureBlobStorage, AzureTableStorage and support aad auth for AzureBlobStorage

Gopkg.lock, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3471
=> [AutoPR apimanagement/resource-manager] updated formatting for externalid description

services/datafactory/mgmt/2018-06-01/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3561
=> [AutoPR datafactory/resource-manager] [Datafactory] Remove readOnly flag on github hostName property

profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3570
=> [AutoPR hanaonazure/resource-manager] Added power state to Hana Instance

services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/applications.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/applications.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3565
=> [AutoPR hdinsight/resource-manager] [HDInsight] Fixed PUT application parameter

profiles/preview/web/mgmt/web/models.go, services/web/mgmt/2018-02-01/web/apps.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3459
=> [AutoPR web/resource-manager] Add API for adding external storage account configurations to a web app

Gopkg.lock, profiles/preview/azurestack/mgmt/azurestack/models.go, services/azurestack/mgmt/2017-06-01/azurestack/customersubscriptions.go, services/azurestack/mgmt/2017-06-01/azurestack/models.go, services/azurestack/mgmt/2017-06-01/azurestack/products.go, services/azurestack/mgmt/2017-06-01/azurestack/registrations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3506
=> [AutoPR azurestack/resource-manager] Fix AzureStack swagger specs lint errors

profiles/preview/preview/monitor/mgmt/insights/models.go, services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go, services/preview/monitor/mgmt/2018-03-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3586
=> [AutoPR monitor/resource-manager] [Monitor] Fix issue #3585: revert previous commit since it is a brealing change

Gopkg.lock
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3597
=> [AutoPR network/resource-manager] add x-ms-long-running-operation-options to query packet capture status

services/containerservice/mgmt/2017-07-01/containerservice/containerservices.go, services/containerservice/mgmt/2017-08-31/containerservice/containerservices.go, services/containerservice/mgmt/2017-08-31/containerservice/managedclusters.go, services/containerservice/mgmt/2017-09-30/containerservice/containerservices.go, services/containerservice/mgmt/2017-09-30/containerservice/managedclusters.go, services/containerservice/mgmt/2018-03-31/containerservice/containerservices.go, services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3591
=> [AutoPR containerservices/resource-manager] [AKS] regex bug fix for LinuxProfile.AdminUser

services/containerservice/mgmt/2018-03-31/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3606
=> [AutoPR containerservices/resource-manager] [AKS]modify credentialResults keyName to kubeconfigs

services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3609
=> [AutoPR apimanagement/resource-manager] Bug fix on readonly property

services/containerservice/mgmt/2018-03-31/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3613
=> [AutoPR containerservices/resource-manager] [AKS] fix CredentialResult value format

services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3589
=> [AutoPR web/resource-manager] Include DRSecondary endpoint for GetPublishingProfileXml

services/logic/mgmt/2016-06-01/logic/workflowtriggers.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3616
=> [AutoPR logic/resource-manager] Fix for extra / on the end of the triggers endpoint

services/compute/mgmt/2018-06-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3618
=> [AutoPR compute/resource-manager/network/resource-manager] Publicipprefixaugust

profiles/preview/preview/automation/mgmt/automation/models.go, services/preview/automation/mgmt/2017-05-15-preview/automation/models.go, services/preview/automation/mgmt/2018-01-preview/automation/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3624
=> [AutoPR automation/resource-manager] Updating SourceControlSyncJobs and SourceControlSyncJobStreams properties and examples. 

services/containerregistry/mgmt/2017-10-01/containerregistry/models.go, services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/registries.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3623
=> [AutoPR containerregistry/resource-manager] add option to import images from public registries

services/preview/sql/mgmt/2017-03-01-preview/sql/sensitivitylabels.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3627
=> [AutoPR sql/resource-manager] [DO NOT MERGE]

profiles/preview/web/mgmt/web/models.go, services/web/mgmt/2018-02-01/web/apps.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3560
=> [AutoPR web/resource-manager] WebApps - Add BackupName to backup API models

profiles/preview/preview/signalr/mgmt/signalr/models.go, services/preview/signalr/mgmt/2018-03-01-preview/signalr/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3686
=> [AutoPR signalr/resource-manager] return more perperties of SignalR resource

services/batch/2018-08-01.7.0/batch/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3701
=> [AutoPR batch/data-plane] Update Batch docs

profiles/preview/cdn/mgmt/cdn/models.go, services/cdn/mgmt/2017-10-12/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3628
=> [AutoPR cdn/resource-manager] adding standard_microsoft in pricing tier

profiles/preview/reservations/mgmt/reservations/models.go, services/reservations/mgmt/2018-06-01/reservations/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3690
=> [AutoPR reservations/resource-manager] Add new reserved resource type CosmosDb

services/compute/mgmt/2018-06-01/compute/virtualmachinesizes.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3722
=> [AutoPR compute/resource-manager] RDBug 13056055 - Update description to deprecated. 

profiles/preview/containerregistry/mgmt/containerregistry/models.go, services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3746
=> [AutoPR containerregistry/resource-manager] Renamed BuildTask to FileTask and RunTask to EncodedTask in Azure Container registry Build GA swagger

services/automation/mgmt/2015-10-31/automation/dscconfiguration.go, services/preview/automation/mgmt/2017-05-15-preview/automation/dscconfiguration.go, services/preview/automation/mgmt/2018-01-preview/automation/dscconfiguration.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3749
=> [AutoPR automation/resource-manager] Fixing the spec for DSCConfigurations.

profiles/preview/datafactory/mgmt/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimenodes.go, services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go, services/datafactory/mgmt/2018-06-01/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3445
=> [AutoPR datafactory/resource-manager] [Do not merge] [Data Factory] add tumbling window dependsOn property under stable

.travis.yml, Gopkg.lock, services/web/mgmt/2016-09-01/web/apps.go, services/web/mgmt/2018-02-01/web/apps.go, storage/authorization_test.go
=> Add Go 1.11 to CI and update dependencies.

services/web/mgmt/2016-09-01/web/apps.go, services/web/mgmt/2018-02-01/web/apps.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3744
=> [AutoPR network/resource-manager] Azure Firewall FQDN Tag top level resource

services/preview/botservice/mgmt/2018-07-12/botservices/bots.go, services/web/mgmt/2016-09-01/web/apps.go, services/web/mgmt/2018-02-01/web/apps.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3781
=> [AutoPR botservice/resource-manager] fix check name availabilty method for botservice

services/compute/mgmt/2015-06-15/compute/models.go, services/compute/mgmt/2016-03-30/compute/models.go, services/compute/mgmt/2017-03-30/compute/models.go, services/compute/mgmt/2017-12-01/compute/models.go, services/compute/mgmt/2018-04-01/compute/models.go, services/compute/mgmt/2018-06-01/compute/models.go, services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3814
=> [AutoPR compute/resource-manager] Fix description for disk size

profiles/preview/datafactory/mgmt/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3813
=> [AutoPR datafactory/resource-manager] [Datafactory] Update FactoryGitHubConfiguration discriminator value (#3643)

services/preview/botservice/mgmt/2018-07-12/botservices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3817
=> [AutoPR botservice/resource-manager] add security fields to directline channel site for botservice

services/containerservice/mgmt/2018-03-31/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3835
=> [AutoPR containerservices/resource-manager] [AKS] note that only one agent pool is currently supported

profiles/latest/resources/mgmt/locks/models.go, profiles/preview/resources/mgmt/locks/models.go, services/resources/mgmt/2016-09-01/locks/client.go, services/resources/mgmt/2016-09-01/locks/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3844
=> [AutoPR resources/resource-manager] Fix ARMViolation Error for Microsoft.Authorization

profiles/preview/preview/logic/mgmt/logic/models.go, services/preview/logic/mgmt/2018-07-01-preview/logic/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3775
=> [AutoPR logic/resource-manager] Change some string Microsoft.Logic modeled enums back into enums

profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2018-06-01/compute/disks.go, services/compute/mgmt/2018-06-01/compute/models.go, services/compute/mgmt/2018-06-01/compute/snapshots.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3854
=> [AutoPR compute/resource-manager] Swagger spec for disk.json + compute.json 2018-06

services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3874
=> [AutoPR adhybridhealthservice/resource-manager] Update ADHybridHealthService.json

services/datalake/analytics/2016-11-01/job/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3871
=> [AutoPR datalake-analytics/data-plane] Add 

services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go, services/sql/mgmt/2014-04-01/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3876
=> [AutoPR sql/resource-manager] Add algorithm types to threat detection disabled alerts description

services/preview/machinelearning/mgmt/2018-03-01-preview/services/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3910
=> [AutoPR machinelearningservices/resource-manager] Masable/update workspace

services/preview/machinelearning/mgmt/2018-03-01-preview/services/models.go
Created to accumulate context: machinelearningservices/resource-manager
=> [AutoPR] machinelearningservices/resource-manager

services/datalake/analytics/2016-11-01/job/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3903
=> [AutoPR dns/resource-manager]  Add readme.typescript.md for DNS

services/advisor/mgmt/2017-04-19/advisor/models.go, services/appinsights/v1/insights/models.go, services/cognitiveservices/v2.0/luis/authoring/models.go, services/cognitiveservices/v2.0/luis/runtime/models.go, services/datafactory/mgmt/2018-06-01/datafactory/models.go, services/graphrbac/1.6/graphrbac/models.go, services/policyinsights/mgmt/2018-04-04/policyinsights/models.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go, services/preview/machinelearning/mgmt/2017-08-01-preview/compute/models.go, services/preview/monitor/mgmt/2018-03-01/insights/models.go, services/preview/monitor/mgmt/2018-09-01/insights/models.go, services/preview/policyinsights/mgmt/2017-08-09-preview/policyinsights/models.go, services/preview/policyinsights/mgmt/2017-10-17-preview/policyinsights/models.go, services/preview/policyinsights/mgmt/2017-12-12-preview/policyinsights/models.go, services/preview/security/mgmt/2017-08-01-preview/security/models.go, services/scheduler/mgmt/2016-03-01/scheduler/models.go, services/storsimple1200series/mgmt/2016-10-01/storsimple/models.go, swagger_to_sdk_config.json
=> Update with latest generator

services/datalake/analytics/2016-11-01/job/models.go
Created to accumulate context: datalake-analytics/data-plane
=> [AutoPR] datalake-analytics/data-plane

services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3875
=> [AutoPR sql/resource-manager] Swagger Changes to Add DnsZonePartner and Collation into Managed Instance 

services/preview/monitor/2018-09-01-preview/monitor/metrics.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3945
=> [AutoPR monitor/data-plane] Update Azure metrics data plane swagger to address few doc generation bugs

services/preview/monitor/2018-09-01-preview/monitor/metrics.go
Created to accumulate context: monitor/data-plane
=> [AutoPR] monitor/data-plane

profiles/preview/databox/mgmt/databox/models.go, services/databox/mgmt/2018-01-01/databox/jobs.go, services/databox/mgmt/2018-01-01/databox/models.go, services/databox/mgmt/2018-01-01/databox/service.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3885
=> [AutoPR databox/resource-manager] specs changes for azure databox ga

services/storsimple1200series/mgmt/2016-10-01/storsimple/availableprovideroperations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3951
=> [AutoPR storSimple1200Series/resource-manager] Fixed GetOperations route to not have subId

services/datafactory/mgmt/2018-06-01/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/pipelineruns.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3917
=> [AutoPR datafactory/resource-manager] [Datafactory] Add SecureInput property to Activity. Add recursive option to cancel API 

services/compute/mgmt/2018-06-01/compute/galleries.go, services/compute/mgmt/2018-06-01/compute/galleryimages.go, services/compute/mgmt/2018-06-01/compute/galleryimageversions.go, services/compute/mgmt/2018-06-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3956
=> [AutoPR compute/resource-manager] More detail added to the descriptions.

services/resources/mgmt/2016-09-01/locks/client.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3960
=> [AutoPR resources/resource-manager] Fix typo, the provider should be Microsoft.Authorization

services/datalake/analytics/2016-11-01/job/models.go, services/preview/datalake/analytics/2015-11-01-preview/job/models.go, services/preview/datalake/analytics/2016-03-20-preview/job/models.go, services/preview/datalake/analytics/2017-09-01-preview/job/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3942
=> [AutoPR datalake-analytics/data-plane] Add hierarchyQueueNode into JobInformation(Basic)

services/storsimple1200series/mgmt/2016-10-01/storsimple/availableprovideroperations.go
Created to accumulate context: storSimple1200Series/resource-manager
=> [AutoPR] storSimple1200Series/resource-manager

profiles/preview/databox/mgmt/databox/models.go, services/databox/mgmt/2018-01-01/databox/jobs.go, services/databox/mgmt/2018-01-01/databox/models.go, services/databox/mgmt/2018-01-01/databox/service.go, swagger_to_sdk_config.json
Created to accumulate context: databox/resource-manager
=> [AutoPR] databox/resource-manager

profiles/latest/recoveryservices/mgmt/backup/models.go, profiles/preview/recoveryservices/mgmt/backup/models.go, services/recoveryservices/mgmt/2016-06-01/backup/models.go, services/recoveryservices/mgmt/2017-07-01/backup/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3975
=> [AutoPR recoveryservicesbackup/resource-manager] Move Go SDK config for back to its own config file

profiles/latest/recoveryservices/mgmt/backup/models.go, profiles/preview/recoveryservices/mgmt/backup/models.go, services/recoveryservices/mgmt/2016-06-01/backup/models.go, services/recoveryservices/mgmt/2017-07-01/backup/models.go
Created to accumulate context: recoveryservicesbackup/resource-manager
=> [AutoPR] recoveryservicesbackup/resource-manager

services/preview/automation/mgmt/2018-06-preview/automation/runbookdraft.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3913
=> [AutoPR automation/resource-manager] Quick fix to response type of runbookdraftcontent get

services/compute/mgmt/2015-06-15/compute/models.go, services/compute/mgmt/2016-03-30/compute/models.go, services/compute/mgmt/2017-03-30/compute/models.go, services/compute/mgmt/2017-12-01/compute/models.go, services/compute/mgmt/2018-04-01/compute/models.go, services/compute/mgmt/2018-06-01/compute/models.go, services/compute/mgmt/2018-10-01/compute/models.go, services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3983
=> [AutoPR compute/resource-manager] Swagger change for adding status to BootDiagnosticsInstanceView

services/web/mgmt/2018-02-01/web/client.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4010
=> [AutoPR web/resource-manager] Add Microsoft.Web georegions filter parameter LinuxDynamicWorkersEnabled

profiles/preview/datafactory/mgmt/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4025
=> [AutoPR datafactory/resource-manager] [Datafactory] Adding script actions support for HDI on demand linked service

profiles/preview/compute/mgmt/compute/models.go, services/compute/mgmt/2018-10-01/compute/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4031
=> [AutoPR compute/resource-manager] Add AutomaticOSUpgradeProperties in GET VMImageVersion API

services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4011
=> [AutoPR hdinsight/resource-manager] [HDInsight] Added additional parameters for security profile

profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4028
=> [AutoPR datafactory/resource-manager] Add Pipeline Variables / Set Variable Activity / Append Variable Activity

services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/models.go, services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/rollouts.go, services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/services.go, services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/steps.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4047
=> [AutoPR deploymentmanager/resource-manager] DeploymentManager: Fix property name and enhance descriptions

services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/models.go, services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/rollouts.go, services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/services.go, services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/steps.go
Created to accumulate context: deploymentmanager/resource-manager
=> [AutoPR] deploymentmanager/resource-manager

profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4046
=> [AutoPR keyvault/resource-manager] Add keyvault/resource-manager/readme.typescript.md

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/service_package_request.md
- Clarify feature request template that it is for SDK features.
=> Clarify feature request template

services/apimanagement/mgmt/2017-03-01/apimanagement/service.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/api.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/operation.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/product.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/subscription.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/tag.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4078
=> [AutoPR apimanagement/resource-manager] api management tags and subscriptions changes

profiles/latest/domainservices/mgmt/aad/models.go, profiles/preview/domainservices/mgmt/aad/models.go, services/domainservices/mgmt/2017-01-01/aad/domainserviceoperations.go, services/domainservices/mgmt/2017-01-01/aad/domainservices.go, services/domainservices/mgmt/2017-01-01/aad/models.go, services/domainservices/mgmt/2017-06-01/aad/domainserviceoperations.go, services/domainservices/mgmt/2017-06-01/aad/domainservices.go, services/domainservices/mgmt/2017-06-01/aad/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4055
=> [AutoPR domainservices/resource-manager] DomainServices: Add missing properties, add examples, and fix linting errors

profiles/latest/domainservices/mgmt/aad/models.go, profiles/preview/domainservices/mgmt/aad/models.go, services/domainservices/mgmt/2017-01-01/aad/domainserviceoperations.go, services/domainservices/mgmt/2017-01-01/aad/domainservices.go, services/domainservices/mgmt/2017-01-01/aad/models.go, services/domainservices/mgmt/2017-06-01/aad/domainserviceoperations.go, services/domainservices/mgmt/2017-06-01/aad/domainservices.go, services/domainservices/mgmt/2017-06-01/aad/models.go
Created to accumulate context: domainservices/resource-manager
=> [AutoPR] domainservices/resource-manager

services/preview/automation/mgmt/2018-06-preview/automation/models.go, services/preview/automation/mgmt/2018-06-preview/automation/runbook.go, services/preview/automation/mgmt/2018-06-preview/automation/runbookdraft.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4017
=> [AutoPR automation/resource-manager] Fix the runbook resource schema issues

profiles/preview/network/mgmt/network/models.go, services/network/mgmt/2018-08-01/network/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4050
=> [AutoPR network/resource-manager] change appgw custom error status code enum and fix a typo of customErrorConfigurations

profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4163
=> [AutoPR hdinsight/resource-manager] [HDInsight] Added support for MSI

services/preview/automation/mgmt/2018-01-15-preview/automation/version.go, services/preview/automation/mgmt/2018-06-30-preview/automation/models.go, services/preview/automation/mgmt/2018-06-30-preview/automation/runbook.go, services/preview/automation/mgmt/2018-06-30-preview/automation/runbookdraft.go, services/preview/automation/mgmt/2018-06-30-preview/automation/version.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4147
=> [AutoPR automation/resource-manager] Add automation/resource-manager/readme.typescript.md

profiles/latest/containerregistry/mgmt/containerregistry/models.go, profiles/preview/containerregistry/mgmt/containerregistry/models.go, profiles/preview/preview/containerregistry/mgmt/containerregistry/models.go, services/containerregistry/mgmt/2017-10-01/containerregistry/models.go, services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go, services/containerregistry/mgmt/2018-09-01/containerregistry/models.go, services/containerregistry/mgmt/2018-09-01/containerregistry/registries.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/registries.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4220
=> [AutoPR containerregistry/resource-manager] Revert the previous change: remove the identity properties

services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/backendpools.go, services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/client.go, services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/endpoints.go, services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontdoors.go, services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontendendpoints.go, services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/healthprobesettings.go, services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/loadbalancingsettings.go, services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/policies.go, services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/routingrules.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4185
=> [AutoPR frontdoor/resource-manager] Add frontdoor/resource-manager/readme.typescript.md

README.md
Travis configuration includes 1.11 as well but in the README file it was not mentioned.
=> Update README.md to mention testing with 1.11

profiles/preview/preview/datalake/analytics/job/models.go, services/preview/datalake/analytics/2017-09-01-preview/job/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4223
=> [AutoPR datalake-analytics/data-plane] Adding Scope job states to job spec

profiles/preview/preview/apimanagement/mgmt/apimanagement/models.go, services/preview/apimanagement/mgmt/2018-01-01/apimanagement/models.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4233
=> [AutoPR apimanagement/resource-manager] add openid connect in authentication settings

services/network/mgmt/2018-08-01/network/expressroutegateways.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4103
=> [AutoPR network/resource-manager] Remove error code from swagger

swagger_to_sdk_config.json
=> update swagger->sdk generator to latest version

profiles/latest/eventgrid/eventgrid/models.go, profiles/preview/eventgrid/eventgrid/models.go, services/eventgrid/2018-01-01/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4111
=> [AutoPR eventgrid/data-plane] Update the MediaServices.json file in the EventGrid DataPlane SDK

profiles/preview/preview/automation/mgmt/automation/models.go, services/automation/mgmt/2015-10-31/automation/runbookdraft.go, services/preview/automation/mgmt/2017-05-15-preview/automation/models.go, services/preview/automation/mgmt/2017-05-15-preview/automation/runbookdraft.go, services/preview/automation/mgmt/2018-01-15-preview/automation/dsccompilationjob.go, services/preview/automation/mgmt/2018-01-15-preview/automation/dscnodeconfiguration.go, services/preview/automation/mgmt/2018-01-15-preview/automation/models.go, services/preview/automation/mgmt/2018-01-15-preview/automation/runbookdraft.go, services/preview/automation/mgmt/2018-06-30-preview/automation/dsccompilationjob.go, services/preview/automation/mgmt/2018-06-30-preview/automation/dscnodeconfiguration.go, services/preview/automation/mgmt/2018-06-30-preview/automation/models.go, services/preview/automation/mgmt/2018-06-30-preview/automation/runbook.go, services/preview/automation/mgmt/2018-06-30-preview/automation/runbookdraft.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4247
=> [AutoPR automation/resource-manager] Updating sync type property from PartialSync to IncrementalSync.

services/preview/resources/mgmt/2016-09-01-preview/managedapplications/appliancedefinitions.go, services/preview/resources/mgmt/2016-09-01-preview/managedapplications/appliances.go, services/resources/mgmt/2015-11-01/resources/deployments.go, services/resources/mgmt/2015-11-01/resources/groups.go, services/resources/mgmt/2015-11-01/resources/resources.go, services/resources/mgmt/2016-02-01/resources/deployments.go, services/resources/mgmt/2016-02-01/resources/groups.go, services/resources/mgmt/2016-02-01/resources/resources.go, services/resources/mgmt/2016-07-01/resources/deployments.go, services/resources/mgmt/2016-07-01/resources/groups.go, services/resources/mgmt/2016-07-01/resources/resources.go, services/resources/mgmt/2016-09-01/resources/deployments.go, services/resources/mgmt/2016-09-01/resources/groups.go, services/resources/mgmt/2016-09-01/resources/resources.go, services/resources/mgmt/2017-05-10/resources/deployments.go, services/resources/mgmt/2017-05-10/resources/groups.go, services/resources/mgmt/2017-05-10/resources/resources.go, services/resources/mgmt/2017-09-01/managedapplications/applicationdefinitions.go, services/resources/mgmt/2017-09-01/managedapplications/applications.go, services/resources/mgmt/2018-02-01/resources/deployments.go, services/resources/mgmt/2018-02-01/resources/groups.go, services/resources/mgmt/2018-02-01/resources/resources.go, services/resources/mgmt/2018-05-01/resources/deployments.go, services/resources/mgmt/2018-05-01/resources/groups.go, services/resources/mgmt/2018-05-01/resources/resources.go, services/resources/mgmt/2018-06-01/managedapplications/applicationdefinitions.go, services/resources/mgmt/2018-06-01/managedapplications/applications.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4236
=> [AutoPR resources/resource-manager] added descriptions for filter and expand

services/eventgrid/mgmt/2018-01-01/eventgrid/eventsubscriptions.go, services/eventgrid/mgmt/2018-01-01/eventgrid/topics.go, services/preview/eventgrid/mgmt/2017-06-15-preview/eventgrid/eventsubscriptions.go, services/preview/eventgrid/mgmt/2017-06-15-preview/eventgrid/topics.go, services/preview/eventgrid/mgmt/2017-09-15-preview/eventgrid/eventsubscriptions.go, services/preview/eventgrid/mgmt/2017-09-15-preview/eventgrid/topics.go, services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/eventsubscriptions.go, services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/topics.go, services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/domains.go, services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/eventsubscriptions.go, services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/topics.go
Created to accumulate context: eventgrid/resource-manager
=> [AutoPR] eventgrid/resource-manager

profiles/preview/iotcentral/mgmt/iotcentral/models.go, services/iotcentral/mgmt/2018-09-01/iotcentral/apps.go, services/iotcentral/mgmt/2018-09-01/iotcentral/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4015
=> [AutoPR iotcentral/resource-manager] [Do not merge] IoTCentral - Add ARM endpoint, update model responses/inputs to align with expected values

services/resources/mgmt/2018-05-01/resources/groups.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4297
=> [AutoPR resources/resource-manager] added to description of allowed characters for resource group name

profiles/latest/eventgrid/eventgrid/models.go, profiles/preview/eventgrid/eventgrid/models.go, services/eventgrid/2018-01-01/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4260
=> [AutoPR eventgrid/data-plane] Added missing discriminator property to MediaJobOutput

profiles/preview/preview/monitor/mgmt/insights/models.go, services/preview/monitor/mgmt/2017-05-01-preview/insights/actiongroups.go, services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go, services/preview/monitor/mgmt/2018-03-01/insights/actiongroups.go, services/preview/monitor/mgmt/2018-03-01/insights/models.go, services/preview/monitor/mgmt/2018-09-01/insights/actiongroups.go, services/preview/monitor/mgmt/2018-09-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4268
=> [AutoPR monitor/resource-manager] add armRoleReceiver to ActionGroup API and update API version to 2018-09-01

profiles/latest/servicebus/mgmt/servicebus/models.go, profiles/preview/servicebus/mgmt/servicebus/models.go, services/servicebus/mgmt/2017-04-01/servicebus/models.go, services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4254
=> [AutoPR servicebus/resource-manager] ServiceBus : Added namespace Migrate API reported in ARMs Fundamental dashboard

profiles/preview/preview/automation/mgmt/automation/models.go, services/preview/automation/mgmt/2017-05-15-preview/automation/models.go, services/preview/automation/mgmt/2018-01-15-preview/automation/models.go, services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4303
=> [AutoPR automation/resource-manager] Reverting change: Replacing PartialSync for IncrementalSync for sync type and updating examples.

services/apimanagement/mgmt/2016-07-07/apimanagement/services.go, services/apimanagement/mgmt/2016-07-07/apimanagement/tenantconfiguration.go, services/apimanagement/mgmt/2016-10-10/apimanagement/services.go, services/apimanagement/mgmt/2016-10-10/apimanagement/tenantconfiguration.go, services/apimanagement/mgmt/2017-03-01/apimanagement/service.go, services/apimanagement/mgmt/2017-03-01/apimanagement/tenantconfiguration.go, services/preview/apimanagement/mgmt/2018-01-01/apimanagement/service.go, services/preview/apimanagement/mgmt/2018-01-01/apimanagement/tenantconfiguration.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/service.go, services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/tenantconfiguration.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4248
=> [AutoPR apimanagement/resource-manager] enableHttpCorrelationHeaders property is added to the Diagnostic entity

services/preview/datamigration/mgmt/2017-11-15-preview/datamigration/services.go, services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/services.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4240
=> [AutoPR datamigration/resource-manager] Updates to Schema migration, project files resource and MongoDb scenario.

services/consumption/mgmt/2018-10-01/consumption/marketplaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4327
=> [AutoPR consumption/resource-manager] Introducing Marketplaces at Management Group Level

README.md
=> Add documentation for built-in loggic facilities.

services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4340
=> [AutoPR sql/resource-manager] Update BlobAuditing swaggers to support Azure Monitor audit target  

CONTRIBUTING.md, README.md
=> Update changelog and add tracing docs

services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4364
=> [AutoPR hdinsight/resource-manager] [HDInsight] Fixed non-existent extra parameter (bug)

README.md
=> add README change from master

services/devtestlabs/mgmt/2016-05-15/dtl/customimages.go, services/devtestlabs/mgmt/2016-05-15/dtl/disks.go, services/devtestlabs/mgmt/2016-05-15/dtl/environments.go, services/devtestlabs/mgmt/2016-05-15/dtl/formulas.go, services/devtestlabs/mgmt/2016-05-15/dtl/globalschedules.go, services/devtestlabs/mgmt/2016-05-15/dtl/labs.go, services/devtestlabs/mgmt/2016-05-15/dtl/schedules.go, services/devtestlabs/mgmt/2016-05-15/dtl/users.go, services/devtestlabs/mgmt/2016-05-15/dtl/virtualmachines.go, services/devtestlabs/mgmt/2016-05-15/dtl/virtualmachineschedules.go, services/devtestlabs/mgmt/2016-05-15/dtl/virtualnetworks.go, services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/cost.go, services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/costinsight.go, services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/customimage.go, services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/formula.go, services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/lab.go, services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/schedule.go, services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/virtualmachine.go, services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/virtualnetwork.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4357
=> [AutoPR devtestlabs/resource-manager] Add Devtestlabs/2018-09-15

services/network/mgmt/2018-08-01/network/virtualnetworks.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4376
=> [AutoPR network/resource-manager] Move parameter to keep order in SDK

services/web/mgmt/2018-02-01/web/apps.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4363
=> [AutoPR web/resource-manager] Fix network trace API bugs (Retake)

profiles/preview/preview/visualstudio/mgmt/visualstudio/models.go, services/preview/visualstudio/mgmt/2014-04-01-preview/visualstudio/accounts.go, services/preview/visualstudio/mgmt/2014-04-01-preview/visualstudio/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4368
=> [AutoPR visualstudio/resource-manager] Added patch API to swagger doc in Visual studio RP

services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4389
=> [AutoPR containerregistry/resource-manager] ACR: Add contextAccessToken to Task step

profiles/latest/domainservices/mgmt/aad/models.go, profiles/preview/domainservices/mgmt/aad/models.go, services/domainservices/mgmt/2017-01-01/aad/domainservices.go, services/domainservices/mgmt/2017-01-01/aad/models.go, services/domainservices/mgmt/2017-06-01/aad/domainservices.go, services/domainservices/mgmt/2017-06-01/aad/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4353
=> [AutoPR domainservices/resource-manager] Domain Services Swagger: Fix Put and Patch Domain Service Input

profiles/preview/preview/visualstudio/mgmt/visualstudio/models.go, services/preview/visualstudio/mgmt/2014-04-01-preview/visualstudio/accounts.go, services/preview/visualstudio/mgmt/2014-04-01-preview/visualstudio/models.go
Created to accumulate context: visualstudio/resource-manager
=> [AutoPR] visualstudio/resource-manager

services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/client.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4400
=> [AutoPR datamigration/resource-manager] Fix Version value to fix Ruby SDK Generation

services/preview/cognitiveservices/v1.0/visualsearch/models.go
Created to accumulate context: cognitiveservices/data-plane/VisualSearch
=> [AutoPR] cognitiveservices/data-plane/VisualSearch

services/network/mgmt/2018-08-01/network/virtualnetworks.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4402
=> [AutoPR network/resource-manager] Add java multi api versions for network

services/preview/authorization/mgmt/2018-01-01-preview/authorization/classicadministrators.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/client.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/permissions.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/provideroperationsmetadata.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/roleassignments.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/roledefinitions.go, services/preview/authorization/mgmt/2018-09-01-preview/authorization/permissions.go, services/preview/authorization/mgmt/2018-09-01-preview/authorization/provideroperationsmetadata.go, services/preview/authorization/mgmt/2018-09-01-preview/authorization/roledefinitions.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4399
=> [AutoPR authorization/resource-manager] Grlin/adding principal typeto ra

profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4386
=> [AutoPR datafactory/resource-manager] Enable delete activity

services/network/mgmt/2018-08-01/network/virtualnetworks.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4420
=> [AutoPR network/resource-manager] [Network wathcer] add a new field trafficAnalyticsInterval for TA

services/preview/authorization/mgmt/2018-01-01-preview/authorization/classicadministrators.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/client.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/permissions.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/provideroperationsmetadata.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/roleassignments.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/roledefinitions.go, services/preview/authorization/mgmt/2018-09-01-preview/authorization/permissions.go, services/preview/authorization/mgmt/2018-09-01-preview/authorization/provideroperationsmetadata.go, services/preview/authorization/mgmt/2018-09-01-preview/authorization/roledefinitions.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4411
=> [AutoPR authorization/resource-manager] remove duplicate entry for Go SDK build

services/web/mgmt/2018-02-01/web/apps.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4291
=> [AutoPR web/resource-manager] WebApps: Snapshots API for DR stamps

services/web/mgmt/2018-02-01/web/apps.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4435
=> [AutoPR web/resource-manager] Add initial set for changes for ANT79

profiles/preview/containerinstance/mgmt/containerinstance/models.go, services/containerinstance/mgmt/2018-10-01/containerinstance/containergroups.go, services/containerinstance/mgmt/2018-10-01/containerinstance/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4423
=> [AutoPR containerinstance/resource-manager]   Azure Container Instance: Add start container group API

swagger_to_sdk_config.json
=> update swagger->sdk code generator

services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4448
=> [AutoPR web/resource-manager] Add GeoRegion property to DeletedSite model

services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4453
=> [AutoPR web/resource-manager] Add GeoRegion to DeletedSite Model

profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4424
=> [AutoPR datafactory/resource-manager] DataFactory: add table name in dataset

services/preview/authorization/mgmt/2018-01-01-preview/authorization/classicadministrators.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/client.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/permissions.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/provideroperationsmetadata.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/roleassignments.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/roledefinitions.go, services/preview/authorization/mgmt/2018-09-01-preview/authorization/permissions.go, services/preview/authorization/mgmt/2018-09-01-preview/authorization/provideroperationsmetadata.go, services/preview/authorization/mgmt/2018-09-01-preview/authorization/roledefinitions.go
Created to accumulate context: authorization/resource-manager
=> [AutoPR] authorization/resource-manager

services/preview/datalake/store/2015-10-01-preview/filesystem/filesystem.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4464
=> [AutoPR datalake-store/data-plane] Add maximum chunk size to data lake store docs.

profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/clusters.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/hdinsightapi/interfaces.go, services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/clusters.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/hdinsightapi/interfaces.go, services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4449
=> [AutoPR hdinsight/resource-manager] [HDInsight] - Support KV URL

services/cognitiveservices/v1.0/autosuggest/client.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4490
=> [AutoPR cognitiveservices/data-plane/AutoSuggest] Description of Autosuggest usage needs improvement.

services/cognitiveservices/v1.0/autosuggest/client.go
Created to accumulate context: cognitiveservices/data-plane/AutoSuggest
=> [AutoPR] cognitiveservices/data-plane/AutoSuggest

profiles/preview/preview/storagesync/mgmt/storagesync/models.go, services/preview/storagesync/mgmt/2018-10-01/storagesync/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4249
=> [AutoPR storagesync/resource-manager] Microsoft.StorageSync : Update ApiVersion 2018-10-01

profiles/preview/preview/blueprint/mgmt/blueprint/blueprintapi/models.go, services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/blueprintapi/interfaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4461
=> [AutoPR blueprint/resource-manager] split swagger to multiple area for easy upgrade

profiles/preview/preview/storagesync/mgmt/storagesync/models.go, services/preview/storagesync/mgmt/2018-10-01/storagesync/models.go
Created to accumulate context: storagesync/resource-manager
=> [AutoPR] storagesync/resource-manager

profiles/preview/preview/blueprint/mgmt/blueprint/blueprintapi/models.go, services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/blueprintapi/interfaces.go
Created to accumulate context: blueprint/resource-manager
=> [AutoPR] blueprint/resource-manager

services/network/mgmt/2018-08-01/network/networkapi/interfaces.go, services/network/mgmt/2018-08-01/network/virtualnetworks.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4497
=> [AutoPR network/resource-manager] Fixes the missing array for the header actions

services/cdn/mgmt/2016-10-02/cdn/customdomains.go, services/cdn/mgmt/2016-10-02/cdn/endpoints.go, services/cdn/mgmt/2016-10-02/cdn/models.go, services/cdn/mgmt/2016-10-02/cdn/profiles.go, services/cdn/mgmt/2017-04-02/cdn/customdomains.go, services/cdn/mgmt/2017-04-02/cdn/endpoints.go, services/cdn/mgmt/2017-04-02/cdn/models.go, services/cdn/mgmt/2017-04-02/cdn/profiles.go, services/cdn/mgmt/2017-10-12/cdn/customdomains.go, services/cdn/mgmt/2017-10-12/cdn/endpoints.go, services/cdn/mgmt/2017-10-12/cdn/models.go, services/cdn/mgmt/2017-10-12/cdn/profiles.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4516
=> [AutoPR cdn/resource-manager] typo: cdn/resource-manager/Microsoft.Cdn/cdn.json

services/cosmos-db/mgmt/2015-04-08/documentdb/collection.go, services/cosmos-db/mgmt/2015-04-08/documentdb/database.go, services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4513
=> [AutoPR cosmos-db/resource-manager] typo: cosmos-db/resource-manager/Microsoft.DocumentDB/cosmos-db.json

profiles/preview/datafactory/mgmt/datafactory/models.go, services/datafactory/mgmt/2018-06-01/datafactory/datafactoryapi/interfaces.go, services/datafactory/mgmt/2018-06-01/datafactory/factories.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3957
=> [AutoPR datafactory/resource-manager] [Datafactory]Adding get Dataplane access API

services/web/mgmt/2016-09-01/web/models.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4504
=> [AutoPR web/resource-manager] typo: Fix Microsoft.Web/CommonDefinitions.json

profiles/preview/databox/mgmt/databox/models.go, services/databox/mgmt/2018-01-01/databox/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4393
=> [AutoPR databox/resource-manager] DataBox : Swagger and example changes for next version of client DLL

services/web/mgmt/2016-09-01/web/models.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4527
=> [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web/AppServiceEnvironments

services/customerinsights/mgmt/2017-01-01/customerinsights/models.go, services/customerinsights/mgmt/2017-01-01/customerinsights/views.go, services/customerinsights/mgmt/2017-04-26/customerinsights/models.go, services/customerinsights/mgmt/2017-04-26/customerinsights/views.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4517
=> [AutoPR customer-insights/resource-manager] typo: Fix customer-insights/resource-manager/Microsoft.CustomerInsights/customer-insights

services/policyinsights/mgmt/2018-04-04/policyinsights/models.go, services/preview/policyinsights/mgmt/2017-08-09-preview/policyinsights/models.go, services/preview/policyinsights/mgmt/2017-10-17-preview/policyinsights/models.go, services/preview/policyinsights/mgmt/2017-12-12-preview/policyinsights/models.go, services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4535
=> [AutoPR policyinsights/resource-manager] typo: policyinsights/resource-manager/Microsoft.PolicyInsights/policyEvents

services/network/mgmt/2018-08-01/network/networkapi/interfaces.go, services/network/mgmt/2018-08-01/network/virtualnetworks.go, services/network/mgmt/2018-10-01/network/networkapi/interfaces.go, services/network/mgmt/2018-10-01/network/virtualnetworks.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4547
=> [AutoPR network/resource-manager] Ported fix from master branch

services/datalake/store/2016-11-01/filesystem/filesystem.go, services/preview/datalake/store/2015-10-01-preview/filesystem/filesystem.go, services/preview/datalake/store/2015-10-01-preview/filesystem/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4537
=> [AutoPR datalake-store/data-plane] typo: datalake-store/data-plane/Microsoft.DataLakeStore/filesystem

services/servicefabric/6.2/servicefabric/client.go, services/servicefabric/6.2/servicefabric/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4528
=> [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric/servicefabric

services/preview/apimanagement/ctrl/2017-03-01/apimanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4511
=> [AutoPR apimanagement/control-plane] typo: apimanagement/control-plane/Microsoft.ApiManagement/apimbackends.json

services/appinsights/mgmt/2015-05-01/insights/componentfeaturecapabilities.go, services/appinsights/mgmt/2015-05-01/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4552
=> [AutoPR applicationinsights/resource-manager] typo: applicationinsights/resource-manager/Microsoft.Insights/componentFeaturesAndPricing_API

services/preview/storage/mgmt/2018-03-01-preview/storage/blobcontainers.go, services/storage/mgmt/2018-02-01/storage/blobcontainers.go, services/storage/mgmt/2018-07-01/storage/blobcontainers.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4551
=> [AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage/blob

services/policyinsights/mgmt/2018-04-04/policyinsights/models.go, services/preview/policyinsights/mgmt/2017-08-09-preview/policyinsights/models.go, services/preview/policyinsights/mgmt/2017-10-17-preview/policyinsights/models.go, services/preview/policyinsights/mgmt/2017-12-12-preview/policyinsights/models.go, services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
Created to accumulate context: policyinsights/resource-manager
=> [AutoPR] policyinsights/resource-manager

services/servicefabric/6.2/servicefabric/client.go, services/servicefabric/6.2/servicefabric/models.go
Created to accumulate context: servicefabric/data-plane
=> [AutoPR] servicefabric/data-plane

services/customerinsights/mgmt/2017-01-01/customerinsights/models.go, services/customerinsights/mgmt/2017-01-01/customerinsights/views.go, services/customerinsights/mgmt/2017-04-26/customerinsights/models.go, services/customerinsights/mgmt/2017-04-26/customerinsights/views.go
Created to accumulate context: customer-insights/resource-manager
=> [AutoPR] customer-insights/resource-manager

services/datalake/store/2016-11-01/filesystem/filesystem.go, services/preview/datalake/store/2015-10-01-preview/filesystem/filesystem.go, services/preview/datalake/store/2015-10-01-preview/filesystem/models.go
Created to accumulate context: datalake-store/data-plane
=> [AutoPR] datalake-store/data-plane

services/preview/apimanagement/ctrl/2017-03-01/apimanagement/models.go
Created to accumulate context: apimanagement/control-plane
=> [AutoPR] apimanagement/control-plane

services/preview/storage/mgmt/2018-03-01-preview/storage/models.go, services/storage/mgmt/2016-05-01/storage/models.go, services/storage/mgmt/2016-12-01/storage/models.go, services/storage/mgmt/2017-06-01/storage/models.go, services/storage/mgmt/2017-10-01/storage/models.go, services/storage/mgmt/2018-02-01/storage/models.go, services/storage/mgmt/2018-07-01/storage/accounts.go, services/storage/mgmt/2018-07-01/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4549
=> [AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage/storage

services/preview/storage/mgmt/2018-03-01-preview/storage/blobcontainers.go, services/preview/storage/mgmt/2018-03-01-preview/storage/models.go, services/storage/mgmt/2016-05-01/storage/models.go, services/storage/mgmt/2016-12-01/storage/models.go, services/storage/mgmt/2017-06-01/storage/models.go, services/storage/mgmt/2017-10-01/storage/models.go, services/storage/mgmt/2018-02-01/storage/blobcontainers.go, services/storage/mgmt/2018-02-01/storage/models.go, services/storage/mgmt/2018-07-01/storage/accounts.go, services/storage/mgmt/2018-07-01/storage/blobcontainers.go, services/storage/mgmt/2018-07-01/storage/models.go
=> Restapi auto storage/resource manager

services/mediaservices/mgmt/2018-07-01/media/models.go, services/preview/mediaservices/mgmt/2018-03-30-preview/media/models.go, services/preview/mediaservices/mgmt/2018-06-01-preview/media/models.go
Created to accumulate context: mediaservices/resource-manager
=> [AutoPR] mediaservices/resource-manager

services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4536
=> [AutoPR datafactory/resource-manager] typo: datafactory/resource-manager/Microsoft.DataFactory/entityTypes/LinkedService

services/eventhub/mgmt/2017-04-01/eventhub/disasterrecoveryconfigs.go, services/eventhub/mgmt/2017-04-01/eventhub/models.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4553
=> [AutoPR eventhub/resource-manager] typo: eventhub/resource-manager/Microsoft.EventHub/EventHub

services/resources/mgmt/2018-05-01/resources/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4501
=> [AutoPR resources/resource-manager] Add type for DeploymentExtend and ResourceGroup

services/eventhub/mgmt/2017-04-01/eventhub/disasterrecoveryconfigs.go, services/eventhub/mgmt/2017-04-01/eventhub/models.go, services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go
Created to accumulate context: eventhub/resource-manager
=> [AutoPR] eventhub/resource-manager

services/appinsights/mgmt/2015-05-01/insights/componentfeaturecapabilities.go, services/appinsights/mgmt/2015-05-01/insights/models.go, services/appinsights/mgmt/2015-05-01/insights/webtests.go, services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go, services/preview/appinsights/v1/insights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4554
=> [AutoPR applicationinsights/resource-manager/applicationinsights/data-plane] typo: applicationinsights data-lane and resource-manager

services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/alerts.go, services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/smartgroups.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4515
=> [AutoPR alertsmanagement/resource-manager] typo: alertsmanagement/resource-manager/Microsoft.AlertsManagement/AlertsManagement.json

services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/alerts.go, services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/smartgroups.go
Created to accumulate context: alertsmanagement/resource-manager
=> [AutoPR] alertsmanagement/resource-manager

profiles/preview/cognitiveservices/qnamaker/models.go, profiles/preview/cognitiveservices/qnamaker/qnamakerapi/models.go, services/cognitiveservices/v4.0/qnamaker/endpointkeys.go, services/cognitiveservices/v4.0/qnamaker/qnamakerapi/interfaces.go
Created to accumulate context: cognitiveservices/data-plane/QnAMaker
=> [AutoPR] cognitiveservices/data-plane/QnAMaker

services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4587
=> [AutoPR adhybridhealthservice/resource-manager] Fix type-o in adhybridhealthservice model

services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
Created to accumulate context: adhybridhealthservice/resource-manager
=> [AutoPR] adhybridhealthservice/resource-manager

services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go, services/datafactory/mgmt/2018-06-01/datafactory/pipelines.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/integrationruntimes.go, services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4573
=> [AutoPR datafactory/resource-manager] typo: datafactory/resource-manager/Microsoft.DataFactory

services/graphrbac/1.6/graphrbac/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4507
=> [AutoPR graphrbac/data-plane] add customKeyIdentifier to password credential

profiles/preview/preview/storagesync/mgmt/storagesync/models.go, services/preview/storagesync/mgmt/2018-10-01/storagesync/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4565
=> [AutoPR storagesync/resource-manager] Microsoft.StorageSync - Fix Issue 4559 and other known problems with preview version

services/analysisservices/mgmt/2016-05-16/analysisservices/models.go, services/analysisservices/mgmt/2016-05-16/analysisservices/servers.go, services/analysisservices/mgmt/2017-07-14/analysisservices/models.go, services/analysisservices/mgmt/2017-07-14/analysisservices/servers.go, services/analysisservices/mgmt/2017-08-01/analysisservices/models.go, services/analysisservices/mgmt/2017-08-01/analysisservices/servers.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4583
=> [AutoPR analysisservices/resource-manager] typo: analysisservices/resource-manager/Microsoft.AnalysisServices

services/graphrbac/1.6/graphrbac/models.go
Created to accumulate context: graphrbac/data-plane
=> [AutoPR] graphrbac/data-plane

services/analysisservices/mgmt/2016-05-16/analysisservices/models.go, services/analysisservices/mgmt/2016-05-16/analysisservices/servers.go, services/analysisservices/mgmt/2017-07-14/analysisservices/models.go, services/analysisservices/mgmt/2017-07-14/analysisservices/servers.go, services/analysisservices/mgmt/2017-08-01/analysisservices/models.go, services/analysisservices/mgmt/2017-08-01/analysisservices/servers.go
Created to accumulate context: analysisservices/resource-manager
=> [AutoPR] analysisservices/resource-manager

profiles/preview/mediaservices/mgmt/media/models.go, services/mediaservices/mgmt/2018-07-01/media/accountfilters.go, services/mediaservices/mgmt/2018-07-01/media/assetfilters.go, services/mediaservices/mgmt/2018-07-01/media/jobs.go, services/mediaservices/mgmt/2018-07-01/media/mediaapi/interfaces.go, services/mediaservices/mgmt/2018-07-01/media/models.go, services/mediaservices/mgmt/2018-07-01/media/streaminglocators.go, services/mediaservices/mgmt/2018-07-01/media/streamingpolicies.go, services/mediaservices/mgmt/2018-07-01/media/transforms.go, services/preview/mediaservices/mgmt/2018-03-30-preview/media/models.go, services/preview/mediaservices/mgmt/2018-03-30-preview/media/streaminglocators.go, services/preview/mediaservices/mgmt/2018-03-30-preview/media/streamingpolicies.go, services/preview/mediaservices/mgmt/2018-06-01-preview/media/models.go, services/preview/mediaservices/mgmt/2018-06-01-preview/media/streaminglocators.go, services/preview/mediaservices/mgmt/2018-06-01-preview/media/streamingpolicies.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4483
=> [AutoPR mediaservices/resource-manager] [Portal Generated] Review request for Microsoft.Media to add version 2018-07-01

services/cdn/mgmt/2016-10-02/cdn/models.go, services/cdn/mgmt/2017-04-02/cdn/models.go, services/cdn/mgmt/2017-10-12/cdn/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4635
=> [AutoPR cdn/resource-manager] typo: Microsoft.Cdn

services/preview/botservice/mgmt/2017-12-01/botservice/models.go, services/preview/botservice/mgmt/2018-07-12/botservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4634
=> [AutoPR botservice/resource-manager] typo: Microsoft.BotService

services/batch/2017-05-01.5.0/batch/computenode.go, services/batch/2017-05-01.5.0/batch/job.go, services/batch/2017-05-01.5.0/batch/jobschedule.go, services/batch/2017-05-01.5.0/batch/models.go, services/batch/2017-05-01.5.0/batch/pool.go, services/batch/2018-03-01.6.1/batch/computenode.go, services/batch/2018-03-01.6.1/batch/job.go, services/batch/2018-03-01.6.1/batch/jobschedule.go, services/batch/2018-03-01.6.1/batch/models.go, services/batch/2018-03-01.6.1/batch/pool.go, services/batch/2018-08-01.7.0/batch/computenode.go, services/batch/2018-08-01.7.0/batch/job.go, services/batch/2018-08-01.7.0/batch/jobschedule.go, services/batch/2018-08-01.7.0/batch/models.go, services/batch/2018-08-01.7.0/batch/pool.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4631
=> [AutoPR batch/resource-manager/batch/data-plane] typo: Microsoft.Batch

services/preview/botservice/mgmt/2017-12-01/botservice/models.go, services/preview/botservice/mgmt/2018-07-12/botservice/models.go
Created to accumulate context: botservice/resource-manager
=> [AutoPR] botservice/resource-manager

services/compute/mgmt/2018-06-01/compute/models.go, services/compute/mgmt/2018-06-01/compute/virtualmachines.go, services/compute/mgmt/2018-06-01/compute/virtualmachinescalesets.go, services/compute/mgmt/2018-10-01/compute/models.go, services/compute/mgmt/2018-10-01/compute/virtualmachines.go, services/compute/mgmt/2018-10-01/compute/virtualmachinescalesets.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4644
=> [AutoPR compute/resource-manager] updated Reimage API documentation in compute json for ephemeral os disks

services/eventgrid/mgmt/2018-01-01/eventgrid/models.go, services/preview/eventgrid/mgmt/2017-06-15-preview/eventgrid/models.go, services/preview/eventgrid/mgmt/2017-09-15-preview/eventgrid/models.go, services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/models.go, services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4690
=> [AutoPR eventgrid/resource-manager] typo: eventgrid/Microsoft.EventGrid

services/datamigration/mgmt/2018-04-19/datamigration/models.go, services/datamigration/mgmt/2018-04-19/datamigration/tasks.go, services/preview/datamigration/mgmt/2017-11-15-preview/datamigration/models.go, services/preview/datamigration/mgmt/2017-11-15-preview/datamigration/tasks.go, services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/models.go, services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/tasks.go, services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go, services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/tasks.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4681
=> [AutoPR datamigration/resource-manager] typo: Microsoft.DataMigration

services/databox/mgmt/2018-01-01/databox/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4672
=> [AutoPR databox/resource-manager] typo: Microsoft.DataBox

services/compute/mgmt/2018-06-01/compute/models.go, services/compute/mgmt/2018-10-01/compute/models.go, services/containerservice/mgmt/2016-03-30/containerservice/models.go, services/containerservice/mgmt/2016-09-30/containerservice/models.go, services/containerservice/mgmt/2017-01-31/containerservice/models.go, services/preview/containerservice/mgmt/2015-11-01-preview/containerservice/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4659
=> [AutoPR compute/resource-manager] typo: Microsoft.ContainerService

services/cognitiveservices/v1.0/contentmoderator/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4650
=> [AutoPR cognitiveservices/data-plane/ContentModerator] typo: ContentModerator

services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go, services/preview/operationalinsights/mgmt/2015-11-01-preview/operationalinsights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4723
=> [AutoPR operationalinsights/resource-manager] typo: operationalinsights/resource-manager/Microsoft.OperationalInsights

services/keyvault/mgmt/2016-10-01/keyvault/models.go, services/keyvault/mgmt/2018-02-14/keyvault/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4701
=> [AutoPR keyvault/resource-manager] typo: resource-manager/Microsoft.KeyVault

services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccounts.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4665
=> [AutoPR cosmos-db/resource-manager] typo: Microsoft.DocumentDB

services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/models.go
Created to accumulate context: marketplaceordering/resource-manager
=> [AutoPR] marketplaceordering/resource-manager

services/keyvault/mgmt/2016-10-01/keyvault/models.go, services/keyvault/mgmt/2018-02-14/keyvault/models.go
Created to accumulate context: keyvault/resource-manager
=> [AutoPR] keyvault/resource-manager

services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4726
=> [AutoPR policyinsights/resource-manager] typo: policyinsights/resource-manager/Microsoft.PolicyInsights

services/preview/logic/mgmt/2015-08-01-preview/logic/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4708
=> [AutoPR logic/resource-manager] typo: logic/resource-manager/Microsoft.Logic

services/devtestlabs/mgmt/2016-05-15/dtl/models.go, services/devtestlabs/mgmt/2016-05-15/dtl/notificationchannels.go, services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4685
=> [AutoPR devtestlabs/resource-manager] typo: Microsoft.DevTestLab

services/consumption/mgmt/2017-11-30/consumption/models.go, services/consumption/mgmt/2017-11-30/consumption/usagedetails.go, services/consumption/mgmt/2018-01-31/consumption/marketplaces.go, services/consumption/mgmt/2018-01-31/consumption/models.go, services/consumption/mgmt/2018-03-31/consumption/costtags.go, services/consumption/mgmt/2018-03-31/consumption/marketplaces.go, services/consumption/mgmt/2018-03-31/consumption/models.go, services/consumption/mgmt/2018-03-31/consumption/reservationrecommendations.go, services/consumption/mgmt/2018-06-30/consumption/costtags.go, services/consumption/mgmt/2018-06-30/consumption/marketplaces.go, services/consumption/mgmt/2018-06-30/consumption/models.go, services/consumption/mgmt/2018-06-30/consumption/reservationrecommendations.go, services/consumption/mgmt/2018-08-31/consumption/marketplaces.go, services/consumption/mgmt/2018-08-31/consumption/models.go, services/consumption/mgmt/2018-08-31/consumption/reservationrecommendations.go, services/consumption/mgmt/2018-10-01/consumption/marketplaces.go, services/consumption/mgmt/2018-10-01/consumption/models.go, services/consumption/mgmt/2018-10-01/consumption/reservationrecommendations.go, services/preview/consumption/mgmt/2017-04-24-preview/consumption/usagedetails.go, services/preview/consumption/mgmt/2017-12-30-preview/consumption/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4660
=> [AutoPR consumption/resource-manager] typo: Microsoft.Consumption

services/cognitiveservices/v1.0/entitysearch/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4651
=> [AutoPR cognitiveservices/data-plane/EntitySearch] typo: cognitiveservices/data-plane/EntitySearch

services/azurestack/mgmt/2017-06-01/azurestack/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4611
=> [AutoPR azurestack/resource-manager] typo: Microsoft.AzureStack

services/devtestlabs/mgmt/2016-05-15/dtl/models.go, services/devtestlabs/mgmt/2016-05-15/dtl/notificationchannels.go, services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/models.go
Created to accumulate context: devtestlabs/resource-manager
=> [AutoPR] devtestlabs/resource-manager

services/consumption/mgmt/2017-11-30/consumption/models.go, services/consumption/mgmt/2017-11-30/consumption/usagedetails.go, services/consumption/mgmt/2018-01-31/consumption/marketplaces.go, services/consumption/mgmt/2018-01-31/consumption/models.go, services/consumption/mgmt/2018-03-31/consumption/costtags.go, services/consumption/mgmt/2018-03-31/consumption/marketplaces.go, services/consumption/mgmt/2018-03-31/consumption/models.go, services/consumption/mgmt/2018-03-31/consumption/reservationrecommendations.go, services/consumption/mgmt/2018-06-30/consumption/costtags.go, services/consumption/mgmt/2018-06-30/consumption/marketplaces.go, services/consumption/mgmt/2018-06-30/consumption/models.go, services/consumption/mgmt/2018-06-30/consumption/reservationrecommendations.go, services/consumption/mgmt/2018-08-31/consumption/marketplaces.go, services/consumption/mgmt/2018-08-31/consumption/models.go, services/consumption/mgmt/2018-08-31/consumption/reservationrecommendations.go, services/consumption/mgmt/2018-10-01/consumption/marketplaces.go, services/consumption/mgmt/2018-10-01/consumption/models.go, services/consumption/mgmt/2018-10-01/consumption/reservationrecommendations.go, services/preview/consumption/mgmt/2017-04-24-preview/consumption/usagedetails.go, services/preview/consumption/mgmt/2017-12-30-preview/consumption/models.go
Created to accumulate context: consumption/resource-manager
=> [AutoPR] consumption/resource-manager

services/cognitiveservices/v1.0/entitysearch/models.go
Created to accumulate context: cognitiveservices/data-plane/EntitySearch
=> [AutoPR] cognitiveservices/data-plane/EntitySearch

services/azurestack/mgmt/2017-06-01/azurestack/models.go
Created to accumulate context: azurestack/resource-manager
=> [AutoPR] azurestack/resource-manager

services/cognitiveservices/v1.0/imagesearch/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4652
=> [AutoPR cognitiveservices/data-plane/ImageSearch] typo: cognitiveservices/data-plane/ImageSearch

services/migrate/mgmt/2018-02-02/migrate/assessedmachines.go, services/migrate/mgmt/2018-02-02/migrate/assessments.go, services/migrate/mgmt/2018-02-02/migrate/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4716
=> [AutoPR migrate/resource-manager] typo: migrate/resource-manager/Microsoft.Migrate

services/recoveryservices/mgmt/2016-06-01/recoveryservices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4730
=> [AutoPR recoveryservices/resource-manager] typo: recoveryservices/resource-manager/Microsoft.RecoveryServices

services/dns/mgmt/2016-04-01/dns/recordsets.go, services/dns/mgmt/2016-04-01/dns/zones.go, services/dns/mgmt/2017-09-01/dns/recordsets.go, services/dns/mgmt/2017-09-01/dns/zones.go, services/dns/mgmt/2017-10-01/dns/recordsets.go, services/dns/mgmt/2017-10-01/dns/zones.go, services/preview/dns/mgmt/2015-05-04-preview/dns/models.go, services/preview/dns/mgmt/2018-03-01-preview/dns/recordsets.go, services/preview/dns/mgmt/2018-03-01-preview/dns/zones.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4686
=> [AutoPR dns/resource-manager] typo: dns/Microsoft.Network

services/cognitiveservices/v1.0/imagesearch/models.go
Created to accumulate context: cognitiveservices/data-plane/ImageSearch
=> [AutoPR] cognitiveservices/data-plane/ImageSearch

services/recoveryservices/mgmt/2016-06-01/backup/models.go, services/recoveryservices/mgmt/2016-06-01/backup/protecteditems.go, services/recoveryservices/mgmt/2016-12-01/backup/models.go, services/recoveryservices/mgmt/2017-07-01/backup/jobdetails.go, services/recoveryservices/mgmt/2017-07-01/backup/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4731
=> [AutoPR recoveryservicesbackup/resource-manager] typo: recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices

services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/managementassociations.go, services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4725
=> [AutoPR operationsmanagement/resource-manager] typo: operationsmanagement/resource-manager/Microsoft.OperationsManagement

services/migrate/mgmt/2018-02-02/migrate/assessedmachines.go, services/migrate/mgmt/2018-02-02/migrate/assessments.go, services/migrate/mgmt/2018-02-02/migrate/models.go
Created to accumulate context: migrate/resource-manager
=> [AutoPR] migrate/resource-manager

services/recoveryservices/mgmt/2016-06-01/recoveryservices/models.go
Created to accumulate context: recoveryservices/resource-manager
=> [AutoPR] recoveryservices/resource-manager

services/containerinstance/mgmt/2018-06-01/containerinstance/containergroups.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4661
=> [AutoPR containerinstance/resource-manager] typo: Microsoft.ConainterInstance

services/eventgrid/2018-01-01/eventgrid/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4687
=> [AutoPR eventgrid/data-plane] typo: Microsoft.Media

services/keyvault/2015-06-01/keyvault/models.go, services/keyvault/2016-10-01/keyvault/client.go, services/keyvault/2016-10-01/keyvault/models.go, services/keyvault/v7.0/keyvault/client.go, services/keyvault/v7.0/keyvault/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4700
=> [AutoPR keyvault/data-plane] typo: data-plane/Microsoft.KeyVault

services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/models.go
Created to accumulate context: mariadb/resource-manager
=> [AutoPR] mariadb/resource-manager

services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go, services/preview/cognitiveservices/mgmt/2016-02-01-preview/cognitiveservices/accounts.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4657
=> [AutoPR cognitiveservices/resource-manager] typo: Microsoft.CognitiveServices

services/notificationhubs/mgmt/2014-09-01/notificationhubs/models.go, services/notificationhubs/mgmt/2014-09-01/notificationhubs/namespaces.go, services/notificationhubs/mgmt/2016-03-01/notificationhubs/models.go, services/notificationhubs/mgmt/2016-03-01/notificationhubs/namespaces.go, services/notificationhubs/mgmt/2017-04-01/notificationhubs/models.go, services/notificationhubs/mgmt/2017-04-01/notificationhubs/namespaces.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4722
=> [AutoPR notificationhubs/resource-manager] typo: notificationhubs/resource-manager/Microsoft.NotificationHubs

services/costmanagement/mgmt/2018-05-31/costmanagement/billingaccountdimensions.go, services/costmanagement/mgmt/2018-05-31/costmanagement/models.go, services/costmanagement/mgmt/2018-05-31/costmanagement/resourcegroupdimensions.go, services/costmanagement/mgmt/2018-05-31/costmanagement/subscriptiondimensions.go, services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/billingaccountdimensions.go, services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/models.go, services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/reports.go, services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/resourcegroupdimensions.go, services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/subscriptiondimensions.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4668
=> [AutoPR cost-management/resource-manager] typo: Microsoft.CostManagement

services/datalake/store/2016-11-01/filesystem/filesystem.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4677
=> [AutoPR datalake-store/data-plane] typo: Microsoft.DataLakeStore

services/resources/mgmt/2015-11-01/resources/models.go, services/resources/mgmt/2016-02-01/resources/models.go, services/resources/mgmt/2016-07-01/resources/models.go, services/resources/mgmt/2016-09-01/links/resourcelinks.go, services/resources/mgmt/2016-09-01/resources/models.go, services/resources/mgmt/2016-09-01/resources/resources.go, services/resources/mgmt/2017-05-10/resources/models.go, services/resources/mgmt/2018-02-01/resources/models.go, services/resources/mgmt/2018-05-01/resources/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4755
=> [AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Resources

services/notificationhubs/mgmt/2014-09-01/notificationhubs/models.go, services/notificationhubs/mgmt/2014-09-01/notificationhubs/namespaces.go, services/notificationhubs/mgmt/2016-03-01/notificationhubs/models.go, services/notificationhubs/mgmt/2016-03-01/notificationhubs/namespaces.go, services/notificationhubs/mgmt/2017-04-01/notificationhubs/models.go, services/notificationhubs/mgmt/2017-04-01/notificationhubs/namespaces.go
Created to accumulate context: notificationhubs/resource-manager
=> [AutoPR] notificationhubs/resource-manager

services/costmanagement/mgmt/2018-05-31/costmanagement/billingaccountdimensions.go, services/costmanagement/mgmt/2018-05-31/costmanagement/models.go, services/costmanagement/mgmt/2018-05-31/costmanagement/resourcegroupdimensions.go, services/costmanagement/mgmt/2018-05-31/costmanagement/subscriptiondimensions.go, services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/billingaccountdimensions.go, services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/models.go, services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/reports.go, services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/resourcegroupdimensions.go, services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/subscriptiondimensions.go
Created to accumulate context: cost-management/resource-manager
=> [AutoPR] cost-management/resource-manager

services/search/mgmt/2015-08-19/search/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4758
=> [AutoPR search/resource-manager] typo: search/resource-manager/Microsoft.Search

services/redis/mgmt/2015-08-01/redis/models.go, services/redis/mgmt/2016-04-01/redis/models.go, services/redis/mgmt/2017-02-01/redis/models.go, services/redis/mgmt/2017-10-01/redis/models.go, services/redis/mgmt/2018-03-01/redis/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4751
=> [AutoPR redis/resource-manager] typo: redis/resource-manager/Microsoft.Cache

services/redis/mgmt/2015-08-01/redis/models.go, services/redis/mgmt/2016-04-01/redis/models.go, services/redis/mgmt/2017-02-01/redis/models.go, services/redis/mgmt/2017-10-01/redis/models.go, services/redis/mgmt/2018-03-01/redis/models.go
Created to accumulate context: redis/resource-manager
=> [AutoPR] redis/resource-manager

services/mysql/mgmt/2017-12-01/mysql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4718
=> [AutoPR mysql/resource-manager] typo: mysql/resource-manager/Microsoft.DBforMySQL

services/postgresql/mgmt/2017-12-01/postgresql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4727
=> [AutoPR postgresql/resource-manager] typo: postgresql/resource-manager/Microsoft.DBforPostgreSQL

services/preview/resources/mgmt/2018-03-01-preview/managementgroups/entities.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4709
=> [AutoPR managementgroups/resource-manager] typo: managementgroups/resource-manager/Microsoft.Management

services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4695
=> [AutoPR hanaonazure/resource-manager] typo: Microsoft.HanaOnAzure

services/preview/workloadmonitor/mgmt/2018-08-31-preview/workloadmonitor/models.go, services/preview/workloadmonitor/mgmt/2018-08-31-preview/workloadmonitor/notificationsettings.go, services/preview/workloadmonitor/mgmt/2018-08-31-preview/workloadmonitor/workloadmonitorapi/interfaces.go
Created to accumulate context: workloadmonitor/resource-manager
=> [AutoPR] workloadmonitor/resource-manager

services/mysql/mgmt/2017-12-01/mysql/models.go
Created to accumulate context: mysql/resource-manager
=> [AutoPR] mysql/resource-manager

services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4675
=> [AutoPR datafactory/resource-manager] typo: Microsoft.DataFactory

services/recoveryservices/mgmt/2016-08-10/siterecovery/models.go, services/recoveryservices/mgmt/2016-08-10/siterecovery/replicationjobs.go, services/recoveryservices/mgmt/2016-08-10/siterecovery/replicationstorageclassificationmappings.go, services/recoveryservices/mgmt/2016-08-10/siterecovery/replicationvcenters.go, services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go, services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationjobs.go, services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationstorageclassificationmappings.go, services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationvcenters.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4749
=> [AutoPR recoveryservicessiterecovery/resource-manager] typo: recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices

services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/models.go, services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/policies.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4692
=> [AutoPR frontdoor/resource-manager] typo: frontdoor/Microsoft.Network

services/preview/provisioningservices/mgmt/2017-08-21-preview/iothub/models.go, services/provisioningservices/mgmt/2017-11-15/iothub/dpscertificate.go, services/provisioningservices/mgmt/2017-11-15/iothub/models.go, services/provisioningservices/mgmt/2018-01-22/iothub/dpscertificate.go, services/provisioningservices/mgmt/2018-01-22/iothub/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4684
=> [AutoPR deviceprovisioningservices/resource-manager] typo: Microsoft.Devices

services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/models.go, services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/policies.go
Created to accumulate context: frontdoor/resource-manager
=> [AutoPR] frontdoor/resource-manager

services/preview/provisioningservices/mgmt/2017-08-21-preview/iothub/models.go, services/provisioningservices/mgmt/2017-11-15/iothub/dpscertificate.go, services/provisioningservices/mgmt/2017-11-15/iothub/models.go, services/provisioningservices/mgmt/2018-01-22/iothub/dpscertificate.go, services/provisioningservices/mgmt/2018-01-22/iothub/models.go
Created to accumulate context: deviceprovisioningservices/resource-manager
=> [AutoPR] deviceprovisioningservices/resource-manager

services/cognitiveservices/v2.0/luis/authoring/apps.go, services/cognitiveservices/v2.0/luis/authoring/models.go, services/cognitiveservices/v2.0/luis/runtime/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4656
=> [AutoPR cognitiveservices/data-plane/LUIS/Authoring/cognitiveservices/data-plane/LUIS/Runtime] typo: cognitiveservices/data-plane/LUIS

services/datalake/analytics/2016-11-01-preview/catalog/models.go, services/datalake/analytics/2016-11-01/job/models.go, services/preview/datalake/analytics/2015-10-01-preview/catalog/models.go, services/preview/datalake/analytics/2015-11-01-preview/job/job.go, services/preview/datalake/analytics/2015-11-01-preview/job/models.go, services/preview/datalake/analytics/2016-03-20-preview/job/job.go, services/preview/datalake/analytics/2016-03-20-preview/job/models.go, services/preview/datalake/analytics/2017-09-01-preview/job/models.go, services/preview/datalake/analytics/mgmt/2015-10-01-preview/account/account.go, services/preview/datalake/analytics/mgmt/2015-10-01-preview/account/models.go, services/preview/datalake/store/mgmt/2015-10-01-preview/account/account.go, services/preview/datalake/store/mgmt/2015-10-01-preview/account/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4676
=> [AutoPR datalake-analytics/resource-manager/datalake-store/resource-manager/datalake-analytics/data-plane] typo: Microsoft.DataLakeAnalytics

profiles/latest/containerregistry/mgmt/containerregistry/models.go, profiles/preview/containerregistry/mgmt/containerregistry/models.go, profiles/preview/preview/containerregistry/mgmt/containerregistry/models.go, services/containerregistry/mgmt/2017-03-01/containerregistry/registries.go, services/containerregistry/mgmt/2017-10-01/containerregistry/models.go, services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go, services/containerregistry/mgmt/2017-10-01/containerregistry/replications.go, services/containerregistry/mgmt/2017-10-01/containerregistry/webhooks.go, services/containerregistry/mgmt/2018-09-01/containerregistry/models.go, services/containerregistry/mgmt/2018-09-01/containerregistry/registries.go, services/containerregistry/mgmt/2018-09-01/containerregistry/replications.go, services/containerregistry/mgmt/2018-09-01/containerregistry/runs.go, services/containerregistry/mgmt/2018-09-01/containerregistry/tasks.go, services/containerregistry/mgmt/2018-09-01/containerregistry/webhooks.go, services/preview/containerregistry/mgmt/2017-06-01-preview/containerregistry/models.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/registries.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/replications.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/webhooks.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4662
=> [AutoPR containerregistry/data-plane/containerregistry/resource-manager] typo: Microsoft.ContainerRegistry

services/preview/signalr/mgmt/2018-03-01-preview/signalr/models.go, services/signalr/mgmt/2018-10-01/signalr/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4781
=> [AutoPR signalr/resource-manager] typo: signalr/resource-manager/Microsoft.SignalRService

profiles/preview/preview/storagesync/mgmt/storagesync/models.go, services/preview/storagesync/mgmt/2018-10-01/storagesync/models.go, services/preview/storagesync/mgmt/2018-10-01/storagesync/serverendpoints.go, services/storagesync/mgmt/2018-04-02/storagesync/models.go, services/storagesync/mgmt/2018-04-02/storagesync/serverendpoints.go, services/storagesync/mgmt/2018-07-01/storagesync/models.go, services/storagesync/mgmt/2018-07-01/storagesync/serverendpoints.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4787
=> [AutoPR storagesync/resource-manager] typo: storagesync/resource-manager/Microsoft.StorageSync

services/preview/security/mgmt/2017-08-01-preview/security/alerts.go, services/preview/security/mgmt/2017-08-01-preview/security/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4763
=> [AutoPR security/resource-manager] typo: security/resource-manager/Microsoft.Security

profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go, services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4773
=> [AutoPR hanaonazure/resource-manager] Update HanaOnAzure Swagger to support new SKU: S96

services/preview/operationalinsights/mgmt/2015-11-01-preview/servicemap/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4764
=> [AutoPR service-map/resource-manager] typo: service-map/resource-manager/Microsoft.OperationalInsights

services/preview/security/mgmt/2017-08-01-preview/security/alerts.go, services/preview/security/mgmt/2017-08-01-preview/security/models.go
Created to accumulate context: security/resource-manager
=> [AutoPR] security/resource-manager

services/preview/operationalinsights/mgmt/2015-11-01-preview/servicemap/models.go
Created to accumulate context: service-map/resource-manager
=> [AutoPR] service-map/resource-manager

services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4779
=> [AutoPR servicefabricmesh/resource-manager] typo: servicefabricmesh/resource-manager/Microsoft.ServiceFabricMesh

services/web/mgmt/2016-09-01/web/models.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4813
=> [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.CertificateRegistration

profiles/preview/datafactory/mgmt/datafactory/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4780
=> [AutoPR datafactory/resource-manager] Add support for HDIinsight cluster with Enterprise Serurity Package

services/preview/billing/mgmt/2017-04-24-preview/billing/models.go, services/preview/billing/mgmt/2018-03-01-preview/billing/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4798
=> [AutoPR billing/resource-manager] Microsoft.Billing: Rolling back the incorrect version merged in master branch.

services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/models.go
Created to accumulate context: servicefabricmesh/resource-manager
=> [AutoPR] servicefabricmesh/resource-manager

profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/models.go, services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go
Created to accumulate context: sqlvirtualmachine/resource-manager
=> [AutoPR] sqlvirtualmachine/resource-manager

services/preview/workloadmonitor/mgmt/2018-08-31-preview/workloadmonitor/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4816
=> [AutoPR workloadmonitor/resource-manager] typo: workloadmonitor/resource-manager/Microsoft.WorkloadMonitor

services/storsimple8000series/mgmt/2017-06-01/storsimple/models.go, services/storsimple8000series/mgmt/2017-06-01/storsimple/operations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4807
=> [AutoPR storsimple8000series/resource-manager] typo: storsimple8000series/resource-manager/Microsoft.StorSimple

services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/blueprints.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4792
=> [AutoPR blueprint/resource-manager] Fix typo

services/storage/mgmt/2015-06-15/storage/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4786
=> [AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage

services/machinelearning/mgmt/2017-01-01/webservices/models.go, services/preview/machinelearning/mgmt/2016-05-01-preview/commitmentplans/models.go, services/preview/machinelearning/mgmt/2016-05-01-preview/webservices/models.go, services/preview/machinelearning/mgmt/2016-05-01-preview/webservices/webservices.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4705
=> [AutoPR machinelearning/resource-manager] typo: machinelearning/resource-manager/Microsoft.MachineLearning

services/cognitiveservices/v1.0/face/largefacelist.go, services/cognitiveservices/v1.0/face/list.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4828
=> [AutoPR cognitiveservices/data-plane/Face] typo: cognitiveservices/data-plane/Face

services/batch/2017-05-01.5.0/batch/models.go, services/batch/2018-03-01.6.1/batch/models.go, services/batch/2018-08-01.7.0/batch/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4835
=> [AutoPR batch/data-plane] typo: batch/data-plane/Microsoft.Batch

services/storsimple8000series/mgmt/2017-06-01/storsimple/models.go, services/storsimple8000series/mgmt/2017-06-01/storsimple/operations.go
Created to accumulate context: storsimple8000series/resource-manager
=> [AutoPR] storsimple8000series/resource-manager

services/machinelearning/mgmt/2017-01-01/webservices/models.go, services/preview/machinelearning/mgmt/2016-05-01-preview/commitmentplans/models.go, services/preview/machinelearning/mgmt/2016-05-01-preview/webservices/models.go, services/preview/machinelearning/mgmt/2016-05-01-preview/webservices/webservices.go
Created to accumulate context: machinelearning/resource-manager
=> [AutoPR] machinelearning/resource-manager

services/cognitiveservices/v1.0/face/largefacelist.go, services/cognitiveservices/v1.0/face/list.go
Created to accumulate context: cognitiveservices/data-plane/Face
=> [AutoPR] cognitiveservices/data-plane/Face

services/preview/subscription/mgmt/2017-11-01-preview/subscription/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4809
=> [AutoPR subscription/resource-manager] typo: subscription/resource-manager/Microsoft.Subscription

services/cognitiveservices/v4.0/qnamaker/models.go
typo: cognitiveservices/data-plane/QnAMaker
- knowlegebases -> knowledgebases
=> Generated from 739894c24e928412aa4c219485762d0382590d93 (#3465)

profiles/preview/servicefabric/servicefabric/models.go, services/servicefabric/6.2/servicefabric/models.go, services/servicefabric/6.3/servicefabric/models.go, services/servicefabric/6.4/servicefabric/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4834
=> [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric

services/powerbidedicated/mgmt/2017-10-01/powerbidedicated/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4728
=> [AutoPR powerbidedicated/resource-manager] typo: powerbidedicated/resource-manager/Microsoft.PowerBIdedicated

services/cognitiveservices/v1.2/customvision/training/client.go, services/cognitiveservices/v1.2/customvision/training/models.go, services/cognitiveservices/v2.1/customvision/training/client.go, services/cognitiveservices/v2.1/customvision/training/models.go, services/cognitiveservices/v2.2/customvision/training/client.go, services/cognitiveservices/v2.2/customvision/training/models.go
Created to accumulate context: cognitiveservices/data-plane/CustomVision/Training
=> [AutoPR] cognitiveservices/data-plane/CustomVision/Training

services/powerbidedicated/mgmt/2017-10-01/powerbidedicated/models.go
Created to accumulate context: powerbidedicated/resource-manager
=> [AutoPR] powerbidedicated/resource-manager

services/preview/cognitiveservices/v1.0/visualsearch/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4829
=> [AutoPR cognitiveservices/data-plane/VisualSearch] typo: cognitiveservices/data-plane/VisualSearch

profiles/preview/preview/containerservice/mgmt/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/containerserviceapi/interfaces.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/openshiftmanagedclusters.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/containerserviceapi/interfaces.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/openshiftmanagedclusters.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4597
=> [AutoPR containerservices/resource-manager] ContainerServices - OpenShift - Add new routes and update

services/apimanagement/mgmt/2017-03-01/apimanagement/apidiagnosticlogger.go, services/apimanagement/mgmt/2017-03-01/apimanagement/apiissueattachments.go, services/apimanagement/mgmt/2017-03-01/apimanagement/apiissuecomments.go, services/apimanagement/mgmt/2017-03-01/apimanagement/apiissues.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4881
=> [AutoPR apimanagement/resource-manager] typo: apimanagement/resource-manager/Microsoft.ApiManagement

profiles/latest/containerregistry/mgmt/containerregistry/models.go, profiles/preview/containerregistry/mgmt/containerregistry/models.go, profiles/preview/preview/containerregistry/mgmt/containerregistry/models.go, services/containerregistry/mgmt/2017-10-01/containerregistry/models.go, services/containerregistry/mgmt/2018-09-01/containerregistry/models.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4895
=> [AutoPR containerregistry/resource-manager] [ACR] Add IP rules

services/streamanalytics/mgmt/2016-03-01/streamanalytics/functions.go, services/streamanalytics/mgmt/2016-03-01/streamanalytics/inputs.go, services/streamanalytics/mgmt/2016-03-01/streamanalytics/models.go, services/streamanalytics/mgmt/2016-03-01/streamanalytics/outputs.go, services/streamanalytics/mgmt/2016-03-01/streamanalytics/streamingjobs.go, services/streamanalytics/mgmt/2016-03-01/streamanalytics/transformations.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4808
=> [AutoPR streamanalytics/resource-manager] typo: streamanalytics/resource-manager/Microsoft.StreamAnalytics

services/preview/sql/mgmt/2017-03-01-preview/sql/manageddatabases.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4907
=> [AutoPR sql/resource-manager] Updating managed database swagger

services/streamanalytics/mgmt/2016-03-01/streamanalytics/functions.go, services/streamanalytics/mgmt/2016-03-01/streamanalytics/inputs.go, services/streamanalytics/mgmt/2016-03-01/streamanalytics/models.go, services/streamanalytics/mgmt/2016-03-01/streamanalytics/outputs.go, services/streamanalytics/mgmt/2016-03-01/streamanalytics/streamingjobs.go, services/streamanalytics/mgmt/2016-03-01/streamanalytics/transformations.go
Created to accumulate context: streamanalytics/resource-manager
=> [AutoPR] streamanalytics/resource-manager

services/web/mgmt/2016-09-01/web/models.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4814
=> [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.DomainRegistration

profiles/preview/preview/hdinsight/hdinsight/models.go, services/preview/hdinsight/2018-11-01-preview/hdinsight/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4906
=> [AutoPR hdinsight/data-plane] [HDInsight] - Add FINISHING to application state

profiles/preview/preview/hdinsight/hdinsight/models.go, services/preview/hdinsight/2018-11-01-preview/hdinsight/models.go
Created to accumulate context: hdinsight/data-plane
=> [AutoPR] hdinsight/data-plane

services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addomainservicemembers.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservice.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicemembers.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservices.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicesreplicationstatus.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicesservicemembers.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicesuserpreference.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/alerts.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/client.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/configuration.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/dimensions.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/operations.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/reports.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/service.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/servicemembers.go, services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/services.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4582
=> [AutoPR adhybridhealthservice/resource-manager] typo: adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService

services/preview/authorization/mgmt/2017-10-01-preview/authorization/models.go, services/preview/authorization/mgmt/2018-01-01-preview/authorization/models.go, services/preview/authorization/mgmt/2018-09-01-preview/authorization/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4886
=> [AutoPR authorization/resource-manager] typo: authorization/resource-manager/Microsoft.Authorization

services/preview/sql/mgmt/2015-05-01-preview/sql/databases.go, services/preview/sql/mgmt/2015-05-01-preview/sql/models.go, services/preview/sql/mgmt/2017-03-01-preview/sql/databases.go, services/preview/sql/mgmt/2017-03-01-preview/sql/jobexecutions.go, services/preview/sql/mgmt/2017-03-01-preview/sql/manageddatabases.go, services/preview/sql/mgmt/2017-03-01-preview/sql/models.go, services/sql/mgmt/2014-04-01/sql/databases.go, services/sql/mgmt/2014-04-01/sql/models.go, services/sql/mgmt/2014-04-01/sql/recommendedelasticpools.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4783
=> [AutoPR sql/resource-manager] typo: sql/resource-manager/Microsoft.Sql

services/preview/trafficmanager/mgmt/2017-09-01-preview/trafficmanager/models.go, services/trafficmanager/mgmt/2015-11-01/trafficmanager/models.go, services/trafficmanager/mgmt/2017-03-01/trafficmanager/models.go, services/trafficmanager/mgmt/2017-05-01/trafficmanager/models.go, services/trafficmanager/mgmt/2018-02-01/trafficmanager/models.go, services/trafficmanager/mgmt/2018-03-01/trafficmanager/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4812
=> [AutoPR trafficmanager/resource-manager] typo: trafficmanager/resource-manager/Microsoft.Network

services/storsimple1200series/mgmt/2016-10-01/storsimple/devices.go, services/storsimple1200series/mgmt/2016-10-01/storsimple/iscsidisks.go, services/storsimple1200series/mgmt/2016-10-01/storsimple/iscsiservers.go, services/storsimple1200series/mgmt/2016-10-01/storsimple/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4806
=> [AutoPR storSimple1200Series/resource-manager] typo: storSimple1200Series/resource-manager/Microsoft.StorSimple

profiles/latest/containerregistry/mgmt/containerregistry/models.go, profiles/preview/containerregistry/mgmt/containerregistry/models.go, profiles/preview/preview/containerregistry/mgmt/containerregistry/models.go, services/containerregistry/mgmt/2017-10-01/containerregistry/models.go, services/containerregistry/mgmt/2018-09-01/containerregistry/models.go, services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4820
=> [AutoPR containerregistry/resource-manager] [ACR] Add Helm actions to webhook

services/preview/resources/mgmt/2015-10-01-preview/policy/assignments.go, services/preview/resources/mgmt/2016-09-01-preview/managedapplications/models.go, services/preview/resources/mgmt/2017-06-01-preview/policy/assignments.go, services/preview/resources/mgmt/2017-06-01-preview/policy/models.go, services/resources/mgmt/2015-11-01/resources/models.go, services/resources/mgmt/2016-02-01/resources/models.go, services/resources/mgmt/2016-04-01/policy/assignments.go, services/resources/mgmt/2016-07-01/resources/models.go, services/resources/mgmt/2016-09-01/links/resourcelinks.go, services/resources/mgmt/2016-09-01/resources/models.go, services/resources/mgmt/2016-09-01/resources/resources.go, services/resources/mgmt/2016-12-01/policy/assignments.go, services/resources/mgmt/2017-05-10/resources/models.go, services/resources/mgmt/2017-09-01/managedapplications/models.go, services/resources/mgmt/2018-02-01/resources/models.go, services/resources/mgmt/2018-03-01/policy/models.go, services/resources/mgmt/2018-05-01/policy/models.go, services/resources/mgmt/2018-05-01/resources/models.go, services/resources/mgmt/2018-06-01/managedapplications/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4760
=> [AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Solutions

profiles/latest/cognitiveservices/mgmt/cognitiveservices/models.go, profiles/preview/cognitiveservices/mgmt/cognitiveservices/models.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/accounts.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go, services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4913
=> [AutoPR cognitiveservices/resource-manager] Change Kind and SKU name to string (from enum).

services/containerservice/mgmt/2017-07-01/containerservice/models.go, services/containerservice/mgmt/2017-08-31/containerservice/models.go, services/containerservice/mgmt/2017-09-30/containerservice/containerservices.go, services/containerservice/mgmt/2017-09-30/containerservice/models.go, services/containerservice/mgmt/2018-03-31/containerservice/containerservices.go, services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go, services/containerservice/mgmt/2018-03-31/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/containerservices.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/managedclusters.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/openshiftmanagedclusters.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/containerservices.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/managedclusters.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go, services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/openshiftmanagedclusters.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4663
=> [AutoPR containerservices/resource-manager] typo: containerservice/Microsoft.ContainerService

profiles/preview/datamigration/mgmt/datamigration/models.go, profiles/preview/preview/datamigration/mgmt/datamigration/models.go, services/datamigration/mgmt/2018-04-19/datamigration/client.go, services/datamigration/mgmt/2018-04-19/datamigration/models.go, services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4627
=> [AutoPR datamigration/resource-manager] Adding sync scenarios to public preview swagger

services/labservices/mgmt/2018-10-15/labservices/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4926
=> [AutoPR labservices/resource-manager] typo: labservices/resource-manager/Microsoft.LabServices

services/labservices/mgmt/2018-10-15/labservices/models.go
Created to accumulate context: labservices/resource-manager
=> [AutoPR] labservices/resource-manager

services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4928
=> [AutoPR sqlvirtualmachine/resource-manager] typo: sqlvirtualmachine/resource-manager/Microsoft.SqlVirtualMachine

services/preview/apimanagement/ctrl/2017-03-01/apimanagement/models.go, services/preview/apimanagement/ctrl/2017-03-01/apimanagement/property.go, services/preview/apimanagement/ctrl/2017-03-01/apimanagement/reports.go, services/preview/apimanagement/ctrl/2017-03-01/apimanagement/subscription.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4882
=> [AutoPR apimanagement/control-plane] typo: apimanagement/control-plane/Microsoft.ApiManagement

services/preview/web/mgmt/2015-08-01-preview/web/models.go, services/web/mgmt/2016-09-01/web/models.go, services/web/mgmt/2018-02-01/web/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4919
=> [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web

services/datamigration/mgmt/2018-04-19/datamigration/models.go
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4924
=> [AutoPR datamigration/resource-manager] typo: datamigration/resource-manager/Microsoft.DataMigration
